"use client"

import{useCallback,useEffect,useMemo,useState}from"react"
import{isoDate}from"../../core/formatters"
import{activeAccountingProperty,closeAccountingPeriod,downloadAccountingCsv,issueArcaFinanceDocument,loadAccountingCenter,recordAccountingExport,reopenAccountingPeriod,saveAccountingExpense,voidAccountingExpense}from"../../services/accounting"
import{AccountsTab,InvoicesTab,JournalTab,LedgerTab,TrialTab}from"./AccountingCoreTabs"
import{CfoTab,TaxTab}from"./AccountingTaxCfoTabs"
import{ExpensesTab,ExportsTab}from"./AccountingExpenseExportTabs"
import{DocumentModal,ExpenseModal,FiscalModal}from"./AccountingModals"
import s from"./accounting-premium.module.css"

const TABS=[["accounts","Cuentas"],["invoices","Facturas"],["journal","Diario"],["ledger","Mayor"],["trial","Balance"],["tax","Impuestos"],["cfo","CFO"],["expenses","Gastos"],["exports","Exportaciones"]]
const ACCOUNT_KIND={asset:"Activo",liability:"Pasivo",equity:"Patrimonio",revenue:"Ingresos",expense:"Gastos",tax:"Impuestos"}
const num=value=>Number(value||0)
const monthKey=value=>String(value||"").slice(0,7)
const todayMonth=()=>isoDate().slice(0,7)
const netPayment=p=>Math.max(0,num(p.monto)-num(p.refunded_amount))
const activePayment=p=>!["anulado","cancelado","reembolsado","refunded"].includes(String(p.estado||"").toLowerCase())
const monthBounds=ym=>{const[y,m]=String(ym).split("-").map(Number),start=`${y}-${String(m).padStart(2,"0")}-01`,endDate=new Date(y,m,0),end=`${y}-${String(m).padStart(2,"0")}-${String(endDate.getDate()).padStart(2,"0")}`;return{year:y,month:m,start,end}}
const inRange=(value,start,end)=>{const d=String(value||"").slice(0,10);return d>=start&&d<=end}
function reservationCharges(r){const lines=[],stay=Math.max(0,num(r.tarifa_noche)*Math.max(0,num(r.noches)));if(stay>0)lines.push({label:`Alojamiento · ${r.noches||0} noche(s)`,amount:stay});if(num(r.cochera_total)>0)lines.push({label:"Cochera",amount:num(r.cochera_total)});if(num(r.mascotas_total)>0)lines.push({label:"Mascotas",amount:num(r.mascotas_total)});if(num(r.early_checkin_importe)>0)lines.push({label:"Early check-in",amount:num(r.early_checkin_importe)});if(num(r.late_checkout_importe)>0)lines.push({label:"Late check-out",amount:num(r.late_checkout_importe)});if(num(r.extra)>0)lines.push({label:r.extra_descripcion||"Extras",amount:num(r.extra)});for(const item of Array.isArray(r.servicios)?r.servicios:[]){const amount=num(item.total??item.importe??item.price);if(amount>0)lines.push({label:item.name||item.nombre||item.descripcion||"Servicio",amount})}return lines}

export default function AccountingPremium({documents:initialDocuments=[],reservations=[],partners=[],groups=[],canManage,onSave,onIssue}){
  const[propertyId]=useState(()=>activeAccountingProperty()||initialDocuments[0]?.property_id||reservations[0]?.property_id||partners[0]?.property_id||groups[0]?.property_id||""),[tab,setTab]=useState("accounts"),[period,setPeriod]=useState(todayMonth()),[data,setData]=useState({accounts:[],expenses:[],periods:[],exports:[],ledger:[],documents:initialDocuments,payments:[],arcaSettings:null,arcaRequests:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(""),[docEditor,setDocEditor]=useState(null),[expenseEditor,setExpenseEditor]=useState(null),[fiscal,setFiscal]=useState(null),[accountCode,setAccountCode]=useState("1101"),[selectedReservation,setSelectedReservation]=useState("")
  const bounds=useMemo(()=>monthBounds(period),[period])
  const reload=useCallback(async()=>{if(!propertyId){setLoading(false);setError("No pude determinar la propiedad activa.");return}setLoading(true);setError("");try{setData(await loadAccountingCenter({propertyId}))}catch(e){setError(e.message||"No se pudo cargar Contabilidad.")}finally{setLoading(false)}},[propertyId])
  useEffect(()=>{reload()},[reload])
  const run=async(key,fn)=>{if(busy)return;setBusy(key);setError("");try{const result=await fn();await reload();return result}catch(e){setError(e.message||"No se pudo completar la operación.")}finally{setBusy("")}}
  const docs=data.documents?.length?data.documents:initialDocuments,payments=data.payments||[],periodRows=data.periods||[],closed=periodRows.find(p=>num(p.period_year)===bounds.year&&num(p.period_month)===bounds.month)?.status==="closed",periodLedger=(data.ledger||[]).filter(r=>inRange(r.entry_date,bounds.start,bounds.end)),arsLedger=periodLedger.filter(r=>String(r.currency||"ARS").toUpperCase()==="ARS"),reservationMap=useMemo(()=>new Map(reservations.map(r=>[String(r.id),r])),[reservations])
  const journal=useMemo(()=>{const map=new Map();for(const line of periodLedger){const key=line.entry_key||`${line.source_type}:${line.source_id}`;if(!map.has(key))map.set(key,{key,date:line.entry_date,reference:line.reference,source:line.source_type,currency:line.currency,lines:[]});map.get(key).lines.push(line)}return[...map.values()].sort((a,b)=>String(b.date).localeCompare(String(a.date)))},[periodLedger])
  const trial=useMemo(()=>{const map=new Map();for(const line of periodLedger){const key=`${line.currency}:${line.account_code}`;if(!map.has(key))map.set(key,{currency:line.currency,code:line.account_code,name:line.account_name,debit:0,credit:0});const row=map.get(key);row.debit+=num(line.debit);row.credit+=num(line.credit)}return[...map.values()].sort((a,b)=>String(a.currency).localeCompare(String(b.currency))||String(a.code).localeCompare(String(b.code)))},[periodLedger])
  const majorLines=useMemo(()=>periodLedger.filter(x=>String(x.account_code)===String(accountCode)).sort((a,b)=>String(a.entry_date).localeCompare(String(b.entry_date))),[periodLedger,accountCode]),majorWithBalance=useMemo(()=>{let balance=0;return majorLines.map(x=>{balance+=num(x.debit)-num(x.credit);return{...x,balance}})},[majorLines])
  const monthlyDocs=docs.filter(d=>d.status==="issued"&&String(d.currency||"ARS").toUpperCase()==="ARS"&&inRange(d.issued_at||d.created_at,bounds.start,bounds.end)),monthlyPayments=payments.filter(p=>activePayment(p)&&String(p.moneda||"ARS").toUpperCase()==="ARS"&&inRange(p.created_at,bounds.start,bounds.end)),monthlyExpenses=(data.expenses||[]).filter(e=>e.status==="posted"&&String(e.currency||"ARS").toUpperCase()==="ARS"&&inRange(e.occurred_on,bounds.start,bounds.end)),invoiced=monthlyDocs.reduce((a,x)=>a+(x.document_type==="credit_note"?-num(x.total):num(x.total)),0),collected=monthlyPayments.reduce((a,x)=>a+netPayment(x),0),expenseTotal=monthlyExpenses.reduce((a,x)=>a+num(x.amount),0),production=reservations.filter(r=>String(r.moneda||"ARS").toUpperCase()==="ARS"&&inRange(r.fecha_entrada,bounds.start,bounds.end)&&r.estado!=="cancelada"&&!r.no_show).reduce((a,x)=>a+num(x.precio_total),0),margin=invoiced-expenseTotal
  const vatOutput=arsLedger.filter(x=>x.account_code==="2101").reduce((a,x)=>a+num(x.credit)-num(x.debit),0),vatInput=arsLedger.filter(x=>x.account_code==="1301").reduce((a,x)=>a+num(x.debit)-num(x.credit),0),arsDifference=arsLedger.reduce((a,x)=>a+num(x.debit)-num(x.credit),0)
  const selected=reservations.find(r=>String(r.id)===String(selectedReservation))||reservations[0]||null,selectedPaid=selected?payments.filter(p=>String(p.reserva_id)===String(selected.id)&&activePayment(p)).reduce((a,p)=>a+netPayment(p),0):0,selectedCharges=selected?reservationCharges(selected):[]
  const supplierTop=useMemo(()=>{const map=new Map();monthlyExpenses.forEach(e=>{const key=e.supplier_name||"Sin proveedor";map.set(key,(map.get(key)||0)+num(e.amount))});return[...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5)},[monthlyExpenses])
  const trend=useMemo(()=>{const result=[];for(let i=5;i>=0;i--){const d=new Date(bounds.year,bounds.month-1-i,1),ym=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`,inv=docs.filter(x=>x.status==="issued"&&String(x.currency||"ARS").toUpperCase()==="ARS"&&monthKey(x.issued_at||x.created_at)===ym).reduce((a,x)=>a+(x.document_type==="credit_note"?-num(x.total):num(x.total)),0),exp=(data.expenses||[]).filter(x=>x.status==="posted"&&String(x.currency||"ARS").toUpperCase()==="ARS"&&monthKey(x.occurred_on)===ym).reduce((a,x)=>a+num(x.amount),0);result.push({ym,label:d.toLocaleDateString("es-AR",{month:"short"}),invoiced:inv,expenses:exp,margin:inv-exp})}return result},[bounds.year,bounds.month,docs,data.expenses]),trendMax=Math.max(1,...trend.map(x=>Math.max(x.invoiced,x.expenses)))

  function newDocument(){setDocEditor({document_type:"invoice_draft",reservation_id:selected?.id||"",group_id:"",partner_id:"",status:"draft",currency:"ARS",tax:0,balance:0,billing_to:{name:selected?.nombre_huesped||"",tax_id:selected?.dni_huesped||""},items:selected?[{description:`Alojamiento ${selected.fecha_entrada} → ${selected.fecha_salida}`,quantity:1,unit_price:num(selected.precio_total),total:num(selected.precio_total)}]:[{description:"Alojamiento",quantity:1,unit_price:0,total:0}],notes:""})}
  async function saveDocument(draft){const result=await run("save-doc",()=>onSave?.(draft));if(result)setDocEditor(null)}
  async function issueInternal(doc){await run(`issue-${doc.id}`,()=>onIssue?.(doc))}
  function openFiscal(doc){const r=reservationMap.get(String(doc.reservation_id)),cfg=data.arcaSettings||{},type=num(cfg.default_receipt_type||11);setFiscal({doc,reservation:r,draft:{receipt_type:type,recipient_doc_type:doc.billing_to?.tax_id?80:99,recipient_doc_number:doc.billing_to?.tax_id||r?.dni_huesped||"",recipient_iva_condition:"consumidor_final",net_amount:type===11?num(doc.total):Math.max(0,num(doc.total)-num(doc.tax)),vat_amount:type===11?0:num(doc.tax),vat_rate_id:5,exchange_rate:r?.tipo_cambio||1,exempt_amount:0,untaxed_amount:0}})}
  async function emitFiscal(){if(!fiscal)return;const result=await run("arca",()=>issueArcaFinanceDocument({propertyId,document:fiscal.doc,reservation:fiscal.reservation,arcaSettings:data.arcaSettings,fiscal:fiscal.draft}));if(result)setFiscal(null)}
  function newExpense(){const account=(data.accounts||[]).find(a=>a.system_key==="operating_expense");setExpenseEditor({occurred_on:isoDate(),supplier_name:"",supplier_tax_id:"",concept:"",category:"Operativo",account_id:account?.id||"",amount:"",tax_amount:0,currency:"ARS",payment_method:"Transferencia",document_number:"",reference:"",notes:""})}
  async function saveExpense(){const result=await run("expense",()=>saveAccountingExpense({propertyId,draft:expenseEditor}));if(result)setExpenseEditor(null)}
  async function togglePeriod(){if(closed)await run("period",()=>reopenAccountingPeriod({propertyId,year:bounds.year,month:bounds.month}));else await run("period",()=>closeAccountingPeriod({propertyId,year:bounds.year,month:bounds.month,notes:"Cierre desde Contabilidad"}))}
  async function exportCsv(target="generic_csv"){const file=`habitacion-llena-contabilidad-${period}-${target}.csv`;downloadAccountingCsv(periodLedger,file);await run("export",()=>recordAccountingExport({propertyId,start:bounds.start,end:bounds.end,target,format:"csv",rowsCount:periodLedger.length,fileName:file,metadata:{mode:"import_file",direct_api:false}}))}

  if(loading)return <div className={s.loading}>Preparando libros contables…</div>
  return <div className={s.root}>
    <section className={s.hero}><div><small>CONTABILIDAD · ARGENTINA</small><h2>De la reserva al asiento, sin volver a cargar nada.</h2><p>Cuenta del huésped, cobros, documentos, ARCA, caja, gastos y libros contables nacen de los movimientos reales del hotel.</p></div><div className={s.heroActions}><label><span>Período</span><input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label><button type="button" data-closed={closed} onClick={togglePeriod} disabled={busy==="period"}>{closed?"Reabrir período":"Cerrar período"}</button></div></section>
    {error&&<div className={s.error}>{error}</div>}
    <nav className={s.tabs}>{TABS.map(([id,label])=><button type="button" key={id} className={tab===id?s.active:""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {tab==="accounts"&&<AccountsTab reservations={reservations} selected={selected} setSelectedReservation={setSelectedReservation} selectedCharges={selectedCharges} selectedPaid={selectedPaid} payments={payments} activePayment={activePayment} netPayment={netPayment} docs={docs} journal={journal}/>} 
    {tab==="invoices"&&<InvoicesTab docs={docs} reservationMap={reservationMap} partners={partners} groups={groups} arcaRequests={data.arcaRequests||[]} arcaEnabled={!!data.arcaSettings?.enabled} canManage={canManage} onNew={newDocument} onEdit={setDocEditor} onIssueInternal={issueInternal} onFiscal={openFiscal}/>} 
    {tab==="journal"&&<JournalTab journal={journal}/>} {tab==="ledger"&&<LedgerTab accounts={data.accounts||[]} accountCode={accountCode} setAccountCode={setAccountCode} majorWithBalance={majorWithBalance}/>} {tab==="trial"&&<TrialTab trial={trial} accounts={data.accounts||[]} arsDifference={arsDifference} accountKind={ACCOUNT_KIND}/>} 
    {tab==="tax"&&<TaxTab settings={data.arcaSettings} vatOutput={vatOutput} vatInput={vatInput} arcaRequests={data.arcaRequests||[]} bounds={bounds}/>} {tab==="cfo"&&<CfoTab production={production} invoiced={invoiced} collected={collected} expenseTotal={expenseTotal} margin={margin} trend={trend} trendMax={trendMax} supplierTop={supplierTop}/>} 
    {tab==="expenses"&&<ExpensesTab expenses={data.expenses||[]} accounts={data.accounts||[]} bounds={bounds} canManage={canManage} onNew={newExpense} onEdit={setExpenseEditor} onVoid={e=>run(`void-${e.id}`,()=>voidAccountingExpense({propertyId,id:e.id}))}/>} {tab==="exports"&&<ExportsTab exports={data.exports||[]} bounds={bounds} busy={busy} onExport={exportCsv}/>} 
    {docEditor&&<DocumentModal draft={docEditor} setDraft={setDocEditor} reservations={reservations} partners={partners} groups={groups} busy={busy} onClose={()=>setDocEditor(null)} onSave={saveDocument}/>} {expenseEditor&&<ExpenseModal draft={expenseEditor} setDraft={setExpenseEditor} accounts={data.accounts||[]} busy={busy} onClose={()=>setExpenseEditor(null)} onSave={saveExpense}/>} {fiscal&&<FiscalModal state={fiscal} setState={setFiscal} settings={data.arcaSettings} busy={busy} onClose={()=>setFiscal(null)} onIssue={emitFiscal}/>} 
  </div>
}
