"use client"

import{money}from"../../core/formatters"
import s from"./accounting-premium.module.css"

const num=value=>Number(value||0)
const fmt=n=>money(num(n),"ARS")
const statusLabel=value=>({draft:"Borrador",issued:"Emitido",authorized:"Autorizado",rejected:"Rechazado",error:"Error",pending:"Pendiente"}[value]||String(value||"—"))
function Empty({title,text}){return <div className={s.empty}><b>{title}</b><span>{text}</span></div>}

export function TaxTab({settings,vatOutput,vatInput,arcaRequests,bounds}){const rows=arcaRequests.filter(x=>String(x.created_at||"").slice(0,10)>=bounds.start&&String(x.created_at||"").slice(0,10)<=bounds.end);return <section><div className={s.taxHero}><div><small>ARCA · IMPUESTOS</small><h3>{settings?.enabled?"Facturación electrónica habilitada":"ARCA todavía no está configurado"}</h3><p>{settings?.enabled?`${settings.legal_name||"Emisor"} · CUIT ${settings.tax_id||"—"} · PV ${settings.point_of_sale||"—"} · ${settings.environment||""}`:"Configurá certificado, CUIT y punto de venta antes de emitir comprobantes fiscales."}</p></div><div><span><small>IVA débito</small><b>{fmt(vatOutput)}</b></span><span><small>IVA crédito</small><b>{fmt(vatInput)}</b></span><span><small>Posición</small><b>{fmt(vatOutput-vatInput)}</b></span></div></div><div className={s.tableWrap}><table><thead><tr><th>Fecha</th><th>Documento</th><th>Tipo</th><th>Importe</th><th>Estado</th><th>CAE</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{String(x.created_at).slice(0,10)}</td><td>{x.finance_document_id||x.reservation_id||"—"}</td><td>{x.receipt_type===1?"Factura A":x.receipt_type===6?"Factura B":x.receipt_type===11?"Factura C":x.receipt_type}</td><td>{money(x.amount,x.currency)}</td><td>{statusLabel(x.status)}</td><td>{x.cae||"—"}</td></tr>)}</tbody></table>{!rows.length&&<Empty title="Sin comprobantes ARCA en el período" text="La tabla se completa con cada solicitud fiscal real."/>}</div></section>}

export function CfoTab({production,invoiced,collected,expenseTotal,margin,trend,trendMax,supplierTop}){return <section><div className={s.sectionTitle}><div><small>CUADRO DE MANDO CFO</small><h3>Producción, facturación, gasto y margen</h3></div></div><div className={s.metricGrid}><article><small>Producción</small><b>{fmt(production)}</b><span>Reservas con llegada en el período</span></article><article><small>Facturado</small><b>{fmt(invoiced)}</b><span>Documentos emitidos</span></article><article><small>Cobrado</small><b>{fmt(collected)}</b><span>Pagos confirmados</span></article><article><small>Gastos</small><b>{fmt(expenseTotal)}</b><span>Gastos contabilizados</span></article><article data-positive={margin>=0}><small>Margen</small><b>{fmt(margin)}</b><span>Facturado menos gastos</span></article></div><div className={s.cfoGrid}><div className={s.trend}><small>EVOLUCIÓN · 6 MESES</small><h3>Facturación vs gastos</h3><div className={s.bars}>{trend.map(x=><div key={x.ym}><div className={s.barPair}><i style={{height:`${Math.max(2,(x.invoiced/trendMax)*100)}%`}}/><i data-expense style={{height:`${Math.max(2,(x.expenses/trendMax)*100)}%`}}/></div><span>{x.label}</span><small>{fmt(x.margin)}</small></div>)}</div></div><aside className={s.suppliers}><small>TOP PROVEEDORES</small><h3>Gasto del período</h3>{supplierTop.map(([name,value])=><div key={name}><span>{name}</span><b>{fmt(value)}</b></div>)}{!supplierTop.length&&<Empty title="Sin gastos cargados" text="El ranking aparece al registrar proveedores."/>}</aside></div></section>}
