"use client"

import{useEffect,useState}from"react"
import{money}from"../../core/formatters"
import{useHotelSession}from"../../hooks/useHotelSession"
import{loadFinanceContext}from"../../services/financeContext"
import PaymentsPremium from"./PaymentsPremium"
import AccountingGateway from"./AccountingGateway"
import ReportsPremium from"./ReportsPremium"
import ui from"../../v2.module.css"
import b from"../business.module.css"

function Modal({title,onClose,onSubmit,children}){return <div className={ui.shade} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className={ui.modal} onSubmit={onSubmit}><header><h3>{title}</h3><button type="button" onClick={onClose}>×</button></header>{children}</form></div>}
function Field({label,wide=false,children}){return <label className={wide?ui.wide:""}><span>{label}</span>{children}</label>}

export function CashView({sessions=[],movements=[],reservations=[],canManage,onOpen,onMovement,onClose}){
  const session=useHotelSession(),[finance,setFinance]=useState(null),[openDraft,setOpenDraft]=useState(null),[moveDraft,setMoveDraft]=useState(null),[closeDraft,setCloseDraft]=useState(null)
  useEffect(()=>{let active=true;if(session.loading||!session.propertyId)return;loadFinanceContext({propertyId:session.propertyId}).then(value=>active&&setFinance(value)).catch(()=>{});return()=>{active=false}},[session.loading,session.propertyId])
  const open=sessions.find(x=>x.status==="open"),currency=finance?.currency||reservations.find(r=>r.moneda)?.moneda||"ARS",locale=finance?.locale||"es-AR",cashMethods=finance?.cashMethods?.length?finance.cashMethods:["Efectivo","Transferencia","Débito","Crédito"],sessionMoves=movements.filter(x=>String(x.session_id)===String(open?.id)),baseMoves=sessionMoves.filter(x=>String(x.currency||currency).toUpperCase()===String(currency).toUpperCase()),foreignMoves=sessionMoves.length-baseMoves.length,net=baseMoves.reduce((a,x)=>a+(x.movement_type==="expense"?-Number(x.amount||0):Number(x.amount||0)),0),expected=Number(open?.opening_amount||0)+net
  return <div className={ui.content}>
    <PaymentsPremium reservations={reservations} sessions={sessions} movements={movements}/>
    <div className={ui.editorial}><div><small>MONEDERO & CAJA · {finance?.name?.toUpperCase()||"HOTEL"}</small><h2>El efectivo del turno también queda trazado.</h2><p>La caja física cierra en {currency}, moneda base de la propiedad. Cobros digitales o referencias en otras monedas se trazan por separado y no alteran el esperado de caja.</p></div>{canManage&&!open&&<button onClick={()=>setOpenDraft({openingAmount:0,notes:""})}>Abrir caja</button>}</div>
    {open?<><section className={b.cashHero}><div><small>CAJA ABIERTA</small><h3>Desde {new Date(open.opened_at).toLocaleString(locale)}</h3><p>Fondo inicial {money(open.opening_amount,currency,locale)} · {baseMoves.length} movimientos en {currency}{foreignMoves?` · ${foreignMoves} fuera de moneda base`:""}</p></div><div><span>Esperado · {currency}</span><b>{money(expected,currency,locale)}</b></div><div className={ui.inline}><button onClick={()=>setMoveDraft({movementType:"income",method:cashMethods[0]||"Efectivo",amount:"",concept:"",reference:"",currency,reservationId:""})}>＋ Movimiento</button><button onClick={()=>setCloseDraft({closingAmount:expected,notes:""})}>Cerrar caja</button></div></section><div className={ui.tableWrap}><table><thead><tr><th>Hora</th><th>Tipo</th><th>Concepto</th><th>Medio</th><th>Reserva</th><th>Monto</th></tr></thead><tbody>{sessionMoves.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleTimeString(locale,{hour:"2-digit",minute:"2-digit"})}</td><td>{x.movement_type}</td><td>{x.concept}</td><td>{x.method}</td><td>{x.reservation_id||"—"}</td><td>{x.movement_type==="expense"?"− ":"+ "}{money(x.amount,x.currency||currency,locale)}</td></tr>)}</tbody></table></div>{foreignMoves>0&&<div className={ui.notice}>Los movimientos en moneda distinta de {currency} quedan visibles en la trazabilidad, pero no se suman al conteo esperado de esta caja.</div>}</>:<section className={ui.placeholder}><div><span>CAJA CERRADA</span><h2>No hay turno abierto.</h2><p>Abrí una caja para registrar ingresos y egresos operativos. Los cobros digitales no dependen de que exista una caja abierta.</p></div></section>}
    {openDraft&&<Modal title="Abrir caja" onClose={()=>setOpenDraft(null)} onSubmit={async e=>{e.preventDefault();await onOpen?.(openDraft);setOpenDraft(null)}}><div className={ui.fieldGrid}><Field label={`Fondo inicial · ${currency}`}><input autoFocus type="number" min="0" value={openDraft.openingAmount} onChange={e=>setOpenDraft(x=>({...x,openingAmount:e.target.value}))}/></Field><Field label="Notas" wide><textarea value={openDraft.notes} onChange={e=>setOpenDraft(x=>({...x,notes:e.target.value}))}/></Field></div><footer><button type="button" onClick={()=>setOpenDraft(null)}>Cancelar</button><button>Abrir caja</button></footer></Modal>}
    {moveDraft&&<Modal title="Registrar movimiento" onClose={()=>setMoveDraft(null)} onSubmit={async e=>{e.preventDefault();await onMovement?.({...moveDraft,currency,sessionId:open?.id});setMoveDraft(null)}}><div className={ui.fieldGrid}><Field label="Tipo"><select value={moveDraft.movementType} onChange={e=>setMoveDraft(x=>({...x,movementType:e.target.value}))}><option value="income">Ingreso</option><option value="expense">Egreso</option></select></Field><Field label={`Monto · ${currency}`}><input autoFocus type="number" min=".01" step=".01" value={moveDraft.amount} onChange={e=>setMoveDraft(x=>({...x,amount:e.target.value}))}/></Field><Field label="Medio"><select value={moveDraft.method} onChange={e=>setMoveDraft(x=>({...x,method:e.target.value}))}>{cashMethods.map(method=><option key={method}>{method}</option>)}</select></Field><Field label="Reserva"><select value={moveDraft.reservationId} onChange={e=>setMoveDraft(x=>({...x,reservationId:e.target.value}))}><option value="">Sin reserva</option>{reservations.slice(0,100).map(r=><option key={r.id} value={r.id}>{r.numero_reserva||r.id} · {r.nombre_huesped}</option>)}</select></Field><Field label="Concepto" wide><input value={moveDraft.concept} onChange={e=>setMoveDraft(x=>({...x,concept:e.target.value}))}/></Field><Field label="Referencia" wide><input value={moveDraft.reference} onChange={e=>setMoveDraft(x=>({...x,reference:e.target.value}))}/></Field></div><footer><button type="button" onClick={()=>setMoveDraft(null)}>Cancelar</button><button>Registrar</button></footer></Modal>}
    {closeDraft&&<Modal title="Cerrar caja" onClose={()=>setCloseDraft(null)} onSubmit={async e=>{e.preventDefault();await onClose?.({...closeDraft,sessionId:open?.id});setCloseDraft(null)}}><div className={ui.fieldGrid}><Field label={`Esperado · ${currency}`}><input disabled value={expected}/></Field><Field label={`Conteo real · ${currency}`}><input autoFocus type="number" step=".01" value={closeDraft.closingAmount} onChange={e=>setCloseDraft(x=>({...x,closingAmount:e.target.value}))}/></Field><Field label="Notas" wide><textarea value={closeDraft.notes} onChange={e=>setCloseDraft(x=>({...x,notes:e.target.value}))}/></Field></div><footer><button type="button" onClick={()=>setCloseDraft(null)}>Cancelar</button><button>Cerrar turno</button></footer></Modal>}
  </div>
}

export function BillingView(props){return <AccountingGateway {...props}/>}
export function ReportsView(props){return <ReportsPremium {...props}/>}
