"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import{money}from"../../core/formatters"
import{applyDeposit,convertOtaPrepayment,createDeposit,createOtaPrepayment,createPaymentRequest,loadPaymentConnection,loadPaymentWorkspace,paidByReservation,refundDeposit,verifyPaymentRequest}from"../../services/payments"
import s from"./payments-premium.module.css"

const ACTIVE_RESERVATION=r=>r&&r.estado!=="cancelada"&&!r.no_show
const requestTone=status=>status==="approved"?"ok":status==="failed"||status==="expired"||status==="cancelled"?"bad":"wait"
const requestLabel=status=>({draft:"Preparando",requested:"Enviado",pending:"Pendiente",approved:"Cobrado",failed:"Fallido",expired:"Vencido",cancelled:"Cancelado"}[status]||status||"Pendiente")
const depositLabel=status=>({held:"Retenida",applied:"Aplicada",refunded:"Devuelta",forfeited:"Retenida por cargo",cancelled:"Cancelada"}[status]||status)
const otaLabel=status=>({reported:"Avisado",converted:"Convertido",ignored:"Ignorado"}[status]||status)
const shortDate=value=>value?new Date(value).toLocaleString("es-AR",{dateStyle:"short",timeStyle:"short"}):"—"

export default function PaymentsPremium({reservations=[],sessions=[],movements=[]}){
  const propertyId=reservations.find(ACTIVE_RESERVATION)?.property_id||sessions[0]?.property_id||movements[0]?.property_id||null
  const[tab,setTab]=useState("requests"),[workspace,setWorkspace]=useState({requests:[],deposits:[],ota:[],payments:[]}),[connection,setConnection]=useState(null),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[userId,setUserId]=useState(null),[lastLink,setLastLink]=useState(null)
  const[requestDraft,setRequestDraft]=useState({reservationId:"",amount:"",expiresHours:72,message:""}),[depositDraft,setDepositDraft]=useState({reservationId:"",amount:"",method:"Transferencia",reference:"",notes:""}),[otaDraft,setOtaDraft]=useState({reservationId:"",channel:"Booking.com",externalRef:"",amount:""})
  const activeReservations=useMemo(()=>reservations.filter(ACTIVE_RESERVATION),[reservations]),paidMap=useMemo(()=>paidByReservation(workspace.payments),[workspace.payments]),reservationMap=useMemo(()=>new Map(reservations.map(r=>[String(r.id),r])),[reservations])
  const selected=reservationMap.get(String(requestDraft.reservationId)),selectedBalance=selected?Math.max(0,Number(selected.precio_total||0)-(paidMap.get(String(selected.id))||0)):0

  async function reload(){if(!propertyId)return;const data=await loadPaymentWorkspace(propertyId);setWorkspace(data)}
  useEffect(()=>{let active=true;supabase.auth.getUser().then(({data})=>active&&setUserId(data?.user?.id||null));return()=>{active=false}},[])
  useEffect(()=>{let active=true;if(!propertyId)return;Promise.all([loadPaymentWorkspace(propertyId),loadPaymentConnection(propertyId)]).then(([data,config])=>{if(!active)return;setWorkspace(data);setConnection(config)}).catch(error=>active&&setMessage(error.message||"No se pudo cargar Pagos."));return()=>{active=false}},[propertyId])
  useEffect(()=>{if(requestDraft.reservationId||!activeReservations.length)return;const target=activeReservations.find(r=>Math.max(0,Number(r.precio_total||0)-(paidMap.get(String(r.id))||0))>.01)||activeReservations[0];if(target)setRequestDraft(x=>({...x,reservationId:String(target.id)}))},[activeReservations,paidMap,requestDraft.reservationId])
  useEffect(()=>{if(!selected)return;setRequestDraft(x=>({...x,amount:String(Math.max(0,Number(selected.precio_total||0)-(paidMap.get(String(selected.id))||0))) }))},[selected?.id,workspace.payments.length])

  async function run(key,fn){if(busy)return;setBusy(key);setMessage("");try{const result=await fn();await reload();return result}catch(error){setMessage(error?.message||"No se pudo completar la operación.")}finally{setBusy("")}}
  function reservationLabel(id){const r=reservationMap.get(String(id));return r?`${r.numero_reserva||r.id} · ${r.nombre_huesped}`:`Reserva ${id}`}
  function copy(text,label="Copiado"){navigator.clipboard?.writeText(String(text||"")).then(()=>setMessage(label)).catch(()=>setMessage("No pudimos copiar automáticamente."))}
  function shareWhatsApp(link,reservation){const phone=String(reservation?.telefono_huesped||"").replace(/\D/g,"");if(!phone)return setMessage("La reserva no tiene teléfono para WhatsApp.");const amount=Number(requestDraft.amount||0),text=`Hola ${String(reservation?.nombre_huesped||"").split(/\s+/)[0]||""}. Te enviamos el enlace seguro para completar el pago de ${money(amount,"ARS")} de tu reserva: ${link}`;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer")}

  async function makeRequest(){const reservation=reservationMap.get(String(requestDraft.reservationId));if(!reservation)return setMessage("Elegí una reserva.");const result=await run("new-request",()=>createPaymentRequest({propertyId,reservationId:reservation.id,amount:requestDraft.amount,currency:reservation.moneda||"ARS",expiresHours:requestDraft.expiresHours,message:requestDraft.message}));if(result?.checkout_url)setLastLink({url:result.checkout_url,reservation,request:result.request})}
  async function verify(row){const result=await run(`verify-${row.id}`,()=>verifyPaymentRequest({propertyId,requestId:row.id}));if(result?.approved)setMessage("Pago confirmado por Mercado Pago y aplicado a la reserva.");else if(result)setMessage(`Mercado Pago todavía no confirmó el cobro (${result.provider_status||"pendiente"}).`)}
  async function addDeposit(){const r=reservationMap.get(String(depositDraft.reservationId));if(!r)return setMessage("Elegí una reserva.");const result=await run("deposit-new",()=>createDeposit({propertyId,userId,reservationId:r.id,amount:depositDraft.amount,currency:r.moneda||"ARS",method:depositDraft.method,reference:depositDraft.reference,notes:depositDraft.notes}));if(result){setDepositDraft({reservationId:"",amount:"",method:"Transferencia",reference:"",notes:""});setMessage("Fianza / depósito retenido y trazado por separado.")}}
  async function addOta(){const r=reservationMap.get(String(otaDraft.reservationId));if(!r)return setMessage("Elegí una reserva.");const result=await run("ota-new",()=>createOtaPrepayment({propertyId,userId,reservationId:r.id,channel:otaDraft.channel,externalRef:otaDraft.externalRef,amount:otaDraft.amount,currency:r.moneda||"ARS"}));if(result){setOtaDraft({reservationId:"",channel:"Booking.com",externalRef:"",amount:""});setMessage("Aviso de prepago OTA registrado sin tocar la cuenta todavía.")}}

  if(!propertyId)return <section className={s.empty}><b>Pagos & Caja</b><p>Cuando exista una reserva o una caja en esta propiedad, el centro de cobros se activa acá.</p></section>
  const openCash=sessions.find(x=>x.status==="open"),cashMoves=openCash?movements.filter(m=>String(m.session_id)===String(openCash.id)):[],cashNet=cashMoves.reduce((sum,m)=>sum+(m.movement_type==="expense"?-Number(m.amount||0):Number(m.amount||0)),0)
  return <section className={s.wrap}>
    <header className={s.hero}><div><small>COBROS & CONCILIACIÓN</small><h2>Cobra donde quieras. Todo queda en la reserva.</h2><p>Enlace de pago, efectivo, fianzas y prepagos OTA con una sola cuenta y trazabilidad por propiedad.</p></div><div className={s.heroMetrics}><span><small>Mercado Pago</small><b>{connection?.connection?.connected?"Conectado":"Sin conectar"}</b></span><span><small>Caja</small><b>{openCash?"Abierta":"Cerrada"}</b></span><span><small>Mov. turno</small><b>{cashMoves.length}</b></span><span><small>Neto caja</small><b>{money(cashNet,"ARS")}</b></span></div></header>
    <nav className={s.tabs}>{[["requests","Solicitar pago"],["deposits","Fianzas"],["ota","Prepago OTA"]].map(([id,label])=><button type="button" key={id} className={tab===id?s.active:""} onClick={()=>setTab(id)}>{label}</button>)}</nav>

    {tab==="requests"&&<div className={s.grid}>
      <article className={s.formCard}><div className={s.cardHead}><span><small>ENLACE DE PAGO</small><h3>Que el banco confirme el cobro</h3></span><i data-on={!!connection?.connection?.connected}>{connection?.connection?.connected?"MP listo":"Conectar MP"}</i></div><label>Reserva<select value={requestDraft.reservationId} onChange={e=>setRequestDraft(x=>({...x,reservationId:e.target.value}))}><option value="">Elegir reserva</option>{activeReservations.map(r=>{const balance=Math.max(0,Number(r.precio_total||0)-(paidMap.get(String(r.id))||0));return <option key={r.id} value={r.id}>{r.numero_reserva||r.id} · {r.nombre_huesped} · {money(balance,r.moneda)}</option>})}</select></label><div className={s.two}><label>Importe<input type="number" min=".01" step=".01" value={requestDraft.amount} onChange={e=>setRequestDraft(x=>({...x,amount:e.target.value}))}/></label><label>Vence en<select value={requestDraft.expiresHours} onChange={e=>setRequestDraft(x=>({...x,expiresHours:e.target.value}))}><option value="24">24 horas</option><option value="48">48 horas</option><option value="72">72 horas</option><option value="168">7 días</option></select></label></div>{selected&&<div className={s.balance}>Saldo de la reserva <b>{money(selectedBalance,selected.moneda||"ARS")}</b></div>}<label>Mensaje interno<input value={requestDraft.message} onChange={e=>setRequestDraft(x=>({...x,message:e.target.value}))} placeholder="Ej. anticipo 30%"/></label><button className={s.primary} type="button" disabled={busy==="new-request"||!connection?.connection?.connected} onClick={makeRequest}>{busy==="new-request"?"Generando…":"Generar enlace Mercado Pago"}</button>{!connection?.connection?.connected&&<p className={s.hint}>Un administrador debe conectar la cuenta de Mercado Pago del hotel desde Integraciones.</p>}
        {lastLink&&<div className={s.linkBox}><span><small>ENLACE LISTO</small><b>{money(lastLink.request?.amount,"ARS")}</b></span><div><button type="button" onClick={()=>copy(lastLink.url,"Enlace copiado.")}>Copiar</button><button type="button" onClick={()=>shareWhatsApp(lastLink.url,lastLink.reservation)}>WhatsApp</button><button type="button" onClick={()=>window.open(lastLink.url,"_blank","noopener,noreferrer")}>Abrir</button></div></div>}
      </article>
      <article className={s.listCard}><div className={s.cardHead}><span><small>SOLICITUDES RECIENTES</small><h3>Banco → reserva</h3></span><button type="button" className={s.ghost} onClick={reload}>Actualizar</button></div><div className={s.rows}>{workspace.requests.map(row=>{const expired=row.status!=="approved"&&row.expires_at&&new Date(row.expires_at).getTime()<Date.now(),status=expired?"expired":row.status,url=row.init_point||row.sandbox_init_point;return <div className={s.row} key={row.id}><span><b>{reservationLabel(row.reserva_id)}</b><small>{shortDate(row.created_at)} · vence {shortDate(row.expires_at)}</small></span><strong>{money(row.amount,row.currency)}</strong><em data-tone={requestTone(status)}>{requestLabel(status)}</em><div>{url&&<button type="button" onClick={()=>copy(url)}>Copiar</button>}{!["approved","expired","cancelled"].includes(status)&&<button type="button" disabled={busy===`verify-${row.id}`} onClick={()=>verify(row)}>Verificar</button>}</div></div>})}{!workspace.requests.length&&<p className={s.zero}>Todavía no hay enlaces de pago.</p>}</div></article>
    </div>}

    {tab==="deposits"&&<div className={s.grid}>
      <article className={s.formCard}><div className={s.cardHead}><span><small>FIANZAS & ANTICIPOS</small><h3>Retener no es cobrar</h3></span></div><label>Reserva<select value={depositDraft.reservationId} onChange={e=>setDepositDraft(x=>({...x,reservationId:e.target.value}))}><option value="">Elegir reserva</option>{activeReservations.map(r=><option key={r.id} value={r.id}>{r.numero_reserva||r.id} · {r.nombre_huesped}</option>)}</select></label><div className={s.two}><label>Importe<input type="number" min=".01" step=".01" value={depositDraft.amount} onChange={e=>setDepositDraft(x=>({...x,amount:e.target.value}))}/></label><label>Medio<select value={depositDraft.method} onChange={e=>setDepositDraft(x=>({...x,method:e.target.value}))}><option>Transferencia</option><option>Efectivo</option><option>Mercado Pago</option><option>Tarjeta</option><option>Otro</option></select></label></div><label>Referencia<input value={depositDraft.reference} onChange={e=>setDepositDraft(x=>({...x,reference:e.target.value}))} placeholder="Transferencia, operación, recibo…"/></label><label>Nota<input value={depositDraft.notes} onChange={e=>setDepositDraft(x=>({...x,notes:e.target.value}))}/></label><button className={s.primary} type="button" disabled={busy==="deposit-new"} onClick={addDeposit}>Registrar fianza / depósito</button><p className={s.hint}>Queda fuera del saldo hasta que recepción lo aplique. Si se devuelve antes de aplicarlo, nunca entra como pago.</p></article>
      <article className={s.listCard}><div className={s.cardHead}><span><small>TRAZABILIDAD</small><h3>Retenido, aplicado o devuelto</h3></span></div><div className={s.rows}>{workspace.deposits.map(row=><div className={s.row} key={row.id}><span><b>{reservationLabel(row.reserva_id)}</b><small>{row.method}{row.reference?` · ${row.reference}`:""} · {shortDate(row.held_at)}</small></span><strong>{money(row.amount,row.currency)}</strong><em data-tone={row.status==="applied"?"ok":row.status==="refunded"?"bad":"wait"}>{depositLabel(row.status)}</em><div>{row.status==="held"&&<button type="button" disabled={busy===`apply-${row.id}`} onClick={()=>run(`apply-${row.id}`,()=>applyDeposit(row.id))}>Aplicar a cuenta</button>}{row.status==="held"&&<button type="button" disabled={busy===`refund-${row.id}`} onClick={()=>run(`refund-${row.id}`,()=>refundDeposit(row.id,"Devuelta desde Pagos & Caja"))}>Devolver</button>}</div></div>)}{!workspace.deposits.length&&<p className={s.zero}>No hay fianzas ni depósitos retenidos.</p>}</div></article>
    </div>}

    {tab==="ota"&&<div className={s.grid}>
      <article className={s.formCard}><div className={s.cardHead}><span><small>PREPAGO DE CANAL</small><h3>Convertir sin duplicar</h3></span></div><label>Reserva<select value={otaDraft.reservationId} onChange={e=>setOtaDraft(x=>({...x,reservationId:e.target.value}))}><option value="">Elegir reserva</option>{activeReservations.map(r=><option key={r.id} value={r.id}>{r.numero_reserva||r.id} · {r.nombre_huesped}</option>)}</select></label><div className={s.two}><label>Canal<select value={otaDraft.channel} onChange={e=>setOtaDraft(x=>({...x,channel:e.target.value}))}><option>Booking.com</option><option>Expedia</option><option>Airbnb</option><option>Despegar</option><option>Otro</option></select></label><label>Importe<input type="number" min=".01" step=".01" value={otaDraft.amount} onChange={e=>setOtaDraft(x=>({...x,amount:e.target.value}))}/></label></div><label>Referencia del canal<input value={otaDraft.externalRef} onChange={e=>setOtaDraft(x=>({...x,externalRef:e.target.value}))} placeholder="ID del cobro/prepago OTA"/></label><button className={s.primary} type="button" disabled={busy==="ota-new"} onClick={addOta}>Registrar aviso de prepago</button><p className={s.hint}>La referencia del canal es única por hotel y evita convertir dos veces el mismo prepago. Cuando el Channel Manager esté conectado, estos avisos podrán ingresar automáticamente.</p></article>
      <article className={s.listCard}><div className={s.cardHead}><span><small>AVISOS DEL CANAL</small><h3>Un clic para llevarlo a la cuenta</h3></span></div><div className={s.rows}>{workspace.ota.map(row=><div className={s.row} key={row.id}><span><b>{reservationLabel(row.reserva_id)}</b><small>{row.channel} · {row.external_ref}</small></span><strong>{money(row.amount,row.currency)}</strong><em data-tone={row.status==="converted"?"ok":"wait"}>{otaLabel(row.status)}</em><div>{row.status==="reported"&&<button type="button" disabled={busy===`ota-${row.id}`} onClick={()=>run(`ota-${row.id}`,()=>convertOtaPrepayment(row.id))}>Convertir en pago</button>}</div></div>)}{!workspace.ota.length&&<p className={s.zero}>Todavía no hay avisos de prepago OTA.</p>}</div></article>
    </div>}
    {message&&<div className={s.message}>{message}</div>}
  </section>
}
