import LegalPage from"../legal/LegalPage"

export const metadata={title:"Privacidad | Habitación Llena",description:"Cómo Habitación Llena trata datos de cuentas, hoteles, huéspedes e integraciones."}

const sections=[
  {title:"Qué datos tratamos",body:["Habitación Llena necesita información para operar el PMS, autenticar usuarios, prestar soporte, proteger el servicio y mantener la trazabilidad de la operación hotelera."],items:["Datos de cuenta y contacto de usuarios autorizados.","Configuración de la propiedad, habitaciones, tarifas, reservas, huéspedes y operación.","Metadatos de pagos, facturación e integraciones cuando el hotel las habilita.","Preferencias del producto, registros técnicos, eventos de seguridad y datos de soporte."]},
  {title:"Quién decide sobre los datos",body:["En el modelo SaaS previsto, cada hotel decide para qué usa los datos de sus huéspedes y colaboradores dentro de su operación. Habitación Llena presta la plataforma y procesa esa información para brindar el servicio. Para datos propios de cuenta, seguridad, contratación y soporte, Habitación Llena puede actuar como responsable del tratamiento según corresponda."]},
  {title:"Para qué se usan",body:["Los datos se utilizan para ejecutar funciones solicitadas por el hotel, mantener la cuenta, prevenir abuso, resolver incidentes, cumplir obligaciones aplicables y mejorar el producto. Analítica, publicidad o personalización no esencial se condicionan a la preferencia de cookies cuando corresponda."],items:["Gestionar reservas, huéspedes, habitaciones, caja, housekeeping y demás módulos habilitados.","Autenticar usuarios y aplicar permisos por propiedad.","Procesar solicitudes de soporte e integraciones.","Detectar fallos, abuso y eventos de seguridad.","Cumplir obligaciones fiscales, contractuales o legales aplicables."]},
  {title:"Proveedores e integraciones",body:["El servicio puede apoyarse en proveedores de hosting, autenticación, correo, pagos, facturación, analítica o canales externos. Sólo se comparte la información necesaria para la función habilitada y bajo las condiciones del proveedor correspondiente. Algunas transferencias pueden involucrar infraestructura ubicada fuera del país del hotel."],items:["Mercado Pago y proveedores de pago cuando el hotel conecta esa función.","ARCA u otros servicios fiscales cuando se habilita facturación electrónica.","Proveedores de infraestructura, correo, autenticación o monitoreo técnico.","OTAs, channel managers, mensajería o cerraduras únicamente cuando exista una integración configurada."]},
  {title:"Conservación y eliminación",body:["La información se conserva mientras sea necesaria para prestar el servicio, mantener la integridad operativa, cumplir obligaciones o atender disputas. Los plazos concretos pueden variar según el tipo de dato, la configuración del hotel y las reglas legales o fiscales aplicables."],items:["La eliminación de una cuenta no implica necesariamente borrar de inmediato datos sujetos a conservación legal.","Los hoteles deben definir sus propias políticas de conservación de datos de huéspedes.","Copias de respaldo pueden tardar un período razonable en rotar por completo."]},
  {title:"Derechos y contacto",body:["Las personas pueden solicitar acceso, corrección, actualización o eliminación cuando corresponda conforme a la normativa aplicable. Las solicitudes vinculadas con una reserva o estadía pueden necesitar ser atendidas primero por el hotel que obtuvo esos datos."],items:["Contacto general: contacto@habitacionllena.com","Para una solicitud, indicar la propiedad relacionada y la naturaleza del pedido sin enviar contraseñas ni datos sensibles innecesarios."]},
  {title:"Argentina y uso internacional",body:["El producto se diseña inicialmente desde Argentina y contempla la Ley 25.326 y normativa relacionada. Cuando el servicio se ofrezca en otras jurisdicciones, se deberán aplicar también las obligaciones locales que correspondan, incluidas reglas de privacidad, transferencias internacionales y derechos de las personas cuando resulten aplicables."]},
]

export default function PrivacyPage(){return <LegalPage kicker="PRIVACIDAD" title="Los datos del hotel no son un subproducto." intro="Diseñamos Habitación Llena para que la información de cada propiedad permanezca aislada y se use sólo para operar, proteger y prestar el servicio." sections={sections}/>}
