"use client"

import{useCallback,useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import s from"./priceLabsPanel.module.css"

const fmt=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value)).replace(".",""):"—"
const statusLabel=value=>({setup:"Configurando",pending_partner:"Esperando partner",prepared:"Tipos preparados",listed:"Listings creados",calendar_ready:"Calendario enviado",ready:"Sincronizando",paused:"Pausado",disabled:"Desactivado"}[value]||"Sin configurar")
const listingLabel=value=>({prepared:"Preparado",listed:"Creado",calendar_ready:"Calendario OK",synced:"Sincronizado"}[value]||value||"Pendiente")

export default function PriceLabsPanel({propertyId,property}){
  const[data,setData]=useState(null),[email,setEmail]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("")
  const canManage=["owner","manager","admin","revenue"].includes(property?.role)
  const authHeaders=useCallback(async()=>{const{data:session}=await supabase.auth.getSession(),token=session?.session?.access_token;if(!token)throw new Error("La sesión venció. Volvé a iniciar sesión.");return{Authorization:`Bearer ${token}`,"Content-Type":"application/json"}},[])
  const load=useCallback(async()=>{if(!propertyId||!canManage)return;setLoading(true);setError("");try{const headers=await authHeaders(),response=await fetch(`/api/integrations/pricelabs/config?property_id=${encodeURIComponent(propertyId)}`,{headers,cache:"no-store"}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||"No se pudo cargar PriceLabs.");setData(payload);setEmail(payload?.connection?.user_email||"")}catch(err){setError(err?.message||"No se pudo cargar PriceLabs.")}finally{setLoading(false)}},[propertyId,canManage,authHeaders])
  useEffect(()=>{load()},[load])
  const eligible=useMemo(()=>data?.room_types?.filter(row=>row.eligible)||[],[data]),prepared=eligible.filter(row=>row.listing),connection=data?.connection,status=connection?.status||"setup"
  async function post(path,body,key){if(busy)return;setBusy(key);setError("");setNotice("");try{const headers=await authHeaders(),response=await fetch(path,{method:"POST",headers,body:JSON.stringify(body)}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||"PriceLabs rechazó la operación.");setNotice(key==="save"?"Email de PriceLabs guardado.":key==="prepare"?"Tipos de habitación preparados.":key==="integration"?"Callbacks registrados en PriceLabs.":key==="listings"?"Listings enviados a PriceLabs.":key==="calendar"?"Calendario de 730 días enviado.":key==="reservations"?"Reservas y bloqueos enviados.":key==="enable"?"Sincronización dinámica activada.":"Sincronización pausada.");await load()}catch(err){setError(err?.message||"No se pudo completar la operación.")}finally{setBusy("")}}
  const save=()=>post("/api/integrations/pricelabs/config",{property_id:propertyId,action:"save",user_email:email},"save")
  const prepare=()=>post("/api/integrations/pricelabs/config",{property_id:propertyId,action:"prepare"},"prepare")
  const action=key=>post("/api/integrations/pricelabs/actions",{property_id:propertyId,action:key},key)
  if(!canManage)return null
  if(loading)return <section className={s.shell}><div className={s.loading}>Cargando integración PriceLabs…</div></section>
  return <section className={s.shell} aria-label="Integración PriceLabs">
    <header className={s.header}><div><small>REVENUE · PRICING DINÁMICO</small><h2>PriceLabs</h2><p>Conectá tipos de habitación, inventario y reservas. Las tarifas vuelven al calendario del PMS sólo cuando la integración esté certificada y activada.</p></div><div className={s.status} data-active={connection?.sync_enabled?"true":"false"}><span/><div><small>ESTADO</small><b>{statusLabel(status)}</b></div></div></header>
    {error?<div className={s.error}>{error}</div>:null}{notice?<div className={s.notice}>{notice}</div>:null}
    <div className={s.grid}><section className={s.setup}><div className={s.sectionHead}><div><small>1 · CUENTA</small><h3>Vinculación del hotel</h3></div><span>{connection?.user_email?"Cuenta identificada":"Falta email"}</span></div><label><span>Email registrado en PriceLabs</span><div className={s.emailRow}><input type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="hotel@ejemplo.com"/><button type="button" onClick={save} disabled={Boolean(busy)||!email.trim()}>{busy==="save"?"Guardando…":"Guardar"}</button></div></label><p>PriceLabs exige el email de su cuenta para crear los listings del PMS. Habitación Llena no guarda una API key del hotel.</p>
      <div className={s.partner} data-ready={data?.platform_ready?"true":"false"}><span>{data?.platform_ready?"✓":"!"}</span><div><b>{data?.platform_ready?"Credenciales de partner disponibles":"A la espera de credenciales oficiales de PriceLabs"}</b><small>{data?.platform_ready?data?.certified?"Integración certificada para aplicar tarifas.":"Backend conectado; falta certificación antes de aplicar precios automáticamente.":`Faltan: ${(data?.missing_platform_env||[]).join(", ")||"credenciales IAPI"}. El PMS queda seguro y no aplica tarifas.`}</small></div></div>
    </section>
    <section className={s.flow}><div className={s.sectionHead}><div><small>2 · FLUJO IAPI</small><h3>Preparación y sincronización</h3></div><span>{prepared.length}/{eligible.length} tipos preparados</span></div><div className={s.actions}><button type="button" onClick={prepare} disabled={Boolean(busy)||!connection?.user_email}>{busy==="prepare"?"Preparando…":"Preparar tipos"}</button><button type="button" onClick={()=>action("integration")} disabled={Boolean(busy)||!data?.platform_ready}>{busy==="integration"?"Registrando…":"Registrar callbacks"}</button><button type="button" onClick={()=>action("listings")} disabled={Boolean(busy)||!data?.platform_ready||!prepared.length}>{busy==="listings"?"Enviando…":"Enviar listings"}</button><button type="button" onClick={()=>action("calendar")} disabled={Boolean(busy)||!data?.platform_ready||!prepared.length}>{busy==="calendar"?"Enviando 730 días…":"Enviar calendario 730 días"}</button><button type="button" onClick={()=>action("reservations")} disabled={Boolean(busy)||!data?.platform_ready||!prepared.length}>{busy==="reservations"?"Enviando…":"Enviar reservas"}</button>{connection?.sync_enabled?<button type="button" className={s.pause} onClick={()=>action("pause")} disabled={Boolean(busy)}>{busy==="pause"?"Pausando…":"Pausar tarifas dinámicas"}</button>:<button type="button" className={s.primary} onClick={()=>action("enable")} disabled={Boolean(busy)||!data?.apply_ready||status!=="calendar_ready"}>{busy==="enable"?"Activando…":"Activar tarifas dinámicas"}</button>}</div><div className={s.timeline}><div><span>Listings</span><b>{fmt(connection?.last_listing_sync_at)}</b></div><div><span>Calendario</span><b>{fmt(connection?.last_calendar_push_at)}</b></div><div><span>Reservas</span><b>{fmt(connection?.last_reservation_sync_at)}</b></div><div><span>Último precio</span><b>{fmt(connection?.last_price_sync_at)}</b></div></div></section></div>
    <section className={s.types}><div className={s.sectionHead}><div><small>3 · INVENTARIO</small><h3>Tipos de habitación conectables</h3></div><span>PriceLabs trabaja por tipo, no por habitación física</span></div><div className={s.typeGrid}>{eligible.map(type=><article key={type.id}><div><b>{type.name}</b><small>{type.code||"Sin código"} · {type.units} unidad{type.units===1?"":"es"}</small></div><span data-ready={type.listing?"true":"false"}>{listingLabel(type.listing?.status)}</span><code>{type.listing_id}</code></article>)}{!eligible.length?<div className={s.empty}>No hay tipos online con habitaciones activas para conectar.</div>:null}</div></section>
    <footer className={s.footer}><div><b>Callbacks firmados</b><span>Sync · Calendar trigger · Hook</span></div><div><b>Aplicación segura</b><span>Precio + mínimo + cierre a llegada/salida</span></div><div><b>Fuente única</b><span>Las tarifas terminan en Tarifas y disponibilidad</span></div></footer>
  </section>
}
