"use client"

const money=(value,currency="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:2}).format(Number(value)||0)

export default function CheckoutBalanceDialog({item,onClose,onPay,onConfirm,saving}){
  if(!item)return null
  const total=Math.max(0,Number(item.precio_total)||0),paid=Math.max(0,Number(item.paid)||0),balance=Math.max(0,total-paid),currency=item.moneda||"ARS"
  const overlay={position:"fixed",inset:0,zIndex:260,display:"grid",placeItems:"center",padding:18,background:"rgba(19,28,46,.34)",backdropFilter:"blur(12px) saturate(1.08)"}
  const panel={width:"min(560px,calc(100vw - 28px))",border:"1px solid color-mix(in srgb,var(--line) 82%,#fff)",borderRadius:22,background:"color-mix(in srgb,var(--panelSolid) 96%,transparent)",boxShadow:"0 28px 80px rgba(17,28,52,.28)",overflow:"hidden"}
  const button={height:40,padding:"0 14px",border:"1px solid var(--line)",borderRadius:11,background:"var(--panelSolid)",color:"var(--text)",font:"inherit",fontSize:11,fontWeight:850,cursor:saving?"wait":"pointer"}
  return <div style={overlay} role="dialog" aria-modal="true" aria-label="Confirmar check-out con saldo pendiente"><section style={panel}><header style={{display:"flex",justifyContent:"space-between",gap:16,padding:"18px 20px 14px",borderBottom:"1px solid var(--line)"}}><div><small style={{display:"block",fontSize:10,fontWeight:900,letterSpacing:".12em",color:"var(--accent)",marginBottom:5}}>CHECK-OUT · SALDO PENDIENTE</small><h2 style={{margin:0,fontSize:20}}>¿Finalizar estadía con deuda?</h2><p style={{margin:"6px 0 0",fontSize:11,color:"var(--muted)"}}>{item.nombre_huesped} · Reserva {item.numero_reserva||item.id}</p></div><button type="button" onClick={onClose} disabled={saving} style={{...button,width:38,padding:0}}>×</button></header><div style={{padding:"18px 20px"}}><p style={{margin:"0 0 14px",fontSize:12,lineHeight:1.55,color:"var(--text)"}}>La reserva todavía tiene saldo pendiente. Podés cobrarlo ahora o confirmar el check-out dejando la deuda registrada.</p><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:9}}><article style={{padding:12,border:"1px solid var(--line)",borderRadius:12}}><small>Total</small><b style={{display:"block",marginTop:5,fontSize:15}}>{money(total,currency)}</b></article><article style={{padding:12,border:"1px solid var(--line)",borderRadius:12}}><small>Pagado</small><b style={{display:"block",marginTop:5,fontSize:15}}>{money(paid,currency)}</b></article><article style={{padding:12,border:"1px solid var(--line)",borderRadius:12}}><small>Pendiente</small><b style={{display:"block",marginTop:5,fontSize:15}}>{money(balance,currency)}</b></article></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,flexWrap:"wrap",marginTop:18,paddingTop:14,borderTop:"1px solid var(--line)"}}><button type="button" onClick={onClose} disabled={saving} style={button}>Cancelar</button><button type="button" onClick={onConfirm} disabled={saving} style={{...button,color:"#d84960"}}>{saving?"Finalizando…":"Check-out con saldo pendiente"}</button><button type="button" onClick={onPay} disabled={saving} style={{...button,borderColor:"var(--accent)",background:"var(--accent)",color:"#fff"}}>Cobrar ahora</button></div></div></section></div>
}
