"use client"

function Field({label,children,wide=false}){return <label style={{display:"grid",gap:5,gridColumn:wide?"span 2":"auto"}}><span style={{fontSize:9.5,fontWeight:850,color:"var(--muted)"}}>{label}</span>{children}</label>}
function Text({value,onChange,type="text",placeholder=""}){return <input type={type} value={value||""} onChange={event=>onChange(event.target.value)} placeholder={placeholder} style={{height:38,width:"100%",boxSizing:"border-box",border:"1px solid var(--line)",borderRadius:10,padding:"0 10px",background:"color-mix(in srgb,var(--panelSolid) 86%,transparent)",color:"var(--text)",font:"inherit",fontSize:11,fontWeight:720,outline:"none"}}/>}
function Select({value,onChange,children}){return <select value={value||""} onChange={event=>onChange(event.target.value)} style={{height:38,width:"100%",border:"1px solid var(--line)",borderRadius:10,padding:"0 10px",background:"color-mix(in srgb,var(--panelSolid) 86%,transparent)",color:"var(--text)",font:"inherit",fontSize:11,fontWeight:720,outline:"none"}}>{children}</select>}

export default function ReservationGuestEditorFields({draft,rooms=[],isGroup=false,onField,onUpload,onOpenDocument}){
  if(!draft)return null
  const grid={display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:9},section={padding:12,border:"1px solid var(--line)",borderRadius:13,background:"color-mix(in srgb,var(--bg) 36%,var(--panelSolid))"},fileButton={height:36,padding:"0 11px",display:"inline-flex",alignItems:"center",justifyContent:"center",gap:6,border:"1px solid var(--line)",borderRadius:9,background:"var(--panelSolid)",color:"var(--text)",font:"inherit",fontSize:10.5,fontWeight:820,cursor:"pointer"}
  return <>
    <section style={section}><h3 style={{margin:"0 0 9px",fontSize:12.5}}>Identidad y contacto</h3><div style={grid}><Field label="Nombre y apellido" wide><Text value={draft.full_name} onChange={value=>onField("full_name",value)} placeholder={isGroup&&draft.role==="primary"?"Nombre real del huésped principal":""}/></Field><Field label="Habitación"><Select value={draft.room_id||""} onChange={value=>onField("room_id",value)}><option value="">Sin asignar</option>{rooms.map(room=><option key={room.id} value={room.id}>Hab. {room.nombre}</option>)}</Select></Field><Field label="Vínculo"><Text value={draft.relationship} onChange={value=>onField("relationship",value)} placeholder={draft.role==="primary"?"Titular":"Pareja, hijo/a…"}/></Field><Field label="Tipo de documento"><Select value={draft.document_type} onChange={value=>onField("document_type",value)}><option>DNI</option><option>Pasaporte</option><option>CI</option><option>CUIL</option><option>Otro</option></Select></Field><Field label="Número"><Text value={draft.document_number} onChange={value=>onField("document_number",value)}/></Field><Field label="CUIL"><Text value={draft.cuil} onChange={value=>onField("cuil",value)}/></Field><Field label="Fecha de nacimiento"><Text type="date" value={draft.birth_date} onChange={value=>onField("birth_date",value)}/></Field><Field label="Sexo"><Select value={draft.sex} onChange={value=>onField("sex",value)}><option value="">Sin informar</option><option value="F">Femenino</option><option value="M">Masculino</option><option value="X">X / Otro</option></Select></Field><Field label="Estado civil"><Select value={draft.marital_status} onChange={value=>onField("marital_status",value)}><option value="">Sin informar</option><option>Soltero/a</option><option>Casado/a</option><option>Unión convivencial</option><option>Divorciado/a</option><option>Viudo/a</option></Select></Field><Field label="Nacionalidad"><Text value={draft.nationality} onChange={value=>onField("nationality",value)}/></Field><Field label="Teléfono"><Text value={draft.phone} onChange={value=>onField("phone",value)}/></Field><Field label="Email" wide><Text type="email" value={draft.email} onChange={value=>onField("email",value)}/></Field></div></section>
    <section style={{...section,marginTop:10}}><h3 style={{margin:"0 0 9px",fontSize:12.5}}>Domicilio y viaje</h3><div style={grid}><Field label="Domicilio" wide><Text value={draft.address} onChange={value=>onField("address",value)}/></Field><Field label="Localidad"><Text value={draft.city} onChange={value=>onField("city",value)}/></Field><Field label="Provincia / estado"><Text value={draft.province} onChange={value=>onField("province",value)}/></Field><Field label="País"><Text value={draft.country} onChange={value=>onField("country",value)}/></Field><Field label="Código postal"><Text value={draft.postal_code} onChange={value=>onField("postal_code",value)}/></Field><Field label="Ocupación"><Text value={draft.occupation} onChange={value=>onField("occupation",value)}/></Field><Field label="Motivo del viaje"><Select value={draft.travel_reason} onChange={value=>onField("travel_reason",value)}><option value="">Sin informar</option><option>Turismo</option><option>Trabajo</option><option>Evento</option><option>Salud</option><option>Visita familiar</option><option>Otro</option></Select></Field></div></section>
    <section style={{...section,marginTop:10}}><h3 style={{margin:"0 0 5px",fontSize:12.5}}>Documentación</h3><p style={{margin:"0 0 10px",fontSize:9.8,color:"var(--muted)"}}>Frente y dorso del DNI, pasaporte u otro documento.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}>{[["front","Frente",draft.document_front_path],["back","Dorso",draft.document_back_path]].map(([kind,label,path])=><div key={kind} style={{padding:10,border:"1px solid var(--line)",borderRadius:11,background:"var(--panelSolid)"}}><b style={{display:"block",fontSize:11}}>{label}</b><small style={{display:"block",margin:"3px 0 8px",fontSize:9.5,color:path?"#278452":"var(--muted)"}}>{path?"Documento cargado":"Sin archivo"}</small><div style={{display:"flex",gap:6}}><label style={fileButton}>＋ Subir<input type="file" accept="image/*,.pdf" hidden onChange={event=>{const file=event.target.files?.[0];event.target.value="";if(file)onUpload(kind,file)}}/></label>{path?<button type="button" onClick={()=>onOpenDocument(path)} style={fileButton}>Abrir</button>:null}</div></div>)}</div></section>
    <section style={{...section,marginTop:10}}><h3 style={{margin:"0 0 7px",fontSize:12.5}}>Observaciones</h3><textarea value={draft.notes||""} onChange={event=>onField("notes",event.target.value)} rows="3" style={{width:"100%",boxSizing:"border-box",resize:"vertical",border:"1px solid var(--line)",borderRadius:10,padding:10,background:"var(--panelSolid)",color:"var(--text)",font:"inherit",fontSize:10.5}}/></section>
    <style>{`@media(max-width:760px){[aria-label="Datos del huésped y acompañantes"] main section>div{grid-template-columns:1fr 1fr!important}}@media(max-width:520px){[aria-label="Datos del huésped y acompañantes"] main section>div{grid-template-columns:1fr!important}}`}</style>
  </>
}
