"use client"

import s from"./reservations.module.css"

const fmtDate=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(`${value}T12:00:00`)):"—"
const paymentLabel=value=>value==="paid"?"Pagado":value==="pending"?"Parcial":"Pendiente"
const statusLabel=value=>value==="alojado"?"En hotel":value==="finalizada"?"Finalizada":value==="cancelada"?"Cancelada":value==="tentativa"?"Tentativa":value==="pendiente"?"Pendiente":"Confirmada"
const resultStatus=item=>item.estado==="cancelada"?"Cancelada":item.no_show?"No Show":statusLabel(item.estado)

export default function ReservationsListView({mode,modeCounts,modeTitle,searching,reservationSearch,onSearchChange,onClearSearch,onSelectMode,sortMode,onSort,filterOpen,onToggleFilter,paymentFilter,onPaymentFilter,dataError,visible,loading,itemsCount,hasMore,loadingMore,onLoadMore,saving,onRestore,onCheckout,onCheckin,onOpenRecord,onNoShow,onCancel}){
  return <section className={s.page}>
    <header className={s.heading}>
      <div><small>{searching?"BÚSQUEDA EN TODAS LAS RESERVAS":mode==="noshow"?"ARCHIVO OPERATIVO":mode==="trash"?"HISTORIAL":"RESERVAS"}</small><h1>{searching?"Resultados de reservas":modeTitle}</h1><p>{searching?`${visible.length} coincidencia${visible.length===1?"":"s"} para “${reservationSearch.trim()}” · activas, No Shows y canceladas.`:`${modeCounts[mode]||0} registros en esta carpeta.`}</p></div>
      <div style={{display:"flex",flexDirection:"column",alignItems:"flex-end",gap:9,width:"100%",maxWidth:820}}>
        <div className={s.search} style={{width:"min(440px,100%)",minWidth:0,boxShadow:searching?"0 8px 24px color-mix(in srgb,var(--accent) 10%,transparent)":"none",borderColor:searching?"color-mix(in srgb,var(--accent) 35%,var(--line))":"var(--line)"}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden="true" style={{flex:"0 0 auto"}}><circle cx="11" cy="11" r="6.5" stroke="currentColor" strokeWidth="1.8"/><path d="m16 16 4 4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></svg><input value={reservationSearch} onChange={event=>onSearchChange(event.target.value)} placeholder="Buscar reservas por huésped, ID o habitación" aria-label="Buscar dentro de todas las reservas"/>{searching?<button type="button" onClick={onClearSearch} aria-label="Limpiar búsqueda" title="Limpiar búsqueda" style={{width:28,height:28,border:0,borderRadius:8,background:"color-mix(in srgb,var(--accent) 8%,transparent)",color:"var(--muted)",font:"inherit",fontSize:18,lineHeight:1,cursor:"pointer",display:"grid",placeItems:"center"}}>×</button>:null}</div>
        <div className={s.tools}><button type="button" className={`${s.tool} ${!searching&&mode==="active"?s.toolActive:""}`} onClick={()=>onSelectMode("active")}>Reservas activas · {modeCounts.active}</button><button type="button" className={`${s.tool} ${!searching&&mode==="noshow"?s.toolActive:""}`} onClick={()=>onSelectMode("noshow")} title="Carpeta de huéspedes que no se presentaron">⊘ No Shows · {modeCounts.noshow}</button><button type="button" className={`${s.tool} ${!searching&&mode==="trash"?s.toolActive:""}`} onClick={()=>onSelectMode("trash")}>♲ Canceladas · {modeCounts.trash}</button><select className={s.tool} value={sortMode} onChange={event=>onSort(event.target.value)} aria-label="Ordenar reservas"><option value="created-desc">Últimas creadas</option><option value="created-asc">Primeras creadas</option><option value="arrival-next">Próximas llegadas</option><option value="arrival-desc">Llegadas más lejanas</option></select><button type="button" className={`${s.tool} ${filterOpen||paymentFilter!=="all"?s.toolActive:""}`} onClick={onToggleFilter} aria-label="Filtrar por estado de pago">Pago</button></div>
      </div>
    </header>
    {dataError&&<div className={s.empty}>{dataError}</div>}
    {filterOpen&&<div className={s.filterPanel}><span>Pago</span>{[["all","Todos"],["paid","Pagado"],["pending","Parcial"],["due","Pendiente"]].map(([value,label])=><button type="button" key={value} className={paymentFilter===value?s.selectedFilter:""} onClick={()=>onPaymentFilter(value)}>{label}</button>)}</div>}
    <div className={s.tableWrap}><table className={s.table}><thead><tr><th>ID</th><th>Cliente</th><th>Habitación</th><th>Llegada</th><th>Salida</th><th>Pago</th><th>Acciones</th></tr></thead><tbody>{visible.map(item=>{const names=(item.rooms||[]).map(room=>room.nombre),cancelled=item.estado==="cancelada";return <tr key={item.id}><td className={s.id}>{item.numero_reserva||item.id}</td><td className={s.client}><b>{item.nombre_huesped}</b><small>{item.canal_reserva||"Directa"}{searching?` · ${resultStatus(item)}`:""}</small></td><td><span className={s.room}><span className={s.roomBadge}>{names[0]||"—"}{names.length>1?` +${names.length-1}`:""}</span><i className={s.roomDot}/></span></td><td>{fmtDate(item.fecha_entrada)}</td><td>{fmtDate(item.fecha_salida)}</td><td><span className={`${s.payment} ${item.payment==="pending"?s.paymentPending:item.payment==="due"?s.paymentDue:""}`}>{paymentLabel(item.payment)}</span></td><td><div className={s.actions}>{cancelled?<button type="button" className={s.actionButton} disabled={saving===String(item.id)} onClick={()=>onRestore(item)}>↺ Restaurar</button>:<><button type="button" className={`${s.actionButton} ${s.checkin} ${item.estado==="alojado"?s.checked:""}`} disabled={saving===String(item.id)||item.estado==="finalizada"||item.no_show} onClick={()=>item.estado==="alojado"?onCheckout(item):onCheckin(item)}>{item.estado==="alojado"?"← Check-out":"→ Check-in"}</button><button type="button" className={s.actionButton} onClick={()=>onOpenRecord(item)} title="Abrir ficha completa">◉</button><button type="button" className={s.actionButton} disabled={saving===String(item.id)||item.estado==="alojado"||item.estado==="finalizada"} onClick={()=>onNoShow(item)} title={item.no_show?"Reabrir No Show":"Marcar No Show"}>{item.no_show?"↺":"⊘"}</button><button type="button" className={s.actionButton} disabled={saving===String(item.id)||item.no_show||item.estado==="finalizada"} onClick={()=>onCancel(item)} title="Cancelar">⌫</button></>}</div></td></tr>})}</tbody></table>{loading?<div className={s.empty}>Cargando reservas…</div>:!visible.length&&<div className={s.empty}>{searching?`No encontramos reservas que coincidan con “${reservationSearch.trim()}”.`:mode==="noshow"?"No hay No Shows en esta carpeta.":mode==="trash"?"No hay reservas canceladas.":"No hay reservas que coincidan con esta vista."}</div>}</div>
    <div className={s.footer}><span>{searching?`Mostrando ${visible.length} coincidencia${visible.length===1?"":"s"} entre ${itemsCount} reservas cargadas`:`Mostrando ${visible.length} de ${modeCounts[mode]||0} en esta carpeta`}</span><span>{hasMore?(searching?"Hay más historial disponible: cargalo para ampliar la búsqueda.":"Hay más historial disponible."):"Historial cargado hasta el último registro disponible."}</span>{hasMore&&<button type="button" className={s.tool} disabled={loadingMore} onClick={onLoadMore}>{loadingMore?"Cargando…":"Cargar 200 más"}</button>}</div>
  </section>
}
