"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import{reservationRoomingRows,reservationRoomingSummary}from"../planning/RoomingEditor"
import ReservationChannelLogo,{channelMeta}from"../planning/ReservationChannelLogo"
import ReservationChargePanel from"./ReservationChargePanel"
import ReservationFolioBilling from"./ReservationFolioBilling"
import s from"./reservationRecord.module.css"

const fmtDate=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${String(value).slice(0,10)}T12:00:00`)).replace(".",""):"—"
const fmtDateTime=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value)).replace(".",""):"—"
const money=(value,currency="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:0}).format(Number(value)||0)
const eventDay=value=>value?new Intl.DateTimeFormat("en-CA",{timeZone:"America/Argentina/Buenos_Aires",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(value)):""
const statusLabel=item=>item.no_show?"No-show":item.estado==="alojado"?"En hotel":item.estado==="finalizada"?"Finalizada":item.estado==="cancelada"?"Cancelada":item.estado==="tentativa"?"Tentativa":item.estado==="pendiente"?"Pendiente":"Confirmada"
const initials=name=>String(name||"H").trim().split(/\s+/).map(part=>part[0]).join("").slice(0,2).toUpperCase()
const TAX_LABELS={unset:"Sin definir",standard:"IVA normal",review:"Revisar exención",exempt:"Exento validado"}
const RETURN_TARGETS=new Set(["tasks","requests","housekeeping","services","finance","dailycash","quotes","messages","audit","guests"])
const RETURN_KEY="hl:pms:return-reservation"

function EmptyCard({text,action,onAction}){return <div className={s.emptyCard}><span>{text}</span>{action&&onAction?<button type="button" onClick={onAction}>{action}</button>:null}</div>}
function RecordCard({title,action,onAction,headerExtra,children}){return <section className={s.card}><header><h3>{title}</h3>{headerExtra||action&&onAction?<>{headerExtra||<button type="button" onClick={onAction}>＋ {action}</button>}</>:null}</header>{children}</section>}

function historyPresentation(event,fallbackCurrency="ARS"){
  const payload=event?.payload||{},currency=payload.after_currency||payload.before_currency||payload.currency||fallbackCurrency||"ARS"
  if(event?.event_type==="account"&&payload.before_rate!=null&&payload.after_rate!=null){
    const beforeRate=Number(payload.before_rate)||0,afterRate=Number(payload.after_rate)||0,beforeTotal=Number(payload.before_total)||0,afterTotal=Number(payload.after_total)||0
    const movement=afterRate>beforeRate?"Upgrade":afterRate<beforeRate?"Downgrade":"Cambio de tarifa"
    return{title:`${afterRate>beforeRate?"↑ ":afterRate<beforeRate?"↓ ":""}${movement} de tarifa`,detail:`Tarifa ${money(beforeRate,currency)} → ${money(afterRate,currency)} por noche · Total ${money(beforeTotal,currency)} → ${money(afterTotal,currency)}`}
  }
  if(event?.event_type==="room"&&payload.before_room_id!=null&&payload.after_room_id!=null)return{title:"Cambio de habitación",detail:`Habitación ${payload.before_room_id} → ${payload.after_room_id}`}
  if(event?.event_type==="stay"&&(payload.before_start||payload.after_start)){const before=`${fmtDate(payload.before_start)} → ${fmtDate(payload.before_end)}`,after=`${fmtDate(payload.after_start)} → ${fmtDate(payload.after_end)}`;return{title:"Estadía modificada",detail:`${before} · ahora ${after}`}}
  return{title:event?.title||event?.event_type||"Movimiento de reserva",detail:event?.detail||"Cambio registrado en la reserva."}
}

function serviceLines(item,room,rooms=[]){
  const lines=[],assigned=rooms.length?rooms:[room].filter(Boolean)
  const nights=Math.max(1,Number(item.noches)||Math.round((new Date(`${item.fecha_salida}T12:00:00`)-new Date(`${item.fecha_entrada}T12:00:00`))/86400000)||1)
  const stayAmount=Number(item.tarifa_noche||0)*nights||Number(item.subtotal||item.precio_total||0)
  if(assigned.length>1)lines.push({key:"stay",title:`Alojamiento grupal · ${assigned.length} habitaciones`,meta:`${item.regimen||"Alojamiento"} · ${nights} noche${nights===1?"":"s"}`,detail:`${assigned.map(item=>item.nombre).join(", ")} · ${fmtDate(item.fecha_entrada)} al ${fmtDate(item.fecha_salida)}`,amount:stayAmount})
  else lines.push({key:"stay",title:`${room?.tipo||"Habitación"} ${room?.nombre||""}`.trim(),meta:`${item.regimen||"Alojamiento"} · ${nights} noche${nights===1?"":"s"}`,detail:`Estadía del ${fmtDate(item.fecha_entrada)} al ${fmtDate(item.fecha_salida)}`,amount:stayAmount})
  const services=Array.isArray(item.servicios)?item.servicios:[]
  services.forEach((service,index)=>{const qty=Number(service?.cantidad||service?.qty||1)||1,unit=Number(service?.precio||service?.price||service?.importe||0),total=Number(service?.total||service?.precio_total||unit*qty),chargedNights=Number(service?.noches||0),metaParts=[];if(qty>1)metaParts.push(`${qty} unidades`);if(chargedNights>0)metaParts.push(`${chargedNights} noche${chargedNights===1?"":"s"}`);lines.push({key:`service-${service?.id||index}`,title:service?.nombre||service?.name||service?.descripcion||"Servicio",meta:metaParts.join(" · ")||"Servicio",detail:service?.detalle||service?.detail||"",amount:total})})
  if(Number(item.cochera_total)>0)lines.push({key:"parking",title:"Cochera",meta:"Adicional de estadía",detail:"",amount:Number(item.cochera_total)})
  if(Number(item.mascotas_total)>0)lines.push({key:"pets",title:"Mascotas",meta:"Adicional de estadía",detail:"",amount:Number(item.mascotas_total)})
  if(Number(item.early_checkin_importe)>0)lines.push({key:"early",title:"Early check-in",meta:"Servicio adicional",detail:"",amount:Number(item.early_checkin_importe)})
  if(Number(item.late_checkout_importe)>0)lines.push({key:"late",title:"Late check-out",meta:"Servicio adicional",detail:"",amount:Number(item.late_checkout_importe)})
  if(Number(item.extra)>0)lines.push({key:"extra",title:item.extra_descripcion||"Extra",meta:"Cargo adicional",detail:"",amount:Number(item.extra)})
  const discountAmount=Math.max(0,Number(item.descuento_importe)||0)
  if(discountAmount>0){
    const type=String(item.descuento_tipo||"").toLowerCase(),value=Math.max(0,Number(item.descuento_valor)||0),isPercent=type==="percent"||type==="porcentaje"
    const reason=String(item.descuento_motivo||"").trim()||"Motivo no documentado"
    const origin=String(item.descuento_origen||"manual").toLowerCase(),originLabel=origin==="rule"?"Regla configurada":origin==="promotion"?"Promoción configurada":origin==="package"?"Paquete":origin==="channel"?"Canal":"Ingresado manualmente"
    lines.push({key:"discount",kind:"discount",title:isPercent&&value>0?`Descuento ${value}%`:"Descuento aplicado",meta:`${originLabel} · −${money(discountAmount,item.moneda)}`,detail:reason,amount:-discountAmount})
  }
  return lines
}

export default function ReservationRecord({item,room,rooms=[],payments=[],propertyId,onBack,onNavigate,onPrimaryAction,saving}){
  const[events,setEvents]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[sideTab,setSideTab]=useState("internal"),[taxSaving,setTaxSaving]=useState(false),[noteDraft,setNoteDraft]=useState(item.notas||""),[noteSaving,setNoteSaving]=useState(false),[noteStatus,setNoteStatus]=useState(""),[chargeOpen,setChargeOpen]=useState(false),[,setChargeRevision]=useState(0),[historyDate,setHistoryDate]=useState(""),[historyOpen,setHistoryOpen]=useState(true)
  useEffect(()=>{setSideTab("internal");setNoteDraft(item.notas||"");setNoteStatus("");setChargeOpen(false);setHistoryDate("");setHistoryOpen(true)},[item.id])
  useEffect(()=>{let cancelled=false;async function load(){if(!item?.id||!propertyId)return;setLoading(true);setError("");try{const eventsRes=await supabase.from("hotel_reservation_events").select("id,event_type,title,detail,payload,actor_name,created_at").eq("property_id",propertyId).eq("reservation_id",item.id).order("created_at",{ascending:false}).limit(500);if(eventsRes.error)throw eventsRes.error;if(!cancelled){const nextEvents=eventsRes.data||[];setEvents(nextEvents);setHistoryDate(nextEvents.length?eventDay(nextEvents[0].created_at):"")}}catch(err){if(!cancelled)setError(err?.message||"No se pudo cargar el detalle operativo de la reserva.")}finally{if(!cancelled)setLoading(false)}}load();return()=>{cancelled=true}},[item?.id,propertyId])

  const itemPayments=useMemo(()=>payments.filter(payment=>Number(payment.reserva_id)===Number(item.id)&&!["anulado","cancelado","void"].includes(String(payment.estado||"").toLowerCase())),[payments,item.id])
  const paid=useMemo(()=>itemPayments.reduce((sum,payment)=>sum+Math.max(0,Number(payment.monto||0)-Number(payment.refunded_amount||0)),0),[itemPayments])
  const historyEvents=useMemo(()=>historyDate?events.filter(event=>eventDay(event.created_at)===historyDate):[],[events,historyDate])
  const assigned=rooms.length?rooms:[room].filter(Boolean),articles=serviceLines(item,room,assigned),total=Number(item.precio_total)||0,balance=Math.max(0,total-paid),nights=Math.max(1,Number(item.noches)||Math.round((new Date(`${item.fecha_salida}T12:00:00`)-new Date(`${item.fecha_entrada}T12:00:00`))/86400000)||1)
  const chargesTotal=articles.reduce((sum,line)=>sum+Number(line.amount||0),0),pricingMismatch=Math.abs(chargesTotal-total)>.5
  const roomSummary=assigned.length>1?`${assigned.length} habitaciones · ${assigned.map(item=>item.nombre).join(", ")}`:room?.nombre?`Habitación ${room.nombre}`:"Sin habitación"
  const roomingRows=reservationRoomingRows(item,assigned),roomingSummary=reservationRoomingSummary(item,assigned)
  const taxEvent=events.find(event=>event.event_type==="tax_profile_updated"),taxStatus=taxEvent?.payload?.iva_status||"unset",channel=channelMeta(item.canal_reserva)

  function navigateFromRecord(target,options){
    if(typeof window!=="undefined"&&RETURN_TARGETS.has(target))try{window.sessionStorage.setItem(RETURN_KEY,JSON.stringify({id:Number(item.id),name:item.nombre_huesped||"",code:item.numero_reserva||item.id}))}catch{}
    onNavigate?.(target,options)
  }
  function registerPayment(){navigateFromRecord("dailycash",{cashReservationId:Number(item.id),restoreScroll:false})}
  async function saveInternalNote(){if(noteSaving)return;setNoteSaving(true);setError("");setNoteStatus("");try{const value=noteDraft.trim();const{error:updateError}=await supabase.from("reservas").update({notas:value||null}).eq("id",item.id).eq("property_id",propertyId);if(updateError)throw updateError;setNoteDraft(value);setNoteStatus("Nota guardada")}catch(err){setError(err?.message||"No se pudo guardar la nota interna.")}finally{setNoteSaving(false)}}
  async function saveTaxStatus(nextStatus){if(taxSaving)return;setTaxSaving(true);setError("");try{const label=TAX_LABELS[nextStatus]||"Estado fiscal actualizado";const{data,error:insertError}=await supabase.from("hotel_reservation_events").insert({property_id:propertyId,reservation_id:item.id,event_type:"tax_profile_updated",title:`IVA · ${label}`,detail:`Marcado manualmente desde la ficha de la reserva${item.pais_huesped?` · País: ${item.pais_huesped}`:""}.`,payload:{iva_status:nextStatus,manual:true,country:item.pais_huesped||null}}).select("id,event_type,title,detail,payload,actor_name,created_at").single();if(insertError)throw insertError;setEvents(current=>[data,...current]);setHistoryDate(eventDay(data.created_at))}catch(err){setError(err?.message||"No se pudo guardar el estado de IVA.")}finally{setTaxSaving(false)}}

  const taxShell={display:"grid",gridTemplateColumns:"minmax(180px,.7fr) minmax(260px,1.3fr)",gap:12,padding:"12px"}
  const taxInfo={padding:"11px",border:"1px solid var(--line)",borderRadius:10,background:"color-mix(in srgb,var(--bg) 55%,var(--panelSolid))"}
  const taxButtons={display:"flex",flexWrap:"wrap",gap:7,marginTop:9}
  const taxButton=status=>({height:32,padding:"0 10px",border:`1px solid ${taxStatus===status?"color-mix(in srgb,var(--accent) 55%,var(--line))":"var(--line)"}`,borderRadius:8,background:taxStatus===status?"color-mix(in srgb,var(--accent) 10%,var(--panelSolid))":"var(--panelSolid)",color:taxStatus===status?"var(--accent)":"var(--text)",font:"inherit",fontSize:11,fontWeight:800,cursor:taxSaving?"wait":"pointer"})

  return <div className={s.record}>
    <div className={s.recordTop}><button type="button" className={s.back} onClick={onBack}>← Reservas</button><div className={s.quickActions}><button type="button" onClick={()=>navigateFromRecord("messages")}>✉ Mensajes</button><button type="button" onClick={()=>navigateFromRecord("guests")}>◎ Huésped</button><button type="button" onClick={()=>navigateFromRecord("tasks")}>✓ Tarea</button><button type="button" onClick={()=>navigateFromRecord("audit")}>◇ Actividad</button></div></div>
    <div className={s.heroGrid}>
      <section className={s.heroCard}><div className={s.heroHeader}><span className={s.avatar}>{initials(item.nombre_huesped)}</span><div><h1>{item.nombre_huesped}</h1><p>{roomSummary} · Reserva {item.numero_reserva||item.id}</p></div><span className={`${s.status} ${item.estado==="alojado"?s.statusIn:item.estado==="pendiente"||item.estado==="tentativa"?s.statusWarn:""}`}>{statusLabel(item)} ✓</span></div><div className={s.heroFacts}><div><small>Llegada</small><b>{fmtDate(item.fecha_entrada)}</b></div><div><small>Salida</small><b>{fmtDate(item.fecha_salida)}</b></div><div><small>Ocupación</small><b>{item.cantidad_huespedes||1} huésped{Number(item.cantidad_huespedes||1)===1?"":"es"}</b></div><div><small>Noches</small><b>{nights}</b></div><div><small>Rooming</small><b>{roomingSummary}</b></div><div><small>{assigned.length>1?"Habitaciones":"Política"}</small><b>{assigned.length>1?assigned.length:item.estado==="tentativa"?"Tentativa":"Reserva activa"}</b></div><div><small>Régimen</small><b>{item.regimen||"Alojamiento"}</b></div><div><small>Canal</small><b style={{display:"inline-flex",alignItems:"center",gap:6}}><ReservationChannelLogo value={item.canal_reserva}/><span>{channel.label}</span></b></div><div><small>Teléfono</small><b>{item.telefono_huesped||"—"}</b></div><div><small>Recibida</small><b>{fmtDate(item.created_at)}</b></div><div className={s.contactFact}><small>Contacto</small><b>{item.email_huesped||"Sin email cargado"}</b></div></div></section>
      <aside className={s.sideCard}><nav>{[["internal","Interno"],["tasks","Tareas"],["requests","Peticiones"],["floors","Pisos"]].map(([value,label])=><button type="button" key={value} className={sideTab===value?s.tabActive:""} onClick={()=>setSideTab(value)}>{label}</button>)}</nav><div className={s.sideBody} style={sideTab==="internal"?{justifyContent:"flex-start",alignItems:"stretch"}:undefined}>{sideTab==="tasks"?<><p>Gestioná tareas vinculadas a esta estadía desde Operación.</p><button type="button" onClick={()=>navigateFromRecord("tasks")}>＋ Añadir tarea</button></>:sideTab==="requests"?<><p>Pedidos y solicitudes del huésped asociados a la reserva.</p><button type="button" onClick={()=>navigateFromRecord("requests")}>Abrir peticiones</button></>:sideTab==="floors"?<><p>{assigned.length>1?`Coordiná limpieza y estado de las ${assigned.length} habitaciones asignadas.`:"Estado de habitación, limpieza y coordinación de pisos."}</p><button type="button" onClick={()=>navigateFromRecord("housekeeping")}>Abrir Housekeeping</button></>:<div style={{display:"grid",gap:7,width:"100%"}}><strong style={{fontSize:10.5}}>Notas internas</strong><textarea value={noteDraft} onChange={event=>{setNoteDraft(event.target.value);setNoteStatus("")}} placeholder="Escribí información importante para el equipo…" rows="5" style={{width:"100%",minHeight:92,boxSizing:"border-box",resize:"vertical",border:"1px solid var(--line)",borderRadius:9,padding:"9px 10px",background:"color-mix(in srgb,var(--panelSolid) 88%,transparent)",color:"var(--text)",font:"inherit",fontSize:10.5,lineHeight:1.45,outline:"none",verticalAlign:"top"}}/><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:8}}><small style={{margin:0}}>{noteStatus||"Visible para el equipo del hotel"}</small><button type="button" disabled={noteSaving} onClick={saveInternalNote} style={{marginTop:0}}>{noteSaving?"Guardando…":"Guardar nota"}</button></div></div>}</div></aside>
    </div>
    {error?<div className={s.alert}>{error}</div>:null}
    <div style={{marginTop:12}}><RecordCard title="Rooming / habitaciones">{roomingRows.length?<div className={s.compactList}>{roomingRows.map(row=>{const parts=[];if(row.matrimonial)parts.push(`${row.matrimonial} matrimonial${row.matrimonial===1?"":"es"}`);if(row.individual)parts.push(`${row.individual} individual${row.individual===1?"":"es"}`);const changed=row.soldAs!==row.physicalCategory;return <div key={row.key}><span><b>Hab. {row.name} · vendida como {row.soldAs}</b><small>Asignada: {row.physicalCategory}{changed?" · categoría física distinta":""} · {row.guests} huésped{row.guests===1?"":"es"} · {parts.length?parts.join(" + "):"Rooming sin configurar"}</small></span><strong>{money(row.rate,item.moneda)}<small style={{display:"block",fontWeight:600,color:"var(--muted)"}}>/ noche</small></strong></div>})}</div>:<EmptyCard text="Esta reserva no tiene Rooming por habitación."/>}</RecordCard></div>
    <div className={s.contentGrid}><RecordCard title="Cargos" action="Agregar cargo" onAction={()=>setChargeOpen(true)}>{pricingMismatch?<div className={s.pricingWarning}><span>!</span><div><b>Los cargos no coinciden con el total de la reserva</b><small>Cargos: {money(chargesTotal,item.moneda)} · Total contractual: {money(total,item.moneda)}. No se creó ningún ajuste automático. Revisá el precio o registrá un descuento explícito con motivo.</small></div></div>:null}<div className={s.articleList}>{articles.map(line=><article key={line.key} className={line.kind==="discount"?s.discountLine:""}><div>{line.kind==="discount"?<span className={s.discountIcon}>%</span>:null}<b>{line.title}</b><small>{line.meta}</small>{line.detail?<p>{line.detail}</p>:null}</div><strong>{money(line.amount,item.moneda)}</strong></article>)}</div><footer className={s.articleTotal}><span className={s.totalLabel}>Total reserva</span><b>{money(total,item.moneda)}</b><small><span className={s.paidAmount}>Pagado {money(paid,item.moneda)}</span><span> · </span><span className={s.pendingAmount}>Pendiente {money(balance,item.moneda)}</span></small></footer></RecordCard><div className={s.financeGrid}>
      <div style={{gridColumn:"1",gridRow:"1 / span 2",minWidth:0}}><ReservationFolioBilling reservation={item} propertyId={propertyId} onNavigate={navigateFromRecord}/></div>
      <RecordCard title="Pagos" action="Registrar pago" onAction={registerPayment}>{itemPayments.length?<div className={s.compactList}>{itemPayments.map(payment=><div key={payment.id}><span><b>{payment.metodo||payment.source||"Pago"}</b><small>{fmtDateTime(payment.created_at)}{payment.referencia?` · ${payment.referencia}`:""}</small></span><strong>{money(Number(payment.monto||0)-Number(payment.refunded_amount||0),payment.moneda||item.moneda)}</strong></div>)}</div>:<EmptyCard text="No hay pagos registrados." action="Registrar pago" onAction={registerPayment}/>}</RecordCard>
      <RecordCard title="Historial" headerExtra={<div style={{display:"flex",alignItems:"center",gap:6}}><div className={s.historyFilter}><span>Fecha</span><input type="date" value={historyDate} onChange={event=>setHistoryDate(event.target.value)} aria-label="Filtrar historial por fecha"/></div><button type="button" onClick={()=>setHistoryOpen(value=>!value)} aria-expanded={historyOpen} aria-label={historyOpen?"Ocultar historial":"Mostrar historial"} title={historyOpen?"Ocultar historial":"Mostrar historial"}>{historyOpen?"▴":"▾"}</button></div>}>{historyOpen?(loading?<EmptyCard text="Cargando historial…"/>:!events.length?<EmptyCard text="Todavía no hay movimientos registrados para esta reserva."/>:historyEvents.length?<div style={{maxHeight:230,overflow:"auto"}}><div className={s.compactList}>{historyEvents.map(event=>{const view=historyPresentation(event,item.moneda);return <div key={event.id}><span><b>{view.title}</b><small>{view.detail}{event.actor_name?` · ${event.actor_name}`:" · Sistema"}</small></span><strong>{fmtDateTime(event.created_at)}</strong></div>})}</div></div>:<EmptyCard text="No hay movimientos registrados en esa fecha."/>):<EmptyCard text="Historial contraído."/>}</RecordCard>
    </div></div>
    <div style={{marginTop:12}}><RecordCard title="IVA / huésped extranjero"><div style={taxShell}><div style={taxInfo}><small style={{display:"block",fontSize:10,color:"var(--muted)"}}>PAÍS DE RESIDENCIA</small><b style={{display:"block",marginTop:3,fontSize:12}}>{item.pais_huesped||"No informado"}</b><small style={{display:"block",marginTop:10,fontSize:10,color:"var(--muted)"}}>ESTADO MANUAL</small><b style={{display:"block",marginTop:3,fontSize:12,color:taxStatus==="exempt"?"#18794e":taxStatus==="review"?"#a26800":"var(--text)"}}>{TAX_LABELS[taxStatus]||TAX_LABELS.unset}</b>{taxEvent?<small style={{display:"block",marginTop:5,color:"var(--muted)",fontSize:10}}>Actualizado {fmtDateTime(taxEvent.created_at)}</small>:null}</div><div style={taxInfo}><b style={{fontSize:11}}>Tratamiento de IVA</b><p style={{margin:"5px 0 0",fontSize:10,lineHeight:1.45,color:"var(--muted)"}}>Esta marca es operativa y manual. No modifica por sí sola una factura ni quita impuestos automáticamente; sirve para que recepción y Finanzas sepan si deben revisar la condición fiscal antes de emitir.</p><div style={taxButtons}><button type="button" disabled={taxSaving} style={taxButton("standard")} onClick={()=>saveTaxStatus("standard")}>IVA normal</button><button type="button" disabled={taxSaving} style={taxButton("review")} onClick={()=>saveTaxStatus("review")}>Revisar exención</button><button type="button" disabled={taxSaving} style={taxButton("exempt")} onClick={()=>saveTaxStatus("exempt")}>Exento validado</button></div></div></div></RecordCard></div>
    {chargeOpen?<ReservationChargePanel reservation={item} propertyId={propertyId} onClose={()=>setChargeOpen(false)} onSaved={({event})=>{if(event){setEvents(current=>[event,...current]);setHistoryDate(eventDay(event.created_at))}setChargeRevision(value=>value+1)}}/>:null}
    <div className={`${s.bottomBar} ${s.bottomBarActionsOnly}`}><div className={s.bottomActions}><button type="button" onClick={()=>onNavigate?.("planning")}>Ver en Planning</button><button type="button" className={s.primaryAction} disabled={saving||item.estado==="finalizada"} onClick={onPrimaryAction}>{item.estado==="alojado"?"Hacer check-out":"Hacer check-in"}</button></div></div>
  </div>
}