"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"

const blankGuest=(role="companion",roomId=null)=>({id:null,role,room_id:roomId||null,full_name:"",email:"",phone:"",document_type:"DNI",document_number:"",birth_date:"",sex:"",marital_status:"",cuil:"",nationality:"",address:"",city:"",province:"",country:"Argentina",postal_code:"",occupation:"",travel_reason:"",relationship:"",document_front_path:"",document_back_path:"",notes:""})
const clean=value=>String(value??"")

function Field({label,children,wide=false}){return <label style={{display:"grid",gap:5,gridColumn:wide?"span 2":"auto"}}><span style={{fontSize:9.5,fontWeight:850,color:"var(--muted)"}}>{label}</span>{children}</label>}
function Text({value,onChange,type="text",placeholder=""}){return <input type={type} value={value||""} onChange={event=>onChange(event.target.value)} placeholder={placeholder} style={{height:38,width:"100%",boxSizing:"border-box",border:"1px solid var(--line)",borderRadius:10,padding:"0 10px",background:"color-mix(in srgb,var(--panelSolid) 86%,transparent)",color:"var(--text)",font:"inherit",fontSize:11,fontWeight:720,outline:"none"}}/>}
function Select({value,onChange,children}){return <select value={value||""} onChange={event=>onChange(event.target.value)} style={{height:38,width:"100%",border:"1px solid var(--line)",borderRadius:10,padding:"0 10px",background:"color-mix(in srgb,var(--panelSolid) 86%,transparent)",color:"var(--text)",font:"inherit",fontSize:11,fontWeight:720,outline:"none"}}>{children}</select>}

export default function ReservationGuestPanel({item,rooms=[],propertyId,onClose,onSaved}){
  const[guests,setGuests]=useState([]),[selectedId,setSelectedId]=useState(""),[draft,setDraft]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("")
  const selected=useMemo(()=>guests.find(guest=>String(guest.id)===String(selectedId))||null,[guests,selectedId])
  const primary=useMemo(()=>guests.find(guest=>guest.role==="primary")||null,[guests])
  const companions=useMemo(()=>guests.filter(guest=>guest.role!=="primary"),[guests])

  async function fetchGuests(preferredId=null){
    const{data,error:loadError}=await supabase.from("hotel_reservation_guests").select("*").eq("property_id",propertyId).eq("reservation_id",item.id).order("sort_order",{ascending:true}).order("created_at",{ascending:true})
    if(loadError)throw loadError
    let rows=data||[]
    if(!rows.length){
      const primaryPayload={...blankGuest("primary",item.habitacion_id),property_id:propertyId,reservation_id:item.id,full_name:item.nombre_huesped||"",email:item.email_huesped||"",phone:item.telefono_huesped||"",document_type:item.tipo_documento_huesped||"DNI",document_number:item.dni_huesped||"",birth_date:item.fecha_nacimiento_huesped||"",nationality:item.nacionalidad_huesped||"",address:item.direccion_huesped||"",city:item.ciudad_huesped||"",province:item.provincia_estado_huesped||"",country:item.pais_huesped||"Argentina",sort_order:0}
      const inserted=await supabase.from("hotel_reservation_guests").insert(primaryPayload).select().single()
      if(inserted.error)throw inserted.error
      rows=[inserted.data]
    }
    rows=[...rows].sort((a,b)=>a.role==="primary"?-1:b.role==="primary"?1:(Number(a.sort_order)||0)-(Number(b.sort_order)||0))
    const target=rows.find(row=>String(row.id)===String(preferredId))||rows.find(row=>row.role==="primary")||rows[0]
    setGuests(rows);setSelectedId(String(target.id));setDraft({...target})
    return rows
  }

  useEffect(()=>{let cancelled=false;async function load(){setLoading(true);setError("");try{await fetchGuests()}catch(err){if(!cancelled)setError(err?.message||"No se pudieron cargar los huéspedes.")}finally{if(!cancelled)setLoading(false)}}load();return()=>{cancelled=true}},[item.id,propertyId])
  useEffect(()=>{if(selected)setDraft({...selected})},[selectedId])

  function setField(key,value){setNotice("");setError("");setDraft(current=>({...current,[key]:value}))}
  function selectPerson(guest){setSelectedId(String(guest.id));setDraft({...guest});setNotice("");setError("")}
  function addCompanion(){const roomId=rooms[0]?.id||item.habitacion_id||null,setId=`new-${Date.now()}`,next={...blankGuest("companion",roomId),id:setId,property_id:propertyId,reservation_id:item.id,sort_order:companions.length+1};setGuests(current=>[...current,next]);setSelectedId(setId);setDraft(next);setNotice("");setError("")}

  async function persistGuest(current=draft){
    if(!current?.full_name?.trim())throw new Error("Ingresá nombre y apellido.")
    const payload={property_id:propertyId,reservation_id:item.id,room_id:current.room_id?Number(current.room_id):null,role:current.role||"companion",full_name:current.full_name.trim(),email:clean(current.email).trim()||null,phone:clean(current.phone).trim()||null,document_type:clean(current.document_type).trim()||null,document_number:clean(current.document_number).trim()||null,birth_date:current.birth_date||null,sex:clean(current.sex).trim()||null,marital_status:clean(current.marital_status).trim()||null,cuil:clean(current.cuil).trim()||null,nationality:clean(current.nationality).trim()||null,address:clean(current.address).trim()||null,city:clean(current.city).trim()||null,province:clean(current.province).trim()||null,country:clean(current.country).trim()||null,postal_code:clean(current.postal_code).trim()||null,occupation:clean(current.occupation).trim()||null,travel_reason:clean(current.travel_reason).trim()||null,relationship:clean(current.relationship).trim()||null,document_front_path:current.document_front_path||null,document_back_path:current.document_back_path||null,notes:clean(current.notes).trim()||null,sort_order:Number(current.sort_order)||0,updated_at:new Date().toISOString()}
    let result
    if(current.id&&String(current.id).startsWith("new-")===false)result=await supabase.from("hotel_reservation_guests").update(payload).eq("id",current.id).eq("property_id",propertyId).select().single()
    else result=await supabase.from("hotel_reservation_guests").insert(payload).select().single()
    if(result.error)throw result.error
    if(result.data.role==="primary"){
      const patch={nombre_huesped:result.data.full_name,email_huesped:result.data.email,telefono_huesped:result.data.phone,tipo_documento_huesped:result.data.document_type,dni_huesped:result.data.document_number,fecha_nacimiento_huesped:result.data.birth_date,nacionalidad_huesped:result.data.nationality,direccion_huesped:result.data.address,ciudad_huesped:result.data.city,provincia_estado_huesped:result.data.province,pais_huesped:result.data.country,documento_path:result.data.document_front_path,documento_nombre:result.data.document_front_path?"Documento del huésped":null}
      const reservationUpdate=await supabase.from("reservas").update(patch).eq("id",item.id).eq("property_id",propertyId)
      if(reservationUpdate.error)throw reservationUpdate.error
    }
    setGuests(currentRows=>currentRows.map(row=>String(row.id)===String(current.id)?result.data:row));setSelectedId(String(result.data.id));setDraft({...result.data});onSaved?.();return result.data
  }

  async function save(){if(saving)return;setSaving(true);setError("");setNotice("");try{await persistGuest();setNotice(draft?.role==="primary"?"Datos del huésped principal guardados.":"Datos del acompañante guardados.")}catch(err){setError(err?.message||"No se pudieron guardar los datos.")}finally{setSaving(false)}}

  async function makePrimary(){if(saving||!draft||draft.role==="primary")return;setSaving(true);setError("");setNotice("");try{let person=draft;if(!person.id||String(person.id).startsWith("new-"))person=await persistGuest(person);else person=await persistGuest(person);const{data,error:rpcError}=await supabase.rpc("hl_set_reservation_primary_guest",{p_reservation_id:Number(item.id),p_guest_id:person.id});if(rpcError)throw rpcError;await fetchGuests(data?.id||person.id);setNotice(`${person.full_name} ahora es el huésped principal. La estadía y la tarifa no se modificaron.`);onSaved?.()}catch(err){setError(err?.message||"No se pudo cambiar el huésped principal.")}finally{setSaving(false)}}

  async function removeGuest(){if(!draft||draft.role==="primary")return;if(!window.confirm(`Quitar a ${draft.full_name||"este acompañante"} de la reserva?`))return;if(String(draft.id).startsWith("new-")){const remaining=guests.filter(row=>String(row.id)!==String(draft.id));setGuests(remaining);const next=remaining.find(row=>row.role==="primary")||remaining[0];setSelectedId(next?String(next.id):"");setDraft(next?{...next}:null);return}setSaving(true);setError("");const{error:deleteError}=await supabase.from("hotel_reservation_guests").delete().eq("id",draft.id).eq("property_id",propertyId);if(deleteError){setSaving(false);setError(deleteError.message);return}await fetchGuests(primary?.id);setSaving(false);onSaved?.()}

  async function uploadDocument(kind,file){if(!file||saving)return;setSaving(true);setError("");setNotice("");try{let persisted=draft;if(!persisted?.id||String(persisted.id).startsWith("new-"))persisted=await persistGuest(persisted);const ext=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg",path=`${propertyId}/${item.id}/${persisted.id}/${kind}-${Date.now()}.${ext}`;const uploaded=await supabase.storage.from("hotel-reservation-documents").upload(path,file,{contentType:file.type||undefined,upsert:false});if(uploaded.error)throw uploaded.error;const field=kind==="front"?"document_front_path":"document_back_path";const saved=await supabase.from("hotel_reservation_guests").update({[field]:path,updated_at:new Date().toISOString()}).eq("id",persisted.id).eq("property_id",propertyId).select().single();if(saved.error)throw saved.error;if(saved.data.role==="primary"&&kind==="front")await supabase.from("reservas").update({documento_path:path,documento_nombre:file.name}).eq("id",item.id).eq("property_id",propertyId);setGuests(rows=>rows.map(row=>String(row.id)===String(saved.data.id)?saved.data:row));setDraft({...saved.data});setSelectedId(String(saved.data.id));setNotice(kind==="front"?"Frente del documento cargado.":"Dorso del documento cargado.");onSaved?.()}catch(err){setError(err?.message||"No se pudo subir el documento.")}finally{setSaving(false)}}
  async function openDocument(path){if(!path)return;const{data,error:urlError}=await supabase.storage.from("hotel-reservation-documents").createSignedUrl(path,120);if(urlError){setError(urlError.message);return}window.open(data.signedUrl,"_blank","noopener,noreferrer")}

  const overlay={position:"fixed",inset:0,zIndex:275,display:"grid",placeItems:"center",padding:16,background:"rgba(12,20,38,.28)",backdropFilter:"blur(10px) saturate(1.1)",WebkitBackdropFilter:"blur(10px) saturate(1.1)"}
  const shell={width:"min(940px,calc(100vw - 26px))",maxHeight:"92vh",overflow:"hidden",display:"grid",gridTemplateRows:"auto 1fr auto",border:"1px solid color-mix(in srgb,#fff 34%,var(--line))",borderRadius:22,background:"color-mix(in srgb,var(--panelSolid) 84%,transparent)",boxShadow:"inset 0 1px color-mix(in srgb,#fff 60%,transparent),0 30px 90px rgba(18,30,58,.3)",backdropFilter:"blur(34px) saturate(1.48)",WebkitBackdropFilter:"blur(34px) saturate(1.48)"}
  const grid={display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:9}
  const section={padding:12,border:"1px solid var(--line)",borderRadius:13,background:"color-mix(in srgb,var(--bg) 36%,var(--panelSolid))"}
  const fileButton={height:36,padding:"0 11px",display:"inline-flex",alignItems:"center",justifyContent:"center",gap:6,border:"1px solid var(--line)",borderRadius:9,background:"var(--panelSolid)",color:"var(--text)",font:"inherit",fontSize:10.5,fontWeight:820,cursor:saving?"wait":"pointer"}
  const companionButton=active=>({padding:"9px 10px",minWidth:145,textAlign:"left",border:`1px solid ${active?"color-mix(in srgb,var(--accent) 42%,var(--line))":"var(--line)"}`,borderRadius:10,background:active?"color-mix(in srgb,var(--accent) 8%,var(--panelSolid))":"var(--panelSolid)",color:"var(--text)",font:"inherit",cursor:"pointer"})

  return <div style={overlay} onMouseDown={event=>event.target===event.currentTarget&&!saving&&onClose?.()}><section style={shell} role="dialog" aria-modal="true" aria-label="Datos del huésped y acompañantes">
    <header style={{padding:"16px 18px",display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:14,borderBottom:"1px solid var(--line)"}}><div><small style={{fontSize:10,fontWeight:900,letterSpacing:".1em",color:"var(--accent)"}}>{draft?.role==="primary"?"DATOS DEL HUÉSPED PRINCIPAL":"DATOS DEL ACOMPAÑANTE"}</small><h2 style={{margin:"4px 0 0",fontSize:20}}>{draft?.full_name||item.nombre_huesped||"Huésped"}</h2><p style={{margin:"5px 0 0",fontSize:10.5,color:"var(--muted)"}}>{draft?.role==="primary"?"Información personal, legal y documentación del titular de la reserva.":"Información personal y documentación del acompañante seleccionado."}</p></div><button type="button" disabled={saving} onClick={onClose} style={{width:38,height:38,border:"1px solid var(--line)",borderRadius:11,background:"var(--panel)",color:"var(--text)",fontSize:19}}>×</button></header>
    <main style={{padding:14,overflow:"auto"}}>{loading?<div style={{padding:34,textAlign:"center",color:"var(--muted)"}}>Cargando datos del huésped…</div>:draft?<>
      {(error||notice)?<div style={{marginBottom:10,padding:"9px 11px",border:`1px solid ${error?"color-mix(in srgb,var(--red) 30%,var(--line))":"color-mix(in srgb,#2e9b61 28%,var(--line))"}`,borderRadius:10,background:error?"color-mix(in srgb,var(--red) 7%,var(--panelSolid))":"color-mix(in srgb,#39a96c 7%,var(--panelSolid))",color:error?"var(--red)":"#26794d",fontSize:10.5,fontWeight:800}}>{error||notice}</div>:null}

      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,marginBottom:10,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}>{draft.role==="primary"?<span style={{padding:"6px 9px",borderRadius:999,background:"color-mix(in srgb,#2e9b61 10%,var(--panelSolid))",color:"#26794d",fontSize:9.5,fontWeight:900}}>✓ Huésped principal</span>:primary?<button type="button" onClick={()=>selectPerson(primary)} style={{height:32,padding:"0 10px",border:"1px solid var(--line)",borderRadius:9,background:"var(--panelSolid)",color:"var(--text)",font:"inherit",fontSize:10,fontWeight:820}}>← Volver a {primary.full_name}</button>:null}</div>{draft.role!=="primary"?<div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button type="button" onClick={makePrimary} disabled={saving} style={{height:34,padding:"0 11px",border:"1px solid color-mix(in srgb,#2e9b61 34%,var(--line))",borderRadius:9,background:"color-mix(in srgb,#2e9b61 7%,var(--panelSolid))",color:"#26794d",font:"inherit",fontSize:10,fontWeight:850}}>✓ Marcar como huésped principal</button><button type="button" onClick={removeGuest} disabled={saving} style={{height:34,padding:"0 10px",border:"1px solid color-mix(in srgb,var(--red) 30%,var(--line))",borderRadius:9,background:"transparent",color:"var(--red)",font:"inherit",fontSize:10,fontWeight:820}}>Quitar acompañante</button></div>:null}</div>

      <section style={section}><h3 style={{margin:"0 0 9px",fontSize:12.5}}>Identidad y contacto</h3><div style={grid}>
        <Field label="Nombre y apellido" wide><Text value={draft.full_name} onChange={v=>setField("full_name",v)}/></Field><Field label="Habitación"><Select value={draft.room_id||""} onChange={v=>setField("room_id",v)}><option value="">Sin asignar</option>{rooms.map(room=><option key={room.id} value={room.id}>Hab. {room.nombre}</option>)}</Select></Field><Field label="Vínculo"><Text value={draft.relationship} onChange={v=>setField("relationship",v)} placeholder={draft.role==="primary"?"Titular":"Pareja, hijo/a…"}/></Field>
        <Field label="Tipo de documento"><Select value={draft.document_type} onChange={v=>setField("document_type",v)}><option>DNI</option><option>Pasaporte</option><option>CI</option><option>CUIL</option><option>Otro</option></Select></Field><Field label="Número"><Text value={draft.document_number} onChange={v=>setField("document_number",v)}/></Field><Field label="CUIL"><Text value={draft.cuil} onChange={v=>setField("cuil",v)}/></Field><Field label="Fecha de nacimiento"><Text type="date" value={draft.birth_date} onChange={v=>setField("birth_date",v)}/></Field>
        <Field label="Sexo"><Select value={draft.sex} onChange={v=>setField("sex",v)}><option value="">Sin informar</option><option value="F">Femenino</option><option value="M">Masculino</option><option value="X">X / Otro</option></Select></Field><Field label="Estado civil"><Select value={draft.marital_status} onChange={v=>setField("marital_status",v)}><option value="">Sin informar</option><option>Soltero/a</option><option>Casado/a</option><option>Unión convivencial</option><option>Divorciado/a</option><option>Viudo/a</option></Select></Field><Field label="Nacionalidad"><Text value={draft.nationality} onChange={v=>setField("nationality",v)}/></Field><Field label="Teléfono"><Text value={draft.phone} onChange={v=>setField("phone",v)}/></Field><Field label="Email" wide><Text type="email" value={draft.email} onChange={v=>setField("email",v)}/></Field>
      </div></section>

      <section style={{...section,marginTop:10}}><h3 style={{margin:"0 0 9px",fontSize:12.5}}>Domicilio y viaje</h3><div style={grid}>
        <Field label="Domicilio" wide><Text value={draft.address} onChange={v=>setField("address",v)}/></Field><Field label="Localidad"><Text value={draft.city} onChange={v=>setField("city",v)}/></Field><Field label="Provincia / estado"><Text value={draft.province} onChange={v=>setField("province",v)}/></Field><Field label="País"><Text value={draft.country} onChange={v=>setField("country",v)}/></Field><Field label="Código postal"><Text value={draft.postal_code} onChange={v=>setField("postal_code",v)}/></Field><Field label="Ocupación"><Text value={draft.occupation} onChange={v=>setField("occupation",v)}/></Field><Field label="Motivo del viaje"><Select value={draft.travel_reason} onChange={v=>setField("travel_reason",v)}><option value="">Sin informar</option><option>Turismo</option><option>Trabajo</option><option>Evento</option><option>Salud</option><option>Visita familiar</option><option>Otro</option></Select></Field>
      </div></section>

      <section style={{...section,marginTop:10}}><h3 style={{margin:"0 0 5px",fontSize:12.5}}>Documentación</h3><p style={{margin:"0 0 10px",fontSize:9.8,lineHeight:1.45,color:"var(--muted)"}}>Frente y dorso del DNI, pasaporte u otro documento. Los archivos quedan privados dentro de la propiedad.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}>{[["front","Frente",draft.document_front_path],["back","Dorso",draft.document_back_path]].map(([kind,label,path])=><div key={kind} style={{padding:10,border:"1px solid var(--line)",borderRadius:11,background:"var(--panelSolid)"}}><b style={{display:"block",fontSize:11}}>{label}</b><small style={{display:"block",margin:"3px 0 8px",fontSize:9.5,color:path?"#278452":"var(--muted)"}}>{path?"Documento cargado":"Sin archivo"}</small><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><label style={fileButton}>＋ Subir<input type="file" accept="image/*,.pdf" hidden onChange={event=>{const file=event.target.files?.[0];event.target.value="";if(file)uploadDocument(kind,file)}}/></label>{path?<button type="button" onClick={()=>openDocument(path)} style={fileButton}>Abrir</button>:null}</div></div>)}</div></section>

      <section style={{...section,marginTop:10}}><h3 style={{margin:"0 0 7px",fontSize:12.5}}>Observaciones</h3><textarea value={draft.notes||""} onChange={event=>setField("notes",event.target.value)} rows="3" style={{width:"100%",boxSizing:"border-box",resize:"vertical",border:"1px solid var(--line)",borderRadius:10,padding:10,background:"var(--panelSolid)",color:"var(--text)",font:"inherit",fontSize:10.5}}/></section>

      {draft.role==="primary"?<section style={{...section,marginTop:10}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,flexWrap:"wrap"}}><div><h3 style={{margin:0,fontSize:12.5}}>Acompañantes</h3><p style={{margin:"3px 0 0",fontSize:9.7,color:"var(--muted)"}}>Agregá o completá los datos de las demás personas alojadas.</p></div><button type="button" onClick={addCompanion} disabled={saving} style={{height:36,padding:"0 12px",border:0,borderRadius:10,background:"linear-gradient(145deg,var(--accent),var(--accent2))",color:"#fff",font:"inherit",fontSize:10.5,fontWeight:850}}>＋ Agregar acompañante</button></div>{companions.length?<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:10}}>{companions.map((guest,index)=><button type="button" key={guest.id||index} onClick={()=>selectPerson(guest)} style={companionButton(false)}><small style={{display:"block",fontSize:8.8,color:"var(--muted)",fontWeight:850}}>ACOMPAÑANTE {index+1}</small><b style={{display:"block",marginTop:3,fontSize:11}}>{guest.full_name||"Sin nombre"}</b><span style={{display:"block",marginTop:2,fontSize:9.2,color:"var(--muted)"}}>{guest.room_id?`Hab. ${rooms.find(room=>Number(room.id)===Number(guest.room_id))?.nombre||guest.room_id}`:"Sin habitación"}</span></button>)}</div>:<p style={{margin:"10px 0 0",fontSize:10.2,color:"var(--muted)"}}>Todavía no hay acompañantes cargados.</p>}</section>:null}
    </>:null}</main>
    <footer style={{padding:"12px 16px",display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,borderTop:"1px solid var(--line)"}}><span style={{fontSize:9.5,color:"var(--muted)"}}>{primary?`Titular: ${primary.full_name||"sin nombre"} · ${companions.length} acompañante${companions.length===1?"":"s"}`:"Datos de huéspedes"}</span><div style={{display:"flex",gap:8}}><button type="button" disabled={saving} onClick={onClose} style={{height:39,padding:"0 13px",border:"1px solid var(--line)",borderRadius:10,background:"var(--panel)",color:"var(--text)",font:"inherit",fontWeight:820}}>Cerrar</button><button type="button" disabled={saving||!draft} onClick={save} style={{height:39,padding:"0 15px",border:0,borderRadius:10,background:"linear-gradient(145deg,var(--accent),var(--accent2))",color:"#fff",font:"inherit",fontWeight:850,opacity:saving?.65:1}}>{saving?"Guardando…":draft?.role==="primary"?"Guardar huésped":"Guardar acompañante"}</button></div></footer>
    <style>{`@media(max-width:760px){[aria-label="Datos del huésped y acompañantes"] main section>div{grid-template-columns:1fr 1fr!important}}@media(max-width:520px){[aria-label="Datos del huésped y acompañantes"] main section>div{grid-template-columns:1fr!important}}`}</style>
  </section></div>
}
