"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"

const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(String(value||""))
const roomIds=item=>[...new Set([item?.habitacion_id,...(item?.habitaciones_ids||[])].filter(Boolean).map(Number))]
const detailFor=(item,roomId)=>(Array.isArray(item?.habitaciones_detalle)?item.habitaciones_detalle:[]).find(row=>Number(row?.habitacion_id)===Number(roomId))||{}
const roomStart=(item,roomId)=>{const value=detailFor(item,roomId)?.fecha_entrada;return validDate(value)?String(value):item?.fecha_entrada}
const roomPlannedEnd=(item,roomId)=>{const value=detailFor(item,roomId)?.fecha_salida;return validDate(value)?String(value):item?.fecha_salida}
const roomEnd=(item,roomId)=>{const planned=roomPlannedEnd(item,roomId),release=item?.room_checkout_dates?.[String(roomId)];return validDate(release)&&String(release)<planned?String(release):planned}
const money=(value,currency="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:0}).format(Number(value)||0)
const normalize=value=>String(value||"").trim().toLowerCase()
const lockSnapshot=(item,isGroup)=>{const ids=isGroup?roomIds(item):[Number(item?.habitacion_id)].filter(Boolean),details=ids.map(id=>detailFor(item,id)),locked=details.filter(row=>Boolean(row?.movement_locked)),reasons=[...new Set(locked.map(row=>String(row?.movement_lock_reason||"").trim()).filter(Boolean))];return{locked:locked.length>0,reason:reasons.join(" · ")}}

export default function ReservationRoomChangeControl({item,roomId,start,end,currentRoom,selectedRoom,allRooms=[],busy=false,isGroup=false,onSelect}){
  const[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[options,setOptions]=useState([]),[query,setQuery]=useState(""),[mode,setMode]=useState("available")
  const[lockOpen,setLockOpen]=useState(false),[lockBusy,setLockBusy]=useState(false),[lockReason,setLockReason]=useState(""),[localLock,setLocalLock]=useState(null)
  const lockKey=JSON.stringify(item?.habitaciones_detalle||[])
  useEffect(()=>{setLocalLock(null)},[lockKey,item?.habitacion_id])
  const baseLock=lockSnapshot(item,isGroup),movementLocked=localLock?.locked??baseLock.locked,movementReason=localLock?.reason??baseLock.reason
  const currency=item.moneda||"ARS",currentRate=Number(item.tarifa_noche)||0,selected=selectedRoom||allRooms.find(room=>String(room.id)===String(roomId))||currentRoom
  const changed=selected&&currentRoom&&Number(selected.id)!==Number(currentRoom.id),categoryChanged=changed&&normalize(selected.tipo)!==normalize(currentRoom.tipo),rateDiff=changed?Number(selected.precio||0)-currentRate:0,direction=rateDiff>0?"upgrade":rateDiff<0?"downgrade":"change"
  const filtered=useMemo(()=>{const term=query.trim().toLowerCase();return options.filter(option=>(mode==="all"||option.available||option.current)&&(!term||`${option.room.nombre} ${option.room.tipo||""} ${option.reason||""}`.toLowerCase().includes(term)))},[options,query,mode])
  const availableCount=options.filter(option=>option.available&&!option.current).length,unavailableCount=options.filter(option=>!option.available&&!option.current).length

  async function loadOptions(){
    if(movementLocked){setError(`El movimiento de ${isGroup?"las habitaciones":"la habitación"} está bloqueado${movementReason?` · ${movementReason}`:""}. Desbloquealo antes de reasignar.`);return}
    if(isGroup){setError("Esta reserva tiene varias habitaciones. La reasignación grupal está protegida para no reemplazar el conjunto por accidente.");setOpen(true);return}
    setOpen(true);setLoading(true);setError("");setQuery("");setMode("available")
    try{
      const[resRes,blockRes]=await Promise.all([
        supabase.from("reservas").select("id,numero_reserva,nombre_huesped,habitacion_id,habitaciones_ids,habitaciones_detalle,room_checkout_dates,fecha_entrada,fecha_salida,estado,no_show").eq("property_id",item.property_id).neq("id",Number(item.id)).neq("estado","cancelada").eq("no_show",false).lt("fecha_entrada",end).gt("fecha_salida",start),
        supabase.from("bloqueos").select("id,habitacion_id,fecha_desde,fecha_hasta,motivo").eq("property_id",item.property_id).lt("fecha_desde",end).gt("fecha_hasta",start),
      ])
      if(resRes.error)throw resRes.error;if(blockRes.error)throw blockRes.error
      const reservations=resRes.data||[],blocks=blockRes.data||[],originalCategory=normalize(currentRoom?.tipo),selectedId=Number(roomId)
      const next=allRooms.map(room=>{
        const id=Number(room.id),current=id===selectedId,roomState=normalize(room.estado),conflict=reservations.find(row=>roomIds(row).includes(id)&&roomStart(row,id)<end&&roomEnd(row,id)>start),block=blocks.find(row=>Number(row.habitacion_id)===id),sameCategory=normalize(room.tipo)===originalCategory
        let available=true,reason="Disponible para toda la estadía"
        if(room.activa===false){available=false;reason="Habitación inactiva"}
        else if(["mantenimiento","fuera_servicio"].includes(roomState)){available=false;reason="Fuera de servicio / mantenimiento"}
        else if(conflict){available=false;reason=`Ocupada por ${conflict.nombre_huesped||conflict.numero_reserva||"otra reserva"} · ${roomStart(conflict,id)} → ${roomEnd(conflict,id)}`}
        else if(block){available=false;reason=`Bloqueada${block.motivo?` · ${block.motivo}`:""} · ${block.fecha_desde} → ${block.fecha_hasta}`}
        if(current){available=true;reason=Number(room.id)===Number(currentRoom?.id)?"Habitación actual de la reserva":"Cambio seleccionado"}
        return{room,current,available,reason,sameCategory,rateDiff:Number(room.precio||0)-currentRate}
      }).sort((a,b)=>Number(b.current)-Number(a.current)||Number(b.available&&b.sameCategory)-Number(a.available&&a.sameCategory)||Number(b.available)-Number(a.available)||(Number(a.room.precio)||0)-(Number(b.room.precio)||0)||String(a.room.nombre||"").localeCompare(String(b.room.nombre||""),"es",{numeric:true}))
      setOptions(next)
    }catch(err){setError(err?.message||"No se pudo comprobar la disponibilidad de las habitaciones.")}
    finally{setLoading(false)}
  }

  async function choose(option){
    if(busy||movementLocked||!option.available||option.current)return
    setLoading(true);setError("")
    try{const ok=await onSelect?.(String(option.room.id));if(ok!==false)setOpen(false)}catch(err){setError(err?.message||"No se pudo seleccionar esa habitación.")}finally{setLoading(false)}
  }

  function openLockDialog(){if(busy||lockBusy||changed)return;setLockReason(movementReason||"");setError("");setLockOpen(true)}
  async function saveLock(){
    if(lockBusy)return
    setLockBusy(true);setError("")
    try{
      const nextLocked=!movementLocked
      const{data,error:rpcError}=await supabase.rpc("hl_set_reservation_room_movement_lock",{p_reserva_id:Number(item.id),p_habitacion_id:isGroup?null:Number(item.habitacion_id),p_locked:nextLocked,p_reason:nextLocked?(lockReason.trim()||null):null})
      if(rpcError)throw rpcError
      const updated=data||item,snapshot=lockSnapshot(updated,isGroup)
      setLocalLock({locked:nextLocked?true:snapshot.locked,reason:nextLocked?(lockReason.trim()||""):snapshot.reason});setLockOpen(false);setOpen(false)
      if(typeof window!=="undefined"){
        window.dispatchEvent(new CustomEvent("hl:pms-toast",{detail:{title:nextLocked?"Movimiento bloqueado":"Movimiento desbloqueado",message:nextLocked?`${isGroup?"Las habitaciones quedan fijas":"La habitación queda fija"} hasta que se quite el bloqueo.`:"La reserva vuelve a permitir cambios de habitación."}}))
        window.dispatchEvent(new CustomEvent("hl:pms-reservation-updated",{detail:{reservationId:Number(item.id)}}))
      }
    }catch(err){setError(err?.message||"No se pudo cambiar el bloqueo de movimiento.")}
    finally{setLockBusy(false)}
  }

  const card={gridColumn:"span 2",padding:"10px 11px",border:movementLocked?"2px solid color-mix(in srgb,#111827 72%,var(--line))":"1px solid color-mix(in srgb,var(--accent) 18%,var(--line))",borderRadius:12,background:movementLocked?"color-mix(in srgb,#111827 4%,var(--panelSolid))":"color-mix(in srgb,var(--accent) 4%,var(--panelSolid))"}
  const changeDisabled=busy||isGroup||movementLocked,button={height:36,padding:"0 12px",border:"1px solid color-mix(in srgb,var(--accent) 30%,var(--line))",borderRadius:9,background:"color-mix(in srgb,var(--accent) 7%,var(--panelSolid))",color:"var(--accent)",font:"inherit",fontSize:10.5,fontWeight:900,cursor:changeDisabled?"not-allowed":"pointer",opacity:changeDisabled?0.55:1}
  const lockButton={height:36,padding:"0 11px",border:`1px solid ${movementLocked?"color-mix(in srgb,#111827 45%,var(--line))":"var(--line)"}`,borderRadius:9,background:movementLocked?"color-mix(in srgb,#111827 9%,var(--panelSolid))":"var(--panelSolid)",color:movementLocked?"var(--text)":"var(--muted)",font:"inherit",fontSize:10,fontWeight:900,cursor:busy||lockBusy||changed?"not-allowed":"pointer",opacity:busy||lockBusy||changed?0.55:1}
  return <>
    <div style={card}>
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div style={{minWidth:0,flex:"1 1 260px"}}><small style={{display:"block",fontSize:9.2,fontWeight:900,letterSpacing:".08em",color:"var(--muted)"}}>HABITACIÓN FÍSICA</small><b style={{display:"block",marginTop:3,fontSize:12.5,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>Hab. {selected?.nombre||"—"} · {selected?.tipo||"Sin categoría"}</b><small style={{display:"block",marginTop:2,fontSize:9.6,color:"var(--muted)"}}>{money(selected?.precio,item.moneda)}/noche configurado · disponibilidad validada contra el Planning</small></div><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap"}}><button type="button" onClick={openLockDialog} disabled={busy||lockBusy||changed} style={lockButton}>{movementLocked?"🔒 Desbloquear":"🔓 Bloquear movimiento"}</button><button type="button" onClick={loadOptions} disabled={changeDisabled} style={button}>{movementLocked?"🔒 Habitación fija":isGroup?"Reserva grupal":"Cambiar habitación"}</button></div></div>
      {movementLocked?<div style={{marginTop:8,padding:"8px 9px",border:"1px solid color-mix(in srgb,#111827 28%,var(--line))",borderRadius:9,background:"color-mix(in srgb,#111827 5%,var(--panelSolid))",fontSize:9.8,lineHeight:1.4}}><b>🔒 Movimiento de habitación bloqueado</b><span style={{display:"block",marginTop:2,color:"var(--muted)"}}>{isGroup?"Las habitaciones de esta reserva quedan fijas y no pueden moverse desde el Planning ni desde la ficha.":"Esta habitación queda fija y no puede moverse desde el Planning ni desde la ficha."}{movementReason?` Motivo: ${movementReason}.`:""} Para reasignar, primero desbloqueá el movimiento.</span></div>:null}
      {changed?<div style={{marginTop:8,padding:"8px 9px",border:`1px solid ${direction==="upgrade"?"color-mix(in srgb,#2f9b61 30%,var(--line))":direction==="downgrade"?"color-mix(in srgb,#c3832e 30%,var(--line))":"var(--line)"}`,borderRadius:9,background:"color-mix(in srgb,var(--panelSolid) 72%,transparent)",fontSize:9.8,lineHeight:1.45}}><b>{direction==="upgrade"?"↑ Upgrade seleccionado":direction==="downgrade"?"↓ Downgrade seleccionado":categoryChanged?"Cambio de categoría seleccionado":"Cambio de habitación seleccionado"}</b><span style={{display:"block",marginTop:2,color:"var(--muted)"}}>Hab. {currentRoom?.nombre} → Hab. {selected?.nombre}{categoryChanged?` · ${currentRoom?.tipo||"Sin categoría"} → ${selected?.tipo||"Sin categoría"}`:""}. {rateDiff!==0?`La tarifa destino es ${money(Math.abs(rateDiff),currency)} ${rateDiff>0?"mayor":"menor"} por noche. Al guardar vas a elegir si actualizás la tarifa o mantenés la actual.`:"La tarifa configurada es equivalente."}{rateDiff>0&&Number(item.paid)>0?" Si actualizás la tarifa, los pagos ya registrados se conservan y la diferencia quedará como saldo pendiente.":""}</span></div>:null}
      {changed?<small style={{display:"block",marginTop:6,color:"var(--muted)",fontSize:9.3}}>Guardá o descartá el cambio de habitación antes de bloquear el movimiento.</small>:null}
      {isGroup&&!movementLocked?<small style={{display:"block",marginTop:7,color:"var(--muted)",fontSize:9.5}}>La reserva ocupa varias habitaciones; el selector evita reemplazar todo el grupo. El botón de bloqueo fija todas las habitaciones del grupo.</small>:null}
      {error&&!open&&!lockOpen?<div style={{marginTop:8,padding:"8px 9px",border:"1px solid color-mix(in srgb,var(--red) 28%,var(--line))",borderRadius:9,background:"color-mix(in srgb,var(--red) 6%,var(--panelSolid))",color:"var(--red)",fontSize:9.7,fontWeight:780}}>{error}</div>:null}
    </div>
    {open?<div style={{position:"fixed",inset:0,zIndex:272,display:"grid",placeItems:"center",padding:16,background:"rgba(10,18,34,.3)",backdropFilter:"blur(9px) saturate(1.12)"}} onMouseDown={event=>event.target===event.currentTarget&&!loading&&setOpen(false)}><section role="dialog" aria-modal="true" aria-label="Cambiar habitación física" style={{width:"min(680px,calc(100vw - 28px))",maxHeight:"86vh",overflow:"hidden",display:"grid",gridTemplateRows:"auto auto 1fr",border:"1px solid color-mix(in srgb,#fff 34%,var(--line))",borderRadius:20,background:"color-mix(in srgb,var(--panelSolid) 88%,transparent)",boxShadow:"0 30px 90px rgba(15,27,50,.3)",backdropFilter:"blur(30px) saturate(1.45)"}}>
      <header style={{padding:"15px 16px",display:"flex",justifyContent:"space-between",gap:14,borderBottom:"1px solid var(--line)"}}><div><small style={{fontSize:9.5,fontWeight:900,letterSpacing:".09em",color:"var(--accent)"}}>REASIGNACIÓN FÍSICA</small><h3 style={{margin:"4px 0 0",fontSize:18}}>Cambiar habitación</h3><p style={{margin:"5px 0 0",fontSize:10.5,color:"var(--muted)"}}>{start} → {end} · priorizamos habitaciones de la misma categoría y mostramos las ocupadas antes de confirmar.</p></div><button type="button" disabled={loading} onClick={()=>setOpen(false)} style={{width:36,height:36,border:"1px solid var(--line)",borderRadius:10,background:"var(--panel)",color:"var(--text)",fontSize:18}}>×</button></header>
      <div style={{padding:"10px 12px",display:"flex",alignItems:"center",gap:8,flexWrap:"wrap",borderBottom:"1px solid var(--line)"}}><label style={{flex:"1 1 240px",height:36,display:"flex",alignItems:"center",gap:7,padding:"0 10px",border:"1px solid var(--line)",borderRadius:9,background:"var(--panelSolid)"}}>⌕<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar habitación o categoría" style={{width:"100%",border:0,outline:0,background:"transparent",color:"var(--text)",font:"inherit",fontSize:10.5}}/></label><button type="button" onClick={()=>setMode("available")} style={{height:34,padding:"0 10px",border:"1px solid var(--line)",borderRadius:9,background:mode==="available"?"color-mix(in srgb,var(--accent) 10%,var(--panelSolid))":"var(--panelSolid)",color:mode==="available"?"var(--accent)":"var(--text)",font:"inherit",fontSize:10,fontWeight:850}}>Disponibles · {availableCount}</button><button type="button" onClick={()=>setMode("all")} style={{height:34,padding:"0 10px",border:"1px solid var(--line)",borderRadius:9,background:mode==="all"?"color-mix(in srgb,var(--accent) 10%,var(--panelSolid))":"var(--panelSolid)",color:mode==="all"?"var(--accent)":"var(--text)",font:"inherit",fontSize:10,fontWeight:850}}>Todas · {options.length}</button></div>
      <div style={{padding:12,overflow:"auto"}}>{loading?<div style={{padding:30,textAlign:"center",color:"var(--muted)",fontSize:11}}>Comprobando ocupación, bloqueos y disponibilidad…</div>:error?<div style={{padding:"11px 12px",border:"1px solid color-mix(in srgb,var(--red) 28%,var(--line))",borderRadius:10,background:"color-mix(in srgb,var(--red) 6%,var(--panelSolid))",color:"var(--red)",fontSize:10.5,fontWeight:780}}>{error}</div>:<><div style={{display:"flex",justifyContent:"space-between",gap:8,marginBottom:9,fontSize:9.6,color:"var(--muted)"}}><span>{availableCount} habitaciones disponibles · {unavailableCount} no disponibles</span><span>Misma categoría primero</span></div><div style={{display:"grid",gap:7}}>{filtered.map(option=>{const room=option.room,diff=option.rateDiff,kind=diff>0?"upgrade":diff<0?"downgrade":"same",tone=!option.available?"var(--red)":kind==="upgrade"?"#2c8855":kind==="downgrade"?"#a36f25":"var(--accent)";return <button key={room.id} type="button" disabled={loading||!option.available||option.current} onClick={()=>choose(option)} style={{padding:"10px 11px",display:"grid",gridTemplateColumns:"1fr auto",gap:12,textAlign:"left",border:`1px solid ${option.current?"color-mix(in srgb,var(--accent) 30%,var(--line))":"var(--line)"}`,borderRadius:11,background:option.current?"color-mix(in srgb,var(--accent) 6%,var(--panelSolid))":"var(--panelSolid)",color:"var(--text)",font:"inherit",cursor:option.available&&!option.current?"pointer":"not-allowed",opacity:option.available||option.current?1:.68}}><span style={{minWidth:0}}><b style={{display:"block",fontSize:11.5}}>Hab. {room.nombre} · {room.tipo||"Sin categoría"}</b><small style={{display:"block",marginTop:3,fontSize:9.4,color:option.available?"var(--muted)":"var(--red)",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{option.reason}</small></span><span style={{textAlign:"right"}}><b style={{display:"block",fontSize:11,color:tone}}>{option.current?"SELECCIONADA":!option.available?"NO DISPONIBLE":option.sameCategory?"MISMA CATEGORÍA":kind==="upgrade"?"↑ UPGRADE":kind==="downgrade"?"↓ DOWNGRADE":"OTRA CATEGORÍA"}</b><small style={{display:"block",marginTop:3,fontSize:9.4,color:"var(--muted)"}}>{money(room.precio,currency)}/noche{option.available&&!option.current&&diff!==0?` · ${diff>0?"+":"−"}${money(Math.abs(diff),currency)}`:""}</small></span></button>})}{!filtered.length?<div style={{padding:24,textAlign:"center",color:"var(--muted)",fontSize:10.5}}>No hay habitaciones que coincidan con esta vista.</div>:null}</div></>}</div>
    </section></div>:null}
    {lockOpen?<div style={{position:"fixed",inset:0,zIndex:276,display:"grid",placeItems:"center",padding:16,background:"rgba(10,18,34,.32)",backdropFilter:"blur(10px) saturate(1.12)"}} onMouseDown={event=>event.target===event.currentTarget&&!lockBusy&&setLockOpen(false)}><section role="dialog" aria-modal="true" aria-label={movementLocked?"Desbloquear movimiento de habitación":"Bloquear movimiento de habitación"} style={{width:"min(470px,calc(100vw - 28px))",border:"1px solid color-mix(in srgb,#fff 34%,var(--line))",borderRadius:18,background:"color-mix(in srgb,var(--panelSolid) 92%,transparent)",boxShadow:"0 28px 80px rgba(15,27,50,.3)",backdropFilter:"blur(28px) saturate(1.4)",overflow:"hidden"}}>
      <header style={{padding:"15px 16px",display:"flex",justifyContent:"space-between",gap:12,borderBottom:"1px solid var(--line)"}}><div><small style={{fontSize:9.4,fontWeight:900,letterSpacing:".09em",color:"var(--accent)"}}>{movementLocked?"DESBLOQUEAR":"FIJAR HABITACIÓN"}</small><h3 style={{margin:"4px 0 0",fontSize:17}}>{movementLocked?"Permitir movimientos nuevamente":"Bloquear movimiento de habitación"}</h3><p style={{margin:"5px 0 0",fontSize:10.4,color:"var(--muted)",lineHeight:1.45}}>{movementLocked?"Después de desbloquear, recepción podrá volver a cambiar la habitación desde la ficha o el Planning.":isGroup?"Se fijarán todas las habitaciones de esta reserva. No podrán arrastrarse ni reasignarse hasta quitar el bloqueo.":`Hab. ${currentRoom?.nombre||selected?.nombre||"—"} quedará fija y no podrá arrastrarse ni reasignarse hasta quitar el bloqueo.`}</p></div><button type="button" disabled={lockBusy} onClick={()=>setLockOpen(false)} style={{width:35,height:35,border:"1px solid var(--line)",borderRadius:10,background:"var(--panel)",color:"var(--text)",fontSize:18}}>×</button></header>
      <div style={{padding:16}}>{error?<div style={{marginBottom:10,padding:"9px 10px",border:"1px solid color-mix(in srgb,var(--red) 28%,var(--line))",borderRadius:9,background:"color-mix(in srgb,var(--red) 6%,var(--panelSolid))",color:"var(--red)",fontSize:10,fontWeight:780}}>{error}</div>:null}{movementLocked?<div style={{padding:"10px 11px",border:"1px solid color-mix(in srgb,#111827 24%,var(--line))",borderRadius:10,background:"color-mix(in srgb,#111827 5%,var(--panelSolid))",fontSize:10.4,lineHeight:1.45}}><b>🔒 Actualmente bloqueada</b>{movementReason?<span style={{display:"block",marginTop:3,color:"var(--muted)"}}>Motivo: {movementReason}</span>:null}</div>:<label style={{display:"grid",gap:6,fontSize:10,fontWeight:850,color:"var(--muted)"}}>Motivo opcional<textarea value={lockReason} maxLength={240} onChange={event=>setLockReason(event.target.value)} placeholder="Ej.: huésped VIP, pedido expreso, habitación accesible…" style={{width:"100%",minHeight:76,boxSizing:"border-box",resize:"vertical",border:"1px solid var(--line)",borderRadius:10,padding:"10px 11px",background:"var(--panelSolid)",color:"var(--text)",font:"inherit",fontSize:11,outline:"none"}}/></label>}<div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:14}}><button type="button" disabled={lockBusy} onClick={()=>setLockOpen(false)} style={{height:38,padding:"0 13px",border:"1px solid var(--line)",borderRadius:9,background:"var(--panel)",color:"var(--text)",font:"inherit",fontWeight:850}}>Cancelar</button><button type="button" disabled={lockBusy} onClick={saveLock} style={{height:38,padding:"0 14px",border:0,borderRadius:9,background:movementLocked?"#111827":"linear-gradient(145deg,var(--accent),var(--accent2))",color:"#fff",font:"inherit",fontWeight:900,opacity:lockBusy?0.65:1}}>{lockBusy?"Guardando…":movementLocked?"Desbloquear movimiento":"🔒 Bloquear movimiento"}</button></div></div>
    </section></div>:null}
  </>
}
