"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"

const CASH_PREFILL_KEY="hl:pms:cash-prefill"
const dateKey=date=>date.toLocaleDateString("en-CA")
const fmtDate=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value}T12:00:00`)).replace(".",""):"—"
const money=(value,currency="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:0}).format(Number(value)||0)
function penaltyValue(rule,item){const value=Math.max(0,Number(rule?.value)||0),type=rule?.charge_type||"none";if(type==="fixed")return value;if(type==="percent")return Math.max(0,Number(item?.precio_total)||0)*value/100;if(type==="nights")return Math.max(0,Number(item?.tarifa_noche)||0)*value;return 0}
function ruleText(rule,currency="ARS"){const value=Math.max(0,Number(rule?.value)||0);if(rule?.charge_type==="fixed")return money(value,currency);if(rule?.charge_type==="percent")return`${value}% del total`;if(rule?.charge_type==="nights")return`${value} noche${value===1?"":"s"}`;return"Sin cargo"}

export default function ReservationNoShowDialog({item,onClose,onConfirm,onPay,saving,error}){
  const[penalty,setPenalty]=useState(false),[amount,setAmount]=useState(0),[note,setNote]=useState(""),[guarantee,setGuarantee]=useState(null),[loadingGuarantee,setLoadingGuarantee]=useState(false)
  const policy=item?.cancellation_policy_snapshot&&typeof item.cancellation_policy_snapshot==="object"?item.cancellation_policy_snapshot:{},policyRule=policy?.no_show_rule||{charge_type:"none",value:0},suggestedPenalty=penaltyValue(policyRule,item)
  useEffect(()=>{
    if(!item)return
    const snapshot=item.cancellation_policy_snapshot&&typeof item.cancellation_policy_snapshot==="object"?item.cancellation_policy_snapshot:{},rule=snapshot?.no_show_rule||{charge_type:"none",value:0},suggested=penaltyValue(rule,item)
    setPenalty(suggested>0);setAmount(suggested);setNote("");setGuarantee(null)
    let cancelled=false
    ;(async()=>{setLoadingGuarantee(true);try{const{data}=await supabase.from("hotel_guarantees").select("id,status,guarantee_type,provider,card_brand,last_four,authorized_amount,captured_amount,currency").eq("property_id",item.property_id).eq("reserva_id",item.id).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(!cancelled)setGuarantee(data||null)}finally{if(!cancelled)setLoadingGuarantee(false)}})()
    return()=>{cancelled=true}
  },[item?.id,item?.property_id,item?.cancellation_policy_id])
  useEffect(()=>{
    if(!item||typeof document==="undefined")return
    const previous=document.body.style.overflow
    document.body.style.overflow="hidden"
    return()=>{document.body.style.overflow=previous}
  },[item?.id])
  const today=useMemo(()=>dateKey(new Date()),[item?.id]),currency=item?.moneda||"ARS",paid=Math.max(0,Number(item?.paid)||0),penaltyAmount=Math.max(0,Number(amount)||0),arrived=today>=String(item?.fecha_entrada||""),withinStay=today<=String(item?.fecha_salida||"9999-12-31"),penaltyCovered=!penalty||penaltyAmount<=0||paid+0.01>=penaltyAmount,canMark=Boolean(item)&&arrived&&withinStay&&penaltyCovered
  if(!item)return null
  const card=guarantee?`${guarantee.card_brand||guarantee.guarantee_type||"Garantía"}${guarantee.last_four?` · •••• ${guarantee.last_four}`:""}`:item.garantia_ultimos4?`${item.garantia_marca||"Tarjeta"} · •••• ${item.garantia_ultimos4}`:null
  function payPenalty(){
    if(typeof window!=="undefined"&&penaltyAmount>0)try{window.sessionStorage.setItem(CASH_PREFILL_KEY,JSON.stringify({reservationId:Number(item.id),amount:penaltyAmount,reason:"no_show_penalty",createdAt:Date.now()}))}catch{}
    onPay?.(penaltyAmount)
  }
  const overlay={position:"fixed",inset:0,zIndex:275,display:"grid",placeItems:"center",padding:12,overflow:"hidden",overscrollBehavior:"contain",background:"rgba(15,22,36,.45)",backdropFilter:"blur(12px) saturate(1.08)"}
  const panel={width:"min(620px,calc(100vw - 24px))",maxHeight:"calc(100vh - 24px)",display:"flex",flexDirection:"column",minHeight:0,border:"1px solid color-mix(in srgb,var(--line) 82%,#fff)",borderRadius:22,background:"color-mix(in srgb,var(--panelSolid) 97%,transparent)",boxShadow:"0 28px 80px rgba(17,28,52,.32)",overflow:"hidden"}
  const button={height:40,padding:"0 14px",border:"1px solid var(--line)",borderRadius:11,background:"var(--panelSolid)",color:"var(--text)",font:"inherit",fontSize:11,fontWeight:850,cursor:saving?"wait":"pointer"}
  return <div style={overlay} role="dialog" aria-modal="true" aria-label="Marcar reserva como No Show"><section style={panel}>
    <header style={{display:"flex",justifyContent:"space-between",gap:16,padding:"18px 20px 14px",borderBottom:"1px solid var(--line)",flex:"0 0 auto"}}><div><small style={{display:"block",fontSize:10,fontWeight:900,letterSpacing:".12em",color:"#30343b",marginBottom:5}}>NO SHOW · LIBERAR INVENTARIO</small><h2 style={{margin:0,fontSize:20}}>Registrar huésped no presentado</h2><p style={{margin:"6px 0 0",fontSize:11,color:"var(--muted)"}}>{item.nombre_huesped} · Reserva {item.numero_reserva||item.id}</p></div><button type="button" onClick={onClose} disabled={saving} style={{...button,width:38,padding:0}}>×</button></header>
    <div style={{padding:"18px 20px",overflowY:"auto",minHeight:0,overscrollBehavior:"contain",WebkitOverflowScrolling:"touch"}}>
      <div style={{padding:"12px 13px",border:"1px solid var(--line)",borderRadius:12,background:"color-mix(in srgb,var(--bg) 45%,var(--panelSolid))",fontSize:11,lineHeight:1.55}}><b>Estadía original: {fmtDate(item.fecha_entrada)} → {fmtDate(item.fecha_salida)}</b><span style={{display:"block",marginTop:2,color:"var(--muted)"}}>Tarifa {money(item.tarifa_noche,currency)} / noche · Total original {money(item.precio_total,currency)}. Estos datos quedan congelados en el historial para informes y Finanzas.</span></div>
      {arrived&&withinStay?<div style={{marginTop:11,padding:"11px 12px",border:"1px solid color-mix(in srgb,#28a66a 34%,var(--line))",borderRadius:12,background:"color-mix(in srgb,#28a66a 7%,var(--panelSolid))",fontSize:10.5,lineHeight:1.5}}><small style={{display:"block",fontSize:9.5,fontWeight:900,letterSpacing:".08em",color:"#218b59"}}>CORTE OPERATIVO AUTOMÁTICO</small><b style={{display:"block",marginTop:3}}>La habitación se libera para nuevas llegadas desde {fmtDate(today)}</b><span style={{display:"block",marginTop:3,color:"var(--muted)"}}>No hace falta acortar manualmente la reserva. El sistema registra {fmtDate(today)} como fecha de liberación operativa, pero conserva {fmtDate(item.fecha_entrada)} → {fmtDate(item.fecha_salida)} y el total original para historial, Finanzas e informes.</span></div>:null}
      {!arrived?<div style={{marginTop:11,padding:"11px 12px",border:"1px solid color-mix(in srgb,#e45c70 40%,var(--line))",borderRadius:12,background:"color-mix(in srgb,#ef6579 7%,var(--panelSolid))",fontSize:11,color:"#d84960"}}>Todavía no llegó la fecha de check-in. El No Show sólo se registra desde el día de llegada.</div>:!withinStay?<div style={{marginTop:11,padding:"11px 12px",border:"1px solid color-mix(in srgb,#e45c70 40%,var(--line))",borderRadius:12,background:"color-mix(in srgb,#ef6579 7%,var(--panelSolid))",fontSize:11,color:"#d84960"}}>La estadía original ya terminó. Este caso conviene revisarlo desde historial antes de modificarlo.</div>:null}
      <div style={{marginTop:11,padding:"11px 12px",border:"1px solid color-mix(in srgb,var(--accent) 28%,var(--line))",borderRadius:12,background:"color-mix(in srgb,var(--accent) 5%,var(--panelSolid))",fontSize:10.5,lineHeight:1.5}}><b>Política de la reserva: {policy?.name||"Sin política histórica"}</b><span style={{display:"block",marginTop:3,color:"var(--muted)"}}>{policy?.description||"Esta reserva fue creada antes de que se asignaran políticas estructuradas."}</span><span style={{display:"block",marginTop:4,fontWeight:800,color:suggestedPenalty>0?"#9a6a00":"#218b59"}}>No Show previsto: {ruleText(policyRule,policy?.currency||currency)}{suggestedPenalty>0?` · sugerido ${money(suggestedPenalty,currency)}`:""}</span></div>
      <div style={{marginTop:12,display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}><article style={{padding:12,border:"1px solid var(--line)",borderRadius:12,background:"var(--panelSolid)"}}><small style={{fontSize:9.5,color:"var(--muted)"}}>GARANTÍA</small><b style={{display:"block",marginTop:4,fontSize:12}}>{loadingGuarantee?"Consultando…":card||"Sin garantía registrada"}</b>{guarantee?<small style={{display:"block",marginTop:3,color:"var(--muted)"}}>Estado: {guarantee.status||"—"}</small>:null}</article><article style={{padding:12,border:"1px solid var(--line)",borderRadius:12,background:"var(--panelSolid)"}}><small style={{fontSize:9.5,color:"var(--muted)"}}>YA COBRADO</small><b style={{display:"block",marginTop:4,fontSize:12}}>{money(paid,currency)}</b><small style={{display:"block",marginTop:3,color:"var(--muted)"}}>Pagos netos de la reserva</small></article></div>
      <div style={{marginTop:12,padding:13,border:"1px solid var(--line)",borderRadius:12}}><b style={{fontSize:11.5}}>Penalidad a aplicar</b><p style={{margin:"4px 0 0",fontSize:9.8,color:"var(--muted)"}}>La política propone el valor automáticamente. Recepción puede eximirlo si corresponde, dejando trazabilidad en la observación.</p><div style={{display:"flex",gap:8,marginTop:9,flexWrap:"wrap"}}><button type="button" onClick={()=>setPenalty(false)} style={{...button,borderColor:!penalty?"var(--accent)":"var(--line)",background:!penalty?"color-mix(in srgb,var(--accent) 8%,var(--panelSolid))":"var(--panelSolid)",color:!penalty?"var(--accent)":"var(--text)"}}>Eximir / no cobrar</button><button type="button" onClick={()=>{setPenalty(true);if(!Number(amount)&&suggestedPenalty>0)setAmount(suggestedPenalty)}} style={{...button,borderColor:penalty?"var(--accent)":"var(--line)",background:penalty?"color-mix(in srgb,var(--accent) 8%,var(--panelSolid))":"var(--panelSolid)",color:penalty?"var(--accent)":"var(--text)"}}>Aplicar penalidad</button></div>{penalty?<div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8,alignItems:"end",marginTop:10}}><label style={{display:"grid",gap:5,fontSize:10,color:"var(--muted)"}}>Importe de penalidad<input type="number" min="0" step="1" value={amount} onChange={event=>setAmount(event.target.value)} style={{height:38,border:"1px solid var(--line)",borderRadius:9,padding:"0 10px",background:"var(--panelSolid)",color:"var(--text)",font:"inherit"}}/></label>{!penaltyCovered?<button type="button" onClick={payPenalty} style={{...button,borderColor:"var(--accent)",background:"var(--accent)",color:"#fff"}}>Cobrar penalidad</button>:<span style={{height:38,display:"grid",placeItems:"center",padding:"0 12px",borderRadius:9,background:"color-mix(in srgb,#28a66a 8%,var(--panelSolid))",color:"#218b59",fontSize:10.5,fontWeight:850}}>Cobro cubierto ✓</span>}</div>:null}{penalty&&!penaltyCovered?<small style={{display:"block",marginTop:7,color:"#a26800"}}>Primero registrá el cobro. Recién después el sistema habilita el No Show.</small>:null}</div>
      <label style={{display:"grid",gap:5,marginTop:12,fontSize:10,color:"var(--muted)"}}>Observación interna<textarea rows="3" value={note} onChange={event=>setNote(event.target.value)} placeholder="Ej.: se llamó al huésped, no respondió…" style={{resize:"vertical",border:"1px solid var(--line)",borderRadius:10,padding:"9px 10px",background:"var(--panelSolid)",color:"var(--text)",font:"inherit",fontSize:11}}/></label>
      <div style={{marginTop:12,padding:"11px 12px",border:"1px solid color-mix(in srgb,#444 28%,var(--line))",borderRadius:12,background:"color-mix(in srgb,#111 3%,var(--panelSolid))",fontSize:10.5,lineHeight:1.5}}><b>Qué va a pasar</b><span style={{display:"block",marginTop:3,color:"var(--muted)"}}>Primero se valida la penalidad. Al confirmar, se corta la ocupación operativa en {fmtDate(today)}, la reserva pasa a No Show y deja de bloquear la habitación para nuevas ventas. La estadía original, la tarifa, el total y la política no se modifican: quedan guardados para trazabilidad.</span></div>
      {error?<div style={{marginTop:11,padding:"10px 11px",border:"1px solid color-mix(in srgb,#e45c70 40%,var(--line))",borderRadius:10,color:"#d84960",fontSize:10.5}}>{error}</div>:null}
      <div style={{display:"flex",justifyContent:"flex-end",gap:8,flexWrap:"wrap",marginTop:18,paddingTop:14,borderTop:"1px solid var(--line)"}}><button type="button" onClick={onClose} disabled={saving} style={button}>Cancelar</button><button type="button" disabled={saving||!canMark} onClick={()=>onConfirm?.({releaseDate:today,penaltyAmount:penalty?penaltyAmount:0,penaltyStatus:penalty?"charged":suggestedPenalty>0?"waived":"none",note:!penalty&&suggestedPenalty>0?`${note?`${note} · `:""}Penalidad prevista por política eximida manualmente.`:note})} style={{...button,borderColor:"#24272d",background:"#24272d",color:"#fff",opacity:canMark?1:.5}}>{saving?"Registrando…":"Confirmar No Show y liberar habitación"}</button></div>
    </div>
  </section></div>
}
