"use client"

import{useEffect,useMemo,useRef,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import useReservationsData from"./useReservationsData"
import ReservationRecord from"./ReservationRecord"
import ReservationEditPanel from"./ReservationEditPanel"
import ReservationActionBar from"./ReservationActionBar"
import ReservationStayActions from"./ReservationStayActions"
import ReservationCheckinDialog from"./ReservationCheckinDialog"
import ReservationNoShowDialog from"./ReservationNoShowDialog"
import ReservationRoomNoShowDialog from"./ReservationRoomNoShowDialog"
import ReservationRestoreNoShowDialog from"./ReservationRestoreNoShowDialog"
import ReservationRestoreCancelledDialog from"./ReservationRestoreCancelledDialog"
import ReservationCancellationDialog from"./ReservationCancellationDialog"
import ReservationsListView from"./ReservationsListView"
import CheckoutBalanceDialog from"./CheckoutBalanceDialog"
import ReservationGroupCheckoutDialog from"./ReservationGroupCheckoutDialog"
import{reservationCheckinProgress}from"./reservationEditUtils"

const money=(value,currency="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:2}).format(Number(value)||0)
const roomIds=item=>[...new Set([item.habitacion_id,...(item.habitaciones_ids||[])].filter(Boolean).map(Number))]
const logicalRoomIds=item=>{const details=Array.isArray(item?.habitaciones_detalle)?item.habitaciones_detalle:[],historicalRoles=new Set(["previous_room","transient_room","cancelled_room","no_show_room"]),active=new Set(details.filter(detail=>!historicalRoles.has(String(detail?.segment_role||"").toLowerCase())).map(detail=>Number(detail?.habitacion_id)).filter(Number.isFinite)),historical=new Set(details.filter(detail=>historicalRoles.has(String(detail?.segment_role||"").toLowerCase())).map(detail=>Number(detail?.habitacion_id)).filter(Number.isFinite));return roomIds(item).filter(id=>active.has(id)||!historical.has(id))}
const activeRoomIds=item=>{const released=new Set(Object.keys(item?.room_checkout_dates||{}).map(Number));const historical=new Set((Array.isArray(item?.habitaciones_detalle)?item.habitaciones_detalle:[]).filter(detail=>String(detail?.segment_role||"").toLowerCase()==="previous_room").map(detail=>Number(detail?.habitacion_id)).filter(Number.isFinite));const active=roomIds(item).filter(id=>!released.has(id)&&!historical.has(id));return active.length?active:[Number(item?.habitacion_id)].filter(Number.isFinite)}
const dateKey=date=>{const value=date instanceof Date?date:new Date(date);return`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`}
const normalizeSearch=value=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/\s+/g," ")
function paymentState(item,paid){const total=Number(item.precio_total)||0;if(total<=0)return"paid";if(paid<=0)return"due";if(paid>=total)return"paid";return"pending"}
const reservationStatusLabel=value=>value==="alojado"?"En hotel":value==="finalizada"?"Finalizada":value==="cancelada"?"Cancelada":value==="tentativa"?"Tentativa":value==="pendiente"?"Pendiente":"Confirmada"
const RECORD_SELECT="id,numero_reserva,nombre_huesped,email_huesped,telefono_huesped,habitacion_id,habitaciones_ids,habitaciones_detalle,room_checkout_dates,fecha_entrada,fecha_salida,estado,no_show,no_show_at,no_show_release_date,no_show_penalty_amount,no_show_penalty_status,no_show_note,garantia_tipo,garantia_marca,garantia_ultimos4,canal_reserva,codigo_canal,precio_total,precio_sin_impuestos_nacionales,iva_porcentaje,iva_importe,impuestos_desglosados,condicion_iva_huesped,subtotal,descuento_tipo,descuento_valor,descuento_importe,tarifa_noche,noches,moneda,cantidad_huespedes,guest_profile_id,notas,created_at,tipo_estadia,servicios,mascotas_total,cochera_total,extra,extra_descripcion,early_checkin_importe,late_checkout_importe,regimen,hora_llegada_estimada,hora_salida_estimada,pais_huesped,nacionalidad_huesped,tipo_documento_huesped,dni_huesped,cancellation_policy_id,cancellation_policy_snapshot,cancelled_at,cancellation_penalty_amount,cancellation_penalty_status,cancellation_note"

export default function ReservationsWorkspace({propertyId,onNavigate,allowedViews=[],focusReservationId,onFocusHandled}){
  const data=useReservationsData(propertyId)
  const[reservationSearch,setReservationSearch]=useState("")
  const[mode,setMode]=useState("active"),[filterOpen,setFilterOpen]=useState(false),[paymentFilter,setPaymentFilter]=useState("all"),[sortMode,setSortMode]=useState("created-desc"),[selected,setSelected]=useState(null),[saving,setSaving]=useState(""),[editOpen,setEditOpen]=useState(false),[checkoutConfirm,setCheckoutConfirm]=useState(null),[groupCheckoutConfirm,setGroupCheckoutConfirm]=useState(null),[checkinConfirm,setCheckinConfirm]=useState(null),[checkinError,setCheckinError]=useState(""),[noShowConfirm,setNoShowConfirm]=useState(null),[noShowError,setNoShowError]=useState(""),[restoreNoShowConfirm,setRestoreNoShowConfirm]=useState(null),[restoreNoShowError,setRestoreNoShowError]=useState(""),[restoreCancelledConfirm,setRestoreCancelledConfirm]=useState(null),[restoreCancelledError,setRestoreCancelledError]=useState(""),[cancelConfirm,setCancelConfirm]=useState(null),[cancelError,setCancelError]=useState("")
  const focusReloadRef=useRef(null)
  const roomById=useMemo(()=>new Map(data.rooms.map(room=>[Number(room.id),room])),[data.rooms])
  const items=useMemo(()=>data.reservations.map(item=>{const paid=data.paymentByReservation.get(Number(item.id))||0,rooms=activeRoomIds(item).map(id=>roomById.get(id)).filter(Boolean);return{...item,property_id:propertyId,paid,payment:paymentState(item,paid),room:rooms[0]||roomById.get(Number(item.habitacion_id)),rooms}}),[data.reservations,data.paymentByReservation,roomById,propertyId])
  const modeCounts=useMemo(()=>({active:items.filter(item=>item.estado!=="cancelada"&&!item.no_show).length,noshow:items.filter(item=>item.no_show).length,trash:items.filter(item=>item.estado==="cancelada").length}),[items])
  const modeTitle=mode==="noshow"?"No Shows":mode==="trash"?"Reservas canceladas":"Reservas activas"
  const searchTerm=normalizeSearch(reservationSearch),searching=Boolean(searchTerm)

  function scrollTop(){if(typeof window!=="undefined")requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:"auto"}))}
  function syncRecordUrl(id){if(typeof window==="undefined")return;const url=new URL(window.location.href);if(id==null)url.searchParams.delete("reservation");else url.searchParams.set("reservation",String(id));window.history.replaceState({pmsView:"reservations",reservationId:id??null},"",url)}
  function enrichRecord(item){const paid=data.paymentByReservation.get(Number(item.id))||0,rooms=activeRoomIds(item).map(id=>roomById.get(id)).filter(Boolean);return{...item,property_id:propertyId,paid,payment:paymentState(item,paid),room:rooms[0]||roomById.get(Number(item.habitacion_id)),rooms}}
  function openRecord(item){setEditOpen(false);setSelected(item);syncRecordUrl(item.id);scrollTop()}
  function openEdit(event){
    event?.preventDefault?.()
    event?.stopPropagation?.()
    setEditOpen(true)
  }
  function closeRecord(){setEditOpen(false);setSelected(null);setCheckoutConfirm(null);setGroupCheckoutConfirm(null);setCheckinConfirm(null);setCheckinError("");setNoShowConfirm(null);setNoShowError("");setRestoreNoShowConfirm(null);setRestoreNoShowError("");setRestoreCancelledConfirm(null);setRestoreCancelledError("");setCancelConfirm(null);setCancelError("");syncRecordUrl(null)}
  function selectMode(next){setReservationSearch("");setMode(next)}
  function changeReservationSearch(value){if(value.trim()&&!reservationSearch.trim()){setPaymentFilter("all");setFilterOpen(false)}setReservationSearch(value)}

  useEffect(()=>{
    if(!focusReservationId){focusReloadRef.current=null;return}
    const wanted=Number(focusReservationId);let cancelled=false;syncRecordUrl(wanted);setEditOpen(false);if(selected&&Number(selected.id)!==wanted)setSelected(null)
    const target=items.find(item=>Number(item.id)===wanted)
    if(target){focusReloadRef.current=null;setMode(target.estado==="cancelada"?"trash":target.no_show?"noshow":"active");setSelected(target);scrollTop();onFocusHandled?.();return}
    if(focusReloadRef.current===String(wanted))return
    focusReloadRef.current=String(wanted)
    ;(async()=>{try{const{data:row,error:rowError}=await supabase.from("reservas").select(RECORD_SELECT).eq("property_id",propertyId).eq("id",wanted).single();if(rowError)throw rowError;if(cancelled)return;const record=enrichRecord(row);setMode(record.estado==="cancelada"?"trash":record.no_show?"noshow":"active");setSelected(record);scrollTop();onFocusHandled?.();data.load()}catch{if(cancelled)return;focusReloadRef.current=null;data.load()}})()
    return()=>{cancelled=true}
  },[focusReservationId,items,onFocusHandled,propertyId,roomById,data.paymentByReservation])
  useEffect(()=>{if(focusReservationId||selected||typeof window==="undefined")return;const requested=Number(new URL(window.location.href).searchParams.get("reservation"));if(!requested)return;const target=items.find(item=>Number(item.id)===requested);if(target){setMode(target.estado==="cancelada"?"trash":target.no_show?"noshow":"active");setSelected(target);scrollTop()}},[focusReservationId,items,selected])
  useEffect(()=>{if(!selected)return;const fresh=items.find(item=>Number(item.id)===Number(selected.id));if(fresh&&fresh!==selected)setSelected(fresh)},[items,selected])

  const visible=useMemo(()=>{const today=dateKey(new Date());const filtered=items.filter(item=>{if(searchTerm){const haystack=normalizeSearch([item.numero_reserva,item.nombre_huesped,item.email_huesped,item.telefono_huesped,item.dni_huesped,item.canal_reserva,item.codigo_canal,...(item.rooms||[]).map(room=>room.nombre),...(item.rooms||[]).map(room=>room.tipo)].filter(Boolean).join(" "));if(!haystack.includes(searchTerm))return false}else{if(mode==="trash"&&item.estado!=="cancelada")return false;if(mode==="noshow"&&!item.no_show)return false;if(mode==="active"&&(item.estado==="cancelada"||item.no_show))return false}if(paymentFilter!=="all"&&item.payment!==paymentFilter)return false;return true});return[...filtered].sort((a,b)=>{if(sortMode==="created-asc")return new Date(a.created_at||0)-new Date(b.created_at||0);if(sortMode==="arrival-next"){const aFuture=String(a.fecha_entrada||"")>=today,bFuture=String(b.fecha_entrada||"")>=today;if(aFuture!==bFuture)return aFuture?-1:1;return aFuture?String(a.fecha_entrada||"").localeCompare(String(b.fecha_entrada||"")):String(b.fecha_entrada||"").localeCompare(String(a.fecha_entrada||""))}if(sortMode==="arrival-desc")return String(b.fecha_entrada||"").localeCompare(String(a.fecha_entrada||""));return new Date(b.created_at||0)-new Date(a.created_at||0)})},[items,mode,paymentFilter,sortMode,searchTerm])

  function requestCheckIn(item){setCheckinError("");setCheckinConfirm(item)}
  async function performCheckIn(item,{roomIds=[]}={}){if(!item)return;setSaving(String(item.id));data.setError("");setCheckinError("");try{const updated=await data.checkin(item.id,roomIds),progress=reservationCheckinProgress(updated);if(selected?.id===item.id)setSelected(current=>({...current,...updated}));setCheckinConfirm(null);if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("hl:pms-toast",{detail:{title:progress.partial?"Check-in parcial realizado":"Check-in realizado",message:progress.partial?`${item.nombre_huesped} · ${progress.checked} de ${progress.total} habitaciones ingresaron. Quedan ${progress.pending} pendientes.`:`${item.nombre_huesped} · todas las habitaciones seleccionadas quedaron en hotel.`}}))}catch(err){const message=err?.message||"No se pudo realizar el check-in.";setCheckinError(message);data.setError(message)}finally{setSaving("")}}
  async function performCheckout(item,{withBalance=false}={}){setSaving(String(item.id));data.setError("");try{const total=Math.max(0,Number(item.precio_total)||0),paid=Math.max(0,Number(item.paid)||0),balance=Math.max(0,total-paid);const updated=await data.checkout(item.id);if(withBalance&&balance>0.01){const{error:eventError}=await supabase.from("hotel_reservation_events").insert({property_id:propertyId,reservation_id:Number(item.id),event_type:"checkout_with_balance",title:"Check-out con saldo pendiente",detail:`Se realizó el check-out con ${money(balance,item.moneda||"ARS")} pendiente de pago.`,payload:{total,paid,balance,currency:item.moneda||"ARS",manual_confirmation:true}});if(eventError)console.warn("No se pudo registrar el evento de saldo pendiente",eventError)}if(selected?.id===item.id)setSelected(current=>({...current,...updated}));setCheckoutConfirm(null);setGroupCheckoutConfirm(null);if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("hl:pms-toast",{detail:{title:withBalance&&balance>0.01?"Check-out con saldo pendiente":"Check-out realizado",message:withBalance&&balance>0.01?`${item.nombre_huesped} · queda pendiente ${money(balance,item.moneda||"ARS")}.`:`${item.nombre_huesped} · estadía finalizada.`}}))}catch(err){data.setError(err?.message||"No se pudo realizar el check-out.")}finally{setSaving("")}}
  function checkoutAll(item){const total=Math.max(0,Number(item.precio_total)||0),paid=Math.max(0,Number(item.paid)||0),balance=Math.max(0,total-paid);if(balance>0.01){setCheckoutConfirm({...item,paid});return}performCheckout(item)}
  function checkout(item){if(item?.estado==="alojado"&&logicalRoomIds(item).length>1){setGroupCheckoutConfirm(item);return}checkoutAll(item)}
  function payBeforeCheckout(item){setCheckoutConfirm(null);onNavigate?.("dailycash",{cashReservationId:Number(item.id),restoreScroll:false})}
  function openHousekeepingFromCheckin(){setCheckinConfirm(null);setCheckinError("");onNavigate?.("housekeeping")}
  function requestNoShow(item){if(item.no_show){setRestoreNoShowError("");setRestoreNoShowConfirm(item);return}setNoShowError("");setNoShowConfirm(item)}
  async function performRestoreNoShow(item,options){if(!item)return;setSaving(String(item.id));data.setError("");setRestoreNoShowError("");try{const updated=await data.restoreNoShow(item.id,options);if(selected?.id===item.id)setSelected(current=>({...current,...updated}));setRestoreNoShowConfirm(null);setMode("active");const removed=options?.penaltyAction==="remove"&&Math.max(0,Number(item.no_show_penalty_amount)||0)>0;if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("hl:pms-toast",{detail:{title:"No Show reabierto",message:removed?`${item.nombre_huesped} volvió a reservas activas y la penalidad fue anulada. El pago, si existía, quedó a cuenta de la estadía.`:`${item.nombre_huesped} volvió a reservas activas. La penalidad se mantuvo según la decisión de recepción.`}}))}catch(err){const message=err?.message||"No se pudo reabrir el No Show.";setRestoreNoShowError(message);data.setError(message)}finally{setSaving("")}}
  async function performNoShow(item,options){if(!item)return;setSaving(String(item.id));data.setError("");setNoShowError("");try{const roomId=Number(options?.roomId)||null,roomMode=Boolean(roomId),updated=roomMode?await data.markGroupRoomNoShow(item.id,options):await data.markNoShow(item.id,options);if(selected?.id===item.id)setSelected(current=>({...current,...updated}));setNoShowConfirm(null);if(!roomMode)setMode("noshow");if(typeof window!=="undefined"){const roomName=(item.rooms||[]).find(room=>Number(room.id)===roomId)?.nombre||roomId;window.dispatchEvent(new CustomEvent("hl:pms-toast",{detail:{title:roomMode?`No Show · Hab. ${roomName}`:"No Show registrado",message:roomMode?`La Hab. ${roomName} quedó liberada sin cerrar el resto del grupo. Pasajeros, Planning y folio fueron resincronizados.`:`${item.nombre_huesped} · se quitó del Planning, se liberó la disponibilidad y quedó archivado en No Shows.`}}))}}catch(err){const message=err?.message||"No se pudo registrar el No Show.";setNoShowError(message);data.setError(message)}finally{setSaving("")}}
  function payBeforeNoShow(item){setNoShowConfirm(null);setNoShowError("");onNavigate?.("dailycash",{cashReservationId:Number(item.id),restoreScroll:false})}
  function cancel(item){setCancelError("");setCancelConfirm(item)}
  async function performCancel(item,options){if(!item)return;setSaving(String(item.id));data.setError("");setCancelError("");try{await data.cancelReservation(item.id,options);setCancelConfirm(null);if(selected?.id===item.id)closeRecord();if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("hl:pms-toast",{detail:{title:"Reserva cancelada",message:`${item.nombre_huesped} · cancelación procesada según ${item.cancellation_policy_snapshot?.name||"la política asignada"}.`}}))}catch(err){const message=err?.message||"No se pudo cancelar la reserva.";setCancelError(message);data.setError(message)}finally{setSaving("")}}
  function payBeforeCancel(item){setCancelConfirm(null);setCancelError("");onNavigate?.("dailycash",{cashReservationId:Number(item.id),restoreScroll:false})}
  function requestRestoreCancelled(item){setRestoreCancelledError("");setRestoreCancelledConfirm(item)}
  async function performRestoreCancelled(item,options){if(!item)return;setSaving(String(item.id));setRestoreCancelledError("");data.setError("");try{const updated=await data.restoreCancelledReservation(item.id,options);setRestoreCancelledConfirm(null);if(!searching)setMode("active");if(selected?.id===item.id)setSelected(current=>({...current,...updated}));if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("hl:pms-toast",{detail:{title:"Reserva restaurada",message:`${item.nombre_huesped} · volvió a estado Confirmada después de validar fechas, habitación y posibles duplicados.`}}))}catch(err){const message=err?.message||"No se pudo restaurar la reserva.";setRestoreCancelledError(message);data.setError(message)}finally{setSaving("")}}

  const groupCheckoutDialog=groupCheckoutConfirm?<ReservationGroupCheckoutDialog item={groupCheckoutConfirm} rooms={data.rooms} propertyId={propertyId} onClose={()=>setGroupCheckoutConfirm(null)} onCheckoutAll={()=>{const target=groupCheckoutConfirm;setGroupCheckoutConfirm(null);if(target)checkoutAll(target)}} onChanged={updated=>{if(updated&&selected?.id===updated.id)setSelected(enrichRecord(updated));void data.load()}}/>:null
  const checkoutDialog=<CheckoutBalanceDialog item={checkoutConfirm} saving={saving===String(checkoutConfirm?.id)} onClose={()=>setCheckoutConfirm(null)} onPay={()=>payBeforeCheckout(checkoutConfirm)} onConfirm={()=>performCheckout(checkoutConfirm,{withBalance:true})}/>
  const checkinDialog=<ReservationCheckinDialog item={checkinConfirm} saving={saving===String(checkinConfirm?.id)} error={checkinError} onClose={()=>{setCheckinConfirm(null);setCheckinError("")}} onHousekeeping={openHousekeepingFromCheckin} onConfirm={options=>performCheckIn(checkinConfirm,options)}/>
  const roomNoShowMode=Boolean(noShowConfirm&&noShowConfirm.estado==="alojado"&&reservationCheckinProgress(noShowConfirm).partial)
  const noShowDialog=roomNoShowMode?<ReservationRoomNoShowDialog item={noShowConfirm} saving={saving===String(noShowConfirm?.id)} error={noShowError} onClose={()=>{setNoShowConfirm(null);setNoShowError("")}} onPay={()=>payBeforeNoShow(noShowConfirm)} onConfirm={options=>performNoShow(noShowConfirm,options)}/>:<ReservationNoShowDialog item={noShowConfirm} saving={saving===String(noShowConfirm?.id)} error={noShowError} onClose={()=>{setNoShowConfirm(null);setNoShowError("")}} onPay={()=>payBeforeNoShow(noShowConfirm)} onConfirm={options=>performNoShow(noShowConfirm,options)}/>
  const restoreNoShowDialog=<ReservationRestoreNoShowDialog item={restoreNoShowConfirm} saving={saving===String(restoreNoShowConfirm?.id)} error={restoreNoShowError} onClose={()=>{setRestoreNoShowConfirm(null);setRestoreNoShowError("")}} onConfirm={options=>performRestoreNoShow(restoreNoShowConfirm,options)}/>
  const restoreCancelledDialog=<ReservationRestoreCancelledDialog item={restoreCancelledConfirm} rooms={data.rooms} reservations={items} saving={saving===String(restoreCancelledConfirm?.id)} error={restoreCancelledError} onClose={()=>{setRestoreCancelledConfirm(null);setRestoreCancelledError("")}} onConfirm={options=>performRestoreCancelled(restoreCancelledConfirm,options)}/>
  const cancellationDialog=<ReservationCancellationDialog item={cancelConfirm} saving={saving===String(cancelConfirm?.id)} error={cancelError} onClose={()=>{setCancelConfirm(null);setCancelError("")}} onPay={()=>payBeforeCancel(cancelConfirm)} onConfirm={options=>performCancel(cancelConfirm,options)}/>

  if(selected){
    const selectedProgress=reservationCheckinProgress(selected),selectedNeedsCheckin=selected.estado!=="alojado"||selectedProgress.checkedRoomIds.length===0||selectedProgress.eligiblePendingRoomIds.length>0||selectedProgress.futurePendingRoomIds.length>0
    const toolbarButton={height:36,padding:"0 12px",border:"1px solid var(--line)",borderRadius:10,background:"color-mix(in srgb,var(--panelSolid) 88%,transparent)",color:"var(--text)",font:"inherit",fontSize:10.5,fontWeight:850,cursor:"pointer",boxShadow:"inset 0 1px color-mix(in srgb,#fff 42%,transparent)"}
    return <><div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap",margin:"0 8px 2px",padding:"4px 6px",minHeight:44}}><button type="button" onClick={closeRecord} style={toolbarButton}>← Reservas</button><div style={{flex:"1 1 auto",minWidth:24}}/><div style={{display:"flex",alignItems:"center",justifyContent:"flex-end",gap:7,flexWrap:"wrap"}}><ReservationActionBar item={selected} rooms={selected.rooms} propertyId={propertyId} onRefresh={data.load}/><ReservationStayActions item={selected} saving={saving===String(selected.id)} onPrimary={()=>selectedNeedsCheckin?requestCheckIn(selected):checkout(selected)} onNoShow={()=>requestNoShow(selected)} onCancel={()=>cancel(selected)}/><button type="button" onMouseDown={event=>event.preventDefault()} onClick={openEdit} disabled={saving===String(selected.id)} style={{...toolbarButton,borderColor:"color-mix(in srgb,var(--accent) 28%,var(--line))",background:"color-mix(in srgb,var(--accent) 7%,var(--panelSolid))",color:"var(--accent)"}}>✎ Editar</button></div></div><ReservationRecord item={selected} room={selected.room} rooms={selected.rooms} payments={data.payments} propertyId={propertyId} allowedViews={allowedViews} onBack={closeRecord} onNavigate={onNavigate} saving={saving===String(selected.id)} onNoShow={()=>requestNoShow(selected)} onCancel={()=>cancel(selected)} onEdit={openEdit} onPrimaryAction={()=>selectedNeedsCheckin?requestCheckIn(selected):checkout(selected)}/>{editOpen?<ReservationEditPanel item={selected} assignedRooms={selected.rooms} allRooms={data.rooms} saving={saving===String(selected.id)} onCancel={()=>setEditOpen(false)} onPreviewMove={data.previewMove} onMove={data.moveReservation} onUpdate={data.updateReservation} onGroupSpecialSaved={updated=>{setSelected(enrichRecord(updated));void data.load()}} onSaved={()=>{setEditOpen(false);data.load()}}/>:null}{checkinDialog}{noShowDialog}{restoreNoShowDialog}{restoreCancelledDialog}{cancellationDialog}{groupCheckoutDialog}{checkoutDialog}</>
  }

  return <><ReservationsListView mode={mode} modeCounts={modeCounts} modeTitle={modeTitle} searching={searching} reservationSearch={reservationSearch} onSearchChange={changeReservationSearch} onClearSearch={()=>setReservationSearch("")} onSelectMode={selectMode} sortMode={sortMode} onSort={setSortMode} filterOpen={filterOpen} onToggleFilter={()=>setFilterOpen(v=>!v)} paymentFilter={paymentFilter} onPaymentFilter={setPaymentFilter} dataError={data.error} visible={visible} loading={data.loading} itemsCount={items.length} hasMore={data.hasMore} loadingMore={data.loadingMore} onLoadMore={data.loadMore} saving={saving} onRestore={requestRestoreCancelled} onCheckout={checkout} onCheckin={requestCheckIn} onOpenRecord={openRecord} onNoShow={requestNoShow} onCancel={cancel}/>{checkinDialog}{noShowDialog}{restoreNoShowDialog}{restoreCancelledDialog}{cancellationDialog}{groupCheckoutDialog}{checkoutDialog}</>
}
