"use client"

import{useEffect,useMemo,useState}from"react"

const DAY=86400000
const dateKey=date=>date.toLocaleDateString("en-CA")
const fmtDate=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value}T12:00:00`)).replace(".",""):"—"
const money=(value,currency="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:0}).format(Number(value)||0)
function daysBefore(value){const today=new Date(`${dateKey(new Date())}T12:00:00`),arrival=new Date(`${value}T12:00:00`);return Math.max(0,Math.round((arrival-today)/DAY))}
function applicableRule(policy,days){const rules=Array.isArray(policy?.cancellation_rules)?[...policy.cancellation_rules]:[];return rules.filter(rule=>days>=Math.max(0,Number(rule.min_days_before)||0)).sort((a,b)=>Number(b.min_days_before||0)-Number(a.min_days_before||0))[0]||{charge_type:"none",value:0}}
function penaltyValue(rule,item){const value=Math.max(0,Number(rule?.value)||0),type=rule?.charge_type||"none";if(type==="fixed")return value;if(type==="percent")return Math.max(0,Number(item?.precio_total)||0)*value/100;if(type==="nights")return Math.max(0,Number(item?.tarifa_noche)||0)*value;return 0}
function ruleText(rule,currency="ARS"){const value=Math.max(0,Number(rule?.value)||0);if(rule?.charge_type==="fixed")return money(value,currency);if(rule?.charge_type==="percent")return`${value}% del total`;if(rule?.charge_type==="nights")return`${value} noche${value===1?"":"s"}`;return"Sin cargo"}

export default function ReservationCancellationDialog({item,onClose,onConfirm,onPay,saving,error}){
  const[note,setNote]=useState(""),[waive,setWaive]=useState(false)
  useEffect(()=>{setNote("");setWaive(false)},[item?.id])
  const policy=item?.cancellation_policy_snapshot&&typeof item.cancellation_policy_snapshot==="object"?item.cancellation_policy_snapshot:{},days=useMemo(()=>item?daysBefore(item.fecha_entrada):0,[item?.id,item?.fecha_entrada]),rule=applicableRule(policy,days),currency=item?.moneda||"ARS",penalty=Math.max(0,penaltyValue(rule,item)),paid=Math.max(0,Number(item?.paid)||0),covered=penalty<=0.01||paid+0.01>=penalty,today=dateKey(new Date()),beforeArrival=Boolean(item)&&today<String(item.fecha_entrada||""),canConfirm=beforeArrival&&(penalty<=0.01||waive||covered)
  if(!item)return null
  const overlay={position:"fixed",inset:0,zIndex:278,display:"grid",placeItems:"center",padding:18,background:"rgba(19,28,46,.42)",backdropFilter:"blur(12px) saturate(1.08)"},panel={width:"min(600px,calc(100vw - 28px))",border:"1px solid color-mix(in srgb,var(--line) 82%,#fff)",borderRadius:22,background:"color-mix(in srgb,var(--panelSolid) 97%,transparent)",boxShadow:"0 28px 80px rgba(17,28,52,.3)",overflow:"hidden"},button={height:40,padding:"0 14px",border:"1px solid var(--line)",borderRadius:11,background:"var(--panelSolid)",color:"var(--text)",font:"inherit",fontSize:11,fontWeight:850,cursor:saving?"wait":"pointer"}
  return <div style={overlay} role="dialog" aria-modal="true" aria-label="Cancelar reserva"><section style={panel}><header style={{display:"flex",justifyContent:"space-between",gap:16,padding:"18px 20px 14px",borderBottom:"1px solid var(--line)"}}><div><small style={{display:"block",fontSize:10,fontWeight:900,letterSpacing:".12em",color:"#c24850",marginBottom:5}}>CANCELACIÓN · POLÍTICA DE LA RESERVA</small><h2 style={{margin:0,fontSize:20}}>¿Cancelar la reserva?</h2><p style={{margin:"6px 0 0",fontSize:11,color:"var(--muted)"}}>{item.nombre_huesped} · Reserva {item.numero_reserva||item.id}</p></div><button type="button" onClick={onClose} disabled={saving} style={{...button,width:38,padding:0}}>×</button></header><div style={{padding:"18px 20px"}}>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}><article style={{padding:12,border:"1px solid var(--line)",borderRadius:12,background:"var(--panelSolid)"}}><small style={{fontSize:9.5,color:"var(--muted)"}}>LLEGADA</small><b style={{display:"block",marginTop:4,fontSize:13}}>{fmtDate(item.fecha_entrada)}</b><small style={{display:"block",marginTop:3,color:"var(--muted)"}}>{beforeArrival?`${days} día${days===1?"":"s"} de anticipación`:"La llegada ya comenzó"}</small></article><article style={{padding:12,border:"1px solid var(--line)",borderRadius:12,background:"var(--panelSolid)"}}><small style={{fontSize:9.5,color:"var(--muted)"}}>TOTAL RESERVA</small><b style={{display:"block",marginTop:4,fontSize:13}}>{money(item.precio_total,currency)}</b><small style={{display:"block",marginTop:3,color:"var(--muted)"}}>Pagado: {money(paid,currency)}</small></article></div>
    {!beforeArrival?<div style={{marginTop:11,padding:"11px 12px",border:"1px solid color-mix(in srgb,#e45c70 40%,var(--line))",borderRadius:12,background:"color-mix(in srgb,#ef6579 7%,var(--panelSolid))",fontSize:11,color:"#d84960"}}>La fecha de llegada ya comenzó. Si el huésped no se presentó, usá <b>No Show</b>; si ya ingresó, corresponde el flujo de check-out.</div>:null}
    <div style={{marginTop:11,padding:"12px 13px",border:"1px solid color-mix(in srgb,var(--accent) 28%,var(--line))",borderRadius:12,background:"color-mix(in srgb,var(--accent) 5%,var(--panelSolid))",fontSize:10.5,lineHeight:1.5}}><b>Política: {policy?.name||"Sin política histórica"}</b><span style={{display:"block",marginTop:3,color:"var(--muted)"}}>{policy?.description||"Esta reserva fue creada antes del sistema de políticas estructuradas."}</span><span style={{display:"block",marginTop:5,fontWeight:850,color:penalty>0?"#9a6a00":"#218b59"}}>Regla aplicable: {ruleText(rule,policy?.currency||currency)}{penalty>0?` · Penalidad ${money(penalty,currency)}`:" · Cancelación sin cargo"}</span></div>
    {penalty>0?<div style={{marginTop:11,padding:12,border:"1px solid var(--line)",borderRadius:12}}><b style={{fontSize:11.5}}>Tratamiento de la penalidad</b>{covered?<div style={{marginTop:8,padding:"9px 10px",borderRadius:9,background:"color-mix(in srgb,#28a66a 8%,var(--panelSolid))",color:"#218b59",fontSize:10.5,fontWeight:850}}>El importe requerido ya está cubierto por pagos registrados.</div>:<div style={{marginTop:8,padding:"9px 10px",borderRadius:9,background:"color-mix(in srgb,#f0bd35 8%,var(--panelSolid))",color:"#9a6a00",fontSize:10.5}}>Antes de cancelar hay que cobrar {money(penalty,currency)} o registrar expresamente una excepción.</div>}<div style={{display:"flex",gap:8,marginTop:9,flexWrap:"wrap"}}>{!covered?<button type="button" onClick={()=>onPay?.(penalty)} style={{...button,borderColor:"var(--accent)",background:"var(--accent)",color:"#fff"}}>Cobrar penalidad</button>:null}<button type="button" onClick={()=>setWaive(value=>!value)} style={{...button,borderColor:waive?"#c24850":"var(--line)",color:waive?"#c24850":"var(--text)",background:waive?"color-mix(in srgb,#ef6579 6%,var(--panelSolid))":"var(--panelSolid)"}}>{waive?"Excepción registrada ✓":"Eximir penalidad"}</button></div>{waive?<small style={{display:"block",marginTop:7,color:"#a26800"}}>La cancelación quedará registrada como excepción manual a la política. Conviene indicar el motivo abajo.</small>:null}</div>:null}
    <label style={{display:"grid",gap:5,marginTop:12,fontSize:10,color:"var(--muted)"}}>Motivo / observación<textarea rows="3" value={note} onChange={event=>setNote(event.target.value)} placeholder="Ej.: huésped solicitó cancelar por teléfono…" style={{resize:"vertical",border:"1px solid var(--line)",borderRadius:10,padding:"9px 10px",background:"var(--panelSolid)",color:"var(--text)",font:"inherit",fontSize:11}}/></label>
    {error?<div style={{marginTop:11,padding:"10px 11px",border:"1px solid color-mix(in srgb,#e45c70 40%,var(--line))",borderRadius:10,color:"#d84960",fontSize:10.5}}>{error}</div>:null}
    <div style={{display:"flex",justifyContent:"flex-end",gap:8,flexWrap:"wrap",marginTop:18,paddingTop:14,borderTop:"1px solid var(--line)"}}><button type="button" onClick={onClose} disabled={saving} style={button}>Volver</button><button type="button" disabled={saving||!canConfirm} onClick={()=>onConfirm?.({penaltyStatus:penalty<=0.01?"none":waive?"waived":"charged",note:waive&&penalty>0?`${note?`${note} · `:""}Penalidad eximida manualmente.`:note})} style={{...button,borderColor:"#c24850",background:"#c24850",color:"#fff",opacity:canConfirm?1:.5}}>{saving?"Cancelando…":"Confirmar cancelación"}</button></div>
  </div></section></div>
}
