"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import s from"./reservationRecord.module.css"

const fmtDate=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${String(value).slice(0,10)}T12:00:00`)).replace(".",""):"—"
const fmtDateTime=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value)).replace(".",""):"—"
const money=(value,currency="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:0}).format(Number(value)||0)
const statusLabel=item=>item.no_show?"No-show":item.estado==="alojado"?"En hotel":item.estado==="finalizada"?"Finalizada":item.estado==="cancelada"?"Cancelada":item.estado==="tentativa"?"Tentativa":item.estado==="pendiente"?"Pendiente":"Confirmada"
const documentKind=value=>String(value||"").toLowerCase()
const initials=name=>String(name||"H").trim().split(/\s+/).map(part=>part[0]).join("").slice(0,2).toUpperCase()

function EmptyCard({text,action,onAction}){return <div className={s.emptyCard}><span>{text}</span>{action&&onAction?<button type="button" onClick={onAction}>{action}</button>:null}</div>}
function RecordCard({title,action,onAction,children}){return <section className={s.card}><header><h3>{title}</h3>{action&&onAction?<button type="button" onClick={onAction}>＋ {action}</button>:null}</header>{children}</section>}

function serviceLines(item,room,rooms=[]){
  const lines=[],assigned=rooms.length?rooms:[room].filter(Boolean)
  const nights=Math.max(1,Number(item.noches)||Math.round((new Date(`${item.fecha_salida}T12:00:00`)-new Date(`${item.fecha_entrada}T12:00:00`))/86400000)||1)
  const stayAmount=Number(item.tarifa_noche||0)*nights||Number(item.subtotal||item.precio_total||0)
  if(assigned.length>1)lines.push({key:"stay",title:`Alojamiento grupal · ${assigned.length} habitaciones`,meta:`${item.regimen||"Alojamiento"} · ${nights} noche${nights===1?"":"s"}`,detail:`${assigned.map(item=>item.nombre).join(", ")} · ${fmtDate(item.fecha_entrada)} al ${fmtDate(item.fecha_salida)}`,amount:stayAmount})
  else lines.push({key:"stay",title:`${room?.tipo||"Habitación"} ${room?.nombre||""}`.trim(),meta:`${item.regimen||"Alojamiento"} · ${nights} noche${nights===1?"":"s"}`,detail:`Estadía del ${fmtDate(item.fecha_entrada)} al ${fmtDate(item.fecha_salida)}`,amount:stayAmount})
  const services=Array.isArray(item.servicios)?item.servicios:[]
  services.forEach((service,index)=>{const qty=Number(service?.cantidad||service?.qty||1)||1,unit=Number(service?.precio||service?.price||service?.importe||0),total=Number(service?.total||service?.precio_total||unit*qty);lines.push({key:`service-${index}`,title:service?.nombre||service?.name||service?.descripcion||"Servicio",meta:qty>1?`${qty} unidades`:"Servicio",detail:service?.detalle||service?.detail||"",amount:total})})
  if(Number(item.cochera_total)>0)lines.push({key:"parking",title:"Cochera",meta:"Adicional de estadía",detail:"",amount:Number(item.cochera_total)})
  if(Number(item.mascotas_total)>0)lines.push({key:"pets",title:"Mascotas",meta:"Adicional de estadía",detail:"",amount:Number(item.mascotas_total)})
  if(Number(item.early_checkin_importe)>0)lines.push({key:"early",title:"Early check-in",meta:"Servicio adicional",detail:"",amount:Number(item.early_checkin_importe)})
  if(Number(item.late_checkout_importe)>0)lines.push({key:"late",title:"Late check-out",meta:"Servicio adicional",detail:"",amount:Number(item.late_checkout_importe)})
  if(Number(item.extra)>0)lines.push({key:"extra",title:item.extra_descripcion||"Extra",meta:"Cargo adicional",detail:"",amount:Number(item.extra)})
  return lines
}

export default function ReservationRecord({item,room,rooms=[],payments=[],propertyId,onBack,onNavigate,onPrimaryAction,saving}){
  const[documents,setDocuments]=useState([]),[deposits,setDeposits]=useState([]),[events,setEvents]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[sideTab,setSideTab]=useState("tasks")
  useEffect(()=>{let cancelled=false;async function load(){if(!item?.id||!propertyId)return;setLoading(true);setError("");try{const[docsRes,depositsRes,eventsRes]=await Promise.all([supabase.from("hotel_finance_documents").select("id,document_type,number,status,currency,total,balance,issued_at,due_at,notes").eq("property_id",propertyId).eq("reservation_id",item.id).order("created_at",{ascending:false}),supabase.from("hotel_deposits").select("id,amount,currency,status,method,reference,notes,held_at,created_at").eq("property_id",propertyId).eq("reserva_id",item.id).order("created_at",{ascending:false}),supabase.from("hotel_reservation_events").select("id,event_type,title,detail,actor_name,created_at").eq("property_id",propertyId).eq("reservation_id",item.id).order("created_at",{ascending:false}).limit(20)]);if(docsRes.error)throw docsRes.error;if(depositsRes.error)throw depositsRes.error;if(eventsRes.error)throw eventsRes.error;if(!cancelled){setDocuments(docsRes.data||[]);setDeposits(depositsRes.data||[]);setEvents(eventsRes.data||[])}}catch(err){if(!cancelled)setError(err?.message||"No se pudo cargar el detalle operativo de la reserva.")}finally{if(!cancelled)setLoading(false)}}load();return()=>{cancelled=true}},[item?.id,propertyId])

  const itemPayments=useMemo(()=>payments.filter(payment=>Number(payment.reserva_id)===Number(item.id)&&!["anulado","cancelado","void"].includes(String(payment.estado||"").toLowerCase())),[payments,item.id])
  const paid=useMemo(()=>itemPayments.reduce((sum,payment)=>sum+Math.max(0,Number(payment.monto||0)-Number(payment.refunded_amount||0)),0),[itemPayments])
  const invoices=documents.filter(doc=>!documentKind(doc.document_type).includes("proforma")&&!documentKind(doc.document_type).includes("presupuesto")),proformas=documents.filter(doc=>documentKind(doc.document_type).includes("proforma")||documentKind(doc.document_type).includes("presupuesto"))
  const assigned=rooms.length?rooms:[room].filter(Boolean),articles=serviceLines(item,room,assigned),total=Number(item.precio_total)||0,balance=Math.max(0,total-paid),nights=Math.max(1,Number(item.noches)||Math.round((new Date(`${item.fecha_salida}T12:00:00`)-new Date(`${item.fecha_entrada}T12:00:00`))/86400000)||1)
  const roomSummary=assigned.length>1?`${assigned.length} habitaciones · ${assigned.map(item=>item.nombre).join(", ")}`:room?.nombre?`Habitación ${room.nombre}`:"Sin habitación"

  return <div className={s.record}>
    <div className={s.recordTop}><button type="button" className={s.back} onClick={onBack}>← Reservas</button><div className={s.quickActions}><button type="button" onClick={()=>onNavigate?.("messages")}>✉ Mensajes</button><button type="button" onClick={()=>onNavigate?.("guests")}>◎ Huésped</button><button type="button" onClick={()=>onNavigate?.("tasks")}>✓ Tarea</button><button type="button" onClick={()=>onNavigate?.("audit")}>◇ Actividad</button></div></div>
    <div className={s.heroGrid}>
      <section className={s.heroCard}><div className={s.heroHeader}><span className={s.avatar}>{initials(item.nombre_huesped)}</span><div><h1>{item.nombre_huesped}</h1><p>{roomSummary} · Reserva {item.numero_reserva||item.id}</p></div><span className={`${s.status} ${item.estado==="alojado"?s.statusIn:item.estado==="pendiente"||item.estado==="tentativa"?s.statusWarn:""}`}>{statusLabel(item)} ✓</span></div><div className={s.heroFacts}><div><small>Llegada</small><b>{fmtDate(item.fecha_entrada)}</b></div><div><small>Salida</small><b>{fmtDate(item.fecha_salida)}</b></div><div><small>Ocupación</small><b>{item.cantidad_huespedes||1} huésped{Number(item.cantidad_huespedes||1)===1?"":"es"}</b></div><div><small>Noches</small><b>{nights}</b></div><div><small>{assigned.length>1?"Habitaciones":"Política"}</small><b>{assigned.length>1?assigned.length:item.estado==="tentativa"?"Tentativa":"Reserva activa"}</b></div><div><small>Régimen</small><b>{item.regimen||"Alojamiento"}</b></div><div><small>Teléfono</small><b>{item.telefono_huesped||"—"}</b></div><div><small>Recibida</small><b>{fmtDate(item.created_at)}</b></div></div></section>
      <aside className={s.sideCard}><nav>{[["tasks","Tareas"],["requests","Peticiones"],["internal","Interno"],["floors","Pisos"]].map(([value,label])=><button type="button" key={value} className={sideTab===value?s.tabActive:""} onClick={()=>setSideTab(value)}>{label}</button>)}</nav><div className={s.sideBody}>{sideTab==="tasks"?<><p>Gestioná tareas vinculadas a esta estadía desde Operación.</p><button type="button" onClick={()=>onNavigate?.("tasks")}>＋ Añadir tarea</button></>:sideTab==="requests"?<><p>Pedidos y solicitudes del huésped asociados a la reserva.</p><button type="button" onClick={()=>onNavigate?.("requests")}>Abrir peticiones</button></>:sideTab==="floors"?<><p>{assigned.length>1?`Coordiná limpieza y estado de las ${assigned.length} habitaciones asignadas.`:"Estado de habitación, limpieza y coordinación de pisos."}</p><button type="button" onClick={()=>onNavigate?.("housekeeping")}>Abrir Housekeeping</button></>:<><p>{item.notas||"No hay notas internas cargadas."}</p>{events[0]?<small>Última actividad: {events[0].title||events[0].event_type} · {fmtDateTime(events[0].created_at)}</small>:null}</>}</div></aside>
    </div>
    {error?<div className={s.alert}>{error}</div>:null}
    <div className={s.contentGrid}><RecordCard title="Artículos" action="Agregar cargo" onAction={()=>onNavigate?.("services")}><div className={s.articleList}>{articles.map(line=><article key={line.key}><div><b>{line.title}</b><small>{line.meta}</small>{line.detail?<p>{line.detail}</p>:null}</div><strong>{money(line.amount,item.moneda)}</strong></article>)}</div><footer className={s.articleTotal}><span>Total</span><b>{money(total,item.moneda)}</b><small>Pagado {money(paid,item.moneda)} · Pendiente {money(balance,item.moneda)}</small></footer></RecordCard><div className={s.financeGrid}>
      <RecordCard title="Facturas" action="Facturar" onAction={()=>onNavigate?.("finance")}>{loading?<EmptyCard text="Cargando documentos…"/>:invoices.length?<div className={s.compactList}>{invoices.map(doc=><div key={doc.id}><span><b>{doc.number||doc.document_type||"Documento"}</b><small>{fmtDate(doc.issued_at)} · {doc.status||"borrador"}</small></span><strong>{money(doc.total,doc.currency||item.moneda)}</strong></div>)}</div>:<EmptyCard text="Todavía no hay facturas vinculadas." action="Ir a Finanzas" onAction={()=>onNavigate?.("finance")}/>}</RecordCard>
      <RecordCard title="Pagos" action="Registrar pago" onAction={()=>onNavigate?.("finance")}>{itemPayments.length?<div className={s.compactList}>{itemPayments.map(payment=><div key={payment.id}><span><b>{payment.metodo||payment.source||"Pago"}</b><small>{fmtDateTime(payment.created_at)}{payment.referencia?` · ${payment.referencia}`:""}</small></span><strong>{money(Number(payment.monto||0)-Number(payment.refunded_amount||0),payment.moneda||item.moneda)}</strong></div>)}</div>:<EmptyCard text="No hay pagos registrados." action="Ir a Finanzas" onAction={()=>onNavigate?.("finance")}/>}</RecordCard>
      <RecordCard title="Proformas" action="Crear" onAction={()=>onNavigate?.("quotes")}>{proformas.length?<div className={s.compactList}>{proformas.map(doc=><div key={doc.id}><span><b>{doc.number||"Proforma"}</b><small>{fmtDate(doc.issued_at)} · {doc.status||"borrador"}</small></span><strong>{money(doc.total,doc.currency||item.moneda)}</strong></div>)}</div>:<EmptyCard text="No hay proformas para esta reserva." action="Crear presupuesto" onAction={()=>onNavigate?.("quotes")}/>}</RecordCard>
      <RecordCard title="Depósitos" action="Gestionar" onAction={()=>onNavigate?.("finance")}>{deposits.length?<div className={s.compactList}>{deposits.map(deposit=><div key={deposit.id}><span><b>{deposit.method||"Depósito"}</b><small>{fmtDateTime(deposit.held_at||deposit.created_at)} · {deposit.status||"registrado"}</small></span><strong>{money(deposit.amount,deposit.currency||item.moneda)}</strong></div>)}</div>:<EmptyCard text="No hay depósitos registrados." action="Ir a Finanzas" onAction={()=>onNavigate?.("finance")}/>}</RecordCard>
    </div></div>
    <div className={s.bottomBar}><div><small>Contacto</small><b>{item.email_huesped||item.telefono_huesped||"Sin datos de contacto"}</b></div><div className={s.bottomActions}><button type="button" onClick={()=>onNavigate?.("planning")}>Ver en Planning</button><button type="button" className={s.primaryAction} disabled={saving||item.estado==="finalizada"} onClick={onPrimaryAction}>{item.estado==="alojado"?"Hacer check-out":"Hacer check-in"}</button></div></div>
  </div>
}
