"use client"

import{useEffect,useState}from"react"
import{supabase}from"../../../../lib/supabase"

const fmtDate=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(`${value}T12:00:00`)):"—"
const statusLabel=value=>value==="alojado"?"En hotel":value==="finalizada"?"Finalizada":value==="cancelada"?"Cancelada":value==="tentativa"?"Tentativa":value==="pendiente"?"Pendiente":"Confirmada"
const todayKey=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
const validPayment=row=>!["anulado","cancelado","void","rechazado","cancelled"].includes(String(row?.estado||"").toLowerCase())
function StateIcon({tone}){const stroke=tone==="ok"?"#268357":tone==="block"?"#c84658":"#a87916";return <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke={stroke} strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{tone==="ok"?<><circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16.5 8.5"/></>:tone==="block"?<><circle cx="12" cy="12" r="9"/><path d="M9 9l6 6M15 9l-6 6"/></>:<><circle cx="12" cy="12" r="9"/><path d="M12 7v6M12 17h.01"/></>}</svg>}

export default function ReservationCheckinDialog({item,onClose,onConfirm,onHousekeeping,saving,error}){
  const[guests,setGuests]=useState([]),[payments,setPayments]=useState([]),[policy,setPolicy]=useState("allow"),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState("")
  const assigned=item?.rooms?.length?item.rooms:[item?.room].filter(Boolean),dirty=assigned.filter(room=>String(room.estado||"").toLowerCase()==="sucia"),blocked=assigned.filter(room=>room.activa===false||!["libre","limpia","inspeccionada","sucia"].includes(String(room.estado||"").toLowerCase()))
  useEffect(()=>{
    if(!item?.id||!item?.property_id){setGuests([]);setPayments([]);setPolicy("allow");setLoading(false);setLoadError("");return}
    let cancelled=false;setLoading(true);setLoadError("")
    ;(async()=>{try{const[g,p,s]=await Promise.all([
      supabase.from("hotel_reservation_guests").select("id,role,full_name,document_number,document_front_path,document_back_path,checked_out_at").eq("property_id",item.property_id).eq("reservation_id",item.id),
      supabase.from("pagos").select("id,monto,refunded_amount,estado").eq("property_id",item.property_id).eq("reserva_id",item.id),
      supabase.from("property_settings").select("settings").eq("property_id",item.property_id).maybeSingle(),
    ]);if(g.error)throw g.error;if(p.error)throw p.error;if(s.error)throw s.error;if(cancelled)return;setGuests(g.data||[]);setPayments(p.data||[]);setPolicy(s.data?.settings?.preferences?.checkin_dirty_room_policy||"allow")}catch(err){if(!cancelled)setLoadError(err?.message||"No se pudo completar el control previo.")}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}
  },[item?.id,item?.property_id])
  if(!item)return null
  const today=todayKey(),future=String(item.fecha_entrada||"")>today,past=String(item.fecha_salida||"")<today,activeGuests=guests.filter(g=>!g.checked_out_at),hasContact=Boolean(String(item.email_huesped||"").trim()||String(item.telefono_huesped||"").trim()),hasDocument=Boolean(item.dni_huesped||activeGuests.some(g=>g.document_number||g.document_front_path||g.document_back_path)),guestTarget=Math.max(1,Number(item.cantidad_huespedes)||1),guestReady=activeGuests.length>=guestTarget,paid=payments.filter(validPayment).reduce((sum,p)=>sum+Math.max(0,Number(p.monto||0)-Number(p.refunded_amount||0)),0),hasGuarantee=paid>0||Boolean(item.garantia_tipo||item.garantia_ultimos4),dirtyBlocked=dirty.length>0&&policy==="block"
  const checks=[
    {label:"Fecha de llegada",detail:future?`La llegada es ${fmtDate(item.fecha_entrada)}.`:past?"La estadía quedó fuera de fecha.":"Fecha válida para realizar el check-in.",tone:future||past?"block":"ok"},
    {label:"Huésped y contacto",detail:hasContact?"Hay email o teléfono disponible.":"Falta email o teléfono. Se puede completar desde la ficha del huésped.",tone:hasContact?"ok":"warn"},
    {label:"Documento",detail:hasDocument?"Hay identificación registrada.":"Documento pendiente. No bloquea salvo política interna del hotel.",tone:hasDocument?"ok":"warn"},
    {label:"Pasajeros",detail:guestReady?`${activeGuests.length} pasajero${activeGuests.length===1?"":"s"} cargado${activeGuests.length===1?"":"s"}.`:`Hay ${activeGuests.length} de ${guestTarget} pasajeros cargados.`,tone:guestReady?"ok":"warn"},
    {label:"Habitación",detail:!assigned.length?"No hay habitación asignada.":blocked.length?`Revisar ${blocked.map(r=>r.nombre).join(", ")}.`:`${assigned.length} habitación${assigned.length===1?"":"es"} asignada${assigned.length===1?"":"s"}.`,tone:!assigned.length||blocked.length?"block":"ok"},
    {label:"Housekeeping",detail:dirty.length?`${dirty.map(r=>r.nombre).join(", ")} figura${dirty.length===1?"":"n"} como sucia${dirty.length===1?"":"s"}. Política: ${policy==="block"?"bloquear":policy==="manager_only"?"requiere supervisor":"advertir"}.`:"Habitaciones sin alerta de limpieza.",tone:dirtyBlocked?"block":dirty.length?"warn":"ok"},
    {label:"Pago o garantía",detail:hasGuarantee?paid>0?`Hay pagos registrados por ${new Intl.NumberFormat("es-AR",{style:"currency",currency:item.moneda||"ARS",maximumFractionDigits:0}).format(paid)}.`:"Hay garantía registrada.":"No hay prepago ni garantía registrada.",tone:hasGuarantee?"ok":"warn"},
  ]
  const canConfirm=assigned.length>0&&!blocked.length&&!future&&!past&&!dirtyBlocked
  const overlay={position:"fixed",inset:0,zIndex:270,display:"grid",placeItems:"center",padding:18,background:"rgba(19,28,46,.38)",backdropFilter:"blur(12px) saturate(1.08)"},panel={width:"min(680px,calc(100vw - 28px))",maxHeight:"92vh",overflow:"auto",border:"1px solid color-mix(in srgb,var(--line) 82%,#fff)",borderRadius:22,background:"color-mix(in srgb,var(--panelSolid) 97%,transparent)",boxShadow:"0 28px 80px rgba(17,28,52,.3)"},button={height:40,padding:"0 14px",border:"1px solid var(--line)",borderRadius:11,background:"var(--panelSolid)",color:"var(--text)",font:"inherit",fontSize:11,fontWeight:850,cursor:saving?"wait":"pointer"},stateCard={flex:"1 1 150px",padding:"12px 13px",border:"1px solid var(--line)",borderRadius:12,background:"var(--panelSolid)"}
  return <div style={overlay} role="dialog" aria-modal="true" aria-label="Confirmar check-in"><section style={panel}>
    <header style={{display:"flex",justifyContent:"space-between",gap:16,padding:"18px 20px 14px",borderBottom:"1px solid var(--line)"}}><div><small style={{display:"block",fontSize:10,fontWeight:900,letterSpacing:".12em",color:"var(--accent)",marginBottom:5}}>CHECK-IN · CONTROL PREVIO</small><h2 style={{margin:0,fontSize:20}}>¿Listo para recibir al huésped?</h2><p style={{margin:"6px 0 0",fontSize:11,color:"var(--muted)"}}>{item.nombre_huesped} · Reserva {item.numero_reserva||item.id}</p></div><button type="button" onClick={onClose} disabled={saving} style={{...button,width:38,padding:0}}>×</button></header>
    <div style={{padding:"18px 20px"}}><div style={{display:"flex",alignItems:"stretch",gap:9,flexWrap:"wrap"}}><article style={stateCard}><small style={{fontSize:10,color:"var(--muted)"}}>ESTADO ACTUAL</small><b style={{display:"block",marginTop:5,fontSize:15}}>{statusLabel(item.estado)}</b></article><div aria-hidden="true" style={{display:"grid",placeItems:"center",fontSize:18,color:"var(--muted)",padding:"0 2px"}}>→</div><article style={{...stateCard,borderColor:"color-mix(in srgb,#28a66a 34%,var(--line))",background:"color-mix(in srgb,#28a66a 6%,var(--panelSolid))"}}><small style={{fontSize:10,color:"var(--muted)"}}>NUEVO ESTADO</small><b style={{display:"block",marginTop:5,fontSize:15,color:"#218b59"}}>En hotel</b></article></div>
      <div style={{marginTop:12,padding:"11px 12px",border:"1px solid var(--line)",borderRadius:12,background:"color-mix(in srgb,var(--bg) 40%,var(--panelSolid))"}}><small style={{display:"block",fontSize:9,fontWeight:900,letterSpacing:".08em",color:"var(--muted)"}}>LISTO PARA CHECK-IN</small><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(255px,1fr))",gap:7,marginTop:8}}>{checks.map(check=><article key={check.label} style={{display:"grid",gridTemplateColumns:"22px 1fr",gap:7,padding:"8px 9px",border:"1px solid var(--line)",borderRadius:10,background:"var(--panelSolid)"}}><span style={{paddingTop:1}}><StateIcon tone={check.tone}/></span><span><b style={{display:"block",fontSize:10.3}}>{check.label}</b><small style={{display:"block",marginTop:2,fontSize:9.2,lineHeight:1.4,color:"var(--muted)"}}>{check.detail}</small></span></article>)}</div></div>
      <div style={{marginTop:10,padding:"10px 11px",border:"1px solid var(--line)",borderRadius:11,background:"var(--panelSolid)",fontSize:10.3,lineHeight:1.5}}><b>{assigned.length?`Habitación${assigned.length>1?"es":""}: ${assigned.map(room=>room.nombre).join(", ")}`:"Sin habitación asignada"}</b><span style={{display:"block",marginTop:2,color:"var(--muted)"}}>Estadía: {fmtDate(item.fecha_entrada)} → {fmtDate(item.fecha_salida)}</span></div>
      {(error||loadError)?<div style={{marginTop:11,padding:"11px 12px",border:"1px solid color-mix(in srgb,#e45c70 40%,var(--line))",borderRadius:12,background:"color-mix(in srgb,#ef6579 7%,var(--panelSolid))",fontSize:11,lineHeight:1.5,color:"#d84960"}}>{error||loadError}</div>:null}
      <div style={{display:"flex",justifyContent:"flex-end",gap:8,flexWrap:"wrap",marginTop:18,paddingTop:14,borderTop:"1px solid var(--line)"}}><button type="button" onClick={onClose} disabled={saving} style={button}>Cancelar</button>{(dirty.length||blocked.length)&&onHousekeeping?<button type="button" onClick={onHousekeeping} disabled={saving} style={button}>Ir a Housekeeping</button>:null}<button type="button" onClick={onConfirm} disabled={saving||loading||!canConfirm} style={{...button,borderColor:"var(--accent)",background:"var(--accent)",color:"#fff",opacity:canConfirm&&!loading?1:.5}}>{saving?"Haciendo check-in…":loading?"Comprobando…":"Confirmar check-in"}</button></div>
    </div>
  </section></div>
}