"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import{reservationRoomingRows}from"../planning/RoomingEditor"
import ReservationChannelLogo,{channelMeta}from"../planning/ReservationChannelLogo"
import ReservationChargePanel from"./ReservationChargePanel"
import ReservationFolioBilling from"./ReservationFolioBilling"
import ReservationRoomRateRow from"./ReservationRoomRateRow"
import{roomCheckoutPresentation,RoomCheckoutHeroBadge,RoomCheckoutFact,RoomCheckoutHeader}from"./ReservationRoomCheckoutStatus"
import ReservationRoomJourney from"./ReservationRoomJourney"
import historyPresentation from"./reservationHistoryPresentation"
import s from"./reservationRecord.module.css"

const fmtDate=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${String(value).slice(0,10)}T12:00:00`)).replace(".",""):"—"
const fmtDateTime=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value)).replace(".",""):"—"
const money=(value,currency="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:2}).format(Number(value)||0)
const eventDay=value=>value?new Intl.DateTimeFormat("en-CA",{timeZone:"America/Argentina/Buenos_Aires",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(value)):""
const statusLabel=item=>item.no_show?"No-show":item.estado==="alojado"?"En hotel":item.estado==="finalizada"?"Check-out realizado":item.estado==="cancelada"?"Cancelada":item.estado==="tentativa"?"Tentativa":item.estado==="pendiente"?"Pendiente":"Confirmada"
const initials=name=>String(name||"H").trim().split(/\s+/).map(part=>part[0]).join("").slice(0,2).toUpperCase()
const RETURN_TARGETS=new Set(["tasks","requests","housekeeping","services","finance","dailycash","quotes","messages","audit","guests"])
const RETURN_KEY="hl:pms:return-reservation"

function EmptyCard({text,action,onAction}){return <div className={s.emptyCard}><span>{text}</span>{action&&onAction?<button type="button" onClick={onAction}>{action}</button>:null}</div>}
function RecordCard({title,action,onAction,headerExtra,primaryAction=false,children}){return <section className={s.card}><header><h3>{title}</h3>{headerExtra||action&&onAction?<>{headerExtra||<button type="button" className={primaryAction?s.primaryCardAction:""} onClick={onAction}>＋ {action}</button>}</>:null}</header>{children}</section>}

function serviceLines(item,room,rooms=[]){
  const lines=[],assigned=rooms.length?rooms:[room].filter(Boolean),taxEnabled=Boolean(item.impuestos_desglosados),vatRate=taxEnabled?Math.max(0,Number(item.iva_porcentaje)||0):0,gross=value=>{const amount=Number(value)||0;return taxEnabled?Math.round(amount*(1+vatRate/100)*100)/100:amount}
  const nights=Math.max(1,Number(item.noches)||Math.round((new Date(`${item.fecha_salida}T12:00:00`)-new Date(`${item.fecha_entrada}T12:00:00`))/86400000)||1)
  const stayAmount=Number(item.tarifa_noche||0)*nights||Number(item.subtotal||item.precio_sin_impuestos_nacionales||item.precio_total||0)
  const details=Array.isArray(item.habitaciones_detalle)?item.habitaciones_detalle:[]
  const segmented=details.filter(detail=>detail?.habitacion_id&&detail?.fecha_entrada&&detail?.fecha_salida&&Number(detail?.tarifa_noche)>=0&&String(detail?.segment_role||"").toLowerCase()!=="transient_room")
  if(segmented.length){
    segmented.forEach((detail,index)=>{
      const segmentNights=Math.max(1,Math.round((new Date(`${detail.fecha_salida}T12:00:00`)-new Date(`${detail.fecha_entrada}T12:00:00`))/86400000)||1)
      const amount=Number(detail.tarifa_noche||0)*segmentNights
      lines.push({key:`stay-segment-${detail.habitacion_id}-${index}`,title:`Alojamiento · Habitación ${detail.nombre||detail.habitacion_id}`,meta:`${item.regimen||"Alojamiento"} · ${segmentNights} noche${segmentNights===1?"":"s"} · ${taxEnabled?`Precio final · IVA ${vatRate}% incluido`:"Precio"}`,detail:`${fmtDate(detail.fecha_entrada)} → ${fmtDate(detail.fecha_salida)}${detail.segment_role==="previous_room"?" · tramo anterior":" · habitación actual"}`,amount,displayAmount:gross(amount)})
    })
  }else if(assigned.length>1)lines.push({key:"stay",title:`Alojamiento grupal · ${assigned.length} habitaciones`,meta:`${item.regimen||"Alojamiento"} · ${nights} noche${nights===1?"":"s"}`,detail:`${assigned.map(item=>item.nombre).join(", ")} · ${fmtDate(item.fecha_entrada)} al ${fmtDate(item.fecha_salida)}`,amount:stayAmount,displayAmount:gross(stayAmount)})
  else lines.push({key:"stay",title:`${room?.tipo||"Habitación"} ${room?.nombre||""}`.trim(),meta:`${item.regimen||"Alojamiento"} · ${nights} noche${nights===1?"":"s"}`,detail:`Estadía del ${fmtDate(item.fecha_entrada)} al ${fmtDate(item.fecha_salida)}`,amount:stayAmount,displayAmount:gross(stayAmount)})
  const services=Array.isArray(item.servicios)?item.servicios:[]
  services.forEach((service,index)=>{const qty=Number(service?.cantidad||service?.qty||1)||1,unit=Number(service?.precio||service?.price||service?.importe||0),total=Number(service?.total||service?.precio_total||unit*qty),chargedNights=Number(service?.noches||0),metaParts=[];if(qty>1)metaParts.push(`${qty} unidades`);if(chargedNights>0)metaParts.push(`${chargedNights} noche${chargedNights===1?"":"s"}`);lines.push({key:`service-${service?.id||index}`,title:service?.nombre||service?.name||service?.descripcion||"Servicio",meta:metaParts.join(" · ")||"Servicio",detail:service?.detalle||service?.detail||"",amount:total,displayAmount:Number(service?.total_final??gross(total))})})
  if(Number(item.cochera_total)>0)lines.push({key:"parking",title:"Cochera",meta:taxEnabled?`Adicional · Precio final · IVA ${vatRate}% incluido`:"Adicional de estadía",detail:"",amount:Number(item.cochera_total),displayAmount:gross(Number(item.cochera_total))})
  if(Number(item.mascotas_total)>0)lines.push({key:"pets",title:"Mascotas",meta:taxEnabled?`Adicional · Precio final · IVA ${vatRate}% incluido`:"Adicional de estadía",detail:"",amount:Number(item.mascotas_total),displayAmount:gross(Number(item.mascotas_total))})
  if(Number(item.early_checkin_importe)>0)lines.push({key:"early",title:"Early check-in",meta:taxEnabled?`Servicio adicional · Precio final · IVA ${vatRate}% incluido`:"Servicio adicional",detail:"",amount:Number(item.early_checkin_importe),displayAmount:gross(Number(item.early_checkin_importe))})
  if(Number(item.late_checkout_importe)>0)lines.push({key:"late",title:"Late check-out",meta:taxEnabled?`Servicio adicional · Precio final · IVA ${vatRate}% incluido`:"Servicio adicional",detail:"",amount:Number(item.late_checkout_importe),displayAmount:gross(Number(item.late_checkout_importe))})
  if(Number(item.extra)>0)lines.push({key:"extra",title:item.extra_descripcion||"Extra",meta:taxEnabled?`Cargo adicional · Precio final · IVA ${vatRate}% incluido`:"Cargo adicional",detail:"",amount:Number(item.extra),displayAmount:gross(Number(item.extra))})
  const discountAmount=Math.max(0,Number(item.descuento_importe)||0)
  if(discountAmount>0){
    const type=String(item.descuento_tipo||"").toLowerCase(),value=Math.max(0,Number(item.descuento_valor)||0),isPercent=type==="percent"||type==="porcentaje"
    const reason=String(item.descuento_motivo||"").trim()||"Motivo no documentado"
    const origin=String(item.descuento_origen||"manual").toLowerCase(),originLabel=origin==="rule"?"Regla configurada":origin==="promotion"?"Promoción configurada":origin==="package"?"Paquete":origin==="channel"?"Canal":"Ingresado manualmente"
    lines.push({key:"discount",kind:"discount",title:isPercent&&value>0?`Descuento ${value}%`:"Descuento aplicado",meta:`${originLabel} · −${money(discountAmount,item.moneda)}`,detail:reason,amount:-discountAmount})
  }
  return lines
}

export default function ReservationRecord({item,room,rooms=[],payments=[],propertyId,onBack,onNavigate,onPrimaryAction,onNoShow,onCancel,onEdit,saving,allowedViews=[]}){
  const[events,setEvents]=useState([]),[conversation,setConversation]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[sideTab,setSideTab]=useState("internal"),[noteDraft,setNoteDraft]=useState(item.notas||""),[noteSaving,setNoteSaving]=useState(false),[noteStatus,setNoteStatus]=useState(""),[chargeOpen,setChargeOpen]=useState(false),[,setChargeRevision]=useState(0),[historyDate,setHistoryDate]=useState(""),[historyOpen,setHistoryOpen]=useState(true),[roomingExpanded,setRoomingExpanded]=useState(false),[chargeExpanded,setChargeExpanded]=useState(false)
  const canOpenMessages=allowedViews.includes("messages")
  useEffect(()=>{setSideTab("internal");setConversation(null);setNoteDraft(item.notas||"");setNoteStatus("");setChargeOpen(false);setHistoryDate("");setHistoryOpen(true);setRoomingExpanded(false);setChargeExpanded(false)},[item.id])
  useEffect(()=>{let cancelled=false;async function load(){if(!item?.id||!propertyId)return;setLoading(true);setError("");try{const conversationRequest=canOpenMessages?supabase.rpc("hl_get_reservation_conversation",{p_property_id:propertyId,p_reservation_id:Number(item.id)}):Promise.resolve({data:null,error:null});const timelineRequest=supabase.rpc("hl_get_reservation_operational_timeline",{p_property_id:propertyId,p_reservation_id:Number(item.id),p_limit:500});const[eventsRes,conversationRes]=await Promise.all([timelineRequest,conversationRequest]);if(eventsRes.error)throw eventsRes.error;if(!cancelled){const nextEvents=Array.isArray(eventsRes.data)?eventsRes.data:[];setEvents(nextEvents);setConversation(conversationRes?.error?null:conversationRes?.data||null);setHistoryDate(nextEvents.length?eventDay(nextEvents[0].created_at):"")}}catch(err){if(!cancelled)setError(err?.message||"No se pudo cargar el timeline operativo de la reserva.")}finally{if(!cancelled)setLoading(false)}}load();return()=>{cancelled=true}},[item?.id,propertyId,canOpenMessages])

  const itemPayments=useMemo(()=>payments.filter(payment=>Number(payment.reserva_id)===Number(item.id)&&!["anulado","cancelado","void"].includes(String(payment.estado||"").toLowerCase())),[payments,item.id])
  const paid=useMemo(()=>itemPayments.reduce((sum,payment)=>sum+Math.max(0,Number(payment.monto||0)-Number(payment.refunded_amount||0)),0),[itemPayments])
  const historyEvents=useMemo(()=>historyDate?events.filter(event=>eventDay(event.created_at)===historyDate):[],[events,historyDate])
  const assigned=rooms.length?rooms:[room].filter(Boolean),articles=serviceLines(item,room,assigned),total=Number(item.precio_total)||0,balance=Math.max(0,total-paid),nights=Math.max(1,Number(item.noches)||Math.round((new Date(`${item.fecha_salida}T12:00:00`)-new Date(`${item.fecha_entrada}T12:00:00`))/86400000)||1)
  const taxEnabled=Boolean(item.impuestos_desglosados),vatRate=taxEnabled?Math.max(0,Number(item.iva_porcentaje)||0):0,vatAmount=taxEnabled?Math.max(0,Number(item.iva_importe)||0):0,netAmount=taxEnabled?Math.max(0,Number(item.precio_sin_impuestos_nacionales)||Math.max(0,total-vatAmount)):total
  const addonGross=value=>{const net=Math.max(0,Number(value)||0);return taxEnabled?Math.round(net*(1+vatRate/100)*100)/100:net}
  const chargesTotal=articles.reduce((sum,line)=>sum+Number(line.amount||0),0),pricingMismatch=Math.abs(chargesTotal-netAmount)>.5
  const roomingRows=reservationRoomingRows(item,assigned),channel=channelMeta(item.canal_reserva)
  const roomDetails=Array.isArray(item.habitaciones_detalle)?item.habitaciones_detalle:[]
  const checkout=roomCheckoutPresentation(item,roomingRows,assigned,room)
  const roomCheckoutCount=checkout.count,totalRoomCount=checkout.total,roomSummary=checkout.summary
  const roomingHasMore=roomingRows.length>8,visibleRoomingRows=roomingExpanded?roomingRows:roomingRows.slice(0,8)
  const chargeHasMore=articles.length>8,visibleArticles=chargeExpanded?articles:articles.slice(0,8)
  const roomHeaderExtra=<RoomCheckoutHeader checkout={checkout} hasMore={roomingHasMore} expanded={roomingExpanded} totalRows={roomingRows.length} onToggle={()=>setRoomingExpanded(value=>!value)}/>

  function navigateFromRecord(target,options){
    if(typeof window!=="undefined"&&RETURN_TARGETS.has(target))try{window.sessionStorage.setItem(RETURN_KEY,JSON.stringify({id:Number(item.id),name:item.nombre_huesped||"",code:item.numero_reserva||item.id}))}catch{}
    onNavigate?.(target,options)
  }
  function openConversation(){if(!conversation?.id)return;if(typeof window!=="undefined"){const url=new URL(window.location.href);url.searchParams.set("conversation",String(conversation.id));window.history.replaceState(window.history.state||{},"",url)}navigateFromRecord("messages",{restoreScroll:false})}
  function registerPayment(){navigateFromRecord("dailycash",{cashReservationId:Number(item.id),restoreScroll:false})}
  function openGuestRequest(event){if(!event?.entity_id)return;if(typeof window!=="undefined"){const url=new URL(window.location.href);url.searchParams.set("guest_request",String(event.entity_id));url.searchParams.delete("request_reservation");window.history.replaceState(window.history.state||{},"",url);window.dispatchEvent(new CustomEvent("hl:guest-request-focus",{detail:{id:String(event.entity_id)}}))}navigateFromRecord("requests",{restoreScroll:false})}
  async function saveInternalNote(){if(noteSaving)return;setNoteSaving(true);setError("");try{const value=noteDraft.trim();const{error:updateError}=await supabase.from("reservas").update({notas:value||null}).eq("id",item.id).eq("property_id",propertyId);if(updateError)throw updateError;setNoteDraft(value);setNoteStatus("saved")}catch(err){setNoteStatus("pending");setError(err?.message||"No se pudo guardar la nota interna.")}finally{setNoteSaving(false)}}

  const sideTabs=[["internal","Interno"],["tasks","Tareas"],["requests","Peticiones"],["floors","Pisos"],...(canOpenMessages?[["messages","Mensajes"]]:[])]
  return <div className={s.record}>
    <div className={s.recordTop}><button type="button" className={s.back} onClick={onBack}>← Reservas</button><div className={s.quickActions}><button type="button" onClick={onNoShow} disabled={saving||item.estado==="alojado"||item.estado==="finalizada"||item.estado==="cancelada"} style={{borderColor:"color-mix(in srgb,#30343b 24%,var(--line))",background:item.no_show?"#30343b":"color-mix(in srgb,#30343b 6%,var(--panelSolid))",color:item.no_show?"#fff":"var(--text)"}}>{item.no_show?"↺ Reabrir No Show":"⊘ Marcar No Show"}</button>{item.estado!=="cancelada"&&!item.no_show&&item.estado!=="finalizada"?<button type="button" onClick={onCancel} disabled={saving} style={{borderColor:"color-mix(in srgb,#c24850 35%,var(--line))",background:"color-mix(in srgb,#ef6579 5%,var(--panelSolid))",color:"#c24850"}}>Cancelar reserva</button>:null}<button type="button" onClick={onEdit} disabled={saving} style={{borderColor:"color-mix(in srgb,var(--accent) 24%,var(--line))",background:"color-mix(in srgb,var(--accent) 7%,var(--panelSolid))",color:"var(--accent)",boxShadow:"inset 0 1px color-mix(in srgb,#fff 45%,transparent)"}}>✎ Editar reserva</button></div></div>
    <div className={s.heroGrid}>
      <section className={s.heroCard}><div className={s.heroHeader}><span className={s.avatar}>{initials(item.nombre_huesped)}</span><div><h1>{item.nombre_huesped}</h1><p>{roomSummary} · Reserva {item.numero_reserva||item.id}</p></div><div style={{marginLeft:"auto",display:"grid",justifyItems:"end",gap:5}}><span className={`${s.status} ${item.estado==="alojado"?s.statusIn:item.estado==="pendiente"||item.estado==="tentativa"?s.statusWarn:""}`}>{statusLabel(item)} ✓</span><RoomCheckoutHeroBadge count={roomCheckoutCount} total={totalRoomCount} finalized={item.estado==="finalizada"}/>{Number(item.early_checkin_importe)>0||Number(item.late_checkout_importe)>0?<div style={{display:"flex",justifyContent:"flex-end",gap:5,flexWrap:"wrap"}}>{Number(item.early_checkin_importe)>0?<span style={{padding:"5px 9px",border:"1px solid color-mix(in srgb,#2f9b61 30%,var(--line))",borderRadius:999,background:"color-mix(in srgb,#37a96a 8%,var(--panelSolid))",color:"#26794d",fontSize:11,fontWeight:900}}>Early check-in · +{money(addonGross(item.early_checkin_importe),item.moneda)}</span>:null}{Number(item.late_checkout_importe)>0?<span style={{padding:"5px 9px",border:"1px solid color-mix(in srgb,#b47a18 32%,var(--line))",borderRadius:999,background:"color-mix(in srgb,#d59a2c 8%,var(--panelSolid))",color:"#956718",fontSize:11,fontWeight:900}}>Late check-out · +{money(addonGross(item.late_checkout_importe),item.moneda)}</span>:null}</div>:null}</div></div><div className={s.heroFacts}><div><small>Llegada</small><b>{fmtDate(item.fecha_entrada)}</b></div><div><small>Salida</small><b>{fmtDate(item.fecha_salida)}</b></div><div><small>Ocupación</small><b>{item.cantidad_huespedes||1} huésped{Number(item.cantidad_huespedes||1)===1?"":"es"}</b></div><div><small>Noches</small><b>{nights}</b></div><div><small>Habitaciones</small><b>{totalRoomCount}</b><RoomCheckoutFact count={roomCheckoutCount}/></div><div><small>Régimen</small><b>{item.regimen||"Alojamiento"}</b></div><div><small>Canal</small><b style={{display:"inline-flex",alignItems:"center",gap:6}}><ReservationChannelLogo value={item.canal_reserva}/><span>{channel.label}</span></b></div><div><small>Teléfono</small><b>{item.telefono_huesped||"—"}</b></div><div><small>Recibida</small><b>{fmtDate(item.created_at)}</b></div><div className={s.contactFact}><small>Contacto</small><b>{item.email_huesped||"Sin email cargado"}</b></div></div></section>
      <aside className={s.sideCard}><nav>{sideTabs.map(([value,label])=><button type="button" key={value} className={sideTab===value?s.tabActive:""} onClick={()=>setSideTab(value)}>{label}</button>)}</nav><div className={s.sideBody} style={sideTab==="internal"?{justifyContent:"flex-start",alignItems:"stretch"}:undefined}>{sideTab==="tasks"?<><p>Gestioná tareas vinculadas a esta estadía desde Operación.</p><button type="button" onClick={()=>navigateFromRecord("tasks")}>＋ Añadir tarea</button></>:sideTab==="requests"?<><p>Pedidos y solicitudes del huésped asociados a la reserva.</p><button type="button" onClick={()=>navigateFromRecord("requests")}>Abrir peticiones</button></>:sideTab==="floors"?<><p>{assigned.length>1?`Coordiná limpieza y estado de las ${assigned.length} habitaciones asignadas.`:"Estado de habitación, limpieza y coordinación de pisos."}</p><button type="button" onClick={()=>navigateFromRecord("housekeeping")}>Abrir Housekeeping</button></>:sideTab==="messages"?(conversation?<><p>{conversation.channel?`Conversación por ${conversation.channel} vinculada a esta reserva.`:"Conversación vinculada a esta reserva."}</p><button type="button" onClick={openConversation}>Abrir conversación</button></>:<p>Todavía no hay una conversación que pueda vincularse de forma segura a esta reserva.</p>):<div style={{display:"grid",gap:7,width:"100%"}}><strong style={{fontSize:10.5}}>Notas internas</strong><textarea value={noteDraft} onChange={event=>{setNoteDraft(event.target.value);setNoteStatus("pending")}} placeholder="Escribí información importante para el equipo…" rows="5" style={{width:"100%",minHeight:92,boxSizing:"border-box",resize:"vertical",border:"1px solid var(--line)",borderRadius:9,padding:"9px 10px",background:"color-mix(in srgb,var(--panelSolid) 88%,transparent)",color:"var(--text)",font:"inherit",fontSize:10.5,lineHeight:1.45,outline:"none",verticalAlign:"top"}}/><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:8}}><small style={{margin:0,color:noteStatus==="saved"?"#26794d":noteStatus==="pending"?"#a36d16":"var(--muted)",fontWeight:noteStatus?900:600}}>{noteStatus==="saved"?"✓ Nota guardada":noteStatus==="pending"?"● Cambios pendientes de guardar":"Visible para el equipo del hotel"}</small><button type="button" disabled={noteSaving} onClick={saveInternalNote} style={{marginTop:0}}>{noteSaving?"Guardando…":"Guardar nota"}</button></div></div>}</div></aside>
    </div>
    {error?<div className={s.alert}>{error}</div>:null}
    <div style={{marginTop:12}}><RecordCard title="Habitaciones" headerExtra={roomHeaderExtra}><ReservationRoomJourney item={item}/>{roomingRows.length?<div className={s.compactList}>{visibleRoomingRows.map(row=><ReservationRoomRateRow key={row.key} row={row} detail={roomDetails.find(detail=>String(detail?.habitacion_id||"")===String(row.roomId||""))||{}} item={item} checkoutDate={checkout.dates[String(row.roomId)]||""} currency={item.moneda} taxEnabled={taxEnabled} vatRate={vatRate} defaultOpen={roomingRows.length===1}/>)}</div>:<EmptyCard text="Esta reserva no tiene habitaciones configuradas."/>}</RecordCard></div>
    <div className={s.contentGrid}><RecordCard title="Cargos" headerExtra={<div style={{display:"flex",alignItems:"center",gap:6}}>{chargeHasMore?<button type="button" onClick={()=>setChargeExpanded(value=>!value)} aria-expanded={chargeExpanded}>{chargeExpanded?"Ver menos":`Ver todos (${articles.length})`} {chargeExpanded?"▴":"▾"}</button>:null}<button type="button" className={s.primaryCardAction} onClick={()=>setChargeOpen(true)}>＋ Agregar cargo</button></div>}>{pricingMismatch?<div className={s.pricingWarning}><span>!</span><div><b>Los cargos no coinciden con la base de la reserva</b><small>Cargos: {money(chargesTotal,item.moneda)} · Precio sin impuestos: {money(netAmount,item.moneda)}. Revisá el precio o registrá un descuento explícito con motivo.</small></div></div>:null}<div className={s.articleList}>{visibleArticles.map(line=><article key={line.key} className={line.kind==="discount"?s.discountLine:""}><div>{line.kind==="discount"?<span className={s.discountIcon}>%</span>:null}<b>{line.title}</b><small>{line.meta}</small>{line.detail?<p>{line.detail}</p>:null}</div><strong>{money(line.displayAmount??line.amount,item.moneda)}</strong></article>)}</div>{taxEnabled?<div style={{margin:"10px 12px 0",padding:"10px 12px",border:"1px solid color-mix(in srgb,var(--accent) 18%,var(--line))",borderRadius:11,background:"color-mix(in srgb,var(--accent) 4%,var(--panelSolid))",display:"grid",gap:6,fontSize:10.5}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><span style={{color:"var(--muted)"}}>Precio sin impuestos nacionales</span><b>{money(netAmount,item.moneda)}</b></div><div style={{display:"flex",justifyContent:"space-between",gap:12}}><span style={{color:"var(--muted)"}}>IVA {vatRate}%</span><b>+ {money(vatAmount,item.moneda)}</b></div><div style={{display:"flex",justifyContent:"space-between",gap:12,paddingTop:6,borderTop:"1px solid var(--line)",fontSize:12}}><strong>Total</strong><strong>{money(total,item.moneda)}</strong></div></div>:null}<footer className={s.articleTotal}><span className={s.totalLabel}>Total reserva</span><b>{money(total,item.moneda)}</b><small><span className={s.paidAmount}>Pagado {money(paid,item.moneda)}</span><span> · </span><span className={s.pendingAmount}>Pendiente {money(balance,item.moneda)}</span></small></footer></RecordCard><div className={s.financeGrid}>
      <div style={{gridColumn:"1 / -1",gridRow:"1",minWidth:0}}><ReservationFolioBilling reservation={item} propertyId={propertyId} onNavigate={navigateFromRecord}/></div>
      <RecordCard title="Pagos" action="Registrar pago" primaryAction onAction={registerPayment}>{itemPayments.length?<div className={s.compactList}>{itemPayments.map(payment=><div key={payment.id}><span><b>{payment.metodo||payment.source||"Pago"}</b><small>{fmtDateTime(payment.created_at)}{payment.referencia?` · ${payment.referencia}`:""}</small></span><strong>{money(Number(payment.monto||0)-Number(payment.refunded_amount||0),payment.moneda||item.moneda)}</strong></div>)}</div>:<EmptyCard text="No hay pagos registrados." action="Registrar pago" onAction={registerPayment}/>}</RecordCard>
      <RecordCard title="Timeline operativo" headerExtra={<div style={{display:"flex",alignItems:"center",gap:6}}><div className={s.historyFilter}><span>Fecha</span><input type="date" value={historyDate} onChange={event=>setHistoryDate(event.target.value)} aria-label="Filtrar timeline por fecha"/></div><button type="button" onClick={()=>setHistoryOpen(value=>!value)} aria-expanded={historyOpen} aria-label={historyOpen?"Ocultar timeline":"Mostrar timeline"} title={historyOpen?"Ocultar timeline":"Mostrar timeline"}>{historyOpen?"▴":"▾"}</button></div>}>{historyOpen?(loading?<EmptyCard text="Cargando timeline…"/>:!events.length?<EmptyCard text="Todavía no hay eventos operativos registrados para esta reserva."/>:historyEvents.length?<div style={{maxHeight:230,overflow:"auto"}}><div className={s.compactList}>{historyEvents.map(event=>{const view=historyPresentation(event,item.moneda,item);return <div key={event.id}><span><b>{view.title}</b><small>{view.detail}{event.actor_name?` · ${event.actor_name}`:" · Sistema"}</small></span><span style={{display:"grid",justifyItems:"end",gap:4}}><strong>{fmtDateTime(event.created_at)}</strong>{event.source==="guest_request"&&allowedViews.includes("requests")?<button type="button" onClick={()=>openGuestRequest(event)} style={{border:"1px solid var(--line)",borderRadius:7,background:"var(--panelSolid)",color:"var(--accent)",padding:"4px 7px",font:"inherit",fontSize:9,fontWeight:850,cursor:"pointer"}}>Abrir petición</button>:null}</span></div>})}</div></div>:<EmptyCard text="No hay eventos operativos registrados en esa fecha."/>):<EmptyCard text="Timeline contraído."/>}</RecordCard>
    </div></div>
    {chargeOpen?<ReservationChargePanel reservation={item} propertyId={propertyId} onClose={()=>setChargeOpen(false)} onSaved={({event})=>{if(event){setEvents(current=>[event,...current]);setHistoryDate(eventDay(event.created_at))}setChargeRevision(value=>value+1)}}/>:null}
    <div className={`${s.bottomBar} ${s.bottomBarActionsOnly}`}><div className={s.bottomActions}><button type="button" onClick={()=>onNavigate?.("planning")}>Ver en Planning</button></div></div>
  </div>
}
