"use client"
import{useEffect,useState}from"react"
import{money,shortDate,initials,isoDate}from"../../core/formatters"
import ui from"../../v2.module.css"
import polish from"./frontdesk-polish.module.css"

export function Lobby({settings,rooms,reservations,payments,onView,onOpen,search,onSearch,onNewReservation,onMenu}){
  const today=isoDate(),live=reservations.filter(r=>r.estado!=="cancelada"&&!r.no_show),arrivals=live.filter(r=>r.fecha_entrada===today&&r.estado!=="alojado"),departures=live.filter(r=>r.fecha_salida===today&&r.estado!=="finalizada"),inhouse=live.filter(r=>r.fecha_entrada<=today&&r.fecha_salida>today&&r.estado!=="finalizada"),sellable=rooms.filter(r=>r.activa!==false&&!['mantenimiento','fuera_servicio'].includes(String(r.estado).toLowerCase())),occupancy=sellable.length?Math.round(new Set(inhouse.map(r=>r.habitacion_id)).size/sellable.length*100):0,paid=new Map();payments.forEach(p=>paid.set(String(p.reserva_id),(paid.get(String(p.reserva_id))||0)+Number(p.monto||0)));const balance=live.reduce((a,r)=>a+Math.max(0,Number(r.precio_total||0)-(paid.get(String(r.id))||0)),0),attention=rooms.filter(r=>['sucia','inspeccion','mantenimiento'].includes(String(r.estado).toLowerCase())).length,[clock,setClock]=useState(null)
  useEffect(()=>{const tick=()=>setClock(new Date()),id=setInterval(tick,30000);tick();return()=>clearInterval(id)},[])
  const clockDate=clock?new Intl.DateTimeFormat("es-AR",{weekday:"long",day:"2-digit",month:"long"}).format(clock):"",clockTime=clock?new Intl.DateTimeFormat("es-AR",{hour:"2-digit",minute:"2-digit"}).format(clock):""
  return <div className={`${ui.content} ${polish.lobbyContent}`}>
    <section className={`${ui.lobby} ${polish.lobbyHero}`}><div className={ui.marble}/><div className={ui.wood}/><div className={ui.glow}/><button className={polish.mobileMenu} onClick={onMenu}>☰</button><div><div className={polish.metaRow}><small>EL ESCRITORIO DIGITAL DE {(settings?.hotel_name||"TU HOTEL").toUpperCase()}</small><span>{clockDate}{clockDate&&clockTime?" · ":""}<b>{clockTime}</b></span></div><h2>Recepción serena.<br/><em>Operación impecable.</em></h2><p>“{settings?.motto||"La hospitalidad se siente en cada detalle."}”</p><div className={polish.heroButtons}><button onClick={()=>onView("calendar")}>Abrir Command Center →</button>{onNewReservation&&<button className={polish.newReservation} onClick={onNewReservation}>＋ Nueva reserva</button>}</div><form className={polish.heroSearch} onSubmit={e=>{e.preventDefault();onView("reservations")}}><span>⌕</span><input value={search||""} onChange={e=>onSearch?.(e.target.value)} placeholder="Buscar huésped, reserva o habitación…"/><button>Buscar</button></form></div><aside><small>OCUPACIÓN HOY</small><b>{occupancy}%</b><span>{arrivals.length} IN · {departures.length} OUT</span></aside></section>
    <section className={polish.brief} aria-label="Resumen del turno">
      <div className={polish.quickAccess}><header><small>ACCESOS RÁPIDOS</small><h3>Lo que recepción usa todo el día.</h3></header><div>{<button onClick={()=>onView("calendar")}><i>▦</i><span><b>Command Center</b><small>Calendario operativo</small></span></button>}{onNewReservation&&<button onClick={onNewReservation}><i>＋</i><span><b>Nueva reserva</b><small>Crear estadía</small></span></button>}<button onClick={()=>onView("housekeeping")}><i>◇</i><span><b>Housekeeping</b><small>Prioridades y estados</small></span></button><button onClick={()=>onView("reports")}><i>▥</i><span><b>Reportes</b><small>Recepción y operación</small></span></button></div></div>
      <div className={polish.briefRail}>
        <button onClick={()=>onView("calendar")}><span><small>LLEGADAS</small><b>Recepción prepara el próximo momento</b></span><strong>{arrivals.length}</strong><em>IN de hoy</em></button>
        <button onClick={()=>onView("housekeeping")}><span><small>OPERACIÓN</small><b>Habitaciones que necesitan atención</b></span><strong>{attention}</strong><em>housekeeping / mantenimiento</em></button>
        <button onClick={()=>onView("cash")}><span><small>SALDOS</small><b>Pendiente sobre estadías activas</b></span><strong>{money(balance)}</strong><em>caja y folios</em></button>
      </div>
    </section>
    <div className={ui.twoCols}><section className={`${ui.panel} ${polish.panelPremium}`}><h3>Próximos momentos</h3>{[...arrivals,...departures].slice(0,8).map(r=><button className={ui.listRow} key={`${r.id}-${r.fecha_salida}`} onClick={()=>onOpen(r)}><span><b>{r.nombre_huesped}</b><small>{r.fecha_salida===today?"Salida":"Llegada"} · {r.numero_reserva||r.id}</small></span><em>{r.fecha_salida===today?"OUT":"IN"}</em></button>)}</section><section className={`${ui.panel} ${polish.panelPremium}`}><h3>En casa</h3>{inhouse.slice(0,8).map(r=><button className={ui.listRow} key={r.id} onClick={()=>onOpen(r)}><span><b>{r.nombre_huesped}</b><small>hasta {shortDate(r.fecha_salida)}</small></span><em>IN</em></button>)}</section></div>
  </div>
}

export function Reservations({reservations,rooms,search,onOpen}){const q=search.toLowerCase(),items=reservations.filter(r=>!q||`${r.nombre_huesped} ${r.numero_reserva||""} ${r.email_huesped||""}`.toLowerCase().includes(q));return <div className={ui.content}><div className={`${ui.editorial} ${polish.compactEditorial}`}><div><small>RESERVATION DESK</small><h2>Reservas</h2><p>Buscá, abrí y editá una estadía sin salir del contexto de recepción.</p></div></div><div className={ui.tableWrap}><table><thead><tr><th>Reserva</th><th>Huésped</th><th>Habitación</th><th>Estadía</th><th>Estado</th></tr></thead><tbody>{items.map(r=><tr key={r.id} onClick={()=>onOpen(r)}><td><b>{r.numero_reserva||r.id}</b><small>{r.canal_reserva||"Directa"}</small></td><td><b>{r.nombre_huesped}</b><small>{r.email_huesped||r.telefono_huesped||""}</small></td><td>{rooms.find(x=>String(x.id)===String(r.habitacion_id))?.nombre||r.habitacion_id}</td><td>{shortDate(r.fecha_entrada)} → {shortDate(r.fecha_salida)}</td><td>{r.estado}</td></tr>)}</tbody></table></div></div>}

export function GuestCRM({guests,search}){const q=search.toLowerCase(),items=guests.filter(g=>!q||`${g.full_name} ${g.email||""} ${g.phone||""}`.toLowerCase().includes(q));return <div className={ui.content}><div className={`${ui.editorial} ${polish.compactEditorial}`}><div><small>GUEST CRM</small><h2>Huéspedes</h2><p>Preferencias, historia, etiquetas y contexto sobreviven a cada estadía.</p></div></div><div className={ui.cardGrid}>{items.map(g=><article className={ui.guestCard} key={g.id}><span>{initials(g.full_name)}</span><div><small>{g.vip_level?.toUpperCase()}</small><h3>{g.full_name}</h3><p>{g.email||g.phone||g.document_number||"Sin contacto"}</p><em>{g.tags?.join(" · ")||"Sin etiquetas"}</em></div></article>)}</div></div>}
