"use client"

import{useMemo,useState}from"react"
import{addDays,isoDate,money,shortDate}from"../../core/formatters"
import s from"./hotelgest-dashboard.module.css"

const dayLabel=offset=>offset<0?"Ayer":offset>0?"Mañana":"Hoy"
const stateOf=r=>{const v=String(r.estado||"").toLowerCase();if(v==="alojado")return"IN";if(v==="finalizada")return"OUT";if(v==="tentativa")return"TENTATIVA";return"RESERVA"}
const roomState=r=>{const v=String(r?.estado||"").toLowerCase();if(["inspeccionada","inspeccion","disponible","libre"].includes(v))return"ready";if(v==="limpia")return"clean";if(["sucia","limpieza","en_limpieza"].includes(v))return"dirty";return"other"}
const created=r=>String(r.created_at||r.fecha_creacion||"").slice(0,10)
const overlap=(r,day)=>String(r.fecha_entrada||"")<=day&&String(r.fecha_salida||"")>day
const balance=(r,payments)=>Math.max(0,Number(r.precio_total||0)-payments.filter(p=>String(p.reserva_id)===String(r.id)).reduce((a,p)=>a+Number(p.monto||0),0))
const nights=r=>Math.max(1,Math.round((new Date(`${r.fecha_salida}T12:00:00`)-new Date(`${r.fecha_entrada}T12:00:00`))/86400000))

function LineChart({values}){const max=Math.max(1,...values),pts=values.map((v,i)=>`${i/(values.length-1||1)*100},${45-v/max*38}`).join(" ");return <svg viewBox="0 0 100 48" preserveAspectRatio="none" className={s.chart}><path d="M0 46H100"/><polyline points={pts}/></svg>}
function DayTabs({value,onChange}){return <div className={s.dayTabs}>{[-1,0,1].map(x=><button key={x} type="button" className={value===x?s.dayActive:""} onClick={()=>onChange(x)}>{dayLabel(x)}</button>)}</div>}
function Avatar({name}){const letters=String(name||"H").split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();return <span className={s.avatar}>{letters||"H"}</span>}

function ReservationRow({r,rooms,onOpen,kind}){const room=rooms.find(x=>String(x.id)===String(r.habitacion_id)),pax=Number(r.cantidad_huespedes||1);return <button className={s.reservationRow} type="button" onClick={()=>onOpen(r)}><Avatar name={r.nombre_huesped}/><span className={s.rowText}><b>{r.nombre_huesped||"Sin titular"}</b><small>{room?.tipo||"Habitación"} | {room?.nombre||"Sin asignar"}</small><em>{r.canal_reserva||"Recepción"} · #{r.numero_reserva||String(r.id).slice(-8)}</em></span><span className={s.rowMeta}><b>{pax} ↟</b><small>{nights(r)} ◒</small>{kind==="arrival"&&<i>IN</i>}{kind==="departure"&&<i>OUT</i>}</span></button>}

function OperationColumn({kind,title,reservations,rooms,today,onOpen}){const[offset,setOffset]=useState(0),[q,setQ]=useState(""),day=addDays(today,offset);const list=useMemo(()=>reservations.filter(r=>{if(kind==="arrival"&&r.fecha_entrada!==day)return false;if(kind==="departure"&&r.fecha_salida!==day)return false;if(kind==="stay"&&!(overlap(r,day)&&(day!==today||stateOf(r)==="IN")))return false;const query=q.trim().toLowerCase();if(!query)return true;const room=rooms.find(x=>String(x.id)===String(r.habitacion_id));return`${r.nombre_huesped||""} ${r.numero_reserva||""} ${room?.nombre||""}`.toLowerCase().includes(query)}),[reservations,rooms,kind,day,today,q]);return <section className={s.operation}><header><b>{list.length} {title}</b><span>⋯</span></header><DayTabs value={offset} onChange={setOffset}/><label className={s.listSearch}>⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Huésped, habitación, o número"/></label><div className={s.reservationList}>{list.map(r=><ReservationRow key={r.id} r={r} rooms={rooms} onOpen={onOpen} kind={kind}/>)}{!list.length&&<div className={s.empty}>Sin movimientos para {dayLabel(offset).toLowerCase()}.</div>}</div></section>}

function ActionDrawer({reservation,rooms,payments,onClose,onOpen,onView}){if(!reservation)return null;const room=rooms.find(x=>String(x.id)===String(reservation.habitacion_id)),due=balance(reservation,payments),phone=String(reservation.telefono_huesped||"").replace(/\D/g,"");return <div className={s.drawerShade} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className={s.drawer}><header><div><small>Acciones rápidas</small><h3>{reservation.nombre_huesped||"Reserva"}</h3><p>{room?.tipo||"Habitación"} · {room?.nombre||"Sin asignar"}</p></div><button onClick={onClose}>Cerrar</button></header><div className={s.drawerStats}><span><small>Llegada</small><b>{shortDate(reservation.fecha_entrada)}</b></span><span><small>Salida</small><b>{shortDate(reservation.fecha_salida)}</b></span><span><small>Estado</small><b>{stateOf(reservation)}</b></span><span><small>Pendiente</small><b>{money(due,reservation.moneda||"ARS")}</b></span></div><div className={s.quickGrid}><button onClick={()=>onOpen(reservation)}>Abrir reserva</button><button onClick={()=>onView("calendar")}>Ver en Planning</button><button onClick={()=>onView("housekeeping")}>Limpieza</button>{phone&&<button onClick={()=>window.open(`https://wa.me/${phone}`,"_blank","noopener,noreferrer")}>WhatsApp</button>}</div><section className={s.detailList}><div><span>Canal</span><b>{reservation.canal_reserva||"Directa"}</b></div><div><span>Reserva</span><b>#{reservation.numero_reserva||String(reservation.id).slice(-8)}</b></div><div><span>Ocupación</span><b>{reservation.cantidad_huespedes||1} huésped(es)</b></div><div><span>Total</span><b>{money(reservation.precio_total||0,reservation.moneda||"ARS")}</b></div></section></aside></div>}

export default function HotelGestDashboard({settings={},rooms=[],reservations=[],payments=[],onView,onOpen,onNewReservation}){
 const today=isoDate(),[selected,setSelected]=useState(null),live=reservations.filter(r=>r.estado!=="cancelada"&&!r.no_show),sellable=rooms.filter(r=>r.activa!==false),occupied=new Set(live.filter(r=>overlap(r,today)).map(r=>String(r.habitacion_id))),occ=Math.round(occupied.size/Math.max(1,sellable.length)*100),month=today.slice(0,7),year=today.slice(0,4),received={today:live.filter(r=>created(r)===today).length,month:live.filter(r=>created(r).startsWith(month)).length,year:live.filter(r=>created(r).startsWith(year)).length},clean=sellable.reduce((a,r)=>{const k=roomState(r);a[k]=(a[k]||0)+1;return a},{}),forecast=Array.from({length:12},(_,i)=>{const d=addDays(today,(i-6)*30),m=d.slice(0,7);return live.filter(r=>String(r.fecha_entrada||"").startsWith(m)).reduce((sum,r)=>sum+Number(r.precio_total||0),0)}),yearRevenue=live.filter(r=>String(r.fecha_entrada||"").startsWith(year)).reduce((sum,r)=>sum+Number(r.precio_total||0),0),todayRevenue=live.filter(r=>overlap(r,today)).reduce((sum,r)=>sum+Number(r.precio_total||0)/nights(r),0),tasks=[]
 live.filter(r=>r.fecha_entrada===today&&stateOf(r)==="RESERVA").forEach(r=>{const room=sellable.find(x=>String(x.id)===String(r.habitacion_id));tasks.push({title:roomState(room)==="ready"?"Check-in pendiente":"Preparar habitación",detail:`${r.nombre_huesped||"Huésped"} · ${room?.nombre||"sin asignar"}`,r})});live.filter(r=>r.fecha_salida===today&&stateOf(r)==="IN").forEach(r=>tasks.push({title:"Salida pendiente",detail:r.nombre_huesped||"Huésped",r}))
 return <div className={s.page}><div className={s.dashboardGrid}><section className={s.production}><header><div><b>{money(todayRevenue,"ARS")}</b><small>Hasta hoy</small></div><div><b>{money(yearRevenue,"ARS")}</b><small>Previsto para este año</small></div><div className={s.segment}><button className={s.segmentActive}>Producción</button><button>Ocupación</button></div></header><LineChart values={forecast}/><footer>{["ENE.","FEB.","MAR.","ABR.","MAY.","JUN.","JUL.","AGO.","SEP.","OCT.","NOV.","DIC."].map(m=><span key={m}>{m}</span>)}</footer></section><section className={s.tasks}><header><b>TAREAS</b><button type="button" onClick={()=>onView("housekeeping")}>Ver todas</button></header><div>{tasks.slice(0,5).map((t,i)=><button key={i} type="button" onClick={()=>setSelected(t.r)}><i/><span><b>{t.title}</b><small>{t.detail}</small></span></button>)}{!tasks.length&&<p>Sin tareas pendientes para hoy.</p>}</div></section><section className={s.occupancy}><small>OCUPACIÓN</small><div><span><b>{occ}%</b><small>Mes</small></span><span><b>{Math.round(live.filter(r=>String(r.fecha_entrada||"").startsWith(year)).length/Math.max(1,sellable.length))}%</b><small>Año</small></span></div></section><section className={s.received}><small>RESERVAS RECIBIDAS</small><div><span><b>{received.today}</b><small>Hoy</small></span><span><b>{received.month}</b><small>Mes</small></span><span><b>{received.year}</b><small>Año</small></span></div></section><section className={s.cleaning}><header><small>LIMPIEZA</small><button onClick={()=>onView("housekeeping")}>⋯</button></header><div><span data-tone="ready"><b>{clean.ready||0}</b><small>Inspeccionado</small></span><span data-tone="clean"><b>{clean.clean||0}</b><small>Limpio</small></span><span data-tone="dirty"><b>{clean.dirty||0}</b><small>Sucio</small></span></div></section></div><div className={s.operationGrid}><OperationColumn kind="arrival" title="Llegadas" reservations={live} rooms={sellable} today={today} onOpen={setSelected}/><OperationColumn kind="stay" title="En casa" reservations={live} rooms={sellable} today={today} onOpen={setSelected}/><OperationColumn kind="departure" title="Salidas" reservations={live} rooms={sellable} today={today} onOpen={setSelected}/></div>{onNewReservation&&<button className={s.fab} type="button" onClick={onNewReservation}>＋ Crear reserva</button>}<ActionDrawer reservation={selected} rooms={sellable} payments={payments} onClose={()=>setSelected(null)} onOpen={onOpen} onView={onView}/></div>
}
