"use client"
import{useEffect,useRef,useState}from"react"
import{createPortal}from"react-dom"
import{money}from"../../core/formatters"
import{mercadoPagoAuthFetch}from"../../services/mercadoPagoOAuth"
import g from"./guarantee.module.css"

let sdkPromise=null
async function mercadoPago(publicKey){
  if(!publicKey)throw new Error("Mercado Pago no devolvió la Public Key de este hotel.")
  if(typeof window==="undefined")throw new Error("Mercado Pago solo puede abrirse desde el navegador.")
  if(!window.MercadoPago){sdkPromise||=new Promise((resolve,reject)=>{const existing=document.querySelector('script[src="https://sdk.mercadopago.com/js/v2"]');if(existing){existing.addEventListener("load",resolve,{once:true});existing.addEventListener("error",()=>reject(new Error("No se pudo cargar Mercado Pago.")),{once:true});return}const script=document.createElement("script");script.src="https://sdk.mercadopago.com/js/v2";script.async=true;script.onload=resolve;script.onerror=()=>reject(new Error("No se pudo cargar Mercado Pago."));document.head.appendChild(script)});await sdkPromise}
  if(!window.MercadoPago)throw new Error("Mercado Pago no está disponible.")
  return new window.MercadoPago(publicKey,{locale:"es-AR"})
}
function statusText(status){return({card_saved:"TARJETA GUARDADA",authorized:"GARANTÍA ACTIVA",captured:"GARANTÍA COBRADA",released:"GARANTÍA LIBERADA",expired:"RETENCIÓN VENCIDA",failed:"RETENCIÓN RECHAZADA",pending:"PENDIENTE",cancelled:"SIN TARJETA"})[status]||String(status||"SIN GARANTÍA").toUpperCase()}
function statusTone(status){if(["card_saved","authorized"].includes(status))return g.good;if(["pending","expired"].includes(status))return g.warn;if(status==="failed")return g.bad;return""}
function expiry(guarantee){return guarantee?.expiration_month&&guarantee?.expiration_year?`${String(guarantee.expiration_month).padStart(2,"0")}/${String(guarantee.expiration_year).slice(-2)}`:""}

function NewCardModal({publicKey,guest,onClose,onToken}){
  const prefix=useRef(`hlmp-${Math.random().toString(36).slice(2)}`).current,consent=useRef(null),cardForm=useRef(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false)
  useEffect(()=>{let active=true;(async()=>{try{const mp=await mercadoPago(publicKey);if(!active)return;cardForm.current=mp.cardForm({amount:"1",iframe:true,form:{id:`${prefix}-form`,cardNumber:{id:`${prefix}-number`,placeholder:"Número de tarjeta"},expirationDate:{id:`${prefix}-expiry`,placeholder:"MM/AA"},securityCode:{id:`${prefix}-cvv`,placeholder:"CVV"},cardholderName:{id:`${prefix}-holder`,placeholder:"Nombre como figura en la tarjeta"},issuer:{id:`${prefix}-issuer`,placeholder:"Banco emisor"},installments:{id:`${prefix}-installments`,placeholder:"Cuotas"},identificationType:{id:`${prefix}-idtype`,placeholder:"Tipo de documento"},identificationNumber:{id:`${prefix}-idnumber`,placeholder:"Número de documento"},cardholderEmail:{id:`${prefix}-email`,placeholder:"Email"}},callbacks:{onFormMounted:error=>error&&setMessage(error.message||"No se pudo abrir el formulario seguro."),onSubmit:async event=>{event.preventDefault();if(!consent.current?.checked)return setMessage("Necesitamos registrar la aceptación de la garantía.");setBusy(true);setMessage("");try{const data=cardForm.current.getCardFormData();if(!data?.token)throw new Error("Mercado Pago no devolvió el token de la tarjeta.");await onToken({token:data.token,payment_method_id:data.paymentMethodId||null,issuer_id:data.issuerId||null,email:data.cardholderEmail||guest?.email||"",identification_type:data.identificationType||null,identification_number:data.identificationNumber||guest?.document||"",cardholder_name:data.cardholderName||"",consent_accepted:true,consent_note:"El huésped aceptó usar la tarjeta como garantía de la reserva y autorizar retenciones/cargos documentados según las condiciones informadas."});onClose()}catch(error){setMessage(error.message)}finally{setBusy(false)}},onFetching:()=>()=>{}}})}catch(error){active&&setMessage(error.message)}})();return()=>{active=false;try{cardForm.current?.unmount?.()}catch{}}},[publicKey,prefix])
  return createPortal(<div className={g.overlay} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className={g.modal}><header><div><h4>Tarjeta de garantía</h4><p>Los datos sensibles viajan por campos seguros de Mercado Pago.</p></div><button type="button" className={g.close} onClick={onClose}>×</button></header><form id={`${prefix}-form`} className={g.form}><div className={g.fields}><label className={`${g.field} ${g.wide}`}><span>Número de tarjeta</span><div id={`${prefix}-number`} className={g.secure}/></label><label className={g.field}><span>Vencimiento</span><div id={`${prefix}-expiry`} className={g.secure}/></label><label className={g.field}><span>CCV / CVV</span><div id={`${prefix}-cvv`} className={g.secure}/></label><label className={`${g.field} ${g.wide}`}><span>Nombre del titular</span><input id={`${prefix}-holder`} autoComplete="cc-name"/></label><label className={g.field}><span>Tipo documento</span><select id={`${prefix}-idtype`} defaultValue="DNI"><option value="DNI">DNI</option></select></label><label className={g.field}><span>Documento</span><input id={`${prefix}-idnumber`} defaultValue={guest?.document||""}/></label><label className={`${g.field} ${g.wide}`}><span>Email del titular / huésped</span><input id={`${prefix}-email`} type="email" defaultValue={guest?.email||""}/></label><div className={g.hiddenAux}><select id={`${prefix}-issuer`}/><select id={`${prefix}-installments`}/></div></div><label className={g.consent}><input ref={consent} type="checkbox"/><span>El huésped acepta que esta tarjeta se utilice como garantía de la estadía y que el hotel pueda efectuar una retención temporal y, ante consumos o daños debidamente documentados, capturar total o parcialmente el importe autorizado conforme a las condiciones informadas.</span></label>{message&&<div className={g.message}>{message}</div>}<div className={g.foot}><small>Habitación Llena no recibe ni guarda el número completo de tarjeta ni el CVV. Mercado Pago devuelve únicamente un token temporal.</small><button className={g.primary} disabled={busy}>{busy?"Protegiendo tarjeta…":"Guardar tarjeta segura"}</button></div></form></div></div>,document.body)
}

function CvvModal({publicKey,cardId,amount,currency,onClose,onToken}){
  const id=useRef(`hlmp-cvv-${Math.random().toString(36).slice(2)}`).current,mp=useRef(null),field=useRef(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false)
  useEffect(()=>{let active=true;(async()=>{try{mp.current=await mercadoPago(publicKey);if(!active)return;field.current=mp.current.fields.create("securityCode",{placeholder:"CVV"});field.current.mount(id)}catch(error){active&&setMessage(error.message)}})();return()=>{active=false;try{field.current?.unmount?.()}catch{}}},[publicKey,id])
  async function submit(e){e.preventDefault();setBusy(true);setMessage("");try{const token=await mp.current.fields.createCardToken({cardId});if(!token?.id)throw new Error("Mercado Pago no pudo validar el código de seguridad.");await onToken(token.id);onClose()}catch(error){setMessage(error.message)}finally{setBusy(false)}}
  return createPortal(<div className={g.overlay} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className={g.modal} style={{maxWidth:430}}><header><div><h4>Retener {money(amount,currency)}</h4><p>Ingresá el código de seguridad para generar la autorización.</p></div><button type="button" className={g.close} onClick={onClose}>×</button></header><form className={g.cvvBox} onSubmit={submit}><label className={g.field}><span>CCV / CVV</span><div id={id} className={g.secure}/></label>{message&&<div className={g.message}>{message}</div>}<p className={g.hint}>El CVV se procesa dentro del campo seguro de Mercado Pago y nunca queda guardado en Habitación Llena.</p><button className={g.primary} disabled={busy}>{busy?"Autorizando…":"Confirmar retención"}</button></form></div></div>,document.body)
}

export default function MercadoPagoGuaranteePanel({propertyId,reservationId,guest,currency="ARS",stayTotal=0,stagedToken=null,onStagedToken,onClearStaged,onGuaranteeChanged}){
  const[snapshot,setSnapshot]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[modal,setModal]=useState(null),[amount,setAmount]=useState(""),[captureAmount,setCaptureAmount]=useState(""),[concept,setConcept]=useState("Rotura / daño documentado")
  const defaultAmount=Math.max(1,Math.min(Number(stayTotal||150000)||150000,150000))
  useEffect(()=>{if(!amount)setAmount(String(defaultAmount))},[defaultAmount])
  async function load(){if(!propertyId)return;try{const data=reservationId?await mercadoPagoAuthFetch(`/api/hotel/mercadopago/guarantee?reservation_id=${encodeURIComponent(reservationId)}`):await mercadoPagoAuthFetch(`/api/hotel/mercadopago/config?property_id=${encodeURIComponent(propertyId)}`);setSnapshot(reservationId?data:{platform_ready:data.platform_ready,connection:data.connection,events:[],guarantee:null});const auth=Number(data?.guarantee?.authorized_amount||0);if(auth>0)setCaptureAmount(String(auth))}catch(error){setMessage(error.message)}}
  useEffect(()=>{load();const handler=()=>load();window.addEventListener("hl:mercadopago-connected",handler);return()=>window.removeEventListener("hl:mercadopago-connected",handler)},[propertyId,reservationId])
  async function connect(){setBusy(true);setMessage("");try{const data=await mercadoPagoAuthFetch("/api/hotel/mercadopago/oauth/start",{method:"POST",body:JSON.stringify({property_id:propertyId})});window.location.href=data.url}catch(error){setMessage(error.message);setBusy(false)}}
  async function action(name,payload={}){setBusy(true);setMessage("");try{const data=await mercadoPagoAuthFetch("/api/hotel/mercadopago/guarantee",{method:"POST",body:JSON.stringify({reservation_id:reservationId,action:name,...payload})});setSnapshot(data);onGuaranteeChanged?.(data.guarantee);return data}catch(error){setMessage(error.message);throw error}finally{setBusy(false)}}
  async function saveToken(payload){if(!reservationId){onStagedToken?.(payload);setMessage("Tarjeta protegida. Se vinculará a la reserva cuando la crees.");return}await action("save_card",payload)}
  async function authorizeToken(token){await action("authorize",{token,amount:Number(amount),idempotency_key:crypto.randomUUID?.()});await load()}
  async function capture(){const value=Number(captureAmount||0);if(!(value>0))return setMessage("Ingresá el importe a cobrar.");if(!window.confirm(`¿Registrar y cobrar ${money(value,currency)} por “${concept}”?`))return;await action("capture",{amount:value,concept,add_charge:true,idempotency_key:crypto.randomUUID?.()});await load()}
  async function release(){if(!window.confirm("¿Liberar la retención? El importe dejará de quedar reservado en la tarjeta."))return;await action("release",{idempotency_key:crypto.randomUUID?.()});await load()}
  async function removeCard(){if(!window.confirm("¿Quitar esta tarjeta de garantía de la reserva?"))return;await action("remove_card");await load()}
  const connection=snapshot?.connection||{},guarantee=snapshot?.guarantee,publicKey=connection?.public_key
  if(!snapshot&&!message)return <div className={g.loading}>Revisando garantía segura…</div>
  if(snapshot&&!snapshot.platform_ready)return <div className={g.card}><div className={g.top}><div><h5>Garantía con Mercado Pago</h5><p>El módulo seguro ya está instalado en Habitación Llena.</p></div><span className={`${g.pill} ${g.warn}`}>ACTIVACIÓN PENDIENTE</span></div><p className={g.hint}>Faltan las credenciales de la aplicación Mercado Pago de Habitación Llena en el servidor. Hasta activarlas no se mostrará ningún campo que pueda dar una falsa sensación de tokenización.</p>{message&&<div className={g.message}>{message}</div>}</div>
  if(snapshot&&!connection.connected)return <div className={g.card}><div className={g.top}><div><h5>Mercado Pago del hotel</h5><p>Cada propiedad conecta su propia cuenta; las tarjetas y autorizaciones no se mezclan entre hoteles.</p></div><span className={`${g.pill} ${g.warn}`}>NO CONECTADO</span></div>{connection.can_manage?<div className={g.actions}><button type="button" className={g.primary} disabled={busy} onClick={connect}>{busy?"Abriendo Mercado Pago…":"Conectar Mercado Pago"}</button></div>:<p className={g.hint}>Pedile al propietario o a un administrador que conecte Mercado Pago una sola vez para esta propiedad.</p>}{message&&<div className={g.message}>{message}</div>}</div>
  if(!snapshot)return <div className={g.card}>{message&&<div className={g.message}>{message}</div>}</div>
  return <div className={g.shell}><div className={g.card}><div className={g.top}><div><h5>Garantía segura</h5><p>Tokenización y retenciones operadas por la cuenta Mercado Pago de este hotel.</p></div><span className={`${g.pill} ${statusTone(guarantee?.status)}`}>{stagedToken&&!reservationId?"LISTA PARA GUARDAR":statusText(guarantee?.status)}</span></div>
    {stagedToken&&!reservationId?<><div className={g.cardLine}><span><b>Tarjeta tokenizada</b><small>Se vinculará al crear la reserva · el token vive solo en esta pantalla</small></span></div><div className={g.actions}><button type="button" onClick={()=>setModal("new")}>Reemplazar</button><button type="button" className={g.danger} onClick={onClearStaged}>Quitar</button></div></>:guarantee?.card_id?<><div className={g.cardLine}><span><b>{guarantee.card_brand||"Tarjeta"} · •••• {guarantee.last_four||"----"}</b><small>{expiry(guarantee)?`Vence ${expiry(guarantee)} · `:""}Protegida por Mercado Pago</small></span><strong>{guarantee.status==="authorized"?money(guarantee.authorized_amount,guarantee.currency):guarantee.status==="captured"?money(guarantee.captured_amount,guarantee.currency):"✓"}</strong></div>
      {guarantee.status==="authorized"?<><p className={g.hint}>Retención activa hasta {guarantee.authorization_expires_at?new Date(guarantee.authorization_expires_at).toLocaleString("es-AR"):"la ventana informada por Mercado Pago"}. Podés capturar un cargo documentado o liberarla si no hubo inconvenientes.</p><div className={g.actions}><button type="button" className={g.primary} disabled={busy} onClick={release}>Liberar garantía</button></div><div className={g.capture}><h6>Registrar daño / cargo</h6><div className={g.captureGrid}><input type="number" min="0.01" max={guarantee.authorized_amount} step="0.01" value={captureAmount} onChange={e=>setCaptureAmount(e.target.value)} placeholder="Monto"/><input value={concept} onChange={e=>setConcept(e.target.value)} placeholder="Concepto documentado"/><button type="button" className={g.danger} disabled={busy} onClick={capture}>Cobrar</button></div><p className={g.hint}>El cargo se suma a la cuenta de la reserva y el pago de Mercado Pago se registra en simultáneo, dejando trazabilidad.</p></div></>:guarantee.status==="captured"?<p className={g.hint}>Se capturaron {money(guarantee.captured_amount,guarantee.currency)} de la garantía. El movimiento quedó auditado en la reserva.</p>:<><div className={g.amountRow}><input type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Monto de garantía"/><button type="button" className={g.primary} disabled={busy||!reservationId} onClick={()=>setModal("cvv")}>Retener garantía</button></div><p className={g.hint}>{reservationId?"Mercado Pago vuelve a pedir el CVV en un campo seguro para generar una autorización temporal. La retención tiene una ventana aproximada de 7 días.":"Primero creá la reserva para poder realizar una retención."}</p><div className={g.actions}><button type="button" onClick={()=>setModal("new")}>Reemplazar tarjeta</button><button type="button" className={g.danger} disabled={busy} onClick={removeCard}>Quitar tarjeta</button></div></>}</>:<><p className={g.hint}>Registrá una tarjeta sin almacenar PAN ni CVV. Mercado Pago conservará la tarjeta tokenizada y Habitación Llena guardará solo su referencia, marca y últimos cuatro dígitos.</p><div className={g.actions}><button type="button" className={g.primary} disabled={busy} onClick={()=>setModal("new")}>Registrar tarjeta segura</button></div></>}
    {message&&<div className={`${g.message} ${message.startsWith("Tarjeta protegida")?g.success:""}`}>{message}</div>}
  </div>
  {snapshot.events?.length>0&&<div className={g.card}><div className={g.history}><h6>Auditoría de garantía</h6>{snapshot.events.slice(0,6).map(event=><div className={g.event} key={event.id}><span><b>{statusText(event.event_type)}</b><small>{new Date(event.created_at).toLocaleString("es-AR")}</small></span>{event.amount!=null&&<strong>{money(event.amount,event.currency||currency)}</strong>}</div>)}</div></div>}
  {modal==="new"&&<NewCardModal publicKey={publicKey} guest={guest} onClose={()=>setModal(null)} onToken={saveToken}/>} {modal==="cvv"&&guarantee?.card_id&&<CvvModal publicKey={publicKey} cardId={guarantee.card_id} amount={Number(amount)} currency={guarantee.currency||currency} onClose={()=>setModal(null)} onToken={authorizeToken}/>}</div>
}