"use client"

import{useEffect,useMemo,useState}from"react"
import{money}from"../../core/formatters"
import{reservationTotal}from"./reservationModel"
import ui from"../../v2.module.css"

function Field({label,wide=false,children}){return <label className={wide?ui.wide:""}><span>{label}</span>{children}</label>}

export default function ReservationDrawer({initial,original,rooms,partners=[],groups=[],charges=[],payments=[],busy=false,onClose,onSave,onCheckin,onCheckout,onPayment,onPrint,onEmail,onKey,onWebCheckin}){
  const[draft,setDraft]=useState(initial),[tab,setTab]=useState("guest"),[payment,setPayment]=useState({amount:"",method:"Efectivo",currency:"ARS",note:""})
  useEffect(()=>{setDraft(initial);setTab("guest")},[initial?.id,initial?.start,initial?.roomId])
  const room=rooms.find(r=>String(r.id)===String(draft?.roomId)),totals=useMemo(()=>reservationTotal(draft||{},room),[draft,room]),paid=payments.filter(p=>String(p.reserva_id)===String(draft?.id)).reduce((a,p)=>a+Number(p.monto||0),0),balance=Math.max(0,totals.total-paid)
  if(!draft)return null
  const set=(key,value)=>setDraft(x=>({...x,[key]:value}))
  function addCompanion(){set("companions",[...(draft.companions||[]),{nombre:"",dni:"",es_menor:false}])}
  function updateCompanion(i,key,value){set("companions",draft.companions.map((p,j)=>j===i?{...p,[key]:value}:p))}
  function addPet(){set("pets",[...(draft.pets||[]),{name:"Mascota",amount:0}])}
  function addCharge(item){set("extras",[...(draft.extras||[]),{name:item.name,total:Number(item.amount||0),catalog_id:item.id}])}
  return <div className={ui.drawerShade} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className={ui.drawer}><header className={ui.drawerHead}><div><small>{original?.numero_reserva||"NUEVA ESTADÍA"}</small><h2>{draft.guest||"Nueva reserva"}</h2><p>{draft.start} → {draft.end}</p></div><button onClick={onClose}>×</button></header><nav className={ui.drawerTabs}>{[["guest","Huésped"],["stay","Estadía"],["money","Garantía & pagos"],["extras","Extras"],["notes","Notas"]].map(([id,label])=><button key={id} className={tab===id?ui.activeTab:""} onClick={()=>setTab(id)}>{label}</button>)}</nav><form className={ui.drawerForm} onSubmit={e=>{e.preventDefault();onSave(draft)}}>{tab==="guest"&&<section><h3>Ficha del pasajero</h3><div className={ui.fieldGrid}><Field label="Nombre y apellido" wide><input autoFocus value={draft.guest} onChange={e=>set("guest",e.target.value)}/></Field><Field label="Email"><input type="email" value={draft.email} onChange={e=>set("email",e.target.value)}/></Field><Field label="Teléfono"><input value={draft.phone} onChange={e=>set("phone",e.target.value)}/></Field><Field label="DNI / Pasaporte"><input value={draft.document} onChange={e=>set("document",e.target.value)}/></Field><Field label="País"><input value={draft.country} onChange={e=>set("country",e.target.value)}/></Field><Field label="Provincia"><input value={draft.province} onChange={e=>set("province",e.target.value)}/></Field><Field label="Dirección" wide><input value={draft.address} onChange={e=>set("address",e.target.value)}/></Field></div><div className={ui.subhead}><h4>Acompañantes</h4><button type="button" onClick={addCompanion}>＋ Agregar</button></div>{(draft.companions||[]).map((p,i)=><div className={ui.companionRow} key={i}><input placeholder="Nombre" value={p.nombre||""} onChange={e=>updateCompanion(i,"nombre",e.target.value)}/><input placeholder="Documento" value={p.dni||""} onChange={e=>updateCompanion(i,"dni",e.target.value)}/><label><input type="checkbox" checked={!!p.es_menor} onChange={e=>updateCompanion(i,"es_menor",e.target.checked)}/> Menor</label><button type="button" onClick={()=>set("companions",draft.companions.filter((_,j)=>j!==i))}>×</button></div>)}</section>}
{tab==="stay"&&<section><h3>Estadía</h3><div className={ui.fieldGrid}><Field label="Habitación"><select value={draft.roomId} onChange={e=>set("roomId",e.target.value)}><option value="">Elegir</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.nombre} · {r.tipo||"Habitación"}</option>)}</select></Field><Field label="Pax"><input type="number" min="1" value={draft.pax} onChange={e=>set("pax",e.target.value)}/></Field><Field label="Entrada"><input type="date" value={draft.start} onChange={e=>set("start",e.target.value)}/></Field><Field label="Salida"><input type="date" value={draft.end} onChange={e=>set("end",e.target.value)}/></Field><Field label="Hora llegada"><input type="time" value={draft.arrivalTime||""} onChange={e=>set("arrivalTime",e.target.value)}/></Field><Field label="Canal"><input value={draft.channel} onChange={e=>set("channel",e.target.value)}/></Field><Field label="Tarifa/noche"><input type="number" min="0" value={draft.rate} onChange={e=>set("rate",e.target.value)}/></Field><Field label="Empresa / Agencia"><select value={draft.partnerId||""} onChange={e=>set("partnerId",e.target.value)}><option value="">Directo</option>{partners.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Grupo"><select value={draft.groupId||""} onChange={e=>set("groupId",e.target.value)}><option value="">Sin grupo</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Field><Field label="Vehículos"><input type="number" min="0" value={draft.vehicles||0} onChange={e=>set("vehicles",e.target.value)}/></Field><Field label="Tipo vehículo"><input value={draft.vehicleType||""} onChange={e=>set("vehicleType",e.target.value)}/></Field><Field label="Dominio"><input value={draft.vehiclePlate||""} onChange={e=>set("vehiclePlate",e.target.value.toUpperCase())}/></Field><Field label="Cochera"><input type="number" min="0" value={draft.parking||0} onChange={e=>set("parking",e.target.value)}/></Field></div></section>}
{tab==="money"&&<section><h3>Garantía y pagos</h3><div className={ui.fieldGrid}><Field label="Garantía"><select value={draft.guaranteeType||"Sin garantía"} onChange={e=>set("guaranteeType",e.target.value)}><option>Sin garantía</option><option>Tarjeta</option><option>Transferencia</option><option>Seña</option><option>Voucher</option></select></Field><Field label="Marca"><input value={draft.guaranteeBrand||""} onChange={e=>set("guaranteeBrand",e.target.value)}/></Field><Field label="Últimos 4"><input maxLength="4" value={draft.guaranteeLast4||""} onChange={e=>set("guaranteeLast4",e.target.value.replace(/\D/g,""))}/></Field><Field label="Vencimiento"><input value={draft.guaranteeExpiry||""} onChange={e=>set("guaranteeExpiry",e.target.value)} placeholder="MM/AA"/></Field><Field label="Medio preferido"><input value={draft.preferredPayment||"Efectivo"} onChange={e=>set("preferredPayment",e.target.value)}/></Field></div>{draft.id&&<div className={ui.paymentBox}><div><span>Total</span><b>{money(totals.total,draft.currency)}</b></div><div><span>Pagado</span><b>{money(paid,draft.currency)}</b></div><div><span>Saldo</span><b>{money(balance,draft.currency)}</b></div><div className={ui.paymentFields}><input type="number" min="0.01" step="0.01" placeholder="Monto" value={payment.amount} onChange={e=>setPayment(x=>({...x,amount:e.target.value}))}/><select value={payment.method} onChange={e=>setPayment(x=>({...x,method:e.target.value}))}><option>Efectivo</option><option>Transferencia</option><option>Débito</option><option>Crédito</option><option>Mercado Pago</option><option>USD efectivo</option></select><button type="button" onClick={async()=>{if(Number(payment.amount)>0){await onPayment(payment);setPayment(x=>({...x,amount:""}))}}}>Registrar pago</button></div></div>}</section>}
{tab==="extras"&&<section><div className={ui.subhead}><h3>Mascotas y extras</h3><button type="button" onClick={addPet}>＋ Mascota</button></div>{(draft.pets||[]).map((pet,i)=><div className={ui.extraRow} key={`pet-${i}`}><input value={pet.name||""} onChange={e=>set("pets",draft.pets.map((p,j)=>j===i?{...p,name:e.target.value}:p))}/><input type="number" min="0" value={pet.amount||0} onChange={e=>set("pets",draft.pets.map((p,j)=>j===i?{...p,amount:Number(e.target.value||0)}:p))}/><button type="button" onClick={()=>set("pets",draft.pets.filter((_,j)=>j!==i))}>×</button></div>)}<div className={ui.chargeChips}>{charges.filter(c=>c.active!==false).map(c=><button type="button" key={c.id} onClick={()=>addCharge(c)}>＋ {c.name} · {money(c.amount)}</button>)}</div>{(draft.extras||[]).map((extra,i)=><div className={ui.extraRow} key={`extra-${i}`}><input value={extra.name||""} onChange={e=>set("extras",draft.extras.map((p,j)=>j===i?{...p,name:e.target.value}:p))}/><input type="number" min="0" value={extra.total||0} onChange={e=>set("extras",draft.extras.map((p,j)=>j===i?{...p,total:Number(e.target.value||0)}:p))}/><button type="button" onClick={()=>set("extras",draft.extras.filter((_,j)=>j!==i))}>×</button></div>)}</section>}
{tab==="notes"&&<section><h3>Observaciones</h3><Field label="Notas internas" wide><textarea className={ui.bigTextarea} value={draft.notes||""} onChange={e=>set("notes",e.target.value)}/></Field></section>}{draft.id&&<div className={ui.chargeChips}><button type="button" onClick={onWebCheckin}>Web Check-in</button><button type="button" onClick={onPrint}>Imprimir</button><button type="button" disabled={!draft.email} onClick={onEmail}>Email</button><button type="button" onClick={onKey}>Llave / tarjeta</button></div>}<aside className={ui.drawerSummary}><span>{totals.nights} noches</span><b>{money(totals.total,draft.currency)}</b>{draft.id&&<small>Saldo {money(balance,draft.currency)}</small>}</aside><footer className={ui.drawerFooter}>{draft.id&&<div><button type="button" disabled={original?.estado==="alojado"||original?.estado==="finalizada"} onClick={onCheckin}>Check-in</button><button type="button" disabled={original?.estado==="finalizada"||balance>.01} onClick={onCheckout}>Check-out</button></div>}<div><button type="button" onClick={onClose}>Cancelar</button><button disabled={busy}>{busy?"Guardando…":draft.id?"Guardar cambios":"Crear reserva"}</button></div></footer></form></aside></div>
}
