import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import forge from "npm:node-forge@1.3.1";
import QRCode from "npm:qrcode@1.5.4";

type FiscalConfig={
  property_id:string;enabled:boolean;environment:'homologacion'|'produccion';tax_id:string;point_of_sale:number;
  default_receipt_type:number;credential_slot:string;issuer_iva_condition:'monotributo'|'responsable_inscripto'|'exento';
  legal_name:string|null;trade_name:string|null;fiscal_address:string|null;gross_income_number:string|null;
  gross_income_condition:'registered'|'non_contributor';activity_start_date:string|null;invoice_a_variant:'standard'|'cbu'|'retention'
};
type VatLine={id:number;base:number;amount:number};
type Tribute={id:number;description:string;base:number;rate:number;amount:number};

const SERVICE='wsfe',SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;

function cors(req:Request){const o=req.headers.get('origin')||'';const ok=o==='https://habitacionllena.com'||o==='https://www.habitacionllena.com'||/^https:\/\/[-a-z0-9]+\.vercel\.app$/i.test(o);return{'Access-Control-Allow-Origin':ok?o:'https://habitacionllena.com','Vary':'Origin','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}}
function json(req:Request,data:unknown,status=200){return Response.json(data,{status,headers:cors(req)})}
function esc(s:unknown){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function dec(s:string){return String(s).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&amp;/g,'&')}
function jwtPayload(req:Request){try{const t=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');const p=t.split('.')[1];if(!p)return null;return JSON.parse(atob(p.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(p.length/4)*4,'=')))}catch{return null}}
function endpoints(env:string){return env==='produccion'?{wsaa:'https://wsaa.afip.gov.ar/ws/services/LoginCms',wsfe:'https://servicios1.afip.gov.ar/wsfev1/service.asmx'}:{wsaa:'https://wsaahomo.afip.gov.ar/ws/services/LoginCms',wsfe:'https://wswhomo.afip.gov.ar/wsfev1/service.asmx'}}
function pemToCmsBase64(certPem:string,keyPem:string,tra:string){const cert=forge.pki.certificateFromPem(certPem),key=forge.pki.privateKeyFromPem(keyPem),p7=forge.pkcs7.createSignedData();p7.content=forge.util.createBuffer(tra,'utf8');p7.addCertificate(cert);p7.addSigner({key,certificate:cert,digestAlgorithm:forge.pki.oids.sha256});p7.sign();return forge.util.encode64(forge.asn1.toDer(p7.toAsn1()).getBytes())}
function arcaDate(value=new Date()){const ps=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(value),m=Object.fromEntries(ps.map(x=>[x.type,x.value]));return`${m.year}${m.month}${m.day}`}
function isoArcaDate(value:unknown){const v=String(value||'').replace(/\D/g,'');return /^\d{8}$/.test(v)?`${v.slice(0,4)}-${v.slice(4,6)}-${v.slice(6,8)}`:null}
function compactDate(value:unknown){const v=String(value||'').slice(0,10).replace(/-/g,'');return /^\d{8}$/.test(v)?v:''}
function parseErrors(t:string){return[...t.matchAll(/<Err>[\s\S]*?<Code>(.*?)<\/Code>[\s\S]*?<Msg>(.*?)<\/Msg>[\s\S]*?<\/Err>/g)].map(m=>({code:m[1],msg:dec(m[2])}))}
function parseObs(t:string){return[...t.matchAll(/<Obs>[\s\S]*?<Code>(.*?)<\/Code>[\s\S]*?<Msg>(.*?)<\/Msg>[\s\S]*?<\/Obs>/g)].map(m=>({code:m[1],msg:dec(m[2])}))}
function headers(extra:Record<string,string>={}){return{apikey:SERVICE_ROLE,Authorization:`Bearer ${SERVICE_ROLE}`,'Content-Type':'application/json',...extra}}
async function admin(path:string,init:RequestInit={}){return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:headers(init.headers as Record<string,string>||{})})}
async function membership(uid:string,propertyId:string){const r=await admin(`property_members?user_id=eq.${encodeURIComponent(uid)}&property_id=eq.${encodeURIComponent(propertyId)}&select=role&limit=1`),a=await r.json();return a?.[0]?.role||null}
async function config(propertyId:string):Promise<FiscalConfig|null>{const fields='property_id,enabled,environment,tax_id,point_of_sale,default_receipt_type,credential_slot,issuer_iva_condition,legal_name,trade_name,fiscal_address,gross_income_number,gross_income_condition,activity_start_date,invoice_a_variant';const r=await admin(`hotel_arca_settings?property_id=eq.${encodeURIComponent(propertyId)}&select=${fields}&limit=1`),a=await r.json();return a?.[0]||null}
async function reservation(propertyId:string,id:unknown){if(!id)return null;const r=await admin(`reservas?property_id=eq.${encodeURIComponent(propertyId)}&id=eq.${encodeURIComponent(String(id))}&select=id,fecha_entrada,fecha_salida,nombre_huesped,dni_huesped,precio_total,moneda&limit=1`),a=await r.json();return a?.[0]||null}
async function financeDocument(propertyId:string,id:unknown){if(!id)return null;const r=await admin(`hotel_finance_documents?property_id=eq.${encodeURIComponent(propertyId)}&id=eq.${encodeURIComponent(String(id))}&select=id,billing_to,number,status,currency,total&limit=1`),a=await r.json();return a?.[0]||null}
async function getCachedTicket(propertyId:string){const r=await admin(`hotel_arca_wsaa_cache?property_id=eq.${encodeURIComponent(propertyId)}&service=eq.${SERVICE}&select=token,sign,expires_at&limit=1`),a=await r.json(),row=a?.[0];if(!row)return null;if(new Date(row.expires_at).getTime()-Date.now()<300000)return null;return row}
async function saveTicket(propertyId:string,t:{token:string;sign:string;expiration:string}){await admin('hotel_arca_wsaa_cache?on_conflict=property_id,service',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({property_id:propertyId,service:SERVICE,token:t.token,sign:t.sign,expires_at:t.expiration,updated_at:new Date().toISOString()})})}
async function rpc(name:string,body:any){const r=await admin(`rpc/${name}`,{method:'POST',body:JSON.stringify(body)}),v=await r.json().catch(()=>null);if(!r.ok)throw new Error(v?.message||`No se pudo ejecutar ${name}`);return v}
async function readVault(secretId:string){const v=await rpc('hl_arca_vault_read_secret',{p_secret_id:secretId});if(typeof v!=='string')throw new Error('No se pudo leer la credencial cifrada de ARCA.');return v.trim()}
async function credentials(cfg:FiscalConfig){const r=await admin(`hotel_arca_credentials?property_id=eq.${encodeURIComponent(cfg.property_id)}&select=private_key_secret_id,certificate_secret_id&limit=1`),a=await r.json(),row=a?.[0];if(!row?.private_key_secret_id||!row?.certificate_secret_id)throw new Error('Falta el certificado ARCA de esta propiedad.');return{cert:await readVault(row.certificate_secret_id),key:await readVault(row.private_key_secret_id)}}
async function wsaa(cfg:FiscalConfig,cert:string,key:string){const now=new Date(),tra=`<?xml version="1.0" encoding="UTF-8"?><loginTicketRequest version="1.0"><header><uniqueId>${Math.floor(now.getTime()/1000)}</uniqueId><generationTime>${new Date(now.getTime()-600000).toISOString()}</generationTime><expirationTime>${new Date(now.getTime()+10*60*60*1000).toISOString()}</expirationTime></header><service>${SERVICE}</service></loginTicketRequest>`,cms=pemToCmsBase64(cert,key,tra),soap=`<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:log="http://wsaa.view.sua.dvadac.desein.afip.gov"><soapenv:Header/><soapenv:Body><log:loginCms><log:in0>${esc(cms)}</log:in0></log:loginCms></soapenv:Body></soapenv:Envelope>`,r=await fetch(endpoints(cfg.environment).wsaa,{method:'POST',headers:{'Content-Type':'text/xml; charset=utf-8','SOAPAction':''},body:soap}),text=await r.text();if(!r.ok||/faultcode|faultstring/i.test(text))throw new Error(`WSAA: ${dec(text.match(/<faultstring>([\s\S]*?)<\/faultstring>/i)?.[1]||text.slice(0,800))}`);const d=dec(text.match(/<loginCmsReturn>([\s\S]*?)<\/loginCmsReturn>/)?.[1]||''),token=d.match(/<token>([\s\S]*?)<\/token>/)?.[1],sign=d.match(/<sign>([\s\S]*?)<\/sign>/)?.[1],expiration=d.match(/<expirationTime>([\s\S]*?)<\/expirationTime>/)?.[1];if(!token||!sign||!expiration)throw new Error('WSAA no devolvió Token/Sign');return{token,sign,expiration}}
async function wsfe(cfg:FiscalConfig,action:string,inner:string){const soap=`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body>${inner}</soap:Body></soap:Envelope>`,r=await fetch(endpoints(cfg.environment).wsfe,{method:'POST',headers:{'Content-Type':'text/xml; charset=utf-8','SOAPAction':`http://ar.gov.afip.dif.FEV1/${action}`},body:soap}),text=await r.text();if(!r.ok||/faultcode|faultstring/i.test(text))throw new Error(`WSFE ${action}: ${dec(text.match(/<faultstring>([\s\S]*?)<\/faultstring>/i)?.[1]||text.slice(0,1000))}`);return text}
function auth(cfg:FiscalConfig,token:string,sign:string){return`<Auth><Token>${esc(token)}</Token><Sign>${esc(sign)}</Sign><Cuit>${esc(cfg.tax_id)}</Cuit></Auth>`}
async function lastAuthorized(cfg:FiscalConfig,token:string,sign:string,receiptType:number){const t=await wsfe(cfg,'FECompUltimoAutorizado',`<FECompUltimoAutorizado xmlns="http://ar.gov.afip.dif.FEV1/">${auth(cfg,token,sign)}<PtoVta>${cfg.point_of_sale}</PtoVta><CbteTipo>${receiptType}</CbteTipo></FECompUltimoAutorizado>`),n=t.match(/<CbteNro>(.*?)<\/CbteNro>/)?.[1],errors=parseErrors(t);if(n===undefined||errors.length)throw new Error(errors.map(e=>`${e.code}: ${e.msg}`).join(' | ')||'No se pudo obtener el último comprobante');return Number(n)}
function norm(v:unknown){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
function receiptClassFor(cfg:FiscalConfig,recipientCondition:string){if(cfg.issuer_iva_condition!=='responsable_inscripto')return'C';const recipient=String(recipientCondition||'consumidor_final').toLowerCase();return['responsable_inscripto','monotributo'].includes(recipient)?'A':'B'}
function standardReceiptType(documentType:string,cls:string){const map:any={invoice:{A:1,B:6,C:11},debit_note:{A:2,B:7,C:12},credit_note:{A:3,B:8,C:13}};return Number(map[documentType]?.[cls]||0)}
async function receiptTypes(cfg:FiscalConfig,token:string,sign:string){const t=await wsfe(cfg,'FEParamGetTiposCbte',`<FEParamGetTiposCbte xmlns="http://ar.gov.afip.dif.FEV1/">${auth(cfg,token,sign)}</FEParamGetTiposCbte>`),errors=parseErrors(t);if(errors.length)throw new Error(errors.map(e=>`${e.code}: ${e.msg}`).join(' | '));return[...t.matchAll(/<CbteTipo>[\s\S]*?<Id>(.*?)<\/Id>[\s\S]*?<Desc>(.*?)<\/Desc>[\s\S]*?<\/CbteTipo>/g)].map(m=>({id:Number(m[1]),desc:dec(m[2])}))}
async function resolveReceiptType(cfg:FiscalConfig,token:string,sign:string,documentType:string,cls:string,variant:string){const standard=standardReceiptType(documentType,cls);if(!standard)throw new Error('Tipo de documento fiscal no soportado.');if(cls!=='A'||variant==='standard')return standard;const rows=await receiptTypes(cfg,token,sign),docNeedle=documentType==='invoice'?'FACTURA':documentType==='debit_note'?'NOTA DE DEBITO':'NOTA DE CREDITO',variantNeedle=variant==='cbu'?'CBU':'RETENCION';const found=rows.find(row=>{const d=norm(row.desc);return d.includes(docNeedle)&&/(^|\s|-)A(\s|-|$)/.test(d)&&d.includes(variantNeedle)});if(!found)throw new Error(`ARCA no devolvió un tipo de comprobante para ${docNeedle} A · ${variant==='cbu'?'Pago en CBU informada':'Operación sujeta a retención'}. Revisá la autorización fiscal del emisor.`);return found.id}
async function recipientCondition(cfg:FiscalConfig,token:string,sign:string,cls:string,wanted:string,id?:number){if(Number.isInteger(id)&&Number(id)>0)return Number(id);const t=await wsfe(cfg,'FEParamGetCondicionIvaReceptor',`<FEParamGetCondicionIvaReceptor xmlns="http://ar.gov.afip.dif.FEV1/">${auth(cfg,token,sign)}<ClaseCmp>${cls}</ClaseCmp></FEParamGetCondicionIvaReceptor>`),vals=[...t.matchAll(/<CondicionIvaReceptor>[\s\S]*?<Id>(.*?)<\/Id>[\s\S]*?<Desc>(.*?)<\/Desc>[\s\S]*?<Cmp_Clase>(.*?)<\/Cmp_Clase>[\s\S]*?<\/CondicionIvaReceptor>/g)].map(m=>({id:Number(m[1]),desc:dec(m[2])})),needle=String(wanted||'consumidor_final').toLowerCase(),patterns:Record<string,RegExp>={consumidor_final:/consumidor\s+final/i,responsable_inscripto:/responsable\s+inscripto/i,monotributo:/monotribut/i,exento:/exento/i,no_categorizado:/no\s+categorizado/i,no_alcanzado:/no\s+alcanzad/i,cliente_exterior:/cliente\s+(del\s+)?exterior/i};const found=vals.find(v=>(patterns[needle]||/consumidor\s+final/i).test(v.desc));if(!found)throw new Error(`ARCA no devolvió la condición IVA receptora solicitada (${wanted||'Consumidor Final'}) para clase ${cls}`);return found.id}
function money2(value:unknown){const n=Number(value||0);if(!Number.isFinite(n)||n<0)throw new Error('Importe fiscal inválido');return Math.round(n*100)/100}
function vatXml(lines:VatLine[]){if(!lines.length)return'';return`<Iva>${lines.map(x=>`<AlicIva><Id>${Number(x.id)}</Id><BaseImp>${money2(x.base).toFixed(2)}</BaseImp><Importe>${money2(x.amount).toFixed(2)}</Importe></AlicIva>`).join('')}</Iva>`}
function tribXml(lines:Tribute[]){if(!lines.length)return'';return`<Tributos>${lines.map(x=>`<Tributo><Id>${Number(x.id)}</Id><Desc>${esc(x.description||'Tributo')}</Desc><BaseImp>${money2(x.base).toFixed(2)}</BaseImp><Alic>${money2(x.rate).toFixed(2)}</Alic><Importe>${money2(x.amount).toFixed(2)}</Importe></Tributo>`).join('')}</Tributos>`}
function associatedXml(row:any){if(!row)return'';const type=Number(row.receipt_type),point=Number(row.point_of_sale),number=Number(row.receipt_number);if(!type||!point||!number)throw new Error('La Nota de Crédito/Débito necesita el comprobante original autorizado por ARCA.');return`<CbtesAsoc><CbteAsoc><Tipo>${type}</Tipo><PtoVta>${point}</PtoVta><Nro>${number}</Nro></CbteAsoc></CbtesAsoc>`}
async function issue(cfg:FiscalConfig,token:string,sign:string,input:any,cbte:number,condIva:number){const total=money2(input.amount),net=money2(input.net_amount),vat=money2(input.vat_amount),exempt=money2(input.exempt_amount),untaxed=money2(input.untaxed_amount),trib=money2(input.tribute_amount),receiptType=Number(input.receipt_type),serviceFrom=compactDate(input.service_from),serviceTo=compactDate(input.service_to),due=compactDate(input.payment_due||input.service_to),concept=serviceFrom&&serviceTo?2:1,currency=input.currency==='USD'?'DOL':'PES',exchange=currency==='DOL'?Number(input.exchange_rate||0):1;if(currency==='DOL'&&(!Number.isFinite(exchange)||exchange<=0))throw new Error('Para facturar en USD falta la cotización ARS/USD.');if(Math.abs((net+vat+exempt+untaxed+trib)-total)>.03)throw new Error('Los importes neto, IVA, exento, no gravado y tributos no coinciden con el total.');const serviceXml=concept===2?`<FchServDesde>${serviceFrom}</FchServDesde><FchServHasta>${serviceTo}</FchServHasta><FchVtoPago>${due||serviceTo}</FchVtoPago>`:'',t=await wsfe(cfg,'FECAESolicitar',`<FECAESolicitar xmlns="http://ar.gov.afip.dif.FEV1/">${auth(cfg,token,sign)}<FeCAEReq><FeCabReq><CantReg>1</CantReg><PtoVta>${cfg.point_of_sale}</PtoVta><CbteTipo>${receiptType}</CbteTipo></FeCabReq><FeDetReq><FECAEDetRequest><Concepto>${concept}</Concepto><DocTipo>${Number(input.recipient_doc_type||99)}</DocTipo><DocNro>${esc(String(input.recipient_doc_number||'0').replace(/\D/g,''))}</DocNro><CbteDesde>${cbte}</CbteDesde><CbteHasta>${cbte}</CbteHasta><CbteFch>${arcaDate()}</CbteFch><ImpTotal>${total.toFixed(2)}</ImpTotal><ImpTotConc>${untaxed.toFixed(2)}</ImpTotConc><ImpNeto>${net.toFixed(2)}</ImpNeto><ImpOpEx>${exempt.toFixed(2)}</ImpOpEx><ImpTrib>${trib.toFixed(2)}</ImpTrib><ImpIVA>${vat.toFixed(2)}</ImpIVA>${serviceXml}<MonId>${currency}</MonId><MonCotiz>${exchange.toFixed(6)}</MonCotiz><CondicionIVAReceptorId>${condIva}</CondicionIVAReceptorId>${associatedXml(input.associated_receipt)}${tribXml(input.tributes||[])}${vatXml(input.vat_breakdown||[])}</FECAEDetRequest></FeDetReq></FeCAEReq></FECAESolicitar>`),result=t.match(/<Resultado>(.*?)<\/Resultado>/)?.[1]||null,cae=t.match(/<CAE>(.*?)<\/CAE>/)?.[1]||null,exp=t.match(/<CAEFchVto>(.*?)<\/CAEFchVto>/)?.[1]||null;return{approved:result==='A'&&!!cae,result,cae,cae_expiration:exp,receipt_number:cbte,date:arcaDate(),amount:total,receipt_type:receiptType,point_of_sale:cfg.point_of_sale,currency:input.currency==='USD'?'USD':'ARS',exchange_rate:exchange,errors:parseErrors(t),observations:parseObs(t)}}
async function existing(propertyId:string,requestId:string){const r=await admin(`hotel_arca_invoice_requests?property_id=eq.${encodeURIComponent(propertyId)}&request_id=eq.${encodeURIComponent(requestId)}&select=*&limit=1`),a=await r.json();return a?.[0]||null}
async function insertPending(propertyId:string,userId:string,input:any){const r=await admin('hotel_arca_invoice_requests',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({property_id:propertyId,request_id:input.request_id,reservation_id:input.reservation_id||null,finance_document_id:input.finance_document_id||null,receipt_type:input.receipt_type,point_of_sale:input.point_of_sale,currency:input.currency,amount:input.amount,net_amount:input.net_amount,vat_amount:input.vat_amount,exempt_amount:input.exempt_amount,recipient_doc_type:input.recipient_doc_type,recipient_doc_number:input.recipient_doc_number,recipient_iva_condition_id:input.recipient_iva_condition_id||null,status:'pending',request_payload:input,created_by:userId})}),a=await r.json().catch(()=>[]);if(!r.ok){const e=await existing(propertyId,input.request_id);if(e)return e;throw new Error(a?.message||'No se pudo registrar la solicitud fiscal')}return a?.[0]}
async function updateReq(id:string,patch:any){await admin(`hotel_arca_invoice_requests?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({...patch,updated_at:new Date().toISOString()})})}
async function qrFor(cfg:FiscalConfig,input:any,invoice:any){const payload={ver:1,fecha:isoArcaDate(invoice.date),cuit:Number(cfg.tax_id),ptoVta:Number(invoice.point_of_sale),tipoCmp:Number(invoice.receipt_type),nroCmp:Number(invoice.receipt_number),importe:money2(invoice.amount),moneda:invoice.currency==='USD'?'DOL':'PES',ctz:Number(invoice.exchange_rate||1),tipoDocRec:Number(input.recipient_doc_type||99),nroDocRec:Number(String(input.recipient_doc_number||'0').replace(/\D/g,''))||0,tipoCodAut:'E',codAut:Number(invoice.cae)};const encoded=btoa(JSON.stringify(payload)),url=`https://www.arca.gob.ar/fe/qr/?p=${encodeURIComponent(encoded)}`,svg=await QRCode.toString(url,{type:'svg',margin:1,width:176,errorCorrectionLevel:'M'});return{url,svg,payload}}
async function linkFinanceDocument(propertyId:string,id:string|undefined,invoice:any,cfg:FiscalConfig,input:any){if(!id)return;const current=await financeDocument(propertyId,id);if(!current)return;const qr=await qrFor(cfg,input,invoice),expiry=isoArcaDate(invoice.cae_expiration),number=`${String(invoice.point_of_sale).padStart(5,'0')}-${String(invoice.receipt_number).padStart(8,'0')}`,billing={...(current.billing_to||{}),issuer_legal_name:cfg.legal_name,issuer_trade_name:cfg.trade_name,issuer_fiscal_address:cfg.fiscal_address,issuer_tax_id:cfg.tax_id,issuer_gross_income_number:cfg.gross_income_condition==='registered'?cfg.gross_income_number:null,issuer_gross_income_condition:cfg.gross_income_condition,issuer_activity_start_date:cfg.activity_start_date,invoice_a_variant:input.invoice_a_variant||cfg.invoice_a_variant||'standard',point_of_sale:Number(invoice.point_of_sale),receipt_type:Number(invoice.receipt_type),receipt_number:Number(invoice.receipt_number),cae:invoice.cae,cae_expiration:expiry,arca_issue_date:isoArcaDate(invoice.date),qr_url:qr.url,qr_svg:qr.svg,exchange_rate:Number(invoice.exchange_rate||1),arca_observations:invoice.observations||[]};const external=`ARCA ${invoice.receipt_type}-${number} · CAE ${invoice.cae}`,patch={status:'issued',number,issued_at:new Date().toISOString(),external_ref:external,billing_to:billing,updated_at:new Date().toISOString()};const response=await admin(`hotel_finance_documents?property_id=eq.${encodeURIComponent(propertyId)}&id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(patch)});if(!response.ok){const detail=await response.json().catch(()=>null);throw new Error(detail?.message||'ARCA autorizó el comprobante, pero no se pudo guardar su representación fiscal.')}}

Deno.serve(async(req:Request)=>{
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});
  if(req.method!=='POST')return json(req,{ok:false,error:'Método no permitido'},405);
  const p=jwtPayload(req);if(!p?.sub||p.role!=='authenticated')return json(req,{ok:false,configured:false,error:'Se requiere sesión autenticada'},401);
  let body:any={};try{body=await req.json()}catch{}
  const propertyId=String(body.property_id||'').trim(),requestId=String(body.request_id||'').trim();
  if(!/^[0-9a-f-]{36}$/i.test(propertyId))return json(req,{ok:false,error:'Propiedad inválida'},400);
  if(!requestId||requestId.length>120)return json(req,{ok:false,error:'request_id inválido'},400);
  const role=await membership(p.sub,propertyId);if(!role||!['owner','manager','admin','reception','night_auditor'].includes(role))return json(req,{ok:false,error:'No tenés permiso para facturar en esta propiedad'},403);
  let row:any=null;
  try{
    const cfg=await config(propertyId);
    if(!cfg?.enabled)return json(req,{ok:false,configured:false,error:'ARCA no está configurado para esta propiedad.'},412);
    if(!cfg.legal_name||!cfg.fiscal_address||!cfg.activity_start_date||(cfg.gross_income_condition==='registered'&&!cfg.gross_income_number))return json(req,{ok:false,configured:true,error:'La configuración fiscal del emisor está incompleta: razón social, domicilio, Ingresos Brutos/información de no contribuyente e inicio de actividades son obligatorios para emitir.'},412);
    const documentType=['invoice','credit_note','debit_note'].includes(String(body.document_type))?String(body.document_type):'invoice';
    const requestedClass=String(body.receipt_class||'').toUpperCase();
    if(['T','E'].includes(requestedClass))return json(req,{ok:false,configured:true,error:requestedClass==='T'?'Factura T requiere el servicio ARCA WSCT; este flujo WSFEv1 no la sustituye por una B.':'Factura E requiere ARCA WSFEXv1.'},422);
    const recipientIvaCondition=String(body.recipient_iva_condition||'consumidor_final'),receiptClass=receiptClassFor(cfg,recipientIvaCondition);
    if(requestedClass&&['A','B','C'].includes(requestedClass)&&requestedClass!==receiptClass)return json(req,{ok:false,configured:true,error:`La clase solicitada (${requestedClass}) no coincide con la determinada por emisor/receptor (${receiptClass}).`},422);
    const variant=receiptClass==='A'&&['standard','cbu','retention'].includes(String(body.invoice_a_variant))?String(body.invoice_a_variant):receiptClass==='A'?(cfg.invoice_a_variant||'standard'):'standard';
    const res=await reservation(propertyId,body.reservation_id),amount=money2(body.amount??res?.precio_total),currency=body.currency==='USD'?'USD':'ARS',serviceFrom=body.service_from||res?.fecha_entrada||null,serviceTo=body.service_to||res?.fecha_salida||null;
    let net=money2(body.net_amount??(receiptClass==='C'?amount:0)),vat=money2(body.vat_amount??0),exempt=money2(body.exempt_amount??0),untaxed=money2(body.untaxed_amount??0),tributes=Array.isArray(body.tributes)?body.tributes:[],tributeAmount=money2(body.tribute_amount??tributes.reduce((s:number,x:any)=>s+Number(x.amount||0),0)),vatBreakdown=Array.isArray(body.vat_breakdown)?body.vat_breakdown:[];
    if(receiptClass!=='C'&&vat>0&&!vatBreakdown.length)return json(req,{ok:false,error:'Para Factura/Nota A o B con IVA necesitás el desglose de alícuotas.'},400);
    if(receiptClass==='C'&&vat>0)return json(req,{ok:false,error:'Los comprobantes C no discriminan IVA en esta integración.'},400);
    if(receiptClass==='C'&&net===0)net=Math.max(0,amount-tributeAmount-exempt-untaxed);
    const recipientDocType=Number(body.recipient_doc_type||99),recipientDocNumber=String(body.recipient_doc_number||'0').replace(/\D/g,'')||'0';
    const prev=await existing(propertyId,requestId);
    if(prev?.status==='authorized'){
      const priorInput=prev.request_payload||body;await linkFinanceDocument(propertyId,body.finance_document_id||priorInput.finance_document_id,prev.response,cfg,priorInput).catch(()=>{});
      return json(req,{ok:true,configured:true,idempotent:true,invoice:prev.response});
    }
    let ticket=await getCachedTicket(propertyId);if(!ticket){const cr=await credentials(cfg);ticket=await wsaa(cfg,cr.cert,cr.key);await saveTicket(propertyId,ticket)}
    const receiptType=await resolveReceiptType(cfg,ticket.token,ticket.sign,documentType,receiptClass,variant);
    const cond=await recipientCondition(cfg,ticket.token,ticket.sign,receiptClass,recipientIvaCondition,body.recipient_iva_condition_id?Number(body.recipient_iva_condition_id):undefined);
    const input={request_id:requestId,property_id:propertyId,reservation_id:res?.id||body.reservation_id||null,finance_document_id:body.finance_document_id||null,document_type:documentType,receipt_class:receiptClass,receipt_type:receiptType,invoice_a_variant:variant,point_of_sale:cfg.point_of_sale,currency,exchange_rate:Number(body.exchange_rate||1),amount,net_amount:net,vat_amount:vat,exempt_amount:exempt,untaxed_amount:untaxed,tribute_amount:tributeAmount,tributes,vat_breakdown:vatBreakdown,recipient_doc_type:recipientDocType,recipient_doc_number:recipientDocNumber,recipient_iva_condition:recipientIvaCondition,recipient_iva_condition_id:cond,service_from:serviceFrom,service_to:serviceTo,payment_due:body.payment_due||serviceTo,associated_receipt:body.associated_receipt||null};
    if(documentType!=='invoice'&&!input.associated_receipt)return json(req,{ok:false,configured:true,error:'La Nota de Crédito/Débito debe estar asociada a un comprobante ARCA autorizado.'},400);
    if(prev?.status==='pending'&&Date.now()-new Date(prev.updated_at||prev.created_at).getTime()<120000)return json(req,{ok:false,configured:true,pending:true,error:'La solicitud ya está en proceso'},409);
    row=prev||await insertPending(propertyId,p.sub,input);if(prev)await updateReq(prev.id,{status:'pending',error:null,receipt_type:receiptType,recipient_iva_condition_id:cond,request_payload:input});
    let invoice:any=null;
    for(let attempt=0;attempt<2;attempt++){const last=await lastAuthorized(cfg,ticket.token,ticket.sign,receiptType);invoice=await issue(cfg,ticket.token,ticket.sign,input,last+1,cond);if(invoice.approved)break;const msg=(invoice.errors||[]).map((e:any)=>`${e.code}: ${e.msg}`).join(' | ');if(!/correlativ|n[uú]mero.*comprobante|ultimo.*autorizado/i.test(msg))break}
    if(!invoice?.approved){await updateReq(row.id,{status:'rejected',response:invoice,error:(invoice?.errors||[]).map((e:any)=>`${e.code}: ${e.msg}`).join(' | ')||'ARCA rechazó el comprobante'});return json(req,{ok:false,configured:true,invoice},422)}
    const expiry=isoArcaDate(invoice.cae_expiration);
    await updateReq(row.id,{status:'authorized',receipt_number:invoice.receipt_number,cae:invoice.cae,cae_expiration:expiry,recipient_iva_condition_id:cond,response:invoice,error:null});
    await linkFinanceDocument(propertyId,input.finance_document_id,invoice,cfg,input);
    return json(req,{ok:true,configured:true,invoice:{...invoice,cae_expiration:expiry}});
  }catch(e){const msg=e instanceof Error?e.message:String(e);try{if(row?.id)await updateReq(row.id,{status:'error',error:msg})}catch{}return json(req,{ok:false,configured:true,error:msg},500)}
});
