"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import s from"./guestPortalSettings.module.css"

const LANGS=[{id:"es",label:"Español",flag:"🇦🇷"},{id:"en",label:"English",flag:"🇬🇧"},{id:"pt",label:"Português",flag:"🇧🇷"}]
const ACTIONS=[
  {id:"towels",label:"Pedir toallas",icon:"🧺"},{id:"pillows",label:"Pedir almohadas",icon:"🛏️"},{id:"cleaning",label:"Solicitar limpieza",icon:"✨"},
  {id:"maintenance",label:"Reportar un problema",icon:"🛠️"},{id:"late_checkout",label:"Late check-out",icon:"🕒"},{id:"other",label:"Otro pedido",icon:"💬"},
]
const DEFAULT_ACTIONS=Object.fromEntries(ACTIONS.map(item=>[item.id,true]))
const DEFAULT_FORM={enabled:true,title:"",portal_title:"",subtitle:"",welcome_message:"",accent_color:"#5B5CEB",logo_url:"",cover_image_url:"",wifi_name:"",wifi_password:"",contact_phone:"",contact_whatsapp:"",checkin_time:"14:00",checkout_time:"10:00",show_account:true,show_wifi:true,show_guide:true,show_nearby:true,show_requests:true,show_contact:true,enabled_actions:DEFAULT_ACTIONS,languages:["es","en","pt"],default_language:"es",sections:[],house_rules:[],nearby_places:[],translations:{}}

const clean=value=>String(value??"").trim()
function normalized(row){
  if(!row)return DEFAULT_FORM
  return{...DEFAULT_FORM,...row,enabled_actions:{...DEFAULT_ACTIONS,...(row.enabled_actions||{})},languages:Array.isArray(row.languages)&&row.languages.length?row.languages:["es"],sections:Array.isArray(row.sections)?row.sections:[],house_rules:Array.isArray(row.house_rules)?row.house_rules:[],nearby_places:Array.isArray(row.nearby_places)?row.nearby_places:Array.isArray(row.useful_links)?row.useful_links:[],translations:row.translations&&typeof row.translations==="object"?row.translations:{},cover_image_url:row.cover_image_url||row.cover_url||""}
}

function Toggle({checked,onChange,title,text,disabled}){return <label className={s.toggle}><span><b>{title}</b>{text?<small>{text}</small>:null}</span><input type="checkbox" checked={Boolean(checked)} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><i/></label>}
function TextField({label,value,onChange,placeholder,type="text",disabled}){return <label className={s.field}><span>{label}</span><input type={type} value={value||""} disabled={disabled} placeholder={placeholder||""} onChange={e=>onChange(e.target.value)}/></label>}
function AreaField({label,value,onChange,placeholder,disabled}){return <label className={s.field}><span>{label}</span><textarea rows="3" value={value||""} disabled={disabled} placeholder={placeholder||""} onChange={e=>onChange(e.target.value)}/></label>}

function ContentList({title,description,items,onChange,languages,nearby=false,disabled}){
  function patch(index,key,value){onChange(items.map((item,i)=>i===index?{...item,[key]:value}:item))}
  function add(){onChange([...items,nearby?{icon:"📍",title:"",description:"",url:""}:{icon:"ℹ️",title:"",description:""}])}
  function remove(index){onChange(items.filter((_,i)=>i!==index))}
  return <div className={s.listBlock}><div className={s.listHeader}><div><h3>{title}</h3><p>{description}</p></div><button type="button" onClick={add} disabled={disabled}>＋ Agregar</button></div>
    {items.length?<div className={s.list}>{items.map((item,index)=><article key={index}>
      <div className={s.itemTop}><input className={s.iconInput} value={item.icon||""} onChange={e=>patch(index,"icon",e.target.value)} disabled={disabled} maxLength="4" aria-label="Icono"/><b>Elemento {index+1}</b><button type="button" onClick={()=>remove(index)} disabled={disabled}>Quitar</button></div>
      <div className={s.listFields}><TextField label="Título · Español" value={item.title} onChange={value=>patch(index,"title",value)} disabled={disabled}/><AreaField label="Descripción · Español" value={item.description} onChange={value=>patch(index,"description",value)} disabled={disabled}/>{nearby?<TextField label="Link / Google Maps" value={item.url} onChange={value=>patch(index,"url",value)} placeholder="https://..." disabled={disabled}/>:null}
      {languages.includes("en")?<><TextField label="Title · English" value={item.title_en} onChange={value=>patch(index,"title_en",value)} disabled={disabled}/><AreaField label="Description · English" value={item.description_en} onChange={value=>patch(index,"description_en",value)} disabled={disabled}/></>:null}
      {languages.includes("pt")?<><TextField label="Título · Português" value={item.title_pt} onChange={value=>patch(index,"title_pt",value)} disabled={disabled}/><AreaField label="Descrição · Português" value={item.description_pt} onChange={value=>patch(index,"description_pt",value)} disabled={disabled}/></>:null}</div>
    </article>)}</div>:<div className={s.listEmpty}>Todavía no cargaste contenido en esta sección.</div>}
  </div>
}

export default function GuestPortalSettings({propertyId,property}){
  const[form,setForm]=useState(DEFAULT_FORM),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("")
  const canEdit=["owner","manager"].includes(property?.role)
  useEffect(()=>{let active=true;async function load(){if(!propertyId)return;setLoading(true);setError("");const{data,error:readError}=await supabase.from("hotel_guest_guides").select("*").eq("property_id",propertyId).maybeSingle();if(!active)return;if(readError)setError(readError.message||"No se pudo cargar el portal.");else setForm(normalized(data));setLoading(false)}load();return()=>{active=false}},[propertyId])
  const previewName=property?.name||"Tu hotel",selectedLangs=useMemo(()=>LANGS.filter(item=>form.languages.includes(item.id)),[form.languages])
  function set(key,value){setForm(current=>({...current,[key]:value}))}
  function toggleLanguage(id){setForm(current=>{const has=current.languages.includes(id),next=has?current.languages.filter(item=>item!==id):[...current.languages,id];if(!next.length)return current;return{...current,languages:next,default_language:next.includes(current.default_language)?current.default_language:next[0]}})}
  function setTranslation(lang,key,value){setForm(current=>({...current,translations:{...current.translations,[lang]:{...(current.translations?.[lang]||{}),[key]:value}}}))}
  async function save(){if(!canEdit||saving)return;setSaving(true);setError("");setNotice("");try{
    const payload={property_id:propertyId,slug:`portal-${propertyId}`,enabled:Boolean(form.enabled),title:clean(form.title)||null,portal_title:clean(form.portal_title)||null,subtitle:clean(form.subtitle)||null,welcome_message:clean(form.welcome_message)||null,accent_color:clean(form.accent_color)||"#5B5CEB",logo_url:clean(form.logo_url)||null,cover_image_url:clean(form.cover_image_url)||null,wifi_name:clean(form.wifi_name)||null,wifi_password:clean(form.wifi_password)||null,contact_phone:clean(form.contact_phone)||null,contact_whatsapp:clean(form.contact_whatsapp)||null,checkin_time:clean(form.checkin_time)||null,checkout_time:clean(form.checkout_time)||null,show_account:Boolean(form.show_account),show_wifi:Boolean(form.show_wifi),show_guide:Boolean(form.show_guide),show_nearby:Boolean(form.show_nearby),show_requests:Boolean(form.show_requests),show_contact:Boolean(form.show_contact),enabled_actions:{...DEFAULT_ACTIONS,...form.enabled_actions},languages:form.languages,default_language:form.default_language,sections:form.sections,house_rules:form.house_rules,nearby_places:form.nearby_places,useful_links:form.nearby_places,translations:form.translations,published_at:form.enabled?new Date().toISOString():null,updated_at:new Date().toISOString()}
    const{data,error:writeError}=await supabase.from("hotel_guest_guides").upsert(payload,{onConflict:"property_id"}).select("*").single();if(writeError)throw writeError;setForm(normalized(data));setNotice("Portal del huésped guardado. Los próximos accesos ya usan esta configuración.")
  }catch(err){setError(err?.message||"No se pudo guardar el portal del huésped.")}finally{setSaving(false)}}
  if(loading)return <div className={s.loading}>Cargando configuración del portal…</div>
  return <div className={s.layout}>
    <div className={s.editor}>
      {error?<div className={s.error}>{error}</div>:null}{notice?<div className={s.notice}>{notice}</div>:null}
      {!canEdit?<div className={s.readOnly}>Podés ver esta configuración. Sólo propietario y manager pueden modificarla.</div>:null}
      <section className={s.card}><div className={s.cardTitle}><div><small>PORTAL DEL HUÉSPED</small><h2>Mini app de la estadía</h2><p>Definí qué ve el huésped y qué puede pedir desde su celular.</p></div><Toggle checked={form.enabled} onChange={value=>set("enabled",value)} title={form.enabled?"Activo":"Desactivado"} disabled={!canEdit}/></div></section>
      <section className={s.card}><h3>Identidad y bienvenida</h3><p className={s.intro}>Se personaliza por hotel y por huésped. El nombre del pasajero se toma de su reserva.</p><div className={s.grid}><TextField label="Título del portal" value={form.portal_title} onChange={value=>set("portal_title",value)} placeholder="Tu estadía" disabled={!canEdit}/><TextField label="Color principal" type="color" value={form.accent_color} onChange={value=>set("accent_color",value)} disabled={!canEdit}/><AreaField label="Mensaje de bienvenida · Español" value={form.welcome_message} onChange={value=>set("welcome_message",value)} placeholder="Estamos para hacerte la estadía más fácil." disabled={!canEdit}/><TextField label="Logo (URL opcional)" value={form.logo_url} onChange={value=>set("logo_url",value)} placeholder="https://..." disabled={!canEdit}/><TextField label="Imagen de portada (URL opcional)" value={form.cover_image_url} onChange={value=>set("cover_image_url",value)} placeholder="https://..." disabled={!canEdit}/></div></section>
      <section className={s.card}><h3>Idiomas</h3><p className={s.intro}>La interfaz del portal se traduce sola. Acá también podés traducir los textos propios del hotel.</p><div className={s.languageRow}>{LANGS.map(lang=><button type="button" key={lang.id} className={form.languages.includes(lang.id)?s.langOn:""} onClick={()=>toggleLanguage(lang.id)} disabled={!canEdit}><span>{lang.flag}</span><b>{lang.label}</b><small>{form.languages.includes(lang.id)?"Habilitado":"Oculto"}</small></button>)}</div><label className={s.selectField}>Idioma predeterminado<select value={form.default_language} disabled={!canEdit} onChange={e=>set("default_language",e.target.value)}>{selectedLangs.map(lang=><option key={lang.id} value={lang.id}>{lang.label}</option>)}</select></label>
        <div className={s.translationGrid}>{form.languages.includes("en")?<div><h4>English</h4><TextField label="Portal title" value={form.translations?.en?.portal_title} onChange={value=>setTranslation("en","portal_title",value)} disabled={!canEdit}/><AreaField label="Welcome message" value={form.translations?.en?.welcome_message} onChange={value=>setTranslation("en","welcome_message",value)} disabled={!canEdit}/></div>:null}{form.languages.includes("pt")?<div><h4>Português</h4><TextField label="Título do portal" value={form.translations?.pt?.portal_title} onChange={value=>setTranslation("pt","portal_title",value)} disabled={!canEdit}/><AreaField label="Mensagem de boas-vindas" value={form.translations?.pt?.welcome_message} onChange={value=>setTranslation("pt","welcome_message",value)} disabled={!canEdit}/></div>:null}</div>
      </section>
      <section className={s.card}><h3>Información práctica</h3><div className={s.grid}><TextField label="Red Wi‑Fi" value={form.wifi_name} onChange={value=>set("wifi_name",value)} disabled={!canEdit}/><TextField label="Clave Wi‑Fi" value={form.wifi_password} onChange={value=>set("wifi_password",value)} disabled={!canEdit}/><TextField label="WhatsApp de recepción" value={form.contact_whatsapp} onChange={value=>set("contact_whatsapp",value)} placeholder="54911..." disabled={!canEdit}/><TextField label="Teléfono" value={form.contact_phone} onChange={value=>set("contact_phone",value)} disabled={!canEdit}/><TextField label="Check-in" type="time" value={form.checkin_time} onChange={value=>set("checkin_time",value)} disabled={!canEdit}/><TextField label="Check-out" type="time" value={form.checkout_time} onChange={value=>set("checkout_time",value)} disabled={!canEdit}/></div></section>
      <section className={s.card}><h3>Qué puede ver</h3><div className={s.toggles}><Toggle checked={form.show_wifi} onChange={value=>set("show_wifi",value)} title="Wi‑Fi" text="Red y contraseña" disabled={!canEdit}/><Toggle checked={form.show_account} onChange={value=>set("show_account",value)} title="Mi cuenta" text="Total, pagado y saldo" disabled={!canEdit}/><Toggle checked={form.show_guide} onChange={value=>set("show_guide",value)} title="Guía del hotel" text="Horarios y servicios" disabled={!canEdit}/><Toggle checked={form.show_nearby} onChange={value=>set("show_nearby",value)} title="Lugares cercanos" text="Recomendaciones del hotel" disabled={!canEdit}/><Toggle checked={form.show_requests} onChange={value=>set("show_requests",value)} title="Mis pedidos" text="Seguimiento de solicitudes" disabled={!canEdit}/><Toggle checked={form.show_contact} onChange={value=>set("show_contact",value)} title="Contacto" text="WhatsApp y recepción" disabled={!canEdit}/></div></section>
      <section className={s.card}><h3>Qué puede solicitar</h3><p className={s.intro}>Desactivar una acción también la bloquea en el servidor: no alcanza con manipular la web para ejecutarla.</p><div className={s.actions}>{ACTIONS.map(action=><Toggle key={action.id} checked={form.enabled_actions[action.id]!==false} onChange={value=>set("enabled_actions",{...form.enabled_actions,[action.id]:value})} title={`${action.icon} ${action.label}`} disabled={!canEdit}/>)}</div></section>
      <section className={s.card}><ContentList title="Guía del hotel" description="Desayuno, piscina, estacionamiento, gimnasio, normas o cualquier dato útil." items={form.sections} onChange={value=>set("sections",value)} languages={form.languages} disabled={!canEdit}/></section>
      <section className={s.card}><ContentList title="Lugares cercanos" description="Restaurantes, farmacias, paseos o recomendaciones que querés darle al turista." items={form.nearby_places} onChange={value=>set("nearby_places",value)} languages={form.languages} nearby disabled={!canEdit}/></section>
      <div className={s.saveBar}><div><b>Los cambios son por propiedad</b><small>No modifican el portal de ningún otro hotel.</small></div><button type="button" onClick={save} disabled={!canEdit||saving}>{saving?"Guardando…":"Guardar portal"}</button></div>
    </div>
    <aside className={s.preview}><div className={s.phone} style={{"--preview-accent":form.accent_color||"#5B5CEB"}}><div className={s.phoneHero}><small>{previewName}</small><strong>Hola, Gabriel 👋</strong><h3>{form.translations?.[form.default_language]?.portal_title||form.portal_title||"¿En qué te podemos ayudar?"}</h3><p>{form.translations?.[form.default_language]?.welcome_message||form.welcome_message||"Todo lo que necesitás durante tu estadía, desde acá."}</p><div><span>Hab. 205</span><span>Salida {form.checkout_time||"10:00"}</span></div></div><div className={s.phoneApps}><span>🏨<b>Mi estadía</b></span><span>🛎️<b>Pedir algo</b></span><span>🛠️<b>Reportar</b></span><span>ℹ️<b>Info útil</b></span></div><small className={s.previewHint}>Vista previa conceptual · el portal real usa los datos de cada reserva.</small></div></aside>
  </div>
}
