"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import{AreaField,ContentList,MediaPicker,PortalPreview,TextField,Toggle}from"./GuestPortalSettingsParts"
import s from"./guestPortalSettings.module.css"

const BUCKET="hotel-guest-portal-media",LANGS=[{id:"es",label:"Español",code:"ES"},{id:"en",label:"English",code:"EN"},{id:"pt",label:"Português",code:"PT"}],ACTIONS=[{id:"towels",label:"Pedir toallas"},{id:"pillows",label:"Pedir almohadas"},{id:"cleaning",label:"Solicitar limpieza"},{id:"maintenance",label:"Reportar un problema"},{id:"late_checkout",label:"Late check-out"},{id:"other",label:"Otro pedido"}],MAP_TYPES=[{id:"restaurant",label:"Restaurantes",query:"restaurantes",icon:"restaurant"},{id:"pharmacy",label:"Farmacias",query:"farmacias",icon:"info"},{id:"attraction",label:"Qué hacer",query:"atracciones turísticas",icon:"pin"},{id:"supermarket",label:"Supermercados",query:"supermercados",icon:"hotel"}],DEFAULT_ACTIONS=Object.fromEntries(ACTIONS.map(x=>[x.id,true])),DEFAULT_NEARBY={auto:true,categories:MAP_TYPES.map(x=>x.id),address_override:""},DEFAULT_ROOM={enabled:false,service_fee_type:"none",service_fee_value:0,catalog:[],integration:"future_restaurant_extension"},DEFAULT_FEEDBACK={enabled:true,during_stay:true,post_stay:true,review_url:""},DEFAULT_AI={enabled:true,learning:true}
const DEFAULT_FORM={enabled:true,title:"",portal_title:"",welcome_message:"",accent_color:"#6474DF",logo_url:"",cover_image_url:"",wifi_name:"",wifi_password:"",contact_phone:"",contact_whatsapp:"",checkin_time:"14:00",checkout_time:"10:00",show_account:true,show_wifi:true,show_guide:true,show_nearby:true,show_requests:true,show_contact:true,enabled_actions:DEFAULT_ACTIONS,languages:["es","en","pt"],default_language:"es",sections:[],house_rules:[],nearby_places:[],nearby_config:DEFAULT_NEARBY,translations:{},room_service_config:DEFAULT_ROOM,feedback_config:DEFAULT_FEEDBACK,guest_ai_config:DEFAULT_AI}
const clean=v=>String(v??"").trim(),mapUrl=(q,a)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${q} cerca de ${a}`)}`
function normalized(row){if(!row)return DEFAULT_FORM;return{...DEFAULT_FORM,...row,enabled_actions:{...DEFAULT_ACTIONS,...(row.enabled_actions||{})},languages:Array.isArray(row.languages)&&row.languages.length?row.languages:["es"],sections:Array.isArray(row.sections)?row.sections:[],house_rules:Array.isArray(row.house_rules)?row.house_rules:[],nearby_places:(Array.isArray(row.nearby_places)?row.nearby_places:[]).filter(x=>x?.source!=="google_auto"),nearby_config:{...DEFAULT_NEARBY,...(row.nearby_config||{})},translations:row.translations&&typeof row.translations==="object"?row.translations:{},cover_image_url:row.cover_image_url||row.cover_url||"",room_service_config:{...DEFAULT_ROOM,...(row.room_service_config||{})},feedback_config:{...DEFAULT_FEEDBACK,...(row.feedback_config||{})},guest_ai_config:{...DEFAULT_AI,...(row.guest_ai_config||{})}}}

export default function GuestPortalSettings({propertyId,property}){
 const[form,setForm]=useState(DEFAULT_FORM),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[hotelAddress,setHotelAddress]=useState(""),[metrics,setMetrics]=useState({opens:0,requests:0,messages:0,assistant:0,feedback:0,score:0})
 const canEdit=["owner","manager"].includes(property?.role),set=(k,v)=>setForm(c=>({...c,[k]:v})),setNested=(root,k,v)=>setForm(c=>({...c,[root]:{...c[root],[k]:v}})),selectedLangs=useMemo(()=>LANGS.filter(x=>form.languages.includes(x.id)),[form.languages]),nearbyAddress=clean(form.nearby_config.address_override)||hotelAddress
 useEffect(()=>{let active=true;(async()=>{if(!propertyId)return;setLoading(true);const since=new Date(Date.now()-30*864e5).toISOString(),[guide,lodging,events,feedback]=await Promise.all([supabase.from("hotel_guest_guides").select("*").eq("property_id",propertyId).maybeSingle(),supabase.from("alojamientos").select("direccion,ciudad").eq("property_id",propertyId).limit(1),supabase.from("hotel_guest_portal_events").select("event_type").eq("property_id",propertyId).gte("created_at",since).limit(5000),supabase.from("hotel_guest_feedback").select("score").eq("property_id",propertyId).gte("created_at",since).limit(1000)]);if(!active)return;if(guide.error)setError(guide.error.message);else setForm(normalized(guide.data));const l=lodging.data?.[0];setHotelAddress([l?.direccion,l?.ciudad].filter(Boolean).join(", "));const ev=events.data||[],fb=feedback.data||[];setMetrics({opens:ev.filter(x=>x.event_type==="app_open").length,requests:ev.filter(x=>x.event_type==="request_created"||x.event_type==="request_confirmed").length,messages:ev.filter(x=>x.event_type==="message_sent").length,assistant:ev.filter(x=>x.event_type==="assistant_question").length,feedback:fb.length,score:fb.length?fb.reduce((a,x)=>a+Number(x.score||0),0)/fb.length:0});setLoading(false)})().catch(e=>{if(active){setError(e.message);setLoading(false)}});return()=>{active=false}},[propertyId])
 function toggleLanguage(id){setForm(c=>{const next=c.languages.includes(id)?c.languages.filter(x=>x!==id):[...c.languages,id];if(!next.length)return c;return{...c,languages:next,default_language:next.includes(c.default_language)?c.default_language:next[0]}})}
 function setTranslation(lang,key,value){setForm(c=>({...c,translations:{...c.translations,[lang]:{...(c.translations?.[lang]||{}),[key]:value}}}))}
 function automaticPlaces(){if(form.nearby_config.auto===false||!nearbyAddress)return[];return MAP_TYPES.filter(x=>form.nearby_config.categories.includes(x.id)).map(x=>({source:"google_auto",category:x.id,icon:x.icon,title:x.id==="restaurant"?"Restaurantes cerca":x.id==="pharmacy"?"Farmacias cerca":x.id==="attraction"?"Qué hacer cerca":"Supermercados cerca",description:`Buscar desde ${nearbyAddress}`,url:mapUrl(x.query,nearbyAddress)}))}
 function toggleMap(id){setNested("nearby_config","categories",form.nearby_config.categories.includes(id)?form.nearby_config.categories.filter(x=>x!==id):[...form.nearby_config.categories,id])}
 function storagePath(url){const marker=`/storage/v1/object/public/${BUCKET}/`,i=String(url||"").indexOf(marker);return i>=0?decodeURIComponent(String(url).slice(i+marker.length)):null}
 async function persistMedia(field,url){const{error:e}=await supabase.from("hotel_guest_guides").upsert({property_id:propertyId,slug:`portal-${propertyId}`,enabled:Boolean(form.enabled),[field]:url||null,updated_at:new Date().toISOString()},{onConflict:"property_id"});if(e)throw e}
 async function uploadMedia(field,file){if(!canEdit||!file)return;if(file.size>6291456)return setError("La imagen no puede superar 6 MB.");if(!["image/jpeg","image/png","image/webp","image/avif"].includes(file.type))return setError("Usá JPG, PNG, WebP o AVIF.");setUploading(field);setError("");try{const ext=file.type.split("/")[1].replace("jpeg","jpg"),path=`${propertyId}/portal/${field}-${Date.now()}.${ext}`,old=form[field],up=await supabase.storage.from(BUCKET).upload(path,file,{contentType:file.type});if(up.error)throw up.error;const url=supabase.storage.from(BUCKET).getPublicUrl(path).data?.publicUrl;if(!url)throw new Error("No se pudo obtener la imagen.");await persistMedia(field,url);set(field,url);const oldPath=storagePath(old);if(oldPath)await supabase.storage.from(BUCKET).remove([oldPath]);setNotice("Imagen cargada y guardada.")}catch(e){setError(e.message||"No se pudo subir la imagen.")}finally{setUploading("")}}
 async function removeMedia(field){setUploading(field);try{const old=form[field];await persistMedia(field,null);set(field,"");const path=storagePath(old);if(path)await supabase.storage.from(BUCKET).remove([path]);setNotice("Imagen eliminada.")}catch(e){setError(e.message)}finally{setUploading("")}}
 function addCatalog(){setNested("room_service_config","catalog",[...form.room_service_config.catalog,{id:`item-${Date.now()}`,name:"",description:"",price:0,enabled:true}])}
 function patchCatalog(index,key,value){setNested("room_service_config","catalog",form.room_service_config.catalog.map((x,i)=>i===index?{...x,[key]:value}:x))}
 function removeCatalog(index){setNested("room_service_config","catalog",form.room_service_config.catalog.filter((_,i)=>i!==index))}
 async function save(){if(!canEdit||saving)return;setSaving(true);setError("");setNotice("");try{const nearby=[...automaticPlaces(),...form.nearby_places.map(x=>({...x,source:x.source||"manual",icon:x.icon||"pin"}))],payload={property_id:propertyId,slug:`portal-${propertyId}`,enabled:Boolean(form.enabled),portal_title:clean(form.portal_title)||null,welcome_message:clean(form.welcome_message)||null,accent_color:form.accent_color||"#6474DF",logo_url:clean(form.logo_url)||null,cover_image_url:clean(form.cover_image_url)||null,wifi_name:clean(form.wifi_name)||null,wifi_password:clean(form.wifi_password)||null,contact_phone:clean(form.contact_phone)||null,contact_whatsapp:clean(form.contact_whatsapp)||null,checkin_time:clean(form.checkin_time)||null,checkout_time:clean(form.checkout_time)||null,show_account:Boolean(form.show_account),show_wifi:Boolean(form.show_wifi),show_guide:Boolean(form.show_guide),show_nearby:Boolean(form.show_nearby),show_requests:Boolean(form.show_requests),show_contact:Boolean(form.show_contact),enabled_actions:{...DEFAULT_ACTIONS,...form.enabled_actions},languages:form.languages,default_language:form.default_language,sections:form.sections,house_rules:form.house_rules,nearby_places:nearby,useful_links:nearby,nearby_config:form.nearby_config,translations:form.translations,room_service_config:form.room_service_config,feedback_config:form.feedback_config,guest_ai_config:form.guest_ai_config,published_at:form.enabled?new Date().toISOString():null,updated_at:new Date().toISOString()};const{data,error:e}=await supabase.from("hotel_guest_guides").upsert(payload,{onConflict:"property_id"}).select("*").single();if(e)throw e;setForm(normalized(data));setNotice("Portal guardado. La configuración se aplica sólo a esta propiedad.")}catch(e){setError(e.message||"No se pudo guardar.")}finally{setSaving(false)}}
 if(loading)return <div className={s.loading}>Cargando configuración del portal…</div>
 return <div className={s.portalShell}><div className={s.layout}><div className={s.editor}>{error?<div className={s.error}>{error}</div>:null}{notice?<div className={s.notice}>{notice}</div>:null}
  <section className={s.card}><div className={s.cardTitle}><div><small>PORTAL DEL HUÉSPED</small><h2>Mini app de la estadía</h2><p>Se habilita con el check-in y se revoca automáticamente al hacer check-out, cancelar o marcar no-show.</p></div><Toggle checked={form.enabled} onChange={v=>set("enabled",v)} title={form.enabled?"Activo":"Desactivado"} disabled={!canEdit}/></div></section>
  <section className={s.card}><h3>Identidad y experiencia</h3><div className={s.grid}><TextField label="Título" value={form.portal_title} onChange={v=>set("portal_title",v)} placeholder="¿En qué te podemos ayudar?" disabled={!canEdit}/><TextField label="Color principal" type="color" value={form.accent_color} onChange={v=>set("accent_color",v)} disabled={!canEdit}/><AreaField label="Bienvenida · Español" value={form.welcome_message} onChange={v=>set("welcome_message",v)} disabled={!canEdit}/></div><div className={s.mediaGrid}><MediaPicker label="Logo" help="Archivo del hotel · queda guardado automáticamente." value={form.logo_url} busy={uploading==="logo_url"} disabled={!canEdit} onPick={f=>uploadMedia("logo_url",f)} onRemove={()=>removeMedia("logo_url")}/><MediaPicker cover label="Portada" help="Foto horizontal que transmite la identidad del hotel." value={form.cover_image_url} busy={uploading==="cover_image_url"} disabled={!canEdit} onPick={f=>uploadMedia("cover_image_url",f)} onRemove={()=>removeMedia("cover_image_url")}/></div></section>
  <section className={s.card}><h3>Idiomas</h3><p className={s.intro}>El predeterminado abre primero; la elección del huésped queda guardada sólo para ese portal y dispositivo.</p><div className={s.languageRow}>{LANGS.map(x=><button type="button" key={x.id} className={form.languages.includes(x.id)?s.langOn:""} onClick={()=>toggleLanguage(x.id)} disabled={!canEdit}><span>{x.code}</span><b>{x.label}</b><small>{form.languages.includes(x.id)?"Habilitado":"Oculto"}</small></button>)}</div><label className={s.selectField}>Idioma predeterminado<select value={form.default_language} disabled={!canEdit} onChange={e=>set("default_language",e.target.value)}>{selectedLangs.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><div className={s.translationGrid}>{form.languages.includes("en")?<div><h4>English</h4><TextField label="Portal title" value={form.translations?.en?.portal_title} onChange={v=>setTranslation("en","portal_title",v)} disabled={!canEdit}/><AreaField label="Welcome message" value={form.translations?.en?.welcome_message} onChange={v=>setTranslation("en","welcome_message",v)} disabled={!canEdit}/></div>:null}{form.languages.includes("pt")?<div><h4>Português</h4><TextField label="Título do portal" value={form.translations?.pt?.portal_title} onChange={v=>setTranslation("pt","portal_title",v)} disabled={!canEdit}/><AreaField label="Mensagem" value={form.translations?.pt?.welcome_message} onChange={v=>setTranslation("pt","welcome_message",v)} disabled={!canEdit}/></div>:null}</div></section>
  <section className={s.card}><h3>Información práctica</h3><div className={s.grid}><TextField label="Red Wi‑Fi" value={form.wifi_name} onChange={v=>set("wifi_name",v)} disabled={!canEdit}/><TextField label="Clave Wi‑Fi" value={form.wifi_password} onChange={v=>set("wifi_password",v)} disabled={!canEdit}/><TextField label="WhatsApp de recepción" value={form.contact_whatsapp} onChange={v=>set("contact_whatsapp",v)} disabled={!canEdit}/><TextField label="Teléfono" value={form.contact_phone} onChange={v=>set("contact_phone",v)} disabled={!canEdit}/><TextField label="Check-in" type="time" value={form.checkin_time} onChange={v=>set("checkin_time",v)} disabled={!canEdit}/><TextField label="Check-out" type="time" value={form.checkout_time} onChange={v=>set("checkout_time",v)} disabled={!canEdit}/></div></section>
  <section className={s.card}><h3>Qué puede ver y pedir</h3><div className={s.toggles}><Toggle checked={form.show_wifi} onChange={v=>set("show_wifi",v)} title="Wi‑Fi" disabled={!canEdit}/><Toggle checked={form.show_account} onChange={v=>set("show_account",v)} title="Cuenta de la estadía" disabled={!canEdit}/><Toggle checked={form.show_guide} onChange={v=>set("show_guide",v)} title="Guía del hotel" disabled={!canEdit}/><Toggle checked={form.show_nearby} onChange={v=>set("show_nearby",v)} title="Lugares cercanos" disabled={!canEdit}/>{ACTIONS.map(x=><Toggle key={x.id} checked={form.enabled_actions[x.id]!==false} onChange={v=>set("enabled_actions",{...form.enabled_actions,[x.id]:v})} title={x.label} disabled={!canEdit}/>)}</div></section>
  <section className={s.card}><div className={s.cardTitle}><div><small>ROOM SERVICE</small><h3>Pedidos a la habitación</h3><p>Queda preparado para integrarlo después con la extensión gastronómica.</p></div><Toggle checked={form.room_service_config.enabled} onChange={v=>setNested("room_service_config","enabled",v)} title={form.room_service_config.enabled?"Visible":"Oculto"} disabled={!canEdit}/></div><div className={s.grid}><label className={s.selectField}>Cargo por servicio<select value={form.room_service_config.service_fee_type} disabled={!canEdit} onChange={e=>setNested("room_service_config","service_fee_type",e.target.value)}><option value="none">Sin cargo</option><option value="fixed">Importe fijo</option><option value="percent">Porcentaje</option></select></label>{form.room_service_config.service_fee_type!=="none"?<TextField label={form.room_service_config.service_fee_type==="percent"?"Porcentaje %":"Importe"} type="number" value={form.room_service_config.service_fee_value} onChange={v=>setNested("room_service_config","service_fee_value",Number(v)||0)} disabled={!canEdit}/>:null}</div><div className={s.listHeader}><div><h3>Artículos visibles</h3><p>El huésped sólo ve lo que habilites acá.</p></div><button type="button" onClick={addCatalog} disabled={!canEdit}>Agregar artículo</button></div><div className={s.catalogEditor}>{form.room_service_config.catalog.map((x,i)=><article key={x.id||i}><div className={s.itemTop}><b>Artículo {i+1}</b><Toggle checked={x.enabled!==false} onChange={v=>patchCatalog(i,"enabled",v)} title="Visible" disabled={!canEdit}/><button type="button" onClick={()=>removeCatalog(i)} disabled={!canEdit}>Quitar</button></div><div className={s.listFields}><TextField label="Nombre" value={x.name} onChange={v=>patchCatalog(i,"name",v)} disabled={!canEdit}/><TextField label="Precio" type="number" value={x.price} onChange={v=>patchCatalog(i,"price",Number(v)||0)} disabled={!canEdit}/><AreaField label="Descripción" value={x.description} onChange={v=>patchCatalog(i,"description",v)} disabled={!canEdit}/></div></article>)}</div></section>
  <section className={s.card}><h3>OlivIA y feedback</h3><div className={s.toggles}><Toggle checked={form.guest_ai_config.enabled} onChange={v=>setNested("guest_ai_config","enabled",v)} title="OlivIA para huéspedes" text="Sólo ve este hotel y esta estadía" disabled={!canEdit}/><Toggle checked={form.guest_ai_config.learning} onChange={v=>setNested("guest_ai_config","learning",v)} title="Aprendizaje local" text="Aprende expresiones confirmadas sólo para este tenant" disabled={!canEdit}/><Toggle checked={form.feedback_config.enabled} onChange={v=>setNested("feedback_config","enabled",v)} title="Feedback" disabled={!canEdit}/><Toggle checked={form.feedback_config.during_stay} onChange={v=>setNested("feedback_config","during_stay",v)} title="Durante la estadía" text="Una mala experiencia alerta a Recepción" disabled={!canEdit}/></div><div className={s.grid}><TextField label="URL de reseñas post-estadía" value={form.feedback_config.review_url} onChange={v=>setNested("feedback_config","review_url",v)} placeholder="Google / TripAdvisor / sitio propio" disabled={!canEdit}/></div></section>
  <section className={s.card}><ContentList title="Guía del hotel" description="Horarios, desayuno, pileta, spa, estacionamiento y otra información útil." items={form.sections} onChange={v=>set("sections",v)} languages={form.languages} disabled={!canEdit}/></section>
  <section className={s.card}><div className={s.cardTitle}><div><small>GOOGLE MAPS</small><h3>Lugares cercanos</h3><p>Parte de la dirección del hotel y además permite recomendaciones manuales.</p></div><Toggle checked={form.nearby_config.auto} onChange={v=>setNested("nearby_config","auto",v)} title="Búsquedas automáticas" disabled={!canEdit}/></div><div className={s.addressBox}><small>DIRECCIÓN DE REFERENCIA</small><b>{nearbyAddress||"Falta cargar la dirección del hotel"}</b><TextField label="Reemplazar dirección sólo para el portal" value={form.nearby_config.address_override} onChange={v=>setNested("nearby_config","address_override",v)} disabled={!canEdit}/></div><div className={s.mapTypes}>{MAP_TYPES.map(x=><button key={x.id} type="button" className={form.nearby_config.categories.includes(x.id)?s.mapTypeOn:""} onClick={()=>toggleMap(x.id)} disabled={!canEdit||!form.nearby_config.auto}><b>{x.label}</b><small>{form.nearby_config.categories.includes(x.id)?"Visible":"Oculto"}</small></button>)}</div><ContentList nearby title="Recomendaciones del hotel" description="Lugares elegidos por el hotel con su enlace de Google Maps." items={form.nearby_places} onChange={v=>set("nearby_places",v)} languages={form.languages} disabled={!canEdit}/></section>
  <section className={s.card}><small className={s.analyticsLabel}>ÚLTIMOS 30 DÍAS</small><h3>Uso del portal</h3><div className={s.metricsGrid}><span><b>{metrics.opens}</b><small>Aperturas</small></span><span><b>{metrics.requests}</b><small>Pedidos</small></span><span><b>{metrics.messages}</b><small>Mensajes</small></span><span><b>{metrics.assistant}</b><small>Consultas a OlivIA</small></span><span><b>{metrics.feedback}</b><small>Opiniones</small></span><span><b>{metrics.score?metrics.score.toFixed(1):"—"}</b><small>Promedio feedback</small></span></div></section>
  <div className={s.saveBar}><div><b>Configuración por propiedad</b><small>Nunca modifica el portal de otro hotel.</small></div><button onClick={save} disabled={!canEdit||saving}>{saving?"Guardando…":"Guardar portal"}</button></div>
 </div><PortalPreview form={form} propertyName={property?.name}/></div></div>
}
