"use client"

import GuestIcon from"../../../stay/[token]/GuestIcon"
import s from"./guestPortalSettings.module.css"

export function Toggle({checked,onChange,title,text,disabled}){return <label className={s.toggle}><span><b>{title}</b>{text?<small>{text}</small>:null}</span><input type="checkbox" checked={Boolean(checked)} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><i/></label>}
export function TextField({label,value,onChange,placeholder,type="text",disabled}){return <label className={s.field}><span>{label}</span><input type={type} value={value||""} disabled={disabled} placeholder={placeholder||""} onChange={e=>onChange(e.target.value)}/></label>}
export function AreaField({label,value,onChange,placeholder,disabled}){return <label className={s.field}><span>{label}</span><textarea rows="3" value={value||""} disabled={disabled} placeholder={placeholder||""} onChange={e=>onChange(e.target.value)}/></label>}

export function MediaPicker({label,help,value,busy,disabled,onPick,onRemove,cover=false}){return <div className={`${s.mediaCard} ${cover?s.coverMedia:""}`}><div className={s.mediaPreview}>{value?<img src={value} alt=""/>:<span><GuestIcon name={cover?"hotel":"room"} size={27}/></span>}</div><div className={s.mediaBody}><b>{label}</b><small>{help}</small><div className={s.mediaActions}><label className={s.uploadButton}>{busy?"Subiendo…":value?"Cambiar imagen":"Elegir imagen"}<input type="file" accept="image/png,image/jpeg,image/webp,image/avif" disabled={disabled||busy} onChange={e=>{const file=e.target.files?.[0];if(file)onPick(file);e.target.value=""}}/></label>{value?<button type="button" onClick={onRemove} disabled={disabled||busy}>Quitar</button>:null}</div></div></div>}

export function ContentList({title,description,items,onChange,languages,nearby=false,disabled}){
  const patch=(index,key,value)=>onChange(items.map((item,i)=>i===index?{...item,[key]:value}:item))
  const add=()=>onChange([...items,nearby?{source:"manual",icon:"pin",title:"",description:"",url:""}:{icon:"info",title:"",description:""}])
  const remove=index=>onChange(items.filter((_,i)=>i!==index))
  return <div className={s.listBlock}><div className={s.listHeader}><div><h3>{title}</h3><p>{description}</p></div><button type="button" onClick={add} disabled={disabled}>Agregar</button></div>{items.length?<div className={s.list}>{items.map((item,index)=><article key={index}><div className={s.itemTop}><b>{nearby?"Recomendación":"Contenido"} {index+1}</b><button type="button" onClick={()=>remove(index)} disabled={disabled}>Quitar</button></div><div className={s.listFields}><TextField label="Título · Español" value={item.title} onChange={value=>patch(index,"title",value)} disabled={disabled}/><AreaField label="Descripción · Español" value={item.description} onChange={value=>patch(index,"description",value)} disabled={disabled}/>{nearby?<TextField label="Google Maps o enlace" value={item.url} onChange={value=>patch(index,"url",value)} placeholder="https://www.google.com/maps/..." disabled={disabled}/>:null}{languages.includes("en")?<><TextField label="Title · English" value={item.title_en} onChange={value=>patch(index,"title_en",value)} disabled={disabled}/><AreaField label="Description · English" value={item.description_en} onChange={value=>patch(index,"description_en",value)} disabled={disabled}/></>:null}{languages.includes("pt")?<><TextField label="Título · Português" value={item.title_pt} onChange={value=>patch(index,"title_pt",value)} disabled={disabled}/><AreaField label="Descrição · Português" value={item.description_pt} onChange={value=>patch(index,"description_pt",value)} disabled={disabled}/></>:null}</div></article>)}</div>:<div className={s.listEmpty}>Todavía no cargaste contenido en esta sección.</div>}</div>
}

export function PortalPreview({form,propertyName}){
  const translated=form.translations?.[form.default_language]||{}
  return <aside className={s.preview}><div className={s.phone} style={{"--preview-accent":form.accent_color||"#5B5CEB"}}><div className={s.phoneHero} style={form.cover_image_url?{backgroundImage:`linear-gradient(150deg,rgba(18,27,42,.86),rgba(38,54,83,.72)),url(${form.cover_image_url})`}:undefined}><div className={s.previewBrand}>{form.logo_url?<img src={form.logo_url} alt=""/>:<span>{String(propertyName||"H")[0]}</span>}<b>{propertyName||"Tu hotel"}</b></div><strong>Hola, Gabriel</strong><h3>{translated.portal_title||form.portal_title||"¿En qué te podemos ayudar?"}</h3><p>{translated.welcome_message||form.welcome_message||"Todo lo que necesitás durante tu estadía, desde acá."}</p><div><span>Hab. 205</span><span>Salida {form.checkout_time||"10:00"}</span></div></div><div className={s.phoneApps}><span><i><GuestIcon name="hotel" size={21}/></i><b>Mi estadía</b></span><span><i><GuestIcon name="bell" size={21}/></i><b>Servicios</b></span><span><i><GuestIcon name="tools" size={21}/></i><b>Asistencia</b></span><span><i><GuestIcon name="pin" size={21}/></i><b>Explorar</b></span></div><small className={s.previewHint}>Vista previa · el portal real usa los datos de cada reserva.</small></div></aside>
}