"use client"

import{RoomSwitch}from"./RoomAdminControls"
import{roomMoney}from"./roomAdminShared"
import s from"./propertyRooms.module.css"

export function RoomAdminRoomList({rooms,allRooms,typeById,floorById,accessByRoom,canManage,saving,menu,openRoom,toggleRoom,duplicateRoom,removeRoom,menuButton}){
  if(!rooms.length)return <div className={s.empty}>{allRooms.length?"No hay resultados para esa búsqueda.":"Todavía no hay habitaciones. Creá la primera para empezar."}</div>
  return <div className={s.list}>{rooms.map(room=>{const type=typeById.get(room.room_type_id),floor=floorById.get(room.floor_id),access=accessByRoom.get(Number(room.id)),color=room.color||type?.color||"#8290A5",menuOpen=menu?.kind==="room"&&menu.id===room.id;return <article key={room.id} className={s.row} onClick={()=>openRoom(room)}><span className={s.drag}>⋮⋮</span><span className={s.colorDot} style={{"--room-color":color}}/><div className={s.identity}><b>{room.nombre}</b><small>{type?.name||room.tipo||"Sin tipo"} · {room.capacidad||type?.capacity||1} pers.{floor?` · ${floor.name}`:""}</small></div><div className={s.statusStack}><span data-state={room.activa?"ok":"off"}>{room.activa?"Operativa":"Inactiva"}</span><small>{room.estado||"libre"}</small></div><div className={s.access}><span data-state={access?.connection_status==="connected"?"ok":"off"}>{access?.connection_status==="connected"?"Acceso conectado":"Sin acceso smart"}</span><small>{access?.provider&&access.provider!=="manual"?access.provider:"PIN por estadía preparado"}</small></div><div className={s.switchBlock} onClick={e=>e.stopPropagation()}><span>Activa</span><RoomSwitch checked={room.activa} disabled={!canManage||saving===`activa-${room.id}`} onChange={()=>toggleRoom(room,"activa")}/></div><div className={s.switchBlock} onClick={e=>e.stopPropagation()}><span>Online</span><RoomSwitch checked={Boolean(room.activa&&room.online_bookable)} disabled={!canManage||!room.activa||saving===`online_bookable-${room.id}`} onChange={()=>toggleRoom(room,"online_bookable")}/></div><div className={s.moreWrap} onClick={e=>e.stopPropagation()}><button className={s.more} aria-label={`Acciones de ${room.nombre}`} onClick={e=>menuButton("room",room.id,e)}>⋯</button>{menuOpen&&<div className={s.menu} onClick={e=>e.stopPropagation()}><button onClick={()=>openRoom(room)}>Editar</button><button onClick={()=>duplicateRoom(room)}>Duplicar</button><button onClick={()=>toggleRoom(room,"activa")}>{room.activa?"Desactivar":"Activar"}</button><button className={s.danger} onClick={()=>removeRoom(room)}>Eliminar</button></div>}</div></article>})}</div>
}

export function RoomAdminTypeList({types,rooms,currency,canManage,saving,menu,openType,toggleType,removeType,menuButton}){
  if(!types.length)return <div className={s.empty}>No hay tipos de habitación para mostrar.</div>
  return <div className={s.list}>{types.map(type=>{const count=rooms.filter(room=>room.room_type_id===type.id).length,menuOpen=menu?.kind==="type"&&menu.id===type.id;return <article key={type.id} className={s.rowType} onClick={()=>openType(type)}><span className={s.drag}>⋮⋮</span><span className={s.colorDot} style={{"--room-color":type.color}}/><div className={s.identity}><b>{type.name}</b><small>{type.beds||0} cama{type.beds===1?"":"s"} · {type.capacity||1} pers. · {count} habitación{count===1?"":"es"}</small></div><span className={s.code}>{type.code||"SIN CÓDIGO"}</span><b className={s.price}>{roomMoney(type.base_price,currency)}</b><div className={s.switchBlock} onClick={e=>e.stopPropagation()}><span>Activo</span><RoomSwitch checked={type.active} disabled={!canManage||saving===`type-${type.id}`} onChange={()=>toggleType(type)}/></div><div className={s.moreWrap} onClick={e=>e.stopPropagation()}><button className={s.more} onClick={e=>menuButton("type",type.id,e)}>⋯</button>{menuOpen&&<div className={s.menu} onClick={e=>e.stopPropagation()}><button onClick={()=>openType(type)}>Editar</button><button onClick={()=>toggleType(type)}>{type.active?"Desactivar":"Activar"}</button><button className={s.danger} onClick={()=>removeType(type)}>Eliminar</button></div>}</div></article>})}</div>
}
