"use client"

import{ROOM_PALETTE}from"./roomAdminShared"
import{RoomField,RoomSection,RoomToggleCard}from"./RoomAdminControls"
import s from"./propertyRooms.module.css"

export default function RoomAdminTypeDrawer({form,setForm,canManage,saving,currency,onClose,onSave,onDelete}){
  const patch=values=>setForm(current=>({...current,...values})),amenities=(form.amenities||[]).join(", ")
  return <div className={s.backdrop} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className={s.drawer} onMouseDown={e=>e.stopPropagation()}><header className={s.drawerHead}><div><small>TIPO DE HABITACIÓN</small><h2>{form.id?`Editar ${form.name}`:"Nuevo tipo"}</h2><p>Esta ficha se reutiliza en Planning, tarifas, integraciones y venta directa.</p></div><button className={s.close} onClick={onClose}>×</button></header><div className={s.drawerBody}>
    <RoomSection title="Identidad comercial" subtitle="Nombre, código y color consistentes en todo el PMS."><div className={s.formGrid}><RoomField label="Nombre"><input value={form.name||""} onChange={e=>patch({name:e.target.value})} autoFocus/></RoomField><RoomField label="Código interno"><input value={form.code||""} maxLength="16" onChange={e=>patch({code:e.target.value.toUpperCase()})} placeholder="DBL-SUP"/></RoomField><RoomField label="Orden"><input type="number" value={form.sort_order||0} onChange={e=>patch({sort_order:e.target.value})}/></RoomField><div className={s.colorField}><span>Color</span><div className={s.colors}>{ROOM_PALETTE.map(color=><button type="button" key={color} aria-label={color} className={form.color===color?s.colorSelected:""} style={{"--pick":color}} onClick={()=>patch({color})}/>)}</div></div></div></RoomSection>
    <RoomSection title="Capacidad" subtitle="Valores predeterminados para las habitaciones de este tipo."><div className={`${s.formGrid} ${s.four}`}><RoomField label="Máximo"><input type="number" min="1" max="30" value={form.capacity||1} onChange={e=>patch({capacity:e.target.value})}/></RoomField><RoomField label="Adultos"><input type="number" min="0" max="30" value={form.adults||0} onChange={e=>patch({adults:e.target.value})}/></RoomField><RoomField label="Niños"><input type="number" min="0" max="30" value={form.children||0} onChange={e=>patch({children:e.target.value})}/></RoomField><RoomField label="Camas"><input type="number" min="0" max="20" value={form.beds||0} onChange={e=>patch({beds:e.target.value})}/></RoomField></div></RoomSection>
    <RoomSection title="Venta" subtitle="Base comercial que puede variar por fecha en Tarifas y disponibilidad."><div className={s.formGrid}><RoomField label={`Tarifa base · ${currency}`}><input type="number" min="0" value={form.base_price||0} onChange={e=>patch({base_price:e.target.value})}/></RoomField><RoomField label="Amenities separados por coma"><input value={amenities} onChange={e=>patch({amenities:e.target.value.split(",").map(v=>v.trim()).filter(Boolean)})} placeholder="Wi‑Fi, TV, Aire acondicionado"/></RoomField><RoomToggleCard title="Tipo activo" text="Disponible para nuevas habitaciones y configuración comercial." checked={form.active!==false} onChange={value=>patch({active:value,online_bookable:value?form.online_bookable:false})}/><RoomToggleCard title="Visible en venta directa" text="Puede mostrarse en el Motor y sitio web." checked={Boolean(form.active&&form.online_bookable)} disabled={!form.active} onChange={value=>patch({online_bookable:value})}/></div></RoomSection>
    <RoomSection title="Descripción pública" subtitle="Texto reutilizable en el Motor y la web del hotel."><RoomField label="Descripción"><textarea rows="5" value={form.description||""} onChange={e=>patch({description:e.target.value})} placeholder="Contá qué hace especial a este tipo de habitación."/></RoomField></RoomSection>
  </div><footer className={s.drawerFooter}>{onDelete&&canManage?<button className={s.deleteButton} onClick={onDelete}>Eliminar tipo</button>:<span/>}<div><button onClick={onClose}>Cancelar</button><button className={s.primary} disabled={!canManage||saving||!form.name?.trim()} onClick={onSave}>{saving?"Guardando…":"Guardar cambios"}</button></div></footer></aside></div>
}
