"use client"

import{useCallback,useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import s from"./subscription.module.css"

const PLANS=[
  {id:"essential",name:"Esencial",tag:"Operación diaria",description:"Para alojamientos que necesitan ordenar recepción y operación sin sumar complejidad.",features:["Planning y reservas","Huéspedes y mensajes","Caja diaria","Housekeeping","Reportes operativos"]},
  {id:"pro",name:"Pro",tag:"Venta + gestión",description:"Para hoteles que quieren vender directo y concentrar la gestión comercial en el mismo PMS.",features:["Todo Esencial","Sitio web + Motor","Finanzas y documentos","Ventas y crecimiento","Integraciones externas","Automatizaciones"]},
  {id:"total",name:"Total",tag:"Hotel conectado",description:"Para equipos que necesitan channel manager, revenue y capacidades avanzadas de OlivIA.",features:["Todo Pro","Channel Manager","Revenue & forecast","OlivIA avanzada","API e integraciones premium","Operación multi-propiedad"]},
]
const TIERS=[{id:"1-10",min:1,max:10,label:"1–10"},{id:"11-25",min:11,max:25,label:"11–25"},{id:"26-50",min:26,max:50,label:"26–50"},{id:"51-100",min:51,max:100,label:"51–100"},{id:"101-200",min:101,max:200,label:"101–200"},{id:"201+",min:201,max:Infinity,label:"201+"}]
const STATUS={inactive:"Sin activar",trial:"Prueba",active:"Activo",past_due:"Pago pendiente",canceled:"Cancelado"}
const fmtDate=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(value)):"—"
const money=(value,currency)=>value==null?"A definir":new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:0}).format(Number(value)||0)

export default function SubscriptionPanel({propertyId,property}){
  const[subscription,setSubscription]=useState(null),[entitlements,setEntitlements]=useState([]),[requests,setRequests]=useState([]),[rooms,setRooms]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[cycle,setCycle]=useState("monthly"),[saving,setSaving]=useState(false)
  const isOwner=property?.role==="owner"
  const load=useCallback(async()=>{if(!propertyId)return;setLoading(true);setError("");try{const[roomRes,subRes,entRes,reqRes]=await Promise.all([supabase.from("habitaciones").select("id",{count:"exact",head:true}).eq("property_id",propertyId).eq("activa",true),supabase.from("hotel_subscriptions").select("id,plan_code,status,billing_cycle,room_tier,room_limit,price_amount,price_currency,started_at,renews_at,source,metadata,updated_at").eq("property_id",propertyId).maybeSingle(),supabase.from("hotel_feature_entitlements").select("feature_code,enabled,source,metadata").eq("property_id",propertyId).order("feature_code"),isOwner?supabase.from("hotel_subscription_requests").select("id,plan_code,billing_cycle,room_tier,status,note,created_at,updated_at").eq("property_id",propertyId).order("created_at",{ascending:false}).limit(5):Promise.resolve({data:[],error:null})]);for(const result of[roomRes,subRes,entRes,reqRes])if(result.error)throw result.error;setRooms(roomRes.count||0);setSubscription(subRes.data||null);setEntitlements(entRes.data||[]);setRequests(reqRes.data||[]);if(subRes.data?.billing_cycle)setCycle(subRes.data.billing_cycle)}catch(err){setError(err?.message||"No se pudo cargar la suscripción.")}finally{setLoading(false)}},[propertyId,isOwner])
  useEffect(()=>{load()},[load])
  const tier=useMemo(()=>TIERS.find(item=>rooms>=item.min&&rooms<=item.max)||TIERS[TIERS.length-1],[rooms]),currentPlan=PLANS.find(plan=>plan.id===subscription?.plan_code),pending=requests.find(item=>item.status==="pending"),usage=subscription?.room_limit?Math.min(100,Math.round((rooms/subscription.room_limit)*100)):0,paymentLabel=subscription?.metadata?.payment_method_label||(subscription?.metadata?.payment_last4?`•••• ${subscription.metadata.payment_last4}`:"Sin método guardado")
  async function requestPlan(planCode){if(!isOwner||saving||pending)return;setSaving(true);setError("");setNotice("");try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("No pudimos validar tu sesión.");const{error:e}=await supabase.from("hotel_subscription_requests").insert({property_id:propertyId,requested_by:user.id,plan_code:planCode,billing_cycle:cycle,room_tier:tier.id});if(e)throw e;setNotice("Solicitud registrada. El plan actual no cambia hasta que la activación quede confirmada.");await load()}catch(err){setError(err?.message||"No se pudo registrar la solicitud.")}finally{setSaving(false)}}
  async function cancelRequest(){if(!pending||saving)return;setSaving(true);setError("");try{const{error:e}=await supabase.from("hotel_subscription_requests").update({status:"canceled",updated_at:new Date().toISOString()}).eq("id",pending.id).eq("property_id",propertyId);if(e)throw e;setNotice("Solicitud cancelada.");await load()}catch(err){setError(err?.message||"No se pudo cancelar la solicitud.")}finally{setSaving(false)}}
  if(loading)return <div className={s.loading}>Cargando plan y módulos…</div>
  return <div className={s.page}>
    {error&&<div className={s.error}>{error}</div>}{notice&&<div className={s.notice}>{notice}</div>}
    <section className={s.current}>
      <div className={s.currentCopy}><div className={s.badges}><span>PLAN ACTUAL</span><b data-state={subscription?.status||"inactive"}>● {STATUS[subscription?.status]||"Sin activar"}</b></div><h2>{currentPlan?.name||"Sin suscripción comercial"}</h2><p>{currentPlan?currentPlan.description:"La propiedad sigue operativa. Cuando se active una suscripción, acá vas a ver renovación, precio y módulos incluidos."}</p></div>
      <button className={s.changePlan} style={{color:"#26347a",WebkitTextFillColor:"#26347a"}} type="button" onClick={()=>document.getElementById("planes-hl")?.scrollIntoView({behavior:"smooth",block:"start"})}>＋ Cambiar plan</button>
      <div className={s.currentStats}><article><span>Estado</span><b>{STATUS[subscription?.status]||"Sin activar"}</b><small>{subscription?.status==="active"?"Suscripción habilitada":"Gestión comercial pendiente"}</small></article><article><span>Próxima renovación</span><b>{fmtDate(subscription?.renews_at)}</b><small>{subscription?.billing_cycle==="annual"?"Ciclo anual":subscription?.billing_cycle==="monthly"?"Ciclo mensual":"Sin ciclo definido"}</small></article><article><span>Precio del plan</span><b>{money(subscription?.price_amount,subscription?.price_currency)}</b><small>{subscription?.price_currency||"ARS"}</small></article><article><span>Habitaciones en uso</span><b>{rooms}{subscription?.room_limit?` / ${subscription.room_limit}`:""}</b><small>Inventario activo</small></article></div>
    </section>
    <div className={s.detailsGrid}>
      <section className={s.detailsCard}><header><div><small>DETALLES DE SUSCRIPCIÓN</small><h3>Información del plan</h3></div></header><div className={s.detailRows}><div><span>Plan</span><b>{currentPlan?.name||"—"}</b></div><div><span>Ciclo</span><b>{subscription?.billing_cycle==="annual"?"Anual":subscription?.billing_cycle==="monthly"?"Mensual":"—"}</b></div><div><span>Inicio</span><b>{fmtDate(subscription?.started_at)}</b></div><div><span>Renueva</span><b>{fmtDate(subscription?.renews_at)}</b></div><div><span>Tramo</span><b>{subscription?.room_tier||tier.label}</b></div><div><span>Origen</span><b>{subscription?.source||"Plataforma"}</b></div></div><div className={s.usage}><div><span>Habitaciones utilizadas</span><b>{rooms}{subscription?.room_limit?` / ${subscription.room_limit}`:""}</b></div><i><span style={{width:`${usage}%`}}/></i></div></section>
      <section className={s.paymentMethod}><small>MÉTODO DE PAGO</small><div className={s.cardGlyph}>▭</div><h3>{paymentLabel}</h3><p>{subscription?.metadata?.payment_last4?"Método registrado para renovaciones.":"Todavía no hay una tarjeta o medio de renovación guardado en la suscripción."}</p><button type="button" disabled>Actualizar método · Próximamente</button></section>
    </div>
    <section className={s.roomTier}><div><small>ESCALA DE LA PROPIEDAD</small><h3>{tier.label} habitaciones</h3><p>Detectamos {rooms} habitación{rooms===1?"":"es"} activa{rooms===1?"":"s"}. Los planes se muestran dentro del tramo correcto.</p></div><div className={s.tiers}>{TIERS.map(item=><span key={item.id} data-active={item.id===tier.id} data-disabled={rooms>item.max}>{item.label}</span>)}</div></section>
    {pending?<section className={s.pending}><div><small>SOLICITUD PENDIENTE</small><h3>{PLANS.find(plan=>plan.id===pending.plan_code)?.name||pending.plan_code} · {pending.billing_cycle==="annual"?"anual":"mensual"}</h3><p>Pedida el {fmtDate(pending.created_at)}. No habilitamos ni cobramos un plan hasta que exista confirmación del circuito comercial.</p></div>{isOwner?<button disabled={saving} onClick={cancelRequest}>Cancelar solicitud</button>:null}</section>:null}
    <section id="planes-hl"><div className={s.sectionHead}><div><small>PLANES</small><h2>Elegí el nivel de herramientas</h2><p>Tres niveles simples. Los módulos bloqueados siguen visibles para que el hotel entienda qué puede sumar.</p></div><div className={s.cycle}><button data-active={cycle==="monthly"} onClick={()=>setCycle("monthly")}>Mensual</button><button data-active={cycle==="annual"} onClick={()=>setCycle("annual")}>Anual</button></div></div><div className={s.planGrid}>{PLANS.map(plan=><article key={plan.id} className={s.planCard} data-current={subscription?.plan_code===plan.id}><div><span>{plan.tag}</span><h3>{plan.name}</h3><p>{plan.description}</p></div><ul>{plan.features.map(feature=><li key={feature}>✓ {feature}</li>)}</ul><footer>{subscription?.plan_code===plan.id?<b>✓ Plan actual</b>:isOwner?<button disabled={Boolean(pending)||saving} onClick={()=>requestPlan(plan.id)}>{pending?"Solicitud pendiente":`Solicitar ${plan.name}`}</button>:<span>Consultá con el propietario</span>}</footer></article>)}</div></section>
    <section className={s.modules}><div className={s.sectionHead}><div><small>MÓDULOS</small><h2>Herramientas de la propiedad</h2><p>El plan define qué módulos existen; el rol del usuario define qué puede hacer dentro de ellos.</p></div></div>{entitlements.length?<div className={s.moduleGrid}>{entitlements.map(item=><article key={item.feature_code}><span data-on={item.enabled}>{item.enabled?"Activo":"Bloqueado"}</span><b>{item.feature_code.replaceAll("_"," ")}</b><small>{item.source==="manual"?"Excepción manual":"Incluido por plan"}</small></article>)}</div>:<div className={s.emptyModules}><b>Sin restricciones comerciales aplicadas</b><p>Hoy no hay entitlements específicos cargados para esta propiedad. Eso evita bloquear módulos por error mientras se termina de conectar el circuito de suscripción.</p></div>}</section>
  </div>
}
