"use client"

import{useMemo,useState}from"react"
import{money,shortDate,isoDate}from"../../core/formatters"
import{deleteResource}from"../../services/resourceCatalog"
import ui from"../../v2.module.css"

function Modal({title,onClose,children,onSubmit}){return <div className={ui.shade} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className={ui.modal} onSubmit={onSubmit}><header><h3>{title}</h3><button type="button" onClick={onClose}>×</button></header>{children}</form></div>}
function Field({label,wide=false,children}){return <label className={wide?ui.wide:""}><span>{label}</span>{children}</label>}

export function RoomsView({rooms,floors,canManage,onSaveFloor,onSaveRoom,onBlock}){
  const[floor,setFloor]=useState(null),[room,setRoom]=useState(null)
  const groups=useMemo(()=>{const map=floors.map(f=>({...f,rooms:rooms.filter(r=>String(r.floor_id)===String(f.id))}));const orphan=rooms.filter(r=>!r.floor_id||!floors.some(f=>String(f.id)===String(r.floor_id)));return orphan.length?[...map,{id:"orphan",name:"Sin piso asignado",rooms:orphan}]:map},[floors,rooms])
  return <div className={ui.content}><div className={ui.editorial}><div><small>HOTEL STRUCTURE</small><h2>El edificio, exactamente como existe.</h2><p>Pisos y habitaciones editables, sin depender del calendario.</p></div>{canManage&&<div className={ui.inline}><button onClick={()=>setFloor({name:"",sort_order:(floors.length+1)*10,active:true})}>＋ Piso</button><button onClick={()=>setRoom({nombre:"",tipo:"Doble",capacidad:2,precio:0,cochera_precio:0,floor_id:floors[0]?.id||"",sort_order:rooms.length+1,estado:"libre",activa:true})}>＋ Habitación</button></div>}</div><div className={ui.floorStack}>{groups.map(group=><section className={ui.floorCard} key={group.id}><header><div><small>PISO</small><h3>{group.name}</h3><span>{group.rooms.length} habitaciones</span></div>{canManage&&group.id!=="orphan"&&<button onClick={()=>setFloor(group)}>Editar</button>}</header><div className={ui.roomGrid}>{group.rooms.map(item=><article className={ui.roomCard} key={item.id}><div className={ui.door}><b>{item.nombre}</b><i/></div><div><small>{item.tipo||"Habitación"}</small><h4>{item.nombre}</h4><p>{item.capacidad||1} pax · {money(item.precio)} / noche</p><span className={ui.badge}>{item.estado||"libre"}</span><div className={ui.cardActions}>{canManage&&<button onClick={()=>setRoom(item)}>Editar</button>}<button onClick={()=>onBlock(item)}>Bloquear</button></div></div></article>)}</div></section>)}</div>{floor&&<FloorEditor draft={floor} setDraft={setFloor} onClose={()=>setFloor(null)} onSave={async e=>{e.preventDefault();await onSaveFloor(floor);setFloor(null)}}/>}{room&&<RoomEditor draft={room} setDraft={setRoom} floors={floors} onClose={()=>setRoom(null)} onSave={async e=>{e.preventDefault();await onSaveRoom(room);setRoom(null)}}/>}</div>
}

function FloorEditor({draft,setDraft,onClose,onSave}){return <Modal title={draft.id?"Editar piso":"Nuevo piso"} onClose={onClose} onSubmit={onSave}><div className={ui.fieldGrid}><Field label="Nombre" wide><input autoFocus value={draft.name||""} onChange={e=>setDraft(x=>({...x,name:e.target.value}))}/></Field><Field label="Orden"><input type="number" value={draft.sort_order||0} onChange={e=>setDraft(x=>({...x,sort_order:e.target.value}))}/></Field></div><footer><button type="button" onClick={onClose}>Cancelar</button><button>Guardar piso</button></footer></Modal>}
function RoomEditor({draft,setDraft,floors,onClose,onSave}){return <Modal title={draft.id?"Editar habitación":"Nueva habitación"} onClose={onClose} onSubmit={onSave}><div className={ui.fieldGrid}><Field label="Nombre"><input autoFocus value={draft.nombre||""} onChange={e=>setDraft(x=>({...x,nombre:e.target.value}))}/></Field><Field label="Piso"><select value={draft.floor_id||""} onChange={e=>setDraft(x=>({...x,floor_id:e.target.value||null}))}><option value="">Sin piso</option>{floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Field><Field label="Tipo"><input value={draft.tipo||""} onChange={e=>setDraft(x=>({...x,tipo:e.target.value}))}/></Field><Field label="Capacidad"><input type="number" min="1" value={draft.capacidad||1} onChange={e=>setDraft(x=>({...x,capacidad:e.target.value}))}/></Field><Field label="Tarifa"><input type="number" min="0" value={draft.precio||0} onChange={e=>setDraft(x=>({...x,precio:e.target.value}))}/></Field><Field label="Cochera"><input type="number" min="0" value={draft.cochera_precio||0} onChange={e=>setDraft(x=>({...x,cochera_precio:e.target.value}))}/></Field><Field label="Zona Housekeeping"><input value={draft.housekeeping_zone||""} onChange={e=>setDraft(x=>({...x,housekeeping_zone:e.target.value}))}/></Field><Field label="Estado"><select value={draft.estado||"libre"} onChange={e=>setDraft(x=>({...x,estado:e.target.value}))}><option value="libre">Libre</option><option value="limpia">Limpia</option><option value="sucia">Sucia</option><option value="inspeccion">Inspección</option><option value="mantenimiento">Mantenimiento</option></select></Field><Field label="Descripción" wide><textarea value={draft.descripcion||""} onChange={e=>setDraft(x=>({...x,descripcion:e.target.value}))}/></Field></div><footer><button type="button" onClick={onClose}>Cancelar</button><button>Guardar habitación</button></footer></Modal>}

export function HousekeepingView({rooms,reservations,tasks,onRoomStatus,onSaveTask,onTaskStatus}){
  const[editor,setEditor]=useState(null),today=isoDate()
  const priority=room=>{const dirty=String(room.estado||"").toLowerCase()==="sucia",arrival=reservations.some(r=>String(r.habitacion_id)===String(room.id)&&r.fecha_entrada===today&&r.estado!=="cancelada"),departure=reservations.some(r=>String(r.habitacion_id)===String(room.id)&&r.fecha_salida===today&&r.estado!=="finalizada");return dirty&&arrival?"URGENTE":dirty||departure?"ALTA":String(room.estado).toLowerCase()==="mantenimiento"?"BLOQUEADA":"LISTA"}
  return <div className={ui.content}><div className={ui.editorial}><div><small>HOUSEKEEPING</small><h2>La próxima llegada define la prioridad.</h2><p>Limpieza, inspección, minibar y tareas comparten el estado real de la habitación.</p></div><button onClick={()=>setEditor({room_id:rooms[0]?.id||"",task_type:"cleaning",priority:"normal",status:"pending",scheduled_for:new Date().toISOString().slice(0,16),notes:""})}>＋ Tarea</button></div><div className={ui.hkGrid}>{rooms.map(room=><article className={ui.hkCard} key={room.id}><div><small>{priority(room)}</small><h3>{room.nombre}</h3><p>{room.estado||"libre"}</p></div><div className={ui.cardActions}><button onClick={()=>onRoomStatus(room,"limpia")}>Lista</button><button onClick={()=>onRoomStatus(room,"sucia")}>Sucia</button><button onClick={()=>onRoomStatus(room,"inspeccion")}>Inspección</button></div></article>)}</div><section className={ui.panel}><h3>Tareas de Housekeeping</h3>{tasks.slice(0,80).map(task=><div className={ui.listRow} key={task.id}><span><b>{rooms.find(r=>String(r.id)===String(task.room_id))?.nombre||task.room_id} · {task.task_type}</b><small>{task.priority} · {task.scheduled_for?new Date(task.scheduled_for).toLocaleString("es-AR"):"Sin horario"}</small></span><div className={ui.rowActions}><button onClick={()=>onTaskStatus(task,"in_progress")}>En proceso</button><button onClick={()=>onTaskStatus(task,"done")}>Terminar</button></div></div>)}</section>{editor&&<HousekeepingEditor draft={editor} setDraft={setEditor} rooms={rooms} onClose={()=>setEditor(null)} onSave={async e=>{e.preventDefault();await onSaveTask(editor);setEditor(null)}}/>}</div>
}
function HousekeepingEditor({draft,setDraft,rooms,onClose,onSave}){return <Modal title="Nueva tarea de Housekeeping" onClose={onClose} onSubmit={onSave}><div className={ui.fieldGrid}><Field label="Habitación"><select value={draft.room_id} onChange={e=>setDraft(x=>({...x,room_id:e.target.value}))}>{rooms.map(r=><option key={r.id} value={r.id}>{r.nombre}</option>)}</select></Field><Field label="Tipo"><select value={draft.task_type} onChange={e=>setDraft(x=>({...x,task_type:e.target.value}))}><option value="cleaning">Limpieza</option><option value="inspection">Inspección</option><option value="turndown">Turn down</option><option value="minibar">Minibar</option></select></Field><Field label="Prioridad"><select value={draft.priority} onChange={e=>setDraft(x=>({...x,priority:e.target.value}))}><option>low</option><option>normal</option><option>high</option><option>urgent</option></select></Field><Field label="Programada"><input type="datetime-local" value={draft.scheduled_for||""} onChange={e=>setDraft(x=>({...x,scheduled_for:e.target.value?new Date(e.target.value).toISOString():null}))}/></Field><Field label="Notas" wide><textarea value={draft.notes||""} onChange={e=>setDraft(x=>({...x,notes:e.target.value}))}/></Field></div><footer><button type="button" onClick={onClose}>Cancelar</button><button>Crear tarea</button></footer></Modal>}

export function MaintenanceView({rooms,resources,tickets,onSave,onStatus}){const[editor,setEditor]=useState(null);return <div className={ui.content}><div className={ui.editorial}><div><small>MAINTENANCE DESK</small><h2>Que una falla no se convierta en una mala estadía.</h2><p>Tickets, prioridad, habitación afectada, costo y resolución en un solo flujo.</p></div><button onClick={()=>setEditor({room_id:"",resource_id:"",title:"",description:"",priority:"normal",status:"open",cost:0,notes:""})}>＋ Ticket</button></div><div className={ui.ticketGrid}>{tickets.map(t=><article className={ui.ticket} key={t.id}><small>{t.priority?.toUpperCase()} · {t.status}</small><h3>{t.title}</h3><p>{t.description||"Sin detalle"}</p><span>{t.room_id?`Hab. ${rooms.find(r=>String(r.id)===String(t.room_id))?.nombre||t.room_id}`:"General"} · {money(t.cost||0)}</span><div className={ui.cardActions}><button onClick={()=>onStatus(t,"in_progress")}>En proceso</button><button onClick={()=>onStatus(t,"done")}>Resolver</button></div></article>)}</div>{editor&&<MaintenanceEditor draft={editor} setDraft={setEditor} rooms={rooms} resources={resources} onClose={()=>setEditor(null)} onSave={async e=>{e.preventDefault();await onSave(editor);setEditor(null)}}/>}</div>}
function MaintenanceEditor({draft,setDraft,rooms,resources,onClose,onSave}){return <Modal title="Nuevo mantenimiento" onClose={onClose} onSubmit={onSave}><div className={ui.fieldGrid}><Field label="Título" wide><input autoFocus value={draft.title} onChange={e=>setDraft(x=>({...x,title:e.target.value}))}/></Field><Field label="Habitación"><select value={draft.room_id||""} onChange={e=>setDraft(x=>({...x,room_id:e.target.value}))}><option value="">General</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.nombre}</option>)}</select></Field><Field label="Recurso"><select value={draft.resource_id||""} onChange={e=>setDraft(x=>({...x,resource_id:e.target.value}))}><option value="">Sin recurso</option>{resources.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Field label="Prioridad"><select value={draft.priority} onChange={e=>setDraft(x=>({...x,priority:e.target.value}))}><option>low</option><option>normal</option><option>high</option><option>urgent</option></select></Field><Field label="Costo"><input type="number" min="0" value={draft.cost||0} onChange={e=>setDraft(x=>({...x,cost:e.target.value}))}/></Field><Field label="Descripción" wide><textarea value={draft.description||""} onChange={e=>setDraft(x=>({...x,description:e.target.value}))}/></Field></div><footer><button type="button" onClick={onClose}>Cancelar</button><button>Crear ticket</button></footer></Modal>}

const CATEGORY_LABELS={parking:"Cochera / vehículo",pet:"Mascota",service:"Servicio / extra",crib:"Cuna",spa:"SPA",event_space:"Salón",meeting_room:"Sala",equipment:"Equipamiento",transfer:"Transfer",amenity:"Amenity",sport:"Deporte",other:"Otro"}
const MODE_LABELS={per_use:"Por uso",per_stay:"Por estadía",per_hour:"Por hora",per_day:"Por día",per_night:"Por noche",per_person:"Por persona"}
export function ResourcesView({resources,onSave}){
  const[editor,setEditor]=useState(null),[deleted,setDeleted]=useState([]),[message,setMessage]=useState("")
  const visible=resources.filter(r=>!deleted.includes(r.id))
  async function removeResource(resource){if(!window.confirm(`¿Eliminar ${resource.name}? Las reservas históricas conservan el precio aplicado.`))return;setMessage("");try{await deleteResource({propertyId:resource.property_id,id:resource.id});setDeleted(x=>[...x,resource.id]);setMessage("Recurso eliminado.")}catch(error){setMessage(error.message||"No se pudo eliminar el recurso.")}}
  return <div className={ui.content}><div className={ui.editorial}><div><small>CONFIGURACIÓN DEL HOTEL</small><h2>Extras, cocheras y servicios.</h2><p>Este es el catálogo maestro de este hotel. Los precios que defina el cliente acá se ofrecen como predeterminados en todas sus reservas, sin afectar a otras propiedades.</p></div><button onClick={()=>setEditor({category:"service",name:"",code:"",capacity:1,status:"available",price:0,charge_mode:"per_stay",location:"",active:true})}>＋ Agregar concepto</button></div>{message&&<div className={ui.notice}>{message}</div>}<div className={ui.resourceGrid}>{visible.map(r=><article className={ui.resourceCard} key={r.id}><small>{CATEGORY_LABELS[r.category]||r.category?.toUpperCase()}</small><h3>{r.name}</h3><p>{r.category==="parking"?"Tipo de vehículo / cochera":r.location||"Disponible para reservas"}</p><b>{money(r.price||0)}</b><span>{MODE_LABELS[r.charge_mode]||r.charge_mode}</span><div className={ui.cardActions}><button onClick={()=>setEditor(r)}>Editar</button><button onClick={()=>removeResource(r)}>Eliminar</button></div></article>)}</div>{!visible.length&&<section className={ui.panel}><p>Todavía no hay conceptos configurados. Podés crear cochera de auto, cochera de camioneta, mascota y cualquier otro extra del hotel.</p></section>}{editor&&<ResourceEditor draft={editor} setDraft={setEditor} onClose={()=>setEditor(null)} onSave={async e=>{e.preventDefault();await onSave(editor);setEditor(null)}}/>}</div>
}
function ResourceEditor({draft,setDraft,onClose,onSave}){return <Modal title={draft.id?"Editar valor predeterminado":"Nuevo valor predeterminado"} onClose={onClose} onSubmit={onSave}><div className={ui.fieldGrid}><Field label={draft.category==="parking"?"Tipo de vehículo / nombre":"Nombre"} wide><input autoFocus value={draft.name||""} placeholder={draft.category==="parking"?"Ej. Auto, Camioneta, Moto":"Ej. Mascota, Cuna, Desayuno extra"} onChange={e=>setDraft(x=>({...x,name:e.target.value}))}/></Field><Field label="Categoría"><select value={draft.category} onChange={e=>setDraft(x=>({...x,category:e.target.value}))}><option value="parking">Cochera / vehículo</option><option value="pet">Mascota</option><option value="service">Servicio / extra</option><option value="crib">Cuna</option><option value="spa">SPA</option><option value="event_space">Salón</option><option value="meeting_room">Sala</option><option value="equipment">Equipamiento</option><option value="transfer">Transfer</option><option value="amenity">Amenity</option><option value="sport">Deporte</option><option value="other">Otro</option></select></Field><Field label="Precio predeterminado"><input type="number" min="0" step="0.01" value={draft.price??0} onChange={e=>setDraft(x=>({...x,price:e.target.value}))}/></Field><Field label="Cómo se cobra"><select value={draft.charge_mode||"per_stay"} onChange={e=>setDraft(x=>({...x,charge_mode:e.target.value}))}><option value="per_stay">Por estadía</option><option value="per_night">Por noche</option><option value="per_day">Por día</option><option value="per_person">Por persona</option><option value="per_use">Por uso</option><option value="per_hour">Por hora</option></select></Field><Field label="Capacidad"><input type="number" min="1" value={draft.capacity||1} onChange={e=>setDraft(x=>({...x,capacity:e.target.value}))}/></Field><Field label="Ubicación / nota"><input value={draft.location||""} onChange={e=>setDraft(x=>({...x,location:e.target.value}))}/></Field></div><footer><button type="button" onClick={onClose}>Cancelar</button><button>Guardar para este hotel</button></footer></Modal>}

export function DigitalTwinView({rooms,floors,reservations}){const today=isoDate(),floorMap=new Map(floors.map(f=>[String(f.id),f.name]));return <div className={ui.content}><div className={ui.editorial}><div><small>HOTEL DIGITAL TWIN</small><h2>El edificio vivo, no un dibujo decorativo.</h2><p>Estado, ocupación y operación se proyectan sobre la estructura real.</p></div></div><div className={ui.twin}>{rooms.map(room=>{const stay=reservations.find(r=>String(r.habitacion_id)===String(room.id)&&r.fecha_entrada<=today&&r.fecha_salida>today&&r.estado!=="cancelada");return <article key={room.id} className={`${ui.twinRoom} ${stay?ui.twinOccupied:""}`}><div className={ui.door}><b>{room.nombre}</b><i/></div><small>{floorMap.get(String(room.floor_id))||"Sin piso"}</small><h3>{stay?stay.nombre_huesped:"Disponible"}</h3><p>{room.estado||"libre"}</p></article>})}</div></div>}
