"use client"

import{useEffect,useMemo,useState}from"react"
import{useHotelSession}from"../../hooks/useHotelSession"
import{commitImportBatch,loadImportBatch,loadImportContext,stageImportBatch}from"../../services/importCenter"
import{buildNormalizedRows,IMPORT_FIELDS,parseDelimited,REQUIRED_IMPORT_FIELDS,suggestMapping,uniqueSourceRooms}from"./importCenterParser"
import s from"./import-center.module.css"

const CORE_FIELDS=new Set(["external_ref","guest_name","email","phone","check_in","check_out","room","pax","total","paid_amount","currency","channel","payment_method","partner_name","notes"])
const fold=value=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"")
const statusText={draft:"Preparando",validated:"Con observaciones",ready:"Listo para importar",importing:"Importando",completed:"Importado",failed:"Falló",cancelled:"Cancelado"}
const rowStatus={valid:"LISTA",invalid:"CORREGIR",duplicate:"DUPLICADA",skipped:"HISTÓRICA",imported:"IMPORTADA",failed:"ERROR",staged:"PENDIENTE"}

export default function ImportCenter({propertyId,sourceSystem="",currency="ARS",canManage=true,onImported}){
  const session=useHotelSession(),[context,setContext]=useState({rooms:[],batches:[]}),[parsed,setParsed]=useState(null),[fileName,setFileName]=useState(""),[mapping,setMapping]=useState({}),[roomMap,setRoomMap]=useState({}),[batchData,setBatchData]=useState(null),[busy,setBusy]=useState(""),[message,setMessage]=useState("")
  async function reloadContext(){if(!propertyId)return;try{setContext(await loadImportContext(propertyId))}catch(error){setMessage(error.message||"No se pudo cargar Import Center.")}}
  useEffect(()=>{reloadContext()},[propertyId])
  const sourceRooms=useMemo(()=>parsed?uniqueSourceRooms(parsed.rows,mapping):[],[parsed,mapping]),missingRequired=REQUIRED_IMPORT_FIELDS.filter(field=>!mapping[field]),unmappedRooms=sourceRooms.filter(name=>!roomMap[name]),stats=batchData?.batch?.stats||{},rows=batchData?.rows||[]
  function autoRoomMap(names,rooms){const next={};for(const name of names){const key=fold(name),matches=rooms.filter(room=>fold(room.nombre)===key);if(matches.length===1)next[name]=String(matches[0].id)}return next}
  async function chooseFile(event){const file=event.target.files?.[0];if(!file)return;if(file.size>2_500_000){setMessage("El archivo supera 2,5 MB. Dividilo en partes de hasta 2500 filas.");return}setBusy("file");setMessage("");setBatchData(null);try{const text=await file.text(),data=parseDelimited(text),suggested=suggestMapping(data.headers),rooms=uniqueSourceRooms(data.rows,suggested);setParsed(data);setFileName(file.name);setMapping(suggested);setRoomMap(autoRoomMap(rooms,context.rooms));setMessage(`${data.rows.length} filas leídas. Revisá el mapeo antes de validar.`)}catch(error){setParsed(null);setMessage(error.message||"No pudimos leer el archivo.")}finally{setBusy("")}}
  function changeMapping(field,column){const next={...mapping,[field]:column};if(!column)delete next[field];setMapping(next);if(field==="room"&&parsed){const names=uniqueSourceRooms(parsed.rows,next);setRoomMap(autoRoomMap(names,context.rooms))}}
  async function stage(){if(!canManage||busy||!parsed)return;if(missingRequired.length)return setMessage("Faltan mapear los campos obligatorios.");if(unmappedRooms.length)return setMessage("Mapeá todas las habitaciones antes de validar.");setBusy("stage");setMessage("");try{const normalizedRows=buildNormalizedRows({rows:parsed.rows,mapping,roomMap,defaultCurrency:currency}),result=await stageImportBatch({propertyId,userId:session.user?.id,sourceSystem:sourceSystem||"PMS anterior",fileName,mapping:{columns:mapping,rooms:roomMap},rows:normalizedRows});setBatchData(result);await reloadContext();setMessage(result.batch.status==="ready"?"Validación terminada: el lote está listo para importar.":"Validación terminada. Hay filas que necesitan corrección.")}catch(error){setMessage(error.message||"No se pudo validar el archivo.")}finally{setBusy("")}}
  async function openBatch(id){setBusy(`open-${id}`);setMessage("");try{setBatchData(await loadImportBatch({propertyId,batchId:id}))}catch(error){setMessage(error.message||"No se pudo abrir el lote.")}finally{setBusy("")}}
  async function commit(){if(!canManage||busy||batchData?.batch?.status!=="ready")return;const count=Number(stats.valid||0);if(!window.confirm(`¿Importar ${count} reserva(s) validadas? Las duplicadas e históricas se omiten y no se enviarán cambios a canales externos durante esta operación.`))return;setBusy("commit");setMessage("");try{const result=await commitImportBatch(batchData.batch.id);setBatchData(await loadImportBatch({propertyId,batchId:batchData.batch.id}));await reloadContext();setMessage(`Importación completada: ${result.imported||0} reservas, ${result.duplicates||0} duplicadas omitidas y ${result.skipped||0} históricas omitidas.`);onImported?.();window.dispatchEvent(new Event("hl:onboarding-changed"))}catch(error){setMessage(error.message||"La importación se revirtió completa por seguridad.")}finally{setBusy("")}}
  const renderMap=fields=><div className={s.mappingGrid}>{IMPORT_FIELDS.filter(([id])=>fields.has(id)).map(([id,label])=><label key={id}><span>{label}</span><select disabled={!canManage} value={mapping[id]||""} onChange={e=>changeMapping(id,e.target.value)}><option value="">No importar</option>{parsed?.headers.map(header=><option key={header} value={header}>{header}</option>)}</select></label>)}</div>
  return <section className={s.root}>
    <header className={s.hero}><div><small>IMPORT CENTER</small><h3>Primero mirar. Después importar.</h3><p>CSV o TSV del PMS anterior → mapeo → staging → validación de duplicados, habitaciones, fechas y saldos → commit atómico.</p></div><span>IMPORT MODE · SIN SYNC EXTERNO</span></header>
    {message&&<div className={s.message}>{message}</div>}
    <div className={s.uploadRow}><label className={s.upload}><input type="file" accept=".csv,.tsv,.txt,text/csv,text/tab-separated-values" disabled={!canManage||!!busy} onChange={chooseFile}/><b>{busy==="file"?"Leyendo…":"Elegir exportación CSV / TSV"}</b><small>Máx. 2500 filas · 2,5 MB</small></label><div><small>SISTEMA DE ORIGEN</small><b>{sourceSystem||"PMS anterior"}</b><span>Moneda por defecto: {currency}</span></div></div>
    {parsed&&<>
      <section className={s.mapping}><div className={s.sectionHead}><div><small>1 · MAPEO DE COLUMNAS</small><h4>{fileName} · {parsed.rows.length} filas</h4></div><em data-ok={!missingRequired.length}>{missingRequired.length?`${missingRequired.length} obligatorios sin mapear`:"Campos mínimos listos"}</em></div>{renderMap(CORE_FIELDS)}<details><summary>Campos opcionales de huésped / empresa</summary>{renderMap(new Set(IMPORT_FIELDS.map(([id])=>id).filter(id=>!CORE_FIELDS.has(id))))}</details></section>
      <section className={s.rooms}><div className={s.sectionHead}><div><small>2 · MAPEO DE HABITACIONES</small><h4>Origen → habitación real del hotel</h4></div><em data-ok={!unmappedRooms.length}>{unmappedRooms.length?`${unmappedRooms.length} sin mapear`:"Todas resueltas"}</em></div><div>{sourceRooms.map(name=><label key={name}><span>{name}</span><b>→</b><select disabled={!canManage} value={roomMap[name]||""} onChange={e=>setRoomMap(current=>({...current,[name]:e.target.value}))}><option value="">Elegir habitación</option>{context.rooms.map(room=><option key={room.id} value={room.id}>{room.nombre}{room.tipo?` · ${room.tipo}`:""}{room.capacidad?` · ${room.capacidad} pax`:""}</option>)}</select></label>)}</div></section>
      <div className={s.validateBar}><div><b>La validación no toca reservas reales.</b><span>Las filas quedan en staging y se revisan en servidor.</span></div><button type="button" disabled={!canManage||!!busy||!!missingRequired.length||!!unmappedRooms.length} onClick={stage}>{busy==="stage"?"Validando…":"Validar en staging"}</button></div>
    </>}
    {batchData&&<section className={s.preview}><div className={s.sectionHead}><div><small>3 · PREVIEW VALIDADO</small><h4>{batchData.batch.file_name}</h4></div><em data-status={batchData.batch.status}>{statusText[batchData.batch.status]||batchData.batch.status}</em></div><div className={s.stats}><span><b>{stats.total||rows.length}</b>Total</span><span data-good><b>{stats.valid||0}</b>Listas</span><span data-bad><b>{stats.invalid||0}</b>Corregir</span><span><b>{stats.duplicates||0}</b>Duplicadas</span><span><b>{stats.skipped||0}</b>Históricas</span><span><b>{stats.warning_rows||0}</b>Con aviso</span></div><div className={s.tableWrap}><table><thead><tr><th>Fila</th><th>Huésped</th><th>Estadía</th><th>Habitación</th><th>Total</th><th>Estado</th><th>Diagnóstico</th></tr></thead><tbody>{rows.slice(0,100).map(row=>{const n=row.normalized_data||{},v=row.validation||{},errors=v.errors||[],warnings=v.warnings||[],room=context.rooms.find(x=>String(x.id)===String(v.room_id||n.room_id));return <tr key={row.id} data-status={row.import_status}><td>{row.row_number}</td><td><b>{n.guest_name||"—"}</b><small>{n.external_ref||n.email||"Sin referencia"}</small></td><td>{n.check_in||"—"} → {n.check_out||"—"}</td><td>{room?.nombre||n.room_source||"—"}</td><td>{n.currency||currency} {n.total||0}</td><td><em>{rowStatus[row.import_status]||row.import_status}</em></td><td>{errors.map((x,i)=><span key={`e-${i}`} data-error>{x}</span>)}{warnings.map((x,i)=><span key={`w-${i}`}>{x}</span>)}{!errors.length&&!warnings.length&&<span>Sin observaciones</span>}</td></tr>})}</tbody></table></div>{rows.length>100&&<p className={s.limit}>Vista previa de 100 filas. La validación incluye las {rows.length} filas.</p>}<div className={s.commitBar}><div><b>{batchData.batch.status==="completed"?"Lote importado y auditado":stats.invalid>0?"Hay errores bloqueantes":"Todo listo para el commit"}</b><span>Si algo falla durante el commit, PostgreSQL revierte el lote completo.</span></div>{batchData.batch.status==="ready"&&<button type="button" disabled={!canManage||!!busy} onClick={commit}>{busy==="commit"?"Importando…":`Importar ${stats.valid||0} reservas`}</button>}</div></section>}
    {!!context.batches.length&&<section className={s.history}><div className={s.sectionHead}><div><small>HISTORIAL</small><h4>Lotes de esta propiedad</h4></div></div><div>{context.batches.map(batch=><button type="button" key={batch.id} onClick={()=>openBatch(batch.id)} disabled={!!busy}><span><b>{batch.file_name||"Importación"}</b><small>{new Date(batch.created_at).toLocaleString("es-AR")}{batch.source_system?` · ${batch.source_system}`:""}</small></span><em data-status={batch.status}>{statusText[batch.status]||batch.status}</em><strong>{batch.stats?.imported??batch.stats?.valid??0}/{batch.stats?.total??0}</strong></button>)}</div></section>}
  </section>
}
