"use client"

import{useEffect,useMemo,useState}from"react"
import{useHotelSession}from"../../hooks/useHotelSession"
import{loadOnboardingProject,saveOnboardingProject,setOnboardingTask}from"../../services/onboarding"
import ImportCenter from"./ImportCenter"
import s from"./onboarding-center.module.css"

const SECTIONS=[
  {id:"config",week:"Semana 1",title:"Construimos tu hotel",detail:"Configuración completa antes de importar operación.",tasks:[["identity","Identidad y operación"],["rooms","Habitaciones y categorías"],["rates","Tarifas y reglas"],["taxes","Impuestos / fiscalidad"],["users","Usuarios y permisos"],["payments","Cobros y caja"]]},
  {id:"data",week:"Semana 2",title:"Traemos tus datos",detail:"Importación controlada, mapeada y conciliada.",tasks:[["mapping","Mapeo del sistema anterior"],["future_reservations","Reservas futuras"],["guests","Huéspedes"],["partners","Empresas y agencias"],["balances","Saldos y anticipos"],["reconciliation","Conciliación de muestra"]]},
  {id:"training",week:"Semana 3",title:"Trabajamos en paralelo",detail:"El sistema anterior sigue productivo mientras el equipo practica.",tasks:[["reception","Recepción / reservas"],["housekeeping","Housekeeping"],["management","Dirección / administración"],["shadow_mode","Shadow mode validado"]]},
  {id:"golive",week:"Semana 4",title:"Go-live controlado",detail:"Sólo después de conciliar datos y validar al equipo.",tasks:[["delta_import","Importación delta final"],["final_reconciliation","Conciliación final"],["team_signoff","Conformidad del hotel"],["channel_cutover","Cutover de conexiones aprobado"]]},
]
const SCOPE=[["reservations","Reservas futuras"],["guests","Huéspedes"],["companies","Empresas"],["agencies","Agencias"],["balances","Saldos"],["rates","Tarifas"],["inventory","Inventario"],["notes","Notas / contexto"]]
const statusLabel={planning:"Planificación",configuring:"Configurando",importing:"Importando",parallel:"En paralelo",ready:"Listo para go-live",live:"Operativo",paused:"Pausado"}
const uid=()=>globalThis.crypto?.randomUUID?.()||`b-${Date.now()}-${Math.random().toString(36).slice(2,7)}`
function completion(project){let done=0,total=0;for(const section of SECTIONS)for(const[task]of section.tasks){total++;if(project?.checklist?.[section.id]?.[task])done++}return{done,total,percent:total?Math.round(done/total*100):0}}
function sectionDone(project,section){return section.tasks.every(([task])=>!!project?.checklist?.[section.id]?.[task])}
function derivedStatus(project){if(project?.status==="live"||project?.status==="paused")return project.status;if(!sectionDone(project,SECTIONS[0]))return"configuring";if(!sectionDone(project,SECTIONS[1]))return"importing";if(!sectionDone(project,SECTIONS[2]))return"parallel";return sectionDone(project,SECTIONS[3])?"ready":"parallel"}

export default function OnboardingCenter({propertyId,currency="ARS"}){
  const session=useHotelSession(),canManage=["owner","manager","admin"].includes(session.role),[project,setProject]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[blockerText,setBlockerText]=useState("")
  async function reload(){if(!propertyId)return;setLoading(true);setMessage("");try{setProject(await loadOnboardingProject(propertyId))}catch(error){setMessage(error.message||"No se pudo cargar la puesta en marcha.")}finally{setLoading(false)}}
  useEffect(()=>{reload()},[propertyId])
  const progress=useMemo(()=>completion(project),[project]),phase=project?derivedStatus(project):"planning",unresolved=(project?.blockers||[]).filter(x=>!x.resolved).length,ready=progress.total>0&&progress.done===progress.total&&unresolved===0
  const patch=(key,value)=>setProject(current=>({...current,[key]:value}))
  async function toggleTask(section,task){if(!canManage||busy)return;const next=!project?.checklist?.[section]?.[task];setBusy(`${section}.${task}`);setMessage("");setProject(current=>({...current,checklist:{...current.checklist,[section]:{...current.checklist[section],[task]:next}}}));try{setProject(await setOnboardingTask({propertyId,section,task,done:next}))}catch(error){setMessage(error.message||"No se pudo actualizar la etapa.");await reload()}finally{setBusy("")}}
  async function save(){if(!canManage||busy)return;setBusy("save");setMessage("");try{const saved=await saveOnboardingProject({propertyId,userId:session.user?.id,draft:{...project,status:project.status==="live"?"live":phase}});setProject(saved);setMessage("Proyecto de puesta en marcha guardado para todo el hotel.")}catch(error){setMessage(error.message||"No se pudo guardar la puesta en marcha.")}finally{setBusy("")}}
  async function goLive(){if(!canManage||!ready||busy)return;if(!window.confirm("¿Registrar que el hotel está listo y operativo en Habitación Llena? Esto NO cambia conexiones ni canales automáticamente."))return;setBusy("live");setMessage("");try{const saved=await saveOnboardingProject({propertyId,userId:session.user?.id,draft:{...project,status:"live",went_live_at:new Date().toISOString()}});setProject(saved);setMessage("Go-live registrado. Las conexiones externas siguen bajo control manual.")}catch(error){setMessage(error.message||"No se pudo registrar el go-live.")}finally{setBusy("")}}
  function addBlocker(){const value=blockerText.trim().slice(0,240);if(!value)return;patch("blockers",[...(project.blockers||[]),{id:uid(),text:value,resolved:false}]);setBlockerText("")}
  function toggleBlocker(id){patch("blockers",(project.blockers||[]).map(item=>item.id===id?{...item,resolved:!item.resolved}:item))}
  function removeBlocker(id){patch("blockers",(project.blockers||[]).filter(item=>item.id!==id))}
  if(loading)return <section className={s.loading}>Preparando proyecto de migración…</section>
  if(!project)return <section className={s.loading}>{message||"No se pudo abrir el onboarding."}</section>
  return <section className={s.root}>
    <header className={s.hero}><div><small>CENTRO DE PUESTA EN MARCHA</small><h2>Migración Llena · sin cerrar el hotel</h2><p>El PMS anterior sigue productivo mientras configuramos, importamos, entrenamos y conciliamos. El corte sucede recién cuando el hotel está validado.</p></div><div className={s.progress}><strong>{progress.percent}%</strong><span><i style={{width:`${progress.percent}%`}}/></span><small>{progress.done} de {progress.total} controles · {statusLabel[phase]}</small></div></header>
    {message&&<div className={s.message}>{message}</div>}
    <div className={s.projectGrid}><section className={s.panel}><div className={s.panelHead}><span><small>PROYECTO</small><h3>De dónde venimos y cuándo cambiamos</h3></span><em data-status={phase}>{statusLabel[phase]}</em></div><div className={s.fields}><label>Sistema actual<input disabled={!canManage} value={project.source_system||""} onChange={e=>patch("source_system",e.target.value)} placeholder="Ej. Cloudbeds, WinHotel, Excel…"/></label><label>Versión / plan<input disabled={!canManage} value={project.source_system_version||""} onChange={e=>patch("source_system_version",e.target.value)} placeholder="Opcional"/></label><label>Go-live objetivo<input disabled={!canManage} type="date" value={project.target_go_live||""} onChange={e=>patch("target_go_live",e.target.value)}/></label><label>Modalidad<select disabled={!canManage} value={project.migration_mode||"parallel"} onChange={e=>patch("migration_mode",e.target.value)}><option value="parallel">Paralelo / shadow mode</option><option value="staged">Migración por etapas</option></select></label></div></section><section className={s.panel}><div className={s.panelHead}><span><small>RESPONSABLES</small><h3>Una persona dueña de cada frente</h3></span></div><div className={s.fields}><label>Proyecto<input disabled={!canManage} value={project.responsibles?.project||""} onChange={e=>patch("responsibles",{...project.responsibles,project:e.target.value})}/></label><label>Datos / importación<input disabled={!canManage} value={project.responsibles?.data||""} onChange={e=>patch("responsibles",{...project.responsibles,data:e.target.value})}/></label><label>Capacitación<input disabled={!canManage} value={project.responsibles?.training||""} onChange={e=>patch("responsibles",{...project.responsibles,training:e.target.value})}/></label></div></section></div>
    <section className={s.scope}><div><small>ALCANCE DE IMPORTACIÓN</small><h3>Traemos lo que el hotel necesita, no basura histórica.</h3><p>El alcance queda registrado antes de procesar archivos para poder conciliar exactamente qué se migró.</p></div><div>{SCOPE.map(([id,label])=><button type="button" key={id} disabled={!canManage} data-on={!!project.data_scope?.[id]} onClick={()=>patch("data_scope",{...project.data_scope,[id]:!project.data_scope?.[id]})}>{project.data_scope?.[id]?"✓":"＋"} {label}</button>)}</div></section>
    <ImportCenter propertyId={propertyId} sourceSystem={project.source_system} currency={currency} canManage={canManage} onImported={reload}/>
    <div className={s.weeks}>{SECTIONS.map((section,index)=>{const complete=sectionDone(project,section);return <article key={section.id} className={complete?s.weekDone:""}><header><i>{complete?"✓":String(index+1).padStart(2,"0")}</i><span><small>{section.week}</small><h3>{section.title}</h3><p>{section.detail}</p></span></header><div className={s.tasks}>{section.tasks.map(([task,label])=>{const checked=!!project.checklist?.[section.id]?.[task];return <button type="button" key={task} disabled={!canManage||!!busy} data-done={checked} onClick={()=>toggleTask(section.id,task)}><i>{checked?"✓":""}</i><span>{label}</span>{busy===`${section.id}.${task}`&&<em>Guardando…</em>}</button>})}</div></article>})}</div>
    <div className={s.bottomGrid}><section className={s.panel}><div className={s.panelHead}><span><small>BLOQUEOS</small><h3>Lo que impide avanzar</h3></span><em>{unresolved} abiertos</em></div><div className={s.blockers}>{(project.blockers||[]).map(item=><div key={item.id} data-resolved={item.resolved}><button type="button" disabled={!canManage} onClick={()=>toggleBlocker(item.id)}>{item.resolved?"✓":"!"}</button><span>{item.text}</span>{canManage&&<button type="button" className={s.remove} onClick={()=>removeBlocker(item.id)}>×</button>}</div>)}{!(project.blockers||[]).length&&<p>Sin bloqueos registrados.</p>}</div>{canManage&&<div className={s.addBlocker}><input value={blockerText} onChange={e=>setBlockerText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addBlocker()}}} placeholder="Ej. falta exportar reservas del PMS anterior…"/><button type="button" onClick={addBlocker}>Agregar</button></div>}</section><section className={s.guard}><small>NO-DOWNTIME GUARD</small><h3>El sistema anterior no se apaga por calendario.</h3><ul><li>Configuración e importación ocurren antes del corte.</li><li>El equipo practica en paralelo con datos conciliados.</li><li>Se hace un delta final de reservas/cambios.</li><li>Canales y conexiones cambian sólo con conformidad del hotel.</li></ul><b>{ready?"Todos los controles están completos.":`${progress.total-progress.done} controles y ${unresolved} bloqueos pendientes.`}</b></section></div>
    <section className={s.actions}><label>Notas del proyecto<textarea disabled={!canManage} value={project.notes||""} onChange={e=>patch("notes",e.target.value)} placeholder="Decisiones, formatos de exportación, excepciones, horarios de corte…"/></label><div>{!canManage&&<span>Solo owner, manager o admin pueden modificar el proyecto.</span>}{canManage&&<button type="button" disabled={!!busy} onClick={save}>{busy==="save"?"Guardando…":"Guardar proyecto"}</button>}{canManage&&project.status!=="live"&&<button type="button" className={s.live} disabled={!ready||!!busy} onClick={goLive}>{busy==="live"?"Registrando…":"Registrar go-live"}</button>}{project.status==="live"&&<strong>● HOTEL OPERATIVO · {project.went_live_at?new Date(project.went_live_at).toLocaleDateString("es-AR"):"GO-LIVE"}</strong>}</div></section>
  </section>
}
