"use client"

import s from"./planning.module.css"
import g from"./planningGroup.module.css"
import l from"./planningLifecycle.module.css"
import{planningStage,planningStageLabel}from"./planningLifecycle"

const DAY=86400000
const fromKey=value=>{const[y,m,d]=String(value).split("-").map(Number);return new Date(y,m-1,d,12)}
const pad=value=>String(value).padStart(2,"0")
const keyFromDate=date=>`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`
const addDays=(value,amount)=>keyFromDate(new Date(fromKey(value).getTime()+amount*DAY))
const diffDays=(a,b)=>Math.round((fromKey(b)-fromKey(a))/DAY)
const longDate=value=>new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",year:"numeric"}).format(fromKey(value)).replace(".","")
const money=(value,currency="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:0}).format(Number(value)||0)
const STEPS=["Fecha","Habitación","Titular","Detalles"]
const uniqueIds=values=>[...new Set((values||[]).filter(Boolean).map(value=>String(value)))]

export function ReservationDetailDrawer({selected,room,rooms=[],onClose,onOpen}){
  if(!selected)return null
  const assigned=rooms.length?rooms:[room].filter(Boolean),selectedIds=uniqueIds([selected.habitacion_id,...(selected.habitaciones_ids||[])]),roomLabel=assigned.length>1?`${assigned.length} habitaciones · ${assigned.map(item=>item.nombre).join(", ")}`:selectedIds.length>1?`${selectedIds.length} habitaciones asignadas`:`Habitación ${assigned[0]?.nombre||"—"}`,stage=planningStage(selected)
  return <aside className={s.detailDrawer}><header><div><small>{selected.canal_reserva||"Directa"} · {selected.numero_reserva||selected.id}</small><h2>{selected.nombre_huesped}</h2><p>{roomLabel}</p></div><button className={s.close} onClick={onClose}>×</button></header><div className={s.detailGrid}><div><small>Llegada</small><b>{longDate(selected.fecha_entrada)}</b></div><div><small>Salida</small><b>{longDate(selected.fecha_salida)}</b></div><div><small>Noches</small><b>{Math.max(1,diffDays(selected.fecha_entrada,selected.fecha_salida))}</b></div><div><small>Estado en Planning</small><b><span className={`${l.stagePill} ${l[stage]}`}>{planningStageLabel(selected)}</span></b></div><div><small>Huéspedes</small><b>{selected.cantidad_huespedes||1}</b></div><div><small>Total</small><b>{money(selected.precio_total,selected.moneda)}</b></div></div>{selected.telefono_huesped||selected.email_huesped?<div className={s.contactBlock}>{selected.telefono_huesped?<p><small>Teléfono</small><b>{selected.telefono_huesped}</b></p>:null}{selected.email_huesped?<p><small>Email</small><b>{selected.email_huesped}</b></p>:null}</div>:null}{selected.notas?<div className={s.noteBlock}><small>Notas</small><p>{selected.notas}</p></div>:null}<footer><button onClick={onClose}>Cerrar</button><button className={s.primary} onClick={onOpen}>Abrir reserva</button></footer></aside>
}

export function CreateReservationDrawer({draft,setDraft,drawerStep,setDrawerStep,draftState,availableRooms,roomById,nights,total,saving,onClose,onDiscard,onNext,onSave}){
  if(!draft)return null
  const selectedRoomIds=uniqueIds(draft.roomIds?.length?draft.roomIds:[draft.roomId]),selectedRooms=selectedRoomIds.map(id=>roomById.get(Number(id))).filter(Boolean)
  const roomNames=selectedRooms.map(room=>room.nombre),capacity=selectedRooms.reduce((sum,room)=>sum+(Number(room.capacidad)||1),0)
  const invalidSelectedRooms=availableRooms.filter(room=>selectedRoomIds.includes(String(room.id))&&(!room.available||room.estado==="mantenimiento")),hasInvalidSelection=invalidSelectedRooms.length>0
  function toggleRoom(room){const id=String(room.id),current=uniqueIds(draft.roomIds?.length?draft.roomIds:[draft.roomId]),isSelected=current.includes(id),unavailable=!room.available||room.estado==="mantenimiento";if(unavailable&&!isSelected)return;const next=isSelected?current.filter(value=>value!==id):[...current,id],nextRate=next.reduce((sum,value)=>sum+(Number(roomById.get(Number(value))?.precio)||0),0);setDraft(currentDraft=>({...currentDraft,roomIds:next,roomId:next[0]||"",rate:nextRate}))}
  const title=drawerStep===0?"Elegí las fechas":drawerStep===1?"Seleccioná habitaciones":drawerStep===2?"Datos del titular":"Revisá la reserva"
  return <div className={s.drawerShade} onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside className={s.createDrawer} role="dialog" aria-modal="true" aria-label="Crear reserva"><header className={s.drawerHeader}><div><small>CREAR RESERVA</small><h2>{title}</h2><p>{draftState}</p></div><button className={s.close} onClick={onClose}>×</button></header><nav className={s.stepNav}>{STEPS.map((step,index)=><button key={step} className={index===drawerStep?s.stepActive:index<drawerStep?s.stepDone:""} onClick={()=>index<=drawerStep&&setDrawerStep(index)}><span>{index+1}</span>{step}</button>)}</nav><div className={s.drawerBody}>
    {drawerStep===0?<div className={s.stepPanel}><div className={s.dateSummary}><span><small>Entrada</small><b>{longDate(draft.start)}</b></span><span className={s.nightsBadge}>{nights} noche{nights===1?"":"s"}</span><span><small>Salida</small><b>{longDate(draft.end)}</b></span></div><div className={s.formGrid}><label>Entrada<input type="date" value={draft.start} onChange={event=>setDraft(current=>({...current,start:event.target.value,end:current.end<=event.target.value?addDays(event.target.value,1):current.end}))}/></label><label>Salida<input type="date" min={addDays(draft.start,1)} value={draft.end} onChange={event=>setDraft(current=>({...current,end:event.target.value}))}/></label><label>Huéspedes<input type="number" min="1" value={draft.guests} onChange={event=>setDraft(current=>({...current,guests:Number(event.target.value)||1}))}/></label><label>Moneda<select value={draft.currency} onChange={event=>setDraft(current=>({...current,currency:event.target.value}))}><option value="ARS">ARS</option><option value="USD">USD</option></select></label></div><p className={s.stepHelp}>Para una reserva grupal, arrastrá un rectángulo sobre varios días y varias habitaciones en el Planning. También podés sumar o quitar habitaciones en el paso siguiente.</p></div>:null}
    {drawerStep===1?<div className={s.stepPanel}><div className={g.groupSummary}><div><small>Habitaciones seleccionadas</small><b>{selectedRoomIds.length||0}</b><span>{roomNames.length?roomNames.join(", "):"Todavía no seleccionaste habitaciones"}</span>{selectedRoomIds.length>1?<span className={g.groupTag}>Reserva grupal</span>:null}</div><div><small>Capacidad combinada</small><b>{capacity} pax</b><span>{selectedRoomIds.length>1?"Una sola reserva, varias habitaciones":"Selección individual"}</span></div></div><p className={g.roomHint}>Elegí una o varias habitaciones disponibles para estas fechas. Las ocupadas quedan bloqueadas y no se pueden agregar.</p><div className={s.roomOptions}>{availableRooms.map(room=>{const active=selectedRoomIds.includes(String(room.id)),unavailable=!room.available||room.estado==="mantenimiento",blocked=unavailable&&!active,invalid=unavailable&&active;return <button key={room.id} disabled={blocked} aria-invalid={invalid?"true":"false"} className={`${s.roomOption} ${active?s.roomOptionActive:""}`} style={invalid?{opacity:.72}:undefined} onClick={()=>toggleRoom(room)}><span className={`${g.roomCheck} ${active?g.roomCheckSelected:""}`}>{active?"✓":""}</span><span><small>{room.tipo||"Sin tipo"}</small><b>{room.nombre}</b><em>{room.capacidad||1} pax · {room.estado==="mantenimiento"?"Mantenimiento":invalid?"Ocupada · quitá esta selección":room.available?"Disponible":"Ocupada"}</em></span><strong>{money(room.precio,draft.currency)}<small>/ noche</small></strong></button>})}</div>{hasInvalidSelection?<p className={s.stepHelp}>La habitación {invalidSelectedRooms.map(room=>room.nombre).join(", ")} ya está ocupada en parte de estas fechas. Quitala y elegí otra disponible para continuar.</p>:null}<label className={s.rateField}>Tarifa total por noche<input type="number" min="0" value={draft.rate} onChange={event=>setDraft(current=>({...current,rate:Number(event.target.value)||0}))}/></label><p className={g.roomListNote}>La tarifa total por noche es la suma de las habitaciones seleccionadas y se puede ajustar manualmente antes de confirmar.</p></div>:null}
    {drawerStep===2?<div className={s.stepPanel}><div className={s.formGrid}><label>Nombre<input value={draft.firstName} onChange={event=>setDraft(current=>({...current,firstName:event.target.value}))} autoFocus/></label><label>Apellido<input value={draft.lastName} onChange={event=>setDraft(current=>({...current,lastName:event.target.value}))}/></label><label>Teléfono<input value={draft.phone} onChange={event=>setDraft(current=>({...current,phone:event.target.value}))} placeholder="11 0000 0000"/></label><label>Email<input type="email" value={draft.email} onChange={event=>setDraft(current=>({...current,email:event.target.value}))} placeholder="huesped@email.com"/></label></div></div>:null}
    {drawerStep===3?<div className={s.stepPanel}><div className={s.review}><div><small>Estadía</small><b>{longDate(draft.start)} — {longDate(draft.end)}</b><span>{nights} noche{nights===1?"":"s"}</span></div><div><small>{selectedRoomIds.length>1?"Habitaciones":"Habitación"}</small><b>{roomNames.slice(0,3).join(", ")||"—"}{roomNames.length>3?` +${roomNames.length-3}`:""}</b><span>{selectedRoomIds.length>1?`${selectedRoomIds.length} habitaciones · ${capacity} pax de capacidad`:selectedRooms[0]?.tipo||""}</span></div><div><small>Titular</small><b>{`${draft.firstName} ${draft.lastName}`.trim()||"Sin completar"}</b><span>{draft.phone||draft.email||"Sin contacto"}</span></div><div><small>Total</small><b>{money(total,draft.currency)}</b><span>{money(draft.rate,draft.currency)} × {nights}</span></div></div><div className={s.formGrid}><label>Canal<select value={draft.channel} onChange={event=>setDraft(current=>({...current,channel:event.target.value}))}><option>Directa</option><option>Motor</option><option>Booking.com</option><option>Expedia</option><option>Despegar</option><option>Airbnb</option><option>Agencia</option></select></label><label>Estado comercial<select value={draft.status} onChange={event=>setDraft(current=>({...current,status:event.target.value}))}><option value="confirmada">Venta · confirmada / garantizada</option><option value="pendiente">Preventa · pendiente de confirmación</option><option value="tentativa">Preventa · tentativa</option></select></label><label className={s.fullField}>Notas<textarea rows="4" value={draft.notes} onChange={event=>setDraft(current=>({...current,notes:event.target.value}))} placeholder="Pedidos, observaciones o información interna"/></label></div><p className={s.stepHelp}>Después, el Planning cambia automáticamente a Check-in, In-house, Check-out, Postventa o No-show según la operación de la estadía.</p></div>:null}
  </div><footer className={s.drawerFooter}><div><button className={s.dangerLink} onClick={onDiscard}>Descartar</button>{drawerStep>0?<button onClick={()=>setDrawerStep(step=>Math.max(0,step-1))}>Atrás</button>:null}</div><div className={s.totalFooter}><span><small>Total</small><b>{money(total,draft.currency)}</b></span>{drawerStep<3?<button className={s.primary} disabled={drawerStep===1&&(hasInvalidSelection||!selectedRoomIds.length)} onClick={onNext}>Continuar</button>:<button className={s.primary} disabled={saving||hasInvalidSelection} onClick={event=>{if(event.currentTarget.disabled)return;event.currentTarget.disabled=true;onSave()}}>{saving?"Creando…":"Crear reserva"}</button>}</div></footer></aside></div>
}
