"use client"

import s from"./planning.module.css"

const DAY=86400000
const fromKey=value=>{const[y,m,d]=String(value).split("-").map(Number);return new Date(y,m-1,d,12)}
const pad=value=>String(value).padStart(2,"0")
const keyFromDate=date=>`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`
const addDays=(value,amount)=>keyFromDate(new Date(fromKey(value).getTime()+amount*DAY))
const diffDays=(a,b)=>Math.round((fromKey(b)-fromKey(a))/DAY)
const longDate=value=>new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",year:"numeric"}).format(fromKey(value)).replace(".","")
const money=(value,currency="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:0}).format(Number(value)||0)
const STATUS_LABEL={alojado:"Alojado",confirmada:"Confirmada",tentativa:"Tentativa",pendiente:"Pendiente",finalizada:"Finalizada"}
const STEPS=["Fecha","Habitación","Titular","Detalles"]

export function ReservationDetailDrawer({selected,room,onClose,onOpen}){
  if(!selected)return null
  return <aside className={s.detailDrawer}><header><div><small>{selected.canal_reserva||"Directa"} · {selected.numero_reserva||selected.id}</small><h2>{selected.nombre_huesped}</h2><p>Habitación {room?.nombre||"—"}</p></div><button className={s.close} onClick={onClose}>×</button></header><div className={s.detailGrid}><div><small>Llegada</small><b>{longDate(selected.fecha_entrada)}</b></div><div><small>Salida</small><b>{longDate(selected.fecha_salida)}</b></div><div><small>Noches</small><b>{Math.max(1,diffDays(selected.fecha_entrada,selected.fecha_salida))}</b></div><div><small>Estado</small><b>{STATUS_LABEL[selected.estado]||selected.estado}</b></div><div><small>Huéspedes</small><b>{selected.cantidad_huespedes||1}</b></div><div><small>Total</small><b>{money(selected.precio_total,selected.moneda)}</b></div></div>{selected.telefono_huesped||selected.email_huesped?<div className={s.contactBlock}>{selected.telefono_huesped?<p><small>Teléfono</small><b>{selected.telefono_huesped}</b></p>:null}{selected.email_huesped?<p><small>Email</small><b>{selected.email_huesped}</b></p>:null}</div>:null}{selected.notas?<div className={s.noteBlock}><small>Notas</small><p>{selected.notas}</p></div>:null}<footer><button onClick={onClose}>Cerrar</button><button className={s.primary} onClick={onOpen}>Abrir reserva</button></footer></aside>
}

export function CreateReservationDrawer({draft,setDraft,drawerStep,setDrawerStep,draftState,availableRooms,roomById,nights,total,saving,onClose,onDiscard,onNext,onSave}){
  if(!draft)return null
  return <div className={s.drawerShade} onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside className={s.createDrawer} role="dialog" aria-modal="true" aria-label="Crear reserva"><header className={s.drawerHeader}><div><small>CREAR RESERVA</small><h2>{drawerStep===0?"Elegí las fechas":drawerStep===1?"Seleccioná habitación":drawerStep===2?"Datos del titular":"Revisá la reserva"}</h2><p>{draftState}</p></div><button className={s.close} onClick={onClose}>×</button></header><nav className={s.stepNav}>{STEPS.map((step,index)=><button key={step} className={index===drawerStep?s.stepActive:index<drawerStep?s.stepDone:""} onClick={()=>index<=drawerStep&&setDrawerStep(index)}><span>{index+1}</span>{step}</button>)}</nav><div className={s.drawerBody}>
    {drawerStep===0?<div className={s.stepPanel}><div className={s.dateSummary}><span><small>Entrada</small><b>{longDate(draft.start)}</b></span><span className={s.nightsBadge}>{nights} noche{nights===1?"":"s"}</span><span><small>Salida</small><b>{longDate(draft.end)}</b></span></div><div className={s.formGrid}><label>Entrada<input type="date" value={draft.start} onChange={event=>setDraft(current=>({...current,start:event.target.value,end:current.end<=event.target.value?addDays(event.target.value,1):current.end}))}/></label><label>Salida<input type="date" min={addDays(draft.start,1)} value={draft.end} onChange={event=>setDraft(current=>({...current,end:event.target.value}))}/></label><label>Huéspedes<input type="number" min="1" value={draft.guests} onChange={event=>setDraft(current=>({...current,guests:Number(event.target.value)||1}))}/></label><label>Moneda<select value={draft.currency} onChange={event=>setDraft(current=>({...current,currency:event.target.value}))}><option value="ARS">ARS</option><option value="USD">USD</option></select></label></div><p className={s.stepHelp}>También podés marcar un rango directamente sobre una fila del Planning: arrastrá desde la entrada hasta la salida.</p></div>:null}
    {drawerStep===1?<div className={s.stepPanel}><div className={s.roomOptions}>{availableRooms.map(room=><button key={room.id} disabled={!room.available||room.estado==="mantenimiento"} className={`${s.roomOption} ${String(draft.roomId)===String(room.id)?s.roomOptionActive:""}`} onClick={()=>setDraft(current=>({...current,roomId:String(room.id),rate:Number(room.precio)||current.rate}))}><span><small>{room.tipo||"Sin tipo"}</small><b>{room.nombre}</b><em>{room.capacidad||1} pax · {room.available?"Disponible":"Ocupada"}</em></span><strong>{money(room.precio,draft.currency)}<small>/ noche</small></strong></button>)}</div><label className={s.rateField}>Tarifa por noche<input type="number" min="0" value={draft.rate} onChange={event=>setDraft(current=>({...current,rate:Number(event.target.value)||0}))}/></label></div>:null}
    {drawerStep===2?<div className={s.stepPanel}><div className={s.formGrid}><label>Nombre<input value={draft.firstName} onChange={event=>setDraft(current=>({...current,firstName:event.target.value}))} autoFocus/></label><label>Apellido<input value={draft.lastName} onChange={event=>setDraft(current=>({...current,lastName:event.target.value}))}/></label><label>Teléfono<input value={draft.phone} onChange={event=>setDraft(current=>({...current,phone:event.target.value}))} placeholder="11 0000 0000"/></label><label>Email<input type="email" value={draft.email} onChange={event=>setDraft(current=>({...current,email:event.target.value}))} placeholder="huesped@email.com"/></label></div></div>:null}
    {drawerStep===3?<div className={s.stepPanel}><div className={s.review}><div><small>Estadía</small><b>{longDate(draft.start)} — {longDate(draft.end)}</b><span>{nights} noche{nights===1?"":"s"}</span></div><div><small>Habitación</small><b>{roomById.get(Number(draft.roomId))?.nombre||"—"}</b><span>{roomById.get(Number(draft.roomId))?.tipo||""}</span></div><div><small>Titular</small><b>{`${draft.firstName} ${draft.lastName}`.trim()||"Sin completar"}</b><span>{draft.phone||draft.email||"Sin contacto"}</span></div><div><small>Total</small><b>{money(total,draft.currency)}</b><span>{money(draft.rate,draft.currency)} × {nights}</span></div></div><div className={s.formGrid}><label>Canal<select value={draft.channel} onChange={event=>setDraft(current=>({...current,channel:event.target.value}))}><option>Directa</option><option>Motor</option><option>Booking.com</option><option>Expedia</option><option>Despegar</option><option>Airbnb</option><option>Agencia</option></select></label><label>Estado<select value={draft.status} onChange={event=>setDraft(current=>({...current,status:event.target.value}))}><option value="confirmada">Confirmada</option><option value="pendiente">Pendiente</option><option value="tentativa">Tentativa</option></select></label><label className={s.fullField}>Notas<textarea rows="4" value={draft.notes} onChange={event=>setDraft(current=>({...current,notes:event.target.value}))} placeholder="Pedidos, observaciones o información interna"/></label></div></div>:null}
  </div><footer className={s.drawerFooter}><div><button className={s.dangerLink} onClick={onDiscard}>Descartar</button>{drawerStep>0?<button onClick={()=>setDrawerStep(step=>Math.max(0,step-1))}>Atrás</button>:null}</div><div className={s.totalFooter}><span><small>Total</small><b>{money(total,draft.currency)}</b></span>{drawerStep<3?<button className={s.primary} onClick={onNext}>Continuar</button>:<button className={s.primary} disabled={saving} onClick={onSave}>{saving?"Creando…":"Crear reserva"}</button>}</div></footer></aside></div>
}
