"use client"

import{useEffect,useState}from"react"
import{useParams}from"next/navigation"
import{supabase}from"../../../lib/supabase"
import HospitalityShell from"../../components/hospitality/HospitalityShell"
import SignaturePad from"./SignaturePad"
import ui from"./checkin.module.css"

const emptyForm={phone:"",document_type:"DNI",document:"",address:"",province:"",country:"Argentina",arrival_time:"",vehicles:0,vehicle_type:"",vehicle_plate:"",pets:[],companions:[],breakfast:false,parking:false,transfer:false,early_checkin:false,late_checkout:false,bed_preference:"",food_preferences:"",accessibility_needs:"",stay_notes:""}
function Choice({active,onClick,title,text}){return <button type="button" className={ui.choice} data-active={active?"true":"false"} onClick={onClick}><span>{active?"✓":"+"}</span><div><b>{title}</b><small>{text}</small></div></button>}
function DocumentSlot({side,label,state,busy,onPick}){return <label className={ui.upload} data-ready={state?"true":"false"} data-busy={busy?"true":"false"}><span>{busy?"…":state?"✓":"↑"}</span><div><b>{label}</b><small>{busy?"Subiendo de forma segura…":state?"Recibido · pendiente de validación":"JPG, PNG o PDF · hasta 5 MB"}</small></div><input type="file" accept="image/jpeg,image/png,application/pdf" disabled={busy||Boolean(state)} onChange={e=>{const file=e.target.files?.[0];if(file)onPick(side,file);e.target.value=""}}/></label>}

export default function WebCheckinPage(){
  const{token}=useParams(),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[done,setDone]=useState(false),[signature,setSignature]=useState(""),[consent,setConsent]=useState(false),[form,setForm]=useState(emptyForm),[docs,setDocs]=useState({front:null,back:null}),[docBusy,setDocBusy]=useState("")
  useEffect(()=>{if(!token)return;(async()=>{const{data:result,error:rpcError}=await supabase.rpc("hl_get_web_checkin",{p_token:String(token)});if(rpcError||!result?.ok){setError(rpcError?.message||result?.error||"No pudimos abrir este check-in.");setLoading(false);return}setData(result);const r=result.reservation||{};setForm({...emptyForm,phone:r.phone||"",document:r.document||"",address:r.address||"",province:r.province||"",country:r.country||"Argentina",arrival_time:r.arrival_time||"",vehicles:Number(r.vehicles||0),vehicle_type:r.vehicle_type||"",vehicle_plate:r.vehicle_plate||"",pets:Array.isArray(r.pets)?r.pets:[],companions:Array.isArray(r.companions)?r.companions:[]});setLoading(false)})()},[token])
  function set(key,value){setForm(x=>({...x,[key]:value}))}
  function addCompanion(){setForm(x=>({...x,companions:[...x.companions,{nombre:"",dni:""}]}))}
  function setCompanion(i,key,value){setForm(x=>({...x,companions:x.companions.map((p,j)=>j===i?{...p,[key]:value}:p)}))}
  async function uploadDocument(side,file){setDocBusy(side);setError("");try{const body=new FormData();body.append("side",side);body.append("file",file);const response=await fetch(`/api/public/check-in/${encodeURIComponent(String(token))}/document`,{method:"POST",body}),result=await response.json().catch(()=>({}));if(!response.ok||!result?.ok)throw new Error(result?.error||"No pudimos subir el documento.");setDocs(current=>({...current,[side]:result}))}catch(err){setError(err?.message||"No pudimos subir el documento.")}finally{setDocBusy("")}}
  async function submit(e){e.preventDefault();if(!consent){setError("Necesitamos tu aceptación para completar el registro.");return}if(!signature){setError("Falta la firma del huésped principal.");return}setLoading(true);setError("");const payload={...form,identity_document_uploaded:Boolean(docs.front||docs.back),identity_document_sides:Object.keys(docs).filter(key=>docs[key])},{data:result,error:rpcError}=await supabase.rpc("hl_submit_web_checkin",{p_token:String(token),p_payload:payload,p_signature_name:data?.reservation?.guest_name||"Huésped",p_signature_data:signature});setLoading(false);if(rpcError||!result?.ok){setError(rpcError?.message||result?.error||"No pudimos guardar el check-in.");return}setDone(true)}
  const hotel=data?.hotel||{},r=data?.reservation||{}
  return <HospitalityShell eyebrow="WEB CHECK-IN" hotelName={hotel.hotel_name||"Habitación Llena"} title={done?"Todo listo para tu llegada.":`Bienvenido${r.guest_name?`, ${r.guest_name.split(" ")[0]}`:""}.`} copy={done?"Recepción ya tiene tus datos, preferencias y pedidos. Cuando llegues, solo tendremos que recibirte.":"Completá tus datos y preferencias antes de llegar para que recepción se ocupe sólo de las excepciones."}>
    {loading&&!data?<div className={ui.loading}>Preparando tu llegada…</div>:error&&!data?<div className={ui.error}>{error}</div>:done?<div className={ui.status}><b>Check-in online completado.</b><br/>Guardamos tus datos y pedidos para la estadía del {r.arrival}. Los servicios solicitados quedan sujetos a confirmación del alojamiento.</div>:<form className={ui.card} onSubmit={submit}>
      <div className={ui.stay}><div><small>LLEGADA</small><b>{r.arrival||"—"}</b></div><div><small>SALIDA</small><b>{r.departure||"—"}</b></div><div><small>HABITACIÓN</small><b>{r.room||"Asignación pendiente"}</b></div><div><small>HOTEL</small><b>{hotel.hotel_name||"Tu hotel"}</b></div></div>
      <section className={ui.section}><div><span className={ui.eyebrow}>DATOS DEL HUÉSPED</span><h2>Dejanos todo preparado.</h2><p className={ui.sectionCopy}>Estos datos evitan volver a completar formularios al llegar.</p></div><div className={ui.grid}><label className={ui.field}>Teléfono<input value={form.phone} onChange={e=>set("phone",e.target.value)} required/></label><label className={ui.field}>Tipo de documento<select value={form.document_type} onChange={e=>set("document_type",e.target.value)}><option>DNI</option><option>Pasaporte</option><option>CUIT</option><option>Otro</option></select></label><label className={ui.field}>Número de documento<input value={form.document} onChange={e=>set("document",e.target.value)} required/></label><label className={ui.field}>Hora aproximada de llegada<input type="time" value={form.arrival_time} onChange={e=>set("arrival_time",e.target.value)}/></label><label className={`${ui.field} ${ui.wide}`}>Dirección<input value={form.address} onChange={e=>set("address",e.target.value)}/></label><label className={ui.field}>Provincia / Estado<input value={form.province} onChange={e=>set("province",e.target.value)}/></label><label className={ui.field}>País<input value={form.country} onChange={e=>set("country",e.target.value)}/></label></div><div className={ui.documentBox}><div className={ui.documentHead}><span>◎</span><div><b>Documento de identidad</b><small>Podés adelantar frente y dorso. Se guardan en un espacio privado del alojamiento y recepción los verá como “pendiente de validación”; subirlos no significa que ya estén aprobados.</small></div></div><div className={ui.uploadGrid}><DocumentSlot side="front" label="Frente" state={docs.front} busy={docBusy==="front"} onPick={uploadDocument}/><DocumentSlot side="back" label="Dorso" state={docs.back} busy={docBusy==="back"} onPick={uploadDocument}/></div></div></section>
      <section className={ui.section}><div><span className={ui.eyebrow}>ACOMPAÑANTES</span><h2>¿Quiénes viajan con vos?</h2></div><div className={ui.companions}>{form.companions.map((p,i)=><div className={ui.companion} key={i}><input placeholder="Nombre" value={p.nombre||""} onChange={e=>setCompanion(i,"nombre",e.target.value)}/><input placeholder="DNI / Pasaporte" value={p.dni||""} onChange={e=>setCompanion(i,"dni",e.target.value)}/><button type="button" aria-label="Quitar acompañante" onClick={()=>set("companions",form.companions.filter((_,j)=>j!==i))}>×</button></div>)}</div><button className={ui.secondary} type="button" onClick={addCompanion}>＋ Agregar acompañante</button></section>
      <section className={ui.section}><div><span className={ui.eyebrow}>TU ESTADÍA</span><h2>Pedí lo que puedas necesitar.</h2><p className={ui.sectionCopy}>Recepción verá estos pedidos antes de tu llegada y confirmará disponibilidad cuando corresponda.</p></div><div className={ui.choices}><Choice active={form.breakfast} onClick={()=>set("breakfast",!form.breakfast)} title="Desayuno" text="Quiero información o reserva"/><Choice active={form.parking} onClick={()=>set("parking",!form.parking)} title="Estacionamiento" text="Necesito un lugar para el vehículo"/><Choice active={form.transfer} onClick={()=>set("transfer",!form.transfer)} title="Traslado" text="Quiero coordinar llegada o salida"/><Choice active={form.early_checkin} onClick={()=>set("early_checkin",!form.early_checkin)} title="Early check-in" text="Me gustaría ingresar antes"/><Choice active={form.late_checkout} onClick={()=>set("late_checkout",!form.late_checkout)} title="Late checkout" text="Me gustaría salir más tarde"/></div></section>
      <section className={ui.section}><div><span className={ui.eyebrow}>PREFERENCIAS</span><h2>Ayudanos a recibirte mejor.</h2></div><div className={ui.grid}><label className={ui.field}>Preferencia de cama<select value={form.bed_preference} onChange={e=>set("bed_preference",e.target.value)}><option value="">Sin preferencia</option><option value="double">Matrimonial</option><option value="twin">Dos camas</option></select></label><label className={ui.field}>Alimentación<input value={form.food_preferences} onChange={e=>set("food_preferences",e.target.value)} placeholder="Ej. sin TACC, vegetariano"/></label><label className={`${ui.field} ${ui.wide}`}>Accesibilidad o necesidades especiales<textarea value={form.accessibility_needs} onChange={e=>set("accessibility_needs",e.target.value)} placeholder="Contanos sólo lo que sea útil para tu estadía."/></label><label className={`${ui.field} ${ui.wide}`}>Algo más que recepción deba saber<textarea value={form.stay_notes} onChange={e=>set("stay_notes",e.target.value)} placeholder="Cumpleaños, cuna, piso preferido, horario especial…"/></label></div></section>
      <section className={ui.section}><div><span className={ui.eyebrow}>LLEGADA</span><h2>Vehículo y mascotas.</h2></div><div className={ui.grid}><label className={ui.field}>Cantidad de vehículos<input type="number" min="0" value={form.vehicles} onChange={e=>set("vehicles",Number(e.target.value||0))}/></label><label className={ui.field}>Tipo de vehículo<input value={form.vehicle_type} onChange={e=>set("vehicle_type",e.target.value)}/></label><label className={ui.field}>Patente<input value={form.vehicle_plate} onChange={e=>set("vehicle_plate",e.target.value.toUpperCase())}/></label><label className={`${ui.field} ${ui.wide}`}>Mascotas / detalles<textarea value={form.pets.map(x=>x.name||x.descripcion||x).join(", ")} onChange={e=>set("pets",e.target.value?e.target.value.split(",").map(name=>({name:name.trim()})).filter(x=>x.name):[])}/></label></div></section>
      <section className={ui.section}><div><span className={ui.eyebrow}>REGISTRO</span><h2>Tu firma.</h2></div><SignaturePad onChange={setSignature}/><label className={ui.consent}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Confirmo que la información ingresada es correcta y autorizo al alojamiento a utilizarla para gestionar mi estadía de acuerdo con sus condiciones y política de privacidad.</span></label></section>{error&&<div className={ui.error}>{error}</div>}<button className={ui.submit} disabled={loading||Boolean(docBusy)}>{loading?"Guardando…":docBusy?"Esperando documento…":"Completar Web Check-in"}</button>
    </form>}
  </HospitalityShell>
}
