import LegalPage from"../legal/LegalPage"

export const metadata={title:"Términos | Habitación Llena",description:"Condiciones generales previstas para el uso de Habitación Llena."}

const sections=[
  {title:"El servicio",body:["Habitación Llena es una plataforma web para operación hotelera. Las funciones disponibles dependen del plan, la propiedad, las integraciones contratadas y el estado de cada módulo. Una función marcada como roadmap o disponible para configurar no se considera una integración productiva hasta que esté efectivamente conectada."]},
  {title:"Cuenta y usuarios",body:["Cada organización debe mantener actualizados sus usuarios, roles y permisos, proteger sus credenciales y retirar accesos cuando una persona deja de necesitar el sistema. Las acciones realizadas por usuarios autorizados pueden quedar registradas para trazabilidad y seguridad."],items:["No compartir contraseñas entre empleados.","Usar permisos mínimos necesarios para cada rol.","Informar accesos sospechosos o pérdida de credenciales."]},
  {title:"Responsabilidad operativa del hotel",body:["El PMS asiste la operación, pero las decisiones hoteleras siguen siendo responsabilidad del establecimiento: asignación de habitaciones, aceptación de reservas, tarifas, impuestos, cobros, documentación de huéspedes y cumplimiento de reglas locales."],items:["Revisar datos importados durante una migración.","Validar tarifas, inventario y restricciones antes del go-live.","Mantener procedimientos alternativos razonables para contingencias operativas."]},
  {title:"Integraciones externas",body:["Mercado Pago, ARCA, OTAs, servicios de correo, mensajería, cerraduras y otros terceros operan bajo sus propias condiciones y disponibilidad. Habitación Llena no controla caídas, cambios de API, certificaciones ni decisiones comerciales de esos proveedores."],items:["Una integración puede requerir credenciales, homologación o aprobación del tercero.","Los cargos del proveedor externo pueden ser independientes del plan de Habitación Llena.","No se debe interpretar “roadmap” como compromiso de fecha o disponibilidad garantizada."]},
  {title:"Pagos y contratación",body:["Precio, moneda, impuestos, período de prueba, límites de uso, renovación y condiciones de cancelación se definen en el plan, checkout u orden de servicio vigente. Las condiciones particulares de una contratación prevalecen sobre esta descripción general cuando exista una diferencia expresa."]},
  {title:"Uso aceptable",body:["No se permite usar el servicio para acceder a datos ajenos, vulnerar sistemas, distribuir código malicioso, eludir límites de seguridad, revender accesos no autorizados o tratar información de forma ilícita."],items:["No intentar superar el aislamiento entre propiedades.","No cargar secretos de terceros en campos no destinados a credenciales.","No utilizar automatizaciones para spam, fraude o actividades prohibidas."]},
  {title:"Disponibilidad y cambios",body:["El objetivo es ofrecer un servicio estable y seguro, pero ningún sistema online puede prometer disponibilidad absoluta. Se pueden realizar mantenimientos, correcciones y mejoras. Los cambios relevantes que afecten de forma material una contratación deberán gestionarse conforme al acuerdo aplicable."]},
  {title:"Propiedad intelectual y datos",body:["El software, diseño y documentación de Habitación Llena pertenecen a sus respectivos titulares. Los datos operativos cargados por el hotel siguen perteneciendo al hotel o a quien corresponda legalmente; el servicio obtiene únicamente los derechos necesarios para procesarlos y prestar la plataforma."],items:["La exportación o portabilidad se gestiona según capacidades técnicas y condiciones de contratación.","No se adquieren derechos sobre marcas, fotografías o contenidos del hotel por el solo hecho de alojarlos en el sistema."]},
  {title:"Marco contractual",body:["La identificación completa del prestador, domicilio, ley aplicable, jurisdicción, niveles de servicio y límites de responsabilidad se fijarán en los documentos de contratación correspondientes antes de operar comercialmente donde resulten exigibles."]},
]

export default function TermsPage(){return <LegalPage kicker="TÉRMINOS" title="Reglas claras para una operación crítica." intro="El PMS participa en una parte sensible del hotel. Por eso distinguimos qué hace la plataforma, qué depende del establecimiento y qué depende de proveedores externos." sections={sections}/>}
