"use client"

const xmlClean=value=>String(value??"").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,"")
const xmlEscape=value=>xmlClean(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;")
const htmlEscape=value=>String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")
const columnName=index=>{let n=index+1,out="";while(n){const r=(n-1)%26;out=String.fromCharCode(65+r)+out;n=Math.floor((n-1)/26)}return out}
const crcTable=(()=>{const table=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0}return table})()
const crc32=bytes=>{let c=0xffffffff;for(const byte of bytes)c=crcTable[(c^byte)&255]^(c>>>8);return(c^0xffffffff)>>>0}
const u16=n=>new Uint8Array([n&255,(n>>>8)&255]),u32=n=>new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])
const joinBytes=parts=>{const length=parts.reduce((sum,part)=>sum+part.length,0),out=new Uint8Array(length);let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length}return out}
function dosStamp(date=new Date()){const year=Math.max(1980,date.getFullYear()),time=(date.getHours()<<11)|(date.getMinutes()<<5)|(date.getSeconds()>>1),day=((year-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate();return{time,date:day}}
function zipStore(entries,encoder){const locals=[],centrals=[];let offset=0;const stamp=dosStamp(),flags=0x0800;for(const entry of entries){const name=encoder.encode(entry.name),data=encoder.encode(entry.content),crc=crc32(data),local=joinBytes([u32(0x04034b50),u16(20),u16(flags),u16(0),u16(stamp.time),u16(stamp.date),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);centrals.push(joinBytes([u32(0x02014b50),u16(20),u16(20),u16(flags),u16(0),u16(stamp.time),u16(stamp.date),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length}const body=joinBytes(locals),directory=joinBytes(centrals),end=joinBytes([u32(0x06054b50),u16(0),u16(0),u16(entries.length),u16(entries.length),u32(directory.length),u32(body.length),u16(0)]);return joinBytes([body,directory,end])}

export function downloadXlsx({fileName,title,subtitle,day,propertyName,columns,rows,totalText}){
  const encoder=new TextEncoder(),last=columnName(Math.max(columns.length-1,0)),headerRow=5,dataStart=6,totalRow=dataStart+rows.length,finalRow=totalText?totalRow:Math.max(headerRow,dataStart+rows.length-1)
  const shared=[],sharedMap=new Map();let sharedCount=0
  const sharedIndex=value=>{const text=xmlClean(value),known=sharedMap.get(text);sharedCount++;if(known!==undefined)return known;const index=shared.length;shared.push(text);sharedMap.set(text,index);return index}
  const excelCell=(ref,value,style=0)=>(value===null||value===undefined||value==="")?`<c r="${ref}" s="${style}"/>`:typeof value==="number"&&Number.isFinite(value)?`<c r="${ref}" t="n" s="${style}"><v>${value}</v></c>`:`<c r="${ref}" t="s" s="${style}"><v>${sharedIndex(value)}</v></c>`
  const noteIndex=columns.findIndex(column=>column.key==="note")
  const widths=columns.map(column=>{const values=rows.slice(0,100).map(row=>String(row[column.key]??"")),max=Math.max(column.label.length,...values.map(value=>value.length));if(column.key==="note")return 32;if(column.key==="guest")return Math.min(28,Math.max(20,max+2));if(column.key==="room")return Math.min(24,Math.max(14,max+2));return Math.min(24,Math.max(12,max+2))})
  const sheetRows=[`<row r="1" ht="27" customHeight="1">${excelCell("A1",title,3)}</row>`,`<row r="2" ht="20" customHeight="1">${excelCell("A2",subtitle,4)}</row>`,`<row r="3" ht="20" customHeight="1">${excelCell("A3",`${propertyName||"Propiedad"} · ${day}`,4)}</row>`,`<row r="${headerRow}" ht="24" customHeight="1">${columns.map((column,index)=>excelCell(`${columnName(index)}${headerRow}`,column.label,1)).join("")}</row>`]
  rows.forEach((row,index)=>{const excelRow=dataStart+index,note=noteIndex>=0?String(row[columns[noteIndex].key]??""):"",height=Math.min(72,Math.max(23,23+Math.max(0,Math.ceil(note.length/42)-1)*14));sheetRows.push(`<row r="${excelRow}" ht="${height}" customHeight="1">${columns.map((column,columnIndex)=>excelCell(`${columnName(columnIndex)}${excelRow}`,row[column.key]??"",column.key==="note"?5:0)).join("")}</row>`)})
  if(totalText)sheetRows.push(`<row r="${totalRow}" ht="25" customHeight="1">${excelCell(`A${totalRow}`,"TOTAL",2)}${columns.length>1?excelCell(`B${totalRow}`,totalText,2):""}</row>`)
  const mergeRefs=[`A1:${last}1`,`A2:${last}2`,`A3:${last}3`];if(totalText&&columns.length>2)mergeRefs.push(`B${totalRow}:${last}${totalRow}`)
  const cols=widths.map((width,index)=>`<col min="${index+1}" max="${index+1}" width="${width}" customWidth="1"/>`).join("")
  const worksheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:${last}${finalRow}"/><sheetViews><sheetView workbookViewId="0" showGridLines="1"><pane ySplit="5" topLeftCell="A6" activePane="bottomLeft" state="frozen"/><selection pane="bottomLeft" activeCell="A6" sqref="A6"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="15"/><cols>${cols}</cols><sheetData>${sheetRows.join("")}</sheetData><mergeCells count="${mergeRefs.length}">${mergeRefs.map(ref=>`<mergeCell ref="${ref}"/>`).join("")}</mergeCells><autoFilter ref="A${headerRow}:${last}${Math.max(headerRow,dataStart+rows.length-1)}"/><pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup orientation="landscape" paperSize="9" fitToWidth="1" fitToHeight="0"/></worksheet>`
  const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="3"><font><sz val="10"/><name val="Calibri"/><family val="2"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Calibri"/><family val="2"/></font><font><b/><color rgb="FF1F2A44"/><sz val="16"/><name val="Calibri"/><family val="2"/></font></fonts><fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF5B5FEF"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFEFF1FF"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border><left/><right/><top/><bottom/><diagonal/></border><border><left style="thin"><color rgb="FFDCE1EC"/></left><right style="thin"><color rgb="FFDCE1EC"/></right><top style="thin"><color rgb="FFDCE1EC"/></top><bottom style="thin"><color rgb="FFDCE1EC"/></bottom><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="6"><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1"><alignment vertical="top"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1"/><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`
  const sharedStrings=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="${sharedCount}" uniqueCount="${shared.length}">${shared.map(text=>`<si><t xml:space="preserve">${xmlEscape(text)}</t></si>`).join("")}</sst>`
  const contentTypes=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/></Types>`
  const entries=[
    {name:"[Content_Types].xml",content:contentTypes},
    {name:"_rels/.rels",content:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`},
    {name:"xl/workbook.xml",content:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><bookViews><workbookView xWindow="0" yWindow="0" windowWidth="24000" windowHeight="12000"/></bookViews><sheets><sheet name="Informe" sheetId="1" r:id="rId1"/></sheets><calcPr calcId="171027" calcMode="auto"/></workbook>`},
    {name:"xl/_rels/workbook.xml.rels",content:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/></Relationships>`},
    {name:"xl/styles.xml",content:styles},{name:"xl/sharedStrings.xml",content:sharedStrings},{name:"xl/worksheets/sheet1.xml",content:worksheet},
  ]
  const bytes=zipStore(entries,encoder),blob=new Blob([bytes],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=`${fileName}.xlsx`;anchor.type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)
}

export function printSheet({title,subtitle,day,propertyName,columns,rows,totalText}){
  const frame=document.createElement("iframe");frame.style.position="fixed";frame.style.width="1px";frame.style.height="1px";frame.style.right="0";frame.style.bottom="0";frame.style.opacity="0";frame.style.pointerEvents="none";document.body.appendChild(frame)
  const documentRef=frame.contentWindow?.document;if(!documentRef){frame.remove();return}
  const small=columns.length>7?"7.8px":"9.2px",colgroup=columns.map(column=>`<col${column.key==="note"?' class="noteCol"':""}>`).join(""),bodyRows=rows.map(row=>`<tr>${columns.map(column=>`<td${column.key==="note"?' class="noteCell"':""}>${htmlEscape(row[column.key]??"")}</td>`).join("")}</tr>`).join("")
  documentRef.open();documentRef.write(`<!doctype html><html><head><meta charset="utf-8"><title>${htmlEscape(title)}</title><style>@page{size:A4 landscape;margin:9mm}*{box-sizing:border-box}body{margin:0;color:#1f2a44;font-family:Arial,sans-serif}header{margin-bottom:12px}small{display:block;color:#5b5fef;font-weight:800;letter-spacing:.08em;font-size:9px}h1{margin:4px 0 3px;font-size:19px}p{margin:0;color:#67728a;font-size:9.5px}.meta{margin-top:5px;color:#4d5870;font-size:9px}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:${small}}col.noteCol{width:22%}thead{display:table-header-group}tr{break-inside:avoid}th{background:#5b5fef;color:white;text-align:left;font-weight:700;padding:6px 5px;border:1px solid #dce1ec;overflow-wrap:anywhere}td{padding:5px;border:1px solid #dce1ec;vertical-align:top;overflow-wrap:anywhere;word-break:break-word}td.noteCell{white-space:normal;line-height:1.35}tbody tr:nth-child(even){background:#f7f8fc}.total{margin-top:8px;padding:7px 9px;border:1px solid #cfd5f7;background:#eff1ff;font-size:9.5px;font-weight:800}.footer{margin-top:7px;color:#7b8498;font-size:8px;text-align:right}</style></head><body><header><small>HABITACIÓN LLENA · INFORME DE RECEPCIÓN</small><h1>${htmlEscape(title)}</h1><p>${htmlEscape(subtitle)}</p><div class="meta">${htmlEscape(propertyName||"Propiedad")} · ${htmlEscape(day)}</div></header><table><colgroup>${colgroup}</colgroup><thead><tr>${columns.map(column=>`<th>${htmlEscape(column.label)}</th>`).join("")}</tr></thead><tbody>${bodyRows||`<tr><td colspan="${columns.length}">No hay datos para esta fecha.</td></tr>`}</tbody></table>${totalText?`<div class="total">TOTAL · ${htmlEscape(totalText)}</div>`:""}<div class="footer">Generado desde Habitación Llena</div></body></html>`);documentRef.close()
  const cleanup=()=>setTimeout(()=>frame.remove(),300);frame.contentWindow.onafterprint=cleanup;setTimeout(()=>{frame.contentWindow?.focus();frame.contentWindow?.print();setTimeout(cleanup,3000)},180)
}
