"use client"

import{useEffect,useMemo,useState}from"react"
import{
  loadMaintenanceWorkspace,subscribeMaintenanceWorkspace,saveMaintenanceTicket,setMaintenanceTicketStatus,
  saveMaintenanceAsset,saveMaintenanceVendor,saveMaintenancePlan,createTicketFromPlan,
}from"../../services/maintenanceWorkspace"
import s from"./maintenance-premium.module.css"
import polish from"./maintenance-readable.module.css"
import{AssetsView,PlansView,VendorsView}from"./MaintenanceViews"
import TicketDrawer from"./MaintenanceDrawer"
import{AssetModal,PlanModal,VendorModal}from"./MaintenanceModals"
import{PRIORITY,STATUS,TERMINAL,addDays,dateLabel,money,priorityTone,roomName,staffName,statusTone,ticketTotal,today}from"./maintenanceUtils"

function Icon({name,size=18}){const p={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:"1.8",strokeLinecap:"round",strokeLinejoin:"round","aria-hidden":true};if(name==="plus")return <svg {...p}><path d="M12 5v14M5 12h14"/></svg>;if(name==="search")return <svg {...p}><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>;return <svg {...p}><circle cx="12" cy="12" r="8"/><path d="M12 8v5M12 16h.01"/></svg>}
function Pill({tone="neutral",children}){return <span className={s.pill} data-tone={tone}>{children}</span>}
function Empty({children}){return <div className={s.empty}>{children}</div>}

export default function MaintenancePremium({propertyId,rooms=[],reservations=[]}){
  const[data,setData]=useState({tickets:[],assets:[],vendors:[],plans:[],events:[],staff:[]}),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[tab,setTab]=useState("board"),[filter,setFilter]=useState("active"),[query,setQuery]=useState(""),[editor,setEditor]=useState(null),[assetEditor,setAssetEditor]=useState(null),[vendorEditor,setVendorEditor]=useState(null),[planEditor,setPlanEditor]=useState(null),[busy,setBusy]=useState(false)
  async function refresh(){if(!propertyId)return;try{const next=await loadMaintenanceWorkspace({propertyId});setData(next);setMessage("")}catch(error){setMessage(error.message||"No pudimos cargar Mantenimiento.")}finally{setLoading(false)}}
  useEffect(()=>{refresh();if(!propertyId)return;return subscribeMaintenanceWorkspace({propertyId,onChange:()=>refresh()})},[propertyId])
  const activeTickets=data.tickets.filter(t=>!TERMINAL.has(String(t.status||"").toLowerCase())),overdue=activeTickets.filter(t=>t.due_at&&new Date(t.due_at)<new Date()),blocked=activeTickets.filter(t=>t.blocks_inventory),costMonth=data.tickets.filter(t=>String(t.updated_at||t.created_at||"").startsWith(today().slice(0,7))).reduce((sum,t)=>sum+ticketTotal(t),0)
  const arrivalAlerts=useMemo(()=>activeTickets.flatMap(ticket=>{if(!ticket.room_id)return[];const next=reservations.filter(r=>r.estado!=="cancelada"&&!r.no_show&&[r.habitacion_id,...(Array.isArray(r.habitaciones_ids)?r.habitaciones_ids:[])].some(id=>String(id)===String(ticket.room_id))&&r.fecha_entrada>=today()&&r.fecha_entrada<=addDays(today(),2)).sort((a,b)=>String(a.fecha_entrada).localeCompare(String(b.fecha_entrada)))[0];return next?[{ticket,reservation:next}]:[]}),[activeTickets,reservations])
  const mttr=useMemo(()=>{const done=data.tickets.filter(t=>t.started_at&&t.completed_at),hours=done.map(t=>(new Date(t.completed_at)-new Date(t.started_at))/3600000).filter(v=>v>=0);return hours.length?hours.reduce((a,b)=>a+b,0)/hours.length:0},[data.tickets])
  const filteredTickets=useMemo(()=>data.tickets.filter(t=>{const active=!TERMINAL.has(String(t.status||"").toLowerCase()),filterOk=filter==="all"||filter==="active"&&active||filter==="urgent"&&["urgent","high"].includes(t.priority)||filter==="blocked"&&t.blocks_inventory||filter==="closed"&&!active,text=`${t.title||""} ${t.description||""} ${roomName(rooms,t.room_id)} ${STATUS[t.status]||t.status}`.toLowerCase();return filterOk&&(!query||text.includes(query.toLowerCase()))}),[data.tickets,filter,query,rooms])
  const visibleStatuses=filter==="closed"?["resolved","verified","closed"]:filter==="all"?["open","assigned","in_progress","waiting_parts","waiting_vendor","resolved","verified","closed"]:["open","assigned","in_progress","waiting_parts","waiting_vendor","resolved"]
  const statusColumns=visibleStatuses.map(status=>({status,items:filteredTickets.filter(t=>t.status===status)}))
  const openNew=(preset={})=>setEditor({title:"",description:"",priority:"normal",status:"open",room_id:"",asset_id:"",vendor_id:"",assigned_to:"",due_at:"",estimated_minutes:"",blocks_inventory:false,labor_cost:0,material_cost:0,external_cost:0,parts:[],checklist:[],photos:[],notes:"",...preset})
  async function saveTicket(draft){setBusy(true);try{const saved=await saveMaintenanceTicket({propertyId,draft});await refresh();setEditor(saved);setMessage("Orden guardada.")}catch(error){setMessage(error.message||"No se pudo guardar la orden.")}finally{setBusy(false)}}
  async function changeStatus(ticket,status){setBusy(true);try{await setMaintenanceTicketStatus({propertyId,ticket,status});await refresh();setEditor(x=>x?.id===ticket.id?{...x,status}:x);setMessage(`Orden ${STATUS[status]?.toLowerCase()||status}.`)}catch(error){setMessage(error.message||"No se pudo cambiar el estado.")}finally{setBusy(false)}}
  async function createPreventive(plan){setBusy(true);try{const created=await createTicketFromPlan({propertyId,plan});await refresh();setEditor(created);setTab("board");setMessage("Orden preventiva creada.")}catch(error){setMessage(error.message||"No se pudo crear la orden preventiva.")}finally{setBusy(false)}}
  if(loading)return <div className={s.loading}>Preparando Mantenimiento…</div>
  return <div className={`${s.page} ${polish.page}`}>
    <header className={s.hero}><div><small>MANTENIMIENTO</small><h2>Operación técnica</h2></div><button className={s.primary} onClick={()=>openNew()}><Icon name="plus" size={17}/>Nueva orden</button></header>
    <section className={s.kpis}><article><small>ABIERTAS</small><b>{activeTickets.length}</b><span>{overdue.length} vencidas</span></article><article><small>URGENTES</small><b>{activeTickets.filter(t=>["urgent","high"].includes(t.priority)).length}</b><span>prioridad alta</span></article><article><small>FUERA DE VENTA</small><b>{blocked.length}</b><span>bloqueadas</span></article><article title="Tiempo medio desde inicio hasta resolución"><small>MTTR</small><b>{mttr?`${mttr.toFixed(1)} h`:"—"}</b><span>resolución media</span></article><article><small>COSTO DEL MES</small><b>{money(costMonth)}</b><span>acumulado</span></article></section>
    {message&&<div className={s.notice}>{message}</div>}
    {arrivalAlerts.length>0&&<section className={s.alertRail}><div><small>RIESGO OPERATIVO</small><b>{arrivalAlerts.length} llegada(s) próxima(s) con mantenimiento abierto</b></div><div className={s.alertChips}>{arrivalAlerts.slice(0,6).map(x=><button key={x.ticket.id} onClick={()=>setEditor(x.ticket)}>Hab. {roomName(rooms,x.ticket.room_id)} · {x.reservation.fecha_entrada}</button>)}</div></section>}
    <nav className={s.tabs}><button data-active={tab==="board"} onClick={()=>setTab("board")}>Órdenes</button><button data-active={tab==="plans"} onClick={()=>setTab("plans")}>Preventivos <span>{data.plans.filter(p=>p.active).length}</span></button><button data-active={tab==="assets"} onClick={()=>setTab("assets")}>Activos <span>{data.assets.filter(a=>a.active).length}</span></button><button data-active={tab==="vendors"} onClick={()=>setTab("vendors")}>Proveedores</button></nav>
    {tab==="board"&&<><section className={s.toolbar}><div className={s.filters}>{[["active","Activas"],["urgent","Urgentes"],["blocked","Fuera de venta"],["closed","Cerradas"],["all","Todas"]].map(([id,label])=><button key={id} data-active={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div><label style={{position:"relative",display:"flex",alignItems:"center"}}><span style={{position:"absolute",left:11,display:"grid",placeItems:"center",pointerEvents:"none",opacity:.58}}><Icon name="search" size={16}/></span><input style={{paddingLeft:34}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar orden o habitación"/></label></section><section className={s.board} style={{gridTemplateColumns:`repeat(${statusColumns.length},minmax(210px,1fr))`}}>{statusColumns.map(col=><div className={s.column} key={col.status}><header><span><i data-tone={statusTone(col.status)}/><b>{STATUS[col.status]}</b></span><em>{col.items.length}</em></header><div className={s.cards}>{col.items.map(ticket=><button className={s.ticket} key={ticket.id} onClick={()=>setEditor(ticket)}><div className={s.ticketTop}><Pill tone={priorityTone(ticket.priority)}>{PRIORITY[ticket.priority]||ticket.priority}</Pill>{ticket.blocks_inventory&&<Pill tone="danger">FUERA DE VENTA</Pill>}</div><h3>{ticket.title}</h3><p>{ticket.description||"Sin detalle."}</p><div className={s.ticketMeta}><span>Hab. {roomName(rooms,ticket.room_id)}</span><span>{staffName(data.staff,ticket.assigned_to)}</span></div><footer><span>{ticket.due_at?dateLabel(ticket.due_at):"Sin vencimiento"}</span><b>{money(ticketTotal(ticket))}</b></footer></button>)}{!col.items.length&&<Empty>Sin órdenes</Empty>}</div></div>)}</section></>}
    {tab==="plans"&&<PlansView plans={data.plans} assets={data.assets} vendors={data.vendors} rooms={rooms} staff={data.staff} onEdit={setPlanEditor} onNew={()=>setPlanEditor({title:"",description:"",frequency_unit:"month",frequency_value:1,next_due_date:addDays(today(),30),priority:"normal",asset_id:"",room_id:"",assigned_to:"",vendor_id:"",estimated_minutes:"",checklist:[],active:true})} onCreateTicket={createPreventive}/>} 
    {tab==="assets"&&<AssetsView assets={data.assets} rooms={rooms} tickets={data.tickets} onEdit={setAssetEditor} onNew={()=>setAssetEditor({name:"",category:"equipment",room_id:"",brand:"",model:"",serial_number:"",location:"",status:"active",purchase_date:"",warranty_until:"",expected_life_months:"",notes:"",active:true})}/>} 
    {tab==="vendors"&&<VendorsView vendors={data.vendors} tickets={data.tickets} onEdit={setVendorEditor} onNew={()=>setVendorEditor({name:"",service_type:"",contact_name:"",phone:"",email:"",notes:"",active:true})}/>} 
    {editor&&<TicketDrawer ticket={editor} rooms={rooms} assets={data.assets} vendors={data.vendors} staff={data.staff} events={data.events.filter(e=>e.ticket_id===editor.id)} busy={busy} onClose={()=>setEditor(null)} onSave={saveTicket} onStatus={changeStatus} onRefresh={refresh} propertyId={propertyId}/>} 
    {assetEditor&&<AssetModal draft={assetEditor} rooms={rooms} busy={busy} onClose={()=>setAssetEditor(null)} onSave={async draft=>{setBusy(true);try{await saveMaintenanceAsset({propertyId,draft});await refresh();setAssetEditor(null);setMessage("Activo guardado.")}catch(e){setMessage(e.message)}finally{setBusy(false)}}}/>} 
    {vendorEditor&&<VendorModal draft={vendorEditor} busy={busy} onClose={()=>setVendorEditor(null)} onSave={async draft=>{setBusy(true);try{await saveMaintenanceVendor({propertyId,draft});await refresh();setVendorEditor(null);setMessage("Proveedor guardado.")}catch(e){setMessage(e.message)}finally{setBusy(false)}}}/>} 
    {planEditor&&<PlanModal draft={planEditor} rooms={rooms} assets={data.assets} vendors={data.vendors} staff={data.staff} busy={busy} onClose={()=>setPlanEditor(null)} onSave={async draft=>{setBusy(true);try{await saveMaintenancePlan({propertyId,draft});await refresh();setPlanEditor(null);setMessage("Preventivo guardado.")}catch(e){setMessage(e.message)}finally{setBusy(false)}}}/>} 
  </div>
}
