"use client"

import{useCallback,useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import PmsIcon from"../../components/shell/PmsIcons"
import usePmsAutoRefresh from"../../core/usePmsAutoRefresh"
import useOperationsControlData from"./useOperationsControlData"
import s from"./operationsControl.module.css"

const CLOSED_REVISION=new Set(["cancelled","canceled","cancelada","anulada"])
const ACTIONABLE_CHANNEL=new Set(["overbooked","partial","unassigned"])
const norm=value=>String(value||"").trim().toLowerCase()
const todayKey=()=>new Date().toLocaleDateString("en-CA")
const tomorrowKey=()=>{const d=new Date();d.setDate(d.getDate()+1);return d.toLocaleDateString("en-CA")}
const formatDate=value=>{if(!value)return"";try{return new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short"}).format(new Date(`${value}T12:00:00`)).replace(".","")}catch{return value}}
const money=(value,currency="ARS")=>{try{return new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:0}).format(Number(value)||0)}catch{return`${currency||"ARS"} ${Math.round(Number(value)||0)}`}}
const relative=value=>{if(!value)return"Sin registro reciente";const ms=Date.now()-new Date(value).getTime();if(!Number.isFinite(ms))return"Sin registro reciente";const min=Math.max(0,Math.round(ms/60000));if(min<2)return"Ahora";if(min<60)return`Hace ${min} min`;const h=Math.round(min/60);if(h<24)return`Hace ${h} h`;return`Hace ${Math.round(h/24)} d`}
const guestName=item=>item?.nombre_huesped||item?.numero_reserva||"Huésped"
const roomLabel=item=>item?.roomNames?.length?item.roomNames.join(", "):"Sin habitación"

function toneRank(tone){return tone==="red"?0:tone==="yellow"?1:tone==="blue"?2:3}
function signalTone(notification){const meta=notification?.metadata&&typeof notification.metadata==="object"?notification.metadata:{};if(meta.severity==="critical"||meta.requires_action)return"red";const event=norm(notification?.event_type);if(event==="booking_new"||event==="booking_cancelled")return"yellow";return"blue"}
function signalDetail(notification){const meta=notification?.metadata&&typeof notification.metadata==="object"?notification.metadata:{},bits=[notification?.provider_name||meta.provider||"OTA",meta.guest_name,meta.reservation_number?`Reserva ${meta.reservation_number}`:"",meta.arrival_date&&meta.departure_date?`${formatDate(meta.arrival_date)} → ${formatDate(meta.departure_date)}`:""];return bits.filter(Boolean).join(" · ")||notification?.detail||"Actualización recibida"}
function dateTime(date,time){if(!date||!time)return null;const clean=String(time).trim().slice(0,5);const d=new Date(`${date}T${/^\d{2}:\d{2}$/.test(clean)?clean:"12:00"}:00`);return Number.isNaN(d.getTime())?null:d}
function eventTime(item,kind){const value=kind==="arrival"?item?.hora_llegada_estimada:item?.hora_salida_estimada;return value?String(value).slice(0,5):"Horario pendiente"}

function MetricCard({icon,label,value,note,tone="blue",onClick}){const Tag=onClick?"button":"article";return <Tag type={onClick?"button":undefined} className={s.metric} data-tone={tone} onClick={onClick}><span className={s.metricIcon}><PmsIcon name={icon} size={19}/></span><div><small>{label}</small><b>{value}</b><span>{note}</span></div>{onClick?<em>›</em>:null}</Tag>}
function StatusLight({tone="green",label}){return <span className={s.statusLight} data-tone={tone}><i/><b>{label}</b></span>}
function Empty({title,text}){return <div className={s.empty}><span>✓</span><div><b>{title}</b><small>{text}</small></div></div>}

export default function OperationsControlWorkspace({propertyId,property,onNavigate,allowedViews=[]}){
  const data=useOperationsControlData(propertyId),m=data.metrics,[notifications,setNotifications]=useState([]),[hub,setHub]=useState(null),[channelStates,setChannelStates]=useState([]),[healthLoading,setHealthLoading]=useState(true),[healthError,setHealthError]=useState(""),[slow,setSlow]=useState(false)
  const allowed=useMemo(()=>new Set(allowedViews),[allowedViews]),can=id=>!allowed.size||allowed.has(id)
  const loadHealth=useCallback(async()=>{if(!propertyId)return;setHealthLoading(true);setHealthError("");try{const since=new Date(Date.now()-48*3600000).toISOString(),[noticeRes,hubRes,stateRes]=await Promise.all([
    supabase.from("hotel_operational_notifications").select("id,reservation_id,event_type,title,detail,provider_name,metadata,created_at").eq("property_id",propertyId).gte("created_at",since).order("created_at",{ascending:false}).limit(40),
    supabase.from("hotel_channel_hubs").select("id,provider,status,mode,external_property_id,diagnostics,last_sync_at,last_error,updated_at").eq("property_id",propertyId).eq("provider","channex").maybeSingle(),
    supabase.from("hotel_channel_booking_state").select("id,reservation_id,ota_reservation_code,channel_code,ota_name,assignment_status,overbooked,conflict_state,last_revision_status,updated_at").eq("property_id",propertyId).in("assignment_status",["overbooked","partial","unassigned"]).order("updated_at",{ascending:false}).limit(80),
  ]);if(noticeRes.error)throw noticeRes.error;if(hubRes.error)throw hubRes.error;if(stateRes.error)throw stateRes.error;setNotifications(noticeRes.data||[]);setHub(hubRes.data||null);setChannelStates(stateRes.data||[])}catch(err){setHealthError(err?.message||"No pudimos leer las señales de integraciones.")}finally{setHealthLoading(false)}},[propertyId])
  useEffect(()=>{loadHealth()},[loadHealth])
  usePmsAutoRefresh(propertyId,loadHealth,["hotel_operational_notifications","hotel_channel_hubs","hotel_channel_booking_state"])
  const loading=data.loading||healthLoading
  useEffect(()=>{if(!loading){setSlow(false);return}const timer=setTimeout(()=>setSlow(true),1400);return()=>clearTimeout(timer)},[loading])

  const current=data.operationsByOffset?.[0]||{arrivals:[],inhouse:[],departures:[]},tomorrow=data.operationsByOffset?.[1]||{arrivals:[],inhouse:[],departures:[]}
  const realOverbookings=useMemo(()=>channelStates.filter(row=>ACTIONABLE_CHANNEL.has(norm(row.assignment_status))&&norm(row.conflict_state)!=="mapping_required"&&!CLOSED_REVISION.has(norm(row.last_revision_status))&&(row.overbooked===true||norm(row.assignment_status)==="overbooked")),[channelStates])
  const mappingIssues=useMemo(()=>channelStates.filter(row=>norm(row.conflict_state)==="mapping_required"&&!CLOSED_REVISION.has(norm(row.last_revision_status))),[channelStates])
  const exceptions=useMemo(()=>{
    const list=[]
    for(const row of realOverbookings)list.push({id:`overbooking-${row.id}`,tone:"red",icon:"calendar",title:"Overbooking OTA sin resolver",detail:`${row.ota_name||row.channel_code||"OTA"}${row.ota_reservation_code?` · Reserva ${row.ota_reservation_code}`:""}`,target:"planning"})
    if(mappingIssues.length)list.push({id:"mapping",tone:"yellow",icon:"link",title:`${mappingIssues.length} mapeo${mappingIssues.length===1?"":"s"} de canal para revisar`,detail:"No es overbooking: falta relacionar correctamente una categoría o tarifa.",target:"channelmanager"})
    current.arrivals.filter(item=>item.roomMaintenance).forEach(item=>list.push({id:`arrival-maint-${item.id}`,tone:"red",icon:"wrench",title:"Llegada con habitación en mantenimiento",detail:`${guestName(item)} · ${roomLabel(item)}`,target:"reservations",reservationId:item.id}))
    current.arrivals.filter(item=>item.roomDirty&&!item.roomMaintenance).forEach(item=>list.push({id:`arrival-dirty-${item.id}`,tone:"yellow",icon:"clean",title:"Habitación pendiente antes del check-in",detail:`${guestName(item)} · ${roomLabel(item)}`,target:"housekeeping",reservationId:item.id}))
    current.departures.filter(item=>Number(item.balance)>0).forEach(item=>list.push({id:`departure-balance-${item.id}`,tone:"red",icon:"cash",title:"Salida con saldo pendiente",detail:`${guestName(item)} · ${money(item.balance,item.moneda)}`,target:"reservations",reservationId:item.id}))
    current.arrivals.filter(item=>!item.roomNames?.length).forEach(item=>list.push({id:`arrival-room-${item.id}`,tone:"yellow",icon:"booking",title:"Llegada sin habitación asignada",detail:`${guestName(item)} · check-in hoy`,target:"planning",reservationId:item.id}))
    if(Number(m.urgent)>0)list.push({id:"urgent-maintenance",tone:"red",icon:"wrench",title:`${m.urgent} mantenimiento${m.urgent===1?"":"s"} urgente${m.urgent===1?"":"s"}`,detail:"Hay órdenes prioritarias abiertas que pueden afectar la operación.",target:"maintenance"})
    return list.sort((a,b)=>toneRank(a.tone)-toneRank(b.tone)).slice(0,10)
  },[realOverbookings,mappingIssues,current.arrivals,current.departures,m.urgent])

  const hubInfo=useMemo(()=>{if(healthError)return{tone:"red",label:"Sin lectura",title:"No pudimos comprobar el Channel Manager",detail:healthError};if(!hub)return{tone:"gray",label:"Sin configurar",title:"Channel Manager",detail:"Todavía no hay un hub preparado para esta propiedad."};const status=norm(hub.status);if(status==="error"||hub.last_error)return{tone:"red",label:"Revisar",title:"Channel Manager",detail:hub.last_error||"El proveedor reportó un error."};if(status==="active")return{tone:"green",label:"Activo",title:"Channel Manager",detail:hub.last_sync_at?`Última sincronización ${relative(hub.last_sync_at).toLowerCase()}.`:"Activo; todavía no hay una marca de sincronización reciente."};if(status==="staging")return{tone:"yellow",label:"Preparado",title:"Channel Manager",detail:"La propiedad está preparada para conectar canales."};if(status==="paused")return{tone:"yellow",label:"Pausado",title:"Channel Manager",detail:"La sincronización está pausada."};return{tone:"gray",label:"Sin preparar",title:"Channel Manager",detail:"Aún no está vinculado a un proveedor."}},[hub,healthError])

  const recentSignals=useMemo(()=>notifications.map(item=>({id:item.id,tone:signalTone(item),title:item.title||"Actualización OTA",detail:signalDetail(item),createdAt:item.created_at,reservationId:item.reservation_id})).sort((a,b)=>toneRank(a.tone)-toneRank(b.tone)||String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,5),[notifications])
  const critical=exceptions.filter(item=>item.tone==="red").length,warning=exceptions.filter(item=>item.tone==="yellow").length
  const pulse=critical?{tone:"red",eyebrow:"ATENCIÓN AHORA",title:"Hay temas que conviene resolver antes de seguir.",text:`${critical} prioridad${critical===1?"":"es"} crítica${critical===1?"":"s"}${warning?` y ${warning} pendiente${warning===1?"":"s"}`:""}.`}:warning?{tone:"yellow",eyebrow:"OPERACIÓN EN CURSO",title:"El hotel está funcionando, con algunos pendientes.",text:`${warning} punto${warning===1?"":"s"} para ordenar antes de que genere fricción.`}:{tone:"green",eyebrow:"OPERACIÓN ORDENADA",title:"Lo importante está bajo control.",text:"No vemos excepciones críticas en las señales disponibles ahora."}

  const timeline=useMemo(()=>{const now=new Date(),limit=new Date(now.getTime()+24*3600000),tomorrowDate=tomorrowKey(),items=[];for(const row of current.arrivals)items.push({id:`a-${row.id}`,kind:"arrival",label:"Llegada",item:row,date:row.fecha_entrada,time:eventTime(row,"arrival"),moment:dateTime(row.fecha_entrada,row.hora_llegada_estimada),day:"Hoy"});for(const row of current.departures)items.push({id:`d-${row.id}`,kind:"departure",label:"Salida",item:row,date:row.fecha_salida,time:eventTime(row,"departure"),moment:dateTime(row.fecha_salida,row.hora_salida_estimada),day:"Hoy"});for(const [kind,rows] of [["arrival",tomorrow.arrivals],["departure",tomorrow.departures]])for(const row of rows){const raw=kind==="arrival"?row.hora_llegada_estimada:row.hora_salida_estimada,moment=dateTime(kind==="arrival"?row.fecha_entrada:row.fecha_salida,raw);if(moment&&moment<=limit)items.push({id:`${kind}-${row.id}-tomorrow`,kind,label:kind==="arrival"?"Llegada":"Salida",item:row,date:tomorrowDate,time:eventTime(row,kind),moment,day:"Mañana"})}return items.sort((a,b)=>{if(a.moment&&b.moment)return a.moment-b.moment;if(a.moment)return-1;if(b.moment)return 1;return a.kind.localeCompare(b.kind)}).slice(0,8)},[current.arrivals,current.departures,tomorrow.arrivals,tomorrow.departures])

  const recommendations=useMemo(()=>{const list=[],dirtyArrivals=current.arrivals.filter(item=>item.roomDirty&&!item.roomMaintenance),balanceDepartures=current.departures.filter(item=>Number(item.balance)>0);if(realOverbookings.length)list.push({tone:"red",title:"Resolver primero el inventario OTA",text:`Hay ${realOverbookings.length} reserva${realOverbookings.length===1?"":"s"} con overbooking real.`,why:"Porque una unidad vendida todavía no tiene habitación física compatible.",target:"planning",cta:"Abrir Planning"});if(dirtyArrivals.length)list.push({tone:"yellow",title:`Preparar ${dirtyArrivals.length} habitación${dirtyArrivals.length===1?"":"es"} antes de recibir huéspedes`,text:"Hay check-ins de hoy vinculados a habitaciones todavía sucias.",why:`Porque ${dirtyArrivals.map(item=>roomLabel(item)).slice(0,3).join(", ")} figura${dirtyArrivals.length===1?"":"n"} pendiente${dirtyArrivals.length===1?"":"s"}.`,target:"housekeeping",cta:"Ir a Housekeeping"});if(balanceDepartures.length)list.push({tone:"yellow",title:"Cerrar saldos antes del check-out",text:`${balanceDepartures.length} salida${balanceDepartures.length===1?"":"s"} de hoy mantiene${balanceDepartures.length===1?"":"n"} saldo pendiente.`,why:"Porque resolver el cobro antes de la salida evita fricción en recepción.",target:"reservations",cta:"Revisar reservas"});if(hubInfo.tone==="red")list.push({tone:"red",title:"Revisar la distribución antes de vender más",text:"El Channel Manager reporta una señal que necesita atención.",why:hubInfo.detail,target:"channelmanager",cta:"Abrir Channel Manager"});if(!list.length&&m.occupancy>=80)list.push({tone:"blue",title:"Día de alta ocupación: conviene anticiparse",text:`La ocupación de hoy está en ${Math.round(m.occupancy)}%.`,why:`Hay ${m.inhouse} de ${m.totalRooms} habitaciones ocupadas; priorizá limpieza, llegadas y salidas.`,target:"planning",cta:"Ver Planning"});if(!list.length)list.push({tone:"green",title:"La operación viene ordenada",text:`Tenés ${m.arrivals} llegada${m.arrivals===1?"":"s"} y ${m.departures} salida${m.departures===1?"":"s"} hoy.`,why:"No detectamos overbooking real, salidas con saldo ni llegadas con habitación pendiente en los datos actuales.",target:"planning",cta:"Ver Planning"});return list.slice(0,3)},[current.arrivals,current.departures,realOverbookings,hubInfo,m])

  const navigate=item=>{if(!item?.target||!can(item.target))return;if(item.reservationId&&item.target==="reservations")onNavigate?.("reservations",{reservationId:item.reservationId});else onNavigate?.(item.target)}
  const refresh=()=>{data.load();loadHealth()}

  return <section className={s.shell}>
    {loading?<div className={s.loadingPill} role="status" aria-live="polite"><i/><div><b>Leyendo la operación…</b><span>{slow?"Ya falta poco. Estamos cruzando las señales del hotel.":"Reservas, habitaciones e integraciones en una sola vista."}</span></div></div>:null}
    <header className={s.hero} data-tone={pulse.tone}><div className={s.heroGlow}/><div className={s.heroCopy}><StatusLight tone={pulse.tone} label={pulse.eyebrow}/><h1>{pulse.title}</h1><p>{pulse.text}</p><div className={s.heroActions}><button type="button" onClick={refresh} disabled={loading}><PmsIcon name="refresh" size={16}/>{loading?"Actualizando…":"Actualizar señales"}</button>{can("planning")?<button type="button" className={s.heroSecondary} onClick={()=>onNavigate?.("planning")}><PmsIcon name="calendar" size={16}/>Abrir Planning</button>:null}</div></div><div className={s.pulseOrb}><span><i/><i/><i/></span><div><small>PULSO DEL HOTEL</small><b>{critical?`${critical} crítica${critical===1?"":"s"}`:warning?`${warning} pendiente${warning===1?"":"s"}`:"Estable"}</b><em>{property?.name||"Propiedad actual"}</em></div></div></header>

    {data.error?<div className={s.errorCard}><span>!</span><div><b>No pudimos leer toda la operación</b><p>{data.error}</p></div><button type="button" onClick={refresh}>Reintentar</button></div>:null}

    <div className={s.metrics}>
      <MetricCard icon="calendar" label="Ocupación hoy" value={`${Math.round(m.occupancy||0)}%`} note={`${m.inhouse} de ${m.totalRooms} habitaciones`} tone="violet" onClick={can("planning")?()=>onNavigate?.("planning"):null}/>
      <MetricCard icon="booking" label="Llegadas" value={m.arrivals||0} note="check-ins programados hoy" tone="green" onClick={can("reservations")?()=>onNavigate?.("reservations"):null}/>
      <MetricCard icon="clean" label="Habitaciones listas" value={m.ready||0} note={`${m.dirty||0} requieren limpieza`} tone={m.dirty?"yellow":"cyan"} onClick={can("housekeeping")?()=>onNavigate?.("housekeeping"):null}/>
      <MetricCard icon="wrench" label="Mantenimiento" value={m.maintenance||0} note={m.urgent?`${m.urgent} urgente${m.urgent===1?"":"s"}`:"Sin urgencias visibles"} tone={m.urgent?"red":"blue"} onClick={can("maintenance")?()=>onNavigate?.("maintenance"):null}/>
    </div>

    <div className={s.mainGrid}>
      <section className={`${s.glassCard} ${s.nowCard}`}><header className={s.sectionHead}><div><small>AHORA</small><h2>Lo que necesita atención</h2></div><span>{exceptions.length?`${exceptions.length} señal${exceptions.length===1?"":"es"}`:"Todo en orden"}</span></header>{exceptions.length?<div className={s.exceptionList}>{exceptions.map(item=><button type="button" key={item.id} className={s.exception} data-tone={item.tone} onClick={()=>navigate(item)} disabled={!can(item.target)}><span className={s.exceptionIcon}><PmsIcon name={item.icon} size={18}/></span><div><b>{item.title}</b><small>{item.detail}</small></div><em>›</em></button>)}</div>:<Empty title="Nada crítico a la vista" text="No detectamos excepciones operativas en las señales disponibles."/>}</section>

      <section className={`${s.glassCard} ${s.timelineCard}`}><header className={s.sectionHead}><div><small>PRÓXIMAS 24 H</small><h2>Movimiento esperado</h2></div><span>{timeline.length} evento{timeline.length===1?"":"s"}</span></header><p className={s.sectionNote}>Incluye todo lo de hoy y, para mañana, los eventos con horario cargado dentro de las próximas 24 horas.</p>{timeline.length?<div className={s.timeline}>{timeline.map(row=><button type="button" key={row.id} onClick={()=>can("reservations")&&onNavigate?.("reservations",{reservationId:row.item.id})}><span className={s.time}>{row.time}</span><i data-kind={row.kind}/><div><b>{row.label} · {guestName(row.item)}</b><small>{row.day} · {roomLabel(row.item)} · {row.item.canal_reserva||"Directa"}</small></div><em>›</em></button>)}</div>:<Empty title="Sin movimientos con horario cargado" text={`Mañana hay ${tomorrow.arrivals.length} llegada${tomorrow.arrivals.length===1?"":"s"} y ${tomorrow.departures.length} salida${tomorrow.departures.length===1?"":"s"}.`}/>}<footer className={s.timelineFoot}><span>Mañana</span><b>{tomorrow.arrivals.length} llegadas · {tomorrow.departures.length} salidas</b></footer></section>
    </div>

    <div className={s.secondaryGrid}>
      <section className={`${s.glassCard} ${s.integrationCard}`}><header className={s.sectionHead}><div><small>ALERTAS E INTEGRACIONES</small><h2>Señales de distribución</h2></div>{can("channelmanager")?<button type="button" onClick={()=>onNavigate?.("channelmanager")}>Ver Channel Manager</button>:null}</header><div className={s.hubHealth}><StatusLight tone={hubInfo.tone} label={hubInfo.label}/><div><b>{hubInfo.title}</b><span>{hubInfo.detail}</span></div>{hub?.updated_at?<em>{relative(hub.updated_at)}</em>:null}</div>{recentSignals.length?<div className={s.signalList}>{recentSignals.map(item=><button type="button" key={item.id} data-tone={item.tone} onClick={()=>item.reservationId&&can("reservations")&&onNavigate?.("reservations",{reservationId:item.reservationId})}><i/><div><b>{item.title}</b><small>{item.detail}</small></div><time>{relative(item.createdAt)}</time></button>)}</div>:<Empty title="Sin alertas OTA recientes" text="No hubo señales operativas registradas por OTAs en las últimas 48 horas."/>}</section>

      <section className={`${s.glassCard} ${s.oliviaCard}`}><header className={s.oliviaHead}><div className={s.oliviaMark}>O</div><div><small>OLIVIA · CRITERIO OPERATIVO</small><h2>Qué haría primero</h2></div><StatusLight tone={recommendations.some(item=>item.tone==="red")?"red":recommendations.some(item=>item.tone==="yellow")?"yellow":"green"} label="Explicable"/></header><div className={s.recommendations}>{recommendations.map((item,index)=><article key={`${item.title}-${index}`} data-tone={item.tone}><div className={s.recNumber}>{String(index+1).padStart(2,"0")}</div><div className={s.recCopy}><b>{item.title}</b><p>{item.text}</p><details><summary>Por qué</summary><span>{item.why}</span></details>{can(item.target)?<button type="button" onClick={()=>onNavigate?.(item.target)}>{item.cta}<span>→</span></button>:null}</div></article>)}</div><footer><span>OlivIA no cambia nada sola.</span><b>Lee señales reales y explica cada sugerencia.</b></footer></section>
    </div>
  </section>
}
