"use client"

import{useMemo,useState}from"react"
import useOperationalNotifications from"../../core/useOperationalNotifications"
import useOperationsData from"./useOperationsData"
import s from"./operations.module.css"

const STATUSES=[["open","Nueva"],["assigned","Asignada"],["in_progress","En curso"],["waiting_parts","Esperando repuesto"],["resolved","Resuelta"],["cancelled","Cancelada"]]
const REQUEST_STATUSES=[["open","Nueva"],["in_progress","En curso"],["resolved","Resuelta"],["cancelled","Cancelada"]]
const PRIORITY={low:"Baja",normal:"Media",high:"Alta",urgent:"Urgente"}
const score={urgent:4,high:3,normal:2,low:1}
const fmtDate=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value)).replace(".",""):"Sin vencimiento"
const stateTone=status=>["resolved"].includes(status)?"green":["assigned","in_progress","waiting_parts"].includes(status)?"yellow":"red"
const priorityTone=value=>value==="urgent"?"red":value==="high"?"orange":value==="normal"?"yellow":"green"
const sortAlerts=(a,b)=>(score[b.priority]||0)-(score[a.priority]||0)||new Date(a.due_at||"2999-01-01")-new Date(b.due_at||"2999-01-01")||new Date(a.created_at||0)-new Date(b.created_at||0)

export default function OperationsWorkspace({propertyId,initialTab="maintenance"}){
  const data=useOperationsData(propertyId)
  const[tab,setTab]=useState(initialTab==="tasks"?"maintenance":initialTab),[query,setQuery]=useState(""),[archived,setArchived]=useState(false),[formOpen,setFormOpen]=useState(false),[saving,setSaving]=useState(false),[newChecklist,setNewChecklist]=useState("")
  const[draft,setDraft]=useState({title:"",description:"",reservation_id:"",room_id:"",priority:"normal",assigned_to:"",due_at:""})
  const[requestOpen,setRequestOpen]=useState(false),[requestQuery,setRequestQuery]=useState(""),[requestFilter,setRequestFilter]=useState("active")
  const[requestDraft,setRequestDraft]=useState({title:"",detail:"",reservation_id:"",room_id:"",priority:"normal",assigned_to:"",requested_by:"guest",due_at:""})
  const notifyArea=tab==="requests"?"requests":"maintenance"
  const notifyTables=tab==="requests"?["hotel_guest_requests"]:["hotel_maintenance_tickets"]
  const notifications=useOperationalNotifications({propertyId,area:notifyArea,tables:notifyTables,onRefresh:data.load})

  const maintenanceActive=useMemo(()=>data.tickets.filter(item=>!["resolved","cancelled"].includes(item.status)).sort(sortAlerts),[data.tickets])
  const requestActive=useMemo(()=>data.guestRequests.filter(item=>!["resolved","cancelled"].includes(item.status)).sort(sortAlerts),[data.guestRequests])
  const visibleTasks=useMemo(()=>data.tickets.filter(t=>{if(archived&&!['resolved','cancelled'].includes(t.status))return false;if(!archived&&['resolved','cancelled'].includes(t.status))return false;const room=data.roomById.get(Number(t.room_id)),reservation=data.reservationById.get(Number(t.reservation_id)),assignee=data.profileById.get(t.assigned_to),term=query.trim().toLowerCase();return !term||`${t.title} ${t.description||""} ${room?.nombre||""} ${reservation?.nombre_huesped||""} ${reservation?.numero_reserva||""} ${assignee?.full_name||""}`.toLowerCase().includes(term)}).sort(sortAlerts),[data.tickets,data.roomById,data.reservationById,data.profileById,query,archived])
  const visibleRequests=useMemo(()=>data.guestRequests.filter(request=>{if(requestFilter==="active"&&['resolved','cancelled'].includes(request.status))return false;if(requestFilter==="resolved"&&request.status!=="resolved")return false;if(requestFilter==="cancelled"&&request.status!=="cancelled")return false;const reservation=data.reservationById.get(Number(request.reservation_id)),room=data.roomById.get(Number(request.room_id)),assignee=data.profileById.get(request.assigned_to),term=requestQuery.trim().toLowerCase();return !term||`${request.title} ${request.detail||""} ${reservation?.nombre_huesped||""} ${reservation?.numero_reserva||""} ${room?.nombre||""} ${assignee?.full_name||""}`.toLowerCase().includes(term)}).sort(sortAlerts),[data.guestRequests,data.reservationById,data.roomById,data.profileById,requestQuery,requestFilter])
  const todayProgress=useMemo(()=>{let done=0,total=0;for(const task of data.housekeepingTasks){const list=Array.isArray(task.checklist)?task.checklist:[];total+=list.length;done+=list.filter(item=>item?.done===true).length}return{done,total,pct:total?Math.round(done/total*100):0}},[data.housekeepingTasks])

  const maintenanceStats=useMemo(()=>({urgent:maintenanceActive.filter(i=>i.priority==="urgent").length,high:maintenanceActive.filter(i=>i.priority==="high").length,pending:maintenanceActive.filter(i=>["open","assigned","waiting_parts"].includes(i.status)).length,progress:maintenanceActive.filter(i=>i.status==="in_progress").length}),[maintenanceActive])
  const requestStats=useMemo(()=>({urgent:requestActive.filter(i=>i.priority==="urgent").length,high:requestActive.filter(i=>i.priority==="high").length,pending:requestActive.filter(i=>i.status==="open").length,progress:requestActive.filter(i=>i.status==="in_progress").length}),[requestActive])

  async function moveTask(id,status){try{await data.updateTicket(id,{status})}catch(err){data.setError(err?.message||"No se pudo actualizar la tarea.")}}
  async function saveTask(){if(!draft.title.trim())return data.setError("Ingresá un título para la tarea.");setSaving(true);data.setError("");try{await data.createTicket(draft);setFormOpen(false);setDraft({title:"",description:"",reservation_id:"",room_id:"",priority:"normal",assigned_to:"",due_at:""})}catch(err){data.setError(err?.message||"No se pudo crear la tarea.")}finally{setSaving(false)}}
  async function addChecklist(){const label=newChecklist.trim();if(!label)return;setSaving(true);try{await data.createChecklistItem(label);setNewChecklist("")}catch(err){data.setError(err?.message||"No se pudo agregar el ítem.")}finally{setSaving(false)}}
  async function saveRequest(){if(!requestDraft.title.trim())return data.setError("Ingresá un pedido o solicitud.");setSaving(true);data.setError("");try{await data.createGuestRequest(requestDraft);setRequestOpen(false);setRequestDraft({title:"",detail:"",reservation_id:"",room_id:"",priority:"normal",assigned_to:"",requested_by:"guest",due_at:""})}catch(err){data.setError(err?.message||"No se pudo crear la solicitud.")}finally{setSaving(false)}}
  async function moveRequest(id,status){try{await data.updateGuestRequest(id,{status})}catch(err){data.setError(err?.message||"No se pudo actualizar la solicitud.")}}
  function quickTask(task){moveTask(task.id,task.status==="in_progress"?"resolved":"in_progress")}
  function quickRequest(request){moveRequest(request.id,request.status==="in_progress"?"resolved":"in_progress")}

  const stats=tab==="requests"?requestStats:maintenanceStats
  const attention=tab==="requests"?requestActive:maintenanceActive

  return <section className={s.page}>
    <header className={s.header}><div><small>OPERACIONES</small><h1>{tab==="requests"?"Peticiones del huésped":tab==="checklists"?"Check-lists operativos":"Mantenimiento"}</h1><p>{tab==="requests"?"Pedidos visibles al instante para recepción y el área responsable.":tab==="checklists"?"Rutinas y control del trabajo diario.":"Reparaciones y tareas técnicas ordenadas por urgencia."}</p></div><div className={s.headerActions}><div className={s.tabs}><button className={tab==="maintenance"?s.active:""} onClick={()=>setTab("maintenance")}>Mantenimiento {maintenanceActive.length?`(${maintenanceActive.length})`:""}</button><button className={tab==="requests"?s.active:""} onClick={()=>setTab("requests")}>Peticiones {requestActive.length?`(${requestActive.length})`:""}</button><button className={tab==="checklists"?s.active:""} onClick={()=>setTab("checklists")}>Check-lists</button></div>{tab!=="checklists"?<button type="button" className={`${s.notifyButton} ${notifications.enabled?s.notifyOn:""}`} onClick={notifications.toggle}>{notifications.enabled?"🔔 Alertas activas":"🔕 Activar alertas"}</button>:null}</div></header>
    {data.error&&<div className={s.errorBox}>{data.error}</div>}

    {tab!=="checklists"?<><div className={s.overview}><article data-tone="red"><span>Urgentes</span><b>{stats.urgent}</b><small>atención inmediata</small></article><article data-tone="orange"><span>Alta prioridad</span><b>{stats.high}</b><small>resolver pronto</small></article><article data-tone="yellow"><span>Pendientes</span><b>{stats.pending}</b><small>todavía sin cerrar</small></article><article data-tone="green"><span>En proceso</span><b>{stats.progress}</b><small>ya tomadas</small></article></div><section className={s.attention}><header><div><small>ATENCIÓN AHORA</small><h2>{attention.length?`${attention.length} pendientes activos`:"Todo al día"}</h2></div><span>Rojo urgente · naranja alta · amarillo media · verde baja</span></header>{attention.length?<div className={s.alertGrid}>{attention.slice(0,8).map(row=>{const room=data.roomById.get(Number(row.room_id)),reservation=data.reservationById.get(Number(row.reservation_id));return <article key={row.id} data-priority={priorityTone(row.priority)}><div className={s.alertTop}><span className={s.priorityPill} data-priority={priorityTone(row.priority)}>{PRIORITY[row.priority]||row.priority}</span><span className={s.statePill} data-tone={stateTone(row.status)}>{(tab==="requests"?REQUEST_STATUSES: Object.fromEntries(STATUSES))[row.status]||row.status}</span></div><h3>{row.title}</h3><p>{row.detail||row.description||"Sin detalle adicional."}</p><div className={s.alertMeta}><b>{room?`Hab. ${room.nombre}`:"General"}</b>{reservation?<span>{reservation.nombre_huesped} · {reservation.numero_reserva||reservation.id}</span>:null}<span>{fmtDate(row.due_at)}</span></div><button type="button" onClick={()=>tab==="requests"?quickRequest(row):quickTask(row)}>{row.status==="in_progress"?"✓ Marcar resuelta":"▶ Tomar ahora"}</button></article>})}</div>:<div className={s.goodState}>✓ No hay alertas activas en esta área.</div>}</section></>:null}

    {tab==="maintenance"&&<><div className={s.toolbar}><label className={s.search}>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar habitación, huésped, tarea o técnico"/></label><button className={archived?s.active:""} onClick={()=>setArchived(v=>!v)}>{archived?"← Volver a activas":"Ver resueltas"}</button><button className={s.primary} onClick={()=>setFormOpen(true)}>+ Nueva tarea</button></div><div className={s.tableWrap}><table><thead><tr><th>Prioridad</th><th>Tarea</th><th>Habitación / huésped</th><th>Responsable</th><th>Estado</th><th>Vence</th></tr></thead><tbody>{visibleTasks.map(task=>{const room=data.roomById.get(Number(task.room_id)),reservation=data.reservationById.get(Number(task.reservation_id));return <tr key={task.id}><td><span className={s.priorityPill} data-priority={priorityTone(task.priority)}>{PRIORITY[task.priority]||task.priority}</span></td><td><b>{task.title}</b><small>{task.description||"Sin detalle"}</small></td><td><b>{room?`Hab. ${room.nombre}`:"General"}</b>{reservation?<small>{reservation.nombre_huesped} · {reservation.numero_reserva||reservation.id}</small>:null}</td><td>{data.profileById.get(task.assigned_to)?.full_name||"Sin asignar"}</td><td><select value={task.status} onChange={e=>moveTask(task.id,e.target.value)}>{STATUSES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></td><td>{fmtDate(task.due_at)}</td></tr>})}</tbody></table>{!data.loading&&!visibleTasks.length?<div className={s.empty}>No hay tareas en esta vista.</div>:null}</div></>}

    {tab==="requests"&&<><div className={s.toolbar}><div className={s.segment}>{[["active","Activas"],["resolved","Resueltas"],["cancelled","Canceladas"]].map(([value,label])=><button key={value} className={requestFilter===value?s.active:""} onClick={()=>setRequestFilter(value)}>{label}</button>)}</div><label className={s.search}>⌕<input value={requestQuery} onChange={e=>setRequestQuery(e.target.value)} placeholder="Buscar pedido, huésped o habitación"/></label><button className={s.primary} onClick={()=>setRequestOpen(true)}>+ Nueva petición</button></div><div className={s.tableWrap}><table><thead><tr><th>Prioridad</th><th>Petición</th><th>Huésped / habitación</th><th>Responsable</th><th>Estado</th><th>Vence</th></tr></thead><tbody>{visibleRequests.map(request=>{const reservation=data.reservationById.get(Number(request.reservation_id)),room=data.roomById.get(Number(request.room_id));return <tr key={request.id}><td><span className={s.priorityPill} data-priority={priorityTone(request.priority)}>{PRIORITY[request.priority]||request.priority}</span></td><td><b>{request.title}</b><small>{request.detail||"Sin detalle"}</small></td><td>{reservation?<><b>{reservation.nombre_huesped}</b><small>Hab. {room?.nombre||"—"} · {reservation.numero_reserva||reservation.id}</small></>:<b>{room?`Hab. ${room.nombre}`:"Sin reserva vinculada"}</b>}</td><td>{data.profileById.get(request.assigned_to)?.full_name||"Sin asignar"}</td><td><select value={request.status} onChange={e=>moveRequest(request.id,e.target.value)}>{REQUEST_STATUSES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></td><td>{fmtDate(request.due_at)}</td></tr>})}</tbody></table>{!data.loading&&!visibleRequests.length?<div className={s.empty}>No hay peticiones en esta vista.</div>:null}</div></>}

    {tab==="checklists"&&<div className={s.checkGrid}><article className={s.checkCard}><div><small>HOY</small><h3>Progreso de housekeeping</h3><span>{data.housekeepingTasks.length} tareas programadas</span></div><div className={s.progress}><i style={{width:`${todayProgress.pct}%`}}/></div><footer><b>{todayProgress.done}/{todayProgress.total}</b><span>{todayProgress.pct}% completado</span></footer></article>{data.checklistCatalog.map(item=><article className={s.checkCard} key={item.id}><div><small>{item.required?"OBLIGATORIO":"OPCIONAL"}</small><h3>{item.label}</h3><span>Inspección de habitación</span></div><footer><b>{item.active?"Activo":"Inactivo"}</b><button disabled={saving} onClick={()=>data.toggleChecklistItem(item)}>{item.active?"Desactivar":"Activar"}</button></footer></article>)}<article className={s.checkCard}><div><small>NUEVO ÍTEM</small><h3>Agregar al checklist</h3><input value={newChecklist} onChange={e=>setNewChecklist(e.target.value)} placeholder="Ej. Revisar caja fuerte"/></div><footer><button disabled={saving||!newChecklist.trim()} onClick={addChecklist}>Agregar</button></footer></article></div>}

    {formOpen&&<div className={s.modalShade} onMouseDown={e=>e.target===e.currentTarget&&setFormOpen(false)}><div className={s.modal}><header><h2>Nueva tarea de mantenimiento</h2><button onClick={()=>setFormOpen(false)}>×</button></header><div className={s.form}><label className={s.wide}>Título<input value={draft.title} onChange={e=>setDraft(v=>({...v,title:e.target.value}))}/></label><label>Reserva<select value={draft.reservation_id} onChange={e=>{const reservation=data.reservationById.get(Number(e.target.value));setDraft(v=>({...v,reservation_id:e.target.value,room_id:reservation?.habitacion_id||v.room_id}))}}><option value="">Sin reserva vinculada</option>{data.reservations.map(r=><option key={r.id} value={r.id}>{r.numero_reserva||r.id} · {r.nombre_huesped}</option>)}</select></label><label>Habitación<select value={draft.room_id} onChange={e=>setDraft(v=>({...v,room_id:e.target.value}))}><option value="">General</option>{data.rooms.map(room=><option key={room.id} value={room.id}>{room.nombre}</option>)}</select></label><label>Prioridad<select value={draft.priority} onChange={e=>setDraft(v=>({...v,priority:e.target.value}))}><option value="low">Baja</option><option value="normal">Media</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label>Responsable<select value={draft.assigned_to} onChange={e=>setDraft(v=>({...v,assigned_to:e.target.value}))}><option value="">Sin asignar</option>{data.profiles.map(profile=><option key={profile.id} value={profile.id}>{profile.full_name||profile.id.slice(0,8)}</option>)}</select></label><label>Vencimiento<input type="datetime-local" value={draft.due_at} onChange={e=>setDraft(v=>({...v,due_at:e.target.value?new Date(e.target.value).toISOString():""}))}/></label><label className={s.wide}>Descripción<textarea value={draft.description} onChange={e=>setDraft(v=>({...v,description:e.target.value}))}/></label></div><footer><button onClick={()=>setFormOpen(false)}>Cancelar</button><button disabled={saving} onClick={saveTask}>{saving?"Guardando…":"Crear tarea"}</button></footer></div></div>}

    {requestOpen&&<div className={s.modalShade} onMouseDown={e=>e.target===e.currentTarget&&setRequestOpen(false)}><div className={s.modal}><header><h2>Nueva petición</h2><button onClick={()=>setRequestOpen(false)}>×</button></header><div className={s.form}><label className={s.wide}>Pedido o solicitud<input value={requestDraft.title} onChange={e=>setRequestDraft(v=>({...v,title:e.target.value}))} placeholder="Ej. Cuna, almohada extra, traslado…"/></label><label className={s.wide}>Reserva<select value={requestDraft.reservation_id} onChange={e=>{const reservation=data.reservationById.get(Number(e.target.value));setRequestDraft(v=>({...v,reservation_id:e.target.value,room_id:reservation?.habitacion_id||v.room_id}))}}><option value="">Sin reserva vinculada</option>{data.reservations.map(reservation=><option key={reservation.id} value={reservation.id}>{reservation.numero_reserva||reservation.id} · {reservation.nombre_huesped}</option>)}</select></label><label>Habitación<select value={requestDraft.room_id} onChange={e=>setRequestDraft(v=>({...v,room_id:e.target.value}))}><option value="">Sin habitación</option>{data.rooms.map(room=><option key={room.id} value={room.id}>{room.nombre} · {room.tipo||""}</option>)}</select></label><label>Prioridad<select value={requestDraft.priority} onChange={e=>setRequestDraft(v=>({...v,priority:e.target.value}))}><option value="low">Baja</option><option value="normal">Media</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label>Responsable<select value={requestDraft.assigned_to} onChange={e=>setRequestDraft(v=>({...v,assigned_to:e.target.value}))}><option value="">Sin asignar</option>{data.profiles.map(profile=><option key={profile.id} value={profile.id}>{profile.full_name||profile.id.slice(0,8)}</option>)}</select></label><label>Solicitado por<select value={requestDraft.requested_by} onChange={e=>setRequestDraft(v=>({...v,requested_by:e.target.value}))}><option value="guest">Huésped</option><option value="reception">Recepción</option><option value="housekeeping">Housekeeping</option><option value="other">Otro</option></select></label><label>Vencimiento<input type="datetime-local" value={requestDraft.due_at} onChange={e=>setRequestDraft(v=>({...v,due_at:e.target.value?new Date(e.target.value).toISOString():""}))}/></label><label className={s.wide}>Detalle<textarea value={requestDraft.detail} onChange={e=>setRequestDraft(v=>({...v,detail:e.target.value}))}/></label></div><footer><button onClick={()=>setRequestOpen(false)}>Cancelar</button><button disabled={saving} onClick={saveRequest}>{saving?"Guardando…":"Crear petición"}</button></footer></div></div>}
  </section>
}
