import{money}from"../../../core/formatters"
import ReservationPaymentSummary from"../ReservationPaymentSummary"
import{holderPatch,holderValue}from"../GuestIdentityPanel"
import{openReservationDocument}from"../../../services/reservationDocuments"
import modal from"../reservation-modal.module.css"
import ws from"../reservation-workspace.module.css"

const DOC_KINDS=[["documento","Documento"],["dni","DNI"],["pasaporte","Pasaporte"],["licencia","Licencia"],["voucher","Voucher"],["autorizacion","Autorización"],["otro","Otro"]]
const PAYMENT_METHODS=["Efectivo","Transferencia","Débito","Crédito","Mercado Pago","Seña / depósito","USD efectivo","Otro"]
const size=n=>n>1048576?`${(n/1048576).toFixed(1)} MB`:`${Math.max(1,Math.round(n/1024))} KB`
const paymentMethod=item=>String(item?.metodo||item?.method||"Pago")
const paymentNote=item=>String(item?.nota||item?.note||"")
const isDeposit=item=>/seña|deposit/i.test(`${paymentMethod(item)} ${paymentNote(item)}`)
function NumberInput({value,onChange,...props}){return <input type="number" value={value??""} onFocus={()=>String(value)==="0"&&onChange("")} onChange={e=>onChange(e.target.value)} {...props}/>}

export default function ReservationMoneyDocuments({tab,draft,set,payment,setPayment,totals,paid,balance,depositTotal,registerPayment,overpaid,paymentMessage,stagedPayments,removeStagedPayment,reservationPayments,pending,documents,documentHolders,docBusy,selectDocuments,reassignStored,removeStored,docMessage}){
  return <>
    {tab==="money"&&<section className={modal.panel}><h3>Pagos, señas y saldo</h3><ReservationPaymentSummary draft={draft} totals={totals} paid={paid} balance={balance}/><div className={ws.moneyTools}>{balance>.01&&<button type="button" onClick={()=>setPayment(x=>({...x,amount:String(balance)}))}>Cargar saldo completo</button>}{balance>.01&&<button type="button" onClick={()=>setPayment(x=>({...x,method:"Seña / depósito",amount:String(Math.min(balance,Math.max(1,Math.round(totals.total*.3))))}))}>Preparar seña 30%</button>}{depositTotal>0&&<span className={ws.pill}>Señas registradas: {money(depositTotal,draft.currency)}</span>}</div><div className={modal.paymentBox}><div className={modal.paymentFields}><NumberInput min="0.01" step="0.01" max={balance||undefined} placeholder="Monto" value={payment.amount} onChange={v=>setPayment(x=>({...x,amount:v}))}/><select value={payment.method} onChange={e=>setPayment(x=>({...x,method:e.target.value}))}><option value="">Medio de pago</option>{PAYMENT_METHODS.map(method=><option key={method}>{method}</option>)}</select><input placeholder="Nota / referencia (opcional)" value={payment.note} onChange={e=>setPayment(x=>({...x,note:e.target.value}))}/><button type="button" disabled={!totals.total||balance<=.01} onClick={registerPayment}>{draft.id?"Registrar pago":"Agregar pago"}</button></div>{overpaid>.01?<div className={`${modal.paymentState} ${modal.balanceOpen}`}>Los pagos superan el total en {money(overpaid,draft.currency)}. Revisá los importes antes de guardar.</div>:balance>.01?<div className={`${modal.paymentState} ${modal.balanceOpen}`}>Quedan {money(balance,draft.currency)} pendientes. Podés guardar la reserva y completar el saldo más adelante; el check-out queda bloqueado mientras exista deuda.</div>:totals.total>0?<div className={`${modal.paymentState} ${modal.balanceClear}`}>Cuenta cubierta. No queda saldo pendiente.</div>:null}</div>{paymentMessage&&<div className={modal.message}>{paymentMessage}</div>}<div className={modal.paymentHistory}><h4>Movimientos de pago</h4>{stagedPayments.map((item,i)=><div className={modal.paymentRow} key={`staged-${i}`}><span><b>{item.method}{isDeposit(item)&&<i className={ws.depositTag}>SEÑA</i>}</b><small>{item.note||"Se registrará al crear la reserva"}</small></span><strong>{money(item.amount,draft.currency)}</strong><button type="button" title="Quitar pago" onClick={()=>removeStagedPayment(i)}>×</button></div>)}{reservationPayments.map(item=><div className={modal.paymentRow} key={item.id}><span><b>{item.metodo||"Pago"}{isDeposit(item)&&<i className={ws.depositTag}>SEÑA</i>}</b><small>{item.nota||"Pago registrado"}</small></span><strong>{money(item.monto,item.moneda||draft.currency)}</strong><span/></div>)}{!stagedPayments.length&&!reservationPayments.length&&<div className={modal.paymentEmpty}>Todavía no hay pagos registrados. Podés cargar un pago total, parcial, una seña o combinar varios medios.</div>}</div></section>}

    {tab==="documents"&&<section className={modal.panel}><h3>Documentos asociados</h3><div className={modal.documents}><label className={modal.drop}><input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" disabled={docBusy} onChange={e=>{selectDocuments(e.target.files);e.target.value=""}}/><span><strong>{docBusy?"Optimizando…":"Subir documentos"}</strong><p>JPG, PNG, WEBP o PDF. Las imágenes se comprimen antes de guardarse. Máximo 12 MB por archivo. Podés indicar a quién pertenece cada archivo.</p></span></label><div className={modal.docList}>{pending.map((item,i)=><article className={modal.doc} key={`pending-${i}`}><span><b>{item.file.name}</b><small>Nuevo · {size(item.originalSize)} → {size(item.file.size)}</small></span><div className={modal.docActions}><select className={modal.kindSelect} value={item.kind} onChange={e=>set("pendingDocuments",pending.map((x,j)=>j===i?{...x,kind:e.target.value}:x))}>{DOC_KINDS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select className={modal.kindSelect} value={holderValue(item)} onChange={e=>set("pendingDocuments",pending.map((x,j)=>j===i?{...x,...holderPatch(e.target.value,draft)}:x))}>{documentHolders.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select><button type="button" onClick={()=>set("pendingDocuments",pending.filter((_,j)=>j!==i))}>Quitar</button></div></article>)}{documents.map(doc=>{const currentHolder=documentHolders.find(option=>option.value===holderValue(doc));return <article className={modal.doc} key={doc.id}><span><b>{doc.file_name}</b><small>{doc.kind} · {size(doc.stored_size_bytes)} · {doc.holder_name||currentHolder?.label||"Reserva"}</small></span><div className={modal.docActions}><select className={modal.kindSelect} disabled={docBusy} value={holderValue(doc)} onChange={e=>reassignStored(doc,e.target.value)}>{documentHolders.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select><button type="button" onClick={()=>openReservationDocument(doc)}>Abrir</button><button type="button" onClick={()=>removeStored(doc)}>Eliminar</button></div></article>})}{!pending.length&&!documents.length&&<div className={modal.message}>Todavía no hay documentos asociados.</div>}</div></div>{docMessage&&<div className={modal.message}>{docMessage}</div>}</section>}
  </>
}
