"use client"

import{useCallback,useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import s from"./guestJourney.module.css"

const norm=v=>String(v||"").trim().toLowerCase()
const fmt=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short"}).format(new Date(`${value}T12:00:00`)).replace(".",""):"—"
const toneRank=t=>t==="red"?0:t==="yellow"?1:t==="blue"?2:3

export default function GuestJourneyPanel({propertyId}){
  const[reservations,setReservations]=useState([]),[checkins,setCheckins]=useState([]),[guests,setGuests]=useState([]),[documents,setDocuments]=useState([]),[requests,setRequests]=useState([]),[templateReady,setTemplateReady]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(null),[notice,setNotice]=useState(""),[error,setError]=useState("")
  const load=useCallback(async()=>{if(!propertyId)return;setLoading(true);setError("");try{const today=new Date().toLocaleDateString("en-CA"),limit=new Date(Date.now()+21*86400000).toLocaleDateString("en-CA"),[resRes,checkRes,guestRes,docRes,requestRes,templateRes]=await Promise.all([
    supabase.from("reservas").select("id,numero_reserva,nombre_huesped,email_huesped,telefono_huesped,dni_huesped,fecha_entrada,fecha_salida,estado,habitacion_id,web_checkin_status,guest_profile_id").eq("property_id",propertyId).gte("fecha_entrada",today).lte("fecha_entrada",limit).not("estado","in",'(cancelada,cancelled,no_show)').order("fecha_entrada",{ascending:true}).limit(80),
    supabase.from("hotel_web_checkins").select("id,reservation_id,status,expires_at,opened_at,completed_at,payload,created_at").eq("property_id",propertyId).order("created_at",{ascending:false}).limit(120),
    supabase.from("hotel_reservation_guests").select("id,reservation_id,role,document_number,document_front_path,document_back_path,updated_at").eq("property_id",propertyId).limit(300),
    supabase.from("hotel_reservation_documents").select("id,reserva_id,kind,storage_path,metadata,created_at").eq("property_id",propertyId).order("created_at",{ascending:false}).limit(300),
    supabase.from("hotel_guest_stay_portal_requests").select("id,reservation_id,kind,decision,requested_time,created_at").eq("property_id",propertyId).is("decision",null).order("created_at",{ascending:false}).limit(80),
    supabase.from("hotel_message_templates").select("id").eq("property_id",propertyId).eq("code","pre_checkin").eq("enabled",true).limit(1),
  ]);for(const r of[resRes,checkRes,guestRes,docRes,requestRes,templateRes])if(r.error)throw r.error;setReservations(resRes.data||[]);setCheckins(checkRes.data||[]);setGuests(guestRes.data||[]);setDocuments(docRes.data||[]);setRequests(requestRes.data||[]);setTemplateReady(Boolean(templateRes.data?.length))}catch(err){setError(err?.message||"No pudimos leer la experiencia del huésped.")}finally{setLoading(false)}},[propertyId])
  useEffect(()=>{load()},[load])
  const latestByReservation=useMemo(()=>{const map=new Map();for(const row of checkins)if(!map.has(String(row.reservation_id)))map.set(String(row.reservation_id),row);return map},[checkins])
  const guestsByReservation=useMemo(()=>{const map=new Map();for(const row of guests){const key=String(row.reservation_id);if(!map.has(key))map.set(key,[]);map.get(key).push(row)}return map},[guests])
  const docsByReservation=useMemo(()=>{const map=new Map();for(const row of documents){const key=String(row.reserva_id);if(!map.has(key))map.set(key,[]);map.get(key).push(row)}return map},[documents])
  const requestsByReservation=useMemo(()=>{const map=new Map();for(const row of requests){const key=String(row.reservation_id);if(!map.has(key))map.set(key,[]);map.get(key).push(row)}return map},[requests])
  const rows=useMemo(()=>reservations.map(r=>{const check=latestByReservation.get(String(r.id)),people=guestsByReservation.get(String(r.id))||[],docs=docsByReservation.get(String(r.id))||[],openRequests=requestsByReservation.get(String(r.id))||[],payload=check?.payload&&typeof check.payload==="object"?check.payload:{},completed=norm(r.web_checkin_status)==="completed"||norm(check?.status)==="completed",opened=norm(r.web_checkin_status)==="opened"||norm(check?.status)==="opened",hasDocument=Boolean(r.dni_huesped||payload.document||people.some(x=>x.document_number||x.document_front_path||x.document_back_path)||docs.length),documentVerified=docs.length>0&&docs.every(x=>["valid","validated","approved"].includes(norm(x.metadata?.validation_status||x.metadata?.status))),hasContact=Boolean(r.email_huesped||r.telefono_huesped),serviceRequests=[payload.breakfast&&"Desayuno",payload.parking&&"Estacionamiento",payload.transfer&&"Traslado",payload.early_checkin&&"Early check-in",payload.late_checkout&&"Late checkout"].filter(Boolean);let tone="green",title="Listo para recibir";if(!hasContact){tone="red";title="Falta contacto"}else if(completed&&!hasDocument){tone="yellow";title="Documento pendiente"}else if(completed&&docs.length&&!documentVerified){tone="yellow";title="Validación pendiente"}else if(!completed){tone="blue";title=opened?"Pre check-in abierto":"Pre check-in pendiente"}else if(openRequests.length||serviceRequests.length){tone="yellow";title="Pedido del huésped"}return{...r,check,people,docs,openRequests,payload,serviceRequests,completed,opened,hasDocument,documentVerified,hasContact,tone,title}}).sort((a,b)=>toneRank(a.tone)-toneRank(b.tone)||String(a.fecha_entrada).localeCompare(String(b.fecha_entrada))),[reservations,latestByReservation,guestsByReservation,docsByReservation,requestsByReservation])
  const completed=rows.filter(x=>x.completed).length,pending=rows.filter(x=>!x.completed).length,exceptions=rows.filter(x=>["red","yellow"].includes(x.tone)).length
  async function createLink(row){setBusy(row.id);setError("");setNotice("");try{const{data:token,error:rpcError}=await supabase.rpc("hl_create_web_checkin_token",{p_property_id:propertyId,p_reservation_id:Number(row.id),p_expires_hours:168});if(rpcError)throw rpcError;if(!token)throw new Error("No se generó el enlace.");const url=`${window.location.origin}/check-in/${token}`;await navigator.clipboard?.writeText(url);setNotice(`Enlace de pre check-in generado y copiado para ${row.nombre_huesped||"el huésped"}.`);await load()}catch(err){setError(err?.message||"No pudimos generar el enlace de pre check-in.")}finally{setBusy(null)}}
  return <section className={s.panel} aria-label="Capa del huésped"><header className={s.head}><div><small>EXPERIENCIA DEL HUÉSPED</small><h2>Pre check-in y excepciones</h2><p>El huésped adelanta datos y recepción interviene sólo cuando falta algo.</p></div><span className={s.live}><i/>Datos reales</span></header><div className={s.metrics}><article><span>Próximas llegadas</span><b>{rows.length}</b><small>21 días</small></article><article data-tone="green"><span>Pre check-in completo</span><b>{completed}</b><small>recibidos</small></article><article data-tone={exceptions?"yellow":"green"}><span>Excepciones</span><b>{exceptions}</b><small>requieren criterio humano</small></article><article data-tone="blue"><span>Pendientes</span><b>{pending}</b><small>{templateReady?"plantilla pre-checkin lista":"sin automatización activa"}</small></article></div>{error?<div className={s.error}>{error}</div>:null}{notice?<div className={s.notice}>{notice}</div>:null}<div className={s.grid}>{loading?<div className={s.empty}>Leyendo llegadas, documentos y pre check-in…</div>:rows.length?rows.slice(0,8).map(row=><article className={s.card} data-tone={row.tone} key={row.id}><div className={s.cardLight}><i/></div><div className={s.cardMain}><div className={s.cardTitle}><div><b>{row.nombre_huesped||"Huésped"}</b><small>{row.numero_reserva||`Reserva ${row.id}`} · {fmt(row.fecha_entrada)} → {fmt(row.fecha_salida)}</small></div><span>{row.title}</span></div><div className={s.steps}><span data-ok={row.hasContact?"1":"0"}>Contacto</span><span data-ok={row.completed?"1":"0"}>Pre check-in</span><span data-ok={row.hasDocument?"1":"0"}>Documento</span><span data-ok={row.docs.length===0||row.documentVerified?"1":"0"}>Validación</span></div>{row.serviceRequests.length?<div className={s.request}>Solicita · {row.serviceRequests.join(" · ")}</div>:row.openRequests.length?<div className={s.request}>Pedido pendiente · {row.openRequests[0].kind||"solicitud"}</div>:null}</div><div className={s.cardActions}>{!row.completed?<button type="button" disabled={busy===row.id} onClick={()=>createLink(row)}>{busy===row.id?"Generando…":row.check?"Nuevo enlace":"Generar enlace"}</button>:<span className={s.ready}>✓ Recibido</span>}</div></article>):<div className={s.empty}>No hay llegadas próximas dentro de los próximos 21 días.</div>}</div><footer className={s.foot}><span><i data-tone="green"/> Completo</span><span><i data-tone="yellow"/> Excepción</span><span><i data-tone="blue"/> En curso</span><p>La foto del documento no se marca como validada sin evidencia real; el número y la firma del pre check-in sí quedan trazados.</p></footer></section>
}
