"use client"

import{useEffect,useMemo,useState}from"react"
import useGuestsData from"./useGuestsData"
import GuestDossier from"./GuestDossier"
import GuestJourneyPanel from"./GuestJourneyPanel"
import GuestSegmentsPanel from"./GuestSegmentsPanel"
import PmsIcon from"../../components/shell/PmsIcons"
import{crmSignals,marketingState,segmentById,segmentCounts}from"./guestCrm"
import{fmtDate,guestState,initials}from"./guestView"
import s from"./guests.module.css"

export default function GuestsWorkspace({propertyId,onNavigate,allowedViews=[]}){
  const[query,setQuery]=useState(""),[debouncedQuery,setDebouncedQuery]=useState("")
  const[activeSegment,setActiveSegment]=useState(""),[selectedId,setSelectedId]=useState(""),[selectedFallback,setSelectedFallback]=useState(null)
  const[overlay,setOverlay]=useState(""),[formOpen,setFormOpen]=useState(false),[saving,setSaving]=useState(false),[draft,setDraft]=useState(null)
  useEffect(()=>{const timer=setTimeout(()=>setDebouncedQuery(query.trim()),260);return()=>clearTimeout(timer)},[query])
  const data=useGuestsData(propertyId,debouncedQuery)
  const segment=activeSegment==="group"?null:segmentById(activeSegment)
  const counts=useMemo(()=>segmentCounts(data.guests),[data.guests])
  const groupCount=useMemo(()=>data.guests.filter(item=>(item.groupStays||0)>0).length,[data.guests])
  const signalCount=useMemo(()=>data.guests.filter(item=>crmSignals(item).length>0).length,[data.guests])
  const liveSelected=useMemo(()=>data.guests.find(item=>item.id===selectedId)||null,[data.guests,selectedId])
  const selected=liveSelected||selectedFallback
  const filtered=useMemo(()=>data.guests.filter(item=>(activeSegment==="group"?(item.groupStays||0)>0:(!segment||segment.match(item)))),[data.guests,activeSegment,segment])
  useEffect(()=>{if(liveSelected)setSelectedFallback(liveSelected)},[liveSelected])
  useEffect(()=>{if(data.loading||typeof window==="undefined")return;const id=new URL(window.location.href).searchParams.get("guest_profile");if(id&&id!==selectedId){const found=data.guests.find(item=>item.id===id);if(found){setSelectedId(id);setSelectedFallback(found)}}},[data.loading,data.guests,selectedId])

  function setProfileUrl(id){if(typeof window==="undefined")return;const url=new URL(window.location.href);if(id)url.searchParams.set("guest_profile",id);else url.searchParams.delete("guest_profile");window.history.replaceState(window.history.state,"",url)}
  function openProfile(item){setSelectedId(item.id);setSelectedFallback(item);setProfileUrl(item.id)}
  function closeProfile(){setSelectedId("");setSelectedFallback(null);setProfileUrl("")}
  function chooseSegment(id){setActiveSegment(id);setOverlay("")}
  function openNew(){setDraft({full_name:"",email:"",phone:"",birth_date:"",document_type:"DNI",document_number:"",country:"Argentina",nationality:"Argentina",language:"es",vip_level:"standard",notes:""});data.setError("");setFormOpen(true)}
  function openEdit(){if(!selected)return;setDraft({id:selected.id,full_name:selected.full_name||"",email:selected.email||"",phone:selected.phone||"",birth_date:selected.birth_date||"",document_type:selected.document_type||"DNI",document_number:selected.document_number||"",country:selected.country||"",nationality:selected.nationality||"",language:selected.language||"es",vip_level:selected.vip_level||"standard",notes:selected.notes||""});data.setError("");setFormOpen(true)}
  async function updateSelected(patch){if(!selected)return;data.setError("");try{const updated=await data.updateGuest(selected.id,patch);setSelectedFallback(current=>current?{...current,...updated}:updated);return updated}catch(err){data.setError(err?.message||"No se pudo actualizar el huésped.");throw err}}
  async function saveDraft(){if(!draft?.full_name?.trim())return data.setError("Ingresá el nombre del huésped.");setSaving(true);data.setError("");try{const payload={full_name:draft.full_name.trim(),email:draft.email?.trim()||null,phone:draft.phone?.trim()||null,birth_date:draft.birth_date||null,document_type:draft.document_type||null,document_number:draft.document_number?.trim()||null,country:draft.country?.trim()||null,nationality:draft.nationality?.trim()||null,language:draft.language||"es",vip_level:draft.vip_level||"standard",notes:draft.notes?.trim()||null};if(draft.id){const updated=await data.updateGuest(draft.id,payload);setSelectedId(updated.id);setSelectedFallback(current=>current?{...current,...updated}:updated)}else await data.createGuest(payload);setFormOpen(false);setDraft(null)}catch(err){data.setError(err?.message||"No se pudo guardar el huésped.")}finally{setSaving(false)}}

  const segmentButtonStyle={minWidth:0,width:"100%",height:30,padding:"0 4px",display:"inline-flex",alignItems:"center",justifyContent:"center",gap:3,fontFamily:"inherit",fontSize:10,fontWeight:800,lineHeight:1,letterSpacing:0,whiteSpace:"nowrap",overflow:"hidden"}
  const segmentCountStyle={margin:0,flex:"0 0 auto",fontFamily:"inherit",fontSize:10,fontWeight:900,lineHeight:1}

  return <section className={s.page}>
    <header className={s.heading}><div><small>GUESTBOOK · CRM HOTELERO</small><h1>Huéspedes</h1><p>Una ficha viva por huésped: estadías, preferencias y oportunidades en un solo lugar.</p></div><div className={s.headerActions}><button type="button" className={s.softButton} onClick={()=>setOverlay("segments")}><PmsIcon name="filter"/>Segmentos</button><button type="button" className={s.softButton} onClick={()=>setOverlay("journey")}><PmsIcon name="calendar"/>Pre check-in</button><button type="button" className={s.primary} onClick={openNew}><PmsIcon name="plus"/>Agregar huésped</button></div></header>
    {data.error&&<div className={s.errorBanner}>{data.error}</div>}
    <div className={s.workspace}>
      <aside className={s.indexPanel}>
        <div className={s.indexHead}><div><small>ÍNDICE DEL GUESTBOOK</small><b>{data.totalProfiles} perfiles</b><em>{data.limited&&!debouncedQuery?`Mostrando ${data.guests.length} recientes`:debouncedQuery?`${data.guests.length} resultados`:"Todos cargados"}</em></div><span className={s.signalPill}>{signalCount} señales</span></div>
        <label className={s.search}><PmsIcon name="search"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar nombre, teléfono o documento"/></label>
        <div className={s.segmentStrip} style={{display:"grid",gridTemplateColumns:"1.12fr 1fr .96fr",gap:4,overflow:"visible"}}><button type="button" style={segmentButtonStyle} className={!activeSegment?s.segmentActive:""} onClick={()=>setActiveSegment("")}><span>Recientes</span><b style={segmentCountStyle}>{data.guests.length}</b></button><button type="button" style={segmentButtonStyle} className={activeSegment==="group"?s.segmentActive:""} onClick={()=>setActiveSegment(activeSegment==="group"?"":"group")}><span>En grupos</span><b style={segmentCountStyle}>{groupCount}</b></button><button type="button" style={segmentButtonStyle} className={activeSegment==="upcoming"?s.segmentActive:""} onClick={()=>setActiveSegment(activeSegment==="upcoming"?"":"upcoming")}><span>Próximas</span><b style={segmentCountStyle}>{counts.upcoming||0}</b></button></div>
        {activeSegment?<div className={s.segmentContext}><span>{activeSegment==="group"?"Con estadías grupales":segment?.label}</span><button type="button" onClick={()=>setActiveSegment("")} aria-label="Quitar filtro"><PmsIcon name="close" size={14}/></button></div>:null}
        <div className={s.guestList}>{data.loading?<div className={s.empty}>Cargando guestbook…</div>:filtered.map(item=>{const itemState=guestState(item),contact=marketingState(item);return <button type="button" key={item.id} className={`${s.guestRow} ${selectedId===item.id?s.guestRowActive:""}`} onClick={()=>openProfile(item)}><span className={s.avatar}>{initials(item.full_name)}</span><span className={s.guestIdentity}><b>{item.full_name}</b><small>{item.nextStay?`Llega ${fmtDate(item.nextStay)}`:item.lastStay?`Última ${fmtDate(item.lastStay)}`:"Sin estadías"}</small></span><span className={s.guestMeta}><i data-tone={itemState.tone}/><small>{item.groupStays?`${item.groupStays} grupal${item.groupStays===1?"":"es"}`:itemState.label}</small>{contact.canEmail||contact.canWhatsapp?<em title="Contacto autorizado">●</em>:null}</span></button>})}{!data.loading&&!filtered.length?<div className={s.empty}>{debouncedQuery?"No encontramos huéspedes con esa búsqueda.":"No hay huéspedes que coincidan con este filtro."}</div>:null}</div>
      </aside>
      <section className={s.stage}>{selected?<GuestDossier selected={selected} reservations={data.reservations} onUpdate={updateSelected} onOpenEdit={openEdit} onClose={closeProfile} onNavigate={onNavigate} allowedViews={allowedViews}/>:<div className={s.welcome}><div className={s.welcomeMark}><PmsIcon name="guest" size={30}/></div><small>GUESTBOOK</small><h2>Elegí un huésped del índice</h2><p>La ficha reúne contexto, historial y preferencias sin cargar toda la base al mismo tiempo.</p><div className={s.welcomeStats}><span><b>{data.totalProfiles}</b> perfiles</span><span><b>{data.guests.length}</b> cargados ahora</span><span><b>{counts.upcoming||0}</b> próximas llegadas</span><span><b>{signalCount}</b> señales</span></div></div>}</section>
    </div>
    {overlay?<div className={s.overlay} onMouseDown={event=>event.target===event.currentTarget&&setOverlay("")}><section className={s.overlayPanel}><header><div><small>{overlay==="segments"?"CRM INTELIGENTE":"EXPERIENCIA DEL HUÉSPED"}</small><h2>{overlay==="segments"?"Segmentos y oportunidades":"Pre check-in y excepciones"}</h2></div><button type="button" className={s.actionRed} onClick={()=>setOverlay("")} aria-label="Cerrar"><PmsIcon name="close"/></button></header><div className={s.overlayBody}>{overlay==="segments"?<GuestSegmentsPanel guests={data.guests} activeSegment={activeSegment} onSegment={chooseSegment} initialExpanded/>:<GuestJourneyPanel propertyId={propertyId}/>}</div></section></div>:null}
    {formOpen&&draft?<div className={s.overlay} onMouseDown={event=>event.target===event.currentTarget&&setFormOpen(false)}><section className={s.formModal}><header><div><small>{draft.id?"EDITAR FICHA":"NUEVO HUÉSPED"}</small><h2>{draft.id?draft.full_name:"Agregar huésped"}</h2></div><button type="button" className={s.actionRed} onClick={()=>setFormOpen(false)} aria-label="Cerrar"><PmsIcon name="close"/></button></header><div className={s.formGrid}><label className={s.wide}>Nombre completo<input value={draft.full_name} onChange={event=>setDraft(value=>({...value,full_name:event.target.value}))} autoFocus/></label><label>Email<input type="email" value={draft.email||""} onChange={event=>setDraft(value=>({...value,email:event.target.value}))}/></label><label>Teléfono<input value={draft.phone||""} onChange={event=>setDraft(value=>({...value,phone:event.target.value}))}/></label><label>Fecha de nacimiento<input type="date" value={draft.birth_date||""} onChange={event=>setDraft(value=>({...value,birth_date:event.target.value}))}/></label><label>Idioma<select value={draft.language||"es"} onChange={event=>setDraft(value=>({...value,language:event.target.value}))}><option value="es">Español</option><option value="en">English</option><option value="pt">Português</option></select></label><label>Tipo de documento<select value={draft.document_type||"DNI"} onChange={event=>setDraft(value=>({...value,document_type:event.target.value}))}><option value="DNI">DNI</option><option value="Pasaporte">Pasaporte</option><option value="CI">CI</option><option value="Otro">Otro</option></select></label><label>Número de documento<input value={draft.document_number||""} onChange={event=>setDraft(value=>({...value,document_number:event.target.value}))}/></label><label>País<input value={draft.country||""} onChange={event=>setDraft(value=>({...value,country:event.target.value}))}/></label><label>Nacionalidad<input value={draft.nationality||""} onChange={event=>setDraft(value=>({...value,nationality:event.target.value}))}/></label><label>Nivel<select value={draft.vip_level||"standard"} onChange={event=>setDraft(value=>({...value,vip_level:event.target.value}))}><option value="standard">Estándar</option><option value="frequent">Habitual</option><option value="vip">VIP</option><option value="signature">Signature</option></select></label><label className={s.wide}>Notas internas<textarea value={draft.notes||""} onChange={event=>setDraft(value=>({...value,notes:event.target.value}))}/></label></div>{data.error?<div className={s.formError}>{data.error}</div>:null}<footer><button type="button" className={s.cancelButton} onClick={()=>setFormOpen(false)}>Cancelar</button><button type="button" className={s.saveButton} disabled={saving} onClick={saveDraft}>{saving?"Guardando…":"Guardar huésped"}</button></footer></section></div>:null}
  </section>
}
