"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../lib/supabase"

export default function PlatformAdmin(){
  const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(""),[query,setQuery]=useState("")
  async function load(){setLoading(true);setError("");const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return}const{data,error}=await supabase.rpc("hl_platform_admin_properties");if(error){setError(error.message);setLoading(false);return}if(data?.error==="forbidden"){setError("Tu usuario no tiene acceso al panel interno.");setLoading(false);return}setRows(data?.properties||[]);setLoading(false)}
  useEffect(()=>{load()},[])
  async function save(row){setSaving(row.id);setError("");const{error}=await supabase.rpc("hl_platform_admin_set_control",{p_property_id:row.id,p_account_enabled:row.account_enabled,p_maintenance_mode:row.maintenance_mode,p_notes:row.notes||null});if(error)setError(error.message);else await load();setSaving("")}
  function patch(id,values){setRows(list=>list.map(row=>row.id===id?{...row,...values}:row))}
  const visible=useMemo(()=>{const term=query.trim().toLowerCase();return term?rows.filter(row=>`${row.name} ${row.city||""} ${row.engine_slug||""} ${row.notes||""}`.toLowerCase().includes(term)):rows},[rows,query])
  const totals=useMemo(()=>({properties:rows.length,enabled:rows.filter(row=>row.account_enabled&&!row.maintenance_mode).length,rooms:rows.reduce((sum,row)=>sum+Number(row.rooms||0),0),future:rows.reduce((sum,row)=>sum+Number(row.future_reservations||0),0),engines:rows.filter(row=>row.engine_enabled).length,payments:rows.filter(row=>row.payment_status==="connected").length}),[rows])
  const card={border:"1px solid #e3e7ef",borderRadius:16,background:"#fff",padding:18},input={width:"100%",boxSizing:"border-box",border:"1px solid #d8deea",borderRadius:8,padding:"9px 10px",font:"inherit"},pill=(ok)=>({display:"inline-flex",alignItems:"center",minHeight:25,padding:"0 8px",borderRadius:999,background:ok?"#edf9f1":"#f4f6f9",color:ok?"#187343":"#687386",fontSize:10,fontWeight:900}),action={height:34,border:"1px solid #d8deea",borderRadius:8,background:"#fff",color:"#475569",padding:"0 10px",fontWeight:800,textDecoration:"none",display:"inline-flex",alignItems:"center",cursor:"pointer"}
  return <main style={{minHeight:"100vh",background:"#f4f6fb",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#1e293b"}}><div style={{maxWidth:1380,margin:"0 auto"}}>
    <header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:20}}><div><small style={{fontWeight:900,letterSpacing:1.2,color:"#5567d8"}}>HABITACIÓN LLENA · INTERNO</small><h1 style={{margin:"5px 0",fontSize:31}}>Panel de plataforma</h1><p style={{margin:0,color:"#64748b"}}>Clientes, salud operativa y controles de plataforma sin tocar código.</p></div><div style={{display:"flex",gap:9}}><button style={action} onClick={load}>Actualizar</button><a href="/pms-next" style={action}>Volver al PMS</a></div></header>
    {error&&<div style={{marginTop:14,padding:12,borderRadius:10,background:"#fff1f2",color:"#be123c"}}>{error}</div>}
    {!loading&&<><div style={{display:"grid",gridTemplateColumns:"repeat(6,minmax(0,1fr))",gap:9,marginTop:14}}>{[["Hoteles",totals.properties],["Operativos",totals.enabled],["Habitaciones",totals.rooms],["Reservas futuras",totals.future],["Motores activos",totals.engines],["Mercado Pago",totals.payments]].map(([label,value])=><article key={label} style={{...card,padding:14}}><small style={{display:"block",color:"#718096",fontSize:10,fontWeight:850}}>{label}</small><b style={{display:"block",fontSize:25,marginTop:5}}>{value}</b></article>)}</div><label style={{display:"block",marginTop:10}}><input style={{...input,height:42}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar hotel, ciudad, motor o nota interna…"/></label></>}
    {loading?<div style={{...card,marginTop:14}}>Cargando propiedades…</div>:<div style={{display:"grid",gap:10,marginTop:10}}>{visible.map(row=><article key={row.id} style={card}>
      <div style={{display:"grid",gridTemplateColumns:"1.15fr .85fr .8fr .85fr",gap:14,alignItems:"start"}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><b style={{fontSize:16}}>{row.name}</b><span style={pill(row.account_enabled&&!row.maintenance_mode)}>{!row.account_enabled?"Suspendido":row.maintenance_mode?"Mantenimiento":"Operativo"}</span></div><small style={{display:"block",marginTop:5,color:"#64748b"}}>{row.city||"Sin ciudad"} · alta {new Intl.DateTimeFormat("es-AR",{dateStyle:"short"}).format(new Date(row.created_at))}</small><div style={{display:"flex",gap:6,marginTop:9,flexWrap:"wrap"}}><span style={pill(row.engine_enabled)}>{row.engine_enabled?"Motor activo":"Sin motor"}</span><span style={pill(row.payment_status==="connected")}>{row.payment_status==="connected"?"MP conectado":"Sin MP"}</span><span style={pill(Number(row.open_maintenance||0)===0)}>{row.open_maintenance||0} mantenimiento</span></div></div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{[["Habitaciones",row.rooms],["Reservas",row.reservations],["Futuras",row.future_reservations],["Alojados",row.inhouse],["Miembros",row.members],["Última reserva",row.last_reservation_at?new Intl.DateTimeFormat("es-AR",{dateStyle:"short"}).format(new Date(row.last_reservation_at)):"—"]].map(([label,value])=><div key={label} style={{padding:9,borderRadius:9,background:"#f7f8fb"}}><small style={{display:"block",fontSize:9,color:"#7a8497"}}>{label}</small><b style={{display:"block",fontSize:12,marginTop:3}}>{value??0}</b></div>)}</div>
      <div style={{display:"grid",gap:8}}><label style={{fontSize:10,fontWeight:850}}>Cuenta<select style={input} value={row.account_enabled?"yes":"no"} onChange={e=>patch(row.id,{account_enabled:e.target.value==="yes"})}><option value="yes">Activa</option><option value="no">Suspendida</option></select></label><label style={{fontSize:10,fontWeight:850}}>Mantenimiento<select style={input} value={row.maintenance_mode?"yes":"no"} onChange={e=>patch(row.id,{maintenance_mode:e.target.value==="yes"})}><option value="no">Desactivado</option><option value="yes">Activado</option></select></label></div>
      <div><label style={{fontSize:10,fontWeight:850}}>Nota interna<input style={input} value={row.notes||""} onChange={e=>patch(row.id,{notes:e.target.value})} placeholder="Onboarding, deuda, incidencia…"/></label><div style={{display:"flex",gap:7,marginTop:9,flexWrap:"wrap"}}>{row.engine_slug&&<><a href={`/book/${row.engine_slug}`} target="_blank" rel="noreferrer" style={action}>Motor ↗</a><a href={`/hotel/${row.engine_slug}`} target="_blank" rel="noreferrer" style={action}>Web ↗</a></>}<button onClick={()=>navigator.clipboard?.writeText(row.id)} style={action}>Copiar ID</button><button onClick={()=>save(row)} disabled={saving===row.id} style={{...action,background:"#5366df",color:"#fff",borderColor:"#5366df"}}>{saving===row.id?"Guardando…":"Guardar"}</button></div></div></div>
    </article>)}{!visible.length?<div style={card}>No hay hoteles que coincidan con la búsqueda.</div>:null}</div>}
  </div></main>
}
