"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../../lib/supabase"
import GuestIcon from"./GuestIcon"
import s from"./guestPortalApp.module.css"

const ACTIONS=[
 {kind:"towels",icon:"towels",area:"housekeeping"},{kind:"pillows",icon:"bed",area:"housekeeping"},{kind:"cleaning",icon:"cleaning",area:"housekeeping"},{kind:"maintenance",icon:"tools",area:"maintenance"},{kind:"late_checkout",icon:"clock",area:"reception"},{kind:"other",icon:"message",area:"reception"}
]
const COPY={
 es:{hello:"Hola",question:"¿En qué te podemos ayudar?",home:"Inicio",stay:"Estadía",services:"Servicios",explore:"Explorar",hotel:"Hotel",help:"Ayuda",room:"Hab.",checkout:"Salida",staySub:"Reserva, cuenta y opinión",servicesSub:"Pedí lo que necesites",hotelSub:"Wi‑Fi, guía y horarios",exploreSub:"Lugares recomendados",openOne:"Tenés 1 pedido en curso",openMany:"Tenés {n} pedidos en curso",track:"Ver estado",wifi:"Wi‑Fi",network:"Red",password:"Contraseña",copy:"Copiar",copied:"Copiada",account:"Tu estadía",booking:"Reserva",total:"Total",paid:"Pagado",balance:"Saldo",feedback:"¿Cómo viene tu estadía?",feedbackSub:"Contanos ahora y podemos ayudarte mientras seguís en el hotel.",sendFeedback:"Enviar opinión",feedbackThanks:"Gracias. Lo recibimos.",feedbackAlert:"Gracias por contarnos. Recepción ya recibió un aviso para poder ayudarte.",guide:"Guía del hotel",guideEmpty:"El hotel todavía no cargó información adicional.",nearby:"Cerca del hotel",nearbyEmpty:"Todavía no hay recomendaciones cargadas.",request:"Pedir",roomService:"Room service",roomServiceSub:"Pedí algo a la habitación",roomServiceSoon:"El hotel todavía no publicó artículos para room service.",serviceFee:"Cargo de servicio",subtotal:"Subtotal",sendOrder:"Enviar pedido",olivia:"OlivIA para tu estadía",oliviaSub:"Preguntá por el hotel o pedí algo con tus propias palabras.",askOlivia:"Preguntarle a OlivIA",reception:"Recepción",receptionSub:"Escribí directamente al equipo",message:"Abrir chat",whatsapp:"WhatsApp",private:"Acceso privado de tu estadía",requestSent:"Listo. El pedido ya fue enviado.",actionConfirm:"Entendí este pedido",confirmSend:"Enviar solicitud",cancel:"Cancelar",typeMessage:"Escribí como te salga…",thinking:"Pensando…",notConfigured:"Consultar en recepción",lateApproved:"Late check-out aprobado",rating1:"Muy mal",rating2:"Mal",rating3:"Regular",rating4:"Bien",rating5:"Excelente"},
 en:{hello:"Hi",question:"How can we help?",home:"Home",stay:"Stay",services:"Services",explore:"Explore",hotel:"Hotel",help:"Help",room:"Room",checkout:"Check-out",staySub:"Booking, account and feedback",servicesSub:"Request what you need",hotelSub:"Wi‑Fi, guide and hours",exploreSub:"Nearby recommendations",openOne:"You have 1 active request",openMany:"You have {n} active requests",track:"View status",wifi:"Wi‑Fi",network:"Network",password:"Password",copy:"Copy",copied:"Copied",account:"Your stay",booking:"Booking",total:"Total",paid:"Paid",balance:"Balance",feedback:"How is your stay going?",feedbackSub:"Tell us now so we can help while you're still here.",sendFeedback:"Send feedback",feedbackThanks:"Thank you. We received it.",feedbackAlert:"Thanks for telling us. Reception has been notified so they can help.",guide:"Hotel guide",guideEmpty:"The hotel has not added more information yet.",nearby:"Near the hotel",nearbyEmpty:"No recommendations have been added yet.",request:"Request",roomService:"Room service",roomServiceSub:"Order to your room",roomServiceSoon:"The hotel has not published room-service items yet.",serviceFee:"Service fee",subtotal:"Subtotal",sendOrder:"Send order",olivia:"OlivIA for your stay",oliviaSub:"Ask about the hotel or request something in your own words.",askOlivia:"Ask OlivIA",reception:"Reception",receptionSub:"Message the hotel team directly",message:"Open chat",whatsapp:"WhatsApp",private:"Private access for your stay",requestSent:"Done. Your request was sent.",actionConfirm:"I understood this request",confirmSend:"Send request",cancel:"Cancel",typeMessage:"Type naturally…",thinking:"Thinking…",notConfigured:"Ask reception",lateApproved:"Late check-out approved",rating1:"Very bad",rating2:"Bad",rating3:"Okay",rating4:"Good",rating5:"Excellent"},
 pt:{hello:"Olá",question:"Como podemos ajudar?",home:"Início",stay:"Estadia",services:"Serviços",explore:"Explorar",hotel:"Hotel",help:"Ajuda",room:"Quarto",checkout:"Saída",staySub:"Reserva, conta e opinião",servicesSub:"Peça o que precisar",hotelSub:"Wi‑Fi, guia e horários",exploreSub:"Lugares recomendados",openOne:"Você tem 1 pedido em andamento",openMany:"Você tem {n} pedidos em andamento",track:"Ver status",wifi:"Wi‑Fi",network:"Rede",password:"Senha",copy:"Copiar",copied:"Copiada",account:"Sua estadia",booking:"Reserva",total:"Total",paid:"Pago",balance:"Saldo",feedback:"Como está sua estadia?",feedbackSub:"Conte agora e podemos ajudar enquanto você ainda está no hotel.",sendFeedback:"Enviar opinião",feedbackThanks:"Obrigado. Recebemos.",feedbackAlert:"Obrigado por contar. A recepção já recebeu um aviso para poder ajudar.",guide:"Guia do hotel",guideEmpty:"O hotel ainda não adicionou informações.",nearby:"Perto do hotel",nearbyEmpty:"Ainda não há recomendações.",request:"Pedir",roomService:"Room service",roomServiceSub:"Peça algo no quarto",roomServiceSoon:"O hotel ainda não publicou itens de room service.",serviceFee:"Taxa de serviço",subtotal:"Subtotal",sendOrder:"Enviar pedido",olivia:"OlivIA para sua estadia",oliviaSub:"Pergunte sobre o hotel ou peça algo com suas palavras.",askOlivia:"Perguntar à OlivIA",reception:"Recepção",receptionSub:"Fale diretamente com a equipe",message:"Abrir chat",whatsapp:"WhatsApp",private:"Acesso privado da sua estadia",requestSent:"Pronto. O pedido foi enviado.",actionConfirm:"Entendi este pedido",confirmSend:"Enviar solicitação",cancel:"Cancelar",typeMessage:"Escreva do seu jeito…",thinking:"Pensando…",notConfigured:"Consultar recepção",lateApproved:"Late check-out aprovado",rating1:"Muito ruim",rating2:"Ruim",rating3:"Regular",rating4:"Bom",rating5:"Excelente"}
}
const ACTION_LABELS={
 es:{towels:["Toallas","Housekeeping"],pillows:["Almohadas","Housekeeping"],cleaning:["Limpieza","Housekeeping"],maintenance:["Reportar un problema","Mantenimiento"],late_checkout:["Late check-out","Recepción aprueba"],other:["Otro pedido","Recepción"]},
 en:{towels:["Towels","Housekeeping"],pillows:["Pillows","Housekeeping"],cleaning:["Room cleaning","Housekeeping"],maintenance:["Report an issue","Maintenance"],late_checkout:["Late check-out","Reception approves"],other:["Other request","Reception"]},
 pt:{towels:["Toalhas","Housekeeping"],pillows:["Travesseiros","Housekeeping"],cleaning:["Limpeza","Housekeeping"],maintenance:["Reportar problema","Manutenção"],late_checkout:["Late check-out","Recepção aprova"],other:["Outro pedido","Recepção"]}
}
const fmtMoney=(v,c="ARS",l="es")=>new Intl.NumberFormat(l==="en"?"en-US":l==="pt"?"pt-BR":"es-AR",{style:"currency",currency:c,maximumFractionDigits:0}).format(Number(v)||0)
const fmtDate=(v,l="es")=>v?new Intl.DateTimeFormat(l==="en"?"en-US":l==="pt"?"pt-BR":"es-AR",{day:"2-digit",month:"short"}).format(new Date(`${String(v).slice(0,10)}T12:00:00`)).replace(".",""):"—"
const localized=(item,l,key)=>item?.[`${key}_${l}`]||item?.[key]||""

export default function GuestPortalApp({token,snapshot,onRefresh,onOpenChat,onOpenActivity,activityCount=0,onOpenAssistant}){
 const guide=snapshot?.guide||{},hotel=snapshot?.hotel||{},stay=snapshot?.stay||{},account=snapshot?.account
 const allowed=Array.isArray(guide.languages)&&guide.languages.length?guide.languages:["es"],storageKey=`hl:stay-lang:${token.slice(0,12)}`
 const[lang,setLang]=useState(()=>guide.default_language||"es"),[view,setView]=useState("home"),[selected,setSelected]=useState(null),[detail,setDetail]=useState(""),[notice,setNotice]=useState(""),[sending,setSending]=useState(false),[copied,setCopied]=useState(false),[rating,setRating]=useState(0),[feedbackText,setFeedbackText]=useState(""),[feedbackNotice,setFeedbackNotice]=useState(""),[roomOpen,setRoomOpen]=useState(false),[cart,setCart]=useState({}),[aiOpen,setAiOpen]=useState(false),[aiText,setAiText]=useState(""),[aiBusy,setAiBusy]=useState(false),[aiHistory,setAiHistory]=useState([]),[aiAction,setAiAction]=useState(null)
 const tr=COPY[lang]||COPY.es,labels=ACTION_LABELS[lang]||ACTION_LABELS.es,firstName=String(snapshot?.guest?.name||"").trim().split(/\s+/)[0]||""
 const enabled={towels:true,pillows:true,cleaning:true,maintenance:true,late_checkout:true,other:true,...(guide.enabled_actions||{})}
 const active=(snapshot?.requests||[]).filter(x=>!["resolved","cancelled"].includes(x.status))
 const roomCfg={enabled:false,service_fee_type:"none",service_fee_value:0,catalog:[],...(guide.room_service_config||{})},feedbackCfg={enabled:true,during_stay:true,...(guide.feedback_config||{})},aiCfg={enabled:true,...(guide.guest_ai_config||{})}
 const catalog=Array.isArray(roomCfg.catalog)?roomCfg.catalog.filter(x=>x&&x.enabled!==false):[]
 const cartRows=catalog.map((item,i)=>({...item,key:String(item.id||i),qty:Number(cart[String(item.id||i)]||0)})).filter(x=>x.qty>0)
 const subtotal=cartRows.reduce((sum,x)=>sum+(Number(x.price)||0)*x.qty,0),fee=roomCfg.service_fee_type==="percent"?subtotal*(Number(roomCfg.service_fee_value)||0)/100:roomCfg.service_fee_type==="fixed"?(Number(roomCfg.service_fee_value)||0):0
 useEffect(()=>{try{const saved=localStorage.getItem(storageKey);setLang(saved&&allowed.includes(saved)?saved:allowed.includes(guide.default_language)?guide.default_language:allowed[0])}catch{setLang(allowed.includes(guide.default_language)?guide.default_language:allowed[0])}},[storageKey,guide.default_language,allowed.join("|")])
 useEffect(()=>{if(token)track("app_open",{lang})},[])
 function track(event,meta={}){if(!token||token==="demo")return;void Promise.resolve(supabase.rpc("hl_guest_stay_portal_track",{p_token:token,p_event:event,p_meta:meta})).catch(()=>{})}
 function go(next){setView(next);track("view_open",{view:next});window.scrollTo({top:0,behavior:"smooth"})}
 function language(next){setLang(next);try{localStorage.setItem(storageKey,next)}catch{};track("language_changed",{language:next})}
 async function copyWifi(){if(!guide.wifi_password)return;try{await navigator.clipboard.writeText(guide.wifi_password);setCopied(true);setTimeout(()=>setCopied(false),1300);track("wifi_copied")}catch{}}
 async function sendRequest(kind,requestDetail){setSending(true);setNotice("");const{data,error}=await supabase.rpc("hl_guest_stay_portal_request",{p_token:token,p_kind:kind,p_detail:requestDetail||null});setSending(false);if(error||!data?.ok){setNotice("No pudimos enviar el pedido. Probá nuevamente.");return false}setNotice(tr.requestSent);track("request_confirmed",{kind});await onRefresh?.();return true}
 async function submitAction(e){e.preventDefault();if(!selected)return;const ok=await sendRequest(selected.kind,detail.trim()||null);if(ok)setTimeout(()=>{setSelected(null);setDetail("");setNotice("")},900)}
 async function submitFeedback(){if(!rating)return;setSending(true);const{data,error}=await supabase.rpc("hl_guest_stay_portal_feedback",{p_token:token,p_score:rating,p_comment:feedbackText.trim()||null});setSending(false);setFeedbackNotice(error||!data?.ok?"No pudimos enviarlo.":data.needs_attention?tr.feedbackAlert:tr.feedbackThanks);if(data?.ok)track("feedback_complete",{score:rating})}
 async function submitRoom(){if(!cartRows.length)return;const lines=cartRows.map(x=>`${x.qty}x ${x.name||x.title||"Artículo"}`).join(", "),detailText=`Room service · ${lines} · ${tr.subtotal}: ${fmtMoney(subtotal,account?.currency||"ARS",lang)}${fee>0?` · ${tr.serviceFee}: ${fmtMoney(fee,account?.currency||"ARS",lang)}`:""}`;const ok=await sendRequest("other",detailText);if(ok){track("room_service_request",{items:cartRows.length,subtotal,fee});setCart({});setRoomOpen(false)}}
 async function askAi(e){e.preventDefault();const q=aiText.trim();if(!q||aiBusy)return;setAiBusy(true);setAiText("");setAiHistory(h=>[...h,{role:"user",text:q}]);setAiAction(null);try{const res=await fetch("/api/guest-assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,question:q,history:aiHistory.slice(-8)})}),data=await res.json();const answer=data?.answer||"No pude responder ahora.";setAiHistory(h=>[...h,{role:"assistant",text:answer}]);if(data?.action)setAiAction({...data.action,source:q});track("assistant_question",{has_action:Boolean(data?.action)})}catch{setAiHistory(h=>[...h,{role:"assistant",text:"No pude responder ahora. Podés escribirle directamente a Recepción."}])}finally{setAiBusy(false)}}
 async function confirmAi(){if(!aiAction)return;const ok=await sendRequest(aiAction.kind,aiAction.detail||aiAction.source);if(ok){if(token!="demo")await Promise.resolve(supabase.rpc("hl_guest_portal_learn_phrase",{p_token:token,p_phrase:aiAction.source,p_intent:aiAction.kind})).catch(()=>{});setAiHistory(h=>[...h,{role:"assistant",text:tr.requestSent}]);setAiAction(null)}}
 const mainCards=[{view:"stay",icon:"room",title:tr.stay,sub:tr.staySub,tone:"violet"},{view:"services",icon:"bell",title:tr.services,sub:tr.servicesSub,tone:"blue"},{view:"hotel",icon:"hotel",title:tr.hotel,sub:tr.hotelSub,tone:"mint"},{view:"explore",icon:"pin",title:tr.explore,sub:tr.exploreSub,tone:"sand"}]
 const nav=[{v:"home",i:"home",t:tr.home},{v:"stay",i:"room",t:tr.stay},{v:"services",i:"bell",t:tr.services},{v:"explore",i:"pin",t:tr.explore},{v:"hotel",i:"hotel",t:tr.hotel},{v:"help",i:"message",t:tr.help}]
 return <main className={s.shell} style={{"--accent":hotel.accent_color||guide.accent_color||"#6474df"}}><div className={s.phone}>
  <header className={`${s.hero} ${view!=="home"?s.heroCompact:""}`} style={hotel.cover?{backgroundImage:`linear-gradient(145deg,rgba(22,31,48,.86),rgba(55,69,112,.80)),url(${hotel.cover})`}:undefined}><div className={s.brand}><span className={s.logo}>{hotel.logo?<img src={hotel.logo} alt=""/>:String(hotel.name||"H")[0]}</span><div><small>{tr.private}</small><b>{hotel.name||"Hotel"}</b></div><select value={lang} onChange={e=>language(e.target.value)}>{allowed.filter(x=>COPY[x]).map(x=><option value={x} key={x}>{x.toUpperCase()}</option>)}</select></div>{view==="home"?<><div className={s.greeting}><small>{tr.hello}, {firstName}</small><h1>{localized(guide.translations?.[lang],lang,"portal_title")||guide.translations?.[lang]?.portal_title||guide.title||tr.question}</h1><p>{guide.translations?.[lang]?.welcome_message||hotel.welcome||""}</p></div><div className={s.stayStrip}><span><GuestIcon name="room" size={18}/><b>{tr.room} {stay.room?.name||"—"}</b><small>{stay.room?.type||""}</small></span><span><GuestIcon name="calendar" size={18}/><b>{fmtDate(stay.arrival,lang)} → {fmtDate(stay.departure,lang)}</b><small>{tr.checkout} {guide.checkout_time||"—"}</small></span></div></>:<div className={s.pageTitle}><button onClick={()=>go("home")} type="button">‹</button><div><small>{hotel.name}</small><h1>{nav.find(x=>x.v===view)?.t}</h1></div></div>}</header>
  <div className={s.content}>
   {view==="home"?<div className={s.home}><div className={s.mainGrid}>{mainCards.map(c=><button type="button" key={c.view} data-tone={c.tone} onClick={()=>go(c.view)}><i><GuestIcon name={c.icon} size={24}/></i><b>{c.title}</b><small>{c.sub}</small></button>)}</div>{active.length?<button type="button" className={s.activeBar} onClick={onOpenActivity}><span/><div><b>{active.length===1?tr.openOne:tr.openMany.replace("{n}",active.length)}</b><small>{tr.track}</small></div><GuestIcon name="chevron-right" size={18}/></button>:null}</div>:null}
   {view==="stay"?<div className={s.page}><section className={s.card}><h2>{tr.account}</h2><div className={s.facts}><span><small>{tr.booking}</small><b>{stay.number||"—"}</b></span><span><small>{tr.room}</small><b>{stay.room?.name||"—"}</b></span><span><small>{tr.checkout}</small><b>{guide.checkout_time||"—"}</b></span></div>{account?<div className={s.money}><span><small>{tr.total}</small><b>{fmtMoney(account.total,account.currency,lang)}</b></span><span><small>{tr.paid}</small><b>{fmtMoney(account.paid,account.currency,lang)}</b></span><span><small>{tr.balance}</small><b>{fmtMoney(account.balance,account.currency,lang)}</b></span></div>:null}</section>{feedbackCfg.enabled!==false&&feedbackCfg.during_stay!==false?<section className={s.card}><h2>{tr.feedback}</h2><p>{tr.feedbackSub}</p><div className={s.rating}>{[1,2,3,4,5].map(n=><button type="button" key={n} className={rating===n?s.ratingOn:""} onClick={()=>setRating(n)}><b>{n}</b><small>{tr[`rating${n}`]}</small></button>)}</div>{rating?<><textarea value={feedbackText} onChange={e=>setFeedbackText(e.target.value)} placeholder="Opcional"/><button className={s.primary} onClick={submitFeedback} disabled={sending}>{tr.sendFeedback}</button></>:null}{feedbackNotice?<div className={s.success}>{feedbackNotice}</div>:null}</section>:null}</div>:null}
   {view==="services"?<div className={s.page}><div className={s.serviceList}>{ACTIONS.filter(a=>enabled[a.kind]!==false).map(a=><button type="button" key={a.kind} onClick={()=>{if(a.kind==="late_checkout"&&stay.late_checkout_confirmed)return;setSelected(a);setDetail("");setNotice("")}}><i><GuestIcon name={a.icon} size={22}/></i><div><b>{a.kind==="late_checkout"&&stay.late_checkout_confirmed?tr.lateApproved:labels[a.kind][0]}</b><small>{labels[a.kind][1]}</small></div><GuestIcon name="chevron-right" size={18}/></button>)}{roomCfg.enabled?<button type="button" onClick={()=>setRoomOpen(true)}><i><GuestIcon name="restaurant" size={22}/></i><div><b>{tr.roomService}</b><small>{tr.roomServiceSub}</small></div><GuestIcon name="chevron-right" size={18}/></button>:null}</div></div>:null}
   {view==="hotel"?<div className={s.page}><section className={s.card}><h2>{tr.wifi}</h2><div className={s.wifi}><GuestIcon name="wifi" size={24}/><span><small>{tr.network}</small><b>{guide.wifi_name||tr.notConfigured}</b></span><button type="button" onClick={copyWifi} disabled={!guide.wifi_password}>{copied?tr.copied:tr.copy}</button></div>{guide.wifi_password?<div className={s.password}><small>{tr.password}</small><b>{guide.wifi_password}</b></div>:null}</section><section className={s.card}><h2>{tr.guide}</h2>{Array.isArray(guide.sections)&&guide.sections.length?<div className={s.guide}>{guide.sections.map((x,i)=><article key={i}><i><GuestIcon name={x.icon||"info"} size={20}/></i><div><b>{localized(x,lang,"title")}</b><p>{localized(x,lang,"description")}</p></div></article>)}</div>:<p>{tr.guideEmpty}</p>}</section></div>:null}
   {view==="explore"?<div className={s.page}><section className={s.card}><h2>{tr.nearby}</h2>{Array.isArray(guide.nearby_places)&&guide.nearby_places.length?<div className={s.places}>{guide.nearby_places.map((x,i)=><a href={x.url||"#"} target="_blank" rel="noreferrer" key={i} onClick={()=>track("nearby_open",{index:i})}><i><GuestIcon name={x.icon||"pin"} size={20}/></i><span><b>{localized(x,lang,"title")||x.title}</b><small>{localized(x,lang,"description")||x.description}</small></span><GuestIcon name="external" size={16}/></a>)}</div>:<p>{tr.nearbyEmpty}</p>}</section></div>:null}
   {view==="help"?<div className={s.page}>{aiCfg.enabled!==false?<section className={`${s.card} ${s.oliviaCard}`}><span className={s.oliviaMark}><GuestIcon name="sparkles" size={23}/></span><div><h2>{tr.olivia}</h2><p>{tr.oliviaSub}</p></div><button className={s.primary} type="button" onClick={()=>{setAiOpen(true);track("assistant_open")}}>{tr.askOlivia}</button></section>:null}<section className={s.card}><h2>{tr.reception}</h2><p>{tr.receptionSub}</p><div className={s.helpActions}><button className={s.primary} type="button" onClick={onOpenChat}>{tr.message}</button>{guide.contact_whatsapp?<a href={`https://wa.me/${String(guide.contact_whatsapp).replace(/\D/g,"")}`} target="_blank" rel="noreferrer">{tr.whatsapp}</a>:null}</div></section></div>:null}
  </div>
  <nav className={s.dock}>{nav.map(n=><button type="button" key={n.v} className={view===n.v?s.navOn:""} onClick={()=>n.v==="help"?go("help"):go(n.v)}><GuestIcon name={n.i} size={19}/><span>{n.t}</span>{n.v==="help"&&activityCount>0?<em>{activityCount}</em>:null}</button>)}</nav>
 </div>
 {selected?<div className={s.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget&&!sending)setSelected(null)}}><form className={s.sheet} onSubmit={submitAction}><button type="button" className={s.close} onClick={()=>setSelected(null)}>×</button><i><GuestIcon name={selected.icon} size={25}/></i><h2>{labels[selected.kind][0]}</h2><p>{selected.kind==="maintenance"?"Contanos brevemente qué está fallando.":selected.kind==="late_checkout"?"Decinos hasta qué hora te gustaría quedarte. Recepción revisará disponibilidad y cargos.":"Podés agregar un detalle si querés."}</p><textarea value={detail} onChange={e=>setDetail(e.target.value)} placeholder={selected.kind==="maintenance"?"Ej: el aire prende pero no enfría":"Detalle opcional"}/>{notice?<div className={s.success}>{notice}</div>:null}<button className={s.primary} disabled={sending}>{sending?"…":labels[selected.kind][0]}</button></form></div>:null}
 {roomOpen?<div className={s.backdrop}><section className={s.sheet}><button type="button" className={s.close} onClick={()=>setRoomOpen(false)}>×</button><i><GuestIcon name="restaurant" size={25}/></i><h2>{tr.roomService}</h2>{catalog.length?<><div className={s.catalog}>{catalog.map((x,i)=>{const key=String(x.id||i),qty=Number(cart[key]||0);return <article key={key}><div><b>{x.name||x.title}</b><small>{x.description||""}</small><strong>{fmtMoney(x.price,account?.currency||"ARS",lang)}</strong></div><span><button onClick={()=>setCart(c=>({...c,[key]:Math.max(0,qty-1)}))}>−</button><b>{qty}</b><button onClick={()=>setCart(c=>({...c,[key]:qty+1}))}>+</button></span></article>})}</div><div className={s.totalRow}><span>{tr.subtotal}<b>{fmtMoney(subtotal,account?.currency||"ARS",lang)}</b></span>{fee>0?<span>{tr.serviceFee}<b>{fmtMoney(fee,account?.currency||"ARS",lang)}</b></span>:null}</div><button className={s.primary} type="button" disabled={!cartRows.length||sending} onClick={submitRoom}>{tr.sendOrder}</button></>:<p>{tr.roomServiceSoon}</p>}</section></div>:null}
 {aiOpen?<div className={s.backdrop}><section className={`${s.sheet} ${s.aiSheet}`}><button type="button" className={s.close} onClick={()=>setAiOpen(false)}>×</button><div className={s.aiHead}><span><GuestIcon name="sparkles" size={24}/></span><div><h2>OlivIA</h2><small>{hotel.name}</small></div></div><div className={s.aiMessages}>{aiHistory.length?aiHistory.map((m,i)=><article key={i} data-role={m.role}>{m.text}</article>):<p>{tr.oliviaSub}</p>}{aiBusy?<article data-role="assistant">{tr.thinking}</article>:null}</div>{aiAction?<div className={s.aiProposal}><small>{tr.actionConfirm}</small><b>{labels[aiAction.kind]?.[0]||aiAction.kind}</b><span>{aiAction.detail}</span><div><button type="button" onClick={()=>setAiAction(null)}>{tr.cancel}</button><button type="button" onClick={confirmAi}>{tr.confirmSend}</button></div></div>:null}<form className={s.aiForm} onSubmit={askAi}><input value={aiText} onChange={e=>setAiText(e.target.value)} placeholder={tr.typeMessage}/><button disabled={!aiText.trim()||aiBusy}>↑</button></form></section></div>:null}
 </main>
}
