"use client"

import{useEffect,useMemo,useRef,useState}from"react"
import{useParams}from"next/navigation"
import{supabase}from"../../../lib/supabase"
import GuestPortalApp from"./GuestPortalApp"
import GuestIcon from"./GuestIcon"
import s from"./guestRuntime.module.css"

const statusLabel={open:"Recibido",in_progress:"En proceso",resolved:"Resuelto",cancelled:"Cancelado"}
const kindLabel={towels:"Toallas",pillows:"Almohadas",cleaning:"Limpieza",maintenance:"Mantenimiento",late_checkout:"Late check-out",other:"Solicitud"}
const requestKey=item=>`${item?.status||""}:${item?.decision||""}:${item?.updated_at||""}:${item?.requested_time||""}`
function noticeText(request){if(request?.kind==="late_checkout"&&request?.decision==="approved")return`Late check-out aprobado${request.requested_time?` hasta las ${request.requested_time}`:""}.`;if(request?.kind==="late_checkout"&&request?.decision==="rejected")return"Recepción revisó tu late check-out y no pudo aprobarlo.";return`${kindLabel[request?.kind]||request?.title||"Tu pedido"}: ${statusLabel[request?.status]||request?.status||"actualizado"}.`}

export default function GuestPortalRuntime(){
 const params=useParams(),token=String(params?.token||""),demo=token==="demo"
 const[snapshot,setSnapshot]=useState(null),[error,setError]=useState(""),[chatOpen,setChatOpen]=useState(false),[chatText,setChatText]=useState(""),[sending,setSending]=useState(false),[chatNotice,setChatNotice]=useState(""),[activityNotice,setActivityNotice]=useState(""),[notifyPrompt,setNotifyPrompt]=useState(false),[notifyState,setNotifyState]=useState("default"),[activityOpen,setActivityOpen]=useState(false)
 const knownRequests=useRef(new Map()),knownMessages=useRef(new Set()),initialized=useRef(false),messagesEnd=useRef(null)
 async function deviceNotification(title,body){if(typeof window==="undefined"||!("Notification"in window)||Notification.permission!=="granted")return;try{if("serviceWorker"in navigator){const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,icon:"/favicon.ico",tag:"hl-guest-stay",renotify:true,data:{url:window.location.href}});return}new Notification(title,{body})}catch{}}
 function pulse(){try{navigator.vibrate?.(60)}catch{}}
 async function refresh({initial=false}={}){if(!token)return;if(demo){setError("demo_unavailable");return}const{data,error:rpcError}=await supabase.rpc("hl_guest_stay_portal_snapshot",{p_token:token});if(rpcError||!data?.ok){setError(data?.error||rpcError?.message||"load_error");setSnapshot(null);return}setError("");const nextRequests=new Map((data.requests||[]).map(item=>[item.id,requestKey(item)])),nextMessages=new Set((data.messages||[]).map(item=>item.id));if(initial||!initialized.current){knownRequests.current=nextRequests;knownMessages.current=nextMessages;initialized.current=true;setSnapshot(data);return}const changed=(data.requests||[]).find(item=>knownRequests.current.get(item.id)!==requestKey(item)),freshOutbound=(data.messages||[]).filter(item=>!knownMessages.current.has(item.id)&&item.direction==="outbound");knownRequests.current=nextRequests;knownMessages.current=nextMessages;setSnapshot(data);if(changed){const text=noticeText(changed);setActivityNotice(text);setTimeout(()=>setActivityNotice(""),4200);pulse();if(document.hidden)deviceNotification(data?.hotel?.name||"Tu hotel",text)}if(freshOutbound.length){const text=freshOutbound.at(-1)?.text||"Recepción respondió tu mensaje.";setActivityNotice(`Recepción: ${text}`);setTimeout(()=>setActivityNotice(""),4200);pulse();if(document.hidden)deviceNotification(data?.hotel?.name||"Recepción",text)}}
 useEffect(()=>{refresh({initial:true});const timer=setInterval(()=>refresh(),5000),focus=()=>refresh(),visibility=()=>{if(!document.hidden)refresh()};window.addEventListener("focus",focus);document.addEventListener("visibilitychange",visibility);return()=>{clearInterval(timer);window.removeEventListener("focus",focus);document.removeEventListener("visibilitychange",visibility)}},[token])
 useEffect(()=>{if(typeof window==="undefined")return;if("serviceWorker"in navigator)navigator.serviceWorker.register("/guest-portal-sw.js").catch(()=>{});if("Notification"in window)setNotifyState(Notification.permission);const key=`hl:guest-notify-prompt:${window.location.pathname}`,dismissed=localStorage.getItem(key)==="dismissed";if(!dismissed&&("Notification"in window)&&Notification.permission==="default")setTimeout(()=>setNotifyPrompt(true),1300)},[])
 useEffect(()=>{if(chatOpen)setTimeout(()=>messagesEnd.current?.scrollIntoView({behavior:"smooth",block:"end"}),80)},[chatOpen,snapshot?.messages?.length])
 async function enableNotifications(){if(!("Notification"in window)){setNotifyPrompt(false);return}try{const value=await Notification.requestPermission();setNotifyState(value);setNotifyPrompt(false);localStorage.setItem(`hl:guest-notify-prompt:${window.location.pathname}`,"dismissed");if(value==="granted"){supabase.rpc("hl_guest_stay_portal_track",{p_token:token,p_event:"notifications_enabled",p_meta:{}}).catch(()=>{});deviceNotification(snapshot?.hotel?.name||"Portal del huésped","Listo. Te avisaremos cuando haya novedades.")}}catch{setNotifyPrompt(false)}}
 function dismissNotifications(){setNotifyPrompt(false);try{localStorage.setItem(`hl:guest-notify-prompt:${window.location.pathname}`,"dismissed")}catch{}}
 async function sendMessage(e){e.preventDefault();const text=chatText.trim();if(!text||sending)return;setSending(true);setChatNotice("");const{data,error}=await supabase.rpc("hl_guest_stay_portal_message",{p_token:token,p_text:text});if(error||!data?.ok)setChatNotice("No pudimos enviar el mensaje. Probá nuevamente.");else{setChatText("");setChatNotice("Mensaje enviado.");await refresh()}setSending(false)}
 const active=useMemo(()=>((snapshot?.requests||[]).filter(item=>!["resolved","cancelled"].includes(item.status))).slice(0,6),[snapshot]),messages=snapshot?.messages||[],recentReception=useMemo(()=>messages.filter(item=>item.direction==="outbound").slice(-3).reverse(),[messages]),activityCount=active.length+recentReception.length
 if(error){const waiting=error==="not_checked_in",ended=error==="access_expired";return <main className={s.accessShell}><section className={s.accessCard}><span><GuestIcon name={waiting?"key":ended?"lock":"help"} size={28}/></span><h1>{waiting?"Tu portal todavía no está habilitado":ended?"Esta estadía ya finalizó":"Portal no disponible"}</h1><p>{waiting?"El acceso se activa automáticamente cuando Recepción realiza tu check-in.":ended?"Por seguridad, este enlace dejó de funcionar al realizar el check-out, cancelar la reserva o marcarla como no-show.":"Pedí un nuevo acceso en Recepción si seguís alojado."}</p></section></main>}
 if(!snapshot)return <main className={s.accessShell}><div className={s.loading}>Preparando tu estadía…</div></main>
 return <>
  <GuestPortalApp token={token} snapshot={snapshot} onRefresh={refresh} onOpenChat={()=>{setChatOpen(true);setChatNotice("")}} onOpenActivity={()=>setActivityOpen(true)} activityCount={activityCount}/>
  {activityNotice?<div className={s.toast}><GuestIcon name="bell" size={17}/><span>{activityNotice}</span></div>:null}
  {activityCount>0?<button className={s.activityFab} type="button" onClick={()=>setActivityOpen(true)} aria-label="Actividad"><GuestIcon name="bell" size={20}/><span>{activityCount}</span></button>:null}
  <button className={s.chatFab} type="button" onClick={()=>{setChatOpen(true);setChatNotice("")}} aria-label="Recepción"><GuestIcon name="message" size={21}/></button>
  {notifyPrompt?<div className={s.notifyPrompt}><span><GuestIcon name="bell" size={19}/></span><div><b>Activá los avisos</b><small>Te avisamos cuando Recepción o el equipo actualicen algo.</small></div><button type="button" onClick={enableNotifications}>Activar</button><button type="button" onClick={dismissNotifications}>×</button></div>:null}
  {activityOpen?<div className={s.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget)setActivityOpen(false)}}><section className={s.activitySheet}><header><div><span><GuestIcon name="bell" size={20}/></span><div><b>Actividad</b><small>Novedades de tu estadía</small></div></div><button onClick={()=>setActivityOpen(false)}>×</button></header><div className={s.activityList}>{active.map(item=><article key={item.id}><span data-status={item.status}/><div><b>{kindLabel[item.kind]||item.title}</b><small>{statusLabel[item.status]||item.status}{item.requested_time?` · ${item.requested_time}`:""}</small></div></article>)}{recentReception.map(m=><button key={m.id} type="button" onClick={()=>{setActivityOpen(false);setChatOpen(true)}}><GuestIcon name="message" size={17}/><div><b>Recepción</b><small>{m.text}</small></div></button>)}{!active.length&&!recentReception.length?<p>No hay novedades pendientes.</p>:null}</div></section></div>:null}
  {chatOpen?<div className={s.backdrop}><section className={s.chatSheet}><header><div><button className={s.back} onClick={()=>setChatOpen(false)}>‹</button><span><GuestIcon name="message" size={21}/></span><div><b>Recepción</b><small>Tu conversación con el hotel</small></div></div><button className={s.desktopClose} onClick={()=>setChatOpen(false)}>×</button></header><div className={s.chatMessages}>{messages.length?messages.map(m=><article key={m.id} data-direction={m.direction}><div>{m.text}</div><small>{m.direction==="outbound"?"Recepción":"Vos"}</small></article>):<p>Escribinos lo que necesites. Tu reserva y habitación ya están vinculadas.</p>}<div ref={messagesEnd}/></div><form onSubmit={sendMessage}><textarea rows={1} value={chatText} onChange={e=>setChatText(e.target.value)} placeholder="Escribí un mensaje…"/><button disabled={sending||!chatText.trim()}>{sending?"…":"Enviar"}</button></form>{chatNotice?<div className={s.chatNotice}>{chatNotice}</div>:null}</section></div>:null}
  {notifyState==="denied"?<div className={s.permissionHint}>Las notificaciones están bloqueadas. Podés habilitarlas desde los permisos del sitio.</div>:null}
 </>
}
