"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import OliviaAssistant from"../../components/OliviaAssistant"
import PmsIcon from"../../components/shell/PmsIcons"
import useDashboardData from"./useDashboardData"
import DashboardBlockContent,{DASHBOARD_METRIC_IDS,DASHBOARD_METRIC_LABELS}from"./DashboardBlockContent"
import{actualVip,normalizeOrder}from"./DashboardViewParts"
import s from"./dashboard.module.css"
import u from"./dashboardUnified.module.css"
import e from"./dashboardEditor.module.css"

const shortcuts=[{id:"planning",label:"Planning",icon:"calendar"},{id:"quotes",label:"Presupuestar",icon:"quote"},{id:"messages",label:"Mensajes",icon:"message"},{id:"finance",label:"Finanzas",icon:"cash"},{id:"rates",label:"Tarifas y disponibilidad",icon:"rates"}]
const AVAILABLE_BLOCKS=["metrics","insights","commercial","frontdesk","shortcuts"]
const DEFAULT_BLOCKS=[...AVAILABLE_BLOCKS]
const DEFAULT_HIDDEN_BLOCKS=["shortcuts"]
const BLOCK_LABELS={metrics:["Indicadores","Ocupación, llegadas, salidas, huéspedes, habitaciones y cobros"],insights:["Centro operativo","Ocupación comparada, próximas llegadas y prioridades"],commercial:["Rendimiento comercial","Ritmo de reservas y canales de venta"],frontdesk:["Movimiento del hotel","Llegadas, huéspedes en casa y salidas"],shortcuts:["Accesos rápidos","Atajos frecuentes del PMS"]}

export default function DashboardWorkspace({propertyId,property,onNavigate,allowedViews=[]}){
  const data=useDashboardData(propertyId),m=data.metrics
  const[opsDay,setOpsDay]=useState(0),[opsQuery,setOpsQuery]=useState("")
  const[widgetOrder,setWidgetOrder]=useState(DASHBOARD_METRIC_IDS),[hiddenWidgets,setHiddenWidgets]=useState([]),[blockOrder,setBlockOrder]=useState(DEFAULT_BLOCKS),[hiddenBlocks,setHiddenBlocks]=useState(DEFAULT_HIDDEN_BLOCKS)
  const[dragging,setDragging]=useState(""),[draggingBlock,setDraggingBlock]=useState(""),[oliviaHidden,setOliviaHidden]=useState(false),[welcomeVisible,setWelcomeVisible]=useState(true),[editing,setEditing]=useState(()=>typeof window!=="undefined"&&new URL(window.location.href).searchParams.get("dashboard_edit")==="1")
  const[layoutLoaded,setLayoutLoaded]=useState(false),[layoutSaving,setLayoutSaving]=useState(false),[layoutNotice,setLayoutNotice]=useState(""),[layoutError,setLayoutError]=useState("")
  const allowed=useMemo(()=>new Set(allowedViews),[allowedViews]),can=id=>allowed.size===0||allowed.has(id),canEditDashboard=["owner","manager"].includes(String(property?.role||"").toLowerCase())

  useEffect(()=>{const timer=window.setTimeout(()=>setWelcomeVisible(false),4200);return()=>window.clearTimeout(timer)},[])
  useEffect(()=>{let alive=true;if(!propertyId)return;(async()=>{try{const{data:row,error}=await supabase.from("property_settings").select("settings").eq("property_id",propertyId).maybeSingle();if(error)throw error;const saved=row?.settings?.dashboard||{},fallback=(()=>{try{return JSON.parse(localStorage.getItem(`hl:dashboard-layout:${propertyId}`)||"null")}catch{return null}})(),source=saved&&Object.keys(saved).length?saved:fallback||{};if(!alive)return;setWidgetOrder(normalizeOrder(source.metric_order,DASHBOARD_METRIC_IDS));setHiddenWidgets(Array.isArray(source.metric_hidden)?source.metric_hidden.filter(id=>DASHBOARD_METRIC_IDS.includes(id)):[]);setBlockOrder(normalizeOrder(source.block_order,AVAILABLE_BLOCKS));const stored=Array.isArray(source.block_hidden)?source.block_hidden.filter(id=>AVAILABLE_BLOCKS.includes(id)):[];setHiddenBlocks(source.shortcuts_enabled===true?stored.filter(id=>id!=="shortcuts"):[...new Set([...stored,"shortcuts"])])}catch{try{const old=JSON.parse(localStorage.getItem(`hl:dashboard-widgets:${propertyId}`)||"null");if(Array.isArray(old))setWidgetOrder(normalizeOrder(old,DASHBOARD_METRIC_IDS))}catch{}setHiddenBlocks(DEFAULT_HIDDEN_BLOCKS)}finally{if(alive)setLayoutLoaded(true)}})();return()=>{alive=false}},[propertyId])
  useEffect(()=>{try{setOliviaHidden(localStorage.getItem(`hl:olivia-hidden:${propertyId}`)==="1")}catch{setOliviaHidden(false)}},[propertyId])

  const snapshotLayout=()=>({metric_order:widgetOrder,metric_hidden:hiddenWidgets,block_order:blockOrder,block_hidden:hiddenBlocks,shortcuts_enabled:!hiddenBlocks.includes("shortcuts")})
  function cacheLayout(next){try{localStorage.setItem(`hl:dashboard-layout:${propertyId}`,JSON.stringify(next));localStorage.setItem(`hl:dashboard-widgets:${propertyId}`,JSON.stringify(next.metric_order))}catch{}}
  async function persistLayout(next,message="Dashboard guardado para esta propiedad."){cacheLayout(next);if(!canEditDashboard)return;setLayoutSaving(true);setLayoutError("");setLayoutNotice("");try{const[{data:row,error:readError},{data:userRes}]=await Promise.all([supabase.from("property_settings").select("settings").eq("property_id",propertyId).maybeSingle(),supabase.auth.getUser()]);if(readError)throw readError;const settings=row?.settings||{},dashboard={...next,updated_at:new Date().toISOString(),updated_by:userRes?.user?.id||null},{error:writeError}=await supabase.from("property_settings").upsert({property_id:propertyId,settings:{...settings,dashboard},updated_at:new Date().toISOString(),updated_by:userRes?.user?.id||null},{onConflict:"property_id"});if(writeError)throw writeError;setLayoutNotice(message);window.dispatchEvent(new CustomEvent("hl:property-settings-updated",{detail:{propertyId,settings:{...settings,dashboard}}}))}catch(err){setLayoutError(err?.message||"No se pudo guardar el dashboard.")}finally{setLayoutSaving(false)}}
  function dropOn(target){if(!dragging||dragging===target)return;const next=widgetOrder.filter(id=>id!==dragging),index=next.indexOf(target);next.splice(index,0,dragging);setWidgetOrder(next);setDragging("");cacheLayout({...snapshotLayout(),metric_order:next})}
  function dropBlock(target){if(!draggingBlock||draggingBlock===target)return;const next=blockOrder.filter(id=>id!==draggingBlock),index=next.indexOf(target);next.splice(index,0,draggingBlock);setBlockOrder(next);setDraggingBlock("");cacheLayout({...snapshotLayout(),block_order:next})}
  function toggleWidget(id){setHiddenWidgets(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])}
  function toggleBlock(id){setHiddenBlocks(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])}
  function resetLayout(){setWidgetOrder(DASHBOARD_METRIC_IDS);setHiddenWidgets([]);setBlockOrder(DEFAULT_BLOCKS);setHiddenBlocks(DEFAULT_HIDDEN_BLOCKS);persistLayout({metric_order:DASHBOARD_METRIC_IDS,metric_hidden:[],block_order:DEFAULT_BLOCKS,block_hidden:DEFAULT_HIDDEN_BLOCKS,shortcuts_enabled:false},"Dashboard restablecido.")}
  function setOliviaVisibility(hidden){setOliviaHidden(hidden);try{if(hidden)localStorage.setItem(`hl:olivia-hidden:${propertyId}`,"1");else localStorage.removeItem(`hl:olivia-hidden:${propertyId}`)}catch{}}

  const quickLinks=shortcuts.filter(item=>can(item.id))
  const assistantContext=useMemo(()=>{const current=data.operationsByOffset?.[0]||{arrivals:[],inhouse:[],departures:[]},unique=new Map();[...(current.arrivals||[]),...(current.inhouse||[]),...(current.departures||[])].forEach(item=>unique.set(item.id,item));return{plataforma:"HabitaciónLlena.com · PMS hotelero",hoy:new Date().toLocaleDateString("en-CA"),alojamientos:propertyId?[{id:propertyId,nombre:property?.name||"Alojamiento actual"}]:[],metricas:{llegadasHoy:m.arrivals,salidasHoy:m.departures,huespedesAlojados:m.guestsInhouse??m.inhouse,habitacionesOcupadas:m.inhouse,ocupacion:Number(m.occupancy||0),habitacionesActivas:m.totalRooms,habitacionesSucias:m.dirty,habitacionesListas:m.ready,mantenimiento:m.maintenance,mantenimientoUrgente:m.urgent,checklistCompletado:m.checkPct,cobradoHoy:m.collected},reservas:[...unique.values()].slice(0,80).map(item=>({id:item.id,numero:item.numero_reserva||null,nombre:item.nombre_huesped||"Huésped",entrada:item.fecha_entrada,salida:item.fecha_salida,estado:item.estado,habitaciones:item.roomNames||[],canal:item.canal_reserva||"Directa",huespedes:item.cantidad_huespedes||1,saldo:Number(item.balance||0),moneda:item.moneda||"ARS",vip:actualVip(item.vipLevel)||null,alertaHabitacion:item.roomMaintenance?"mantenimiento":item.roomDirty?"sucia":null}))}},[data.operationsByOffset,m,propertyId,property?.name])

  function blockContent(id){
    if(id==="shortcuts")return quickLinks.length?<section className={s.quickSection}><header><strong>Accesos rápidos</strong><small>Atajos frecuentes del PMS</small></header><div className={s.quickGrid}>{quickLinks.map(item=><button key={item.id} className={s.quickLink} type="button" onClick={()=>onNavigate?.(item.id)}><span><PmsIcon name={item.icon} size={15}/></span>{item.label}</button>)}</div></section>:null
    return <DashboardBlockContent id={id} data={data} propertyId={propertyId} onNavigate={onNavigate} allowedViews={allowedViews} editing={editing} widgetOrder={widgetOrder} hiddenWidgets={hiddenWidgets} dragging={dragging} setDragging={setDragging} dropOn={dropOn} opsDay={opsDay} setOpsDay={setOpsDay} opsQuery={opsQuery} setOpsQuery={setOpsQuery}/>
  }

  return <section className={s.page}>
    {welcomeVisible?<div className={u.welcomeToast} role="status"><span className={u.welcomeMark}><PmsIcon name="olivia" size={25}/></span><div><b>Bienvenido. Así está tu hotel hoy.</b><span>{property?.name||"Tu alojamiento"} · datos operativos en vivo</span></div><button type="button" onClick={()=>setWelcomeVisible(false)} aria-label="Cerrar bienvenida"><PmsIcon name="close" size={13}/></button></div>:null}
    <div className={u.compactTools}>{oliviaHidden?<button type="button" onClick={()=>setOliviaVisibility(false)}>Mostrar OlivIA</button>:null}{canEditDashboard?<button type="button" className={editing?e.editActive:""} onClick={()=>setEditing(value=>!value)}><PmsIcon name="sliders" size={14}/>{editing?"Salir de edición":"Editar dashboard"}</button>:null}<button type="button" onClick={resetLayout}>Restablecer widgets</button><button type="button" data-live="true" onClick={()=>data.load(false)}>{data.loading?"Actualizando…":"Actualizar datos"}</button></div>
    {data.error?<div className={s.notice}>{data.error}</div>:null}{layoutError?<div className={e.layoutError}>{layoutError}</div>:null}{layoutNotice?<div className={e.layoutNotice}>{layoutNotice}</div>:null}
    {editing&&canEditDashboard?<section className={e.editor}><header><div><small>MODO EDICIÓN</small><h2>Armá el Dashboard de este hotel</h2><p>Mové bloques, ocultá lo que no necesitás y guardá una vista común para toda la propiedad.</p></div><div><button type="button" className={e.reset} onClick={resetLayout}>Restablecer</button><button type="button" className={e.save} disabled={layoutSaving} onClick={()=>persistLayout(snapshotLayout())}><PmsIcon name="check" size={14}/>{layoutSaving?"Guardando…":"Guardar cambios"}</button></div></header><div className={e.catalog}><div><b>Indicadores</b><span>Mostrá sólo los KPI útiles para este hotel.</span><div className={e.toggleGrid}>{DASHBOARD_METRIC_IDS.map(id=><button type="button" key={id} data-on={!hiddenWidgets.includes(id)} onClick={()=>toggleWidget(id)}><span>{DASHBOARD_METRIC_LABELS[id]}</span><i/></button>)}</div></div><div><b>Bloques</b><span>Estos módulos usan datos reales del PMS.</span><div className={e.toggleGrid}>{AVAILABLE_BLOCKS.map(id=><button type="button" key={id} data-on={!hiddenBlocks.includes(id)} onClick={()=>toggleBlock(id)}><span>{BLOCK_LABELS[id][0]}</span><i/></button>)}</div></div></div></section>:null}
    {layoutLoaded?blockOrder.filter(id=>!hiddenBlocks.includes(id)).map(id=>{const content=blockContent(id);if(!content)return null;return <div key={id} className={`${editing?e.editableBlock:""} ${draggingBlock===id?e.draggingBlock:""}`} draggable={editing} onDragStart={()=>editing&&setDraggingBlock(id)} onDragEnd={()=>setDraggingBlock("")} onDragOver={event=>editing&&event.preventDefault()} onDrop={()=>editing&&dropBlock(id)}>{editing?<div className={e.blockHandle}><PmsIcon name="grip" size={14}/><span><b>{BLOCK_LABELS[id][0]}</b><small>{BLOCK_LABELS[id][1]}</small></span><button type="button" onClick={()=>toggleBlock(id)}>Ocultar</button></div>:null}{content}</div>}):null}
    {!oliviaHidden?<OliviaAssistant propertyId={propertyId} propertyName={property?.name} context={assistantContext} onHide={()=>setOliviaVisibility(true)}/>:null}
  </section>
}
