"use client"

import{useMemo}from"react"
import PmsIcon from"../../components/shell/PmsIcons"
import DashboardOperationsPulse from"./DashboardOperationsPulse"
import{GuestRow,MetricIcon,ReservationPreview,isPendingArrival,money,uniqueOccupiedRooms}from"./DashboardViewParts"
import s from"./dashboard.module.css"
import d from"./frontDesk.module.css"
import v from"./dashboardViz.module.css"

export const DASHBOARD_METRIC_IDS=["occupancy","arrivals","departures","inhouse","ready","collected"]
export const DASHBOARD_METRIC_LABELS={occupancy:"Ocupación hoy",arrivals:"Llegadas hoy",departures:"Salidas hoy",inhouse:"Huéspedes",ready:"Habitaciones listas",collected:"Cobros del día"}

export default function DashboardBlockContent({id,data,propertyId,onNavigate,allowedViews=[],editing=false,widgetOrder=DASHBOARD_METRIC_IDS,hiddenWidgets=[],dragging="",setDragging,dropOn,opsDay=0,setOpsDay,opsQuery="",setOpsQuery}){
  const allowed=useMemo(()=>new Set(allowedViews),[allowedViews]),can=view=>allowed.size===0||allowed.has(view),m=data.metrics
  const openReservation=item=>onNavigate?.("reservations",{reservationId:item.id})
  if(id==="metrics"){
    const widgets={occupancy:{label:"Ocupación hoy",value:`${m.occupancy.toFixed(0)}%`,note:`${m.inhouse} / ${m.totalRooms} habitaciones`,view:"planning",tone:"violet",icon:"occupancy"},arrivals:{label:"Llegadas hoy",value:m.arrivals,note:"check-in programados",view:"reservations",tone:"green",icon:"arrivals"},departures:{label:"Salidas hoy",value:m.departures,note:"check-out programados",view:"reservations",tone:"rose",icon:"departures"},inhouse:{label:"Huéspedes",value:m.guestsInhouse??m.inhouse,note:`${m.inhouse} habitaciones ocupadas`,view:"guests",tone:"blue",icon:"inhouse"},ready:{label:"Habitaciones listas",value:m.ready,note:`${m.dirty} requieren limpieza`,view:"housekeeping",tone:"cyan",icon:"ready"},collected:{label:"Cobros del día",value:money(m.collected),note:"pagos confirmados hoy",view:"finance",tone:"emerald",icon:"collected"}}
    const visible=widgetOrder.filter(key=>widgets[key]&&can(widgets[key].view)&&!hiddenWidgets.includes(key))
    return <div className={s.metricGrid}>{visible.map(key=>{const widget=widgets[key];return <button key={key} type="button" draggable={editing} onDragStart={()=>editing&&setDragging?.(key)} onDragEnd={()=>setDragging?.("")} onDragOver={event=>editing&&event.preventDefault()} onDrop={()=>editing&&dropOn?.(key)} data-tone={widget.tone} className={`${s.metricCard} ${dragging===key?s.dragging:""}`} onClick={()=>!editing&&onNavigate?.(widget.view)}><span className={s.metricIcon}><MetricIcon type={widget.icon}/></span><span className={s.metricBody}><small>{widget.label}</small><strong className={key==="collected"?s.moneyValue:""}>{widget.value}</strong><em>{widget.note}</em></span>{editing?<i className={s.dragHandle}><PmsIcon name="grip" size={13}/></i>:null}</button>})}</div>
  }
  if(id==="insights"){
    const occupancyBars=[-1,0,1].map(offset=>{const item=data.operationsByOffset?.[offset]||{inhouse:[]},labels={[-1]:"Ayer",[0]:"Hoy",[1]:"Mañana"},rooms=uniqueOccupiedRooms(item.inhouse);return{offset,label:labels[offset],rooms,pct:m.totalRooms?Math.min(100,Math.round(rooms/m.totalRooms*100)):0,today:offset===0}})
    const rows=(()=>{const unique=new Map();for(const offset of[0,1]){const item=data.operationsByOffset?.[offset]||{arrivals:[]};(item.arrivals||[]).filter(isPendingArrival).forEach(row=>unique.set(row.id,row))}return[...unique.values()].sort((a,b)=>`${a.fecha_entrada||""} ${a.hora_llegada_estimada||"23:59"}`.localeCompare(`${b.fecha_entrada||""} ${b.hora_llegada_estimada||"23:59"}`)).slice(0,7)})()
    return <div className={s.insightGrid}><article className={`${s.panelCard} ${s.occupancyCard}`}><header className={s.panelHeader}><div><strong>Ocupación</strong><small>Ayer, hoy y mañana · habitaciones reales</small></div><button type="button" onClick={()=>onNavigate?.("planning")}>Ver planning</button></header><div className={s.occupancyChart}><div className={s.chartScale}><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div className={s.barPlot}>{occupancyBars.map(item=><div className={s.barColumn} key={item.offset} data-today={item.today?"1":"0"}><span className={s.barValue}>{item.pct}%</span><div className={s.barTrack}><i style={{height:`${Math.max(item.pct,4)}%`}}/></div><b>{item.label}</b><small>{item.rooms} hab.</small></div>)}</div></div></article><article className={s.panelCard}><header className={s.panelHeader}><div><strong>Próximas llegadas</strong><small>Check-ins pendientes de hoy y mañana</small></div><button type="button" onClick={()=>onNavigate?.("reservations")}>Ver todas</button></header><div className={s.reservationList}>{rows.length?rows.map(item=><ReservationPreview key={item.id} item={item} onOpen={()=>openReservation(item)}/>):<div className={s.emptyPanel}>No hay check-ins pendientes para hoy ni mañana.</div>}</div></article><DashboardOperationsPulse propertyId={propertyId} data={data} onNavigate={onNavigate} allowedViews={allowedViews}/></div>
  }
  if(id==="commercial"){
    if(!can("reservations"))return null
    const insights=data.bookingInsights||{days:[],channels:[],total:0,today:0,previousSix:0},paceMax=Math.max(1,...insights.days.map(day=>Number(day.value)||0)),previousAverage=insights.previousSix?insights.previousSix/6:0
    return <section className={v.vizGrid} aria-label="Rendimiento comercial reciente"><article className={v.vizCard}><header className={v.vizHeader}><div className={v.vizTitle}><strong>Ritmo de reservas</strong><small>Nuevas reservas creadas · últimos 7 días</small></div><span className={v.vizMeta}>{insights.total} en 7 días</span></header>{insights.total?<div className={v.paceChart} role="img" aria-label={`Reservas creadas en los últimos siete días. Hoy: ${insights.today}.`}>{insights.days.map((day,index)=><div className={v.paceDay} data-today={index===insights.days.length-1?"1":"0"} key={day.key}><span className={v.paceValue}>{day.value}</span><div className={v.paceTrack}><i style={{height:`${Math.max(4,day.value/paceMax*100)}%`}}/></div><b>{day.label}</b></div>)}</div>:<div className={v.emptyViz}>Todavía no hay reservas nuevas registradas en los últimos 7 días.</div>}<div className={v.dataNote}>Hoy ingresaron {insights.today} reservas nuevas. Promedio de los 6 días anteriores: {previousAverage.toLocaleString("es-AR",{maximumFractionDigits:1})} por día.</div></article><article className={v.vizCard}><header className={v.vizHeader}><div className={v.vizTitle}><strong>Canales de venta</strong><small>Origen de las reservas nuevas · 7 días</small></div></header>{insights.channels.length?<div className={v.channelList}>{insights.channels.map(channel=><div className={v.channelRow} key={channel.label}><span className={v.channelLabel}>{channel.label}</span><span className={v.channelValue}>{channel.value} · {channel.pct}%</span><div className={v.channelTrack}><i style={{width:`${Math.max(2,channel.pct)}%`}}/></div></div>)}</div>:<div className={v.emptyViz}>Sin actividad suficiente para comparar canales.</div>}<div className={v.dataNote}>Se cuentan reservas creadas realmente en el PMS; canceladas y no-show quedan fuera.</div></article></section>
  }
  if(id==="frontdesk"){
    if(!can("reservations"))return null
    const ops=data.operationsByOffset?.[opsDay]||{arrivals:[],inhouse:[],departures:[]},term=opsQuery.trim().toLowerCase(),filterRows=rows=>term?rows.filter(item=>`${item.nombre_huesped} ${item.numero_reserva||""} ${(item.roomNames||[]).join(" ")} ${item.canal_reserva||""} ${(item.guestTags||[]).join(" ")}`.toLowerCase().includes(term)):rows,columns=[{key:"arrivals",title:"Llegadas",kind:"arrival"},{key:"inhouse",title:"En casa",kind:"inhouse"},{key:"departures",title:"Salidas",kind:"departure"}]
    return <section className={`${d.frontDesk} ${s.frontDeskWrap}`}><header className={d.frontDeskHead}><div><small>RECEPCIÓN</small><h2>Movimiento del hotel</h2><p>Entradas, huéspedes alojados y salidas con alertas operativas.</p></div><div className={d.frontDeskTools}><div className={d.dayTabs}>{[[-1,"Ayer"],[0,"Hoy"],[1,"Mañana"]].map(([value,label])=><button type="button" key={value} className={opsDay===value?d.dayActive:""} onClick={()=>setOpsDay?.(value)}>{label}</button>)}</div><label className={d.deskSearch}><PmsIcon name="search" size={14}/><input value={opsQuery} onChange={event=>setOpsQuery?.(event.target.value)} placeholder="Huésped, habitación o reserva"/></label></div></header><div className={d.frontDeskGrid}>{columns.map(column=>{const rows=filterRows(ops[column.key]||[]);return <article className={d.deskColumn} key={column.key}><header><b>{column.title}</b><span>{rows.length}</span></header><div className={d.guestList}>{rows.length?rows.map(item=><GuestRow key={`${column.key}-${item.id}`} item={item} kind={column.kind} onOpen={()=>openReservation(item)}/>):<div className={d.emptyOps}>Sin movimientos para esta vista.</div>}</div></article>})}</div></section>
  }
  return null
}
