"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../../lib/supabase"

const box={border:"1px solid #e3e0ec",borderRadius:20,background:"rgba(255,255,255,.95)",padding:20,boxShadow:"0 14px 38px rgba(43,32,80,.055)"}
const input={width:"100%",boxSizing:"border-box",border:"1px solid #d8d4e4",borderRadius:11,padding:"11px 12px",font:"inherit",fontSize:15,background:"#fff",color:"#231f2c",outline:"none"}
const button={minHeight:42,border:"1px solid #d8d4e4",borderRadius:11,background:"#fff",color:"#4c4659",padding:"0 15px",fontWeight:850,fontSize:14,cursor:"pointer",textDecoration:"none",display:"inline-flex",alignItems:"center",justifyContent:"center"}
const primary={...button,border:0,background:"#6252dc",color:"#fff"}
const LABEL={fontSize:12,fontWeight:850,color:"#504a59",display:"grid",gap:6}
const TIER=[{id:"1-10",max:10},{id:"11-25",max:25},{id:"26-50",max:50},{id:"51-100",max:100},{id:"101-200",max:200},{id:"201+",max:Infinity}]
const tierFor=count=>TIER.find(item=>count<=item.max)?.id||"201+"

export default function NewPlatformClient(){
  const[plans,setPlans]=useState([]),[modules,setModules]=useState([]),[planModules,setPlanModules]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[result,setResult]=useState(null)
  const[form,setForm]=useState({propertyName:"",city:"",ownerName:"",ownerEmail:"",planCode:"base",billingCycle:"monthly",rooms:"",priceAmount:"",priceCurrency:"ARS",trial:true,trialDays:14,customize:false,modules:[],notes:""})

  useEffect(()=>{let alive=true;(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return}const{data,error}=await supabase.rpc("hl_platform_admin_properties");if(!alive)return;if(error||data?.error){setError(error?.message||"No tenés acceso al panel interno.");setLoading(false);return}const nextPlans=data?.plans||[],nextModules=data?.modules||[],nextPlanModules=data?.plan_modules||[];setPlans(nextPlans);setModules(nextModules);setPlanModules(nextPlanModules);const first=nextPlans.find(p=>p.plan_code==="base")||nextPlans[0];if(first)setForm(current=>({...current,planCode:first.plan_code,modules:modulesForPlan(first.plan_code,nextModules,nextPlanModules)}));setLoading(false)})().catch(err=>{setError(err?.message||"No se pudo cargar el alta.");setLoading(false)});return()=>{alive=false}},[])

  function modulesForPlan(planCode,mods=modules,links=planModules){const selected=new Set(mods.filter(m=>m.base_required).map(m=>m.module_code));links.filter(item=>item.plan_code===planCode&&item.enabled!==false).forEach(item=>selected.add(item.module_code));return [...selected]}
  function patch(values){setForm(current=>({...current,...values}))}
  function changePlan(planCode){patch({planCode,modules:form.customize?form.modules:modulesForPlan(planCode)})}
  function toggleModule(code,on){const base=modules.find(item=>item.module_code===code)?.base_required;if(base)return;patch({customize:true,modules:on?[...new Set([...form.modules,code])]:form.modules.filter(item=>item!==code)})}
  const roomCount=Math.max(0,Number(form.rooms||0)),roomTier=roomCount?tierFor(roomCount):null,currentPlan=plans.find(p=>p.plan_code===form.planCode)
  const enabledLabels=useMemo(()=>modules.filter(item=>form.modules.includes(item.module_code)||item.base_required).map(item=>item.label),[modules,form.modules])

  async function submit(event){event.preventDefault();if(saving)return;setError("");setResult(null);if(!form.propertyName.trim()||!form.ownerEmail.trim()){setError("Completá el nombre del hotel y el email del propietario.");return}setSaving(true);try{const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("Tu sesión venció. Volvé a iniciar sesión.");const response=await fetch("/api/platform/onboard-client",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({propertyName:form.propertyName,city:form.city,ownerName:form.ownerName,ownerEmail:form.ownerEmail,planCode:form.planCode,billingCycle:form.billingCycle,roomLimit:roomCount||null,roomTier,priceAmount:form.priceAmount===""?null:Number(form.priceAmount),priceCurrency:form.priceCurrency,trialDays:form.trial?Number(form.trialDays||14):0,modules:form.customize?form.modules:null,notes:form.notes})});const payload=await response.json();if(!response.ok)throw new Error(payload?.error||"No se pudo crear el cliente.");setResult(payload)}catch(err){setError(err?.message||"No se pudo completar el alta.")}finally{setSaving(false)}}

  if(loading)return <main style={{minHeight:"100vh",background:"#f5f6fa",padding:28,fontFamily:"Inter,Arial,sans-serif"}}><div style={{maxWidth:1080,margin:"0 auto",...box}}>Cargando alta comercial…</div></main>
  return <main style={{minHeight:"100vh",background:"radial-gradient(circle at 16% 0,#f1edff 0,transparent 32%),#f5f6fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#211d2b"}}><div style={{maxWidth:1180,margin:"0 auto"}}>
    <header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:18,flexWrap:"wrap"}}><div><small style={{fontWeight:900,letterSpacing:1.4,color:"#6557d6",fontSize:12}}>HABITACIÓN LLENA · ALTA COMERCIAL</small><h1 style={{margin:"7px 0",fontSize:34}}>Nuevo cliente</h1><p style={{margin:0,color:"#6c6677",fontSize:15}}>Creá el alojamiento, asigná propietario y dejá plan, trial y módulos listos en un solo paso.</p></div><a href="/pms-admin" style={button}>← Volver a clientes</a></header>
    {error&&<div style={{marginTop:16,padding:14,borderRadius:12,background:"#fff0f3",color:"#b42343",fontSize:14}}>{error}</div>}
    {result?<section style={{...box,marginTop:18,borderColor:"#ccebd8",background:"#f7fff9"}}><small style={{fontWeight:900,color:"#247248"}}>ALTA COMPLETADA</small><h2 style={{margin:"7px 0",fontSize:26}}>{result.property?.name||form.propertyName}</h2><p style={{margin:"0 0 14px",color:"#5d675f",fontSize:15}}>{result.message}</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:9}}><article style={{padding:13,borderRadius:12,background:"#fff"}}><small>Propietario</small><b style={{display:"block",marginTop:4}}>{form.ownerEmail}</b></article><article style={{padding:13,borderRadius:12,background:"#fff"}}><small>Plan</small><b style={{display:"block",marginTop:4}}>{currentPlan?.label||form.planCode}</b></article><article style={{padding:13,borderRadius:12,background:"#fff"}}><small>Estado</small><b style={{display:"block",marginTop:4}}>{result.subscription?.status==="trialing"?"Prueba activa":"Activo"}</b></article></div><div style={{display:"flex",gap:9,marginTop:16,flexWrap:"wrap"}}><a href="/pms-admin" style={primary}>Ver en Clientes</a><button type="button" style={button} onClick={()=>{setResult(null);setForm({propertyName:"",city:"",ownerName:"",ownerEmail:"",planCode:plans.find(p=>p.plan_code==="base")?.plan_code||plans[0]?.plan_code||"base",billingCycle:"monthly",rooms:"",priceAmount:"",priceCurrency:"ARS",trial:true,trialDays:14,customize:false,modules:modulesForPlan(plans.find(p=>p.plan_code==="base")?.plan_code||plans[0]?.plan_code||"base"),notes:""})}}>Dar de alta otro</button></div></section>:
    <form onSubmit={submit} style={{display:"grid",gap:15,marginTop:18}}>
      <section style={box}><small style={{fontWeight:900,color:"#6557d6"}}>1 · ALOJAMIENTO</small><h2 style={{margin:"6px 0 14px",fontSize:21}}>Datos básicos</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:12}}><label style={LABEL}>Nombre del hotel<input style={input} value={form.propertyName} onChange={e=>patch({propertyName:e.target.value})} placeholder="Ej. Hostería Los Aromos" autoFocus/></label><label style={LABEL}>Ciudad<input style={input} value={form.city} onChange={e=>patch({city:e.target.value})} placeholder="Ej. Villa General Belgrano"/></label><label style={LABEL}>Habitaciones contratadas<input style={input} type="number" min="1" value={form.rooms} onChange={e=>patch({rooms:e.target.value})} placeholder="Ej. 18"/></label></div></section>
      <section style={box}><small style={{fontWeight:900,color:"#6557d6"}}>2 · PROPIETARIO</small><h2 style={{margin:"6px 0 14px",fontSize:21}}>Quién va a administrar el hotel</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:12}}><label style={LABEL}>Nombre del propietario<input style={input} value={form.ownerName} onChange={e=>patch({ownerName:e.target.value})} placeholder="Nombre y apellido"/></label><label style={LABEL}>Email<input style={input} type="email" value={form.ownerEmail} onChange={e=>patch({ownerEmail:e.target.value})} placeholder="propietario@hotel.com"/></label></div><p style={{margin:"12px 0 0",fontSize:13,color:"#716b7b"}}>Si el email todavía no existe, Habitación Llena le envía una invitación. Si ya existe, se vincula ese usuario como propietario sin duplicarlo.</p></section>
      <section style={box}><small style={{fontWeight:900,color:"#6557d6"}}>3 · PLAN Y PRUEBA</small><h2 style={{margin:"6px 0 14px",fontSize:21}}>Configuración comercial</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}><label style={LABEL}>Plan<select style={input} value={form.planCode} onChange={e=>changePlan(e.target.value)}>{plans.map(plan=><option key={plan.plan_code} value={plan.plan_code}>{plan.label}</option>)}</select></label><label style={LABEL}>Ciclo<select style={input} value={form.billingCycle} onChange={e=>patch({billingCycle:e.target.value})}><option value="monthly">Mensual</option><option value="annual">Anual</option></select></label><label style={LABEL}>Precio acordado<input style={input} type="number" min="0" value={form.priceAmount} onChange={e=>patch({priceAmount:e.target.value})} placeholder="A definir"/></label><label style={LABEL}>Moneda<select style={input} value={form.priceCurrency} onChange={e=>patch({priceCurrency:e.target.value})}><option>ARS</option><option>USD</option><option>EUR</option></select></label></div><div style={{marginTop:13,padding:13,border:"1px solid #e6e1ff",borderRadius:14,background:"#faf9ff"}}><label style={{display:"flex",alignItems:"center",gap:9,fontSize:14,fontWeight:850}}><input type="checkbox" checked={form.trial} onChange={e=>patch({trial:e.target.checked})}/>Dar acceso completo de prueba</label>{form.trial?<label style={{...LABEL,marginTop:10,maxWidth:220}}>Días de prueba<input style={input} type="number" min="1" max="90" value={form.trialDays} onChange={e=>patch({trialDays:e.target.value})}/></label>:null}<p style={{margin:"9px 0 0",fontSize:12,color:"#726d7c"}}>Durante el trial el hotel puede probar todos los módulos. Al vencer, pasa a respetar el plan y las excepciones configuradas.</p></div></section>
      <section style={box}><div style={{display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap"}}><div><small style={{fontWeight:900,color:"#6557d6"}}>4 · MÓDULOS</small><h2 style={{margin:"6px 0",fontSize:21}}>Qué incluye después del trial</h2><p style={{margin:0,color:"#716b7b",fontSize:13}}>Por defecto usa exactamente los módulos del plan. Activá personalización sólo si vendiste una combinación especial.</p></div><label style={{display:"flex",alignItems:"center",gap:8,fontSize:13,fontWeight:850}}><input type="checkbox" checked={form.customize} onChange={e=>patch({customize:e.target.checked,modules:e.target.checked?form.modules:modulesForPlan(form.planCode)})}/>Personalizar módulos</label></div><div style={{display:"flex",flexWrap:"wrap",gap:8,marginTop:14}}>{modules.map(module=>{const on=module.base_required||form.modules.includes(module.module_code);return <label key={module.module_code} style={{display:"flex",alignItems:"center",gap:7,padding:"9px 11px",borderRadius:11,border:`1px solid ${on?"#d3cbff":"#e4e1ea"}`,background:on?"#f6f3ff":"#fff",fontSize:13,fontWeight:800,opacity:!form.customize&&!module.base_required?.9:1}}><input type="checkbox" disabled={module.base_required||!form.customize} checked={on} onChange={e=>toggleModule(module.module_code,e.target.checked)}/>{module.label}{module.base_required?<small> · base</small>:null}</label>})}</div><p style={{margin:"13px 0 0",fontSize:13,color:"#696371"}}><b>Quedarían habilitados:</b> {enabledLabels.join(", ")||"PMS Core"}.</p></section>
      <section style={box}><small style={{fontWeight:900,color:"#6557d6"}}>5 · INTERNO</small><h2 style={{margin:"6px 0 12px",fontSize:21}}>Nota de la cuenta</h2><label style={LABEL}>Nota interna<textarea style={{...input,minHeight:88,resize:"vertical"}} value={form.notes} onChange={e=>patch({notes:e.target.value})} placeholder="Ej. Demo comercial, contacto, condición acordada, seguimiento…"/></label></section>
      <section style={{...box,display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",flexWrap:"wrap"}}><div><b style={{fontSize:16}}>{form.propertyName||"Nuevo hotel"}</b><small style={{display:"block",marginTop:4,color:"#716b7b",fontSize:13}}>{currentPlan?.label||"Plan"}{form.trial?` · ${form.trialDays||14} días de prueba`:" · sin prueba"}{roomCount?` · ${roomCount} habitaciones`:""}</small></div><button type="submit" disabled={saving} style={{...primary,minWidth:190,opacity:saving?.65:1}}>{saving?"Creando cliente…":"Crear cliente"}</button></section>
    </form>}
  </div></main>
}
