"use client"

import Link from"next/link"
import{useEffect,useState}from"react"
import s from"./landing-editorial.module.css"

const HOTEL="https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=1900"
const LOBBY="https://images.pexels.com/photos/5371676/pexels-photo-5371676.jpeg?auto=compress&cs=tinysrgb&w=1800"
const ROOM="https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1800&q=88"
const TEAM="https://images.pexels.com/photos/9462786/pexels-photo-9462786.jpeg?auto=compress&cs=tinysrgb&w=1800"

function Icon({name,size=18}){const p={calendar:"M7 2v3M17 2v3M3.5 9h17M5 4h14a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z",user:"M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm7 9a7 7 0 0 0-14 0",bed:"M3 19v-6h18v6M5 13V8h6a3 3 0 0 1 3 3v2M3 17h18",wallet:"M4 6h15a2 2 0 0 1 2 2v10H4a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2Zm11 5h6",spark:"m12 2 1.7 5.3L19 9l-5.3 1.7L12 16l-1.7-5.3L5 9l5.3-1.7L12 2Zm7 13 .8 2.2L22 18l-2.2.8L19 21l-.8-2.2L16 18l2.2-.8L19 15Z",chart:"M4 20V10m5 10V5m6 15v-7m5 7V8",bell:"M6 9a6 6 0 0 1 12 0c0 7 3 7 3 7H3s3 0 3-7Zm4 11h4",cloud:"M7 18h10a4 4 0 0 0 .6-8A6 6 0 0 0 6.1 8.2 5 5 0 0 0 7 18Z",lock:"M6 10h12v10H6V10Zm3 0V7a3 3 0 0 1 6 0v3",bolt:"m13 2-8 12h6l-1 8 9-13h-6V2Z",arrow:"M5 12h14m-5-5 5 5-5 5",check:"m5 12 4 4L19 6",menu:"M4 7h16M4 12h16M4 17h16"}[name]||"M5 12h14";return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={p}/></svg>}

const workspaces={
 planning:{label:"Planning",eyebrow:"Recepción",title:"El hotel se entiende de un vistazo.",copy:"Reservas, bloqueos, disponibilidad y movimientos viven en la misma línea de tiempo. Menos ventanas. Menos dudas.",icon:"calendar"},
 arrivals:{label:"Llegadas",eyebrow:"Turno",title:"Cada llegada con contexto, no con memoria.",copy:"Saldo, canal, preferencias y estado de habitación aparecen antes de que recepción tenga que buscarlos.",icon:"bell"},
 guests:{label:"Huéspedes",eyebrow:"CRM",title:"La próxima estadía empieza donde terminó la anterior.",copy:"Historial, recurrencia, consentimiento y preferencias útiles reunidos en una ficha 360°.",icon:"user"},
 housekeeping:{label:"Housekeeping",eyebrow:"Operación",title:"Pisos ve prioridades. No ruido.",copy:"Salidas, stayovers, inspecciones y próximas llegadas ordenadas por lo que realmente cambia el día.",icon:"bed"},
 revenue:{label:"Inteligencia",eyebrow:"Dirección",title:"Datos que terminan en una decisión.",copy:"Ocupación, ritmo de reservas, ADR, RevPAR y señales operativas sin convertir el PMS en una planilla gigante.",icon:"chart"}
}

function Brand(){return <span className={s.brand}><span className={s.brandMark}>HL</span><span><b>Habitación Llena</b><small>HOTEL OPERATING SYSTEM</small></span></span>}

function MiniPlanning(){const stays=[["Micaela R.",0,3,"green"],["Booking · 204",2,3,"blue"],["Grupo Durazno",1,5,"amber"],["Olivia M.",4,2,"green"]];return <div className={s.miniPlanning}><div className={s.miniDays}>{["L 14","M 15","X 16","J 17","V 18","S 19","D 20"].map(d=><span key={d}>{d}</span>)}</div>{[101,102,201,203].map((room,row)=><div className={s.miniRow} key={room}><b>{room}</b><i/><i/><i/><i/><i/><i/><i/>{stays[row]&&<em className={s[stays[row][3]]} style={{left:`calc(60px + ${stays[row][1]} * (100% - 60px)/7)`,width:`calc(${stays[row][2]} * (100% - 60px)/7 - 8px)`}}>{stays[row][0]}</em>}</div>)}</div>}

function OperatingWindow(){return <div className={s.osWindow}>
  <div className={s.windowTop}><div className={s.traffic}><i/><i/><i/></div><div className={s.windowTitle}>Hostería Durazno <span>· Hoy</span></div><div className={s.live}><i/>EN VIVO</div></div>
  <div className={s.windowBody}><aside className={s.osDock}><span className={s.dockLogo}>HL</span>{["calendar","user","bed","wallet","chart"].map((x,i)=><button className={i===0?s.dockActive:""} key={x} aria-label={x}><Icon name={x} size={16}/></button>)}</aside><div className={s.osMain}><div className={s.osHeader}><div><small>BUENAS TARDES</small><h3>Todo bajo control.</h3></div><button><Icon name="spark" size={15}/> Preguntar a OlivIA</button></div><div className={s.metricGrid}><article><small>Ocupación</small><b>78%</b><span>+6% vs. semana pasada</span></article><article><small>Llegadas</small><b>12</b><span>3 antes de las 15:00</span></article><article><small>Salidas</small><b>9</b><span>7 habitaciones en limpieza</span></article></div><MiniPlanning/></div></div>
</div>}

function FloatingSignals(){return <><div className={`${s.floatCard} ${s.floatArrival}`}><span className={s.signalIcon}><Icon name="bell"/></span><div><small>LLEGADA EN 42 MIN</small><b>Lucía Ferrer · 204</b><span>Hab. lista · saldo OK</span></div><i>→</i></div><div className={`${s.floatCard} ${s.floatAi}`}><span className={s.signalIcon}><Icon name="spark"/></span><div><small>OLIVIA</small><b>Hay 3 llegadas OTA recurrentes hoy.</b><span>Ver huéspedes</span></div></div><div className={s.offlinePill}><Icon name="cloud" size={15}/><span>App instalada · continuidad offline segura</span></div></>}

function WorkspaceVisual({active}){if(active==="planning")return <MiniPlanning/>;if(active==="arrivals")return <div className={s.arrivalVisual}>{[["13:20","Lucía Ferrer","204","Directa","Lista"],["14:10","Mateo Ruiz","301","Booking","Limpieza"],["15:00","Ana Lima","102","WhatsApp","Lista"],["16:40","Nicolás Paz","201","Airbnb","Pendiente"]].map((r,i)=><div key={r[1]} className={i===1?s.rowHot:""}><time>{r[0]}</time><span><b>{r[1]}</b><small>{r[2]} · {r[3]}</small></span><em>{r[4]}</em><i>→</i></div>)}</div>;if(active==="guests")return <div className={s.guestVisual}><header><span>MR</span><div><small>HUÉSPED FRECUENTE</small><h3>Martina Rossi</h3><p>5 estadías · última visita hace 43 días</p></div><b>VIP</b></header><div className={s.guestStats}><span><small>Valor histórico</small><b>ARS 842.000</b></span><span><small>Próxima estadía</small><b>18 → 21 Sep</b></span><span><small>Preferencia</small><b>Piso alto</b></span></div><div className={s.guestNote}><Icon name="spark"/><span><b>Sugerencia</b><small>Ofrecer late check-out según disponibilidad.</small></span></div></div>;if(active==="housekeeping")return <div className={s.hkVisual}>{[["204","Prioridad alta","Entrada 13:20","danger"],["301","En limpieza","Entrada 14:10","progress"],["406","Lista","Sin próxima llegada","ready"],["108","Inspección","Stayover","neutral"]].map(x=><div key={x[0]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span><em className={s[x[3]]}/><i>→</i></div>)}</div>;return <div className={s.revenueVisual}><div className={s.revTop}><span><small>OCUPACIÓN 14 DÍAS</small><b>81%</b></span><span><small>ADR</small><b>$94.200</b></span><span><small>REVPAR</small><b>$76.302</b></span></div><svg viewBox="0 0 700 230" preserveAspectRatio="none"><defs><linearGradient id="revfill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#5e7df8" stopOpacity=".28"/><stop offset="1" stopColor="#5e7df8" stopOpacity="0"/></linearGradient></defs><path d="M0 190 C70 170 96 105 170 126 S270 182 330 118 S430 42 500 86 S610 146 700 64 L700 230 L0 230Z" fill="url(#revfill)"/><path d="M0 190 C70 170 96 105 170 126 S270 182 330 118 S430 42 500 86 S610 146 700 64" fill="none" stroke="#6d86ff" strokeWidth="4"/></svg><div className={s.revSignal}><Icon name="spark"/><span><b>Fin de semana acelerando</b><small>+18% de pickup en las últimas 48 h</small></span></div></div>}

const capabilities=[
 ["calendar","Planning vivo","Mover, extender, bloquear y entender disponibilidad sin salir del calendario."],
 ["bolt","Channel Manager","Channex conectado para reducir carga manual entre PMS y OTAs."],
 ["wallet","Pagos y caja","Folios, pagos divididos, saldos y caja diaria dentro de la misma operación."],
 ["user","CRM hotelero","Perfiles 360°, recurrencia, preferencias, consentimiento y segmentos útiles."],
 ["lock","ARCA guiado","Configuración fiscal por propiedad con CSR, certificado y prueba de conexión."],
 ["cloud","Instalable + offline","PWA para desktop y móvil con continuidad segura de consulta ante cortes."]
]

export default function LandingEditorial(){
 const[active,setActive]=useState("planning"),[menu,setMenu]=useState(false)
 useEffect(()=>{const items=[...document.querySelectorAll("[data-reveal]")],io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add(s.visible)}),{threshold:.13});items.forEach(n=>io.observe(n));return()=>io.disconnect()},[])
 useEffect(()=>{if(typeof window==="undefined"||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const keys=Object.keys(workspaces),id=setInterval(()=>setActive(a=>keys[(keys.indexOf(a)+1)%keys.length]),6500);return()=>clearInterval(id)},[])
 return <main className={s.page}>
  <div className={s.ambient}/>
  <nav className={s.nav}><Link href="/" aria-label="Habitación Llena"><Brand/></Link><div className={`${s.navLinks} ${menu?s.open:""}`}><a href="#producto">Producto</a><a href="#automatizacion">Automatización</a><a href="#integraciones">Integraciones</a><a href="#migracion">Migración</a></div><div className={s.navActions}><Link href="/login" className={s.login}>Entrar</Link><Link href="/registro" className={s.primary}>Ver demo <Icon name="arrow" size={15}/></Link><button className={s.menuBtn} onClick={()=>setMenu(v=>!v)} aria-label="Abrir menú"><Icon name="menu"/></button></div></nav>

  <section className={s.hero}><div className={s.heroCopy} data-reveal><div className={s.kicker}><i/>PMS + AUTOMATIZACIÓN HOTELERA</div><h1>Tu hotel entero.<br/><em>En una sola vista.</em></h1><p>Habitación Llena une recepción, Planning, huéspedes, housekeeping, pagos, revenue y canales en un sistema que se siente como una app moderna, no como una planilla.</p><div className={s.heroActions}><Link href="/registro" className={s.heroPrimary}>Quiero verlo en mi hotel <Icon name="arrow"/></Link><a href="#producto" className={s.heroSecondary}><span>Explorar producto</span><i><Icon name="arrow" size={16}/></i></a></div><div className={s.trustRow}><span><Icon name="check" size={14}/> Hecho en Argentina</span><span><Icon name="check" size={14}/> Multi-propiedad</span><span><Icon name="check" size={14}/> Desktop + móvil</span></div></div><div className={s.heroVisual} data-reveal><div className={s.hotelFrame}><img src={HOTEL} alt="Hotel contemporáneo"/></div><OperatingWindow/><FloatingSignals/></div></section>

  <section className={s.signalBar} data-reveal><div><small>UNA OPERACIÓN</small><b>Recepción</b></div><i/><div><small>UN MISMO DATO</small><b>Housekeeping</b></div><i/><div><small>SIN REINGRESAR</small><b>Administración</b></div><i/><div><small>CON CONTEXTO</small><b>Dirección</b></div></section>

  <section className={s.workspace} id="producto"><header data-reveal><div><small>UN SISTEMA, CINCO FORMAS DE MIRARLO</small><h2>No abrís módulos.<br/>Entrás a trabajar.</h2></div><p>Lo complejo queda atrás. Cada equipo ve lo que necesita y el resto aparece cuando hace falta.</p></header><div className={s.workspaceShell} data-reveal><div className={s.workspaceTabs}>{Object.entries(workspaces).map(([key,w])=><button className={active===key?s.active:""} onClick={()=>setActive(key)} key={key}><span><Icon name={w.icon}/></span><div><b>{w.label}</b><small>{w.eyebrow}</small></div><i>→</i></button>)}</div><div className={s.workspaceStage}><div className={s.workspaceCopy}><span>{workspaces[active].eyebrow}</span><h3>{workspaces[active].title}</h3><p>{workspaces[active].copy}</p></div><div className={s.visualCard}><WorkspaceVisual active={active}/></div></div></div></section>

  <section className={s.automation} id="automatizacion"><div className={s.automationPhoto}><img src={LOBBY} alt="Recepción de hotel moderna"/><div className={s.photoLabel}><span>13:18</span><b>El hotel cambia. El sistema reacciona.</b></div></div><div className={s.automationPanel} data-reveal><small>AUTOMATIZACIÓN ÚTIL</small><h2>Menos clics porque el sistema entiende el turno.</h2><p>No se trata de llenar la pantalla de IA. Se trata de mover información al lugar correcto en el momento correcto.</p><ol><li><time>10:32</time><span><b>Check-out confirmado</b><small>Habitación 204 pasa a Housekeeping.</small></span><Icon name="check"/></li><li><time>11:07</time><span><b>Nueva reserva OTA</b><small>Disponibilidad y Planning se actualizan.</small></span><Icon name="check"/></li><li><time>12:41</time><span><b>Habitación lista</b><small>Recepción ve la llegada priorizada.</small></span><Icon name="check"/></li><li><time>13:18</time><span><b>Huésped recurrente</b><small>Preferencias relevantes aparecen en contexto.</small></span><Icon name="spark"/></li></ol></div></section>

  <section className={s.aiSection}><div className={s.aiCopy} data-reveal><span className={s.aiBadge}><Icon name="spark"/> IA OPERATIVA</span><h2>OlivIA no ocupa el hotel.<br/>Te ayuda a leerlo.</h2><p>Consultá el sistema en lenguaje natural, entendé métricas y encontrá lo importante sin aprender veinte reportes.</p><ul><li><Icon name="check"/> Resume cambios del turno.</li><li><Icon name="check"/> Explica indicadores con contexto.</li><li><Icon name="check"/> Lleva al módulo correcto.</li><li><Icon name="lock"/> Acciones sensibles siguen bajo control humano.</li></ul></div><div className={s.aiDemo} data-reveal><div className={s.aiTop}><span><Icon name="spark"/> OlivIA</span><small>Asistente del hotel</small></div><div className={s.chatUser}>¿Qué tengo que mirar antes de las 15?</div><div className={s.chatAi}><span><Icon name="spark" size={16}/></span><div><p>Hay <b>3 llegadas prioritarias</b>. La 301 sigue en limpieza y tiene llegada a las 14:10. Además, quedan <b>2 saldos pendientes</b> de hoy.</p><div><button>Ver llegadas</button><button>Ver saldos</button></div></div></div><div className={s.aiPrompt}><span>Preguntale algo sobre tu hotel…</span><i><Icon name="arrow"/></i></div></div></section>

  <section className={s.capabilities} id="integraciones"><header data-reveal><small>BASE SERIA, EXPERIENCIA SIMPLE</small><h2>Todo lo que tiene que estar.<br/>Sin convertirlo en ruido.</h2></header><div className={s.capGrid}>{capabilities.map(([icon,title,copy],i)=><article data-reveal key={title} style={{transitionDelay:`${i*45}ms`}}><span><Icon name={icon}/></span><h3>{title}</h3><p>{copy}</p><i>0{i+1}</i></article>)}</div></section>

  <section className={s.humanSection}><div className={s.humanCopy} data-reveal><small>HECHO PARA PERSONAS QUE ESTÁN TRABAJANDO</small><h2>La tecnología desaparece cuando está bien diseñada.</h2><p>Botones claros, menos texto visible, ventanas contextuales y una misma lógica visual en todo el sistema.</p><div><span><b>01</b>Recepción aprende rápido.</span><span><b>02</b>Housekeeping toca menos.</span><span><b>03</b>Dirección encuentra contexto.</span></div></div><div className={s.humanImage}><img src={TEAM} alt="Equipo de housekeeping trabajando"/><span>Operación móvil y responsive</span></div></section>

  <section className={s.migration} id="migracion"><div className={s.migrationHead} data-reveal><small>MIGRAR SIN PARAR</small><h2>Tu PMS actual no se apaga hasta que el nuevo esté listo.</h2><p>Configuramos, importamos, conciliamos y entrenamos antes del cambio final.</p></div><div className={s.migrationFlow}>{[["01","Mapeo","Habitaciones, tarifas y usuarios"],["02","Importación","Reservas, huéspedes y saldos"],["03","Entrenamiento","Recepción y operación"],["04","Go-live","Cambio controlado y acompañado"]].map(([n,t,c])=><article data-reveal key={n}><b>{n}</b><span><strong>{t}</strong><small>{c}</small></span><i><Icon name="arrow"/></i></article>)}</div></section>

  <section className={s.finalCta}><div className={s.finalImage}><img src={ROOM} alt="Habitación de hotel moderna"/></div><div data-reveal><span className={s.finalMark}>HL</span><small>HABITACIÓN LLENA</small><h2>Un PMS que da ganas de abrir todos los días.</h2><p>Probalo con la operación de tu hotel. Sin presentación eterna.</p><div><Link href="/registro">Solicitar demo <Icon name="arrow"/></Link><Link href="/login">Ya soy cliente</Link></div></div></section>

  <footer className={s.footer}><Brand/><span>Argentina · 2026</span><div><Link href="/privacidad">Privacidad</Link><Link href="/terminos">Términos</Link><Link href="/seguridad">Seguridad</Link></div></footer>
 </main>
}
