"use client"

import{useEffect,useMemo,useState}from"react"
import{useParams}from"next/navigation"

const money=(value,currency="ARS")=>{try{return new Intl.NumberFormat("es-AR",{style:"currency",currency,maximumFractionDigits:0}).format(Number(value)||0)}catch{return`${currency} ${Number(value)||0}`}}
const fmt=value=>value?new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(`${value}T12:00:00`)):"—"

export default function GuestReservationPortal(){
  const params=useParams(),slug=String(params?.slug||""),token=String(params?.token||""),[data,setData]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[detail,setDetail]=useState("")
  const endpoint=useMemo(()=>`/api/public/booking/${encodeURIComponent(slug)}/manage/${encodeURIComponent(token)}`,[slug,token])
  async function load(){setLoading(true);setError("");try{const r=await fetch(endpoint,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"No se pudo abrir la reserva.");setData(j)}catch(e){setError(e.message||"No se pudo abrir la reserva.")}finally{setLoading(false)}}
  useEffect(()=>{if(slug&&token)load()},[slug,token])
  async function act(action){if(action==="cancel"&&!window.confirm("¿Querés cancelar esta reserva? Esta acción no se puede deshacer desde el portal."))return;if(action==="request_change"&&!detail.trim()){setError("Contanos qué cambio necesitás.");return}setBusy(action);setError("");setNotice("");try{const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,detail})}),j=await r.json();if(!r.ok)throw new Error(j.error||"No se pudo completar la acción.");setData(j);if(action==="request_change"){setDetail("");setNotice("Tu solicitud quedó enviada al hotel y vinculada a la reserva.")}else setNotice("La reserva quedó cancelada correctamente.")}catch(e){setError(e.message||"No se pudo completar la acción.")}finally{setBusy("")}}
  const r=data?.reservation,h=data?.hotel
  return <main style={{minHeight:"100vh",background:"#f4f6fb",padding:"28px 14px",fontFamily:"Inter,ui-sans-serif,system-ui,-apple-system,sans-serif",color:"#182033"}}><section style={{width:"min(760px,100%)",margin:"0 auto",background:"#fff",border:"1px solid #e4e8f0",borderRadius:22,boxShadow:"0 22px 70px rgba(28,45,78,.08)",overflow:"hidden"}}>
    <header style={{padding:"22px 24px",borderBottom:"1px solid #edf0f5",display:"flex",justifyContent:"space-between",gap:16,alignItems:"center"}}><div><small style={{fontSize:10,fontWeight:900,letterSpacing:".11em",color:"#6a70e8"}}>MI RESERVA</small><h1 style={{fontSize:23,margin:"4px 0 0"}}>{h?.name||"Habitación Llena"}</h1></div><a href={`/book/${slug}`} style={{fontSize:12,fontWeight:800,color:"#5960d8",textDecoration:"none"}}>Nueva búsqueda</a></header>
    {loading?<div style={{padding:34,textAlign:"center",color:"#687086"}}>Cargando reserva…</div>:error&&!data?<div style={{padding:28,color:"#b42318"}}>{error}</div>:r?<div style={{padding:24,display:"grid",gap:18}}>
      {error?<div style={{padding:"11px 13px",borderRadius:11,background:"#fff1f0",color:"#b42318",fontSize:12,fontWeight:700}}>{error}</div>:null}{notice?<div style={{padding:"11px 13px",borderRadius:11,background:"#effaf3",color:"#16713d",fontSize:12,fontWeight:700}}>{notice}</div>:null}
      <div style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",flexWrap:"wrap"}}><div><small style={{fontSize:10,color:"#7b8498",fontWeight:850}}>RESERVA</small><h2 style={{fontSize:21,margin:"4px 0"}}>{r.numero_reserva||r.id}</h2><span style={{fontSize:12,color:"#667085"}}>{r.name}</span></div><span style={{padding:"7px 10px",borderRadius:999,background:r.status==="cancelada"?"#fff1f0":"#eef8f2",color:r.status==="cancelada"?"#b42318":"#16713d",fontSize:11,fontWeight:900,textTransform:"capitalize"}}>{r.status}</span></div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10}}>{[["Entrada",fmt(r.check_in)],["Salida",fmt(r.check_out)],["Habitación",r.room_type],["Noches",r.nights],["Total",money(r.total,r.currency)],["Política",h?.cancellation_policy||"Consultar con el hotel"]].map(([label,value])=><div key={label} style={{padding:14,border:"1px solid #edf0f4",borderRadius:13,background:"#fafbfc"}}><small style={{display:"block",fontSize:10,color:"#7b8498",fontWeight:850}}>{label}</small><b style={{display:"block",marginTop:4,fontSize:13,lineHeight:1.35}}>{value}</b></div>)}</div>
      {r.status!=="cancelada"?<section style={{padding:16,border:"1px solid #e7eaf0",borderRadius:15}}><h3 style={{margin:"0 0 5px",fontSize:15}}>¿Necesitás cambiar algo?</h3><p style={{margin:"0 0 10px",fontSize:12,color:"#687086",lineHeight:1.5}}>Pedí un cambio de fechas, huéspedes u otro dato. El hotel lo recibe asociado a esta reserva.</p><textarea value={detail} onChange={e=>setDetail(e.target.value)} rows="4" maxLength="1200" placeholder="Ej.: quisiera cambiar la salida al 24 de octubre…" style={{width:"100%",boxSizing:"border-box",resize:"vertical",border:"1px solid #dfe3ea",borderRadius:11,padding:11,font:"inherit",fontSize:12}}/><div style={{display:"flex",gap:9,marginTop:10,flexWrap:"wrap"}}><button disabled={!!busy} onClick={()=>act("request_change")} style={{height:38,border:0,borderRadius:10,padding:"0 14px",background:"#5b5ceb",color:"#fff",fontWeight:850,cursor:"pointer"}}>{busy==="request_change"?"Enviando…":"Enviar solicitud"}</button>{data.can_cancel?<button disabled={!!busy} onClick={()=>act("cancel")} style={{height:38,border:"1px solid #f0c3bf",borderRadius:10,padding:"0 14px",background:"#fff",color:"#b42318",fontWeight:850,cursor:"pointer"}}>{busy==="cancel"?"Cancelando…":"Cancelar reserva"}</button>:null}</div>{!data.can_cancel?<small style={{display:"block",marginTop:9,color:"#7b8498",lineHeight:1.4}}>La cancelación automática no está habilitada para esta reserva. Podés enviar una solicitud al hotel.</small>:null}</section>:null}
      {(h?.contact_phone||h?.contact_email)?<footer style={{paddingTop:4,fontSize:12,color:"#687086"}}>Contacto del hotel: {[h.contact_phone,h.contact_email].filter(Boolean).join(" · ")}</footer>:null}
    </div>:null}
  </section></main>
}
