"use client"

import{useState}from"react"
import{supabase}from"../../../../lib/supabase"
import s from"./growth.module.css"

const money=(value,currency)=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:0}).format(Number(value)||0)
const slugify=value=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")

export default function VoucherEditor({editing,setEditing,currency,roomTypes,propertyId,saving,onSave}){
  const[step,setStep]=useState(1),[imageBusy,setImageBusy]=useState(false),f=editing.form
  const patch=values=>setEditing(current=>({...current,form:{...current.form,...values}}))
  const titles=["Información general","Descripción e imagen","Precio","Fechas de utilización","Inventario","Vigencia","Visibilidad"]
  async function upload(file){if(!file)return;setImageBusy(true);try{const ext=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg",path=`${propertyId}/vouchers/${Date.now()}-${slugify(f.name||"voucher")}.${ext}`,res=await supabase.storage.from("hotel-media").upload(path,file,{upsert:false,contentType:file.type});if(res.error)throw res.error;const pub=supabase.storage.from("hotel-media").getPublicUrl(path);patch({image_url:pub.data.publicUrl})}catch(err){window.alert(err?.message||"No se pudo subir la imagen.")}finally{setImageBusy(false)}}
  const canNext=step!==1||String(f.name||"").trim()
  return <div className={s.backdrop} onMouseDown={e=>e.target===e.currentTarget&&setEditing(null)}><div className={`${s.modal} ${s.voucherModal}`}><button className={s.close} onClick={()=>setEditing(null)}>×</button><small>VOUCHER · PASO {step} DE 7</small><h2>{f.id?"Editar voucher":"Nuevo voucher"}</h2><div className={s.voucherSteps}>{titles.map((title,index)=><button type="button" key={title} className={step===index+1?s.stepActive:step>index+1?s.stepDone:""} onClick={()=>setStep(index+1)}><span>{index+1}</span><b>{title}</b></button>)}</div>
    <div className={s.voucherBody}>
      {step===1&&<><h3>Información general</h3><p>Definí el nombre, la URL del voucher y el idioma con el que se mostrará.</p><div className={s.form}><label>Nombre<input autoFocus value={f.name||""} onChange={e=>{const name=e.target.value;patch({name,slug:f.id?f.slug:slugify(name)})}}/></label><label>URL del voucher<div className={s.slugInput}><span>/voucher/</span><input value={f.slug||""} onChange={e=>patch({slug:slugify(e.target.value)})}/></div></label><label>Idioma<select value={f.language||"es"} onChange={e=>patch({language:e.target.value})}><option value="es">Español</option><option value="en">English</option><option value="pt-BR">Português</option></select></label><label className={s.toggle}><input type="checkbox" checked={f.active!==false} onChange={e=>patch({active:e.target.checked})}/> Voucher activo</label></div></>}
      {step===2&&<><h3>Descripción e imagen</h3><p>Es lo que verá el huésped antes de elegir el voucher.</p><div className={s.form}><label className={s.wide}>Descripción<textarea rows="4" value={f.description||""} onChange={e=>patch({description:e.target.value})}/></label><label className={s.wide}>Condiciones comerciales<textarea rows="3" value={f.commercial_conditions||""} onChange={e=>patch({commercial_conditions:e.target.value})} placeholder="Ej.: sujeto a disponibilidad, no acumulable con otras promociones…"/></label><label className={s.wide}>Imagen del voucher<div className={s.imagePicker}>{f.image_url?<img src={f.image_url} alt="Vista previa"/>:<div>Sin imagen</div>}<label className={s.uploadMini}>{imageBusy?"Subiendo…":"Subir imagen"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={imageBusy} onChange={e=>{upload(e.target.files?.[0]);e.target.value=""}}/></label>{f.image_url&&<button type="button" onClick={()=>patch({image_url:""})}>Quitar</button>}</div></label></div></>}
      {step===3&&<><h3>Precio del voucher</h3><p>Podés venderlo con tarifa fija o dejarlo sin cargo.</p><div className={s.choiceGrid}><button type="button" className={f.price_mode==="fixed"?s.choiceActive:""} onClick={()=>patch({price_mode:"fixed"})}><b>Tarifa fija</b><span>El voucher tiene un precio concreto.</span></button><button type="button" className={f.price_mode==="free"?s.choiceActive:""} onClick={()=>patch({price_mode:"free",price:0,tax_percent:0})}><b>Sin cargo</b><span>No genera importe a cobrar.</span></button></div>{f.price_mode!=="free"&&<div className={s.form}><label>Precio<input type="number" min="0" value={f.price||0} onChange={e=>patch({price:e.target.value})}/></label><label>Moneda<select value={f.currency||currency} onChange={e=>patch({currency:e.target.value})}>{["ARS","USD","EUR","BRL","CLP","UYU"].map(x=><option key={x}>{x}</option>)}</select></label><label>IVA / impuesto %<input type="number" min="0" max="100" step="0.01" value={f.tax_percent||0} onChange={e=>patch({tax_percent:e.target.value})}/></label><label className={s.toggle}><input type="checkbox" checked={Boolean(f.tax_included)} onChange={e=>patch({tax_included:e.target.checked})}/> El precio ya incluye impuestos</label></div>}</>}
      {step===4&&<><h3>Fechas de utilización</h3><p>Elegí si el voucher queda abierto o si el comprador define sus fechas.</p><div className={s.choiceGrid}><button type="button" className={f.date_mode==="open"?s.choiceActive:""} onClick={()=>patch({date_mode:"open"})}><b>Fechas libres</b><span>Se utiliza más adelante dentro de su vigencia.</span></button><button type="button" className={f.date_mode==="buyer_dates"?s.choiceActive:""} onClick={()=>patch({date_mode:"buyer_dates"})}><b>El comprador elige</b><span>Se valida disponibilidad al seleccionar fechas.</span></button></div><div className={s.form}><label>Tipo de estancia<select value={f.stay_type||"overnight"} onChange={e=>patch({stay_type:e.target.value,nights:e.target.value==="same_day"?0:Math.max(1,Number(f.nights)||1)})}><option value="same_day">En el mismo día</option><option value="overnight">Una noche o más</option></select></label>{f.stay_type==="overnight"&&<><label>Cantidad de noches<input type="number" min="1" max="365" value={f.nights||1} onChange={e=>patch({nights:e.target.value})}/></label><label>Tipo de habitación<select value={f.room_type||""} onChange={e=>patch({room_type:e.target.value})}><option value="">Cualquier tipo compatible</option>{roomTypes.map(x=><option key={x}>{x}</option>)}</select></label></>}</div></>}
      {step===5&&<><h3>Inventario</h3><p>Controlá cuántos vouchers pueden utilizarse.</p><div className={s.choiceGrid}>{[["unlimited","Ilimitado","No tiene tope de uso."],["daily","Inventario por día","La cantidad se renueva para cada fecha."],["total","Inventario único total","Se descuenta hasta agotarse."]].map(([value,title,desc])=><button type="button" key={value} className={f.inventory_mode===value?s.choiceActive:""} onClick={()=>patch({inventory_mode:value,inventory_quantity:value==="unlimited"?"":f.inventory_quantity||1})}><b>{title}</b><span>{desc}</span></button>)}</div>{f.inventory_mode!=="unlimited"&&<div className={s.form}><label>Cantidad disponible<input type="number" min="1" value={f.inventory_quantity||1} onChange={e=>patch({inventory_quantity:e.target.value})}/></label></div>}</>}
      {step===6&&<><h3>Vigencia</h3><p>Puede ser ilimitada o quedar disponible sólo entre fechas determinadas.</p><div className={s.choiceGrid}><button type="button" className={f.validity_mode==="unlimited"?s.choiceActive:""} onClick={()=>patch({validity_mode:"unlimited",valid_from:"",valid_to:""})}><b>Ilimitada</b><span>Sin fecha de vencimiento configurada.</span></button><button type="button" className={f.validity_mode==="limited"?s.choiceActive:""} onClick={()=>patch({validity_mode:"limited"})}><b>Vigencia limitada</b><span>Definí desde y hasta cuándo puede utilizarse.</span></button></div>{f.validity_mode==="limited"&&<div className={s.form}><label>Válido desde<input type="date" value={f.valid_from||""} onChange={e=>patch({valid_from:e.target.value})}/></label><label>Válido hasta<input type="date" value={f.valid_to||""} onChange={e=>patch({valid_to:e.target.value})}/></label></div>}</>}
      {step===7&&<><h3>Visibilidad y revisión</h3><p>Elegí dónde se ofrece y revisá el resumen antes de guardar.</p><div className={s.visibilityGrid}><label><input type="checkbox" checked={f.visibility?.booking_engine!==false} onChange={e=>patch({visibility:{...f.visibility,booking_engine:e.target.checked}})}/><span><b>Motor de reservas</b><small>Visible para quien reserva directo.</small></span></label><label><input type="checkbox" checked={Boolean(f.visibility?.website_home)} onChange={e=>patch({visibility:{...f.visibility,website_home:e.target.checked}})}/><span><b>Inicio del sitio</b><small>Preparado para destacarlo en la web del hotel.</small></span></label><label><input type="checkbox" checked={f.visibility?.promotions!==false} onChange={e=>patch({visibility:{...f.visibility,promotions:e.target.checked}})}/><span><b>Sección promociones</b><small>Aparece en la colección de ofertas.</small></span></label></div><div className={s.previewCard}><div><small>VOUCHER</small><h4>{f.name||"Sin nombre"}</h4><p>{f.description||"Sin descripción"}</p></div><strong>{f.price_mode==="free"?"Sin cargo":money(f.price,f.currency||currency)}</strong><dl><div><dt>Estancia</dt><dd>{f.stay_type==="same_day"?"Mismo día":`${f.nights||1} noche${Number(f.nights||1)===1?"":"s"}`}</dd></div><div><dt>Inventario</dt><dd>{f.inventory_mode==="unlimited"?"Ilimitado":f.inventory_mode==="daily"?`${f.inventory_quantity||0}/día`:`${f.inventory_quantity||0} total`}</dd></div><div><dt>Vigencia</dt><dd>{f.validity_mode==="unlimited"?"Ilimitada":`${f.valid_from||"—"} → ${f.valid_to||"—"}`}</dd></div></dl></div></>}
    </div>
    <footer className={s.wizardFooter}><button type="button" onClick={()=>step===1?setEditing(null):setStep(step-1)}>{step===1?"Cancelar":"← Anterior"}</button><span>Paso {step} de 7</span>{step<7?<button type="button" className={s.primary} disabled={!canNext} onClick={()=>setStep(step+1)}>Siguiente →</button>:<button type="button" className={s.primary} disabled={saving||!String(f.name||"").trim()} onClick={onSave}>{saving?"Guardando…":"Finalizar y guardar"}</button>}</footer>
  </div></div>
}
