"use client"

import{useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import s from"./housekeepingMyDay.module.css"

const TYPE={clean:"Limpieza",stayover:"Repaso",checkout:"Salida",inspection:"Inspección",turndown:"Turn down",linen:"Ropa blanca",minibar:"Minibar",deep_clean:"Profunda",other:"Otra"}
const STATUS={scheduled:"Programada",assigned:"Asignada",in_progress:"En limpieza",inspection:"A inspección",done:"Completada",blocked:"Bloqueada"}
const PRIORITY={low:"Baja",normal:"Media",high:"Alta",urgent:"Urgente"}
const SCORE={urgent:4,high:3,normal:2,low:1}
const SUPERVISOR_ROLES=new Set(["owner","manager","admin","supervisor","housekeeping_supervisor"])
const activeTask=task=>task&&task.status!=="done"
const isOccupied=room=>Boolean(room?.reservation)&&!/Sin estadía activa/i.test(room?.occupancy||"")

function Icon({kind,size=17}){
  const common={width:size,height:size,viewBox:"0 0 24 24",fill:"none","aria-hidden":true}
  if(kind==="person")return <svg {...common}><circle cx="12" cy="8" r="3.2" stroke="currentColor" strokeWidth="1.8"/><path d="M5.5 20c.5-4.1 2.7-6.2 6.5-6.2s6 2.1 6.5 6.2" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></svg>
  if(kind==="alert")return <svg {...common}><path d="M12 4 3.8 19h16.4L12 4Z" stroke="currentColor" strokeWidth="1.8" strokeLinejoin="round"/><path d="M12 9v4.5M12 16.8v.2" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round"/></svg>
  if(kind==="play")return <svg {...common}><path d="m9 7 8 5-8 5V7Z" stroke="currentColor" strokeWidth="1.8" strokeLinejoin="round"/></svg>
  if(kind==="check")return <svg {...common}><path d="m5 12.5 4.2 4L19 7" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round"/></svg>
  if(kind==="plus")return <svg {...common}><path d="M12 5v14M5 12h14" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></svg>
  if(kind==="close")return <svg {...common}><path d="m6 6 12 12M18 6 6 18" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></svg>
  return <svg {...common}><path d="M4 6.5h16v11H4z" stroke="currentColor" strokeWidth="1.8"/><path d="M8 10h8M8 14h5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></svg>
}

function Action({children,onClick,primary=false,danger=false,disabled=false}){
  return <button type="button" className={`${s.action} ${primary?s.primary:""} ${danger?s.danger:""}`} onClick={onClick} disabled={disabled}>{children}</button>
}

export default function HousekeepingMyDay({visible=[],saving,onAdvanceTask,onAdvanceRoom}){
  const[open,setOpen]=useState(false),[identity,setIdentity]=useState({userId:"",propertyId:"",role:""}),[identityLoading,setIdentityLoading]=useState(true)
  const[claimed,setClaimed]=useState(()=>new Set()),[notice,setNotice]=useState(""),[error,setError]=useState("")
  const[reportRoom,setReportRoom]=useState(null),[reportKind,setReportKind]=useState("maintenance"),[reportPriority,setReportPriority]=useState("normal"),[reportDetail,setReportDetail]=useState(""),[reportSaving,setReportSaving]=useState(false)

  const firstRoomId=visible[0]?.id||null
  useEffect(()=>{let cancelled=false;async function loadIdentity(){setIdentityLoading(true);try{const{data:userData,error:userError}=await supabase.auth.getUser();if(userError)throw userError;const userId=userData?.user?.id||"";if(!userId||!firstRoomId){if(!cancelled)setIdentity({userId,propertyId:"",role:""});return}const roomRes=await supabase.from("habitaciones").select("property_id").eq("id",firstRoomId).maybeSingle();if(roomRes.error)throw roomRes.error;const propertyId=roomRes.data?.property_id||"";let role="";if(propertyId){const memberRes=await supabase.from("property_members").select("role").eq("property_id",propertyId).eq("user_id",userId).maybeSingle();if(memberRes.error)throw memberRes.error;role=memberRes.data?.role||""}if(!cancelled){setIdentity({userId,propertyId,role});if(typeof window!=="undefined"&&window.matchMedia("(max-width: 820px)").matches)setOpen(true)}}catch(err){if(!cancelled)setError(err?.message||"No se pudo preparar Mi jornada.")}finally{if(!cancelled)setIdentityLoading(false)}}loadIdentity();return()=>{cancelled=true}},[firstRoomId])

  const canInspect=SUPERVISOR_ROLES.has(identity.role)
  const mine=useMemo(()=>visible.filter(room=>{const task=room.task;if(!activeTask(task))return false;return String(task.assigned_to||"")===identity.userId||claimed.has(String(task.id))}).sort((a,b)=>(SCORE[b.task?.priority]||0)-(SCORE[a.task?.priority]||0)),[visible,identity.userId,claimed])
  const available=useMemo(()=>visible.filter(room=>activeTask(room.task)&&room.task.status==="scheduled"&&!room.task.assigned_to&&!claimed.has(String(room.task.id))).sort((a,b)=>(SCORE[b.task?.priority]||0)-(SCORE[a.task?.priority]||0)),[visible,claimed])
  const inspection=useMemo(()=>canInspect?visible.filter(room=>activeTask(room.task)&&room.task.status==="inspection"&&!mine.some(item=>item.id===room.id)):[],[visible,canInspect,mine])
  const inProgress=mine.filter(room=>room.task?.status==="in_progress").length

  async function takeTask(room){const task=room?.task;if(!task||!identity.userId||!identity.propertyId)return;setError("");setNotice("");try{const{error:updateError}=await supabase.from("hotel_housekeeping_tasks").update({assigned_to:identity.userId,status:"assigned",updated_at:new Date().toISOString()}).eq("id",task.id).eq("property_id",identity.propertyId);if(updateError)throw updateError;setClaimed(current=>new Set([...current,String(task.id)]));setNotice(`Habitación ${room.nombre}: tarea tomada. Ya podés iniciarla.`)}catch(err){setError(err?.message||"No se pudo tomar la tarea.")}}

  function openReport(room,kind="maintenance"){setReportRoom(room);setReportKind(kind);setReportPriority(kind==="guest_declined"?"normal":"normal");setReportDetail("");setError("");setNotice("")}

  async function saveReport(){if(!reportRoom||!identity.propertyId||!identity.userId||reportSaving)return;const detail=reportDetail.trim(),kind=reportKind,room=reportRoom,task=room.task;if(!detail&&kind!=="guest_declined"){setError("Describí brevemente qué pasó.");return}setReportSaving(true);setError("");setNotice("");try{const title=kind==="maintenance"?"Incidencia de mantenimiento":kind==="damage"?"Daño o faltante detectado":kind==="minibar"?"Incidencia de minibar":kind==="lost_found"?"Objeto perdido / encontrado":kind==="guest_declined"?"Huésped rechazó limpieza":"Nota de habitación",reportType=kind==="lost_found"?"lost_found":"room_note";const report=await supabase.from("hotel_housekeeping_room_reports").insert({property_id:identity.propertyId,room_id:room.id,reservation_id:room.reservation?.id||task?.reservation_id||null,kind:reportType,title,detail:detail||"El huésped informó que no desea el servicio de limpieza.",priority:reportPriority,status:"open",created_by:identity.userId});if(report.error)throw report.error
      if(["maintenance","damage"].includes(kind)){const ticket=await supabase.from("hotel_maintenance_tickets").insert({property_id:identity.propertyId,room_id:room.id,reservation_id:room.reservation?.id||task?.reservation_id||null,title:`${title} · Hab. ${room.nombre}`,description:detail||title,priority:reportPriority,status:"open",reported_by:identity.userId,source:"housekeeping",blocks_inventory:false});if(ticket.error)throw ticket.error}
      if(kind==="guest_declined"&&task){const currentNotes=String(task.notes||"").trim(),note=`Huésped rechazó limpieza${detail?`: ${detail}`:""}`,update=await supabase.from("hotel_housekeeping_tasks").update({status:"blocked",notes:currentNotes?`${currentNotes}\n${note}`:note,updated_at:new Date().toISOString()}).eq("id",task.id).eq("property_id",identity.propertyId);if(update.error)throw update.error}
      setNotice(kind==="guest_declined"?`Habitación ${room.nombre}: rechazo registrado y tarea bloqueada.`:`Habitación ${room.nombre}: incidencia registrada${["maintenance","damage"].includes(kind)?" y enviada a Mantenimiento":""}.`);setReportRoom(null);setReportDetail("")
    }catch(err){setError(err?.message||"No se pudo registrar la incidencia.")}finally{setReportSaving(false)}}

  function renderTask(room,{inspectionOnly=false}={}){const task=room.task,status=task?.status,waiting=status==="inspection"&&!canInspect,advanceLabel=status==="scheduled"||status==="assigned"||status==="blocked"?"Iniciar limpieza":status==="in_progress"?"Enviar a inspección":status==="inspection"?"Aprobar habitación":"Actualizar",advanceIcon=status==="inspection"?"check":"play";return <article key={`${inspectionOnly?"inspection":"mine"}-${room.id}`} className={s.card} data-priority={task?.priority||"normal"}>
    <div className={s.cardHead}><div><small>{room.tipo||"Habitación"}</small><h3>Hab. {room.nombre}</h3></div><span className={s.status} data-status={status}>{STATUS[status]||status}</span></div>
    <div className={s.meta}><span>{TYPE[task?.task_type]||task?.task_type||"Limpieza"}</span><span>{PRIORITY[task?.priority]||"Media"}</span>{room.housekeeping_zone?<span>{room.housekeeping_zone}</span>:null}</div>
    <p className={s.occupancy}>{room.occupancy}</p>{task?.notes?<p className={s.notes}>{task.notes}</p>:null}{room.requestCount?<p className={s.request}>Hay {room.requestCount} petición{room.requestCount===1?"":"es"} de huésped pendiente{room.requestCount===1?"":"s"}.</p>:null}
    <footer className={s.cardActions}>{waiting?<span className={s.waiting}>Esperando inspección del supervisor</span>:<Action primary disabled={saving===`task-${task?.id}`} onClick={()=>onAdvanceTask?.(task)}><Icon kind={advanceIcon}/>{saving===`task-${task?.id}`?"Guardando…":advanceLabel}</Action>}<Action onClick={()=>openReport(room)}><Icon kind="alert"/>Incidencia</Action>{isOccupied(room)&&status!=="inspection"?<Action danger onClick={()=>openReport(room,"guest_declined")}>Rechazó limpieza</Action>:null}</footer>
  </article>}

  if(!visible.length)return null
  return <section className={s.shell} data-open={open?"true":"false"}>
    <button type="button" className={s.trigger} onClick={()=>setOpen(value=>!value)} aria-expanded={open}><span className={s.triggerIcon}><Icon kind="person"/></span><span><b>Mi jornada</b><small>{identityLoading?"Preparando tareas…":mine.length?`${mine.length} tarea${mine.length===1?"":"s"} asignada${mine.length===1?"":"s"} · ${inProgress} en curso`:available.length?`${available.length} tarea${available.length===1?"":"s"} disponible${available.length===1?"":"s"} para tomar`:"Sin tareas asignadas"}</small></span><span className={s.chevron}>{open?"−":"+"}</span></button>
    {open?<div className={s.body}>{error?<div className={s.error}>{error}</div>:null}{notice?<div className={s.notice}>{notice}</div>:null}<div className={s.summary}><div><span>Asignadas</span><b>{mine.length}</b></div><div><span>Disponibles</span><b>{available.length}</b></div>{canInspect?<div><span>Para inspeccionar</span><b>{inspection.length}</b></div>:null}</div>
      {mine.length?<section className={s.block}><header><div><small>AHORA</small><h2>Mis habitaciones</h2></div><span>Ordenadas por prioridad</span></header><div className={s.grid}>{mine.map(room=>renderTask(room))}</div></section>:<div className={s.empty}><Icon kind="check" size={20}/><div><b>No tenés tareas asignadas en este momento.</b><span>Si hay tareas abiertas, podés tomarlas desde “Disponibles”.</span></div></div>}
      {available.length?<section className={s.block}><header><div><small>DISPONIBLES</small><h2>Tomar una tarea</h2></div><span>Útil cuando el equipo trabaja sin reparto previo</span></header><div className={s.available}>{available.map(room=><article key={`available-${room.id}`}><div><b>Hab. {room.nombre} · {TYPE[room.task?.task_type]||"Limpieza"}</b><span>{room.occupancy} · prioridad {String(PRIORITY[room.task?.priority]||"Media").toLowerCase()}</span></div><Action onClick={()=>takeTask(room)}><Icon kind="plus"/>Tomar</Action></article>)}</div></section>:null}
      {inspection.length?<section className={s.block}><header><div><small>SUPERVISIÓN</small><h2>Listas para inspeccionar</h2></div><span>La aprobación final libera la habitación</span></header><div className={s.grid}>{inspection.map(room=>renderTask(room,{inspectionOnly:true}))}</div></section>:null}
    </div>:null}
    {reportRoom?<div className={s.modalShade} onMouseDown={event=>event.target===event.currentTarget&&!reportSaving&&setReportRoom(null)}><section className={s.modal} role="dialog" aria-modal="true" aria-label="Registrar incidencia de Housekeeping"><header><div><small>HOUSEKEEPING · HAB. {reportRoom.nombre}</small><h2>Registrar incidencia</h2></div><button type="button" onClick={()=>setReportRoom(null)} disabled={reportSaving} aria-label="Cerrar"><Icon kind="close"/></button></header><div className={s.form}><label><span>Tipo</span><select value={reportKind} onChange={event=>setReportKind(event.target.value)}><option value="maintenance">Mantenimiento</option><option value="damage">Daño o faltante</option><option value="minibar">Minibar</option><option value="lost_found">Objeto perdido / encontrado</option><option value="guest_declined">Huésped rechazó limpieza</option><option value="other">Otra nota</option></select></label><label><span>Prioridad</span><select value={reportPriority} onChange={event=>setReportPriority(event.target.value)}><option value="low">Baja</option><option value="normal">Media</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label className={s.wide}><span>Detalle</span><textarea rows="4" value={reportDetail} onChange={event=>setReportDetail(event.target.value)} placeholder={reportKind==="guest_declined"?"Motivo informado por el huésped (opcional)":"Qué encontraste y qué necesita atención"}/></label>{["maintenance","damage"].includes(reportKind)?<p className={s.formHint}>Al guardar también se crea un ticket real en Mantenimiento para que no quede sólo como una nota de pisos.</p>:reportKind==="guest_declined"?<p className={s.formHint}>La tarea queda bloqueada como “rechazada por el huésped”; no se marcará la habitación como limpia.</p>:null}</div><footer><Action onClick={()=>setReportRoom(null)} disabled={reportSaving}>Cancelar</Action><Action primary onClick={saveReport} disabled={reportSaving}>{reportSaving?"Guardando…":"Registrar"}</Action></footer></section></div>:null}
  </section>
}
