"use client"

import{useCallback,useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabase"
import usePmsAutoRefresh from"../../core/usePmsAutoRefresh"
import useOperationalNotifications from"../../core/useOperationalNotifications"
import s from"./housekeeping.module.css"

const labels={sucia:"Sucia",limpia:"Limpia",inspeccionada:"Inspeccionada",libre:"Lista",mantenimiento:"Mantenimiento",fuera_servicio:"Fuera de servicio"}
const HK_STATUS={scheduled:"Programada",assigned:"Asignada",in_progress:"En curso",inspection:"A inspección",done:"Lista",blocked:"Bloqueada",open:"Nueva",resolved:"Resuelta",cancelled:"Cancelada"}
const HK_TYPE={clean:"Limpieza",stayover:"Repaso",checkout:"Salida",inspection:"Inspección",turndown:"Turn down",linen:"Ropa blanca",minibar:"Minibar",deep_clean:"Profunda",other:"Otra"}
const PRIORITY={low:"Baja",normal:"Media",high:"Alta",urgent:"Urgente"},score={urgent:4,high:3,normal:2,low:1}
const priorityTone=value=>value==="urgent"?"red":value==="high"?"orange":value==="normal"?"yellow":"green"
const stateTone=status=>["done","resolved"].includes(status)?"green":["in_progress","inspection"].includes(status)?"yellow":"red"
const EVENT_LABEL={created:"Creada",status_changed:"Cambio de estado",assigned:"Asignación",priority_changed:"Cambio de prioridad"}

function localDate(){return new Date().toLocaleDateString("en-CA")}
function daysBetween(a,b){return Math.floor((b-a)/86400000)}
function dateLabel(value){if(!value)return"Nunca";return new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(value)).replace(".","")}
function dateTime(value){if(!value)return"Ahora";return new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value)).replace(".","")}
function nextStatus(status){if(["scheduled","assigned","blocked"].includes(status))return"in_progress";if(status==="in_progress")return"inspection";if(status==="inspection")return"done";return null}
function nextLabel(status){const next=nextStatus(status);return next==="in_progress"?"▶ Iniciar":next==="inspection"?"◎ Enviar a inspección":next==="done"?"✓ Completar":""}
function roomSortValue(name){const num=Number(String(name||"").match(/\d+/)?.[0]);return Number.isFinite(num)?num:Number.MAX_SAFE_INTEGER}

export default function HousekeepingWorkspace({propertyId}){
  const[rooms,setRooms]=useState([]),[reservations,setReservations]=useState([]),[tasks,setTasks]=useState([]),[guestRequests,setGuestRequests]=useState([]),[deepTasks,setDeepTasks]=useState([]),[profiles,setProfiles]=useState([])
  const[filter,setFilter]=useState("all"),[query,setQuery]=useState(""),[sortMode,setSortMode]=useState("number"),[mode,setMode]=useState("daily"),[deepCadence,setDeepCadence]=useState(90)
  const[loading,setLoading]=useState(true),[saving,setSaving]=useState(""),[error,setError]=useState("")
  const[timelineTarget,setTimelineTarget]=useState(null),[timeline,setTimeline]=useState([]),[timelineLoading,setTimelineLoading]=useState(false)

  const load=useCallback(async()=>{
    if(!propertyId)return
    setLoading(true);setError("");const today=localDate()
    try{
      const[roomRes,reservationRes,taskRes,requestRes,deepRes,settingsRes,membersRes]=await Promise.all([
        supabase.from("habitaciones").select("id,nombre,tipo,estado,sort_order,housekeeping_zone").eq("property_id",propertyId).eq("activa",true).order("sort_order").order("nombre"),
        supabase.from("reservas").select("id,numero_reserva,nombre_huesped,habitacion_id,habitaciones_ids,fecha_entrada,fecha_salida,estado,hora_llegada_estimada,hora_salida_estimada").eq("property_id",propertyId).lte("fecha_entrada",today).gte("fecha_salida",today).neq("estado","cancelada"),
        supabase.from("hotel_housekeeping_tasks").select("id,reservation_id,room_id,task_type,priority,status,assigned_to,scheduled_for,started_at,completed_at,checklist,notes,created_at,updated_at").eq("property_id",propertyId).neq("task_type","deep_clean").order("updated_at",{ascending:false}),
        supabase.from("hotel_guest_requests").select("id,reservation_id,room_id,title,detail,status,priority,assigned_area,assigned_to,due_at,created_at,updated_at,resolved_at").eq("property_id",propertyId).eq("assigned_area","housekeeping").order("created_at",{ascending:false}),
        supabase.from("hotel_housekeeping_tasks").select("id,reservation_id,room_id,status,priority,scheduled_for,completed_at,created_at,notes").eq("property_id",propertyId).eq("task_type","deep_clean").order("completed_at",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false}),
        supabase.from("property_settings").select("settings").eq("property_id",propertyId).maybeSingle(),
        supabase.from("property_members").select("user_id,role").eq("property_id",propertyId),
      ])
      for(const result of[roomRes,reservationRes,taskRes,requestRes,deepRes,settingsRes,membersRes])if(result.error)throw result.error
      const ids=(membersRes.data||[]).map(row=>row.user_id);let profileRows=[]
      if(ids.length){const profileRes=await supabase.from("profiles").select("id,full_name,role").in("id",ids);if(profileRes.error)throw profileRes.error;profileRows=profileRes.data||[]}
      setRooms(roomRes.data||[]);setReservations(reservationRes.data||[]);setTasks(taskRes.data||[]);setGuestRequests(requestRes.data||[]);setDeepTasks(deepRes.data||[]);setProfiles(profileRows)
      const configured=Number(settingsRes.data?.settings?.housekeeping?.deep_clean_cadence_days);if(configured>0)setDeepCadence(configured)
    }catch(err){setError(err?.message||"No se pudo cargar Housekeeping.")}finally{setLoading(false)}
  },[propertyId])

  useEffect(()=>{load()},[load])
  usePmsAutoRefresh(propertyId,load,["reservas","habitaciones","hotel_housekeeping_tasks","hotel_guest_requests","hotel_operational_events"])
  const notifications=useOperationalNotifications({area:"housekeeping"})

  const profileById=useMemo(()=>new Map(profiles.map(item=>[item.id,item])),[profiles])
  const reservationByRoom=useMemo(()=>{const map=new Map();for(const reservation of reservations){const ids=[reservation.habitacion_id,...(reservation.habitaciones_ids||[])].filter(Boolean);ids.forEach(id=>map.set(Number(id),reservation))}return map},[reservations])
  const reservationById=useMemo(()=>new Map(reservations.map(item=>[Number(item.id),item])),[reservations])
  const requestCountByRoom=useMemo(()=>{const map=new Map();for(const request of guestRequests)if(!["resolved","cancelled"].includes(request.status)&&request.room_id)map.set(Number(request.room_id),(map.get(Number(request.room_id))||0)+1);return map},[guestRequests])
  const taskByRoom=useMemo(()=>{const map=new Map();for(const task of tasks){if(!task.room_id)continue;const id=Number(task.room_id),current=map.get(id);if(!current||current.status==="done"&&task.status!=="done")map.set(id,task)}return map},[tasks])
  const lastDeepByRoom=useMemo(()=>{const map=new Map();for(const task of deepTasks)if(task.room_id&&task.status==="done"&&!map.has(Number(task.room_id)))map.set(Number(task.room_id),task);return map},[deepTasks])

  const enriched=useMemo(()=>rooms.map(room=>{const reservation=reservationByRoom.get(Number(room.id)),task=taskByRoom.get(Number(room.id)),deep=lastDeepByRoom.get(Number(room.id)),today=localDate();let occupancy="Sin estadía activa";if(reservation){if(reservation.fecha_entrada===today&&reservation.fecha_salida===today)occupancy="Entrada y salida hoy";else if(reservation.fecha_entrada===today)occupancy=`Entrada hoy${reservation.hora_llegada_estimada?` · ${reservation.hora_llegada_estimada}`:""}`;else if(reservation.fecha_salida===today)occupancy=`Salida hoy${reservation.hora_salida_estimada?` · ${reservation.hora_salida_estimada}`:""}`;else occupancy=`Alojado · ${reservation.nombre_huesped||"Huésped"}`}const completed=deep?.completed_at||null,elapsed=completed?daysBetween(new Date(completed),new Date()):null,due=elapsed==null?null:deepCadence-elapsed;return{...room,reservation,task,requestCount:requestCountByRoom.get(Number(room.id))||0,occupancy,lastDeep:completed,deepDue:due}}),[rooms,reservationByRoom,taskByRoom,lastDeepByRoom,requestCountByRoom,deepCadence])
  const activeTasks=useMemo(()=>tasks.filter(task=>task.status!=="done").map(task=>({...task,_kind:"task",_entity:"hotel_housekeeping_tasks",title:`${HK_TYPE[task.task_type]||task.task_type}`,detail:task.notes,due_at:task.scheduled_for})),[tasks])
  const activeRequests=useMemo(()=>guestRequests.filter(request=>!["resolved","cancelled"].includes(request.status)).map(request=>({...request,_kind:"request",_entity:"hotel_guest_requests"})),[guestRequests])
  const queue=useMemo(()=>[...activeTasks,...activeRequests].sort((a,b)=>(score[b.priority]||0)-(score[a.priority]||0)||new Date(a.due_at||0)-new Date(b.due_at||0)),[activeTasks,activeRequests])
  const stats=useMemo(()=>({urgent:queue.filter(t=>t.priority==="urgent").length,pending:queue.filter(t=>["scheduled","assigned","blocked","open"].includes(t.status)).length,progress:queue.filter(t=>["in_progress","inspection"].includes(t.status)).length,done:tasks.filter(t=>t.status==="done").length+guestRequests.filter(r=>r.status==="resolved").length}),[queue,tasks,guestRequests])
  const counts=useMemo(()=>Object.fromEntries(Object.keys(labels).map(key=>[key,enriched.filter(room=>room.estado===key).length])),[enriched])
  const visible=useMemo(()=>enriched.filter(room=>(filter==="all"||room.estado===filter)&&(!query||`${room.nombre} ${room.tipo||""} ${room.housekeeping_zone||""} ${room.occupancy} ${room.task?.notes||""}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>{if(sortMode==="priority"){const ap=a.task?score[a.task.priority]||0:0,bp=b.task?score[b.task.priority]||0:0;if(bp!==ap)return bp-ap}if(sortMode==="status"){const order={sucia:0,limpia:1,mantenimiento:2,inspeccionada:3,libre:4};const d=(order[a.estado]??9)-(order[b.estado]??9);if(d)return d}const n=roomSortValue(a.nombre)-roomSortValue(b.nombre);return n||String(a.nombre).localeCompare(String(b.nombre),"es",{numeric:true})}),[enriched,filter,query,sortMode])

  async function registerHistory(room,task,fromStatus,toStatus,note){const{data:userData}=await supabase.auth.getUser();await supabase.from("hotel_housekeeping_history").insert({property_id:propertyId,room_id:room.id,reservation_id:task?.reservation_id||room.reservation?.id||null,task_id:task?.id||null,from_status:fromStatus,to_status:toStatus,source:"housekeeping",note:note||null,metadata:{surface:"housekeeping"},actor_id:userData?.user?.id||null})}
  async function advanceRoom(room){const next=room.estado==="sucia"?"limpia":room.estado==="limpia"?"inspeccionada":null;if(!next)return;setSaving(String(room.id));setError("");try{const{error:updateError}=await supabase.from("habitaciones").update({estado:next}).eq("id",room.id).eq("property_id",propertyId);if(updateError)throw updateError;await registerHistory(room,room.task,room.estado,next,null);await load()}catch(err){setError(err?.message||"No se pudo actualizar la habitación.")}finally{setSaving("")}}
  async function advanceTask(task){const next=nextStatus(task.status);if(!next)return;const room=enriched.find(item=>Number(item.id)===Number(task.room_id));setSaving(`task-${task.id}`);setError("");try{const now=new Date().toISOString(),patch={status:next,updated_at:now};if(next==="in_progress")patch.started_at=now;if(next==="done")patch.completed_at=now;const{error:updateError}=await supabase.from("hotel_housekeeping_tasks").update(patch).eq("id",task.id).eq("property_id",propertyId);if(updateError)throw updateError;if(room&&(next==="inspection"||next==="done")){const to=next==="inspection"?"limpia":"inspeccionada",before=room.estado;const{error:roomError}=await supabase.from("habitaciones").update({estado:to}).eq("id",room.id).eq("property_id",propertyId);if(roomError)throw roomError;await registerHistory(room,task,before,to,`Tarea ${HK_TYPE[task.task_type]||task.task_type}: ${HK_STATUS[next]||next}`)}await load()}catch(err){setError(err?.message||"No se pudo actualizar la tarea de pisos.")}finally{setSaving("")}}
  async function advanceRequest(request){const next=request.status==="open"?"in_progress":request.status==="in_progress"?"resolved":null;if(!next)return;setSaving(`request-${request.id}`);setError("");try{const patch={status:next,updated_at:new Date().toISOString(),resolved_at:next==="resolved"?new Date().toISOString():null};const{error:updateError}=await supabase.from("hotel_guest_requests").update(patch).eq("id",request.id).eq("property_id",propertyId);if(updateError)throw updateError;await load()}catch(err){setError(err?.message||"No se pudo actualizar la petición.")}finally{setSaving("")}}
  async function openTimeline(item){setTimelineTarget(item);setTimeline([]);setTimelineLoading(true);try{const{data,error:timelineError}=await supabase.from("hotel_operational_events").select("id,event_type,from_status,to_status,actor_id,metadata,created_at").eq("property_id",propertyId).eq("entity_type",item._entity).eq("entity_id",item.id).order("created_at",{ascending:true});if(timelineError)throw timelineError;setTimeline(data||[])}catch(err){setError(err?.message||"No se pudo cargar el seguimiento.")}finally{setTimelineLoading(false)}}
  async function registerDeepClean(room){setSaving(`deep-${room.id}`);setError("");try{const{data:userData,error:userError}=await supabase.auth.getUser();if(userError)throw userError;const now=new Date().toISOString();const{error:taskError}=await supabase.from("hotel_housekeeping_tasks").insert({property_id:propertyId,room_id:room.id,reservation_id:room.reservation?.id||null,task_type:"deep_clean",priority:"normal",status:"done",assigned_to:userData?.user?.id||null,scheduled_for:now,started_at:now,completed_at:now,checklist:[],minibar:{},linen:{},notes:null,created_by:userData?.user?.id||null});if(taskError)throw taskError;await load()}catch(err){setError(err?.message||"No se pudo registrar la limpieza profunda.")}finally{setSaving("")}}
  async function saveCadence(){setSaving("cadence");setError("");try{const{data:current,error:readError}=await supabase.from("property_settings").select("settings").eq("property_id",propertyId).maybeSingle();if(readError)throw readError;const settings={...(current?.settings||{}),housekeeping:{...(current?.settings?.housekeeping||{}),deep_clean_cadence_days:deepCadence}};const{error:writeError}=await supabase.from("property_settings").upsert({property_id:propertyId,settings,updated_at:new Date().toISOString()},{onConflict:"property_id"});if(writeError)throw writeError}catch(err){setError(err?.message||"No se pudo guardar la cadencia.")}finally{setSaving("")}}

  return <section className={s.page}>
    <header className={s.header}><div><small>HOUSEKEEPING</small><h1>Panel de Housekeeping</h1><p>Habitaciones, limpiezas y peticiones del área en una sola vista operativa.</p></div><div className={s.headerActions}><div className={s.mode}><button className={mode==="daily"?s.active:""} onClick={()=>setMode("daily")}>Operación diaria</button><button className={mode==="deep"?s.active:""} onClick={()=>setMode("deep")}>Limpieza profunda</button></div>{mode==="daily"?<button className={`${s.notifyButton} ${notifications.enabled?s.notifyOn:""}`} onClick={notifications.toggle}>{notifications.enabled?"🔔 Alertas activas":"🔕 Activar alertas"}</button>:null}</div></header>
    {error&&<div className={s.errorBox}>{error}</div>}
    {loading?<div className={s.note}>Cargando habitaciones…</div>:!rooms.length?<div className={s.note}>Todavía no hay habitaciones activas en esta propiedad.</div>:mode==="daily"?<>
      <div className={s.overview}><article data-tone="red"><span>Urgentes</span><b>{stats.urgent}</b><small>requieren atención ya</small></article><article data-tone="orange"><span>Pendientes</span><b>{stats.pending}</b><small>todavía sin tomar</small></article><article data-tone="yellow"><span>En proceso</span><b>{stats.progress}</b><small>limpieza, inspección o pedido</small></article><article data-tone="green"><span>Resueltas hoy</span><b>{stats.done}</b><small>trabajos completados</small></article></div>
      <section className={s.queue}><header><div><small>COLA DE HOUSEKEEPING</small><h2>{queue.length?`${queue.length} pendientes activos`:"Todo al día"}</h2></div><span>Tareas y peticiones ordenadas automáticamente por urgencia</span></header>{queue.length?<div className={s.queueGrid}>{queue.slice(0,8).map(item=>{const room=rooms.find(r=>Number(r.id)===Number(item.room_id)),reservation=reservationById.get(Number(item.reservation_id))||reservationByRoom.get(Number(item.room_id)),isRequest=item._kind==="request";return <article key={`${item._kind}-${item.id}`} data-priority={priorityTone(item.priority)}><div className={s.queueTop}><span className={s.priorityPill} data-priority={priorityTone(item.priority)}>{PRIORITY[item.priority]||item.priority}</span><span className={s.statePill} data-tone={stateTone(item.status)}>{HK_STATUS[item.status]||item.status}</span></div><span className={s.typePill}>{isRequest?"Petición":"Pisos"}</span><h3>{isRequest?item.title:`Hab. ${room?.nombre||item.room_id} · ${item.title}`}</h3>{reservation?<p>{reservation.nombre_huesped||"Huésped"} · {reservation.numero_reserva||reservation.id}</p>:<p>{room?`Hab. ${room.nombre}`:"Sin huésped vinculado"}</p>}<small>{item.detail||dateTime(item.due_at)}</small><div className={s.queueActions}><button onClick={()=>isRequest?advanceRequest(item):advanceTask(item)} disabled={saving===`${isRequest?"request":"task"}-${item.id}`}>{saving===`${isRequest?"request":"task"}-${item.id}`?"Guardando…":isRequest?(item.status==="in_progress"?"✓ Resolver":"▶ Tomar") : nextLabel(item.status)}</button><button onClick={()=>openTimeline(item)}>Historial</button></div></article>})}</div>:<div className={s.goodState}>✓ No hay tareas ni peticiones activas de Housekeeping.</div>}</section>
      <div className={s.stats}>{Object.entries(labels).filter(([key])=>key!=="fuera_servicio").map(([key,label])=><button key={key} className={filter===key?s.selected:""} onClick={()=>setFilter(filter===key?"all":key)}><span>{label}</span><b>{counts[key]||0}</b></button>)}</div>
      <div className={s.toolbar}><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar habitación, huésped, tipo o zona"/></label><select value={sortMode} onChange={e=>setSortMode(e.target.value)}><option value="number">Orden: habitación</option><option value="priority">Orden: prioridad</option><option value="status">Orden: estado</option></select><button onClick={()=>setFilter("all")}>Todas</button></div>
      <div className={s.roomGrid}>{visible.map(room=><article className={s.roomCard} key={room.id} data-priority={room.task?priorityTone(room.task.priority):room.requestCount?"orange":"none"}><div className={s.roomTop}><div><small>{room.tipo||"Habitación"}</small><h2>{room.nombre}</h2></div><span data-status={room.estado}>{labels[room.estado]||room.estado}</span></div><p className={s.occupancy}>{room.occupancy}</p>{room.requestCount?<div className={s.requestBadge}>● {room.requestCount} petición{room.requestCount===1?"":"es"} pendiente{room.requestCount===1?"":"s"}</div>:null}{room.task?<div className={s.activeTask}><div><span className={s.priorityPill} data-priority={priorityTone(room.task.priority)}>{PRIORITY[room.task.priority]||room.task.priority}</span><b>{HK_TYPE[room.task.task_type]||room.task.task_type}</b></div><span className={s.statePill} data-tone={stateTone(room.task.status)}>{HK_STATUS[room.task.status]||room.task.status}</span>{room.task.notes?<p>{room.task.notes}</p>:null}</div>:<div className={s.noTask}>Sin tarea de limpieza pendiente</div>}<dl><div><dt>Última profunda</dt><dd>{dateLabel(room.lastDeep)}</dd></div><div><dt>Zona</dt><dd>{room.housekeeping_zone||"General"}</dd></div></dl><footer>{room.task&&nextStatus(room.task.status)?<button onClick={()=>advanceTask(room.task)} disabled={saving===`task-${room.task.id}`}>{saving===`task-${room.task.id}`?"Guardando…":nextLabel(room.task.status)}</button>:!room.task&&room.estado==="sucia"?<button onClick={()=>advanceRoom(room)} disabled={saving===String(room.id)}>Marcar limpia</button>:!room.task&&room.estado==="limpia"?<button onClick={()=>advanceRoom(room)} disabled={saving===String(room.id)}>Marcar inspeccionada</button>:null}</footer></article>)}</div>
    </>:<><div className={s.deepToolbar}><div><b>Cadencia de limpieza profunda</b><span>Cada <input type="number" min="1" max="365" value={deepCadence} onChange={e=>setDeepCadence(Math.max(1,Number(e.target.value)||1))}/> días <button onClick={saveCadence} disabled={saving==="cadence"}>Guardar</button></span></div><div><strong>{enriched.filter(r=>r.deepDue==null||r.deepDue<=14).length}</strong><span>habitaciones sin registro o próximas a vencer</span></div></div><div className={s.deepList}>{enriched.map(room=>{const overdue=room.deepDue!=null&&room.deepDue<=0,dueSoon=room.deepDue==null||room.deepDue<=14;return <article key={room.id} className={s.deepRow}><div className={s.deepRoom}><b>{room.nombre}</b><small>{room.tipo||"Habitación"}</small></div><div><small>Última limpieza</small><b>{dateLabel(room.lastDeep)}</b></div><div><small>Próxima</small><b className={overdue?s.overdue:dueSoon?s.soon:""}>{room.deepDue==null?"Sin registro":overdue?"Vencida":`${room.deepDue} días`}</b></div><button onClick={()=>registerDeepClean(room)} disabled={saving===`deep-${room.id}`}>{saving===`deep-${room.id}`?"Guardando…":"Registrar profunda"}</button></article>})}</div></>}

    {timelineTarget&&<div className={s.modalShade} onMouseDown={e=>e.target===e.currentTarget&&setTimelineTarget(null)}><div className={s.modal}><header><div><small>SEGUIMIENTO</small><h2>{timelineTarget.title||HK_TYPE[timelineTarget.task_type]||"Tarea"}</h2></div><button onClick={()=>setTimelineTarget(null)}>×</button></header><div className={s.timeline}>{timelineLoading?<div className={s.note}>Cargando historial…</div>:timeline.map(event=>{const actor=profileById.get(event.actor_id);return <article className={s.timelineItem} key={event.id}><i data-tone={stateTone(event.to_status||event.from_status)}/><div><b>{EVENT_LABEL[event.event_type]||event.event_type}</b><span>{event.from_status&&event.to_status&&event.from_status!==event.to_status?`${HK_STATUS[event.from_status]||event.from_status} → ${HK_STATUS[event.to_status]||event.to_status}`:HK_STATUS[event.to_status]||event.to_status||""}</span><small>{actor?.full_name||"Sistema / usuario"} · {dateTime(event.created_at)}</small></div></article>})}{!timelineLoading&&!timeline.length?<div className={s.note}>Todavía no hay eventos registrados.</div>:null}</div><footer><button onClick={()=>setTimelineTarget(null)}>Cerrar</button></footer></div></div>}
  </section>
}
