"use client"

import s from"./housekeeping.module.css"

const labels={sucia:"Sucia",limpia:"Limpia",inspeccionada:"Inspeccionada",libre:"Lista",mantenimiento:"Mantenimiento",fuera_servicio:"Fuera de servicio"}
const HK_STATUS={scheduled:"Programada",assigned:"Asignada",in_progress:"En curso",inspection:"A inspección",done:"Lista",blocked:"Bloqueada",open:"Nueva",resolved:"Resuelta",cancelled:"Cancelada"}
const HK_TYPE={clean:"Limpieza",stayover:"Repaso",checkout:"Salida",inspection:"Inspección",turndown:"Turn down",linen:"Ropa blanca",minibar:"Minibar",deep_clean:"Profunda",other:"Otra"}
const PRIORITY={low:"Baja",normal:"Media",high:"Alta",urgent:"Urgente"}
const priorityTone=value=>value==="urgent"?"red":value==="high"?"orange":value==="normal"?"yellow":"green"
const stateTone=status=>["done","resolved"].includes(status)?"green":["in_progress","inspection"].includes(status)?"yellow":"red"
function nextStatus(status){if(["scheduled","assigned","blocked"].includes(status))return"in_progress";if(status==="in_progress")return"inspection";if(status==="inspection")return"done";return null}
function nextLabel(status){const next=nextStatus(status);return next==="in_progress"?"▶ Iniciar":next==="inspection"?"◎ Enviar a inspección":next==="done"?"✓ Completar":""}
function dateLabel(value){if(!value)return"Nunca";return new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(value)).replace(".","")}

const bulkBar={display:"flex",alignItems:"center",gap:8,flexWrap:"wrap",padding:"11px 12px",border:"1px solid color-mix(in srgb,var(--accent) 24%,var(--line))",borderRadius:14,background:"color-mix(in srgb,var(--accent) 5%,var(--panelSolid))",boxShadow:"0 8px 24px rgba(20,30,54,.05)"}
const bulkButton={minHeight:38,border:"1px solid var(--line)",borderRadius:11,padding:"8px 11px",background:"var(--panelSolid)",color:"var(--text)",font:"inherit",fontSize:12,fontWeight:850,cursor:"pointer"}

export default function HousekeepingRoomGrid({visible,selectedRoomIds,saving,focusedRoomId,onToggleRoom,onBulkStatus,onClearSelection,onAdvanceTask,onAdvanceRoom}){
  return <>
    {selectedRoomIds.size?<div style={bulkBar}><strong style={{fontSize:13,marginRight:4}}>{selectedRoomIds.size} habitación{selectedRoomIds.size===1?"":"es"} seleccionada{selectedRoomIds.size===1?"":"s"}</strong><button type="button" style={{...bulkButton,color:"#b83d3d",borderColor:"color-mix(in srgb,#d75555 34%,var(--line))"}} onClick={()=>onBulkStatus("sucia")} disabled={saving==="bulk-status"}>● Marcar sucias</button><button type="button" style={{...bulkButton,color:"#916916",borderColor:"color-mix(in srgb,#d7a028 34%,var(--line))"}} onClick={()=>onBulkStatus("limpia")} disabled={saving==="bulk-status"}>● Marcar limpias</button><button type="button" style={{...bulkButton,color:"#26794d",borderColor:"color-mix(in srgb,#2d9f62 34%,var(--line))"}} onClick={()=>onBulkStatus("inspeccionada")} disabled={saving==="bulk-status"}>● Marcar inspeccionadas</button><button type="button" style={{...bulkButton,marginLeft:"auto"}} onClick={onClearSelection} disabled={saving==="bulk-status"}>Cancelar selección</button></div>:null}
    <div className={s.roomGrid}>{visible.map(room=>{const selectedRoom=selectedRoomIds.has(String(room.id));return <article id={`housekeeping-room-${room.id}`} className={s.roomCard} key={room.id} data-priority={room.task?priorityTone(room.task.priority):room.requestCount?"orange":"none"} style={{transition:"box-shadow .18s ease,transform .18s ease",...(selectedRoom?{boxShadow:"0 0 0 2px color-mix(in srgb,var(--accent) 30%,transparent),0 12px 36px rgba(20,30,54,.08)"}:{}),...(focusedRoomId===Number(room.id)?{boxShadow:"0 0 0 3px color-mix(in srgb,var(--accent) 32%,transparent),0 18px 42px color-mix(in srgb,var(--accent) 12%,transparent)",transform:"translateY(-2px)"}:{})}}><div className={s.roomTop}><div style={{display:"flex",alignItems:"flex-start",gap:10}}><input type="checkbox" checked={selectedRoom} onChange={()=>onToggleRoom(room.id)} aria-label={`Seleccionar habitación ${room.nombre}`} style={{width:18,height:18,marginTop:4,accentColor:"var(--accent)",cursor:"pointer"}}/><div><small>{room.tipo||"Habitación"}</small><h2>{room.nombre}</h2></div></div><span data-status={room.estado}>{labels[room.estado]||room.estado}</span></div><p className={s.occupancy}>{room.occupancy}</p>{room.requestCount?<div className={s.requestBadge}>● {room.requestCount} petición{room.requestCount===1?"":"es"} pendiente{room.requestCount===1?"":"s"}</div>:null}{room.task?<div className={s.activeTask}><div><span className={s.priorityPill} data-priority={priorityTone(room.task.priority)}>{PRIORITY[room.task.priority]||room.task.priority}</span><b>{HK_TYPE[room.task.task_type]||room.task.task_type}</b></div><span className={s.statePill} data-tone={stateTone(room.task.status)}>{HK_STATUS[room.task.status]||room.task.status}</span>{room.task.notes?<p>{room.task.notes}</p>:null}</div>:<div className={s.noTask}>Sin tarea de limpieza pendiente</div>}<dl><div><dt>Última profunda</dt><dd>{dateLabel(room.lastDeep)}</dd></div><div><dt>Zona</dt><dd>{room.housekeeping_zone||"General"}</dd></div></dl><footer>{room.task&&nextStatus(room.task.status)?<button onClick={()=>onAdvanceTask(room.task)} disabled={saving===`task-${room.task.id}`}>{saving===`task-${room.task.id}`?"Guardando…":nextLabel(room.task.status)}</button>:!room.task&&room.estado==="sucia"?<button onClick={()=>onAdvanceRoom(room)} disabled={saving===String(room.id)}>Marcar limpia</button>:!room.task&&room.estado==="limpia"?<button onClick={()=>onAdvanceRoom(room)} disabled={saving===String(room.id)}>Marcar inspeccionada</button>:null}</footer></article>})}</div>
  </>
}
