"use client"

import{useMemo,useState}from"react"
import s from"./demand-intelligence.module.css"

const DAY=86400000,CANCELLED=new Set(["cancelada","cancelled","canceled"]),LOST=new Set(["lost","perdido","perdida","rejected","rechazado","cancelled","cancelada"])
const norm=v=>String(v||"").trim().toLowerCase(),day=v=>String(v||"").slice(0,10),asDate=v=>{const d=new Date(`${day(v)}T12:00:00Z`);return Number.isNaN(d.getTime())?null:d},shift=(v,n)=>{const d=asDate(v);if(!d)return"";d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)},diff=(a,b)=>{const x=asDate(a),y=asDate(b);return x&&y?Math.max(0,Math.round((y-x)/DAY)):0},today=()=>new Date().toISOString().slice(0,10)
const isoOf=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?"":d.toISOString().slice(0,10)},inRange=(v,start,end)=>{const d=isoOf(v);return d>=start&&d<end},money=(v,c="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency:c,maximumFractionDigits:0}).format(Number(v)||0),short=v=>new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short"}).format(asDate(v)),monthLabel=v=>new Intl.DateTimeFormat("es-AR",{month:"short"}).format(asDate(v)).replace(".","")
const dateMeta=m=>{const x=m||{};return{start:day(x.check_in||x.checkin||x.arrival_date||x.arrival||x.from||x.fecha_entrada||x.start_date),end:day(x.check_out||x.checkout||x.departure_date||x.departure||x.to||x.fecha_salida||x.end_date)}}
const explicitNoAvailability=e=>["no_availability","availability_empty","availability_no_results","search_no_availability","sold_out"].includes(norm(e.event_name))||e.metadata?.available===false||e.metadata?.has_availability===false
const explicitSearch=e=>["availability_search","engine_search","search_availability","booking_search","availability_empty","availability_no_results","search_no_availability","sold_out"].includes(norm(e.event_name))
const leadBucket=n=>n===0?"Mismo día":n<=3?"1–3":n<=7?"4–7":n<=14?"8–14":n<=29?"15–29":"30+"
const LEADS=["Mismo día","1–3","4–7","8–14","15–29","30+"]
const stayBucket=n=>n<=1?"1 noche":n===2?"2 noches":n===3?"3 noches":n<=5?"4–5 noches":n<=7?"6–7 noches":"8+ noches"
const STAYS=["1 noche","2 noches","3 noches","4–5 noches","6–7 noches","8+ noches"]
const lossReason=r=>{const text=norm(`${r.cancellation_note||""} ${r.notas||""}`);if(/precio|tarifa|caro|cost/.test(text))return"Precio";if(/dispon|completo|ocupad|sold/.test(text))return"Sin disponibilidad";if(/fecha|cambio|pospon/.test(text))return"Cambio de fechas";if(/viaje|cancel/.test(text))return"Viaje cancelado";return"Sin clasificar"}
function Metric({label,value,detail,tone}){return <article className={s.metric} data-tone={tone}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
function Bars({title,eyebrow,rows,valueKey="count",suffix=""}){const max=Math.max(1,...rows.map(x=>x[valueKey]||0));return <article className={s.card}><header><div><small>{eyebrow}</small><h2>{title}</h2></div></header><div className={s.bars}>{rows.map(row=><div key={row.label}><div><span>{row.label}</span><b>{row[valueKey]}{suffix}</b></div><i><em style={{width:`${Math.max(row[valueKey]?5:0,(row[valueKey]||0)/max*100)}%`}}/></i><small>{row.note}</small></div>)}</div></article>}

export default function DemandIntelligence({reservations=[],groups=[],quotes=[],webEvents=[],settings={}}){
 const[period,setPeriod]=useState("90d"),now=today(),start=period==="30d"?shift(now,-29):period==="year"?`${now.slice(0,4)}-01-01`:shift(now,-89),end=shift(now,1),currency=String(settings?.currency||settings?.default_currency||settings?.moneda||"ARS").toUpperCase()
 const searches=useMemo(()=>webEvents.filter(e=>explicitSearch(e)&&inRange(e.created_at,start,end)).map(e=>({...e,...dateMeta(e.metadata)})).filter(e=>e.start&&e.end&&e.end>e.start),[webEvents,start,end])
 const sold=useMemo(()=>reservations.filter(r=>!CANCELLED.has(norm(r.estado))&&!r.no_show&&!r.merged_into_id&&r.created_at&&inRange(r.created_at,start,end)&&r.fecha_entrada&&r.fecha_salida),[reservations,start,end])
 const groupSignals=useMemo(()=>groups.filter(g=>g.created_at&&inRange(g.created_at,start,end)&&g.arrival_date&&g.departure_date&&!LOST.has(norm(g.sales_stage||g.status))),[groups,start,end])
 const signals=useMemo(()=>[...sold.map(r=>({kind:"sold",created:r.created_at,start:day(r.fecha_entrada),end:day(r.fecha_salida),source:r.canal_reserva||r.codigo_canal||"Directa"})),...groupSignals.map(g=>({kind:"group",created:g.created_at,start:day(g.arrival_date),end:day(g.departure_date),source:"Grupos"})),...searches.map(e=>({kind:"search",created:e.created_at,start:e.start,end:e.end,source:e.source||"Motor"}))].filter(x=>x.start&&x.end&&x.end>x.start),[sold,groupSignals,searches])
 const noAvailability=useMemo(()=>webEvents.filter(e=>explicitNoAvailability(e)&&inRange(e.created_at,start,end)).map(e=>({...e,...dateMeta(e.metadata)})).filter(e=>e.start&&e.end&&e.end>e.start),[webEvents,start,end])
 const cancelled=useMemo(()=>reservations.filter(r=>(CANCELLED.has(norm(r.estado))||r.cancelled_at)&&inRange(r.cancelled_at||r.created_at,start,end)&&!r.merged_into_id),[reservations,start,end])
 const lostGroups=useMemo(()=>groups.filter(g=>LOST.has(norm(g.sales_stage||g.status))&&inRange(g.updated_at||g.created_at,start,end)),[groups,start,end])
 const lostValue=cancelled.filter(r=>String(r.moneda||"ARS").toUpperCase()===currency).reduce((a,r)=>a+Number(r.precio_total||0),0)+lostGroups.filter(g=>String(g.budget_currency||currency).toUpperCase()===currency).reduce((a,g)=>a+Number(g.budget_total||0),0)
 const avgLead=signals.length?signals.reduce((a,x)=>a+diff(isoOf(x.created),x.start),0)/signals.length:0,avgStay=signals.length?signals.reduce((a,x)=>a+Math.max(1,diff(x.start,x.end)),0)/signals.length:0
 const leadRows=LEADS.map(label=>{const list=signals.filter(x=>leadBucket(diff(isoOf(x.created),x.start))===label);return{label,count:list.length,note:`${signals.length?Math.round(list.length/signals.length*100):0}% de la demanda registrada`}})
 const stayRows=STAYS.map(label=>{const list=signals.filter(x=>stayBucket(Math.max(1,diff(x.start,x.end)))===label);return{label,count:list.length,note:`${signals.length?Math.round(list.length/signals.length*100):0}% de las señales`}})
 const originRows=useMemo(()=>{const map=new Map();sold.forEach(r=>{const label=String(r.ciudad_huesped||r.provincia_estado_huesped||r.pais_huesped||"").trim();if(!label)return;map.set(label,(map.get(label)||0)+1)});return[...map.entries()].map(([label,count])=>({label,count,note:`${count} reserva${count===1?"":"s"} con origen informado`})).sort((a,b)=>b.count-a.count).slice(0,7)},[sold])
 const lossRows=useMemo(()=>{const map=new Map();cancelled.forEach(r=>{const key=lossReason(r);map.set(key,(map.get(key)||0)+1)});if(lostGroups.length)map.set("Oportunidad grupal perdida",lostGroups.length);if(noAvailability.length)map.set("Sin disponibilidad",(map.get("Sin disponibilidad")||0)+noAvailability.length);return[...map.entries()].map(([label,count])=>({label,count,note:`${count} señal${count===1?"":"es"} perdida${count===1?"":"s"}`})).sort((a,b)=>b.count-a.count)},[cancelled,lostGroups,noAvailability])
 const heat=useMemo(()=>{const startDay=shift(now,-7),days=70,map=new Map();for(let i=0;i<days;i++){const d=shift(startDay,i);map.set(d,{day:d,count:0,unavailable:0})}signals.forEach(x=>{for(let d=x.start;d<x.end;d=shift(d,1))if(map.has(d))map.get(d).count++});noAvailability.forEach(x=>{for(let d=x.start;d<x.end;d=shift(d,1))if(map.has(d))map.get(d).unavailable++});return[...map.values()]},[signals,noAvailability,now]),heatMax=Math.max(1,...heat.map(x=>x.count)),weekday=["L","M","X","J","V","S","D"]
 const nextDemand=heat.filter(x=>x.day>=now).sort((a,b)=>b.count-a.count)[0],lostCount=cancelled.length+lostGroups.length+noAvailability.length
 return <main className={s.page}>
  <header className={s.hero}><div><small>INTELIGENCIA DE DEMANDA · FASE 2</small><h1>Ver lo que el huésped quiere antes de que llegue.</h1><p>Anticipación, duración, fechas buscadas, procedencia y demanda perdida conectadas con señales reales del PMS.</p></div><div className={s.heroStat}><span>SEÑALES ANALIZADAS</span><strong>{signals.length}</strong><small>{sold.length} vendidas · {groupSignals.length+searches.length} consultas/oportunidades</small></div></header>
  <section className={s.filters}><div>{[["30d","30 días"],["90d","90 días"],["year","Año"]].map(([id,label])=><button type="button" key={id} data-active={period===id} onClick={()=>setPeriod(id)}>{label}</button>)}</div><span>{short(start)} → {short(shift(end,-1))}</span></section>
  <section className={s.metrics}><Metric label="Anticipación media" value={`${avgLead.toFixed(1)} días`} detail="Desde la señal hasta el check-in solicitado" tone="violet"/><Metric label="Estadía solicitada" value={`${avgStay.toFixed(1)} noches`} detail="Promedio de todas las señales con fechas" tone="blue"/><Metric label="Fechas sin disponibilidad" value={noAvailability.length?noAvailability.length:"Sin dato"} detail={noAvailability.length?"Búsquedas explícitas sin inventario":"Todavía no hay búsquedas fechadas sin disponibilidad registradas"} tone="rose"/><Metric label="Demanda perdida" value={lostCount} detail={lostValue?`${money(lostValue,currency)} de valor asociado`:`Cancelaciones y oportunidades perdidas`} tone="amber"/><Metric label="Próximo pico" value={nextDemand?.count?short(nextDemand.day):"Sin dato"} detail={nextDemand?.count?`${nextDemand.count} señales para esa noche`:"Sin concentración futura suficiente"} tone="green"/></section>
  <section className={s.two}><Bars eyebrow="ANTICIPACIÓN" title="Cuándo empieza la intención" rows={leadRows}/><Bars eyebrow="DURACIÓN" title="Cuántas noches pide la demanda" rows={stayRows}/></section>
  <article className={s.heatCard}><header><div><small>FECHAS SOLICITADAS</small><h2>Mapa de calor de demanda</h2><p>Últimos 7 días + próximas 9 semanas. La intensidad muestra señales con estadía sobre cada noche; el borde rojo indica búsquedas explícitas sin disponibilidad.</p></div><div className={s.heatLegend}><span><i/>Demanda</span><span><i data-lost/>Sin disponibilidad</span></div></header><div className={s.heatWrap}><div className={s.weekdays}>{weekday.map(x=><b key={x}>{x}</b>)}</div><div className={s.heat}>{heat.map((x,i)=><div key={x.day} className={s.cell} data-today={x.day===now} data-lost={x.unavailable>0} title={`${x.day}: ${x.count} señales${x.unavailable?` · ${x.unavailable} sin disponibilidad`:""}`} style={{"--level":x.count/heatMax}}><span>{day(x.day).slice(8)}</span>{(i<7||day(x.day).slice(8)==="01")&&<small>{monthLabel(x.day)}</small>}</div>)}</div></div></article>
  <section className={s.two}><Bars eyebrow="ORIGEN DECLARADO" title="De dónde viene la demanda vendida" rows={originRows.length?originRows:[{label:"Sin datos de origen",count:0,note:"Se completa cuando la ficha del huésped tiene ciudad, provincia o país"}]}/><Bars eyebrow="DEMANDA PERDIDA" title="Por qué se cae negocio" rows={lossRows.length?lossRows:[{label:"Sin pérdidas clasificables",count:0,note:"No hay cancelaciones, grupos perdidos ni búsquedas sin disponibilidad en el período"}]}/></section>
  <section className={s.truth}><div><small>CALIDAD DEL DATO</small><h2>Sin métricas decorativas</h2></div><p>Las búsquedas y fechas sin disponibilidad sólo entran cuando el motor registra fechas explícitas en sus eventos. Hasta que esa instrumentación genere historial, reservas y grupos aportan demanda real; los estados sin base suficiente se muestran como “Sin dato”.</p><div><span>Reservas</span><b>{sold.length}</b><span>Grupos</span><b>{groupSignals.length}</b><span>Búsquedas fechadas</span><b>{searches.length}</b></div></section>
 </main>
}
