"use client"

import s from"./intelligence-home.module.css"

const norm=v=>String(v||"").trim().toLowerCase(),today=()=>new Date().toISOString().slice(0,10),shift=(value,days)=>{const d=new Date(`${value}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)},validReservation=r=>!["cancelada","cancelled","canceled"].includes(norm(r.estado))&&!r.no_show&&!r.merged_into_id
const inRange=(value,start,end)=>{const d=new Date(value);if(Number.isNaN(d.getTime()))return false;const key=d.toISOString().slice(0,10);return key>=start&&key<end}

function Icon({type}){const paths={demand:<><path d="M4 17V9"/><path d="M10 17V5"/><path d="M16 17v-7"/><path d="M22 17V3"/></>,pipeline:<><path d="M4 6h16"/><path d="M7 12h10"/><path d="M10 18h4"/></>,revenue:<><path d="M4 18V8"/><path d="M10 18V4"/><path d="M16 18v-6"/><path d="m19 6 2-2 2 2"/></>,olivia:<><path d="M12 3a7 7 0 0 0-4 12.74V21l4-2 4 2v-5.26A7 7 0 0 0 12 3Z"/><path d="M9.5 10.5h.01"/><path d="M14.5 10.5h.01"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{paths[type]||paths.demand}</g></svg>}
function Stat({label,value,detail,tone}){return <article className={s.stat} data-tone={tone}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}

export default function IntelligenceHome({data,property,onNavigate}){
 const t=today(),start30=shift(t,-29),end=shift(t,1),currency=String(property?.currency||property?.default_currency||property?.moneda||"ARS").toUpperCase(),reservations=(data.reservations||[]).filter(validReservation),recent=reservations.filter(r=>r.created_at&&inRange(r.created_at,start30,end)),rooms=(data.rooms||[]).filter(r=>r.active!==false&&norm(r.estado)!=="inactiva"),occupied=new Set(reservations.filter(r=>String(r.fecha_entrada||"").slice(0,10)<=t&&String(r.fecha_salida||"").slice(0,10)>t).map(r=>String(r.habitacion_id||r.room_id||"")).filter(Boolean)).size,occupancy=rooms.length?Math.round(occupied/rooms.length*100):0
 const unread=(data.conversations||[]).reduce((sum,c)=>sum+Number(c.unread_count||0),0),openQuotes=(data.quotes||[]).filter(q=>["draft","sent","pendiente","enviado"].includes(norm(q.status))),lostGroups=(data.groups||[]).filter(g=>["lost","perdido","perdida","rejected","rechazado","cancelled","cancelada"].includes(norm(g.sales_stage||g.status))),rejectedQuotes=(data.quotes||[]).filter(q=>["rejected","rechazado","rechazada"].includes(norm(q.status))),lost=Math.max(lostGroups.length,rejectedQuotes.length),futureDemand=reservations.filter(r=>String(r.fecha_entrada||"").slice(0,10)>=t&&String(r.fecha_entrada||"").slice(0,10)<shift(t,30)).length
 const activeValue=openQuotes.filter(q=>String(q.currency||currency).toUpperCase()===currency).reduce((a,q)=>a+Number(q.total||0),0),money=new Intl.NumberFormat("es-AR",{style:"currency",currency,maximumFractionDigits:0}).format(activeValue)
 const actions=[];if(unread)actions.push({tone:"urgent",title:`Responder ${unread} mensaje${unread===1?"":"s"} pendiente${unread===1?"":"s"}`,detail:"Hay conversaciones esperando atención. Conviene resolverlas antes de revisar métricas.",mode:"pipeline",cta:"Abrir pipeline"});if(openQuotes.length)actions.push({tone:"money",title:`Resolver ${openQuotes.length} presupuesto${openQuotes.length===1?"":"s"} abierto${openQuotes.length===1?"":"s"}`,detail:`${money} sigue en juego según los presupuestos de la propiedad.`,mode:"pipeline",cta:"Ver oportunidades"});if(lost)actions.push({tone:"lost",title:`Entender ${lost} oportunidad${lost===1?"":"es"} perdida${lost===1?"":"s"}`,detail:"Revisá motivos y fechas para detectar problemas de precio, disponibilidad o seguimiento.",mode:"demand",cta:"Ver demanda perdida"});if(!actions.length)actions.push({tone:"calm",title:"La operación comercial está al día",detail:"No hay mensajes ni presupuestos pendientes detectados. Podés revisar demanda y rendimiento.",mode:"demand",cta:"Explorar demanda"})
 const modules=[{id:"demand",type:"demand",eyebrow:"DEMANDA",title:"Qué quiere el huésped",detail:`${futureDemand} llegadas previstas en los próximos 30 días. Anticipación, duración y fechas con presión.`,cta:"Abrir demanda"},{id:"pipeline",type:"pipeline",eyebrow:"CONVERSIÓN",title:"Qué negocio necesita atención",detail:`${openQuotes.length} presupuestos abiertos y ${unread} mensajes pendientes, ordenados por prioridad.`,cta:"Abrir pipeline"},{id:"hotel",type:"revenue",eyebrow:"RENDIMIENTO",title:"Cómo está rindiendo el hotel",detail:`Ocupación de hoy: ${rooms.length?`${occupancy}%`:"sin inventario configurado"}. ADR, RevPAR, pickup y producción en contexto.`,cta:"Abrir rendimiento"},{id:"olivia",type:"olivia",eyebrow:"OLIVIA",title:"Qué conviene hacer ahora",detail:"Cruza señales comerciales y operativas para sugerir la próxima acción sin ejecutar envíos ni cobros.",cta:"Abrir OlivIA"}]
 return <main className={s.page}>
  <header className={s.hero}><div><span className={s.kicker}>INTELIGENCIA</span><h1>Decidir qué hacer, sin perderse entre gráficos.</h1><p>Una lectura ejecutiva del negocio: primero lo que requiere acción, después el detalle que explica por qué.</p></div><div className={s.heroMini}><span>HOY</span><strong>{rooms.length?`${occupancy}%`:"—"}</strong><small>ocupación actual</small></div></header>
  <section className={s.stats} aria-label="Panorama de Inteligencia"><Stat label="Ocupación hoy" value={rooms.length?`${occupancy}%`:"Sin dato"} detail={`${occupied} de ${rooms.length} habitaciones ocupadas`} tone="blue"/><Stat label="Pipeline abierto" value={openQuotes.length} detail={openQuotes.length?`${money} en presupuestos activos`:"Sin presupuestos pendientes"} tone="violet"/><Stat label="Mensajes pendientes" value={unread} detail={unread?"Conversaciones para responder":"Bandeja al día"} tone="cyan"/><Stat label="Reservas · 30 días" value={recent.length} detail="Reservas creadas en el período" tone="green"/></section>
  <section className={s.actionPanel}><header><div><span className={s.kicker}>PRIORIDAD</span><h2>Qué hacer ahora</h2></div><small>Basado en datos actuales del PMS</small></header><div className={s.actionList}>{actions.slice(0,3).map((a,i)=><button type="button" key={`${a.title}-${i}`} className={s.action} data-tone={a.tone} onClick={()=>onNavigate(a.mode)}><span className={s.actionIndex}>{String(i+1).padStart(2,"0")}</span><span><strong>{a.title}</strong><small>{a.detail}</small></span><b>{a.cta}<i aria-hidden="true">→</i></b></button>)}</div></section>
  <section className={s.moduleGrid}>{modules.map(m=><button type="button" className={s.module} key={m.id} onClick={()=>onNavigate(m.id)}><span className={s.icon}><Icon type={m.type}/></span><span className={s.kicker}>{m.eyebrow}</span><strong>{m.title}</strong><small>{m.detail}</small><b>{m.cta}<i aria-hidden="true">→</i></b></button>)}</section>
  <section className={s.tools}><div><span className={s.kicker}>DETALLE</span><h2>Herramientas comerciales</h2><p>Quedan disponibles cuando necesitás bajar a operación, sin ocupar espacio permanente en la navegación principal.</p></div><div><button type="button" onClick={()=>onNavigate("sales")}>Ventas directas <span>Embudo, motor y conversión</span></button><button type="button" onClick={()=>onNavigate("automation")}>Reglas y seguimiento <span>Automatizaciones con control humano</span></button></div></section>
 </main>
}
