"use client"

import{useMemo,useState}from"react"
import s from"./sales-intelligence.module.css"

const DAY=86400000
const OTA_WORDS=["booking","expedia","airbnb","despegar","agoda","hotels.com","hotelbeds","vrbo"]
const MOTOR_WORDS=["motor","web"]
const CANCELLED=new Set(["cancelada","cancelled"])
const eventDate=value=>{const d=new Date(value);return Number.isNaN(d.getTime())?null:d}
const isoDay=value=>{const d=eventDate(value);return d?d.toISOString().slice(0,10):""}
const today=()=>new Date().toISOString().slice(0,10)
const shift=(value,days)=>{const d=new Date(`${value}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
const inRange=(value,start,end)=>{const day=isoDay(value);return day>=start&&day<end}
const normalize=value=>String(value||"").trim().toLowerCase()
const channelOf=r=>String(r.canal_reserva||r.codigo_canal||"Directa").trim()||"Directa"
const isOta=r=>OTA_WORDS.some(word=>normalize(channelOf(r)).includes(word))
const isMotor=r=>MOTOR_WORDS.some(word=>normalize(channelOf(r)).includes(word))
const validReservation=r=>!CANCELLED.has(normalize(r.estado))&&!r.no_show&&!r.merged_into_id
const money=(value,currency="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency,maximumFractionDigits:0}).format(Number(value)||0)
const pct=(a,b)=>b?`${(a/b*100).toFixed(a/b*100<10?1:0)}%`:"—"
const clamp=value=>Math.max(0,Math.min(100,Number(value)||0))
const average=values=>values.length?values.reduce((a,b)=>a+b,0)/values.length:0
const rangeFor=key=>{const t=today(),year=Number(t.slice(0,4)),month=Number(t.slice(5,7));if(key==="7d")return{start:shift(t,-6),end:shift(t,1),label:"7 días"};if(key==="30d")return{start:shift(t,-29),end:shift(t,1),label:"30 días"};if(key==="year")return{start:`${year}-01-01`,end:`${year+1}-01-01`,label:`${year}`};const end=month===12?`${year+1}-01-01`:`${year}-${String(month+1).padStart(2,"0")}-01`;return{start:`${year}-${String(month).padStart(2,"0")}-01`,end,label:"Este mes"}}
const shortDate=value=>new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short"}).format(new Date(`${value}T12:00:00Z`))
const sessionKey=(event,index)=>String(event.session_id||event.id||`event-${index}`)

function responseStats(messages,conversationIds,start,end){
  const relevant=(messages||[]).filter(m=>conversationIds.has(String(m.conversation_id))&&inRange(m.occurred_at||m.created_at,start,end)).sort((a,b)=>new Date(a.occurred_at||a.created_at)-new Date(b.occurred_at||b.created_at))
  const byConversation=new Map();for(const message of relevant){const id=String(message.conversation_id),list=byConversation.get(id)||[];list.push(message);byConversation.set(id,list)}
  const waits=[];let answered=0,inbound=0
  for(const list of byConversation.values()){for(let i=0;i<list.length;i++){if(normalize(list[i].direction)!=="inbound")continue;inbound++;const incoming=new Date(list[i].occurred_at||list[i].created_at).getTime();const reply=list.slice(i+1).find(item=>normalize(item.direction)==="outbound");if(reply){const wait=Math.max(0,new Date(reply.occurred_at||reply.created_at).getTime()-incoming);if(wait<DAY*2)waits.push(wait);answered++}}}
  return{averageMs:average(waits),answered,inbound,rate:inbound?answered/inbound*100:0}
}
function duration(ms){if(!ms)return"—";const minutes=Math.round(ms/60000);if(minutes<1)return"< 1 min";if(minutes<60)return`${minutes} min`;const hours=Math.floor(minutes/60),rest=minutes%60;return`${hours} h${rest?` ${rest} min`:""}`}
function stageLabel(value,total){return total?`${value.toLocaleString("es-AR")} · ${pct(value,total)}`:value.toLocaleString("es-AR")}
function Kpi({eyebrow,value,detail,tone="violet"}){return <article className={s.kpi} data-tone={tone}><span>{eyebrow}</span><strong>{value}</strong><small>{detail}</small></article>}
function Funnel({title,subtitle,stages}){const max=Math.max(1,...stages.map(x=>x.value));return <article className={s.funnel}><header><div><small>{subtitle}</small><h2>{title}</h2></div></header><div className={s.funnelBody}>{stages.map((stage,index)=><div className={s.stage} key={stage.label}><div className={s.stageHead}><span>{String(index+1).padStart(2,"0")}</span><div><b>{stage.label}</b><small>{stage.note}</small></div><strong>{stage.value.toLocaleString("es-AR")}</strong></div><div className={s.stageTrack}><i style={{width:`${Math.max(4,stage.value/max*100)}%`}}/></div>{index<stages.length-1?<em>{stage.ratio||pct(stages[index+1].value,stage.value)} avanza</em>:null}</div>)}</div></article>}

export default function SalesIntelligence({reservations=[],conversations=[],messages=[],webEvents=[],quotes=[],groups=[],channelCosts=[],settings={}}){
  const[period,setPeriod]=useState("30d"),range=useMemo(()=>rangeFor(period),[period]),preferred=String(settings?.currency||settings?.default_currency||settings?.moneda||"ARS").toUpperCase(),currencies=useMemo(()=>[...new Set(reservations.map(r=>String(r.moneda||"ARS").toUpperCase()))],[reservations]),[selectedCurrency,setSelectedCurrency]=useState(preferred),currency=currencies.includes(selectedCurrency)?selectedCurrency:(currencies.includes(preferred)?preferred:currencies[0]||"ARS")
  const periodReservations=useMemo(()=>reservations.filter(r=>inRange(r.created_at,range.start,range.end)&&String(r.moneda||"ARS").toUpperCase()===currency&&validReservation(r)),[reservations,range,currency])
  const directReservations=useMemo(()=>periodReservations.filter(r=>!isOta(r)),[periodReservations]),motorReservations=useMemo(()=>periodReservations.filter(isMotor),[periodReservations])
  const directRevenue=directReservations.reduce((sum,r)=>sum+Number(r.precio_total||0),0),motorRevenue=motorReservations.reduce((sum,r)=>sum+Number(r.precio_total||0),0)
  const periodMessages=useMemo(()=>messages.filter(m=>inRange(m.occurred_at||m.created_at,range.start,range.end)),[messages,range]),activeConversationIds=useMemo(()=>new Set(periodMessages.map(m=>String(m.conversation_id))),[periodMessages]),periodConversations=useMemo(()=>conversations.filter(c=>activeConversationIds.has(String(c.id))||inRange(c.created_at,range.start,range.end)),[conversations,activeConversationIds,range]),conversationIds=useMemo(()=>new Set(periodConversations.map(c=>String(c.id))),[periodConversations]),responses=useMemo(()=>responseStats(messages,conversationIds,range.start,range.end),[messages,conversationIds,range])
  const periodQuotes=useMemo(()=>quotes.filter(q=>inRange(q.created_at,range.start,range.end)),[quotes,range]),acceptedQuotes=periodQuotes.filter(q=>normalize(q.status)==="accepted"),openQuotes=periodQuotes.filter(q=>["draft","sent"].includes(normalize(q.status))),openQuoteValue=openQuotes.filter(q=>String(q.currency||currency).toUpperCase()===currency).reduce((sum,q)=>sum+Number(q.total||0),0)
  const reservationGroups=useMemo(()=>new Set(reservations.filter(validReservation).map(r=>String(r.group_id||"")).filter(Boolean)),[reservations]),convertedQuotes=periodQuotes.filter(q=>q.group_id&&reservationGroups.has(String(q.group_id)))
  const events=useMemo(()=>webEvents.filter(e=>inRange(e.created_at,range.start,range.end)),[webEvents,range]),siteEvents=events.filter(e=>normalize(e.event_name)==="site_view"),engineEvents=events.filter(e=>normalize(e.event_name)==="engine_view"),engineSessions=new Set(engineEvents.map(sessionKey)).size,siteSessions=new Set(siteEvents.map(sessionKey)).size
  const motorConversion=engineSessions?motorReservations.length/engineSessions*100:0,quoteWinRate=periodQuotes.length?Math.max(acceptedQuotes.length,convertedQuotes.length)/periodQuotes.length*100:0
  const configuredCommissions=channelCosts.map(c=>Number(c.commission_percent||0)).filter(v=>v>0),commissionRate=average(configuredCommissions),avoidedCommission=commissionRate?directRevenue*commissionRate/100:0
  const unread=periodConversations.reduce((sum,c)=>sum+Number(c.unread_count||0),0),unanswered=Math.max(0,responses.inbound-responses.answered)
  const groupById=useMemo(()=>Object.fromEntries(groups.map(g=>[String(g.id),g])),[groups])
  const quoteContacts=periodQuotes.filter(q=>groupById[String(q.group_id)]?.contact_email||groupById[String(q.group_id)]?.contact_phone).length
  const directChannels=useMemo(()=>{const map=new Map();directReservations.forEach(r=>{const key=channelOf(r),current=map.get(key)||{name:key,count:0,revenue:0};current.count++;current.revenue+=Number(r.precio_total||0);map.set(key,current)});return[...map.values()].sort((a,b)=>b.revenue-a.revenue).slice(0,6)},[directReservations])
  const maxChannel=Math.max(1,...directChannels.map(x=>x.revenue))
  const daily=useMemo(()=>{const days=[];for(let d=range.start;d<range.end;d=shift(d,1))days.push(d);const bucket=days.length>35?7:1,rows=[];for(let i=0;i<days.length;i+=bucket){const start=days[i],end=shift(days[Math.min(days.length-1,i+bucket-1)],1),conv=new Set(messages.filter(m=>inRange(m.occurred_at||m.created_at,start,end)).map(m=>String(m.conversation_id))).size,q=quotes.filter(x=>inRange(x.created_at,start,end)).length,views=new Set(webEvents.filter(x=>normalize(x.event_name)==="engine_view"&&inRange(x.created_at,start,end)).map(sessionKey)).size,book=reservations.filter(r=>inRange(r.created_at,start,end)&&validReservation(r)&&isMotor(r)).length;rows.push({day:start,conv,q,views,book})}return rows},[range,messages,quotes,webEvents,reservations]),dailyMax=Math.max(1,...daily.flatMap(r=>[r.conv,r.q,r.views,r.book]))
  const assistedStages=[{label:"Conversaciones",value:periodConversations.length,note:`${periodMessages.filter(m=>normalize(m.direction)==="inbound").length} mensajes entrantes`},{label:"Presupuestos",value:periodQuotes.length,note:`${quoteContacts} con contacto identificable`},{label:"Ganados",value:Math.max(acceptedQuotes.length,convertedQuotes.length),note:`${convertedQuotes.length} ya vinculados a una reserva`}]
  const motorStages=[{label:"Visitas al sitio",value:siteSessions,note:"Sesiones registradas en la web del hotel"},{label:"Motor abierto",value:engineSessions,note:"Sesiones que llegaron al motor directo"},{label:"Reserva motor",value:motorReservations.length,note:`${money(motorRevenue,currency)} confirmado en el PMS`}]
  return <main className={s.page}>
    <header className={s.hero}><div><small>INTELIGENCIA DE VENTAS · FASE 1</small><h1>Del interés a la reserva, sin adivinar.</h1><p>Conversaciones, presupuestos, tráfico del motor y reservas reales cruzados en una sola lectura comercial.</p></div><div className={s.heroPulse}><span>VENTA DIRECTA</span><strong>{money(directRevenue,currency)}</strong><small>{directReservations.length} reservas · {range.label}</small></div></header>
    <section className={s.filters}><div>{[["7d","7 días"],["30d","30 días"],["month","Mes"],["year","Año"]].map(([id,label])=><button type="button" key={id} data-active={period===id} onClick={()=>setPeriod(id)}>{label}</button>)}</div>{currencies.length>1?<label>Moneda<select value={currency} onChange={e=>setSelectedCurrency(e.target.value)}>{currencies.map(c=><option value={c} key={c}>{c}</option>)}</select></label>:<span>{shortDate(range.start)} → {shortDate(shift(range.end,-1))}</span>}</section>
    <section className={s.kpis}><Kpi eyebrow="Revenue directo" value={money(directRevenue,currency)} detail={`${directReservations.length} reservas sin OTA`} tone="violet"/><Kpi eyebrow="Conversión motor" value={engineSessions?`${motorConversion.toFixed(1)}%`:"—"} detail={engineSessions?`${motorReservations.length} reservas / ${engineSessions} sesiones motor`:"Todavía no hay sesiones suficientes"} tone="blue"/><Kpi eyebrow="Respuesta media" value={duration(responses.averageMs)} detail={`${responses.rate.toFixed(0)}% de consultas respondidas`} tone="cyan"/><Kpi eyebrow="Presupuestos ganados" value={periodQuotes.length?`${quoteWinRate.toFixed(0)}%`:"—"} detail={`${Math.max(acceptedQuotes.length,convertedQuotes.length)} de ${periodQuotes.length} presupuestos`} tone="green"/><Kpi eyebrow="Pipeline abierto" value={money(openQuoteValue,currency)} detail={`${openQuotes.length} presupuestos por resolver`} tone="amber"/><Kpi eyebrow="Comisión OTA potencial evitada" value={commissionRate?money(avoidedCommission,currency):"—"} detail={commissionRate?`Referencia: ${commissionRate.toFixed(1)}% promedio configurado`:`Configurá costos de canales para calcularla`} tone="rose"/></section>
    <section className={s.funnelGrid}><Funnel title="Venta asistida" subtitle="MENSAJES → PRESUPUESTO → RESERVA" stages={assistedStages}/><Funnel title="Motor directo" subtitle="WEB → MOTOR → CONFIRMACIÓN" stages={motorStages}/></section>
    <section className={s.signalGrid}><article className={s.signalCard}><header><div><small>OPORTUNIDADES AHORA</small><h2>Lo que merece atención</h2></div><b>{unread+unanswered+openQuotes.length}</b></header><div className={s.signalRows}><div><span>Consultas sin respuesta</span><strong>{unanswered}</strong><small>{unread} mensajes siguen sin leer</small></div><div><span>Presupuestos abiertos</span><strong>{openQuotes.length}</strong><small>{money(openQuoteValue,currency)} todavía en juego</small></div><div><span>Sesiones motor sin reserva</span><strong>{Math.max(0,engineSessions-motorReservations.length)}</strong><small>Señal de fricción para investigar</small></div></div></article><article className={s.signalCard}><header><div><small>CALIDAD COMERCIAL</small><h2>Salud del embudo</h2></div><span>{range.label}</span></header><div className={s.health}><label><span>Respuesta a consultas</span><b>{responses.rate.toFixed(0)}%</b><i><em style={{width:`${clamp(responses.rate)}%`}}/></i></label><label><span>Presupuestos ganados</span><b>{quoteWinRate.toFixed(0)}%</b><i><em style={{width:`${clamp(quoteWinRate)}%`}}/></i></label><label><span>Conversión del motor</span><b>{engineSessions?`${motorConversion.toFixed(0)}%`:"—"}</b><i><em style={{width:`${clamp(motorConversion)}%`}}/></i></label></div><p>Las tasas usan datos registrados por el PMS. Cuando todavía no existe una base suficiente, se muestra “—” en lugar de inventar un valor.</p></article></section>
    <section className={s.trendCard}><header><div><small>RITMO COMERCIAL</small><h2>Cómo se mueve el embudo</h2></div><div className={s.legend}><span data-kind="conv">Consultas</span><span data-kind="quote">Presupuestos</span><span data-kind="view">Motor</span><span data-kind="book">Reservas</span></div></header><div className={s.trend}>{daily.map((row,index)=><div className={s.day} key={`${row.day}-${index}`} title={`${shortDate(row.day)} · ${stageLabel(row.conv,0)} consultas · ${row.q} presupuestos · ${row.views} motor · ${row.book} reservas`}><div><i data-kind="conv" style={{height:`${Math.max(row.conv?5:0,row.conv/dailyMax*100)}%`}}/><i data-kind="quote" style={{height:`${Math.max(row.q?5:0,row.q/dailyMax*100)}%`}}/><i data-kind="view" style={{height:`${Math.max(row.views?5:0,row.views/dailyMax*100)}%`}}/><i data-kind="book" style={{height:`${Math.max(row.book?5:0,row.book/dailyMax*100)}%`}}/></div><small>{index===0||index===daily.length-1||daily.length<=14?shortDate(row.day):""}</small></div>)}</div></section>
    <section className={s.bottomGrid}><article className={s.channels}><header><div><small>VENTA DIRECTA POR ORIGEN</small><h2>Qué canales propios producen</h2></div><span>{directReservations.length} reservas</span></header>{directChannels.length?<div className={s.channelRows}>{directChannels.map(row=><div key={row.name}><div><b>{row.name}</b><span>{row.count} reservas</span><strong>{money(row.revenue,currency)}</strong></div><i><em style={{width:`${Math.max(3,row.revenue/maxChannel*100)}%`}}/></i></div>)}</div>:<div className={s.empty}>Todavía no hay reservas directas dentro de este período.</div>}</article><aside className={s.note}><small>LECTURA ÚTIL</small><h2>Una sola verdad comercial</h2><p>El panel no usa números de demostración: toma conversaciones, presupuestos, eventos web y reservas que ya existen en Habitación Llena.</p><div><span>Atribución</span><b>Operativa</b><small>En la fase de Pipeline se vincula cada oportunidad punta a punta por huésped y sesión.</small></div><div><span>Motor</span><b>Medición real</b><small>Las visitas ya salen de <code>hotel_web_events</code>; las reservas se validan contra el PMS.</small></div></aside></section>
  </main>
}
