import{supabase}from"../../../lib/supabase"
import{requirePropertyId}from"../data/tenant"
const tenant=id=>requirePropertyId(id)
export async function loadAccessWorkspace(propertyId){const property=tenant(propertyId),[{data:points,error:pErr},{data:links,error:lErr},{data:policy,error:polErr},{data:grants,error:gErr},{data:events,error:eErr},{data:permissions,error:permErr},{data:{user}}]=await Promise.all([supabase.from("hotel_access_points").select("*").eq("property_id",property).order("kind").order("name"),supabase.from("hotel_access_links").select("*").eq("property_id",property).order("sequence"),supabase.from("hotel_access_policies").select("*").eq("property_id",property).maybeSingle(),supabase.from("hotel_access_grants").select("*").eq("property_id",property).order("created_at",{ascending:false}).limit(250),supabase.from("hotel_access_events").select("*").eq("property_id",property).order("created_at",{ascending:false}).limit(400),supabase.from("hotel_role_permissions").select("*").eq("property_id",property).in("permission",["frontdesk.access.open","hotel.access.manage"]),supabase.auth.getUser()]),error=pErr||lErr||polErr||gErr||eErr||permErr;if(error)throw error;let member=null;if(user){const{data,error:mErr}=await supabase.from("property_members").select("user_id,role").eq("property_id",property).eq("user_id",user.id).maybeSingle();if(mErr)throw mErr;member=data||null}return{points:points||[],links:links||[],policy:policy||null,grants:grants||[],events:events||[],permissions:permissions||[],member,user}}
export function subscribeAccessWorkspace(propertyId,onChange){const property=tenant(propertyId),refresh=()=>onChange?.(),channel=supabase.channel(`hl-access-${property}`).on("postgres_changes",{event:"*",schema:"public",table:"hotel_access_points",filter:`property_id=eq.${property}`},refresh).on("postgres_changes",{event:"*",schema:"public",table:"hotel_access_links",filter:`property_id=eq.${property}`},refresh).on("postgres_changes",{event:"*",schema:"public",table:"hotel_access_grants",filter:`property_id=eq.${property}`},refresh).on("postgres_changes",{event:"*",schema:"public",table:"hotel_access_events",filter:`property_id=eq.${property}`},refresh).subscribe();return()=>supabase.removeChannel(channel)}
export async function accessReadiness(reservationId){const{data,error}=await supabase.rpc("hl_access_readiness",{p_reservation_id:Number(reservationId)});if(error)throw error;return data}
export async function generateAccessGrant(reservationId,mode="manual"){const{data,error}=await supabase.rpc("hl_access_generate_grant",{p_reservation_id:Number(reservationId),p_mode:mode});if(error)throw error;return data}
export async function revokeAccessGrant(grantId,reason="manual"){const{data,error}=await supabase.rpc("hl_access_revoke_grant",{p_grant_id:grantId,p_reason:reason});if(error)throw error;return data}
export async function createGuestAccessLink(reservationId){const{data,error}=await supabase.rpc("hl_access_create_guest_link",{p_reservation_id:Number(reservationId)});if(error)throw error;return`${location.origin}/access/${data}`}
export async function assistedAccess(reservationId,pointId){const{data,error}=await supabase.rpc("hl_access_assisted_entry",{p_reservation_id:Number(reservationId),p_access_point_id:pointId});if(error)throw error;return data}
export async function saveAccessPolicy(propertyId,draft){const property=tenant(propertyId),row={property_id:property,enabled:draft.enabled!==false,require_full_payment:draft.require_full_payment!==false,require_checkin:draft.require_checkin!==false,require_room_ready:draft.require_room_ready!==false,require_arrival_time:draft.require_arrival_time!==false,allow_assisted_override:draft.allow_assisted_override!==false,pin_length:Math.max(4,Math.min(8,Number(draft.pin_length||4))),timezone:draft.timezone||"America/Argentina/Buenos_Aires",arrival_lead_minutes:Math.max(0,Number(draft.arrival_lead_minutes||0)),checkout_grace_minutes:Math.max(0,Number(draft.checkout_grace_minutes||0)),updated_at:new Date().toISOString()},{data,error}=await supabase.from("hotel_access_policies").upsert(row,{onConflict:"property_id"}).select("*").single();if(error)throw error;return data}
export async function saveAccessPoint(propertyId,draft){const property=tenant(propertyId),row={property_id:property,room_id:draft.room_id?Number(draft.room_id):null,name:String(draft.name||"").trim(),kind:draft.kind||"common",visibility:draft.visibility||"public",zone:String(draft.zone||"").trim()||null,provider:draft.provider||"PIN",provider_ref:String(draft.provider_ref||"").trim()||null,connection_status:draft.connection_status||"not_connected",pin_enabled:draft.pin_enabled!==false,remote_open_enabled:!!draft.remote_open_enabled,linked_service_kind:String(draft.linked_service_kind||"").trim()||null,active:draft.active!==false,metadata:draft.metadata||{},updated_at:new Date().toISOString()};if(!row.name)throw new Error("El acceso necesita un nombre.");const query=draft.id?supabase.from("hotel_access_points").update(row).eq("id",draft.id).eq("property_id",property):supabase.from("hotel_access_points").insert(row),{data,error}=await query.select("*").single();if(error)throw error;return data}
export async function deleteAccessPoint(propertyId,id){const{error}=await supabase.from("hotel_access_points").delete().eq("property_id",tenant(propertyId)).eq("id",id);if(error)throw error}
export async function saveAccessLink(propertyId,{source_point_id,inherited_point_id,sequence=0}){const property=tenant(propertyId),{data,error}=await supabase.from("hotel_access_links").upsert({property_id:property,source_point_id,inherited_point_id,sequence:Number(sequence||0),active:true},{onConflict:"property_id,source_point_id,inherited_point_id"}).select("*").single();if(error)throw error;return data}
export async function deleteAccessLink(propertyId,id){const{error}=await supabase.from("hotel_access_links").delete().eq("property_id",tenant(propertyId)).eq("id",id);if(error)throw error}
export async function saveAccessRolePermission(propertyId,role,permission,allowed){const property=tenant(propertyId),{error}=await supabase.from("hotel_role_permissions").upsert({property_id:property,role,permission,allowed:!!allowed,updated_at:new Date().toISOString()},{onConflict:"property_id,role,permission"});if(error)throw error}