import{supabase}from"../../../lib/supabase"
import{requirePropertyId}from"../data/tenant"
import{dateSpan,reservationTotal,shiftDate,stayOccupancy}from"../features/frontdesk/reservationModel"
import{uploadReservationDocuments}from"./reservationDocuments"
import{expireTentativeReservations}from"./tentatives"

const text=v=>String(v??"").trim()
const roomIdsInReservation=reservation=>[...new Set([reservation?.habitacion_id,...(Array.isArray(reservation?.habitaciones_ids)?reservation.habitaciones_ids:[])].map(String).filter(Boolean))]
const roomInReservation=(reservation,roomId)=>roomIdsInReservation(reservation).includes(String(roomId))
const humanMoment=value=>{const raw=String(value||"");if(!raw)return"";const[date,time=""]=raw.split("T");return`${date}${time?` ${time.slice(0,5)}`:""}`}
const normalizeCompanions=items=>(Array.isArray(items)?items:[]).slice(0,24).map(item=>{const document=text(item?.documento||item?.dni||item?.document_number),name=text(item?.nombre||item?.name);return{nombre:name,tipo_documento:text(item?.tipo_documento||item?.document_type)||null,documento:document||null,dni:document||null,fecha_nacimiento:item?.fecha_nacimiento||item?.birth_date||null,nacionalidad:text(item?.nacionalidad||item?.nationality)||null,relacion:text(item?.relacion||item?.relationship)||null,es_menor:!!item?.es_menor}}).filter(item=>item.nombre||item.documento)
function selectedRooms(draft,primaryRoom,rooms=[]){
  const byId=new Map((rooms||[]).map(item=>[String(item.id),item])),seen=new Set(),rows=[]
  const add=(id,rateOverride)=>{const key=String(id||"");if(!key||seen.has(key))return;seen.add(key);const actual=byId.get(key)||(String(primaryRoom?.id)===key?primaryRoom:null),rate=rateOverride!==""&&rateOverride!=null?Number(rateOverride||0):Number(actual?.precio||0);rows.push({id:key,room:actual,rate})}
  add(draft.roomId||primaryRoom?.id,draft.rate)
  ;(draft.additionalRooms||[]).forEach(item=>add(item?.roomId,item?.rate))
  return rows
}
function payload(draft,room,propertyId,userId,rooms=[]){
  const occupancy=stayOccupancy(draft)
  if(!occupancy.valid)throw new Error(occupancy.message)
  const totals=reservationTotal(draft,room),chosen=selectedRooms(draft,room,rooms)
  if(!chosen.length)throw new Error("Elegí al menos una habitación.")
  const details=chosen.map((item,index)=>{const source=index===0?room:item.room,rate=index===0?totals.rate:item.rate;return{habitacion_id:Number(item.id),nombre:source?.nombre||draft.additionalRooms?.find(x=>String(x.roomId)===String(item.id))?.name||String(item.id),tipo:source?.tipo||draft.additionalRooms?.find(x=>String(x.roomId)===String(item.id))?.type||"Habitación",tarifa_noche:Number(rate||0),noches:occupancy.billingUnits,subtotal:Number(rate||0)*occupancy.billingUnits}})
  return{property_id:requirePropertyId(propertyId),user_id:userId,alojamiento_id:room.alojamiento_id||null,habitacion_id:Number(chosen[0].id),habitaciones_ids:chosen.map(item=>Number(item.id)),habitaciones_detalle:details,fecha_entrada:draft.start,fecha_salida:draft.end,tipo_estadia:occupancy.stayType,nombre_huesped:text(draft.guest),email_huesped:text(draft.email)||null,telefono_huesped:text(draft.phone)||null,tipo_documento_huesped:text(draft.documentType)||null,dni_huesped:text(draft.document)||null,fecha_nacimiento_huesped:draft.birthDate||null,nacionalidad_huesped:text(draft.nationality)||null,idioma_huesped:text(draft.language)||null,direccion_huesped:text(draft.address)||null,ciudad_huesped:text(draft.city)||null,provincia_estado_huesped:text(draft.province)||null,pais_huesped:text(draft.country)||null,cantidad_huespedes:Math.max(1,Number(draft.pax||1)),canal_reserva:text(draft.channel)||"Directa",codigo_canal:text(draft.channelCode)||null,tarifa_noche:totals.rate,noches:totals.nights,precio_total:totals.total,moneda:draft.currency||"ARS",notas:text(draft.notes)||null,partner_id:draft.partnerId||null,group_id:draft.groupId||null,garantia_tipo:text(draft.guaranteeType)||null,garantia_marca:text(draft.guaranteeBrand)||null,garantia_ultimos4:text(draft.guaranteeLast4)||null,garantia_vencimiento:text(draft.guaranteeExpiry)||null,medio_pago_preferido:text(draft.preferredPayment)||null,vehiculos:Math.max(0,Number(draft.vehicles||0)),tipo_vehiculo:text(draft.vehicleType)||null,dominio_vehiculo:text(draft.vehiclePlate)||null,cochera_total:totals.parking,mascotas:draft.pets||[],mascotas_total:totals.pets,servicios:draft.extras||[],pasajeros:normalizeCompanions(draft.companions),hora_llegada_estimada:occupancy.arrivalTime,hora_salida_estimada:occupancy.departureTime}
}
export async function checkReservationAvailability({propertyId,roomId,roomIds=[],draft,excludeReservationId=null}){
  const pid=requirePropertyId(propertyId),ids=[...new Set([roomId,...roomIds].map(Number).filter(Boolean))],occupancy=stayOccupancy(draft)
  if(!ids.length||!occupancy.valid)return{available:false,type:"invalid",message:occupancy.message||"Elegí al menos una habitación y un período válido antes de guardar."}
  await expireTentativeReservations({propertyId:pid})
  const blockQueryEnd=shiftDate(draft.end,1)
  const[{data:reservations,error:reservationError},{data:blocks,error:blockError}]=await Promise.all([
    supabase.from("reservas").select("id,numero_reserva,nombre_huesped,fecha_entrada,fecha_salida,hora_llegada_estimada,hora_salida_estimada,tipo_estadia,ocupacion_desde_local,ocupacion_hasta_local,habitacion_id,habitaciones_ids,estado,no_show").eq("property_id",pid).neq("estado","cancelada").eq("no_show",false).lt("ocupacion_desde_local",occupancy.endAt).gt("ocupacion_hasta_local",occupancy.startAt),
    supabase.from("bloqueos").select("id,habitacion_id,fecha_desde,fecha_hasta,motivo,detalle").eq("property_id",pid).in("habitacion_id",ids).lt("fecha_desde",blockQueryEnd).gt("fecha_hasta",draft.start),
  ])
  if(reservationError)throw reservationError
  if(blockError)throw blockError
  for(const rid of ids){
    const conflict=(reservations||[]).find(r=>String(r.id)!==String(excludeReservationId||"")&&roomInReservation(r,rid))
    if(conflict){const who=text(conflict.nombre_huesped)||"otro huésped",code=conflict.numero_reserva?` · ${conflict.numero_reserva}`:"",from=humanMoment(conflict.ocupacion_desde_local||`${conflict.fecha_entrada}T${conflict.hora_llegada_estimada||"14:00"}`),to=humanMoment(conflict.ocupacion_hasta_local||`${conflict.fecha_salida}T${conflict.hora_salida_estimada||"10:00"}`);return{available:false,type:"reservation",roomId:rid,reservation:conflict,message:`Una de las habitaciones elegidas ya está ocupada por ${who}${code} desde ${from} hasta ${to}. Cambiá esa habitación o el horario antes de guardar.`}}
    const block=(blocks||[]).find(item=>String(item.habitacion_id)===String(rid)&&occupancy.startAt<`${item.fecha_hasta}T00:00:00`&&occupancy.endAt>`${item.fecha_desde}T00:00:00`)
    if(block){const reason=text(block.motivo||block.detalle)||"bloqueo operativo";return{available:false,type:"block",roomId:rid,block,message:`Una de las habitaciones elegidas está bloqueada del ${block.fecha_desde} al ${block.fecha_hasta} (${reason}). Cambiá esa habitación o el horario antes de guardar.`}}
  }
  return{available:true,type:"free",message:"Disponible"}
}
async function saveStagedGuarantee(reservationId,tokenPayload){if(!tokenPayload?.token)return null;const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("La reserva se creó, pero la sesión venció antes de guardar la tarjeta de garantía.");const response=await fetch("/api/hotel/mercadopago/guarantee",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({reservation_id:Number(reservationId),action:"save_card",...tokenPayload})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||"No se pudo guardar la tarjeta de garantía.");return data}
export async function moveReservation({reservationId,roomId,start,end}){let targetEnd=end;if(!targetEnd){const{data:current,error:readError}=await supabase.from("reservas").select("fecha_entrada,fecha_salida").eq("id",Number(reservationId)).single();if(readError)throw readError;targetEnd=shiftDate(start,Math.max(0,dateSpan(current.fecha_entrada,current.fecha_salida)))}const{data,error}=await supabase.rpc("hl_planning_move_reservation_atomic",{p_reserva_id:Number(reservationId),p_habitacion_id:Number(roomId),p_fecha_entrada:start,p_fecha_salida:targetEnd});if(error)throw error;return Array.isArray(data)?data[0]:data}
export async function checkoutReservation(id){
  const{data:reservation,error:reservationError}=await supabase.from("reservas").select("id,property_id,precio_total").eq("id",Number(id)).single();if(reservationError)throw reservationError
  const[{data:paymentRows,error:paymentsError},{data:guarantee,error:guaranteeError}]=await Promise.all([supabase.from("pagos").select("monto").eq("reserva_id",Number(id)).eq("property_id",reservation.property_id),supabase.from("hotel_guarantees").select("status,authorized_amount,authorization_expires_at").eq("reserva_id",Number(id)).eq("property_id",reservation.property_id).maybeSingle()]);if(paymentsError)throw paymentsError;if(guaranteeError)throw guaranteeError
  const paid=(paymentRows||[]).reduce((sum,row)=>sum+Number(row.monto||0),0),balance=Math.max(0,Number(reservation.precio_total||0)-paid)
  if(balance>.01)throw new Error(`No se puede hacer check-out: queda un saldo pendiente de $ ${balance.toLocaleString("es-AR",{minimumFractionDigits:2,maximumFractionDigits:2})}.`)
  const guaranteeActive=guarantee?.status==="authorized"&&(!guarantee.authorization_expires_at||new Date(guarantee.authorization_expires_at).getTime()>Date.now());if(guaranteeActive)throw new Error(`Antes del check-out resolvé la garantía activa de $ ${Number(guarantee.authorized_amount||0).toLocaleString("es-AR")}: liberala si no hubo daños o registrá el cargo correspondiente.`)
  const{data,error}=await supabase.rpc("hl_checkout_reservation_atomic",{p_reserva_id:Number(id)});if(error)throw error;return Array.isArray(data)?data[0]:data
}
export async function checkinReservation({id,propertyId}){const{error}=await supabase.from("reservas").update({estado:"alojado",checkin_real_at:new Date().toISOString()}).eq("id",id).eq("property_id",requirePropertyId(propertyId));if(error)throw error}
export async function saveReservation({draft,room,rooms=[],propertyId,userId,original}){
  const data=payload(draft,room,propertyId,userId,rooms),pending=draft.pendingDocuments||[],stagedPayments=draft.id?[]:(draft.initialPayments||[]).filter(item=>Number(item.amount)>0&&text(item.method)),stagedGuarantee=draft.id?null:draft.guaranteeTokenPayload,pid=requirePropertyId(propertyId);let saved
  const availability=await checkReservationAvailability({propertyId:pid,roomId:room.id,roomIds:data.habitaciones_ids,draft,excludeReservationId:draft.id||null})
  if(!availability.available)throw new Error(availability.message)
  if(draft.id){delete data.property_id;delete data.user_id;const{data:updated,error}=await supabase.from("reservas").update(data).eq("id",draft.id).eq("property_id",pid).select("*").single();if(error)throw error;saved=updated}else{data.estado="confirmada";data.no_show=false;const rows=stagedPayments.map(item=>({property_id:pid,user_id:userId,monto:Number(item.amount),metodo:text(item.method),moneda:item.currency||draft.currency||"ARS",nota:text(item.note)||null})),{data:created,error}=await supabase.rpc("hl_create_reservation_atomic",{p_reservation:data,p_payments:rows});if(error)throw error;saved=Array.isArray(created)?created[0]:created;if(!saved?.id)throw new Error("La reserva no devolvió una confirmación válida. No se registró ningún pago parcial fuera de la transacción.")}
  if(pending.length){try{const personalKinds=new Set(["documento","dni","pasaporte","licencia"]),items=pending.map(item=>{const holderRole=item.holderRole||(personalKinds.has(item.kind)?"primary":"reservation");return{...item,holderRole,holderName:item.holderName||(holderRole==="primary"?(saved.nombre_huesped||draft.guest):null),guestProfileId:item.guestProfileId||(holderRole==="primary"?saved.guest_profile_id:null)}});await uploadReservationDocuments({propertyId:pid,reservationId:saved.id,userId,items})}catch(error){saved={...saved,document_warning:error?.message||"La reserva quedó creada, pero uno o más documentos quedaron pendientes de subir."};console.warn("Habitación Llena: documentos pendientes",error)}}
  if(stagedGuarantee?.token){try{await saveStagedGuarantee(saved.id,stagedGuarantee)}catch(error){saved={...saved,guarantee_warning:error?.message||"La tarjeta de garantía quedó pendiente de vincular."};console.warn("Habitación Llena: garantía pendiente",error)}}
  return saved
}
export async function savePayment({propertyId,userId,reservationId,amount,method,currency="ARS",note=""}){const{error}=await supabase.from("pagos").insert({property_id:requirePropertyId(propertyId),user_id:userId,reserva_id:Number(reservationId),monto:Number(amount),metodo:method,moneda:currency,nota:note||null});if(error)throw error}
export async function changeReservationRoom({reservationId,roomId,reprice=false}){const{data,error}=await supabase.rpc("hl_planning_change_room_atomic",{p_reserva_id:Number(reservationId),p_habitacion_id:Number(roomId),p_reprice:!!reprice});if(error)throw error;return Array.isArray(data)?data[0]:data}
export async function swapReservations({reservationId,otherReservationId}){const{data,error}=await supabase.rpc("hl_planning_swap_reservations_atomic",{p_reserva_a:Number(reservationId),p_reserva_b:Number(otherReservationId)});if(error)throw error;return data}
export async function undoPlanningOperation(operationGroup){const{data,error}=await supabase.rpc("hl_undo_planning_operation_atomic",{p_operation_group:operationGroup});if(error)throw error;return data}
