"use client"

import{useEffect,useMemo,useState}from"react"
import BookingEngine from"../../book/[slug]/BookingEngine"
import{HOTEL_WEB_COPY}from"./hotelWebsiteCopy"
import c from"./hotelWebsiteCanvas.module.css"
import e from"./hotelWebsiteEditor.module.css"

const DEFAULT_SECTIONS=["hero","rooms","about","promo","benefits","gallery","location","booking","contact"]
const FALLBACKS={classic:"radial-gradient(circle at 72% 22%,#8791d9 0,transparent 28%),linear-gradient(135deg,#2c3264,#11182c 62%,#0c1020)",boutique:"radial-gradient(circle at 78% 28%,#b78b73 0,transparent 30%),linear-gradient(135deg,#6e493e,#312522 64%,#171312)",minimal:"linear-gradient(125deg,#5b6676 0 28%,#151c28 28% 72%,#080c12 72%)",coast:"radial-gradient(circle at 70% 28%,#93d7d0 0,transparent 27%),linear-gradient(145deg,#1b777a,#194c59 62%,#102b37)",urban:"linear-gradient(115deg,#121b31 0 40%,#4054c7 40% 62%,#111827 62%)",lodge:"radial-gradient(circle at 76% 24%,#ab9271 0,transparent 25%),linear-gradient(145deg,#50644a,#273b2d 60%,#18251c)",premium:"radial-gradient(circle at 75% 24%,rgba(183,152,93,.32) 0,transparent 28%),linear-gradient(135deg,#343941,#14171c 58%,#08090b)"}
const imageUrl=item=>typeof item==="string"?item:item?.url||item?.src||""
const money=(value,currency)=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:0}).format(Number(value)||0)
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`
const plusDays=(value,days)=>{const d=new Date(`${value}T12:00:00`);d.setDate(d.getDate()+days);return dateKey(d)}
function normalizedSections(value){const source=Array.isArray(value)?value:[],disabled=new Set(source.filter(x=>x?.enabled===false).map(x=>x.id)),result=source.filter(x=>x?.enabled!==false).map(x=>x.id).filter(Boolean);for(const id of DEFAULT_SECTIONS)if(!result.includes(id)&&!disabled.has(id))result.push(id);return result.length?result:DEFAULT_SECTIONS}
function roomTypes(data,previewRooms){if(Array.isArray(data?.website_room_types)&&data.website_room_types.length)return data.website_room_types;const rooms=Array.isArray(previewRooms)?previewRooms:[],map=new Map();for(const room of rooms){const name=room.tipo||"Habitación",old=map.get(name)||{name,units:0,from_price:Number(room.precio)||0,capacity:Number(room.capacidad)||2};old.units++;if(Number(room.precio)>0&&(!old.from_price||Number(room.precio)<old.from_price))old.from_price=Number(room.precio);old.capacity=Math.max(old.capacity,Number(room.capacidad)||2);map.set(name,old)}return[...map.values()]}

export default function HotelWebsiteCanvas({data,slug,preview=false,previewRooms=[],lang:controlledLang,onLangChange,onEditSection}){
  const[localLang,setLocalLang]=useState("es"),[search,setSearch]=useState({checkIn:"",checkOut:"",guests:2}),[popupOpen,setPopupOpen]=useState(false)
  useEffect(()=>{const d=new Date(),out=new Date(d);out.setDate(out.getDate()+1);setSearch({checkIn:dateKey(d),checkOut:dateKey(out),guests:2})},[])
  const config=data?.website_studio_config&&typeof data.website_studio_config==="object"?data.website_studio_config:{},theme=config.theme||{},hero=config.hero||{},sections=normalizedSections(data?.website_sections),gallery=useMemo(()=>Array.isArray(data?.gallery)?data.gallery.map(imageUrl).filter(Boolean):[],[data?.gallery]),rooms=useMemo(()=>roomTypes(data,previewRooms),[data,previewRooms]),languages=Array.isArray(data?.website_languages)&&data.website_languages.length?data.website_languages:["es"],lang=controlledLang||localLang||languages[0]||"es",t=HOTEL_WEB_COPY[lang]||HOTEL_WEB_COPY.es
  useEffect(()=>{if(preview||!config?.popup?.enabled)return;const timer=setTimeout(()=>setPopupOpen(true),Math.max(0,Number(config.popup.delay_seconds)||5)*1000);return()=>clearTimeout(timer)},[preview,config?.popup?.enabled,config?.popup?.delay_seconds])
  const setLang=value=>{setLocalLang(value);onLangChange?.(value)},heroImage=data?.hero_url||gallery[0]||"",heroTitle=hero.title||data?.name||"Tu hotel",heroSubtitle=hero.subtitle||data?.booking_message||"Reservá directo con disponibilidad real y confirmación inmediata.",sectionOn=id=>sections.includes(id),radius=theme.radius||"soft",headingFont=theme.heading_font||"editorial",bodyFont=theme.body_font||"modern",fallback=FALLBACKS[data?.template]||FALLBACKS.classic
  const submitSearch=e=>{if(preview){e.preventDefault();return}},navTargets=[sectionOn("rooms")&&["#habitaciones",t.rooms],sectionOn("about")&&["#hotel",t.hotel],sectionOn("gallery")&&gallery.length&&["#galeria",t.gallery]].filter(Boolean),editable=preview&&onEditSection?e.editable:"",editProps=(id,label)=>preview&&onEditSection?{"data-edit-label":label,onClick:event=>{event.preventDefault();event.stopPropagation();onEditSection(id)}}:{}
  return <div className={c.site} data-template={data?.template||"classic"} data-radius={radius} data-heading={headingFont} data-body={bodyFont} data-image-tone={theme.image_tone||"natural"} style={{"--site-primary":data?.primary_color||"#5B5CEB","--site-accent":data?.accent_color||"#9B8CFF"}}>
    <header className={c.nav} data-style={theme.nav_style||"glass"}><a className={c.brand} href="#inicio" onClick={preview?event=>event.preventDefault():undefined}>{data?.logo_url?<img src={data.logo_url} alt=""/>:<span>{String(data?.name||"H").slice(0,1)}</span>}<b>{data?.name||"Tu hotel"}</b></a><nav>{navTargets.map(([href,label])=><a key={href} href={href} onClick={preview?event=>event.preventDefault():undefined}>{label}</a>)}</nav><div className={c.navRight}>{languages.length>1?<select aria-label="Idioma" value={lang} onChange={event=>setLang(event.target.value)}>{languages.map(id=><option value={id} key={id}>{id.toUpperCase()}</option>)}</select>:null}<a href="#reservar" className={c.navBook} onClick={preview?event=>event.preventDefault():undefined}>{t.book}</a></div></header>
    <form className={c.searchBar} data-style={theme.search_style||"floating"} action={preview?undefined:`/book/${slug}`} method="get" onSubmit={submitSearch}>{!preview?<input type="hidden" name="source" value="site_hero"/>:null}<label><span>{t.checkIn}</span><input type="date" name="check_in" required value={search.checkIn} onChange={event=>{const checkIn=event.target.value;setSearch(value=>({...value,checkIn,checkOut:!value.checkOut||value.checkOut<=checkIn?plusDays(checkIn,1):value.checkOut}))}}/></label><label><span>{t.checkOut}</span><input type="date" name="check_out" required min={search.checkIn?plusDays(search.checkIn,1):undefined} value={search.checkOut} onChange={event=>setSearch(value=>({...value,checkOut:event.target.value}))}/></label><label><span>{t.guests}</span><input type="number" name="guests" min="1" max="20" value={search.guests} onChange={event=>setSearch(value=>({...value,guests:Math.max(1,Number(event.target.value)||1)}))}/></label><label className={c.promoInput}><span>{t.promo}</span><input name="promo" placeholder="Opcional"/></label><button type="submit">⌕ <b>{t.search}</b></button></form>
    <section id="inicio" className={`${c.hero} ${editable}`} {...editProps("hero","portada")}>{heroImage?<img src={heroImage} alt=""/>:<div className={c.heroFallback} style={{background:fallback}}/>}<div className={c.heroShade}/><div className={c.heroCopy}><small>{hero.eyebrow||t.direct}</small><h1 style={{color:"#fff"}}>{heroTitle}</h1><p style={{color:"rgba(255,255,255,.9)"}}>{heroSubtitle}</p><div><a href="#reservar" onClick={preview?event=>event.preventDefault():undefined}>{t.book}</a>{sectionOn("rooms")?<a className={c.secondary} href="#habitaciones" onClick={preview?event=>event.preventDefault():undefined}>{hero.secondary_cta||t.discover}</a>:null}</div></div></section>
    {sectionOn("rooms")&&rooms.length?<section id="habitaciones" className={`${c.section} ${c.rooms} ${editable}`} {...editProps("rooms","habitaciones")}><Heading eye={t.roomsEye} title={t.roomsTitle}/><div className={c.roomGrid}>{rooms.slice(0,4).map((room,index)=><article key={room.name}><div className={c.roomImage} style={!gallery.length?{background:`linear-gradient(${135+index*17}deg,color-mix(in srgb,var(--site-primary) ${10+index*3}%,#dedede),color-mix(in srgb,var(--site-accent) ${12+index*2}%,#f6f6f4))`}:undefined}>{gallery.length&&gallery[index%gallery.length]?<img src={gallery[index%gallery.length]} alt=""/>:<span>{String(index+1).padStart(2,"0")}</span>}</div><div className={c.roomBody}><small>{room.capacity?`Hasta ${room.capacity} huéspedes`:"Categoría"}</small><h3>{room.name}</h3><div>{Number(room.from_price)>0?<span>{t.from} <b>{money(room.from_price,data?.currency)}</b> {t.night}</span>:<span>Consultá disponibilidad</span>}<a href="#reservar" onClick={preview?event=>event.preventDefault():undefined}>Ver disponibilidad →</a></div></div></article>)}</div></section>:null}
    {sectionOn("about")?<section id="hotel" className={`${c.section} ${c.about} ${editable}`} {...editProps("about","hotel")}><div className={c.aboutMedia} style={!gallery[1]&&!heroImage?{background:fallback}:undefined}>{gallery[1]?<img src={gallery[1]} alt=""/>:heroImage?<img src={heroImage} alt=""/>:null}</div><div className={c.aboutCopy}><small>{t.about}</small><h2>{data?.name}</h2><p>{data?.description||"Una estadía con identidad propia, atención directa y todo lo necesario para disfrutar desde el primer momento."}</p><a href="#reservar" onClick={preview?event=>event.preventDefault():undefined}>{t.book} →</a></div></section>:null}
    {sectionOn("promo")&&Array.isArray(data?.vouchers)&&data.vouchers.length?<section className={`${c.section} ${c.promo} ${editable}`} {...editProps("promo","promoción")}><div><small>PROMOCIONES</small><h2>{data.vouchers[0].name}</h2><p>{data.vouchers[0].description||data.vouchers[0].commercial_conditions||"Una propuesta especial para reservar directo."}</p><a href="#reservar" onClick={preview?event=>event.preventDefault():undefined}>Ver promoción →</a></div>{data.vouchers[0].image_url?<img src={data.vouchers[0].image_url} alt=""/>:null}</section>:null}
    {sectionOn("benefits")?<section className={`${c.section} ${c.benefits} ${editable}`} {...editProps("benefits","reserva directa")}><Heading eye={t.benefitsEye} title={t.benefitsTitle}/><div className={c.benefitGrid}>{t.benefits.map(([title,text],index)=><article key={title}><em>{String(index+1).padStart(2,"0")}</em><h3>{title}</h3><p>{text}</p></article>)}</div></section>:null}
    {sectionOn("gallery")&&gallery.length?<section id="galeria" className={`${c.section} ${c.gallery} ${editable}`} {...editProps("gallery","galería")}><Heading eye={t.galleryEye} title={t.galleryTitle}/><div className={c.galleryGrid}>{gallery.slice(0,7).map((url,index)=><figure key={`${url}-${index}`}><img src={url} alt="" loading={index>2?"lazy":"eager"}/><span>{String(index+1).padStart(2,"0")}</span></figure>)}</div></section>:null}
    {sectionOn("services")&&Array.isArray(config.services)&&config.services.length?<section className={`${c.section} ${c.services} ${editable}`} {...editProps("services","servicios")}><Heading eye={t.servicesEye} title={t.servicesTitle}/><div className={c.serviceGrid}>{config.services.map((item,index)=><article key={item.id||index}><span>✦</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>:null}
    {sectionOn("testimonials")&&Array.isArray(config.testimonials)&&config.testimonials.length?<section className={`${c.section} ${c.testimonials} ${editable}`} {...editProps("testimonials","opiniones")}><Heading eye={t.testimonialsEye} title={t.testimonialsTitle}/><div className={c.quoteGrid}>{config.testimonials.map((item,index)=><blockquote key={item.id||index}><p>“{item.text}”</p><footer>{item.name||"Huésped"}</footer></blockquote>)}</div></section>:null}
    {sectionOn("location")&&(config?.location?.address||data?.city)?<section className={`${c.section} ${c.location} ${editable}`} {...editProps("location","ubicación")}><Heading eye={t.locationEye} title={t.locationTitle}/><div className={c.locationCard}><div><small>{data?.city||"Ubicación"}</small><h3>{config?.location?.address||data?.city}</h3><p>Consultá la ubicación y organizá tu llegada directamente con el hotel.</p></div>{config?.location?.maps_url?<a href={config.location.maps_url} target="_blank" rel="noreferrer">Abrir mapa ↗</a>:null}</div></section>:null}
    {sectionOn("faq")?<section className={`${c.section} ${c.faq} ${editable}`} {...editProps("faq","preguntas frecuentes")}><Heading eye={t.faqEye} title={t.faqTitle}/><div className={c.faqList}>{(Array.isArray(config.faq)&&config.faq.length?config.faq:t.faq.map(([question,answer],index)=>({id:index,question,answer}))).map(item=><details key={item.id||item.question}><summary>{item.question}<span>＋</span></summary><p>{item.answer}</p></details>)}</div></section>:null}
    {sectionOn("booking")?<section id="reservar" className={`${c.section} ${c.booking} ${editable}`} {...editProps("booking","motor de reservas")}><Heading eye={t.bookingEye} title={t.bookingTitle}/>{preview?<div className={c.bookingDemo}><div><small>{t.checkIn}</small><b>{search.checkIn||"Elegir fecha"}</b></div><div><small>{t.checkOut}</small><b>{search.checkOut||"Elegir fecha"}</b></div><div><small>{t.guests}</small><b>{search.guests} personas</b></div><button type="button">{t.search}</button></div>:<div className={c.bookingShell}><BookingEngine slug={slug} embedded initialSearch={{checkIn:search.checkIn,checkOut:search.checkOut,guests:search.guests}}/></div>}</section>:null}
    {sectionOn("contact")?<footer className={`${c.footer} ${editable}`} {...editProps("contact","contacto")}><div><b>{data?.name}</b><span>{data?.city||"Sitio oficial"}</span></div><div>{data?.contact_phone?<a href={`tel:${data.contact_phone}`}>{data.contact_phone}</a>:null}{data?.contact_email?<a href={`mailto:${data.contact_email}`}>{data.contact_email}</a>:null}</div><small>{t.powered}</small></footer>:null}
    {data?.floating_booking_enabled!==false?<a className={c.floating} data-position={data?.floating_booking_position||"bottom_right"} href="#reservar" onClick={preview?event=>event.preventDefault():undefined}>{data?.floating_booking_label||t.book}<span>→</span></a>:null}
    {popupOpen&&config?.popup?.enabled?<div className={c.popupBackdrop} onMouseDown={event=>{if(event.target===event.currentTarget)setPopupOpen(false)}}><aside className={c.popup}><button type="button" onClick={()=>setPopupOpen(false)} aria-label="Cerrar">×</button><small>BENEFICIO DIRECTO</small><h2>{config.popup.title||"Reservá directo"}</h2><p>{config.popup.text||"Consultá disponibilidad real y confirmá tu estadía directamente con el hotel."}</p><a href="#reservar" onClick={()=>setPopupOpen(false)}>{config.popup.cta_label||t.book}</a></aside></div>:null}
  </div>
}
function Heading({eye,title}){return <header className={c.heading}><small>{eye}</small><h2>{title}</h2></header>}
