"use client";

import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../../lib/supabase";
import ComandaArt from "./ComandaArt";
import s from "../styles/comanda-reports.module.css";

const GROUPS=[
 {key:"sales",title:"Ventas",art:"sale",perm:"reports_sales",items:["Resumen","Detalle","Por concepto","Tiempos de demora"]},
 {key:"cash",title:"Cajas",art:"cash",perm:"reports_cash",items:["Detalle","Pagos","Movimientos"]},
 {key:"workday",title:"Días de trabajo",art:"computer",perm:"reports_workday",items:["Detalle"]},
 {key:"customers",title:"Clientes",art:"user",perm:"reports_customers",items:["Detalle","Registro de incidencias"]},
 {key:"kitchen",title:"Cocinas",art:"kitchen",perm:"reports_kitchen",items:["Ventas","Tiempos de preparación"]},
 {key:"stock",title:"Stock",art:"menu",perm:"reports_stock",items:["Movimientos","Stock actual"]},
 {key:"staff",title:"Funcionarios",art:"waiter",perm:"reports_staff",items:["Detalle","Ventas por funcionario"]},
];
const txt=el=>el?.textContent?.replace(/\s+/g," ").trim()||"";
const money=n=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(Number(n||0));
const date=v=>v?new Date(v).toLocaleString("es-AR"):"-";

export default function ComandaReportsHub(){
 const [open,setOpen]=useState(false),[permissions,setPermissions]=useState({}),[branchName,setBranchName]=useState(""),[data,setData]=useState({orders:[],items:[],payments:[],staff:[],customers:[],incidents:[],kitchens:[],stock:[],stockMoves:[],days:[],cashSessions:[]}),[selected,setSelected]=useState(null),[loading,setLoading]=useState(false);
 const branchId=typeof window!=="undefined"?sessionStorage.getItem("comanda_branch"):null,workstationId=typeof window!=="undefined"?sessionStorage.getItem("comanda_workstation"):null;
 async function load(){if(!branchId)return;setLoading(true);const [{data:w},{data:b},{data:orders},{data:staff},{data:customers},{data:kitchens},{data:stock},{data:stockMoves},{data:days},{data:cashSessions},{data:incidents}]=await Promise.all([supabase.from("comanda_workstations").select("permissions").eq("id",workstationId).maybeSingle(),supabase.from("comanda_branches").select("name").eq("id",branchId).maybeSingle(),supabase.from("comanda_orders").select("id,table_id,waiter_id,status,sale_type,opened_at,closed_at,diners,label,discount_amount").eq("branch_id",branchId).order("opened_at",{ascending:false}).limit(1000),supabase.from("comanda_staff").select("id,name,staff_type,active,created_at").eq("branch_id",branchId),supabase.from("comanda_customers").select("id,name,email,phone,created_at").eq("branch_id",branchId).order("created_at",{ascending:false}).limit(1000),supabase.from("comanda_kitchens").select("id,name,active").eq("branch_id",branchId),supabase.from("comanda_inventory_items").select("*").eq("branch_id",branchId).limit(1000),supabase.from("comanda_inventory_movements").select("*").eq("branch_id",branchId).order("created_at",{ascending:false}).limit(1000),supabase.from("comanda_business_days").select("*").eq("branch_id",branchId).order("opened_at",{ascending:false}).limit(500),supabase.from("comanda_cash_sessions").select("*").in("register_id",(await supabase.from("comanda_cash_registers").select("id").eq("branch_id",branchId)).data?.map(x=>x.id)||[]).order("opened_at",{ascending:false}).limit(1000),supabase.from("comanda_customer_incidents").select("*").eq("branch_id",branchId).order("created_at",{ascending:false}).limit(1000)]);const orderIds=(orders||[]).map(o=>o.id);let items=[],payments=[];if(orderIds.length){const [{data:i},{data:p}]=await Promise.all([supabase.from("comanda_order_items").select("*").in("order_id",orderIds),supabase.from("comanda_payments").select("*").in("order_id",orderIds).order("created_at",{ascending:false})]);items=i||[];payments=p||[]}setPermissions(w?.permissions||{});setBranchName(b?.name||"");setData({orders:orders||[],items,payments,staff:staff||[],customers:customers||[],incidents:incidents||[],kitchens:kitchens||[],stock:stock||[],stockMoves:stockMoves||[],days:days||[],cashSessions:cashSessions||[]});setLoading(false)}
 useEffect(()=>{const f=e=>{const el=e.target?.closest?.("button,a,[role=button]");if(!el)return;const t=txt(el);if(t==="Reportes"){setOpen(true);setSelected(null);setTimeout(load,0)}if(open&&["Principal","Caja activa","Venta / Salón","Venta","Menú","Clientes","Configuración"].includes(t))setOpen(false)};document.addEventListener("click",f,true);return()=>document.removeEventListener("click",f,true)},[open,branchId,workstationId]);
 const summary=useMemo(()=>{const paid=data.payments.reduce((a,x)=>a+Number(x.amount||0),0);const closed=data.orders.filter(o=>o.status==="closed").length;return {sales:paid,orders:data.orders.length,closed,cash:data.payments.filter(p=>p.method==="cash").reduce((a,x)=>a+Number(x.amount||0),0),customers:data.customers.length,staff:data.staff.filter(x=>x.active).length,stock:data.stock.length,workday:data.days.length,kitchen:data.kitchens.filter(x=>x.active).length}},[data]);
 const all=permissions.all===true||permissions.reports===true;const groups=GROUPS.filter(g=>all||permissions[g.perm]===true);
 function reportRows(){if(!selected)return [];const {group,item}=selected;if(group==="sales"){if(item==="Por concepto"){const map=new Map();for(const i of data.items.filter(x=>x.kitchen_status!=="cancelled")){const cur=map.get(i.product_name)||{Producto:i.product_name,Cantidad:0,Importe:0};cur.Cantidad+=Number(i.quantity);cur.Importe+=Number(i.quantity)*Number(i.unit_price);map.set(i.product_name,cur)}return [...map.values()]}if(item==="Tiempos de demora")return data.orders.map(o=>({Comanda:o.id.slice(0,8),Tipo:o.sale_type,Estado:o.status,Apertura:date(o.opened_at),Cierre:date(o.closed_at),Minutos:o.closed_at?Math.round((new Date(o.closed_at)-new Date(o.opened_at))/60000):"Abierta"}));return data.orders.map(o=>({Comanda:o.id.slice(0,8),Tipo:o.sale_type,Estado:o.status,Comensales:o.diners,Apertura:date(o.opened_at),Total:money(data.payments.filter(p=>p.order_id===o.id).reduce((a,p)=>a+Number(p.amount),0))}))}if(group==="cash"){if(item==="Pagos")return data.payments.map(p=>({Fecha:date(p.created_at),Medio:p.method,Importe:money(p.amount),Comanda:p.order_id.slice(0,8)}));return data.cashSessions.map(x=>({Caja:x.register_id?.slice(0,8),Estado:x.status,Apertura:date(x.opened_at),Cierre:date(x.closed_at),Inicial:money(x.opening_amount),Final:money(x.closing_amount)}))}if(group==="workday")return data.days.map(x=>({Fecha:x.business_date||date(x.opened_at),Estado:x.status||"-",Apertura:date(x.opened_at),Cierre:date(x.closed_at)}));if(group==="customers")return item.includes("incid")?data.incidents.map(x=>({Fecha:date(x.created_at),Estado:x.status||"-",Tipo:x.incident_type||x.type||"Incidente",Detalle:x.description||x.notes||""})):data.customers.map(x=>({Nombre:x.name,Email:x.email||"",Teléfono:x.phone||"",Alta:date(x.created_at)}));if(group==="kitchen")return data.items.filter(x=>x.destination==="kitchen"||x.destination==="bar").map(x=>({Producto:x.product_name,Cantidad:Number(x.quantity),Estado:x.kitchen_status,Enviada:date(x.sent_at),Preparada:date(x.prepared_at),Minutos:x.sent_at&&x.prepared_at?Math.round((new Date(x.prepared_at)-new Date(x.sent_at))/60000):"-"}));if(group==="stock")return item==="Movimientos"?data.stockMoves.map(x=>({Fecha:date(x.created_at),Tipo:x.movement_type||x.type||"-",Cantidad:x.quantity||x.qty||0,Nota:x.notes||""})):data.stock.map(x=>({Producto:x.name||x.product_name||"Item",Stock:x.quantity??x.stock_quantity??0,Unidad:x.unit||""}));if(group==="staff"){const totals=new Map();for(const o of data.orders){if(!o.waiter_id)continue;totals.set(o.waiter_id,(totals.get(o.waiter_id)||0)+data.payments.filter(p=>p.order_id===o.id).reduce((a,p)=>a+Number(p.amount),0))}return data.staff.map(x=>({Funcionario:x.name,Tipo:x.staff_type,Estado:x.active?"Activo":"Inactivo",Alta:date(x.created_at),Ventas:money(totals.get(x.id)||0)}))}return []}
 const rows=reportRows();
 function exportXls(){const exportRows=selected?rows:[{Reporte:"Ventas",Valor:summary.sales},{Reporte:"Comandas",Valor:summary.orders},{Reporte:"Caja efectivo",Valor:summary.cash},{Reporte:"Clientes",Valor:summary.customers},{Reporte:"Funcionarios",Valor:summary.staff},{Reporte:"Stock",Valor:summary.stock},{Reporte:"Días de trabajo",Valor:summary.workday},{Reporte:"Cocinas",Valor:summary.kitchen}];const keys=Object.keys(exportRows[0]||{Dato:"Sin datos"});const esc=v=>String(v??"").replace(/\t/g," ").replace(/\n/g," ");const body=[keys.join("\t"),...exportRows.map(r=>keys.map(k=>esc(r[k])).join("\t"))].join("\n");const blob=new Blob(["\ufeff"+body],{type:"application/vnd.ms-excel;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`comanda-${selected?selected.group+"-"+selected.item.toLowerCase().replace(/\W+/g,"-"):"reportes"}-${new Date().toISOString().slice(0,10)}.xls`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
 if(!open)return null;
 return <main className={s.overlay}><header className={s.header}><div><span>REPORTES · {branchName||"SUCURSAL"}</span><h1>{selected?`${GROUPS.find(g=>g.key===selected.group)?.title} · ${selected.item}`:"Reportes"}</h1><p>{selected?`${rows.length} registros encontrados`:"Información operativa y administrativa organizada por área."}</p></div><div style={{display:"flex",gap:8}}>{selected&&<button onClick={()=>setSelected(null)}>Volver</button>}<button onClick={exportXls}>Exportar XLS</button></div></header>{loading?<div className={s.empty}>Cargando información…</div>:selected?<ReportTable rows={rows}/>:<><section className={s.kpis}><article><strong>{money(summary.sales)}</strong><span>Ventas cobradas</span></article><article><strong>{summary.orders}</strong><span>Comandas</span></article><article><strong>{money(summary.cash)}</strong><span>Efectivo registrado</span></article><article><strong>{summary.staff}</strong><span>Funcionarios activos</span></article></section><section className={s.grid}>{groups.map(g=><article key={g.key}><div className={s.art}><ComandaArt kind={g.art}/></div><h2>{g.title}</h2>{g.items.map(item=><button key={item} onClick={()=>setSelected({group:g.key,item})}>{item}</button>)}</article>)}</section>{!groups.length&&<div className={s.empty}>Este puesto no tiene reportes habilitados.</div>}</>}</main>
}
function ReportTable({rows}){if(!rows.length)return <div style={{background:"#fff",borderRadius:16,padding:24}}>No hay datos para este reporte.</div>;const keys=Object.keys(rows[0]);return <div style={{overflow:"auto",background:"#fff",border:"1px solid rgba(110,70,42,.12)",borderRadius:16,maxHeight:"65vh"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{keys.map(k=><th key={k} style={{position:"sticky",top:0,background:"#fff7ed",padding:12,textAlign:"left",borderBottom:"1px solid #f1dfd0"}}>{k}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{keys.map(k=><td key={k} style={{padding:11,borderBottom:"1px solid #f5ebe4"}}>{String(r[k]??"")}</td>)}</tr>)}</tbody></table></div>}
