"use client";

import {useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";
import s from "../styles/comanda-staff.module.css";

function Modal({title,onClose,onSave,saving,children}){return <div className={s.overlay} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={s.modal}><header><h2>{title}</h2><button onClick={onClose}>×</button></header><div className={s.modalBody}>{children}</div><footer><button className={s.secondary} onClick={onClose}>Cancelar</button><button className={s.primary} disabled={saving} onClick={onSave}>{saving?"Guardando…":"Guardar cambios"}</button></footer></section></div>}

export default function ComandaSetupManagers(){
 const [mode,setMode]=useState(null),[rows,setRows]=useState([]),[branch,setBranch]=useState(null),[dialog,setDialog]=useState(null),[saving,setSaving]=useState(false);
 const branchId=typeof window!=="undefined"?sessionStorage.getItem("comanda_branch"):null;
 const access=typeof window!=="undefined"?sessionStorage.getItem("comanda_access_level"):null;
 const canAdmin=["owner","superadmin"].includes(access)||document?.documentElement?.dataset?.comandaRole==="principal";
 async function load(next=mode){if(!branchId||!next)return;const {data:b}=await supabase.from("comanda_branches").select("id,account_id,name").eq("id",branchId).maybeSingle();setBranch(b||null);if(next==="cash"){const {data}=await supabase.from("comanda_cash_registers").select("*").eq("branch_id",branchId).order("register_number");setRows(data||[])}else{const {data}=await supabase.from("comanda_kitchens").select("*").eq("branch_id",branchId).order("name");setRows(data||[])}}
 useEffect(()=>{const f=e=>{const b=e.target?.closest?.("button");if(!b)return;const t=b.textContent?.replace(/\s+/g," ").trim();if(t==="Cajas"){setMode("cash");setTimeout(()=>load("cash"),0)}else if(t==="Cocinas"){setMode("kitchen");setTimeout(()=>load("kitchen"),0)}else if(mode&&["Usuarios","Funcionarios","Puestos","Sectores","Impresoras","Tickets","Notificaciones","Módulos y pagos","Mi cuenta"].includes(t))setMode(null)};document.addEventListener("click",f,true);return()=>document.removeEventListener("click",f,true)},[mode,branchId]);
 function create(){setDialog(mode==="cash"?{mode:"new",data:{name:"Nueva caja",register_number:(rows.reduce((m,r)=>Math.max(m,Number(r.register_number||0)),0)+1),description:"",active:true}}:{mode:"new",data:{name:"Nueva cocina",code:"COCINA",color:"#f97316",active:true}})}
 function edit(r){setDialog(mode==="cash"?{mode:"edit",row:r,data:{name:r.name||"",register_number:Number(r.register_number||1),description:r.description||"",active:r.active!==false}}:{mode:"edit",row:r,data:{name:r.name||"",code:r.code||"",color:r.color||"#f97316",active:r.active!==false}})}
 async function save(){if(!dialog||!branch)return;setSaving(true);const d=dialog.data;let q;if(mode==="cash"){const payload={account_id:branch.account_id,branch_id:branch.id,name:d.name.trim(),register_number:Number(d.register_number),description:d.description.trim()||null,active:d.active};q=dialog.mode==="edit"?supabase.from("comanda_cash_registers").update(payload).eq("id",dialog.row.id):supabase.from("comanda_cash_registers").insert(payload)}else{const payload={account_id:branch.account_id,branch_id:branch.id,name:d.name.trim(),code:d.code.trim().toUpperCase()||null,color:d.color||null,active:d.active};q=dialog.mode==="edit"?supabase.from("comanda_kitchens").update(payload).eq("id",dialog.row.id):supabase.from("comanda_kitchens").insert(payload)}const {error}=await q;setSaving(false);if(error)return alert(error.message);setDialog(null);await load(mode)}
 async function disable(r){if(!confirm(`¿Desactivar ${r.name}?`))return;await supabase.from(mode==="cash"?"comanda_cash_registers":"comanda_kitchens").update({active:false}).eq("id",r.id);await load(mode)}
 if(!mode||!canAdmin)return null;const cash=mode==="cash";
 return <main className={s.manager}><header className={s.header}><div><span>CONFIGURACIÓN</span><h1>{cash?"Cajas":"Cocinas"}</h1><p>{cash?"Cajas físicas y operativas de la sucursal.":"Destinos de preparación para productos y comandas."}</p></div><div className={s.actions}><button className={s.secondary} onClick={()=>setMode(null)}>Volver a Configuración</button><button className={s.primary} onClick={create}>{cash?"Nueva caja":"Nueva cocina"}</button></div></header><section className={s.card}><div className={s.tableWrap}><table><thead><tr><th>Nombre</th><th>{cash?"Número":"Código"}</th><th>{cash?"Descripción":"Color"}</th><th>Estado</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td><td>{cash?r.register_number:r.code||"-"}</td><td>{cash?r.description||"-":<span style={{display:"inline-flex",alignItems:"center",gap:8}}><i style={{width:14,height:14,borderRadius:4,background:r.color||"#ddd",display:"inline-block"}}></i>{r.color||"-"}</span>}</td><td><span className={r.active?s.active:s.inactive}>{r.active?"Activa":"Inactiva"}</span></td><td><div className={s.rowActions}><button onClick={()=>edit(r)}>Editar</button><button className={s.danger} onClick={()=>disable(r)}>Eliminar</button></div></td></tr>)}</tbody></table></div></section>{dialog&&<Modal title={dialog.mode==="new"?(cash?"Nueva caja":"Nueva cocina"):(cash?"Editar caja":"Editar cocina")} onClose={()=>setDialog(null)} onSave={save} saving={saving}><div className={s.formGrid}><label><span>Nombre</span><input value={dialog.data.name} onChange={e=>setDialog(d=>({...d,data:{...d.data,name:e.target.value}}))}/></label>{cash?<><label><span>Número de caja</span><input type="number" min="1" value={dialog.data.register_number} onChange={e=>setDialog(d=>({...d,data:{...d.data,register_number:Number(e.target.value)}}))}/></label><label style={{gridColumn:"1/-1"}}><span>Descripción</span><input value={dialog.data.description} onChange={e=>setDialog(d=>({...d,data:{...d.data,description:e.target.value}}))}/></label></>:<><label><span>Código</span><input value={dialog.data.code} onChange={e=>setDialog(d=>({...d,data:{...d.data,code:e.target.value}}))}/></label><label><span>Color</span><input type="color" value={dialog.data.color} onChange={e=>setDialog(d=>({...d,data:{...d.data,color:e.target.value}}))}/></label></>}<label className={s.check}><input type="checkbox" checked={dialog.data.active} onChange={e=>setDialog(d=>({...d,data:{...d.data,active:e.target.checked}}))}/><span>{cash?"Caja activa":"Cocina activa"}</span></label></div></Modal>}</main>
}
