"use client";

import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../../lib/supabase";
import ComandaArt,{resolveCategoryArt,resolveProductArt} from "./ComandaArt";
import ComandaProductEditor from "./ComandaProductEditor";
import ui from "../styles/comanda-polish.module.css";
import v from "../styles/comanda-menu-visual.module.css";

const money=(value)=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",minimumFractionDigits:0,maximumFractionDigits:2}).format(Number(value||0));
function clickLegacy(rootRef,label){const buttons=[...rootRef.current?.querySelectorAll("button")||[]];const exact=buttons.find(b=>b.textContent?.trim()===label);if(exact)exact.click()}
function ArtBox({item,category,isCategory=false}){const image=item?.image_url;const kind=isCategory?resolveCategoryArt(item):resolveProductArt(item,category);return <div className={`${v.artBox} ${isCategory?v.artCategory:""}`}>{image?<img src={image} alt="" loading="lazy"/>:<ComandaArt kind={kind} className={v.art}/>}</div>}
function ChannelPills({item,onToggle}){return <div className={v.visibilitySet}><button title="Restaurante" className={item.visible_restaurant!==false?v.visibilityOn:v.visibilityOff} onClick={e=>{e.stopPropagation();onToggle?.("visible_restaurant")}}>R</button><button title="Delivery" className={item.visible_delivery!==false?v.visibilityOn:v.visibilityOff} onClick={e=>{e.stopPropagation();onToggle?.("visible_delivery")}}>D</button><button title="Mostrador" className={item.visible_counter!==false?v.visibilityOn:v.visibilityOff} onClick={e=>{e.stopPropagation();onToggle?.("visible_counter")}}>M</button></div>}

export default function ComandaVisualMenu({rootRef,branchId,onNotice}){
  const [categories,setCategories]=useState([]),[products,setProducts]=useState([]),[selected,setSelected]=useState(null),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[categoryMode,setCategoryMode]=useState("buttons"),[productMode,setProductMode]=useState("buttons"),[editingProduct,setEditingProduct]=useState(null);
  async function load(){if(!branchId)return;setLoading(true);const [{data:cats,error:ce},{data:prods,error:pe}]=await Promise.all([supabase.from("comanda_categories").select("*").eq("branch_id",branchId).eq("active",true).order("sort_order").order("name"),supabase.from("comanda_products").select("*").eq("branch_id",branchId).eq("active",true).order("sort_order").order("name")]);if(ce||pe){onNotice?.(ce?.message||pe?.message||"No se pudo cargar el menú");setLoading(false);return}const c=cats||[],p=prods||[];setCategories(c);setProducts(p);setSelected(prev=>prev&&c.some(x=>x.id===prev)?prev:c[0]?.id||null);setLoading(false)}
  useEffect(()=>{let active=true;(async()=>{if(active)await load()})();return()=>{active=false}},[branchId]);
  const selectedCategory=categories.find(x=>x.id===selected)||null;
  const visibleProducts=useMemo(()=>{const q=search.toLowerCase().trim();return products.filter(p=>(!selected||p.category_id===selected)&&(!q||`${p.public_name||p.name} ${p.sku||""}`.toLowerCase().includes(q)))},[products,selected,search]);
  async function toggleVisibility(cat,key){const next=!cat[key];setCategories(rows=>rows.map(x=>x.id===cat.id?{...x,[key]:next}:x));const {error}=await supabase.from("comanda_categories").update({[key]:next}).eq("id",cat.id);if(error){setCategories(rows=>rows.map(x=>x.id===cat.id?{...x,[key]:!next}:x));onNotice?.(error.message)}}
  async function toggleProduct(product,key){const current=product[key]!==false,next=!current;setProducts(rows=>rows.map(x=>x.id===product.id?{...x,[key]:next}:x));const {error}=await supabase.from("comanda_products").update({[key]:next,updated_at:new Date().toISOString()}).eq("id",product.id);if(error){setProducts(rows=>rows.map(x=>x.id===product.id?{...x,[key]:current}:x));onNotice?.(error.message)}}
  const updateProduct=(updated)=>setProducts(rows=>rows.map(p=>p.id===updated.id?updated:p));

  return <section className={v.stage}>
    <header className={v.header}><div><span className={v.eyebrow}>CARTA OPERATIVA</span><h1>Menú</h1><p>Elegí una categoría y después un producto. Lista y Botones muestran la misma información.</p></div><div className={v.headerActions}><button className={ui.secondaryButton} onClick={()=>clickLegacy(rootRef,"Nueva categoría")}>Nueva categoría</button><button className={ui.primaryButton} onClick={()=>clickLegacy(rootRef,"Nuevo producto")}>Nuevo producto</button></div></header>
    <div className={v.tabs}><button className={v.tabActive}>Productos</button><button onClick={()=>clickLegacy(rootRef,"Opciones")}>Opciones</button><button onClick={()=>clickLegacy(rootRef,"Combos")}>Combos</button><button onClick={()=>clickLegacy(rootRef,"Ingredientes")}>Ingredientes</button></div>
    <div className={v.toolbar}><div className={v.searchWrap}><input className={ui.input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto o código…"/><span>{visibleProducts.length} productos</span></div><div className={v.viewSwitch}><span>Categorías</span><button className={categoryMode==="buttons"?v.viewActive:""} onClick={()=>setCategoryMode("buttons")}>Botones</button><button className={categoryMode==="list"?v.viewActive:""} onClick={()=>setCategoryMode("list")}>Lista</button></div><div className={v.viewSwitch}><span>Productos</span><button className={productMode==="buttons"?v.viewActive:""} onClick={()=>setProductMode("buttons")}>Botones</button><button className={productMode==="list"?v.viewActive:""} onClick={()=>setProductMode("list")}>Lista</button></div></div>
    {loading?<div className={v.loading}>Cargando menú…</div>:<>
      {categoryMode==="buttons"?<div className={v.categoryGrid}>{categories.map(cat=><button key={cat.id} className={`${v.categoryCard} ${selected===cat.id?v.categorySelected:""}`} onClick={()=>setSelected(cat.id)}><ArtBox item={cat} isCategory/><div><strong>{cat.public_name||cat.name}</strong><span>{products.filter(p=>p.category_id===cat.id).length} productos</span></div></button>)}</div>:<div className={v.categoryList}>{categories.map(cat=><div key={cat.id} className={`${v.categoryRow} ${selected===cat.id?v.categorySelected:""}`}><button className={v.categoryIdentity} onClick={()=>setSelected(cat.id)}><ArtBox item={cat} isCategory/><span><strong>{cat.public_name||cat.name}</strong><small>{products.filter(p=>p.category_id===cat.id).length} productos</small></span></button><ChannelPills item={cat} onToggle={key=>toggleVisibility(cat,key)}/></div>)}</div>}
      <div className={v.sectionHead}><div><span>PRODUCTOS</span><h2>{selectedCategory?.public_name||selectedCategory?.name||"Todos"}</h2></div><small>{visibleProducts.length} disponibles</small></div>
      {productMode==="buttons"?<div className={v.productGrid}>{visibleProducts.map(product=><button key={product.id} className={v.productCard} onClick={()=>setEditingProduct(product)}><ArtBox item={product} category={selectedCategory}/><div className={v.productInfo}><strong>{product.public_name||product.name}</strong><span>{money(product.restaurant_price??product.price)}</span></div><ChannelPills item={product} onToggle={key=>toggleProduct(product,key)}/>{product.track_stock&&<small className={v.stockPill}>Stock {Number(product.stock_quantity||0)}</small>}</button>)}</div>:<div className={v.productList}>{visibleProducts.map(product=><div key={product.id} className={v.productRow}><button style={{display:"contents"}} onClick={()=>setEditingProduct(product)}><ArtBox item={product} category={selectedCategory}/><div><strong>{product.public_name||product.name}</strong><span>{product.sku||"Sin código"}</span></div><b>{money(product.restaurant_price??product.price)}</b></button><ChannelPills item={product} onToggle={key=>toggleProduct(product,key)}/></div>)}</div>}
      {!visibleProducts.length&&<div className={v.empty}>No hay productos en esta categoría.</div>}
    </>}
    {editingProduct&&<ComandaProductEditor product={editingProduct} categories={categories} branchId={branchId} onClose={()=>setEditingProduct(null)} onSaved={updateProduct}/>} 
  </section>
}
