"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {supabase} from "../../../lib/supabase";
import styles from "../styles/comanda-v1.module.css";

const money=(n)=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(Number(n||0));
const nowIso=()=>new Date().toISOString();

export default function ComandaApp(){
  const [loading,setLoading]=useState(true),[view,setView]=useState("salon"),[toast,setToast]=useState(null);
  const [user,setUser]=useState(null),[account,setAccount]=useState(null),[branches,setBranches]=useState([]),[branchId,setBranchId]=useState("");
  const [staff,setStaff]=useState([]),[activeStaffId,setActiveStaffId]=useState(""),[registers,setRegisters]=useState([]),[cashSessions,setCashSessions]=useState([]),[movements,setMovements]=useState([]);
  const [sectors,setSectors]=useState([]),[sectorId,setSectorId]=useState(""),[tables,setTables]=useState([]),[categories,setCategories]=useState([]),[categoryId,setCategoryId]=useState(""),[products,setProducts]=useState([]);
  const [orders,setOrders]=useState([]),[items,setItems]=useState([]),[payments,setPayments]=useState([]),[selectedOrderId,setSelectedOrderId]=useState("");
  const [modal,setModal]=useState(null);const channelRef=useRef(null),lastKitchenCount=useRef(0);

  const flash=(message,error=false)=>{setToast({message,error});setTimeout(()=>setToast(null),3000)};
  const activeStaff=staff.find(s=>s.id===activeStaffId)||null;
  const isAdmin=activeStaff?.staff_type==="admin";
  const canSell=isAdmin||activeStaff?.staff_type==="waiter"||activeStaff?.staff_type==="cashier";
  const canCash=isAdmin||activeStaff?.staff_type==="cashier";
  const canKitchen=isAdmin||activeStaff?.staff_type==="cook"||activeStaff?.staff_type==="bar";

  async function loadBase(){
    const {data:{user:u}}=await supabase.auth.getUser();if(!u){window.location.href="/comanda/login";return null}setUser(u);
    const {data:a,error}=await supabase.from("comanda_accounts").select("*").order("created_at").limit(1);if(error)throw error;
    if(!a?.[0]){window.location.href="/comanda/onboarding";return null}setAccount(a[0]);return a[0];
  }

  async function loadData(accountId){
    const qs=await Promise.all([
      supabase.from("comanda_branches").select("*").eq("account_id",accountId).eq("active",true).order("name"),
      supabase.from("comanda_staff").select("*").eq("account_id",accountId).eq("active",true).order("name"),
      supabase.from("comanda_cash_registers").select("*").eq("account_id",accountId).eq("active",true).order("name"),
      supabase.from("comanda_cash_sessions").select("*").eq("account_id",accountId).order("opened_at",{ascending:false}).limit(40),
      supabase.from("comanda_cash_movements").select("*").eq("account_id",accountId).order("created_at",{ascending:false}).limit(100),
      supabase.from("comanda_sectors").select("*").eq("account_id",accountId).eq("active",true).order("sort_order"),
      supabase.from("comanda_tables").select("*").eq("account_id",accountId).eq("active",true).order("number"),
      supabase.from("comanda_categories").select("*").eq("account_id",accountId).eq("active",true).order("sort_order"),
      supabase.from("comanda_products").select("*").eq("account_id",accountId).eq("active",true).order("sort_order"),
      supabase.from("comanda_orders").select("*").eq("account_id",accountId).order("opened_at",{ascending:false}).limit(150),
      supabase.from("comanda_order_items").select("*").eq("account_id",accountId).order("created_at"),
      supabase.from("comanda_payments").select("*").eq("account_id",accountId).order("created_at"),
    ]);
    const firstError=qs.find(q=>q.error)?.error;if(firstError)throw firstError;
    const [b,s,r,cs,mv,se,t,c,p,o,i,pay]=qs.map(q=>q.data||[]);
    setBranches(b);setStaff(s);setRegisters(r);setCashSessions(cs);setMovements(mv);setSectors(se);setTables(t);setCategories(c);setProducts(p);setOrders(o);setItems(i);setPayments(pay);
    setBranchId(v=>v||b[0]?.id||"");setActiveStaffId(v=>v||localStorage.getItem("comanda_active_staff")||s[0]?.id||"");setSectorId(v=>v||se[0]?.id||"");setCategoryId(v=>v||c[0]?.id||"");
  }

  async function refreshOps(){if(account)await loadData(account.id)}
  useEffect(()=>{(async()=>{try{const a=await loadBase();if(a)await loadData(a.id)}catch(e){flash(e.message,true)}finally{setLoading(false)}})()},[]);
  useEffect(()=>{if(activeStaffId)localStorage.setItem("comanda_active_staff",activeStaffId)},[activeStaffId]);
  useEffect(()=>{
    if(!account)return;channelRef.current?.unsubscribe();
    const ch=supabase.channel(`comanda-${account.id}`)
      .on("postgres_changes",{event:"*",schema:"public",table:"comanda_orders",filter:`account_id=eq.${account.id}`},()=>refreshOps())
      .on("postgres_changes",{event:"*",schema:"public",table:"comanda_order_items",filter:`account_id=eq.${account.id}`},payload=>{if(payload.eventType==="INSERT"||payload.new?.kitchen_status==="pending")beep();refreshOps()})
      .subscribe();channelRef.current=ch;return()=>ch.unsubscribe();
  },[account?.id]);
  function beep(){try{const C=window.AudioContext||window.webkitAudioContext;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=880;g.gain.value=.08;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.16)}catch{}}

  const branch=branches.find(b=>b.id===branchId);const branchSectors=sectors.filter(s=>s.branch_id===branchId);const branchTables=tables.filter(t=>t.branch_id===branchId);const openOrders=orders.filter(o=>o.branch_id===branchId&&o.status==="open");
  const selectedOrder=orders.find(o=>o.id===selectedOrderId)||null;const selectedItems=items.filter(i=>i.order_id===selectedOrderId&&i.kitchen_status!=="cancelled");const selectedPayments=payments.filter(p=>p.order_id===selectedOrderId);
  const orderTotal=selectedItems.reduce((a,i)=>a+Number(i.quantity)*Number(i.unit_price),0),paidTotal=selectedPayments.reduce((a,p)=>a+Number(p.amount),0),balance=Math.max(0,orderTotal-paidTotal);
  const openCash=cashSessions.find(s=>s.status==="open"&&registers.some(r=>r.id===s.register_id&&r.branch_id===branchId));
  const trialDays=account?Math.max(0,Math.ceil((new Date(account.trial_ends_at)-new Date())/86400000)):0;

  async function audit(action,entity_type,entity_id,detail={}){if(!account||!user)return;await supabase.from("comanda_audit_logs").insert({account_id:account.id,branch_id:branchId||null,user_id:user.id,staff_id:activeStaffId||null,action,entity_type,entity_id,detail})}
  async function openTable(table){if(!canSell){flash("Este funcionario no tiene permiso para abrir mesas.",true);return}const waiters=staff.filter(s=>s.branch_id===branchId&&(s.staff_type==="waiter"||s.staff_type==="admin"));setModal({type:"openTable",table,diners:table.seats||2,waiterId:(activeStaff?.staff_type==="waiter"?activeStaffId:waiters[0]?.id)||"",label:""})}
  async function confirmOpenTable(){const m=modal;if(!m?.waiterId){flash("Seleccioná un mozo.",true);return}const {data,error}=await supabase.from("comanda_orders").insert({account_id:account.id,branch_id:branchId,table_id:m.table.id,waiter_id:m.waiterId,opened_by:user.id,diners:Number(m.diners)||1,label:m.label||null}).select().single();if(error){flash(error.message,true);return}await audit("table_opened","order",data.id,{table:m.table.number,diners:m.diners});setModal(null);setSelectedOrderId(data.id);setView("order");await refreshOps()}
  function selectTable(table){const o=openOrders.find(x=>x.table_id===table.id);if(o){setSelectedOrderId(o.id);setView("order")}else openTable(table)}
  async function addProduct(product){if(!selectedOrder||!canSell){flash("No podés agregar productos en este puesto.",true);return}const {error}=await supabase.from("comanda_order_items").insert({account_id:account.id,order_id:selectedOrder.id,product_id:product.id,product_name:product.name,quantity:1,unit_price:product.price,destination:product.destination,kitchen_status:"draft",created_by:user.id});if(error){flash(error.message,true);return}await audit("item_added","order",selectedOrder.id,{product:product.name});await refreshOps()}
  async function removeItem(item){if(item.kitchen_status!=="draft"&&!isAdmin){flash("Solo administración puede anular un producto ya enviado.",true);return}if(item.kitchen_status==="draft"){await supabase.from("comanda_order_items").delete().eq("id",item.id);await audit("item_removed","order_item",item.id,{product:item.product_name})}else{const reason=window.prompt("Motivo obligatorio de anulación:");if(!reason?.trim())return;await supabase.from("comanda_order_items").update({kitchen_status:"cancelled",cancelled_at:nowIso(),cancellation_reason:reason.trim()}).eq("id",item.id);await audit("item_cancelled","order_item",item.id,{product:item.product_name,reason:reason.trim()})}await refreshOps()}
  async function sendKitchen(){const drafts=selectedItems.filter(i=>i.kitchen_status==="draft");if(!drafts.length){flash("No hay productos nuevos para enviar.");return}const idsKitchen=drafts.filter(i=>i.destination!=="none").map(i=>i.id),idsNone=drafts.filter(i=>i.destination==="none").map(i=>i.id);if(idsKitchen.length)await supabase.from("comanda_order_items").update({kitchen_status:"pending",sent_at:nowIso(),updated_at:nowIso()}).in("id",idsKitchen);if(idsNone.length)await supabase.from("comanda_order_items").update({kitchen_status:"delivered",sent_at:nowIso(),updated_at:nowIso()}).in("id",idsNone);await audit("kitchen_sent","order",selectedOrder.id,{items:drafts.length});flash("Comanda enviada a cocina.");await refreshOps()}
  async function kitchenNext(item){if(!canKitchen){flash("Este funcionario no opera cocina.",true);return}const next={pending:"preparing",preparing:"ready",ready:"delivered"}[item.kitchen_status];if(!next)return;await supabase.from("comanda_order_items").update({kitchen_status:next,prepared_at:next==="ready"?nowIso():item.prepared_at,updated_at:nowIso()}).eq("id",item.id);await audit(`kitchen_${next}`,"order_item",item.id,{product:item.product_name});await refreshOps()}
  function printTicket(){window.print()}
  function addPayment(){if(!canCash){flash("Solo caja o administración pueden cobrar.",true);return}if(!openCash){flash("Primero tenés que abrir una caja.",true);setView("caja");return}setModal({type:"payment",method:"cash",amount:balance,received:balance})}
  async function confirmPayment(){const m=modal,amount=Number(m.amount),received=Number(m.received||amount);if(!amount||amount<=0){flash("Ingresá un importe válido.",true);return}const change=m.method==="cash"?Math.max(0,received-amount):0;const {error}=await supabase.from("comanda_payments").insert({account_id:account.id,order_id:selectedOrder.id,cash_session_id:openCash.id,staff_id:activeStaffId||null,method:m.method,amount,received_amount:received,change_amount:change,created_by:user.id});if(error){flash(error.message,true);return}await audit("payment_added","order",selectedOrder.id,{method:m.method,amount});setModal(null);flash(`Pago registrado${change?` · Vuelto ${money(change)}`:""}`);await refreshOps()}
  async function closeOrder(){if(!canCash&&!isAdmin){flash("Este funcionario no puede cerrar la mesa.",true);return}if(balance>.01){flash("No se puede cerrar la mesa: todavía hay saldo pendiente.",true);return}if(selectedItems.some(i=>i.kitchen_status==="draft")){flash("Hay productos sin confirmar. Enviá o anulá los cambios antes de cerrar.",true);return}await supabase.from("comanda_orders").update({status:"closed",closed_at:nowIso(),updated_at:nowIso()}).eq("id",selectedOrder.id);await audit("order_closed","order",selectedOrder.id,{total:orderTotal});setSelectedOrderId("");setView("salon");flash("Mesa cerrada correctamente.");await refreshOps()}
  async function cancelOrder(){if(!isAdmin){flash("Solo administración puede anular una venta.",true);return}const reason=window.prompt("Motivo obligatorio de anulación:");if(!reason?.trim())return;await supabase.from("comanda_orders").update({status:"cancelled",cancellation_reason:reason.trim(),closed_at:nowIso(),updated_at:nowIso()}).eq("id",selectedOrder.id);await supabase.from("comanda_order_items").update({kitchen_status:"cancelled",cancelled_at:nowIso(),cancellation_reason:reason.trim()}).eq("order_id",selectedOrder.id).neq("kitchen_status","cancelled");await audit("order_cancelled","order",selectedOrder.id,{reason:reason.trim()});setSelectedOrderId("");setView("salon");flash("Venta anulada.");await refreshOps()}
  async function openCashSession(){if(!canCash){flash("Este funcionario no puede abrir caja.",true);return}const register=registers.find(r=>r.branch_id===branchId);if(!register){flash("No hay caja configurada.",true);return}const amount=Number(window.prompt("Monto inicial de caja:","0"));if(Number.isNaN(amount))return;const {error}=await supabase.from("comanda_cash_sessions").insert({account_id:account.id,register_id:register.id,staff_id:activeStaffId||null,opened_by:user.id,opening_amount:amount});if(error){flash(error.message,true);return}await audit("cash_opened","cash_register",register.id,{opening_amount:amount});flash("Caja abierta.");await refreshOps()}
  async function closeCashSession(){if(!openCash)return;const amount=Number(window.prompt("Monto contado al cierre:","0"));if(Number.isNaN(amount))return;await supabase.from("comanda_cash_sessions").update({status:"closed",closed_by:user.id,closed_at:nowIso(),closing_amount:amount}).eq("id",openCash.id);await audit("cash_closed","cash_session",openCash.id,{closing_amount:amount});flash("Caja cerrada.");await refreshOps()}
  async function addMovement(type){if(!openCash){flash("No hay caja abierta.",true);return}const amount=Number(window.prompt(type==="income"?"Importe del ingreso":"Importe del egreso"));if(!amount||amount<=0)return;const reason=window.prompt("Motivo:");if(!reason?.trim())return;await supabase.from("comanda_cash_movements").insert({account_id:account.id,cash_session_id:openCash.id,staff_id:activeStaffId||null,movement_type:type,amount,reason:reason.trim(),created_by:user.id});await audit("cash_movement","cash_session",openCash.id,{type,amount,reason});await refreshOps()}
  async function addSector(){if(!isAdmin){flash("Solo administración puede configurar sectores.",true);return}const name=window.prompt("Nombre del nuevo sector:");if(!name?.trim())return;const max=Math.max(0,...sectors.map(s=>s.sort_order||0));const {data,error}=await supabase.from("comanda_sectors").insert({account_id:account.id,branch_id:branchId,name:name.trim(),sort_order:max+1}).select().single();if(error){flash(error.message,true);return}setSectorId(data.id);await refreshOps()}
  async function addTable(){if(!isAdmin)return;const sec=sectorId||branchSectors[0]?.id;if(!sec){flash("Primero creá un sector.",true);return}const number=window.prompt("Número de mesa:");if(!number?.trim())return;const seats=Number(window.prompt("Cantidad de comensales:","4"))||4;const used=tables.filter(t=>t.sector_id===sec);const pos=used.length;const {error}=await supabase.from("comanda_tables").insert({account_id:account.id,branch_id:branchId,sector_id:sec,number:number.trim(),seats,pos_x:pos%6,pos_y:Math.floor(pos/6)});if(error)flash(error.message,true);else await refreshOps()}
  async function moveTable(table,x,y){if(!isAdmin)return;await supabase.from("comanda_tables").update({pos_x:x,pos_y:y}).eq("id",table.id);setTables(v=>v.map(t=>t.id===table.id?{...t,pos_x:x,pos_y:y}:t))}
  async function addCategory(){if(!isAdmin)return;const name=window.prompt("Nombre de categoría:");if(!name?.trim())return;const {error}=await supabase.from("comanda_categories").insert({account_id:account.id,branch_id:branchId,name:name.trim(),sort_order:categories.length+1});if(error)flash(error.message,true);else await refreshOps()}
  async function addNewProduct(){if(!isAdmin)return;const cat=categoryId||categories[0]?.id;if(!cat)return;const name=window.prompt("Nombre del producto:");if(!name?.trim())return;const price=Number(window.prompt("Precio:","0"));if(Number.isNaN(price))return;const destination=window.prompt("Destino: kitchen, bar o none","kitchen")||"kitchen";const {error}=await supabase.from("comanda_products").insert({account_id:account.id,category_id:cat,name:name.trim(),price,destination:destination==="bar"?"bar":destination==="none"?"none":"kitchen",sort_order:products.length+1});if(error)flash(error.message,true);else await refreshOps()}
  async function addStaff(){if(!isAdmin)return;const name=window.prompt("Nombre del funcionario:");if(!name?.trim())return;const type=window.prompt("Tipo: waiter, cashier, cook, admin","waiter")||"waiter";const allowed=["waiter","cashier","cook","admin","bar","other"].includes(type)?type:"other";const {error}=await supabase.from("comanda_staff").insert({account_id:account.id,branch_id:branchId,name:name.trim(),staff_type:allowed});if(error)flash(error.message,true);else await refreshOps()}
  async function logout(){await supabase.auth.signOut();window.location.href="/comanda/login"}

  if(loading)return <main className={styles.page} style={{display:"grid",placeItems:"center"}}>Cargando Comanda Llena...</main>;
  if(!account)return null;

  const nav=[
    ["salon","🪑","Salón",true],["cocina","🍳","Cocina",canKitchen],["caja","💵","Caja",canCash||isAdmin],["carta","📋","Carta",true],["equipo","👥","Equipo",isAdmin],["mesas","🧩","Mesas",isAdmin],["ayuda","❔","Ayuda",true]
  ];
  const filteredProducts=products.filter(p=>!categoryId||p.category_id===categoryId);

  return <main className={`${styles.page} ${styles.app}`}>
    <header className={styles.topbar}><div className={styles.topBrand}><span className={styles.brandMark} style={{width:30,height:30,borderRadius:8}}>C</span>Comanda Llena</div><div className={styles.topNav}>{nav.filter(n=>n[3]).slice(0,5).map(([id,icon,label])=><button key={id} onClick={()=>{setView(id);if(id!=="order")setSelectedOrderId("")}} className={view===id?styles.activeNav:""}>{icon} {label}</button>)}</div><div className={styles.topRight}><span className={styles.trialPill}>{trialDays}d prueba</span><select className={styles.compactSelect} value={branchId} onChange={e=>{setBranchId(e.target.value);const s=sectors.find(x=>x.branch_id===e.target.value);if(s)setSectorId(s.id)}}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select className={styles.compactSelect} value={activeStaffId} onChange={e=>setActiveStaffId(e.target.value)}>{staff.filter(s=>!branchId||s.branch_id===branchId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div></header>
    <div className={styles.workspace}>
      <aside className={styles.sidebar}><div className={styles.sidebarTitle}>Operación</div>{nav.filter(n=>n[3]).map(([id,icon,label])=><button key={id} onClick={()=>{setView(id);if(id!=="order")setSelectedOrderId("")}} className={view===id?styles.sideActive:""}>{icon} {label}</button>)}<div className={styles.sidebarTitle}>Cuenta</div><button onClick={()=>window.location.href="/comanda/onboarding"}>🚀 Onboarding</button><button onClick={logout}>↪ Salir</button></aside>
      <section className={styles.content}>
        {view==="salon"&&<><Header title="Salón" subtitle={`${branch?.name||"Sucursal"} · ${openOrders.length} mesa${openOrders.length===1?"":"s"} abierta${openOrders.length===1?"":"s"}`} right={<span className={styles.trialPill}>{openCash?"Caja activa":"Caja cerrada"}</span>}/><div className={styles.sectorTabs}>{branchSectors.map(s=><button className={sectorId===s.id?styles.tabActive:""} key={s.id} onClick={()=>setSectorId(s.id)}>{s.name} · {branchTables.filter(t=>t.sector_id===s.id).length}</button>)}</div><div className={styles.tableGrid}>{branchTables.filter(t=>t.sector_id===sectorId).map(t=>{const o=openOrders.find(x=>x.table_id===t.id),oi=o?items.filter(i=>i.order_id===o.id&&i.kitchen_status!=="cancelled"):[],ready=oi.length&&oi.every(i=>["ready","delivered"].includes(i.kitchen_status));const waiter=staff.find(s=>s.id===o?.waiter_id);return <button key={t.id} className={`${styles.tableCard} ${o?(ready?styles.tableReady:styles.tableBusy):styles.tableFree}`} onClick={()=>selectTable(t)}><span className={styles.tableNumber}>{t.number}</span><span className={styles.tableMeta}>👥 {o?.diners||t.seats}</span>{o&&<span className={styles.waiterTag}>{waiter?.name||"Abierta"}</span>}</button>})}</div></>}
        {view==="order"&&selectedOrder&&<OrderView order={selectedOrder} table={tables.find(t=>t.id===selectedOrder.table_id)} waiter={staff.find(s=>s.id===selectedOrder.waiter_id)} items={selectedItems} payments={selectedPayments} total={orderTotal} paid={paidTotal} balance={balance} categories={categories} categoryId={categoryId} setCategoryId={setCategoryId} products={filteredProducts} addProduct={addProduct} removeItem={removeItem} sendKitchen={sendKitchen} addPayment={addPayment} closeOrder={closeOrder} cancelOrder={cancelOrder} printTicket={printTicket} back={()=>{setView("salon");setSelectedOrderId("")}}/>}
        {view==="cocina"&&<Kitchen orders={openOrders} items={items.filter(i=>i.destination!=="none"&&["pending","preparing","ready"].includes(i.kitchen_status))} tables={tables} staff={staff} next={kitchenNext}/>} 
        {view==="caja"&&<CashView openCash={openCash} register={registers.find(r=>r.id===openCash?.register_id)||registers.find(r=>r.branch_id===branchId)} payments={payments} movements={movements.filter(m=>m.cash_session_id===openCash?.id)} open={openCashSession} close={closeCashSession} move={addMovement}/>} 
        {view==="carta"&&<MenuView categories={categories} categoryId={categoryId} setCategoryId={setCategoryId} products={filteredProducts} addCategory={addCategory} addProduct={addNewProduct} isAdmin={isAdmin}/>} 
        {view==="equipo"&&<StaffView staff={staff.filter(s=>s.branch_id===branchId)} add={addStaff}/>} 
        {view==="mesas"&&<TableEditor sectors={branchSectors} sectorId={sectorId} setSectorId={setSectorId} tables={branchTables.filter(t=>t.sector_id===sectorId)} addSector={addSector} addTable={addTable} move={moveTable}/>} 
        {view==="ayuda"&&<Help/>}
      </section>
    </div>
    {modal?.type==="openTable"&&<OpenTableModal modal={modal} setModal={setModal} waiters={staff.filter(s=>s.branch_id===branchId&&(s.staff_type==="waiter"||s.staff_type==="admin"))} confirm={confirmOpenTable}/>} 
    {modal?.type==="payment"&&<PaymentModal modal={modal} setModal={setModal} balance={balance} confirm={confirmPayment}/>} 
    {toast&&<div className={`${styles.toast} ${toast.error?styles.toastError:""}`}>{toast.message}</div>}
  </main>
}

function Header({title,subtitle,right}){return <div className={styles.contentHeader}><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{right}</div>}
function OrderView(p){return <><Header title={`Mesa ${p.table?.number||""}`} subtitle={`${p.waiter?.name||"Sin mozo"} · ${p.order.diners} comensales`} right={<button className={styles.ghost} onClick={p.back}>← Volver al salón</button>}/><div className={styles.orderLayout}><div className={styles.orderPane}><div className={styles.paneHeader}><b>Detalle</b><span>{p.items.length} ítems</span></div><div className={styles.paneBody}>{p.items.length?p.items.map(i=><div className={styles.orderItem} key={i.id}><b>{i.quantity}</b><div><div className={styles.itemName}>{i.product_name}</div><span className={styles.itemState}>{i.kitchen_status}</span></div><b>{money(Number(i.quantity)*Number(i.unit_price))}</b><button className={styles.danger} style={{padding:6}} onClick={()=>p.removeItem(i)}>×</button></div>):<div className={styles.empty}>Todavía no agregaste productos.</div>}</div><div className={styles.totals}><div>Pagado<br/><b>{money(p.paid)}</b></div><div className={styles.totalBig}>{money(p.total)}</div><div>Saldo</div><div className={styles.totalBig} style={{color:p.balance?"#b34b40":"#08785e"}}>{money(p.balance)}</div></div></div><div className={styles.orderPane}><div className={styles.categoryStrip}><button className={!p.categoryId?styles.catActive:""} onClick={()=>p.setCategoryId("")}>Todos</button>{p.categories.map(c=><button key={c.id} className={p.categoryId===c.id?styles.catActive:""} onClick={()=>p.setCategoryId(c.id)}>{c.name}</button>)}</div><div className={styles.productGrid}>{p.products.map(pr=><button className={styles.product} key={pr.id} onClick={()=>p.addProduct(pr)}><span className={styles.productPrice}>{money(pr.price)}</span><span className={styles.productName}>{pr.name}</span><small>{pr.destination==="bar"?"Bar":pr.destination==="kitchen"?"Cocina":"Directo"}</small></button>)}</div></div><div className={styles.orderPane}><div className={styles.paneHeader}><b>Acciones</b></div><div className={styles.actions}><button className={styles.primary} onClick={p.sendKitchen}>✓ Enviar cambios</button><button className={styles.secondary} onClick={p.printTicket}>🖨 Imprimir cuenta</button><button className={styles.secondary} onClick={p.addPayment}>＋ Agregar pago</button><button className={styles.darkButton} onClick={p.closeOrder}>Cerrar mesa</button><button className={styles.danger} onClick={p.cancelOrder}>Anular venta</button></div></div></div></>}
function Kitchen({orders,items,tables,staff,next}){const groups=orders.map(o=>({...o,kitems:items.filter(i=>i.order_id===o.id)})).filter(o=>o.kitems.length);return <><Header title="Monitor de cocina" subtitle="Las comandas aparecen en tiempo real y generan un aviso sonoro."/><div className={styles.kitchenGrid}>{groups.length?groups.map(o=><article className={styles.ticket} key={o.id}><div className={styles.ticketHead}><div><b>Mesa {tables.find(t=>t.id===o.table_id)?.number||"-"}</b><br/><small>{staff.find(s=>s.id===o.waiter_id)?.name||"Sin mozo"}</small></div><span>{o.diners} 👥</span></div><div className={styles.ticketItems}>{o.kitems.map(i=><div className={styles.kitchenItem} key={i.id}><div><b>{i.quantity} × {i.product_name}</b>{i.notes&&<small style={{display:"block"}}>{i.notes}</small>}</div><div style={{display:"flex",gap:6,alignItems:"center"}}><span className={`${styles.statusBadge} ${i.kitchen_status==="pending"?styles.statusPending:i.kitchen_status==="preparing"?styles.statusPreparing:styles.statusReady}`}>{i.kitchen_status==="pending"?"Pendiente":i.kitchen_status==="preparing"?"Preparando":"Listo"}</span><button className={styles.kitchenButton} onClick={()=>next(i)}>→</button></div></div>)}</div></article>):<div className={styles.card}><div className={styles.empty}>No hay comandas pendientes.</div></div>}</div></>}
function CashView({openCash,register,payments,movements,open,close,move}){const paid=openCash?payments.filter(p=>p.cash_session_id===openCash.id).reduce((a,p)=>a+Number(p.amount),0):0,inc=movements.filter(m=>m.movement_type==="income").reduce((a,m)=>a+Number(m.amount),0),exp=movements.filter(m=>m.movement_type==="expense").reduce((a,m)=>a+Number(m.amount),0);return <><Header title="Caja" subtitle={register?.name||"Caja principal"} right={openCash?<button className={styles.danger} onClick={close}>Cerrar caja</button>:<button className={styles.primary} onClick={open}>Abrir caja</button>}/><div className={styles.statGrid}><div className={styles.stat}><span>Inicio</span><strong>{money(openCash?.opening_amount)}</strong></div><div className={styles.stat}><span>Pagos</span><strong>{money(paid)}</strong></div><div className={styles.stat}><span>Movimientos</span><strong>{money(inc-exp)}</strong></div><div className={styles.stat}><span>Teórico</span><strong>{money(Number(openCash?.opening_amount||0)+paid+inc-exp)}</strong></div></div><div className={styles.twoCols}><div className={styles.card} style={{padding:18}}><h3>Movimientos de caja</h3><div style={{display:"flex",gap:8,marginBottom:12}}><button className={styles.secondary} onClick={()=>move("income")}>＋ Ingreso</button><button className={styles.ghost} onClick={()=>move("expense")}>− Egreso</button><button className={styles.ghost} onClick={()=>window.print()}>🖨 Control de caja</button></div>{movements.length?movements.map(m=><div key={m.id} className={styles.listRow}><b>{m.reason}</b><span>{m.movement_type==="income"?"Ingreso":"Egreso"}</span><b>{money(m.amount)}</b><small>{new Date(m.created_at).toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})}</small></div>):<div className={styles.empty}>Sin movimientos.</div>}</div><div className={styles.card} style={{padding:18}}><h3>Estado</h3>{openCash?<><p><b>Caja abierta</b> desde {new Date(openCash.opened_at).toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})}</p><p className={styles.muted}>No se puede cobrar sin una caja activa. El cierre conserva monto contado, usuario y horario.</p></>:<div className={styles.empty}>Abrí una caja para empezar a cobrar.</div>}</div></div></>}
function MenuView({categories,categoryId,setCategoryId,products,addCategory,addProduct,isAdmin}){return <><Header title="Carta" subtitle="Categorías y productos" right={isAdmin?<div style={{display:"flex",gap:8}}><button className={styles.ghost} onClick={addCategory}>＋ Categoría</button><button className={styles.primary} onClick={addProduct}>＋ Producto</button></div>:null}/><div className={styles.sectorTabs}>{categories.map(c=><button key={c.id} className={categoryId===c.id?styles.tabActive:""} onClick={()=>setCategoryId(c.id)}>{c.name}</button>)}</div><div className={styles.productGrid}>{products.map(p=><article className={styles.product} key={p.id}><span className={styles.productPrice}>{money(p.price)}</span><span className={styles.productName}>{p.name}</span><small>Destino: {p.destination}</small></article>)}</div></>}
function StaffView({staff,add}){const names={waiter:"Mozo",cashier:"Cajero",cook:"Cocinero",admin:"Administrador",bar:"Bar",other:"Otro"};return <><Header title="Funcionarios" subtitle="La persona que ejecuta cada acción queda asociada a la auditoría." right={<button className={styles.primary} onClick={add}>＋ Funcionario</button>}/><div className={styles.list}>{staff.map(s=><div key={s.id} className={styles.listRow}><b>{s.name}</b><span>{names[s.staff_type]||s.staff_type}</span><small>{s.email||"Sin email"}</small><span className={styles.statusBadge+" "+styles.statusReady}>Activo</span></div>)}</div></>}
function TableEditor({sectors,sectorId,setSectorId,tables,addSector,addTable,move}){const cells=Array.from({length:24},(_,i)=>({x:i%6,y:Math.floor(i/6)}));return <><Header title="Sectores y mesas" subtitle="Arrastrá una mesa a otra celda para cambiar su posición." right={<div style={{display:"flex",gap:8}}><button className={styles.ghost} onClick={addSector}>＋ Sector</button><button className={styles.primary} onClick={addTable}>＋ Mesa</button></div>}/><div className={styles.sectorTabs}>{sectors.map(s=><button key={s.id} className={sectorId===s.id?styles.tabActive:""} onClick={()=>setSectorId(s.id)}>{s.name}</button>)}</div><div className={styles.editorGrid}>{cells.map(c=>{const t=tables.find(t=>t.pos_x===c.x&&t.pos_y===c.y);return <div key={`${c.x}-${c.y}`} className={styles.editorCell} onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData("text/table-id");const tb=tables.find(x=>x.id===id);if(tb)move(tb,c.x,c.y)}}>{t&&<div className={styles.editorTable} draggable onDragStart={e=>e.dataTransfer.setData("text/table-id",t.id)}>Mesa {t.number}<small>👥 {t.seats}</small></div>}</div>})}</div></>}
function Help(){return <><Header title="Ayuda y soporte" subtitle="Primeros pasos y asistencia técnica"/><div className={styles.helpGrid}><div className={styles.helpCard}><h3>1. Abrí caja</h3><p>Elegí un cajero o administrador y abrí la caja con el monto inicial.</p></div><div className={styles.helpCard}><h3>2. Abrí una mesa</h3><p>Desde Salón seleccioná mesa, comensales y mozo. Después cargá los productos.</p></div><div className={styles.helpCard}><h3>3. Enviá a cocina</h3><p>Los productos aparecen automáticamente en la PC de cocina y suena un aviso.</p></div><div className={styles.helpCard}><h3>4. Cobrá</h3><p>Agregá el pago. Comanda Llena bloquea el cierre mientras exista saldo pendiente.</p></div><div className={styles.helpCard}><h3>5. Configurá</h3><p>Administración puede crear funcionarios, sectores, mesas, categorías y productos.</p></div><div className={styles.helpCard}><h3>Atajos próximos</h3><p>La interfaz es desktop-first y vamos a sumar atajos de teclado para acelerar la operación.</p></div></div><div className={styles.supportBox}><div><b>¿Necesitás que te ayudemos a configurarlo?</b><div style={{color:"#b9cec7",marginTop:5}}>Soporte técnico para puesta en marcha y resolución de problemas.</div></div><a className={styles.primary} href="https://wa.me/5491159609135?text=Hola%2C%20necesito%20soporte%20con%20Comanda%20Llena" target="_blank" rel="noreferrer">Abrir soporte</a></div></>}
function OpenTableModal({modal,setModal,waiters,confirm}){return <div className={styles.modalBackdrop}><div className={styles.modal}><div className={styles.modalHead}><h2>Abrir mesa {modal.table.number}</h2><button className={styles.ghost} onClick={()=>setModal(null)}>×</button></div><div className={styles.modalBody}><div className={styles.form}><label className={styles.label}>Comensales<input type="number" min="1" className={styles.input} value={modal.diners} onChange={e=>setModal({...modal,diners:e.target.value})}/></label><label className={styles.label}>Mozo<select className={styles.select} value={modal.waiterId} onChange={e=>setModal({...modal,waiterId:e.target.value})}>{waiters.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className={styles.label}>Etiqueta opcional<input className={styles.input} value={modal.label} onChange={e=>setModal({...modal,label:e.target.value})} placeholder="Reserva, evento, huésped..."/></label></div></div><div className={styles.modalActions}><button className={styles.ghost} onClick={()=>setModal(null)}>Cancelar</button><button className={styles.primary} onClick={confirm}>Abrir mesa</button></div></div></div>}
function PaymentModal({modal,setModal,balance,confirm}){const change=modal.method==="cash"?Math.max(0,Number(modal.received||0)-Number(modal.amount||0)):0;return <div className={styles.modalBackdrop}><div className={styles.modal}><div className={styles.modalHead}><h2>Agregar pago</h2><button className={styles.ghost} onClick={()=>setModal(null)}>×</button></div><div className={styles.modalBody}><div className={styles.statGrid} style={{gridTemplateColumns:"repeat(3,1fr)"}}><div className={styles.stat}><span>Saldo</span><strong>{money(balance)}</strong></div><div className={styles.stat}><span>A pagar</span><strong>{money(modal.amount)}</strong></div><div className={styles.stat}><span>Vuelto</span><strong>{money(change)}</strong></div></div><div className={styles.form}><label className={styles.label}>Medio de pago<select className={styles.select} value={modal.method} onChange={e=>setModal({...modal,method:e.target.value})}><option value="cash">Efectivo</option><option value="pos">POS / Tarjeta</option><option value="transfer">Transferencia</option><option value="room_charge">Cargar a habitación (preparado)</option><option value="other">Otro</option></select></label><label className={styles.label}>Importe<input className={styles.input} type="number" value={modal.amount} onChange={e=>setModal({...modal,amount:e.target.value})}/></label>{modal.method==="cash"&&<label className={styles.label}>Entrega<input className={styles.input} type="number" value={modal.received} onChange={e=>setModal({...modal,received:e.target.value})}/></label>}</div></div><div className={styles.modalActions}><button className={styles.ghost} onClick={()=>setModal(null)}>Cancelar</button><button className={styles.primary} onClick={confirm}>Confirmar pago</button></div></div></div>}
