"use client";

import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../../lib/supabase";
import ComandaArt from "./ComandaArt";
import s from "../styles/comanda-sales-terminal.module.css";

const money=n=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(Number(n||0));
const METHODS=[["cash","Efectivo"],["debit","Débito"],["credit","Crédito"],["mercadopago","Mercado Pago"],["transfer","Transferencia"],["account","Cuenta corriente"],["room_charge","Habitación"],["other","Otro"]];
function Modal({title,onClose,children,wide=false}){return <div className={s.overlay} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={`${s.modal} ${wide?s.wide:""}`}><header><h2>{title}</h2><button onClick={onClose}>×</button></header>{children}</section></div>}

export default function ComandaSalesTerminal(){
 const [role,setRole]=useState(null),[permissions,setPermissions]=useState({}),[branch,setBranch]=useState(null),[user,setUser]=useState(null),[sectors,setSectors]=useState([]),[tables,setTables]=useState([]),[staff,setStaff]=useState([]),[categories,setCategories]=useState([]),[products,setProducts]=useState([]),[kitchens,setKitchens]=useState([]),[orders,setOrders]=useState([]),[items,setItems]=useState([]),[sectorId,setSectorId]=useState(null),[modal,setModal]=useState(null),[categoryId,setCategoryId]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const branchId=typeof window!=="undefined"?sessionStorage.getItem("comanda_branch"):null, workstationId=typeof window!=="undefined"?sessionStorage.getItem("comanda_workstation"):null;
 const canOperate=permissions.all||permissions.sale_restaurant||permissions.tables_operate||permissions.open_tables;
 async function load(){if(!branchId||!workstationId)return;const {data:{user:u}}=await supabase.auth.getUser();setUser(u);const [{data:ws},{data:b},{data:ss},{data:tt},{data:ff},{data:cc},{data:pp},{data:kk},{data:oo}]=await Promise.all([supabase.from("comanda_workstations").select("kind,permissions,name").eq("id",workstationId).maybeSingle(),supabase.from("comanda_branches").select("id,account_id,name").eq("id",branchId).maybeSingle(),supabase.from("comanda_sectors").select("*").eq("branch_id",branchId).eq("active",true).order("sort_order"),supabase.from("comanda_tables").select("*").eq("branch_id",branchId).eq("active",true).order("created_at"),supabase.from("comanda_staff").select("id,name,staff_type,active").eq("branch_id",branchId).eq("active",true).in("staff_type",["waiter","manager","supervisor"]),supabase.from("comanda_categories").select("*").eq("branch_id",branchId).eq("active",true).order("sort_order"),supabase.from("comanda_products").select("*").eq("branch_id",branchId).eq("active",true).order("sort_order"),supabase.from("comanda_kitchens").select("id,name,active").eq("branch_id",branchId).eq("active",true),supabase.from("comanda_orders").select("*").eq("branch_id",branchId).eq("status","open").order("opened_at")]);setRole(ws?.kind||null);setPermissions(ws?.permissions||{});setBranch(b||null);setSectors(ss||[]);setTables(tt||[]);setStaff(ff||[]);setCategories(cc||[]);setProducts(pp||[]);setKitchens(kk||[]);setOrders(oo||[]);setSectorId(x=>(ss||[]).some(a=>a.id===x)?x:ss?.[0]?.id||null);const ids=(oo||[]).map(o=>o.id);if(ids.length){const {data:ii}=await supabase.from("comanda_order_items").select("*").in("order_id",ids).order("created_at");setItems(ii||[])}else setItems([])}
 useEffect(()=>{load();if(!branchId)return;const ch=supabase.channel(`sales-terminal-${branchId}`).on("postgres_changes",{event:"*",schema:"public",table:"comanda_orders",filter:`branch_id=eq.${branchId}`},load).on("postgres_changes",{event:"*",schema:"public",table:"comanda_order_items"},load).subscribe();return()=>supabase.removeChannel(ch)},[branchId,workstationId]);
 const visible=role&&["waiter","waiter_app","cashier","principal"].includes(role)&&canOperate;
 useEffect(()=>{if(!visible)return;const legacy=[...document.querySelectorAll("h1,h2,h3")].find(x=>/venta|salón/i.test(x.textContent||"")&&!x.closest('[data-sales-terminal="1"]'));const root=legacy?.closest('[class*="workspace"]')||legacy?.parentElement?.parentElement;if(root)root.style.display="none";return()=>{if(root)root.style.display=""}},[visible]);
 const activeTables=useMemo(()=>tables.filter(t=>t.sector_id===sectorId),[tables,sectorId]);const orderForTable=id=>orders.find(o=>o.table_id===id);const itemsFor=id=>items.filter(i=>i.order_id===id&&i.kitchen_status!=="cancelled");const totalFor=id=>itemsFor(id).reduce((a,i)=>a+Number(i.quantity)*Number(i.unit_price),0);
 async function openTable(table,form){if(!branch||!user)return;setBusy(true);const {data,error}=await supabase.from("comanda_orders").insert({account_id:branch.account_id,branch_id:branch.id,table_id:table.id,waiter_id:form.waiter_id||null,opened_by:user.id,diners:Number(form.diners||1),label:form.label||null,status:"open",workstation_id:workstationId,sale_type:"restaurant",room_service_charge:0,discount_amount:0}).select().single();setBusy(false);if(error)return setNotice(error.message);await audit("table_open","order",data.id,null,{table:table.number,diners:form.diners});setModal({type:"order",order:data,table});await load()}
 async function addProduct(order,p){if(!branch||!user)return;const kitchen=kitchens.find(k=>k.id===p.kitchen_id);const destination=!p.kitchen_id?"none":/bar/i.test(kitchen?.name||"")?"bar":"kitchen";const unit=Number(p.restaurant_price??p.price??0);const {error}=await supabase.from("comanda_order_items").insert({account_id:branch.account_id,order_id:order.id,product_id:p.id,product_name:p.public_name||p.name,quantity:1,unit_price:unit,destination,kitchen_status:"draft",created_by:user.id,kitchen_id:p.kitchen_id||null,options:[],special_flags:{celiac:/cel[ií]ac/i.test(p.name||"")}});if(error)return setNotice(error.message);await load()}
 async function changeQty(item,delta){const q=Number(item.quantity)+delta;if(q<=0)return setModal({type:"voidItem",item});await supabase.from("comanda_order_items").update({quantity:q,updated_at:new Date().toISOString()}).eq("id",item.id);await load()}
 async function voidItem(item,reason){if(!reason.trim())return;await supabase.from("comanda_order_items").update({kitchen_status:"cancelled",cancelled_at:new Date().toISOString(),cancellation_reason:reason.trim(),updated_at:new Date().toISOString()}).eq("id",item.id);await audit("item_void","order_item",item.id,reason,{product:item.product_name});setModal(null);await load()}
 async function sendKitchen(order){const draft=items.filter(i=>i.order_id===order.id&&i.kitchen_status==="draft");if(!draft.length)return setNotice("No hay productos nuevos para enviar.");const now=new Date().toISOString();const {error}=await supabase.from("comanda_order_items").update({kitchen_status:"pending",sent_at:now,updated_at:now}).in("id",draft.map(i=>i.id));if(error)return setNotice(error.message);await queuePrint("send_kitchen",order.id);await audit("send_kitchen","order",order.id,null,{items:draft.length});setNotice("Comanda enviada a cocina");await load()}
 async function queuePrint(trigger,orderId=null,cashSessionId=null){if(!branch)return;const {data:templates}=await supabase.from("comanda_ticket_templates").select("*").eq("branch_id",branch.id).eq("active",true);for(const t of templates||[]){const tr=Array.isArray(t.triggers)?t.triggers:[];const match=tr.some(x=>(typeof x==="string"?x:x?.event||x?.trigger)===trigger);if(!match)continue;const copies=Math.max(1,Number(t.copies||1));for(let n=0;n<copies;n++)await supabase.from("comanda_print_jobs").insert({account_id:branch.account_id,branch_id:branch.id,printer_id:t.printer_id||null,template_id:t.id,order_id:orderId,cash_session_id:cashSessionId,status:"queued",payload:{trigger,copy:n+1},created_by:user?.id||null})}}
 async function partial(order){await queuePrint("partial_table",order.id);await audit("partial_ticket","order",order.id);setNotice("Ticket parcial enviado a impresión")}
 async function closeOrder(order,method){const active=itemsFor(order.id);const total=active.reduce((a,i)=>a+Number(i.quantity)*Number(i.unit_price),0);if(total<=0)return setNotice("La mesa no tiene consumos para cobrar.");setBusy(true);let cashSessionId=null;if(method==="cash"){const {data:cs}=await supabase.from("comanda_cash_sessions").select("id").eq("account_id",branch.account_id).eq("status","open").order("opened_at",{ascending:false}).limit(1).maybeSingle();cashSessionId=cs?.id||null;if(!cashSessionId){setBusy(false);return setNotice("Para cobrar en efectivo primero abrí una caja.")}}const waiter=order.waiter_id||null;const {error:pe}=await supabase.from("comanda_payments").insert({account_id:branch.account_id,order_id:order.id,cash_session_id:cashSessionId,staff_id:waiter,method,amount:total,received_amount:method==="cash"?total:null,change_amount:0,created_by:user.id});if(pe){setBusy(false);return setNotice(pe.message)}const now=new Date().toISOString();await supabase.from("comanda_order_items").update({kitchen_status:"delivered",delivered_at:now,updated_at:now}).eq("order_id",order.id).neq("kitchen_status","cancelled");await supabase.from("comanda_orders").update({status:"closed",closed_at:now,updated_at:now,cash_session_id:cashSessionId}).eq("id",order.id);await queuePrint("close_table",order.id,cashSessionId);await audit("order_close","order",order.id,null,{method,total});setBusy(false);setModal(null);setNotice(`Mesa cobrada · ${money(total)}`);await load()}
 async function audit(action,entity_type,entity_id,reason=null,metadata={}){if(!branch||!user)return;await supabase.from("comanda_audit_log").insert({account_id:branch.account_id,branch_id:branch.id,user_id:user.id,workstation_id:workstationId,action,entity_type,entity_id,reason,metadata})}
 if(!visible)return null;
 const orderModal=modal?.type==="order"?orders.find(o=>o.id===modal.order.id)||modal.order:null;const orderItems=orderModal?itemsFor(orderModal.id):[];
 return <main className={s.shell} data-sales-terminal="1"><header className={s.top}><div><span>VENTA / SALÓN</span><h1>{branch?.name||"Restaurante"}</h1><p>{orders.length} mesas abiertas · Puesto {role==="principal"?"Principal":"Camareros"}</p></div></header><div className={s.sectors}>{sectors.map(sec=><button key={sec.id} className={sec.id===sectorId?s.active:""} onClick={()=>setSectorId(sec.id)}>{sec.name}</button>)}</div><section className={s.floor}>{activeTables.map(t=>{const o=orderForTable(t.id),total=o?totalFor(o.id):0;return <button key={t.id} className={`${s.table} ${o?s.open:""} ${t.shape==="round"?s.round:t.shape==="diamond"?s.diamond:""}`} onClick={()=>o?setModal({type:"order",order:o,table:t}):setModal({type:"open",table:t})}><strong>Mesa {t.number}</strong><span>{t.seats||4} lugares</span>{o&&<><b>{money(total)}</b><small>{staff.find(x=>x.id===o.waiter_id)?.name||"Sin mozo"}</small></>}</button>})}</section>
 {modal?.type==="open"&&<OpenTableModal table={modal.table} staff={staff} busy={busy} onClose={()=>setModal(null)} onSave={f=>openTable(modal.table,f)}/>} {orderModal&&modal?.type==="order"&&<Modal title={`Mesa ${modal.table.number}`} onClose={()=>setModal(null)} wide><div className={s.orderLayout}><section className={s.catalog}><div className={s.catRow}><button className={!categoryId?s.catActive:""} onClick={()=>setCategoryId(null)}>Todos</button>{categories.map(c=><button key={c.id} className={categoryId===c.id?s.catActive:""} onClick={()=>setCategoryId(c.id)}>{c.public_name||c.name}</button>)}</div><div className={s.products}>{products.filter(p=>!categoryId||p.category_id===categoryId).map(p=><button key={p.id} onClick={()=>addProduct(orderModal,p)}><ComandaArt kind={p.image_key||categories.find(c=>c.id===p.category_id)?.image_key||"main"}/><strong>{p.public_name||p.name}</strong><span>{money(p.restaurant_price??p.price)}</span></button>)}</div></section><aside className={s.ticket}><div className={s.ticketHead}><div><strong>{orderModal.diners} comensales</strong><span>{staff.find(x=>x.id===orderModal.waiter_id)?.name||"Sin mozo asignado"}</span></div><b>{money(totalFor(orderModal.id))}</b></div><div className={s.lineItems}>{orderItems.map(i=><div key={i.id} className={i.kitchen_status==="ready"?s.ready:""}><div><strong>{i.product_name}</strong><small>{i.kitchen_status==="draft"?"Sin enviar":i.kitchen_status==="pending"?"Recibida en cocina":i.kitchen_status==="preparing"?"En preparación":i.kitchen_status==="ready"?"Lista":""}</small></div><div className={s.qty}><button onClick={()=>changeQty(i,-1)}>−</button><b>{Number(i.quantity)}</b><button onClick={()=>changeQty(i,1)}>+</button></div><span>{money(Number(i.quantity)*Number(i.unit_price))}</span></div>)}</div><div className={s.actions}><button onClick={()=>sendKitchen(orderModal)}>Enviar comanda</button><button onClick={()=>partial(orderModal)}>Ticket parcial</button><button className={s.pay} onClick={()=>setModal({type:"pay",order:orderModal,table:modal.table})}>Cobrar y cerrar</button></div></aside></div></Modal>}
 {modal?.type==="voidItem"&&<ReasonModal item={modal.item} onClose={()=>setModal(null)} onConfirm={r=>voidItem(modal.item,r)}/>} {modal?.type==="pay"&&<PayModal order={modal.order} total={totalFor(modal.order.id)} busy={busy} onClose={()=>setModal({type:"order",order:modal.order,table:modal.table})} onPay={m=>closeOrder(modal.order,m)}/>} {notice&&<button className={s.toast} onClick={()=>setNotice("")}>{notice}</button>}</main>
}
function OpenTableModal({table,staff,busy,onClose,onSave}){const [diners,setDiners]=useState(table.seats||4),[waiter,setWaiter]=useState(staff[0]?.id||""),[label,setLabel]=useState("");return <Modal title={`Abrir mesa ${table.number}`} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave({diners,waiter_id:waiter,label})}} className={s.form}><label>Cantidad de comensales<input type="number" min="1" max="200" value={diners} onChange={e=>setDiners(e.target.value)} autoFocus/></label><label>Mozo / camarero<select value={waiter} onChange={e=>setWaiter(e.target.value)}><option value="">Sin asignar</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Etiqueta<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Opcional"/></label><footer><button type="button" onClick={onClose}>Cancelar</button><button className={s.pay} disabled={busy}>Abrir mesa</button></footer></form></Modal>}
function ReasonModal({item,onClose,onConfirm}){const [reason,setReason]=useState("");return <Modal title={`Anular ${item.product_name}`} onClose={onClose}><form className={s.form} onSubmit={e=>{e.preventDefault();onConfirm(reason)}}><label>Motivo de anulación<textarea value={reason} onChange={e=>setReason(e.target.value)} required autoFocus placeholder="Escribí el motivo…"/></label><footer><button type="button" onClick={onClose}>Cancelar</button><button className={s.danger}>Anular producto</button></footer></form></Modal>}
function PayModal({total,busy,onClose,onPay}){const [method,setMethod]=useState("cash");return <Modal title="Cobrar mesa" onClose={onClose}><div className={s.payBox}><span>Total</span><strong>{money(total)}</strong><div>{METHODS.map(([v,l])=><button key={v} className={method===v?s.selectedMethod:""} onClick={()=>setMethod(v)}>{l}</button>)}</div><footer><button onClick={onClose}>Volver</button><button className={s.pay} disabled={busy} onClick={()=>onPay(method)}>{busy?"Procesando…":"Confirmar cobro"}</button></footer></div></Modal>}
