"use client";
import {useEffect,useRef,useState} from "react";
import {supabase} from "../../../lib/supabase";

function beep(){try{const Ctx=window.AudioContext||window.webkitAudioContext;const ctx=new Ctx(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=1046;g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.18,ctx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.35);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.36)}catch{}}
export default function ComandaReadyNotifier(){
 const [role,setRole]=useState(null),[alerts,setAlerts]=useState([]);const known=useRef(new Set());
 const branchId=typeof window!=="undefined"?sessionStorage.getItem("comanda_branch"):null,workstationId=typeof window!=="undefined"?sessionStorage.getItem("comanda_workstation"):null;
 async function load(){if(!branchId||!["waiter","waiter_app","principal"].includes(role))return;const {data:orders}=await supabase.from("comanda_orders").select("id,table_id,label,status").eq("branch_id",branchId).eq("status","open");const ids=(orders||[]).map(x=>x.id);if(!ids.length){setAlerts([]);return}const {data:items}=await supabase.from("comanda_order_items").select("id,order_id,product_name,quantity,kitchen_status,prepared_at").in("order_id",ids).eq("kitchen_status","ready").order("prepared_at",{ascending:false});const tableIds=[...new Set((orders||[]).map(o=>o.table_id).filter(Boolean))];let tableMap={};if(tableIds.length){const {data:tables}=await supabase.from("comanda_tables").select("id,number").in("id",tableIds);tableMap=Object.fromEntries((tables||[]).map(t=>[t.id,t.number]))}const orderMap=Object.fromEntries((orders||[]).map(o=>[o.id,o]));const fresh=(items||[]).filter(i=>!known.current.has(i.id));if(known.current.size&&fresh.length)beep();(items||[]).forEach(i=>known.current.add(i.id));const grouped=new Map();for(const i of items||[]){const o=orderMap[i.order_id];if(!o)continue;if(!grouped.has(i.order_id))grouped.set(i.order_id,{orderId:i.order_id,table:tableMap[o.table_id]||"-",label:o.label||"",items:[]});grouped.get(i.order_id).items.push(i)}setAlerts([...grouped.values()])}
 useEffect(()=>{let alive=true;(async()=>{if(!workstationId)return;const {data}=await supabase.from("comanda_workstations").select("kind").eq("id",workstationId).maybeSingle();if(alive)setRole(data?.kind||null)})();return()=>{alive=false}},[workstationId]);
 useEffect(()=>{if(!["waiter","waiter_app","principal"].includes(role)||!branchId)return;load();const ch=supabase.channel(`waiter-ready-${branchId}`).on("postgres_changes",{event:"*",schema:"public",table:"comanda_order_items"},load).subscribe();return()=>supabase.removeChannel(ch)},[role,branchId]);
 if(!alerts.length||!["waiter","waiter_app","principal"].includes(role))return null;
 return <aside style={{position:"fixed",right:18,bottom:72,zIndex:205,display:"grid",gap:8,width:"min(340px,calc(100vw - 36px))"}}>{alerts.slice(0,4).map(a=><div key={a.orderId} style={{background:"#173e2b",color:"white",borderRadius:14,padding:"12px 14px",boxShadow:"0 16px 36px rgba(0,0,0,.22)",border:"1px solid rgba(255,255,255,.12)"}}><strong style={{display:"block",fontSize:13}}>Mesa {a.table} · pedido listo</strong><span style={{display:"block",fontSize:10,opacity:.78,marginTop:4}}>{a.items.map(i=>`${Number(i.quantity)}× ${i.product_name}`).join(" · ")}</span></div>)}</aside>
}
