"use client"

import{useEffect,useMemo,useState}from"react"
import HotelSidebar from"./components/shell/HotelSidebar"
import HotelTopbar from"./components/shell/HotelTopbar"
import CommandPalette from"./components/shell/CommandPalette"
import IntelligenceConcierge from"./components/intelligence/IntelligenceConcierge"
import{useHotelSession}from"./hooks/useHotelSession"
import{useHotelData}from"./hooks/useHotelData"
import{can}from"./core/permissions"
import{VIEW_META}from"./core/navigation"
import{addDays,isoDate,money,shortDate}from"./core/formatters"
import CommandCenter from"./features/frontdesk/CommandCenter"
import{Lobby,Reservations,GuestCRM}from"./features/frontdesk/FrontDeskViews"
import ReservationDrawer from"./features/frontdesk/ReservationDrawer"
import{blankReservation,reservationToDraft}from"./features/frontdesk/reservationModel"
import{saveReservation,moveReservation,checkinReservation,checkoutReservation,savePayment}from"./services/reservations"
import{saveFloor,saveRoom,updateRoomStatus,saveBlock,saveHousekeepingTask,setHousekeepingStatus,saveMaintenanceTicket,setMaintenanceStatus,saveResource}from"./services/operations"
import{saveRateCell,saveRateRange,savePartner,saveGroup,saveUpsell,prepareChannel}from"./services/commercial"
import{openCashSession,saveCashMovement,closeCashSession,saveFinanceDocument,issueInternalDocument}from"./services/finance"
import{updateMemberRole,saveRolePermission,saveAutomation,toggleAutomation,deleteAutomation,resolveAutomationEvent,saveHotelSettings,prepareKey,revokeKey,createWebCheckin,sendReservationEmail,askIntelligence}from"./services/hotel"
import{RoomsView,MaintenanceView,ResourcesView,DigitalTwinView}from"./features/operations/OperationsViews"
import HousekeepingPremium from"./features/operations/HousekeepingPremium"
import{RevenueView,PartnersView,GroupsView,UpsellingView,DistributionView}from"./features/commercial/CommercialViews"
import{CashView,BillingView,ReportsView}from"./features/finance/FinanceViews"
import{KeysView,TeamView,AutomationsView,IntelligenceView,IntegrationsView,SettingsView}from"./features/hotel/HotelViews"
import SupportView from"./features/hotel/SupportView"
import ui from"./v2.module.css"

const TITLES={lobby:"Inicio",calendar:"Planning",reservations:"Reservas",guests:"Huéspedes",keys:"Llaves",rooms:"Habitaciones",housekeeping:"Housekeeping",maintenance:"Mantenimiento",resources:"Recursos",twin:"Digital Twin",rates:"Revenue",partners:"Empresas & Agencias",groups:"Grupos",upselling:"Upselling",distribution:"Distribución",cash:"Caja & Folios",billing:"Facturación",reports:"Reportes",team:"Equipo & Roles",automations:"Automatizaciones",intelligence:"Llena Intelligence",integrations:"Integraciones",settings:"Configuración",support:"Ayuda & soporte"}
const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))

export default function HotelOSV2(){
  const session=useHotelSession(),[view,setView]=useState("lobby"),[search,setSearch]=useState(""),[mobile,setMobile]=useState(false),[drawer,setDrawer]=useState(null),[blockDraft,setBlockDraft]=useState(null),[busy,setBusy]=useState(false),[toast,setToast]=useState(""),[commandOpen,setCommandOpen]=useState(false)
  const data=useHotelData(session.propertyId,view),permissions=data.hotel?.permissions||[],role=session.role,today=isoDate(),live=useMemo(()=>data.reservations.filter(r=>r.estado!=="cancelada"&&!r.no_show),[data.reservations]),activeRooms=data.rooms.filter(r=>r.activa!==false),currentProperty=session.properties.find(p=>String(p.id)===String(session.propertyId))
  const settings=data.settings||{hotel_name:currentProperty?.hotel_name||currentProperty?.name||"Hotel",motto:"La hospitalidad se siente en cada detalle.",logo_data_url:currentProperty?.logo_data_url||""},allowed=permission=>can(role,permission,permissions),ops=settings.operational_settings&&typeof settings.operational_settings==="object"?settings.operational_settings:{}
  const notify=message=>{setToast(String(message));setTimeout(()=>setToast(""),3200)},changeView=id=>{setView(id);setMobile(false)}
  useEffect(()=>{const handler=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setCommandOpen(v=>!v)}else if(e.key==="Escape")setCommandOpen(false)};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[])
  async function action(fn,success){try{setBusy(true);const result=await fn();await data.reload();if(success)notify(typeof success==="function"?success(result):success);return result}catch(error){notify(error?.message||"No se pudo completar la operación.")}finally{setBusy(false)}}
  function openReservation(r){setDrawer(reservationToDraft(r))}
  function newReservation(roomId="",start=""){const draft=blankReservation();if(roomId)draft.roomId=String(roomId);if(start)draft.start=start;setDrawer(draft)}
  async function persistReservation(draft){const room=data.rooms.find(r=>String(r.id)===String(draft.roomId)),original=draft.id?data.reservations.find(r=>String(r.id)===String(draft.id)):null;if(!room)return notify("Elegí una habitación.");if(!draft.guest?.trim())return notify("Falta el nombre del huésped.");await action(async()=>{await saveReservation({draft,room,propertyId:session.propertyId,userId:session.user.id,original});setDrawer(null)},draft.id?"Reserva actualizada.":"Reserva creada.")}
  async function move(id,roomId,start){const r=data.reservations.find(x=>String(x.id)===String(id));if(r)await action(()=>moveReservation({reservationId:r.id,roomId,start,end:null}),"Reserva movida.")}
  async function resize(id,end){const r=data.reservations.find(x=>String(x.id)===String(id));if(r)await action(()=>moveReservation({reservationId:r.id,roomId:r.habitacion_id,start:r.fecha_entrada,end}),"Fecha de salida actualizada.")}
  async function pay(payment){if(drawer?.id)await action(()=>savePayment({propertyId:session.propertyId,userId:session.user.id,reservationId:drawer.id,amount:payment.amount,method:payment.method,currency:payment.currency||"ARS",note:payment.note||""}),"Pago registrado.")}
  async function checkin(){if(drawer?.id)await action(async()=>{await checkinReservation({id:drawer.id,propertyId:session.propertyId});setDrawer(null)},"Check-in realizado.")}
  async function checkout(){if(drawer?.id)await action(async()=>{await checkoutReservation(drawer.id);setDrawer(null)},"Check-out realizado. La habitación pasó a Housekeeping.")}
  async function webCheckin(){if(!drawer?.id)return;const url=await action(()=>createWebCheckin({propertyId:session.propertyId,reservationId:drawer.id}),null);if(url){try{await navigator.clipboard.writeText(url);notify("Web Check-in generado y enlace copiado.")}catch{notify(`Web Check-in generado: ${url}`)}}}
  async function emailCurrent(){if(drawer?.id)await action(()=>sendReservationEmail({reservationId:drawer.id}),r=>r?.mode==="sent"?"Email enviado por el proveedor configurado.":"Correo preparado en el dispositivo.")}
  async function keyCurrent(){if(!original)return;const room=data.rooms.find(r=>String(r.id)===String(original.habitacion_id));await action(()=>prepareKey({propertyId:session.propertyId,userId:session.user.id,reservation:original,room,encoder:ops.key_encoder||{},count:Number(ops.key_encoder?.default_key_count||2)}),r=>r?.physical?"Llave codificada por el encoder.":"Emisión auditada; encoder físico no confirmó codificación.")}
  function printCurrent(){if(!original)return;const room=data.rooms.find(r=>String(r.id)===String(original.habitacion_id)),paid=data.payments.filter(p=>String(p.reserva_id)===String(original.id)).reduce((a,p)=>a+Number(p.monto||0),0),w=window.open("","_blank","width=900,height=720");if(!w)return notify("El navegador bloqueó la impresión.");w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Reserva ${esc(original.numero_reserva||original.id)}</title><style>body{font-family:Arial;color:#173126;padding:34px}h1{font-family:Georgia;font-weight:400}table{border-collapse:collapse;width:100%}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left}</style></head><body><small>${esc(settings.hotel_name)}</small><h1>Reserva ${esc(original.numero_reserva||original.id)}</h1><p><b>${esc(original.nombre_huesped)}</b><br>${esc(original.email_huesped||"")} · ${esc(original.telefono_huesped||"")}</p><table><tr><th>Habitación</th><td>${esc(room?.nombre||original.habitacion_id)}</td></tr><tr><th>Estadía</th><td>${esc(shortDate(original.fecha_entrada))} → ${esc(shortDate(original.fecha_salida))}</td></tr><tr><th>Total</th><td>${esc(money(original.precio_total,original.moneda))}</td></tr><tr><th>Pagado</th><td>${esc(money(paid,original.moneda))}</td></tr></table><script>onload=()=>print()</script></body></html>`);w.document.close()}
  const original=drawer?.id?data.reservations.find(r=>String(r.id)===String(drawer.id)):null
  if(session.loading)return <div className={ui.loading}>Preparando Habitación Llena OS…</div>
  if(!session.properties.length)return <div className={ui.loading}>No hay una propiedad asociada a esta cuenta.</div>
  const hotelName=settings.hotel_name||currentProperty?.hotel_name||currentProperty?.name||"Hotel",hotelLogo=settings.logo_data_url||currentProperty?.logo_data_url||"",newReservationAction=allowed("frontdesk.reservations.edit")?()=>newReservation():null
  return <div className={ui.shell}><HotelSidebar view={view} onView={changeView} hotelName={hotelName} hotelLogo={hotelLogo} role={role} properties={session.properties} propertyId={session.propertyId} onPropertyChange={session.setPropertyId} onLogout={session.logout} mobileOpen={mobile}/><main className={ui.work}>{view!=="lobby"&&<HotelTopbar view={view} title={TITLES[view]||VIEW_META[view]?.label||"Hotel"} onNewReservation={view==="support"?null:newReservationAction} onMenu={()=>setMobile(v=>!v)} onCommand={()=>setCommandOpen(true)}/>} {data.error&&<div className={ui.notice}>{data.error}</div>}{renderView()}</main>{drawer&&<ReservationDrawer initial={drawer} original={original} rooms={activeRooms} partners={data.commercial.partners||[]} groups={data.commercial.groups||[]} charges={data.charges} payments={data.payments} busy={busy} onClose={()=>setDrawer(null)} onSave={persistReservation} onCheckin={checkin} onCheckout={checkout} onPayment={pay} onPrint={printCurrent} onEmail={emailCurrent} onKey={keyCurrent} onWebCheckin={webCheckin}/>} {blockDraft&&<BlockModal draft={blockDraft} setDraft={setBlockDraft} rooms={activeRooms} busy={busy} onClose={()=>setBlockDraft(null)} onSave={()=>action(async()=>{await saveBlock({propertyId:session.propertyId,userId:session.user.id,draft:blockDraft});setBlockDraft(null)},"Habitación bloqueada.")}/>}<CommandPalette open={commandOpen} onClose={()=>setCommandOpen(false)} reservations={data.reservations} rooms={activeRooms} guests={data.guests} onNavigate={changeView} onOpenReservation={openReservation} onNewReservation={newReservationAction}/><IntelligenceConcierge settings={settings} rooms={activeRooms} reservations={live} payments={data.payments} onAsk={(question,context)=>askIntelligence({question,context})} onNavigate={changeView}/>{toast&&<div className={ui.toast}>{toast}</div>}</div>

  function renderView(){
    if(view==="lobby")return <Lobby settings={settings} rooms={data.rooms} reservations={live} payments={data.payments} onView={changeView} onOpen={openReservation} search={search} onSearch={setSearch} onNewReservation={newReservationAction} onMenu={()=>setMobile(v=>!v)} onCommand={()=>setCommandOpen(true)} userId={session.user?.id}/>
    if(view==="calendar")return <CommandCenter rooms={activeRooms} reservations={live} payments={data.payments} blocks={data.blocks} floors={data.floors} onMove={move} onResize={resize} onOpen={openReservation} onNew={(room,day)=>newReservation(room.id,day)} onBlock={(room,day)=>setBlockDraft({roomId:String(room.id),start:day,end:addDays(day,1),reason:"Bloqueo operativo",detail:""})}/>
    if(view==="reservations")return <Reservations reservations={data.reservations} rooms={data.rooms} search={search} onOpen={openReservation}/>
    if(view==="guests")return <GuestCRM guests={data.guests} search={search}/>
    if(view==="keys")return <KeysView reservations={live} rooms={data.rooms} issues={data.keyIssues||[]} settings={settings} onPrepare={(reservation,room,encoder,count)=>action(()=>prepareKey({propertyId:session.propertyId,userId:session.user.id,reservation,room,encoder,count}),r=>r?.physical?"Llave codificada.":"Emisión registrada; falta confirmación física.")} onRevoke={issue=>action(()=>revokeKey({propertyId:session.propertyId,id:issue.id}),"Llave revocada en el PMS.")}/>
    if(view==="rooms")return <RoomsView rooms={data.rooms} floors={data.floors} canManage={allowed("operations.rooms.manage")} onSaveFloor={draft=>action(()=>saveFloor({propertyId:session.propertyId,draft}),"Piso guardado.")} onSaveRoom={draft=>action(()=>saveRoom({propertyId:session.propertyId,draft}),"Habitación guardada.")} onBlock={room=>setBlockDraft({roomId:String(room.id),start:today,end:addDays(today,1),reason:"Mantenimiento",detail:""})}/>
    if(view==="housekeeping")return <HousekeepingPremium rooms={activeRooms} floors={data.floors} reservations={live} tasks={data.operations.housekeeping||[]} onRoomStatus={(room,status)=>action(()=>updateRoomStatus({propertyId:session.propertyId,roomId:room.id,status}),"Estado actualizado.")} onSaveTask={draft=>action(()=>saveHousekeepingTask({propertyId:session.propertyId,userId:session.user.id,draft}),"Tarea creada.")} onTaskStatus={(task,status)=>action(()=>setHousekeepingStatus({propertyId:session.propertyId,id:task.id,status}),"Tarea actualizada.")}/>
    if(view==="maintenance")return <MaintenanceView rooms={activeRooms} resources={data.operations.resources||[]} tickets={data.operations.maintenance||[]} onSave={draft=>action(()=>saveMaintenanceTicket({propertyId:session.propertyId,userId:session.user.id,draft}),"Ticket creado.")} onStatus={(ticket,status)=>action(()=>setMaintenanceStatus({propertyId:session.propertyId,id:ticket.id,status}),"Mantenimiento actualizado.")}/>
    if(view==="resources")return <ResourcesView resources={data.operations.resources||[]} onSave={draft=>action(()=>saveResource({propertyId:session.propertyId,draft}),"Recurso guardado.")}/>
    if(view==="twin")return <DigitalTwinView rooms={activeRooms} floors={data.floors} reservations={live}/>
    if(view==="rates")return <RevenueView rooms={activeRooms} reservations={live} rates={data.commercial.rates||[]} canManage={allowed("commercial.rates.manage")} onSaveCell={draft=>action(()=>saveRateCell({propertyId:session.propertyId,draft}),"Tarifa actualizada.")} onBulk={draft=>action(()=>saveRateRange({propertyId:session.propertyId,roomId:draft.roomId,start:draft.start,end:draft.end,price:draft.price,minStay:draft.minStay,stopSell:draft.stopSell,cta:draft.cta,ctd:draft.ctd,existingRates:data.commercial.rates||[],fallbackPrice:draft.fallbackPrice}),n=>`${n||0} días tarifarios actualizados.`)}/>
    if(view==="partners")return <PartnersView partners={data.commercial.partners||[]} canManage={allowed("commercial.partners.manage")} onSave={draft=>action(()=>savePartner({propertyId:session.propertyId,draft}),"Empresa / agencia guardada.")}/>
    if(view==="groups")return <GroupsView groups={data.commercial.groups||[]} partners={data.commercial.partners||[]} canManage={allowed("commercial.groups.manage")} onSave={draft=>action(()=>saveGroup({propertyId:session.propertyId,draft}),"Grupo guardado.")}/>
    if(view==="upselling")return <UpsellingView items={data.commercial.upsells||[]} canManage={allowed("commercial.upsell")} onSave={draft=>action(()=>saveUpsell({propertyId:session.propertyId,draft}),"Upsell guardado.")}/>
    if(view==="distribution")return <DistributionView connections={data.channels||[]} onPrepare={provider=>action(()=>prepareChannel({propertyId:session.propertyId,provider}),provider==="Motor directo"?"Motor directo registrado.":`${provider}: sandbox preparado; todavía no es una conexión real.`)}/>
    if(view==="cash")return <CashView sessions={data.finance.sessions||[]} movements={data.finance.movements||[]} reservations={live} canManage={allowed("finance.cash")} onOpen={draft=>action(()=>openCashSession({propertyId:session.propertyId,userId:session.user.id,openingAmount:draft.openingAmount,notes:draft.notes}),"Caja abierta.")} onMovement={draft=>action(()=>saveCashMovement({propertyId:session.propertyId,userId:session.user.id,sessionId:draft.sessionId,reservationId:draft.reservationId,movementType:draft.movementType,method:draft.method,amount:draft.amount,concept:draft.concept,reference:draft.reference,currency:draft.currency}),"Movimiento registrado.")} onClose={draft=>action(()=>closeCashSession({propertyId:session.propertyId,userId:session.user.id,sessionId:draft.sessionId,closingAmount:draft.closingAmount,notes:draft.notes}),r=>`Caja cerrada · diferencia ${money(r?.difference||0)}`)}/>
    if(view==="billing")return <BillingView documents={data.finance.documents||[]} reservations={live} partners={data.commercial.partners||[]} groups={data.commercial.groups||[]} canManage={allowed("finance.folios")} onSave={draft=>action(()=>saveFinanceDocument({propertyId:session.propertyId,userId:session.user.id,draft}),"Documento guardado.")} onIssue={doc=>action(()=>issueInternalDocument({propertyId:session.propertyId,id:doc.id}),number=>`Documento interno emitido: ${number}`)}/>
    if(view==="reports")return <ReportsView reservations={data.reservations} rooms={data.rooms} payments={data.payments} housekeeping={data.operations.housekeeping||[]}/>
    if(view==="team")return <TeamView members={data.hotel.members||[]} permissions={permissions} currentRole={role} onRole={(member,nextRole)=>action(()=>updateMemberRole({propertyId:session.propertyId,userId:member.user_id,role:nextRole}),"Rol actualizado.")} onPermission={(targetRole,permission,value)=>action(()=>saveRolePermission({propertyId:session.propertyId,role:targetRole,permission,allowed:value}),"Permiso actualizado.")}/>
    if(view==="automations")return <AutomationsView rules={data.hotel.automations||[]} events={data.hotel.events||[]} canManage={allowed("hotel.automations")} onSave={draft=>action(()=>saveAutomation({propertyId:session.propertyId,userId:session.user.id,draft}),"Automatización guardada.")} onToggle={(rule,enabled)=>action(()=>toggleAutomation({propertyId:session.propertyId,id:rule.id,enabled}),enabled?"Automatización activada.":"Automatización pausada.")} onDelete={rule=>action(()=>deleteAutomation({propertyId:session.propertyId,id:rule.id}),"Automatización eliminada.")} onResolve={event=>action(()=>resolveAutomationEvent({propertyId:session.propertyId,id:event.id}),"Evento resuelto.")}/>
    if(view==="intelligence")return <IntelligenceView settings={settings} rooms={activeRooms} reservations={live} payments={data.payments} onAsk={(question,context)=>askIntelligence({question,context})}/>
    if(view==="integrations")return <IntegrationsView settings={settings} channels={data.channels||[]}/>
    if(view==="settings")return <SettingsView settings={settings} canManage={allowed("hotel.settings")} onSave={draft=>action(()=>saveHotelSettings({propertyId:session.propertyId,draft}),"Configuración guardada.")}/>
    if(view==="support")return <SupportView propertyId={session.propertyId} hotelName={hotelName}/>
    return <ModuleBridge view={view}/>
  }
}

function ModuleBridge({view}){return <div className={ui.content}><section className={ui.placeholder}><div><span>MIGRACIÓN MODULAR SEGURA</span><h2>{VIEW_META[view]?.label||"Módulo"}</h2><p>Este dominio todavía está en migración y no se simula funcionalidad.</p></div></section></div>}
function BlockModal({draft,setDraft,rooms,busy,onClose,onSave}){return <div className={ui.shade} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className={ui.modal} onSubmit={e=>{e.preventDefault();onSave()}}><header><h3>Bloquear habitación</h3><button type="button" onClick={onClose}>×</button></header><div className={ui.fieldGrid}><label><span>Habitación</span><select value={draft.roomId} onChange={e=>setDraft(x=>({...x,roomId:e.target.value}))}>{rooms.map(r=><option key={r.id} value={r.id}>{r.nombre}</option>)}</select></label><label><span>Motivo</span><select value={draft.reason} onChange={e=>setDraft(x=>({...x,reason:e.target.value}))}><option>Mantenimiento</option><option>Fuera de servicio</option><option>Uso interno</option><option>Bloqueo operativo</option><option>Otro</option></select></label><label><span>Desde</span><input type="date" value={draft.start} onChange={e=>setDraft(x=>({...x,start:e.target.value}))}/></label><label><span>Hasta</span><input type="date" value={draft.end} onChange={e=>setDraft(x=>({...x,end:e.target.value}))}/></label><label className={ui.wide}><span>Detalle</span><textarea value={draft.detail||""} onChange={e=>setDraft(x=>({...x,detail:e.target.value}))}/></label></div><footer><button type="button" onClick={onClose}>Cancelar</button><button disabled={busy}>Crear bloqueo</button></footer></form></div>}
