"use client"

import{useMemo,useState}from"react"
import s from"./bookingEngineStudio.module.css"

const STEPS=[["identity","Identidad","Marca y reglas base"],["design","Diseño","Plantilla, portada y galería"],["content","Contenido","Textos, SEO y cobro"],["publish","Publicar","Habitaciones y enlaces"]]
const money=(value,currency)=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:0}).format(Number(value)||0)
const imageUrl=item=>typeof item==="string"?item:item?.url||item?.src||""

export default function BookingEngineStudio({engine,draft,setDraft,description,setDescription,rooms,roomTypes,paymentConnection,paymentConnected,bookingUrl,siteUrl,embedCode,copied,saving,onCreate,onSave,onUpload,onRemoveGallery,onCopy,onToggleType}){
  const[step,setStep]=useState("identity"),[previewMode,setPreviewMode]=useState("desktop")
  const enabledTypes=useMemo(()=>roomTypes.filter(type=>draft?.room_type_rules?.[type]?.enabled!==false),[roomTypes,draft?.room_type_rules])
  const activeRooms=useMemo(()=>rooms.filter(room=>room.activa!==false&&room.online_bookable!==false).length,[rooms])
  const gallery=useMemo(()=>(draft?.gallery||[]).map(imageUrl).filter(Boolean),[draft?.gallery])
  const patch=values=>setDraft(current=>({...current,...values}))
  if(!engine)return <section className={s.emptyHero}><div className={s.emptyIcon}>✦</div><div><small>SITIO WEB + MOTOR</small><h2>Creá el canal directo del hotel</h2><p>Una web propia con motor conectado al inventario, las tarifas y las reservas del PMS.</p></div><button className={s.primary} disabled={saving} onClick={onCreate}>{saving?"Creando…":"Crear sitio"}</button></section>
  return <div className={s.studio}>
    <section className={s.statusBar}>
      <div><small>GESTIÓN · SITIO WEB</small><h2>{draft?.display_name||engine.display_name}</h2><p><span className={s.liveDot} data-live={draft?.enabled}/>{draft?.enabled?"Publicado":"Pausado"} · /hotel/{engine.slug}</p></div>
      <div className={s.statusActions}><button onClick={()=>patch({enabled:!draft?.enabled})}>{draft?.enabled?"Pausar sitio":"Activar sitio"}</button>{siteUrl?<a href={siteUrl} target="_blank" rel="noreferrer">Abrir web ↗</a>:null}{bookingUrl?<a href={bookingUrl} target="_blank" rel="noreferrer">Abrir motor ↗</a>:null}<button className={s.primary} disabled={saving} onClick={onSave}>{saving?"Guardando…":"Guardar y publicar"}</button></div>
    </section>
    <div className={s.metrics}><article><span>Habitaciones online</span><b>{activeRooms}</b><small>Inventario activo</small></article><article><span>Tipos publicados</span><b>{enabledTypes.length}</b><small>Categorías visibles</small></article><article data-ok={paymentConnected}><span>Mercado Pago</span><b>{paymentConnected?"Conectado":"Pendiente"}</b><small>{paymentConnected?"Cobro online disponible":"Pago en hotel disponible"}</small></article><article data-ok={draft?.enabled}><span>Estado</span><b>{draft?.enabled?"Publicado":"Pausado"}</b><small>Canal directo</small></article></div>
    <div className={s.workspace}>
      <section className={s.editor}>
        <nav className={s.stepNav}>{STEPS.map(([id,label,help],index)=><button key={id} className={step===id?s.active:""} onClick={()=>setStep(id)}><span>{index+1}</span><b>{label}</b><small>{help}</small></button>)}</nav>
        {step==="identity"?<IdentityStep draft={draft} patch={patch}/>:step==="design"?<DesignStep draft={draft} patch={patch} gallery={gallery} onUpload={onUpload} onRemoveGallery={onRemoveGallery} saving={saving}/>:step==="content"?<ContentStep draft={draft} patch={patch} description={description} setDescription={setDescription} paymentConnected={paymentConnected}/>:<PublishStep draft={draft} roomTypes={roomTypes} rooms={rooms} bookingUrl={bookingUrl} siteUrl={siteUrl} embedCode={embedCode} copied={copied} onCopy={onCopy} onToggleType={onToggleType}/>}
      </section>
      <LivePreview draft={draft} description={description} rooms={rooms} enabledTypes={enabledTypes} gallery={gallery} mode={previewMode} setMode={setPreviewMode}/>
    </div>
    <section className={`${s.payment} ${paymentConnected?s.paymentOk:""}`}><div><small>PASARELA DE PAGO</small><h3>{paymentConnected?"Mercado Pago conectado":"Mercado Pago pendiente"}</h3><p>{paymentConnected?`La cuenta está lista para cobros online${paymentConnection?.live_mode?" en modo real":""}.`:"El sitio puede reservar y cobrar en el hotel. Para exigir seña o pago total online, conectá Mercado Pago."}</p></div><span>{paymentConnected?"Conectado":"Pendiente"}</span></section>
  </div>
}

function IdentityStep({draft,patch}){return <div className={s.section}><header><small>PASO 1</small><h3>Identidad y reglas base</h3><p>Los datos esenciales que ve el huésped y usa el motor.</p></header><div className={s.formGrid}><label>Nombre público<input value={draft?.display_name||""} onChange={e=>patch({display_name:e.target.value})}/></label><label>Moneda<select value={draft?.currency||"ARS"} onChange={e=>patch({currency:e.target.value})}><option>ARS</option><option>USD</option><option>EUR</option><option>BRL</option><option>UYU</option></select></label><label>Teléfono<input value={draft?.contact_phone||""} onChange={e=>patch({contact_phone:e.target.value})}/></label><label>Email<input value={draft?.contact_email||""} onChange={e=>patch({contact_email:e.target.value})}/></label><label>Estadía mínima<input type="number" min="1" value={draft?.min_nights||1} onChange={e=>patch({min_nights:e.target.value})}/></label><label>Anticipación máxima<input type="number" min="1" value={draft?.max_advance_days||730} onChange={e=>patch({max_advance_days:e.target.value})}/></label></div></div>}

function DesignStep({draft,patch,gallery,onUpload,onRemoveGallery,saving}){const templates=[{id:"classic",name:"Clásica",help:"Limpia y hotelera"},{id:"boutique",name:"Boutique",help:"Más editorial y cálida"},{id:"minimal",name:"Minimal",help:"Simple y contemporánea"}];return <div className={s.section}><header><small>PASO 2</small><h3>Diseño y marca</h3><p>Elegí una base visual y personalizala sin tocar código.</p></header><div className={s.templateGrid}>{templates.map(item=><button key={item.id} className={draft?.template===item.id?s.templateActive:""} onClick={()=>patch({template:item.id})}><span className={s.templatePreview} data-template={item.id}><i/><i/><i/></span><b>{item.name}</b><small>{item.help}</small></button>)}</div><div className={s.designGrid}><div className={s.heroPicker}>{draft?.hero_url?<img src={draft.hero_url} alt="Vista previa de portada"/>:<div><span>▣</span><b>Portada del hotel</b><small>JPG, PNG o WebP · máximo 8 MB</small></div>}<label>{saving?"Subiendo…":"Cambiar portada"}<input type="file" hidden accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)onUpload(file,"hero");e.target.value=""}}/></label></div><div className={s.designFields}><label>Color principal<div className={s.colorField}><input type="color" value={draft?.primary_color||"#5B5CEB"} onChange={e=>patch({primary_color:e.target.value})}/><span>{draft?.primary_color||"#5B5CEB"}</span></div></label><label>Color de acento<div className={s.colorField}><input type="color" value={draft?.accent_color||"#7C5CFC"} onChange={e=>patch({accent_color:e.target.value})}/><span>{draft?.accent_color||"#7C5CFC"}</span></div></label><label className={s.galleryUpload}>Galería<label className={s.uploadButton}>＋ Agregar foto<input type="file" hidden accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)onUpload(file,"gallery");e.target.value=""}}/></label></label></div></div><div className={s.galleryStrip}>{gallery.map((url,index)=><figure key={`${url}-${index}`}><img src={url} alt=""/><button type="button" aria-label="Quitar foto" onClick={()=>onRemoveGallery(index)}>×</button></figure>)}{!gallery.length?<div className={s.galleryEmpty}>La galería aparece acá y se refleja en la vista previa.</div>:null}</div></div>}

function ContentStep({draft,patch,description,setDescription,paymentConnected}){return <div className={s.section}><header><small>PASO 3</small><h3>Contenido, SEO y cobro</h3><p>Textos claros, políticas y forma de pago del canal directo.</p></header><div className={s.formGrid}><label className={s.wide}>Presentación del hotel<textarea rows="4" value={description||""} onChange={e=>setDescription(e.target.value)} placeholder="Contá qué hace especial al hotel, ubicación y propuesta."/></label><label className={s.wide}>Mensaje junto al buscador<textarea rows="3" value={draft?.booking_message||""} onChange={e=>patch({booking_message:e.target.value})}/></label><label className={s.wide}>Mensaje de confirmación<textarea rows="3" value={draft?.confirmation_message||""} onChange={e=>patch({confirmation_message:e.target.value})}/></label><label className={s.wide}>Política de cancelación<textarea rows="3" value={draft?.cancellation_policy||""} onChange={e=>patch({cancellation_policy:e.target.value})}/></label><label>Título para Google<input value={draft?.seo_title||""} onChange={e=>patch({seo_title:e.target.value})}/></label><label>Descripción para Google<input value={draft?.seo_description||""} onChange={e=>patch({seo_description:e.target.value})}/></label><label>Cobro<select value={draft?.payment_mode||"at_property"} onChange={e=>patch({payment_mode:e.target.value})}><option value="at_property">Pago en el hotel</option><option value="deposit" disabled={!paymentConnected}>Seña online</option><option value="full" disabled={!paymentConnected}>Pago total online</option></select></label>{draft?.payment_mode==="deposit"?<label>Seña %<input type="number" min="1" max="100" value={draft?.deposit_percent||0} onChange={e=>patch({deposit_percent:e.target.value})}/></label>:<div/>}<label className={s.toggle}><input type="checkbox" checked={Boolean(draft?.allow_self_cancel)} onChange={e=>patch({allow_self_cancel:e.target.checked})}/><span><b>Cancelación desde el portal</b><small>Sólo reservas web dentro de la ventana permitida.</small></span></label><label>Límite para cancelar<input type="number" min="0" max="720" disabled={!draft?.allow_self_cancel} value={draft?.self_cancel_cutoff_hours??48} onChange={e=>patch({self_cancel_cutoff_hours:e.target.value})}/></label></div></div>}

function PublishStep({draft,roomTypes,rooms,bookingUrl,siteUrl,embedCode,copied,onCopy,onToggleType}){return <div className={s.section}><header><small>PASO 4</small><h3>Publicación y distribución</h3><p>Elegí qué categorías se venden y copiá los enlaces cuando estés listo.</p></header><div className={s.typeGrid}>{roomTypes.map(type=>{const enabled=draft?.room_type_rules?.[type]?.enabled!==false,count=rooms.filter(room=>(room.tipo||"Habitación")===type).length;return <label key={type} className={enabled?s.typeOn:""}><input type="checkbox" checked={enabled} onChange={e=>onToggleType(type,e.target.checked)}/><span><b>{type}</b><small>{count} unidad{count===1?"":"es"}</small></span></label>})}</div><div className={s.shareGrid}><Share label="SITIO DEL HOTEL" value={siteUrl} copied={copied==="site"} onCopy={()=>onCopy(siteUrl,"site")}/><Share label="MOTOR DIRECTO" value={bookingUrl} copied={copied==="url"} onCopy={()=>onCopy(bookingUrl,"url")}/><Share label="CÓDIGO EMBEBIDO" value={embedCode} copied={copied==="embed"} onCopy={()=>onCopy(embedCode,"embed")}/></div></div>}
function Share({label,value,copied,onCopy}){return <div><small>{label}</small><code>{value||"Se genera al crear el sitio"}</code><button disabled={!value} onClick={onCopy}>{copied?"Copiado ✓":"Copiar"}</button></div>}

function LivePreview({draft,description,rooms,enabledTypes,gallery,mode,setMode}){const currency=draft?.currency||"ARS",sample=enabledTypes[0]||rooms[0]?.tipo||"Habitación doble",price=rooms.find(room=>(room.tipo||"Habitación")===sample)?.precio||0;return <aside className={s.preview}><div className={s.previewTop}><div><span>VISTA PREVIA EN VIVO</span><i data-live={draft?.enabled}/></div><div className={s.previewModes}><button className={mode==="desktop"?s.modeActive:""} onClick={()=>setMode("desktop")}>Escritorio</button><button className={mode==="mobile"?s.modeActive:""} onClick={()=>setMode("mobile")}>Móvil</button></div></div><div className={s.deviceStage}><div className={s.previewFrame} data-mode={mode} data-template={draft?.template||"classic"} style={{"--preview-primary":draft?.primary_color||"#5B5CEB","--preview-accent":draft?.accent_color||"#7C5CFC"}}><div className={s.browserBar}><span/><span/><span/><b>{draft?.display_name||"Tu hotel"}</b></div><nav className={s.siteNav}><strong>{draft?.display_name||"Tu hotel"}</strong><div><span>Hotel</span><span>Habitaciones</span><span>Galería</span></div><button>Reservar</button></nav><section className={s.siteHero}>{draft?.hero_url?<img src={draft.hero_url} alt=""/>:null}<div className={s.heroOverlay}/><div className={s.siteHeroCopy}><small>RESERVA DIRECTA</small><h3>{draft?.display_name||"Tu hotel"}</h3><p>{draft?.booking_message||"Reservá online con disponibilidad real."}</p></div><div className={s.bookingBar}><span>Entrada</span><span>Salida</span><span>2 huéspedes</span><button>Buscar</button></div></section><section className={s.siteAbout}><small>EL HOTEL</small><h4>{draft?.display_name||"Tu hotel"}</h4><p>{description||"Una estadía simple de reservar, con información clara y disponibilidad actualizada."}</p><div className={s.trustRow}><span>Disponibilidad real</span><span>Reserva directa</span><span>Confirmación inmediata</span></div></section><section className={s.roomPreview}><div><small>HABITACIÓN</small><b>{sample}</b><span>Disponible para reservar online</span></div><strong>{money(price,currency)}</strong></section>{gallery.length?<div className={s.miniGallery}>{gallery.slice(0,3).map((url,index)=><img key={`${url}-${index}`} src={url} alt=""/>)}</div>:null}<footer className={s.siteFooter}>{draft?.contact_phone||"Contacto del hotel"}<span>Operado con Habitación Llena</span></footer></div></div></aside>}
