"use client"

import{useMemo,useState}from"react"
import s from"./bookingEngineStudio.module.css"

const STEPS=[["identity","Identidad"],["design","Diseño"],["content","Contenido"],["publish","Publicar"]]
const money=(value,currency)=>new Intl.NumberFormat("es-AR",{style:"currency",currency:currency||"ARS",maximumFractionDigits:0}).format(Number(value)||0)

export default function BookingEngineStudio({engine,draft,setDraft,rooms,roomTypes,paymentConnection,paymentConnected,bookingUrl,embedCode,copied,saving,onCreate,onSave,onUpload,onCopy,onToggleType}){
  const[step,setStep]=useState("identity")
  const enabledTypes=useMemo(()=>roomTypes.filter(type=>draft?.room_type_rules?.[type]?.enabled!==false),[roomTypes,draft?.room_type_rules])
  const activeRooms=useMemo(()=>rooms.filter(room=>room.activa!==false&&room.online_bookable!==false).length,[rooms])
  const patch=values=>setDraft(current=>({...current,...values}))
  if(!engine)return <section className={s.emptyHero}><div><small>MOTOR WEB</small><h2>Activá tu venta directa</h2><p>Un sitio de reservas propio, conectado al inventario y las tarifas del PMS, sin duplicar disponibilidad.</p></div><button className={s.primary} disabled={saving} onClick={onCreate}>{saving?"Creando…":"Crear motor"}</button></section>
  return <div className={s.studio}>
    <section className={s.statusBar}>
      <div><small>MOTOR PROPIO</small><h2>{engine.display_name}</h2><p>{draft?.enabled?"Venta directa activa":"Venta directa pausada"} · {engine.slug}</p></div>
      <div className={s.statusActions}><button onClick={()=>patch({enabled:!draft?.enabled})}>{draft?.enabled?"Pausar":"Activar"}</button><a href={`/book/${engine.slug}`} target="_blank" rel="noreferrer">Vista previa ↗</a><button className={s.primary} disabled={saving} onClick={onSave}>{saving?"Guardando…":"Guardar cambios"}</button></div>
    </section>
    <div className={s.metrics}><article><span>Habitaciones online</span><b>{activeRooms}</b></article><article><span>Tipos publicados</span><b>{enabledTypes.length}</b></article><article data-ok={paymentConnected}><span>Mercado Pago</span><b>{paymentConnected?"Conectado":"Pendiente"}</b></article><article data-ok={draft?.enabled}><span>Estado</span><b>{draft?.enabled?"Publicado":"Pausado"}</b></article></div>
    <div className={s.workspace}>
      <section className={s.editor}>
        <nav className={s.stepNav}>{STEPS.map(([id,label],index)=><button key={id} className={step===id?s.active:""} onClick={()=>setStep(id)}><span>{index+1}</span>{label}</button>)}</nav>
        {step==="identity"?<IdentityStep draft={draft} patch={patch}/>:step==="design"?<DesignStep draft={draft} patch={patch} onUpload={onUpload} saving={saving}/>:step==="content"?<ContentStep draft={draft} patch={patch} paymentConnected={paymentConnected}/>:<PublishStep draft={draft} patch={patch} roomTypes={roomTypes} rooms={rooms} bookingUrl={bookingUrl} embedCode={embedCode} copied={copied} onCopy={onCopy} onToggleType={onToggleType}/>}
      </section>
      <LivePreview draft={draft} rooms={rooms} enabledTypes={enabledTypes}/>
    </div>
    <section className={`${s.payment} ${paymentConnected?s.paymentOk:""}`}><div><small>PASARELA DE PAGO</small><h3>{paymentConnected?"Mercado Pago conectado":"Mercado Pago todavía no está conectado"}</h3><p>{paymentConnected?`Cuenta lista para cobros online${paymentConnection?.live_mode?" · modo real":""}.`:"El motor puede reservar y cobrar en el hotel. Para exigir seña o pago total online primero hay que conectar Mercado Pago."}</p></div><span>{paymentConnected?"Conectado":"Pendiente"}</span></section>
  </div>
}

function IdentityStep({draft,patch}){return <div className={s.section}><header><small>PASO 1</small><h3>Identidad del canal directo</h3><p>Lo que ve el huésped cuando entra a reservar.</p></header><div className={s.formGrid}><label>Nombre público<input value={draft?.display_name||""} onChange={e=>patch({display_name:e.target.value})}/></label><label>Moneda<select value={draft?.currency||"ARS"} onChange={e=>patch({currency:e.target.value})}><option>ARS</option><option>USD</option><option>EUR</option><option>BRL</option><option>UYU</option></select></label><label>Teléfono<input value={draft?.contact_phone||""} onChange={e=>patch({contact_phone:e.target.value})}/></label><label>Email<input value={draft?.contact_email||""} onChange={e=>patch({contact_email:e.target.value})}/></label><label>Estadía mínima<input type="number" min="1" value={draft?.min_nights||1} onChange={e=>patch({min_nights:e.target.value})}/></label><label>Anticipación máxima<input type="number" min="1" value={draft?.max_advance_days||730} onChange={e=>patch({max_advance_days:e.target.value})}/></label></div></div>}
function DesignStep({draft,patch,onUpload,saving}){return <div className={s.section}><header><small>PASO 2</small><h3>Diseño y marca</h3><p>Una experiencia visual propia sin salir del PMS.</p></header><div className={s.designGrid}><div className={s.heroPicker}>{draft?.hero_url?<img src={draft.hero_url} alt="Vista previa de portada"/>:<div><span>▣</span><b>Portada del hotel</b><small>JPG, PNG o WebP · máximo 8 MB</small></div>}<label>{saving?"Subiendo…":"Cambiar portada"}<input type="file" hidden accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)onUpload(file);e.target.value=""}}/></label></div><div className={s.designFields}><label>Plantilla<select value={draft?.template||"classic"} onChange={e=>patch({template:e.target.value})}><option value="classic">Clásica</option><option value="boutique">Boutique</option><option value="minimal">Minimal</option></select></label><label>Color principal<input type="color" value={draft?.primary_color||"#5B5CEB"} onChange={e=>patch({primary_color:e.target.value})}/></label><label>Color de acento<input type="color" value={draft?.accent_color||"#7C5CFC"} onChange={e=>patch({accent_color:e.target.value})}/></label></div></div></div>}
function ContentStep({draft,patch,paymentConnected}){return <div className={s.section}><header><small>PASO 3</small><h3>Contenido y reglas</h3><p>Mensajes comerciales, cancelación y forma de cobro del canal directo.</p></header><div className={s.formGrid}><label className={s.wide}>Mensaje de venta<textarea rows="3" value={draft?.booking_message||""} onChange={e=>patch({booking_message:e.target.value})}/></label><label className={s.wide}>Mensaje de confirmación<textarea rows="3" value={draft?.confirmation_message||""} onChange={e=>patch({confirmation_message:e.target.value})}/></label><label className={s.wide}>Política de cancelación<textarea rows="3" value={draft?.cancellation_policy||""} onChange={e=>patch({cancellation_policy:e.target.value})}/></label><label>Cobro<select value={draft?.payment_mode||"at_property"} onChange={e=>patch({payment_mode:e.target.value})}><option value="at_property">Pago en el hotel</option><option value="deposit" disabled={!paymentConnected}>Seña online</option><option value="full" disabled={!paymentConnected}>Pago total online</option></select></label>{draft?.payment_mode==="deposit"?<label>Seña %<input type="number" min="1" max="100" value={draft?.deposit_percent||0} onChange={e=>patch({deposit_percent:e.target.value})}/></label>:<div/>}<label className={s.toggle}><input type="checkbox" checked={Boolean(draft?.allow_self_cancel)} onChange={e=>patch({allow_self_cancel:e.target.checked})}/><span><b>Cancelación desde el portal</b><small>Sólo reservas web dentro de la ventana permitida.</small></span></label><label>Límite para cancelar<input type="number" min="0" max="720" disabled={!draft?.allow_self_cancel} value={draft?.self_cancel_cutoff_hours??48} onChange={e=>patch({self_cancel_cutoff_hours:e.target.value})}/></label><label>Términos URL<input value={draft?.terms_url||""} onChange={e=>patch({terms_url:e.target.value})}/></label><label>Privacidad URL<input value={draft?.privacy_url||""} onChange={e=>patch({privacy_url:e.target.value})}/></label></div></div>}
function PublishStep({draft,roomTypes,rooms,bookingUrl,embedCode,copied,onCopy,onToggleType}){return <div className={s.section}><header><small>PASO 4</small><h3>Publicación y distribución</h3><p>Elegí qué categorías se venden y copiá el acceso para tu web, redes o campañas.</p></header><div className={s.typeGrid}>{roomTypes.map(type=>{const enabled=draft?.room_type_rules?.[type]?.enabled!==false,count=rooms.filter(room=>(room.tipo||"Habitación")===type).length;return <label key={type} className={enabled?s.typeOn:""}><input type="checkbox" checked={enabled} onChange={e=>onToggleType(type,e.target.checked)}/><span><b>{type}</b><small>{count} unidad{count===1?"":"es"}</small></span></label>})}</div><div className={s.shareGrid}><div><small>ENLACE DIRECTO</small><code>{bookingUrl}</code><button onClick={()=>onCopy(bookingUrl,"url")}>{copied==="url"?"Copiado ✓":"Copiar enlace"}</button></div><div><small>EMBEBIDO</small><code>{embedCode}</code><button onClick={()=>onCopy(embedCode,"embed")}>{copied==="embed"?"Copiado ✓":"Copiar código"}</button></div></div></div>}
function LivePreview({draft,rooms,enabledTypes}){const currency=draft?.currency||"ARS",sample=enabledTypes[0]||rooms[0]?.tipo||"Habitación doble",price=rooms.find(room=>(room.tipo||"Habitación")===sample)?.precio||0;return <aside className={s.preview}><div className={s.previewTop}><span>VISTA PREVIA</span><i data-live={draft?.enabled}/></div><div className={s.previewFrame} style={{"--preview-primary":draft?.primary_color||"#5B5CEB","--preview-accent":draft?.accent_color||"#7C5CFC"}}><div className={s.previewHero}>{draft?.hero_url?<img src={draft.hero_url} alt=""/>:null}<div><small>RESERVA DIRECTA</small><h3>{draft?.display_name||"Tu hotel"}</h3><p>{draft?.booking_message||"Reservá online con disponibilidad real."}</p></div></div><div className={s.previewSearch}><span>Entrada</span><span>Salida</span><button>Buscar</button></div><article><div><small>TIPO DE HABITACIÓN</small><b>{sample}</b><span>Disponibilidad en tiempo real</span></div><strong>{money(price,currency)}</strong></article><footer>Reserva segura · Habitación Llena</footer></div></aside>}
