"use client"

import p from"./bookingEngineStudioPreview.module.css"
import{Light,money}from"./BookingEngineStudioBits"

function PreviewHeader({mode,setMode,label="VISTA PREVIA EN VIVO"}){return <div className={p.previewTop}><div><i/><span>{label}</span></div><div className={p.previewModes}><button type="button" className={mode==="desktop"?p.modeActive:""} onClick={()=>setMode("desktop")}>Escritorio</button><button type="button" className={mode==="mobile"?p.modeActive:""} onClick={()=>setMode("mobile")}>Móvil</button></div></div>}

export function ManagedPreview({draft,description,rooms,enabledTypes,gallery,previewMode,setPreviewMode}){const currency=draft?.currency||"ARS",sample=enabledTypes[0]||rooms[0]?.tipo||"Habitación",price=rooms.find(room=>(room.tipo||"Habitación")===sample)?.precio||0;return <aside className={p.preview}><PreviewHeader mode={previewMode} setMode={setPreviewMode}/><div className={p.deviceStage}><div className={p.previewFrame} data-mode={previewMode} data-template={draft?.template||"classic"} style={{"--preview-primary":draft?.primary_color||"#5B5CEB","--preview-accent":draft?.accent_color||"#7C5CFC"}}><div className={p.browserBar}><span/><span/><span/><b>{draft?.display_name||"Tu hotel"}</b></div><nav className={p.siteNav}><strong>{draft?.display_name||"Tu hotel"}</strong><div><span>Hotel</span><span>Habitaciones</span><span>Galería</span></div><button>Reservar</button></nav><section className={p.siteHero}>{draft?.hero_url?<img src={draft.hero_url} alt=""/>:null}<div className={p.heroOverlay}/><div className={p.siteHeroCopy}><small>RESERVA DIRECTA</small><h3>{draft?.display_name||"Tu hotel"}</h3><p>{draft?.booking_message||"Reservá directo con disponibilidad real."}</p></div><div className={p.bookingBar}><span><small>Entrada</small>Elegir fecha</span><span><small>Salida</small>Elegir fecha</span><span><small>Huéspedes</small>2 personas</span><button>Buscar</button></div></section><section className={p.siteAbout}><small>EL HOTEL</small><h4>{draft?.display_name||"Tu hotel"}</h4><p>{description||"Una estadía simple de reservar, con información clara y disponibilidad actualizada."}</p><div><span>Disponibilidad real</span><span>Reserva directa</span><span>Confirmación inmediata</span></div></section><section className={p.roomPreview}><div><small>DESDE</small><b>{sample}</b><span>Tarifa conectada al PMS</span></div><strong>{money(price,currency)}</strong></section>{gallery.length?<div className={p.miniGallery}>{gallery.slice(0,3).map((url,index)=><img key={`${url}-${index}`} src={url} alt=""/>)}</div>:null}<footer className={p.siteFooter}><b>{draft?.display_name||"Tu hotel"}</b><span>{draft?.contact_phone||"Contacto del hotel"}</span></footer></div></div></aside>}

export function ExternalPreview({draft,integration,previewMode,setPreviewMode}){return <aside className={p.preview}><PreviewHeader mode={previewMode} setMode={setPreviewMode} label="ASÍ QUEDA EN TU WEB"/><div className={p.deviceStage}><div className={`${p.previewFrame} ${p.externalFrame}`} data-mode={previewMode} style={{"--preview-primary":draft?.primary_color||"#5B5CEB"}}><div className={p.browserBar}><span/><span/><span/><b>www.tuhotel.com</b></div><nav className={p.fakeNav}><strong>{draft?.display_name||"Tu hotel"}</strong><span>Inicio</span><span>Habitaciones</span><span>Contacto</span></nav><section className={p.fakeHero}><small>TU WEB ACTUAL</small><h3>El diseño sigue siendo tuyo.</h3><p>Habitación Llena aparece solamente donde decidís vender.</p>{integration==="link"?<button className={p.demoBook}>Reservar ahora</button>:null}</section>{integration==="search"?<div className={p.demoSearch}><span><small>Entrada</small>Elegir fecha</span><span><small>Salida</small>Elegir fecha</span><span><small>Huéspedes</small>2</span><button>Buscar</button></div>:null}{integration==="full"?<div className={p.demoEngine}><header><div><small>RESERVA DIRECTA</small><b>{draft?.display_name||"Tu hotel"}</b></div><Light tone="green">Disponible</Light></header><h4>Encontrá tu habitación</h4><div><span>Entrada</span><span>Salida</span><span>2 huéspedes</span><button>Buscar</button></div><footer>Operado con Habitación Llena</footer></div>:null}<section className={p.fakeContent}><i/><i/><i/></section></div></div></aside>}
