"use client"

import{Light,Switch}from"./BookingEngineStudioBits"
import{LANGUAGES,normalizeLanguages,normalizeSections}from"./websiteStageTwo"
import s from"./bookingEngineStageTwo.module.css"

export function SiteStageTwo({websiteDraft,patchWebsite,revisions,onRestoreRevision}){
  const sections=normalizeSections(websiteDraft?.sections),languages=normalizeLanguages(websiteDraft?.languages),defaultLanguage=languages.includes(websiteDraft?.default_language)?websiteDraft.default_language:languages[0]
  const move=(id,delta)=>{const next=[...sections],index=next.findIndex(item=>item.id===id),target=index+delta;if(index<0||target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];patchWebsite({sections:next})}
  const toggleSection=(id,enabled)=>patchWebsite({sections:sections.map(item=>item.id===id?{...item,enabled:item.required?true:enabled}:item)})
  const toggleLanguage=id=>{const exists=languages.includes(id),next=exists?languages.filter(item=>item!==id):[...languages,id];if(!next.length)return;patchWebsite({languages:next,default_language:next.includes(defaultLanguage)?defaultLanguage:next[0]})}
  return <div className={s.stack}>
    <section className={s.card}><header><div><small>SECCIONES</small><h3>Armá la página sin complicarte</h3><p>Mostrá, ocultá y ordená bloques. La disponibilidad y las tarifas siguen saliendo del PMS.</p></div><Light tone="green">En vivo</Light></header><div className={s.sectionList}>{sections.map((item,index)=><article key={item.id}><span className={s.handle}>≡</span><div><b>{item.name}</b><small>{item.help}</small></div><div className={s.order}><button type="button" disabled={index===0} onClick={()=>move(item.id,-1)} aria-label={`Subir ${item.name}`}>↑</button><button type="button" disabled={index===sections.length-1} onClick={()=>move(item.id,1)} aria-label={`Bajar ${item.name}`}>↓</button></div><label className={s.miniSwitch}><input type="checkbox" checked={item.enabled!==false} disabled={item.required} onChange={event=>toggleSection(item.id,event.target.checked)}/><i/></label></article>)}</div></section>
    <section className={s.card}><header><div><small>IDIOMAS DEL SITIO Y CTA</small><h3>Que reservar sea obvio</h3><p>Elegí los idiomas de la página pública y mantené un botón de reservas siempre a mano. El motor conserva por ahora su flujo operativo en español.</p></div></header><div className={s.languages}>{LANGUAGES.map(item=><button type="button" key={item.id} className={languages.includes(item.id)?s.languageOn:""} onClick={()=>toggleLanguage(item.id)}><span>{languages.includes(item.id)?"✓":"＋"}</span>{item.name}</button>)}</div><div className={s.controls}><label>Idioma principal<select value={defaultLanguage} onChange={event=>patchWebsite({default_language:event.target.value})}>{languages.map(id=><option key={id} value={id}>{LANGUAGES.find(item=>item.id===id)?.name||id}</option>)}</select></label><label>Texto del botón<input value={websiteDraft?.floating_booking_label||"Reservar"} onChange={event=>patchWebsite({floating_booking_label:event.target.value})} maxLength="28"/></label><label>Posición<select value={websiteDraft?.floating_booking_position||"bottom_right"} onChange={event=>patchWebsite({floating_booking_position:event.target.value})}><option value="bottom_right">Abajo a la derecha</option><option value="bottom_left">Abajo a la izquierda</option></select></label></div><Switch checked={websiteDraft?.floating_booking_enabled!==false} onChange={value=>patchWebsite({floating_booking_enabled:value})} label="Botón flotante de reservas" help="En móvil y escritorio acompaña al huésped sin tapar contenido."/></section>
    <RevisionCard revisions={revisions} onRestoreRevision={onRestoreRevision}/>
  </div>
}

export function AnalyticsCard({funnel}){const data=funnel||{},visits=Number(data.visits??(Number(data.site_views||0)+Number(data.engine_views||0))),empty=!visits;return <section className={s.analytics}><header><div><small>ÚLTIMOS 30 DÍAS</small><h3>Embudo de venta directa</h3></div><Light tone={empty?"yellow":"green"}>{empty?"Midiendo desde ahora":`${Number(data.conversion_pct||0)}% conversión`}</Light></header><div className={s.funnel}><article><strong>{visits}</strong><span>Entradas al canal</span></article><i>→</i><article><strong>{Number(data.searches||0)}</strong><span>Búsquedas</span></article><i>→</i><article><strong>{Number(data.booking_starts||0)}</strong><span>Reservas iniciadas</span></article><i>→</i><article><strong>{Number(data.confirmed||0)}</strong><span>Confirmadas</span></article></div>{empty?<p>Las métricas empiezan a registrarse con esta etapa. No usamos datos sensibles del huésped para este embudo.</p>:<SourceRow sources={data.sources}/>}</section>}
function SourceRow({sources}){const entries=Object.entries(sources&&typeof sources==="object"?sources:{}).sort((a,b)=>Number(b[1])-Number(a[1])).slice(0,5);if(!entries.length)return null;return <div className={s.sources}><small>ORIGEN</small>{entries.map(([key,value])=><span key={key}><b>{sourceLabel(key)}</b>{value}</span>)}</div>}
function sourceLabel(value){return({site:"Web HL",direct:"Directo",button:"Botón",search:"Buscador",embed:"Embebido",whatsapp:"WhatsApp",engine:"Motor"}[value]||value)}
function RevisionCard({revisions,onRestoreRevision}){return <section className={s.card}><header><div><small>VERSIONES</small><h3>Publicar sin miedo</h3><p>Cada publicación guarda una copia. Cargar una versión anterior la convierte en borrador; nada cambia online hasta publicar.</p></div></header>{revisions?.length?<div className={s.revisions}>{revisions.map(item=><article key={item.id}><div><b>Versión {item.version}</b><small>{formatDate(item.created_at)}</small></div><button type="button" onClick={()=>onRestoreRevision(item)}>Cargar</button></article>)}</div>:<div className={s.empty}>La primera publicación de esta etapa va a crear la versión 1.</div>}</section>}
function formatDate(value){try{return new Intl.DateTimeFormat("es-AR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}catch{return""}}
