"use client"

import{useCallback,useEffect,useMemo,useState}from"react"
import{supabase}from"../../../../lib/supabaseClient"
import BookingEngineStudio from"./BookingEngineStudio"

const ENGINE_FIELDS="id,slug,enabled,display_name,currency,primary_color,accent_color,logo_url,hero_url,booking_message,confirmation_message,contact_phone,contact_email,allowed_origins,min_advance_days,max_advance_days,min_nights,template,cancellation_policy,terms_url,privacy_url,payment_mode,deposit_percent,room_type_rules,gallery,seo_title,seo_description,allow_self_cancel,self_cancel_cutoff_hours,updated_at"
const WEBSITE_FIELDS="property_id,mode,enabled,custom_domain,domain_status,seo_indexable,seo_canonical_url,analytics_ga4_id,analytics_gtm_id,analytics_meta_pixel_id,updated_at"
const slugify=value=>String(value||"hotel").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,58)||"hotel"
const imageUrl=item=>typeof item==="string"?item:item?.url||item?.src||""
const normalizeOrigins=value=>String(value||"").split(/[\n,]/).map(item=>item.trim()).filter(Boolean).map(item=>{try{return new URL(/^https?:\/\//i.test(item)?item:`https://${item}`).origin}catch{return""}}).filter(Boolean)

export default function WebsitePanel({propertyId,propertyName}){
  const[engine,setEngine]=useState(null),[draft,setDraft]=useState(null),[website,setWebsite]=useState(null),[websiteDraft,setWebsiteDraft]=useState(null),[rooms,setRooms]=useState([]),[paymentConnection,setPaymentConnection]=useState(null),[description,setDescription]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[copied,setCopied]=useState("")
  const load=useCallback(async()=>{if(!propertyId)return;setLoading(true);setError("");try{const[engineRes,roomsRes,paymentRes,propertyRes,websiteRes]=await Promise.all([
    supabase.from("hotel_booking_engines").select(ENGINE_FIELDS).eq("property_id",propertyId).maybeSingle(),
    supabase.from("habitaciones").select("id,nombre,numero,tipo,precio,estado,activo").eq("property_id",propertyId).neq("activo",false).order("numero"),
    supabase.from("hotel_payment_connections").select("id,status,provider,account_email,updated_at").eq("property_id",propertyId).eq("provider","mercadopago").maybeSingle(),
    supabase.from("properties").select("description").eq("id",propertyId).maybeSingle(),
    supabase.from("hotel_websites").select(WEBSITE_FIELDS).eq("property_id",propertyId).maybeSingle()
  ]);if(engineRes.error)throw engineRes.error;if(roomsRes.error)throw roomsRes.error;if(websiteRes.error)throw websiteRes.error;const e=engineRes.data||null,w=websiteRes.data||{property_id:propertyId,mode:"managed",enabled:true,custom_domain:"",domain_status:"not_connected",seo_indexable:true,seo_canonical_url:"",analytics_ga4_id:"",analytics_gtm_id:"",analytics_meta_pixel_id:""};setEngine(e);setDraft(e?{...e}:null);setWebsite(w);setWebsiteDraft({...w});setRooms(roomsRes.data||[]);setPaymentConnection(paymentRes.data||null);setDescription(propertyRes.data?.description||"")}catch(err){setError(err.message||"No se pudo cargar el canal web.")}finally{setLoading(false)}},[propertyId])
  useEffect(()=>{load()},[load])
  const roomTypes=useMemo(()=>[...new Set(rooms.map(room=>room.tipo||"Habitación"))],[rooms]),paymentConnected=paymentConnection?.status==="connected",origin=typeof window!=="undefined"?window.location.origin:""
  const bookingUrl=engine?.slug&&origin?`${origin}/book/${engine.slug}`:"",siteUrl=engine?.slug&&origin?`${origin}/hotel/${engine.slug}`:"",includedDomain=engine?.slug?`${engine.slug}.habitacionllena.com`:""
  const buttonCode=bookingUrl?`<a href="${bookingUrl}" target="_blank" rel="noopener" style="display:inline-flex;align-items:center;justify-content:center;padding:14px 22px;border-radius:999px;background:#111827;color:#fff;font:600 16px system-ui;text-decoration:none">Reservar ahora</a>`:""
  const searchCode=bookingUrl?`<form action="${bookingUrl}" method="get" target="_blank" style="display:flex;gap:10px;flex-wrap:wrap;align-items:end;font-family:system-ui"><label>Entrada<br><input name="check_in" type="date" required style="padding:11px;border:1px solid #d1d5db;border-radius:12px"></label><label>Salida<br><input name="check_out" type="date" required style="padding:11px;border:1px solid #d1d5db;border-radius:12px"></label><label>Huéspedes<br><input name="guests" type="number" min="1" value="2" style="width:90px;padding:11px;border:1px solid #d1d5db;border-radius:12px"></label><button style="padding:12px 18px;border:0;border-radius:12px;background:#111827;color:white;font-weight:700">Buscar</button></form>`:""
  const embedCode=bookingUrl?`<iframe id="hl-booking-${engine.slug}" src="${bookingUrl}?embed=1" title="Reservas ${draft?.display_name||propertyName||"hotel"}" loading="lazy" style="width:100%;min-height:720px;border:0;border-radius:18px;overflow:hidden" allow="payment"></iframe>\n<script>window.addEventListener('message',function(e){if(e.origin!=='${origin}')return;if(e.data&&e.data.type==='hl-booking-resize'){var f=document.getElementById('hl-booking-${engine.slug}');if(f&&e.data.height)f.style.height=Math.max(620,Number(e.data.height))+'px';}});</script>`:""
  async function createEngine(mode="managed"){setSaving(true);setError("");setNotice("");try{const base=slugify(propertyName),{data:created,error:createError}=await supabase.from("hotel_booking_engines").insert({property_id:propertyId,slug:`${base}-${String(propertyId).slice(0,6)}`,enabled:true,display_name:propertyName||"Mi hotel",currency:"ARS",template:"classic",primary_color:"#5B5CEB",accent_color:"#7C5CFC",payment_mode:"at_property",deposit_percent:0,room_type_rules:{},gallery:[],allowed_origins:[]}).select(ENGINE_FIELDS).single();if(createError)throw createError;const nextWebsite={property_id:propertyId,mode,enabled:mode==="managed",domain_status:"not_connected",seo_indexable:true,updated_at:new Date().toISOString()},{data:w,error:wError}=await supabase.from("hotel_websites").upsert(nextWebsite,{onConflict:"property_id"}).select(WEBSITE_FIELDS).single();if(wError)throw wError;setEngine(created);setDraft({...created});setWebsite(w);setWebsiteDraft({...w});setNotice(mode==="managed"?"Canal directo creado. Tu sitio y el motor ya comparten inventario real.":"Motor directo creado. Sólo te mostramos lo necesario para conectarlo a tu web actual.")}catch(err){setError(err.message||"No se pudo crear el canal directo.")}finally{setSaving(false)}}
  async function save(){if(!draft||!websiteDraft)return;setSaving(true);setError("");setNotice("");try{const enginePayload={enabled:Boolean(draft.enabled),display_name:draft.display_name?.trim()||propertyName||"Hotel",currency:draft.currency||"ARS",primary_color:draft.primary_color||"#5B5CEB",accent_color:draft.accent_color||"#7C5CFC",logo_url:draft.logo_url||null,hero_url:draft.hero_url||null,booking_message:draft.booking_message||null,confirmation_message:draft.confirmation_message||null,contact_phone:draft.contact_phone||null,contact_email:draft.contact_email||null,allowed_origins:Array.isArray(draft.allowed_origins)?draft.allowed_origins:normalizeOrigins(draft.allowed_origins),min_advance_days:Number(draft.min_advance_days)||0,max_advance_days:Math.max(1,Number(draft.max_advance_days)||730),min_nights:Math.max(1,Number(draft.min_nights)||1),template:draft.template||"classic",cancellation_policy:draft.cancellation_policy||null,terms_url:draft.terms_url||null,privacy_url:draft.privacy_url||null,payment_mode:draft.payment_mode||"at_property",deposit_percent:draft.payment_mode==="deposit"?Math.min(100,Math.max(1,Number(draft.deposit_percent)||30)):0,room_type_rules:draft.room_type_rules||{},gallery:Array.isArray(draft.gallery)?draft.gallery:[],seo_title:draft.seo_title||null,seo_description:draft.seo_description||null,allow_self_cancel:Boolean(draft.allow_self_cancel),self_cancel_cutoff_hours:Math.max(0,Number(draft.self_cancel_cutoff_hours)||48),updated_at:new Date().toISOString()};const websitePayload={property_id:propertyId,mode:websiteDraft.mode==="external"?"external":"managed",enabled:websiteDraft.mode==="managed"?Boolean(websiteDraft.enabled):false,custom_domain:websiteDraft.custom_domain?.trim()||null,domain_status:websiteDraft.custom_domain?.trim()?websiteDraft.domain_status==="verified"?"verified":"pending":"not_connected",seo_indexable:Boolean(websiteDraft.seo_indexable),seo_canonical_url:websiteDraft.seo_canonical_url?.trim()||null,analytics_ga4_id:websiteDraft.analytics_ga4_id?.trim()||null,analytics_gtm_id:websiteDraft.analytics_gtm_id?.trim()||null,analytics_meta_pixel_id:websiteDraft.analytics_meta_pixel_id?.trim()||null,updated_at:new Date().toISOString()};const[eRes,wRes,pRes]=await Promise.all([supabase.from("hotel_booking_engines").update(enginePayload).eq("id",engine.id).eq("property_id",propertyId).select(ENGINE_FIELDS).single(),supabase.from("hotel_websites").upsert(websitePayload,{onConflict:"property_id"}).select(WEBSITE_FIELDS).single(),supabase.from("properties").update({description:description||null}).eq("id",propertyId)]);if(eRes.error)throw eRes.error;if(wRes.error)throw wRes.error;if(pRes.error)throw pRes.error;setEngine(eRes.data);setDraft({...eRes.data});setWebsite(wRes.data);setWebsiteDraft({...wRes.data});setNotice("Cambios guardados y publicados.")}catch(err){setError(err.message||"No se pudieron guardar los cambios.")}finally{setSaving(false)}}
  async function upload(file,kind){if(!engine||!file)return;setSaving(true);setError("");try{const ext=(file.name.split(".").pop()||"jpg").toLowerCase(),path=`${propertyId}/website/${kind}-${Date.now()}.${ext}`,{error:uploadError}=await supabase.storage.from("hotel-media").upload(path,file,{upsert:true,contentType:file.type});if(uploadError)throw uploadError;const{data}=supabase.storage.from("hotel-media").getPublicUrl(path),url=data.publicUrl;if(kind==="hero")setDraft(current=>({...current,hero_url:url}));else setDraft(current=>({...current,gallery:[...(Array.isArray(current.gallery)?current.gallery:[]),{url}].slice(-12)}))}catch(err){setError(err.message||"No se pudo subir la imagen.")}finally{setSaving(false)}}
  function removeGallery(index){setDraft(current=>({...current,gallery:(Array.isArray(current.gallery)?current.gallery:[]).filter((_,i)=>i!==index)}))}
  function setTypeEnabled(type,enabled){setDraft(current=>({...current,room_type_rules:{...(current.room_type_rules||{}),[type]:{...(current.room_type_rules?.[type]||{}),enabled}}}))}
  async function copy(value,key){if(!value)return;try{await navigator.clipboard.writeText(value);setCopied(key);setTimeout(()=>setCopied(""),1600)}catch{setError("No se pudo copiar. Seleccioná el código manualmente.")}}
  if(loading)return <div style={{padding:20,border:"1px solid var(--line)",borderRadius:20,color:"var(--muted)",fontSize:14}}>Cargando canal web…</div>
  return <div style={{display:"grid",gap:12}}>{error?<div style={{padding:13,border:"1px solid color-mix(in srgb,var(--red) 30%,var(--line))",borderRadius:16,color:"var(--red)",fontSize:13,fontWeight:700}}>{error}</div>:null}{notice?<div style={{padding:13,border:"1px solid color-mix(in srgb,var(--green) 30%,var(--line))",borderRadius:16,color:"var(--green)",fontSize:13,fontWeight:700}}>{notice}</div>:null}<BookingEngineStudio engine={engine} draft={draft} setDraft={setDraft} website={website} websiteDraft={websiteDraft} setWebsiteDraft={setWebsiteDraft} description={description} setDescription={setDescription} rooms={rooms} roomTypes={roomTypes} paymentConnection={paymentConnection} paymentConnected={paymentConnected} bookingUrl={bookingUrl} siteUrl={siteUrl} includedDomain={includedDomain} buttonCode={buttonCode} searchCode={searchCode} embedCode={embedCode} copied={copied} saving={saving} onCreate={createEngine} onSave={save} onUpload={upload} onRemoveGallery={removeGallery} onCopy={copy} onToggleType={setTypeEnabled}/></div>
}
