"use client"

import{useMemo,useRef,useState}from"react"
import HotelWebsiteCanvas from"../../../hotel/[slug]/HotelWebsiteCanvas"
import WebsiteAiStudio from"./WebsiteAiStudio"
import{Light,Switch,galleryUrls,templates}from"./BookingEngineStudioBits"
import{COMPONENT_CATALOG,FONT_OPTIONS,LANGUAGES,normalizeLanguages,normalizeSections,normalizeStudioConfig}from"./websiteStudioModel"
import w from"./websiteStudio.module.css"

const clone=value=>JSON.parse(JSON.stringify(value))
export default function WebsiteStudio({engine,draft,setDraft,websiteDraft,setWebsiteDraft,description,setDescription,rooms,saving,onUpload,onRemoveGallery,onSaveDraft,onPublish,siteUrl,draftSavedAt}){
  const[tool,setTool]=useState("site"),[device,setDevice]=useState("desktop"),[zoom,setZoom]=useState(86),[history,setHistory]=useState([]),[future,setFuture]=useState([]),dragId=useRef(null),gallery=useMemo(()=>galleryUrls(draft?.gallery),[draft?.gallery]),studio=normalizeStudioConfig(websiteDraft?.studio_config),sections=normalizeSections(websiteDraft?.sections),languages=normalizeLanguages(websiteDraft?.languages)
  const snapshot=()=>({draft:clone(draft),website:clone(websiteDraft),description}),remember=()=>{setHistory(current=>[...current.slice(-19),snapshot()]);setFuture([])},restore=snap=>{if(!snap)return;setDraft(snap.draft);setWebsiteDraft(snap.website);setDescription(snap.description)}
  const undo=()=>{if(!history.length)return;const current=snapshot(),previous=history[history.length-1];setHistory(history.slice(0,-1));setFuture(items=>[current,...items].slice(0,20));restore(previous)},redo=()=>{if(!future.length)return;const current=snapshot(),next=future[0];setFuture(future.slice(1));setHistory(items=>[...items,current].slice(-20));restore(next)}
  const patchDraft=value=>{remember();setDraft(current=>{const next={...current,...value};if(value?.template&&value.template!==current?.template&&!Object.prototype.hasOwnProperty.call(value,"primary_color")){const theme=templates.find(item=>item.id===value.template);if(theme){next.primary_color=theme.primary;next.accent_color=theme.accent}}return next})},patchWebsite=value=>{remember();setWebsiteDraft(current=>({...current,...value}))},patchStudio=value=>{remember();setWebsiteDraft(current=>({...current,studio_config:normalizeStudioConfig({...normalizeStudioConfig(current?.studio_config),...value})}))},patchTheme=value=>patchStudio({theme:{...studio.theme,...value}}),patchHero=value=>patchStudio({hero:{...studio.hero,...value}}),patchPopup=value=>patchStudio({popup:{...studio.popup,...value}})
  const toggle=id=>{const next=sections.map(item=>item.id===id?{...item,enabled:item.required?true:item.enabled===false}:item);patchWebsite({sections:next})},enable=id=>patchWebsite({sections:sections.map(item=>item.id===id?{...item,enabled:true}:item)}),drop=id=>{const from=dragId.current;if(!from||from===id)return;remember();const next=[...sections],a=next.findIndex(x=>x.id===from),b=next.findIndex(x=>x.id===id);if(a<0||b<0)return;const[moved]=next.splice(a,1);next.splice(b,0,moved);setWebsiteDraft(current=>({...current,sections:next}));dragId.current=null}
  const previewData={name:draft?.display_name||"Tu hotel",description,currency:draft?.currency||"ARS",primary_color:draft?.primary_color,accent_color:draft?.accent_color,logo_url:draft?.logo_url,hero_url:draft?.hero_url,booking_message:draft?.booking_message,contact_phone:draft?.contact_phone,contact_email:draft?.contact_email,gallery:draft?.gallery,template:draft?.template,website_sections:sections,website_studio_config:studio,website_languages:languages,website_default_language:websiteDraft?.default_language||languages[0],floating_booking_enabled:websiteDraft?.floating_booking_enabled!==false,floating_booking_label:websiteDraft?.floating_booking_label||"Reservar",floating_booking_position:websiteDraft?.floating_booking_position||"bottom_right",vouchers:[]}
  const currentTemplate=templates.find(item=>item.id===draft?.template)||templates[0],publishedTemplate=templates.find(item=>item.id===engine?.template)||templates[0],changed=JSON.stringify({template:draft?.template,primary:draft?.primary_color,accent:draft?.accent_color,sections,studio,description})!==JSON.stringify({template:engine?.template,primary:engine?.primary_color,accent:engine?.accent_color,sections:websiteDraft?.published_sections||sections,studio:websiteDraft?.published_studio_config||{},description:websiteDraft?.published_snapshot?.description??description})
  return <div className={w.shell}>
    <header className={w.toolbar}><div className={w.tools}>{[{id:"site",icon:"▤",label:"Sitio"},{id:"add",icon:"＋",label:"Agregar"},{id:"settings",icon:"⚙",label:"Ajustes"},{id:"popups",icon:"▭",label:"Popups"},{id:"styles",icon:"✦",label:"Estilos"},{id:"ai",icon:"✧",label:"OlivIA"}].map(item=><button key={item.id} className={tool===item.id?w.activeTool:""} onClick={()=>setTool(item.id)}><span>{item.icon}</span>{item.label}</button>)}</div><div className={w.publish}><Light tone={changed?"orange":"green"}>{changed?(draftSavedAt?"Borrador guardado":"Cambios sin guardar"):"Publicado"}</Light><button onClick={onSaveDraft} disabled={saving}>{saving?"Guardando…":"Guardar"}</button><button className={w.publishButton} onClick={onPublish} disabled={saving}>{saving?"Publicando…":"Publicar"}</button></div></header>
    <div className={w.subbar}><div><b>Página:</b><button className={w.pageButton}>Inicio⌄</button></div><div className={w.devices}><button className={device==="desktop"?w.on:""} onClick={()=>setDevice("desktop")}>▰</button><button className={device==="tablet"?w.on:""} onClick={()=>setDevice("tablet")}>▯</button><button className={device==="mobile"?w.on:""} onClick={()=>setDevice("mobile")}>▯</button></div><div className={w.address}><span>⌂</span><span>{siteUrl||"Tu dirección se genera al publicar"}</span></div><div className={w.history}><button onClick={undo} disabled={!history.length}>↶</button><button onClick={redo} disabled={!future.length}>↷</button><button onClick={()=>setZoom(z=>Math.max(55,z-5))}>−</button><span>{zoom}%</span><button onClick={()=>setZoom(z=>Math.min(100,z+5))}>＋</button></div></div>
    <div className={w.workspace}>
      <aside className={w.panel}>{tool==="site"?<SitePanel sections={sections} onToggle={toggle} onDragStart={id=>{dragId.current=id}} onDrop={drop} currentTemplate={currentTemplate} publishedTemplate={publishedTemplate}/>:null}{tool==="add"?<AddPanel sections={sections} onEnable={enable}/>:null}{tool==="settings"?<SettingsPanel draft={draft} patchDraft={patchDraft} studio={studio} patchHero={patchHero} websiteDraft={websiteDraft} patchWebsite={patchWebsite} description={description} setDescription={value=>{remember();setDescription(value)}} gallery={gallery} saving={saving} onUpload={onUpload} onRemoveGallery={onRemoveGallery} languages={languages}/>:null}{tool==="popups"?<PopupPanel popup={studio.popup} patchPopup={patchPopup}/>:null}{tool==="styles"?<StylesPanel draft={draft} patchDraft={patchDraft} studio={studio} patchTheme={patchTheme}/>:null}{tool==="ai"?<WebsiteAiStudio engineId={engine?.id} draft={draft} setDraft={setDraft} websiteDraft={websiteDraft} setWebsiteDraft={setWebsiteDraft} description={description} setDescription={setDescription}/>:null}</aside>
      <main className={w.canvas}><div className={w.canvasLabel}><span><i/> Vista previa en vivo</span><b>{currentTemplate.name}</b></div><div className={w.stage} data-device={device}><div className={w.scaler} style={{"--studio-zoom":zoom/100}}><HotelWebsiteCanvas data={previewData} slug={engine?.slug||"preview"} preview previewRooms={rooms}/></div></div></main>
    </div>
  </div>
}

function SitePanel({sections,onToggle,onDragStart,onDrop,currentTemplate,publishedTemplate}){return <div className={w.panelInner}><header><small>SITIO</small><h3>Inicio</h3><p>Arrastrá las secciones para cambiar el orden. Todo se adapta automáticamente a celular y escritorio.</p></header><div className={w.siteStatus}><span style={{background:currentTemplate.primary}}/><div><b>{currentTemplate.name}</b><small>{currentTemplate.id===publishedTemplate.id?"Diseño publicado":"Publicado: "+publishedTemplate.name}</small></div></div><div className={w.sectionList}>{sections.map(item=><article key={item.id} draggable onDragStart={()=>onDragStart(item.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>onDrop(item.id)}><span className={w.drag}>≡</span><span className={w.sectionIcon}>{item.icon}</span><div><b>{item.name}</b><small>{item.help}</small></div><label><input type="checkbox" checked={item.enabled!==false} disabled={item.required} onChange={()=>onToggle(item.id)}/><i/></label></article>)}</div></div>}
function AddPanel({sections,onEnable}){const enabled=new Set(sections.filter(x=>x.enabled!==false).map(x=>x.id));return <div className={w.panelInner}><header><small>COMPONENTES</small><h3>Agregar sección</h3><p>Bloques hoteleros listos para usar. No hay HTML libre que pueda romper el sitio.</p></header><div className={w.searchFake}>⌕ Buscar componentes…</div><div className={w.componentGrid}>{COMPONENT_CATALOG.map(item=><button key={item.id} disabled={enabled.has(item.id)||item.required} onClick={()=>onEnable(item.id)}><span>{item.icon}</span><div><b>{item.name}</b><small>{item.category}</small></div><em>{enabled.has(item.id)?"✓":"＋"}</em></button>)}</div></div>}
function SettingsPanel({draft,patchDraft,studio,patchHero,websiteDraft,patchWebsite,description,setDescription,gallery,saving,onUpload,onRemoveGallery,languages}){const toggleLanguage=id=>{const next=languages.includes(id)?languages.filter(x=>x!==id):[...languages,id];if(next.length)patchWebsite({languages:next,default_language:next.includes(websiteDraft?.default_language)?websiteDraft.default_language:next[0]})};return <div className={w.panelInner}><header><small>AJUSTES</small><h3>Contenido del hotel</h3><p>Nombre, portada, textos, contacto e idiomas. Los precios y habitaciones vienen del PMS.</p></header><Field label="Nombre público"><input value={draft?.display_name||""} onChange={e=>patchDraft({display_name:e.target.value})}/></Field><Field label="Título de portada"><input value={studio.hero.title||""} onChange={e=>patchHero({title:e.target.value})} placeholder={draft?.display_name||"Tu hotel"}/></Field><Field label="Bajada de portada"><textarea rows="3" value={studio.hero.subtitle||""} onChange={e=>patchHero({subtitle:e.target.value})} placeholder={draft?.booking_message||"Contá qué hace especial a tu hotel"}/></Field><div className={w.heroUpload}>{draft?.hero_url?<img src={draft.hero_url} alt=""/>:<span>Foto principal</span>}<label>{saving?"Subiendo…":"Cambiar portada"}<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)onUpload(f,"hero");e.target.value=""}}/></label></div><Field label="Presentación"><textarea rows="4" value={description||""} onChange={e=>setDescription(e.target.value)}/></Field><div className={w.two}><Field label="Teléfono"><input value={draft?.contact_phone||""} onChange={e=>patchDraft({contact_phone:e.target.value})}/></Field><Field label="Email"><input value={draft?.contact_email||""} onChange={e=>patchDraft({contact_email:e.target.value})}/></Field></div><div className={w.languageRow}>{LANGUAGES.map(item=><button key={item.id} className={languages.includes(item.id)?w.selectedChip:""} onClick={()=>toggleLanguage(item.id)}>{languages.includes(item.id)?"✓ ":"＋ "}{item.name}</button>)}</div><div className={w.galleryHead}><b>Galería</b><label>＋ Foto<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)onUpload(f,"gallery");e.target.value=""}}/></label></div><div className={w.galleryStrip}>{gallery.map((url,index)=><figure key={url+index}><img src={url} alt=""/><button onClick={()=>onRemoveGallery(index)}>×</button></figure>)}</div></div>}
function PopupPanel({popup,patchPopup}){return <div className={w.panelInner}><header><small>POPUPS</small><h3>Promoción destacada</h3><p>Mostrá un mensaje elegante sin tapar la experiencia del huésped.</p></header><Switch checked={popup.enabled} onChange={enabled=>patchPopup({enabled})} label="Activar popup" help="Aparece una sola vez después del tiempo configurado."/><Field label="Título"><input value={popup.title||""} onChange={e=>patchPopup({title:e.target.value})} placeholder="Reservá directo y obtené un beneficio"/></Field><Field label="Mensaje"><textarea rows="4" value={popup.text||""} onChange={e=>patchPopup({text:e.target.value})}/></Field><Field label="Botón"><input value={popup.cta_label||"Reservar ahora"} onChange={e=>patchPopup({cta_label:e.target.value})}/></Field><Field label="Mostrar después de"><select value={popup.delay_seconds||5} onChange={e=>patchPopup({delay_seconds:Number(e.target.value)})}><option value="0">Inmediatamente</option><option value="3">3 segundos</option><option value="5">5 segundos</option><option value="10">10 segundos</option></select></Field></div>}
function StylesPanel({draft,patchDraft,studio,patchTheme}){return <div className={w.panelInner}><header><small>ESTILOS</small><h3>Dirección visual</h3><p>Cada base cambia composición, tipografía, proporciones y tratamiento fotográfico; no sólo el color.</p></header><div className={w.templateList}>{templates.map(item=><button key={item.id} className={draft?.template===item.id?w.templateOn:""} onClick={()=>patchDraft({template:item.id})}><span data-template={item.id}><i/><i/><i/><i/></span><div><b>{item.name}</b><small>{item.help}</small><em>{item.font}</em></div>{draft?.template===item.id?<strong>✓</strong>:null}</button>)}</div><div className={w.styleFields}><Field label="Tipografía de títulos"><select value={studio.theme.heading_font} onChange={e=>patchTheme({heading_font:e.target.value})}>{FONT_OPTIONS.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Field><Field label="Tipografía de texto"><select value={studio.theme.body_font} onChange={e=>patchTheme({body_font:e.target.value})}>{FONT_OPTIONS.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Field><Field label="Forma"><select value={studio.theme.radius} onChange={e=>patchTheme({radius:e.target.value})}><option value="square">Recta</option><option value="soft">Suave</option><option value="round">Muy redondeada</option></select></Field><Field label="Navegación"><select value={studio.theme.nav_style} onChange={e=>patchTheme({nav_style:e.target.value})}><option value="glass">Vidrio</option><option value="solid">Sólida</option><option value="overlay">Sobre la foto</option></select></Field><Field label="Buscador"><select value={studio.theme.search_style} onChange={e=>patchTheme({search_style:e.target.value})}><option value="floating">Flotante</option><option value="bar">Barra completa</option><option value="compact">Píldora</option></select></Field><Field label="Fotografía"><select value={studio.theme.image_tone} onChange={e=>patchTheme({image_tone:e.target.value})}><option value="natural">Natural</option><option value="warm">Cálida</option><option value="cool">Fría</option><option value="mono">Monocromo</option></select></Field><div className={w.colors}><label><span>Principal</span><input type="color" value={draft?.primary_color||"#5B5CEB"} onChange={e=>patchDraft({primary_color:e.target.value})}/></label><label><span>Acento</span><input type="color" value={draft?.accent_color||"#9B8CFF"} onChange={e=>patchDraft({accent_color:e.target.value})}/></label></div></div></div>}
function Field({label,children}){return <label className={w.field}><span>{label}</span>{children}</label>}
