import{NextResponse}from"next/server"
import{createClient}from"@supabase/supabase-js"

const KINDS=new Set(["towels","pillows","cleaning","maintenance","late_checkout","other"])
const clean=v=>String(v||"").trim()
const norm=v=>clean(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()
const schema={type:"object",additionalProperties:false,required:["answer","action"],properties:{answer:{type:"string"},action:{anyOf:[{type:"null"},{type:"object",additionalProperties:false,required:["kind","detail"],properties:{kind:{type:"string",enum:["towels","pillows","cleaning","maintenance","late_checkout","other"]},detail:{type:"string"}}}]}}}
function memoryIntent(q,memory=[]){for(const row of memory){if(row?.phrase&&q.includes(norm(row.phrase))&&KINDS.has(row.intent))return row.intent}return null}
function localAction(question,ctx){const q=norm(question),learned=memoryIntent(q,ctx.memory);if(learned)return{kind:learned,detail:question};if(/(toalla|toallon|toallones)/.test(q))return{kind:"towels",detail:question};if(/(almohad|pillow)/.test(q))return{kind:"pillows",detail:question};if(/(limpi|mucama|housekeeping|hkp|hacer la habitacion|ordenar la habitacion)/.test(q))return{kind:"cleaning",detail:question};if(/(aire|tele|tv|cerradura|caja fuerte|agua|ducha|inodoro|luz|electric|wifi no|calefaccion|heladera|fuga|pierde|gotea|roto|rota|no funciona|no anda)/.test(q))return{kind:"maintenance",detail:question};if(/(late|salir mas tarde|quedarme hasta|checkout mas tarde|check out mas tarde)/.test(q))return{kind:"late_checkout",detail:question};return null}
function localInfo(question,ctx){const q=norm(question),g=ctx.guide||{},s=ctx.stay||{};if(/wifi|wi fi|clave|contrasena|internet/.test(q))return g.wifi_name?`La red Wi‑Fi es ${g.wifi_name}${g.wifi_password?` y la clave es ${g.wifi_password}`:""}.`:"La información de Wi‑Fi todavía no está cargada. Podés consultarla con Recepción.";if(/check.?out|salida|a que hora.*(irme|salir)/.test(q))return`Tu horario de salida es ${g.checkout_time||"el informado por Recepción"}.`;if(/check.?in|entrada/.test(q))return`El horario habitual de check-in es ${g.checkin_time||"el informado por Recepción"}.`;if(/habitacion|cuarto|room/.test(q))return`Estás alojado en la habitación ${s.room||"asignada"}.`;const sections=Array.isArray(g.sections)?g.sections:[];for(const item of sections){const hay=norm(`${item?.title||""} ${item?.description||""}`);if(hay&&hay.split(" ").some(w=>w.length>4&&q.includes(w)))return`${item.title||"Información del hotel"}: ${item.description||""}`.trim()}return null}

export async function POST(request){try{const body=await request.json().catch(()=>null),token=clean(body?.token),question=clean(body?.question),history=Array.isArray(body?.history)?body.history.slice(-8):[];if(token.length<32||question.length<2)return NextResponse.json({error:"Solicitud inválida."},{status:400});if(question.length>1200)return NextResponse.json({error:"Mensaje demasiado largo."},{status:413});const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return NextResponse.json({error:"Configuración incompleta."},{status:500});const client=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),{data:ctx,error}=await client.rpc("hl_guest_stay_portal_ai_context",{p_token:token});if(error||!ctx?.ok)return NextResponse.json({error:ctx?.error||"Portal no disponible."},{status:403});if(ctx?.guide?.guest_ai_config?.enabled===false)return NextResponse.json({answer:"El asistente del huésped está desactivado para este hotel.",action:null});client.rpc("hl_guest_stay_portal_track",{p_token:token,p_event:"assistant_question",p_meta:{length:question.length}}).catch(()=>{});const action=localAction(question,ctx),info=localInfo(question,ctx);if(action&&!/^(como|cómo|que|qué|puedo|se puede|donde|dónde)\b/.test(norm(question)))return NextResponse.json({answer:`Sí, entendí. Puedo preparar ese pedido para ${action.kind==="maintenance"?"Mantenimiento":action.kind==="late_checkout"||action.kind==="other"?"Recepción":"Housekeeping"}. Confirmalo y lo envío asociado a tu habitación.`,action});if(info)return NextResponse.json({answer:info,action:null});const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return NextResponse.json({answer:"Puedo ayudarte con información del hotel, tu estadía o preparar un pedido. Escribime como te salga.",action:null});const safe={hotel:ctx.hotel,guest:{name:ctx.guest?.name},stay:ctx.stay,guide:{welcome_message:ctx.guide?.welcome_message,wifi_name:ctx.guide?.wifi_name,wifi_password:ctx.guide?.wifi_password,checkin_time:ctx.guide?.checkin_time,checkout_time:ctx.guide?.checkout_time,sections:ctx.guide?.sections,house_rules:ctx.guide?.house_rules,nearby_places:ctx.guide?.nearby_places,enabled_actions:ctx.guide?.enabled_actions,room_service_config:ctx.guide?.room_service_config},memory:ctx.memory};const prompt=`Sos OlivIA, asistente del huésped de ${ctx.hotel?.name||"un hotel"}. Hablás con el huésped actual, no con personal del PMS. Respondé humano, breve, cálido y en el idioma del mensaje.

REGLAS
- Sólo conocés ESTA estadía y ESTE hotel. Nunca inventes ni menciones otros huéspedes, habitaciones o reservas.
- Usá la información validada del hotel para Wi-Fi, horarios, guía, lugares y servicios.
- Si el huésped expresa una necesidad operativa concreta, podés PROPONER una acción; jamás ejecutarla. El huésped debe confirmar en la interfaz.
- towels/pillows/cleaning van a Housekeeping; fallas/roturas a maintenance; late_checkout y other a Recepción.
- Un late check-out siempre requiere aprobación posterior de Recepción.
- Si es sólo una pregunta, action=null.
- La memoria incluida es vocabulario aprendido únicamente para este hotel; usala para comprender expresiones locales, nunca fuera de este tenant.

CONTEXTO SEGURO:${JSON.stringify(safe)}
HISTORIAL:${JSON.stringify(history)}
MENSAJE:${question}`;const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:"gpt-5.6-luna",input:prompt,max_output_tokens:650,text:{format:{type:"json_schema",name:"guest_olivia_response",strict:true,schema}}})}),data=await response.json();if(!response.ok)return NextResponse.json({answer:"Puedo ayudarte con información del hotel o preparar un pedido. Si querés, escribime de otra manera.",action:null});let parsed={};try{parsed=JSON.parse(data.output_text||"{}")}catch{};const parsedAction=parsed?.action&&KINDS.has(parsed.action.kind)?{kind:parsed.action.kind,detail:clean(parsed.action.detail).slice(0,1000)}:null;return NextResponse.json({answer:clean(parsed?.answer)||"Decime qué necesitás y te ayudo.",action:parsedAction})}catch(error){console.error("Guest assistant error",error);return NextResponse.json({error:"No se pudo procesar la consulta."},{status:500})}}
