"use client"

import{useEffect,useRef,useState}from"react"
import{filterNavForRole,HOUSEKEEPING_NAV,INTEGRATIONS_NAV,MANAGEMENT_NAV,OPERATIONS_NAV,PRIMARY_NAV,RECEPTION_NAV}from"../../core/navigation"
import SidebarSubscriptionCard from"./SidebarSubscriptionCard"
import s from"../../pms-next.module.css"
import brand from"./pmsSidebarBrand.module.css"
import glass from"./pmsGlassShell.module.css"
import collapse from"./pmsSidebarCollapse.module.css"
import PmsIcon from"./PmsIcons"

const ROLE_LABELS={owner:"Propietario",admin:"Administrador",manager:"Gerencia",reception:"Recepción",night_audit:"Auditoría nocturna",housekeeping:"Housekeeping",maintenance:"Mantenimiento",revenue:"Revenue",member:"Equipo"}
const PROPERTY_CARD_STYLE={gridTemplateColumns:"28px minmax(0,1fr)"}
const PROPERTY_SELECT_STYLE={gridColumn:"1 / -1",width:"100%",maxWidth:"100%",minWidth:0,height:32,border:"1px solid var(--line)",borderRadius:9,background:"color-mix(in srgb,var(--panelSolid) 62%,transparent)",backdropFilter:"blur(16px) saturate(1.35)",color:"var(--text)",padding:"0 8px",outline:"none"}
const PROPERTY_LOCK_STYLE={gridColumn:"2",justifySelf:"end"}
const NAV_COLORS={dashboard:"#5b6cf3",planning:"#2797ff",reservations:"#8a63e8",quotes:"#d79a31",guests:"#ed6b8f",messages:"#20ad7a",tasks:"#ea7a37",requests:"#e65d68",housekeeping:"#21a8a0",maintenance:"#e09533",inventory:"#597fda",services:"#b268dc",dailycash:"#2a9b64",receptionreports:"#7c68d8",rates:"#4b9c72",finance:"#2a9b64",onboarding:"#6181dc",website:"#5d8ee7",growth:"#45a16f",revenue:"#5d9c76",channelmanager:"#5966dc",reports:"#7c68d8",audit:"#596f9d",staff:"#dd718f",integrations:"#557ed1",integrationapi:"#6d69d8",integrationmessages:"#20ad7a",integrationpayments:"#2a9b64",settings:"#7a8497",support:"#20a18f"}
const BUSINESS_NAV_IDS=new Set(["finance","revenue","growth","intelligence","reports"])
const FOLDER_STYLE={display:"grid",gap:3,marginBottom:4}
const FOLDER_BUTTON_STYLE={width:"100%",height:36,border:"1px solid color-mix(in srgb,#fff 26%,var(--line))",borderRadius:11,display:"grid",gridTemplateColumns:"26px minmax(0,1fr) 16px",alignItems:"center",gap:8,padding:"0 8px",background:"color-mix(in srgb,var(--panelSolid) 45%,transparent)",textAlign:"left",fontSize:10,fontWeight:850,cursor:"pointer",boxShadow:"inset 0 1px color-mix(in srgb,#fff 42%,transparent)"}
const SUBNAV_STYLE={display:"grid",gap:2,margin:"1px 0 4px 18px",paddingLeft:8,borderLeft:"1px solid color-mix(in srgb,var(--accent) 18%,var(--line))"}
const BADGE_STYLE={minWidth:18,height:18,padding:"0 5px",borderRadius:999,display:"inline-grid",placeItems:"center",background:"#e5484d",color:"#fff",fontSize:10,fontWeight:950,lineHeight:1,boxShadow:"0 3px 10px rgba(229,72,77,.28)",fontStyle:"normal"}
const COLLAPSE_KEY="hl:pms:sidebar-collapsed"
function LabelWithBadge({label,badge}){return <span style={{minWidth:0,display:"flex",alignItems:"center",justifyContent:"space-between",gap:6}}><span style={{overflow:"hidden",textOverflow:"ellipsis"}}>{label}</span>{Number(badge)>0?<em style={BADGE_STYLE}>{Number(badge)>99?"99+":Number(badge)}</em>:null}</span>}
function NavButton({item,active,onView,badge=0,compact=false,onTooltip}){const show=e=>{if(compact)onTooltip?.(item.label,e.currentTarget)},hide=()=>{if(compact)onTooltip?.()};return <button type="button" aria-label={compact?item.label:undefined} style={{"--nav-icon":NAV_COLORS[item.id]||"var(--accent)"}} className={`${s.navItem} ${compact?collapse.navItemCompact:""} ${glass.navItemGlass} ${active?`${s.navItemActive} ${glass.navItemGlassActive}`:""}`} onMouseEnter={show} onMouseLeave={hide} onFocus={show} onBlur={hide} onClick={()=>{hide();onView(item.id)}}><span className={glass.navIcon}><PmsIcon name={item.icon} size={15}/></span>{compact?Number(badge)>0?<em className={collapse.compactNavBadge}>{Number(badge)>99?"99+":Number(badge)}</em>:null:<LabelWithBadge label={item.label} badge={badge}/>}</button>}
function NavGroup({title,items,view,onView,badges={},compact=false,onTooltip}){if(!items.length)return null;return <section className={`${s.navGroup} ${compact?collapse.navGroupCompact:""}`}>{title&&!compact&&<small className={s.navLabel}>{title}</small>}{items.map(item=><NavButton key={item.id} item={item} active={view===item.id} onView={onView} badge={badges[item.id]} compact={compact} onTooltip={onTooltip}/>)}</section>}
function NavFolder({label,icon,color,items,view,onView,defaultOpen=false,badges={}}){
  const active=items.some(item=>item.id===view),[open,setOpen]=useState(defaultOpen||active)
  useEffect(()=>{if(active)setOpen(true)},[active])
  if(!items.length)return null
  return <div style={FOLDER_STYLE}><button type="button" style={{...FOLDER_BUTTON_STYLE,"--nav-icon":color}} onClick={()=>setOpen(value=>!value)} aria-expanded={open}><span className={glass.navIcon}><PmsIcon name={icon} size={15}/></span><span>{label}</span><span style={{fontSize:11,color:"var(--muted)",transform:open?"rotate(90deg)":"none",transition:"transform .15s ease"}}>›</span></button>{open?<div style={SUBNAV_STYLE}>{items.map(item=>{const selected=view===item.id;return <button key={item.id} type="button" style={{"--nav-icon":NAV_COLORS[item.id]||color,height:32,minHeight:32}} className={`${s.navItem} ${glass.navItemGlass} ${selected?`${s.navItemActive} ${glass.navItemGlassActive}`:""}`} onClick={()=>onView(item.id)}><span className={glass.navIcon} style={{width:22,height:22,borderRadius:7}}><PmsIcon name={item.icon} size={13}/></span><LabelWithBadge label={item.label} badge={badges[item.id]}/></button>})}</div>:null}</div>
}

export default function PmsSidebar({view,onView,property,properties=[],onProperty,user,featureFlags={},rolePermissions={},buildId="local",badges={}}){
  const propertyName=property?.name||"Seleccionar propiedad",role=property?.role||"member",primary=filterNavForRole(PRIMARY_NAV,role,featureFlags,rolePermissions),reception=filterNavForRole(RECEPTION_NAV,role,featureFlags,rolePermissions),housekeeping=filterNavForRole(HOUSEKEEPING_NAV,role,featureFlags,rolePermissions),operations=filterNavForRole(OPERATIONS_NAV,role,featureFlags,rolePermissions),management=filterNavForRole(MANAGEMENT_NAV,role,featureFlags,rolePermissions),integrations=filterNavForRole(INTEGRATIONS_NAV,role,featureFlags,rolePermissions),version=buildId&&buildId!=="local"?buildId.slice(0,7):"local",roleLabel=ROLE_LABELS[role]||"Equipo"
  const business=management.filter(item=>BUSINESS_NAV_IDS.has(item.id)),managementCore=management.filter(item=>!BUSINESS_NAV_IDS.has(item.id))
  const sidebarRef=useRef(null),[collapsed,setCollapsed]=useState(false),[collapseReady,setCollapseReady]=useState(false),[narrow,setNarrow]=useState(false),[tooltip,setTooltip]=useState(null)
  useEffect(()=>{try{setCollapsed(window.localStorage.getItem(COLLAPSE_KEY)==="1")}catch{}setCollapseReady(true)},[])
  useEffect(()=>{if(typeof window==="undefined")return;const media=window.matchMedia("(max-width:900px) and (min-width:641px)"),sync=()=>setNarrow(media.matches);sync();media.addEventListener?.("change",sync);return()=>media.removeEventListener?.("change",sync)},[])
  useEffect(()=>{if(!collapseReady)return;try{window.localStorage.setItem(COLLAPSE_KEY,collapsed?"1":"0")}catch{}const root=sidebarRef.current?.parentElement;if(root)root.dataset.sidebar=collapsed?"collapsed":"expanded"},[collapsed,collapseReady])
  const compact=collapsed||narrow,operationalCompact=[...reception,...housekeeping,...operations],managementCompact=[...management,...integrations]
  useEffect(()=>{if(!compact)setTooltip(null)},[compact])
  function showTooltip(label,node){if(!label||!node){setTooltip(null);return}const rect=node.getBoundingClientRect(),side=sidebarRef.current?.getBoundingClientRect();setTooltip({label,left:Math.round((side?.right||rect.right)+9),top:Math.round(rect.top+rect.height/2)})}
  return <aside ref={sidebarRef} className={`${s.sidebar} ${glass.sidebarGlass}`}>
    <div className={`${s.brandBlock} ${compact?collapse.brandBlockCompact:""}`}><div className={collapse.brandTop}><button className={s.brandButton} type="button" title={compact?"HabitacionLlena.com":undefined} onClick={()=>onView("dashboard")}>{compact?<span className={s.brandMark}>HL</span>:<span className={brand.brandName}>HabitacionLlena.com</span>}</button>{!narrow?<button type="button" className={collapse.sidebarCollapse} onClick={()=>setCollapsed(value=>!value)} title={collapsed?"Expandir menú":"Compactar menú"} aria-label={collapsed?"Expandir menú lateral":"Compactar menú lateral"}>{collapsed?"›":"‹"}</button>:null}</div><div className={`${s.propertyCard} ${compact?collapse.propertyCardCompact:""}`} style={compact?undefined:PROPERTY_CARD_STYLE} title={compact?`${propertyName} · ${roleLabel}`:undefined}><span className={s.propertyAvatar}>{propertyName.slice(0,1).toUpperCase()}</span>{!compact?<><label style={{minWidth:0}}><b>{propertyName}</b><small>{property?.city||"Propiedad activa"} · {roleLabel}</small></label>{properties.length>1?<select style={PROPERTY_SELECT_STYLE} aria-label="Cambiar propiedad" value={property?.id||""} onChange={e=>onProperty?.(e.target.value)}>{properties.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>:<span className={s.propertyLock} style={PROPERTY_LOCK_STYLE}>✓</span>}</>:null}</div></div>
    <nav className={`${s.navScroll} ${compact?collapse.navScrollCompact:""}`}>{compact?<><NavGroup items={primary} view={view} onView={onView} badges={badges} compact onTooltip={showTooltip}/><NavGroup items={operationalCompact} view={view} onView={onView} badges={badges} compact onTooltip={showTooltip}/><NavGroup items={managementCompact} view={view} onView={onView} badges={badges} compact onTooltip={showTooltip}/></>:<><NavGroup items={primary} view={view} onView={onView} badges={badges}/><section className={s.navGroup}><small className={s.navLabel}>Operación</small><NavFolder label="Recepción" icon="booking" color="#4b5fd5" items={reception} view={view} onView={onView} badges={badges}/>{housekeeping.map(item=><NavButton key={item.id} item={item} active={view===item.id} onView={onView} badge={badges[item.id]}/>)}{operations.map(item=><NavButton key={item.id} item={item} active={view===item.id} onView={onView} badge={badges[item.id]}/>)}</section><NavGroup title="Finanzas y rendimiento" items={business} view={view} onView={onView} badges={badges}/><section className={s.navGroup}><small className={s.navLabel}>Gestión</small>{managementCore.map(item=><NavButton key={item.id} item={item} active={view===item.id} onView={onView} badge={badges[item.id]}/>) }<NavFolder label="Integraciones" icon="link" color="#557ed1" items={integrations} view={view} onView={onView} badges={badges}/></section></>}</nav>
    {!compact?<div style={{display:"grid",gap:8,padding:"0 10px 8px"}}>{["owner","manager","admin"].includes(role)?<SidebarSubscriptionCard propertyId={property?.id} onManage={()=>onView("subscription")}/>:null}</div>:null}
    <div className={`${s.sidebarFooter} ${compact?collapse.sidebarFooterCompact:""}`}>{!compact?<span><b>{user?.email||"Usuario autenticado"}</b><small>{roleLabel} · v{version}</small></span>:null}{management.some(item=>item.id==="settings")&&<button type="button" aria-label="Configuración" onMouseEnter={compact?e=>showTooltip("Configuración",e.currentTarget):undefined} onMouseLeave={compact?()=>showTooltip():undefined} onFocus={compact?e=>showTooltip("Configuración",e.currentTarget):undefined} onBlur={compact?()=>showTooltip():undefined} title={!compact?`Configuración · versión ${version}`:undefined} onClick={()=>{showTooltip();onView("settings")}}>•••</button>}</div>
    {compact&&tooltip?<div className={collapse.instantTooltip} style={{left:tooltip.left,top:tooltip.top}} role="tooltip">{tooltip.label}</div>:null}
  </aside>
}