"use client"

import{useEffect,useMemo,useState}from"react"
import s from"./bookingEngine.module.css"

const dateKey=date=>{const d=new Date(date);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
const addDays=(value,n)=>{const d=new Date(`${value}T12:00:00`);d.setDate(d.getDate()+n);return dateKey(d)}
const nights=(a,b)=>a&&b?Math.max(0,Math.round((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/86400000)):0
const makeRequestId=()=>globalThis.crypto?.randomUUID?.()||`hl-${Date.now()}-${Math.random().toString(36).slice(2)}`
const BED_OPTIONS=[{value:"",label:"Sin preferencia"},{value:"matrimonial",label:"1 cama matrimonial"},{value:"twin",label:"2 camas twin"},{value:"individual",label:"1 cama individual"},{value:"matrimonial_twin",label:"1 matrimonial + 1 twin"},{value:"triple_twin",label:"3 camas twin"}]
const bedLabel=value=>BED_OPTIONS.find(item=>item.value===value)?.label||value||"Sin preferencia"

export default function BookingEngine({slug,embedded=false}){
  const today=dateKey(new Date()),[engine,setEngine]=useState(null),[step,setStep]=useState("search"),[rooms,setRooms]=useState([]),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState(null),[requestId,setRequestId]=useState(""),[accepted,setAccepted]=useState(false)
  const[form,setForm]=useState({checkIn:today,checkOut:addDays(today,1),guests:2,name:"",email:"",phone:"",bedType:""})
  const stayNights=useMemo(()=>nights(form.checkIn,form.checkOut),[form.checkIn,form.checkOut]),currency=engine?.currency||"ARS",money=value=>new Intl.NumberFormat("es-AR",{style:"currency",currency,maximumFractionDigits:0}).format(Number(value)||0)
  useEffect(()=>{let active=true;fetch(`/api/public/booking/${encodeURIComponent(slug)}/config`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);if(active)setEngine(j.engine)}).catch(e=>active&&setError(e.message||"Motor no disponible."));return()=>{active=false}},[slug])
  async function search(){setError("");setRequestId("");if(stayNights<1)return setError("La salida tiene que ser posterior a la entrada.");setBusy(true);try{const qs=new URLSearchParams({check_in:form.checkIn,check_out:form.checkOut,guests:String(form.guests),bed_type:form.bedType}),r=await fetch(`/api/public/booking/${encodeURIComponent(slug)}/availability?${qs}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error);setRooms(j.rooms||[]);setStep("rooms")}catch(e){setError(e.message||"No se pudo consultar disponibilidad.")}finally{setBusy(false)}}
  async function confirm(event){event.preventDefault();if(!selected||!accepted)return;setError("");setBusy(true);let key=requestId;if(!key){key=makeRequestId();setRequestId(key)}try{const r=await fetch(`/api/public/booking/${encodeURIComponent(slug)}/book`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({check_in:form.checkIn,check_out:form.checkOut,guests:Number(form.guests),name:form.name,email:form.email,phone:form.phone,bed_type:form.bedType,room_type:selected.type,request_id:key})}),j=await r.json();if(!r.ok)throw new Error(j.error);setResult(j);setStep("success")}catch(e){setError(e.message||"No se pudo confirmar la reserva.")}finally{setBusy(false)}}
  const colors={"--engine-primary":engine?.primary_color||"#5B5CEB","--engine-accent":engine?.accent_color||"#7C5CFC"},selectedTotal=Number(selected?.total??(Number(selected?.price||0)*stayNights))
  const paymentText=engine?.payment_mode==="deposit"?`Seña requerida: ${Number(engine.deposit_percent||0)}%`:engine?.payment_mode==="full"?"Pago total requerido":"Pago según condiciones del hotel"
  if(!engine&&!error)return <main className={`${s.shell} ${embedded?s.embedded:""}`}><div className={s.loading}>Cargando disponibilidad…</div></main>
  if(!engine)return <main className={`${s.shell} ${embedded?s.embedded:""}`}><div className={s.errorCard}>{error}</div></main>
  return <main className={`${s.shell} ${embedded?s.embedded:""}`} style={colors}>
    <section className={s.card}>
      <header className={s.header}><div className={s.brand}>{engine.logo_url?<img src={engine.logo_url} alt=""/>:<span>{String(engine.name||"H")[0]}</span>}<div><small>RESERVA DIRECTA</small><h1>{engine.name}</h1></div></div>{!embedded?<a href={`/book/${slug}`} className={s.secure}>Reserva segura · HL</a>:<span className={s.secure}>Motor Habitación Llena</span>}</header>
      {engine.hero_url&&step==="search"?<div style={{height:180,overflow:"hidden"}}><img src={engine.hero_url} alt={engine.name} style={{width:"100%",height:"100%",objectFit:"cover"}}/></div>:null}
      {step==="search"&&<div className={s.body}><div className={s.lead}><h2>Encontrá tu habitación</h2><p>{engine.booking_message||"Consultá disponibilidad y reservá directamente con el hotel."}</p></div><div className={s.searchGrid}><label>Entrada<input type="date" min={today} value={form.checkIn} onChange={e=>setForm(v=>({...v,checkIn:e.target.value,checkOut:v.checkOut<=e.target.value?addDays(e.target.value,1):v.checkOut}))}/></label><label>Salida<input type="date" min={addDays(form.checkIn,1)} value={form.checkOut} onChange={e=>setForm(v=>({...v,checkOut:e.target.value}))}/></label><label>Huéspedes<input type="number" min="1" max="20" value={form.guests} onChange={e=>setForm(v=>({...v,guests:Math.max(1,Number(e.target.value)||1)}))}/></label><label>Cama<select value={form.bedType} onChange={e=>setForm(v=>({...v,bedType:e.target.value}))}>{BED_OPTIONS.map(option=><option key={option.value||"any"} value={option.value}>{option.label}</option>)}</select></label><button onClick={search} disabled={busy}>{busy?"Buscando…":"Buscar"}</button></div></div>}
      {step==="rooms"&&<div className={s.body}><div className={s.subhead}><div><small>{form.checkIn} → {form.checkOut}{form.bedType?` · ${bedLabel(form.bedType)}`:""}</small><h2>{rooms.length?"Opciones disponibles":"Sin disponibilidad"}</h2></div><button className={s.textButton} onClick={()=>setStep("search")}>Cambiar búsqueda</button></div><div className={s.rooms}>{rooms.map(room=><button key={room.key||room.type} className={s.room} onClick={()=>{setSelected(room);setRequestId("");setAccepted(false);setStep("guest")}}><div><small>TIPO DE HABITACIÓN</small><h3>{room.type||"Habitación"}</h3>{room.description?<p>{room.description}</p>:null}<span>Hasta {room.capacity||1} huésped{Number(room.capacity||1)===1?"":"es"}{Number(room.available_count)>0?` · ${room.available_count} disponible${Number(room.available_count)===1?"":"s"}`:""}</span>{form.bedType?<span style={{display:"block",marginTop:4,fontWeight:700}}>Preferencia: {bedLabel(form.bedType)}</span>:<span style={{display:"block",marginTop:4,fontWeight:700}}>Podés elegir la configuración de cama</span>}</div><strong>{money(room.total??Number(room.price||0)*stayNights)}<small>{stayNights} noche{stayNights===1?"":"s"} · {money(room.price)}/noche prom.</small></strong></button>)}{!rooms.length?<div className={s.empty}>Probá otras fechas o consultá directamente con el hotel.</div>:null}</div></div>}
      {step==="guest"&&selected?<form className={s.body} onSubmit={confirm}><div className={s.summary}><div><small>{selected.type||"Habitación"}</small><b>{form.checkIn} → {form.checkOut}</b><span>{stayNights} noche{stayNights===1?"":"s"} · {form.guests} huésped{Number(form.guests)===1?"":"es"} · {bedLabel(form.bedType)}</span></div><strong>{money(selectedTotal)}</strong></div><div className={s.guestGrid}><label>Nombre y apellido<input required autoFocus value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} placeholder="Nombre del titular"/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))} placeholder="tu@email.com"/></label><label>Teléfono<input value={form.phone} onChange={e=>setForm(v=>({...v,phone:e.target.value}))} placeholder="+54 9…"/></label><label>Huéspedes<input type="number" min="1" max={selected.capacity||20} value={form.guests} onChange={e=>setForm(v=>({...v,guests:Math.max(1,Number(e.target.value)||1)}))}/></label><label style={{gridColumn:"1 / -1"}}>Configuración de cama<select value={form.bedType} onChange={e=>setForm(v=>({...v,bedType:e.target.value}))}>{BED_OPTIONS.map(option=><option key={option.value||"any"} value={option.value}>{option.label}</option>)}</select></label></div><div style={{marginTop:16,padding:14,border:"1px solid #e4e7ec",borderRadius:12,fontSize:12,lineHeight:1.55}}><b>{paymentText}</b>{engine.cancellation_policy?<p style={{margin:"6px 0 0"}}>{engine.cancellation_policy}</p>:null}<label style={{display:"flex",gap:8,alignItems:"flex-start",marginTop:10}}><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} style={{marginTop:2}}/><span>Acepto las condiciones de la reserva{engine.terms_url?<a href={engine.terms_url} target="_blank" rel="noreferrer"> · Términos</a>:null}{engine.privacy_url?<a href={engine.privacy_url} target="_blank" rel="noreferrer"> · Privacidad</a>:null}</span></label></div><div className={s.actions}><button type="button" className={s.back} onClick={()=>setStep("rooms")}>Volver</button><button type="submit" className={s.primary} disabled={busy||!accepted}>{busy?"Confirmando…":"Confirmar reserva"}</button></div></form>:null}
      {step==="success"&&result?<div className={`${s.body} ${s.success}`}><span className={s.check}>✓</span><small>RESERVA CONFIRMADA</small><h2>¡Listo, {form.name.split(" ")[0]||""}!</h2><p>{engine.confirmation_message||"Tu reserva quedó registrada directamente en el hotel."}</p><div className={s.confirmBox}><span>Número de reserva</span><b>{result.numero_reserva||result.id}</b><small>{result.room_type} · {bedLabel(result.bed_type||form.bedType)} · {result.check_in} → {result.check_out}</small><strong>{money(result.total)}</strong></div>{result.manage_token?<a href={`/book/${slug}/manage/${result.manage_token}`} style={{display:"inline-flex",alignItems:"center",justifyContent:"center",minHeight:42,padding:"0 16px",marginTop:14,borderRadius:11,background:"#182033",color:"#fff",fontSize:12,fontWeight:850,textDecoration:"none"}}>Ver y gestionar mi reserva</a>:null}{engine.payment_mode!=="at_property"?<p style={{fontSize:12,opacity:.75}}>La reserva quedó registrada. El cobro online se habilita cuando la propiedad conecta su pasarela de pago.</p>:null}</div>:null}
      {error?<div className={s.error}>{error}</div>:null}
      <footer className={s.footer}><span>Disponibilidad en tiempo real</span><span>Operado con Habitación Llena</span></footer>
    </section>
  </main>
}